feat: [SRM-10986]: Splunk Health Source template
harness/harness-core-ui pull request #10005
Opened 2022-07-14 04:06 UTC by deepesh-ui

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-15 06:46 UTC, praneshg239 submitted a review, later dismissed

2022-07-16 20:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10005) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10005) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10005) it.</sub>

2022-07-19 09:52 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/connectors/SplunkHealthSource/components/MapQueriesToHarnessService/SplunkQueryBuilder.tsx
> +            [
This can be moved to utils.

2022-07-19 09:53 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/SplunkHealthSource/components/MapQueriesToHarnessService/SplunkQueryBuilder.tsx
> +            [
done

2022-07-19 09:56 UTC, harshilbits requested changes

2022-07-19 09:56 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/connectors/SplunkHealthSource/components/MapQueriesToHarnessService/SplunkQueryBuilder.tsx
> +              getString('cv.monitoringSources.splunk.splunkLogsQuery'),
Please verify again

2022-07-22 08:13 UTC, praneshg239 approved these changes

2022-07-25 04:26 UTC, harshilbits requested changes

2022-07-25 04:26 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/connectors/SplunkHealthSource/components/MapQueriesToHarnessService/SplunkQueryBuilder.tsx
>          ? sourceData?.mappedServicesAndEnvs
Please move this to utils

2022-07-25 05:00 UTC, praneshg239 approved these changes

2022-07-25 05:03 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/connectors/SplunkHealthSource/components/MapQueriesToHarnessService/SplunkQueryBuilder.tsx
> +  }>(getSplunkMappedMetric({ sourceData, isConnectorRuntimeOrExpression, getString }))
Lets lazy initialise this.

2022-07-25 05:05 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/SplunkHealthSource/components/MapQueriesToHarnessService/SplunkQueryBuilder.tsx
> +  }>(getSplunkMappedMetric({ sourceData, isConnectorRuntimeOrExpression, getString }))
correct me if i am wrong , but this is already a function .so will act initialise lazy.

2022-07-25 05:16 UTC, deepesh-ui commented
retrigger jest

2022-07-25 05:24 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/connectors/SplunkHealthSource/components/MapQueriesToHarnessService/SplunkQueryBuilder.tsx
> +  }>(getSplunkMappedMetric({ sourceData, isConnectorRuntimeOrExpression, getString }))
correct !

2022-07-25 05:27 UTC, harshilbits approved these changes

2022-07-25 05:31 UTC, merged