feat: [CDS-37893]:ssh-winrm-services
harness/harness-core-ui pull request #10050
Opened 2022-07-17 17:00 UTC by litvinovstas

### Summary

[](https://harness.atlassian.net/browse/CDS-37893)

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-17 17:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10050) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10050) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10050) it.</sub>

2022-07-19 07:00 UTC, bhavya-sinha commented on src/modules/31-filestore/common/useNewNodeModal/views/NewFileModalForm.tsx
> +        // fileUsage: Yup.string().nullable(true).trim().required(getString('filestore.errors.fileUsage'))
Commented?

2022-07-19 07:00 UTC, bhavya-sinha commented on src/modules/31-filestore/common/useNewNodeModal/views/NewFileModalForm.tsx
>                    style={{ width: 180 }}
Inline style?

2022-07-19 07:06 UTC, bhavya-sinha commented on src/modules/31-filestore/components/MultiTypeFileSelect/EncryptedSelect/EncryptedFileSelectField.tsx
> +  onChange: (newValue: any, id?: any) => void
id can be string | number

2022-07-19 07:06 UTC, bhavya-sinha commented on src/modules/31-filestore/components/StoreView/StoreView.tsx
> +      style={{
Inline style?

2022-07-19 07:09 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactListView/ArtifactListView.tsx
> +        {isAdditionAllowed && isSidecarAllowed && withSideCar && (
There was already a function `isSidecarAllowed` doing same thing. Check if you can use that

2022-07-19 07:11 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesHelper.ts
> +  }
All 4 above if conditions can be combined

2022-07-19 07:13 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesListView/ConfigFilesListView.tsx
> +    onConnectorCreated: () => {
We can use noop here

2022-07-19 07:14 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesListView/ConfigFilesListView.tsx
> +        listOfConfigFiles.splice(configFileIndex, 1, configFileObj)
Should not try to mutate props. Props are readonly

2022-07-19 07:15 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesListView/ConfigFilesListView.tsx
> +  }
There is exported func in `getBuildPayload` in ManifestHelper. You can try to use it here

2022-07-19 07:15 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesListView/ConfigFilesListView.tsx
> +    listOfConfigFiles.splice(index, 1)
props should be readonly

2022-07-19 07:16 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesListView/ConfigFilesListView.tsx
> +              listOfConfigFiles.map((data: ConfigFileWrapper, index: number) => {
Chaining can be used

2022-07-19 07:16 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesWizard/ConfigFilesSteps/ConfigFilesStore.tsx
> +}: // isNewFile
Please remove commented codes

2022-07-19 07:18 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesWizard/ConfigFilesWizard.tsx
> +        // selectedConfigFile={selectedConfigFile}
Remove commented code

2022-07-19 07:26 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/DeployServiceSpecifications.tsx
> +  } = context
Why this change?

2022-07-19 08:45 UTC, chetanvekariya-harness requested changes

2022-07-19 10:00 UTC, chetanvekariya-harness requested changes

2022-07-19 10:04 UTC, chetanvekariya-harness requested changes

2022-07-19 11:44 UTC, kapilkumawat86 commented on scripts/strings/yamlStringsCheck.mjs
> -    errors.push([
Is this change intended

2022-07-19 11:51 UTC, kapilkumawat86 commented
dockerize

2022-07-19 12:01 UTC, litvinovstas commented on scripts/strings/yamlStringsCheck.mjs
> -    errors.push([
hmm, i didn't modified this file.. don't understand why it's changed

2022-07-19 12:33 UTC, litvinovstas commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesListView/ConfigFilesListView.tsx
> +    switch (true) {
resolved

2022-07-19 12:33 UTC, litvinovstas commented on src/modules/31-filestore/components/FileStoreComponent/FileStoreComponent.tsx
> +      handleShowModal()
resolved

2022-07-19 12:33 UTC, litvinovstas commented on src/modules/31-filestore/common/useNewNodeModal/views/NewFileModalForm.tsx
> +        // fileUsage: Yup.string().nullable(true).trim().required(getString('filestore.errors.fileUsage'))
resolved

2022-07-19 12:33 UTC, litvinovstas commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/DeployServiceSpecifications.tsx
> +  } = context
resolved

2022-07-19 12:33 UTC, litvinovstas commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesWizard/ConfigFilesSteps/ConfigFilesStore.tsx
> +}: // isNewFile
resolved

2022-07-19 12:35 UTC, litvinovstas commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesListView/ConfigFilesListView.tsx
> +        listOfConfigFiles.splice(configFileIndex, 1, configFileObj)
resolve

2022-07-19 12:35 UTC, litvinovstas commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesHelper.ts
> +  }
resolved

2022-07-19 12:35 UTC, litvinovstas commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactsSelection.tsx
> +      withSideCar={!withoutSideCar(deploymentType)}
resolved

2022-07-19 12:35 UTC, litvinovstas commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactListView/ArtifactListView.tsx
> +        {isAdditionAllowed && isSidecarAllowed && withSideCar && (
resolved

2022-07-19 12:35 UTC, litvinovstas commented on src/modules/31-filestore/components/MultiTypeFileSelect/EncryptedSelect/EncryptedFileSelectField.tsx
> +  onChange: (newValue: any, id?: any) => void
resolved

2022-07-19 12:35 UTC, litvinovstas commented on src/modules/31-filestore/common/useNewNodeModal/views/NewFileModalForm.tsx
>                    style={{ width: 180 }}
resolved

2022-07-19 12:35 UTC, litvinovstas commented on src/modules/31-filestore/common/useNewNodeModal/views/NewFileModalForm.tsx
> +        // fileUsage: Yup.string().nullable(true).trim().required(getString('filestore.errors.fileUsage'))
resolved

2022-07-19 13:22 UTC, chetanvekariya-harness requested changes

2022-07-19 13:22 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/KubernetesServiceSpecInputSetMode.tsx
> +      {!!template?.configFiles?.length && (
Looks like this needs to be removed yet.

2022-07-19 14:30 UTC, chetanvekariya-harness approved these changes

2022-07-19 14:56 UTC, kapilkumawat86 approved these changes

2022-07-19 14:56 UTC, merged