feat: [PL-23871]: Pagination in switch account
harness/harness-core-ui pull request #10065
Opened 2022-07-18 08:42 UTC by avinashmadhwani02

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-18 08:42 UTC, avinashmadhwani02 commented
dockerize

2022-07-18 09:02 UTC, avinashmadhwani02 commented
dockerize

2022-07-22 04:35 UTC, abhinavrastogi-harness requested changes

2022-07-22 04:35 UTC, abhinavrastogi-harness commented on src/modules/10-common/modals/SwitchAccount/SwitchAccount.tsx
> +          <Container className={css.spinner}>
you can remove the container the `spinner` css. PageSpinner should already be taking full screen. 
if it's not, we can check the layout changes

2022-07-22 04:35 UTC, abhinavrastogi-harness commented on src/modules/10-common/modals/SwitchAccount/SwitchAccount.module.scss
> +.spinner {
this class should not be needed

2022-07-22 04:35 UTC, abhinavrastogi-harness commented on src/modules/10-common/modals/SwitchAccount/SwitchAccount.tsx
> +import { useGetCurrentUserInfo } from 'services/cd-ng'
currentUserInfo is already available in appstore context. why do need to make a new network call here?

2022-07-22 04:35 UTC, abhinavrastogi-harness commented on src/modules/10-common/modals/SwitchAccount/SwitchAccount.tsx
> +    if (userInfo?.data?.defaultAccountId !== currentUserInfo.defaultAccountId) {
why is this needed? let's discuss on a call

2022-07-22 09:23 UTC, abhinavrastogi-harness approved these changes

2022-07-22 09:32 UTC, amitsh14 approved these changes

2022-07-22 09:33 UTC, merged