feat:[BT-1543]:Add create versions, fix techdebt in scripts
harness/harness-core-ui pull request #10108
Opened 2022-07-19 17:08 UTC by mbatchelor

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-20 04:05 UTC, diptiman-adak requested changes

2022-07-20 04:05 UTC, diptiman-adak commented on scripts/ci/check-jira-status.sh
> +  if [ "$resp" -ne 200 ]
These two if loops should be combined together with and

2022-07-20 04:05 UTC, diptiman-adak commented on scripts/ci/message-check.sh
> +  if [ "$resp" -ne 200 ]
ditto

2022-07-20 04:05 UTC, diptiman-adak commented on scripts/ci/message-check.sh
> +  if [ "$resp" -ne 200 ]
Since we are touching these scripts, it will be great to move the common pieces inside a common script

2022-07-20 09:35 UTC, mbatchelor commented on scripts/ci/check-jira-status.sh
> +  if [ "$resp" -ne 200 ]
They cannot be joined into a single statement. These are deciding whether to exit the script. They are logically separate tests:
if curl exits with a non-zero response then exit
if the http response code isn't 200 then exit

2022-07-20 11:39 UTC, diptiman-adak approved these changes

2022-07-20 13:35 UTC, mbatchelor commented
retrigger coverage

2022-07-20 17:14 UTC, abhinavrastogi-harness approved these changes

2022-07-21 11:12 UTC, abhinavrastogi-harness approved these changes

2022-07-21 11:13 UTC, kapilkumawat86 approved these changes

2022-07-21 11:15 UTC, merged