[SRM-10964]: Error Budget Reset UI Changes.
harness/harness-core-ui pull request #10112
Opened 2022-07-20 03:55 UTC by naveen-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-20 03:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10112) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10112) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10112) it.</sub>

2022-07-20 06:41 UTC, harshilbits requested changes

2022-07-20 06:41 UTC, harshilbits commented on src/services/audit/index.tsx
>    auditEventData?: AuditEventData
swagger.json also needs to be updated and this index.tsx should be autogenerated from the updated swagger. We should not update this manually.

2022-07-21 06:36 UTC, naveen-harness commented on src/services/audit/index.tsx
>    auditEventData?: AuditEventData
Done.

2022-07-21 07:25 UTC, vasuki-kalluri approved these changes

2022-07-21 09:02 UTC, harshilbits submitted a review, later dismissed

2022-07-21 09:24 UTC, praneshg239 commented
retrigger titlecheck

2022-07-21 09:42 UTC, praneshg239 approved these changes

2022-07-21 10:01 UTC, harshilbits approved these changes

2022-07-21 10:07 UTC, avinashmadhwani02 approved these changes

2022-07-21 10:22 UTC, merged