fix: [PIE-4443]: Jenkins and amazonS3 triggers
harness/harness-core-ui pull request #10117
Opened 2022-07-20 06:48 UTC by satyam-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-20 06:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10117) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10117) it.</sub>

2022-07-20 07:02 UTC, udayvunnam commented on cypress/integration/72-triggers/AmazonS3Trigger.spec.ts
> +    cy.get('input[placeholder="Select or Add bucket name"]').click()
findByPlaceHolder() or findByRole with placeholder and can avoid explicit wait above

2022-07-20 07:02 UTC, udayvunnam commented on cypress/integration/72-triggers/AmazonS3Trigger.spec.ts
> +    cy.get('.TableV2--cells').eq(0).click()
FYI cells have a role. we can use that

2022-07-20 07:04 UTC, udayvunnam commented on src/modules/72-triggers/pages/triggers/utils/TriggersListUtils.ts
> +        // Uncomment this to enable AmazonS3 and Jenkins triggers
Let's remove the commented code unless we can look back at this with ticket number

2022-07-20 08:11 UTC, satyam-harness commented on cypress/integration/72-triggers/AmazonS3Trigger.spec.ts
> +    cy.get('section[data-cy="Artifact_Amazon S3"]').click()
we discussed this is not an issue

2022-07-20 08:12 UTC, satyam-harness commented on cypress/integration/72-triggers/AmazonS3Trigger.spec.ts
> +    cy.get('.TableV2--cells').eq(0).click()
with role its not working

2022-07-20 08:12 UTC, satyam-harness commented on cypress/integration/72-triggers/AmazonS3Trigger.spec.ts
> +    cy.get('input[placeholder="Select or Add bucket name"]').click()
addressed

2022-07-20 08:41 UTC, udayvunnam approved these changes

2022-07-20 09:36 UTC, chetanvekariya-harness requested changes

2022-07-20 09:36 UTC, chetanvekariya-harness commented on cypress/fixtures/pipeline/api/triggers/amazonS3PipelineDetailsWithFilePathFixed.json
> +{
filePathRegexFixed ?

2022-07-20 09:36 UTC, chetanvekariya-harness commented on cypress/fixtures/pipeline/api/triggers/amazonS3pipelineDetailsWithRoutingIdCallWithFilePathFixed.json
> +{
FilePathRegexFixed ?

2022-07-20 09:36 UTC, chetanvekariya-harness commented on cypress/integration/72-triggers/AmazonS3Trigger.spec.ts
> +describe.skip('AmazonS3 Trigger', () => {
Why is it skipped ?

2022-07-20 09:36 UTC, chetanvekariya-harness commented on cypress/integration/72-triggers/AmazonS3Trigger.spec.ts
> +    cy.get('input[placeholder="Select or Add bucket name"]').click()
Is this pushed ? Can't see the change ?

2022-07-20 09:36 UTC, chetanvekariya-harness commented on cypress/integration/72-triggers/AmazonS3Trigger.spec.ts
> +    cy.get('input[value="testRegex"]').should('be.visible')
Add an assertion which check if this is disabled.

2022-07-20 09:36 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/strings/strings.en.yaml
> +amazonS3DependencyRequired: 'AmazonS3 Connector is required to fetch buckets.'
Just display `Connector is required to fetch buckets`

2022-07-20 09:36 UTC, chetanvekariya-harness commented on src/modules/72-triggers/pages/triggers/utils/TriggersWizardPageUtils.ts
> +          !manifest?.spec?.filePathRegex &&
You should use `||` here
`!manifest?.spec?.filePathRegex ||
          getRuntimeInputLabel({ str: manifest?.spec?.filePathRegex, getString }) !==
            getString?.('pipeline.artifactTriggerConfigPanel.runtimeInput')
        )`

2022-07-20 09:36 UTC, chetanvekariya-harness commented on src/modules/72-triggers/pages/triggers/views/modals/SelectArtifactModal.tsx
> +    finalArtifact.spec.build = replaceTriggerDefaultBuild({
Please check this again. Maybe, it should be like below -
`finalArtifact.spec.filePathRegex = replaceTriggerDefaultBuild({`

2022-07-20 09:36 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/AmazonS3ArtifactSource/AmazonS3ArtifactSource.tsx
> +                fromTrigger
Let's not even call the function here, it is confusing
Do like this
`!fromTrigger && isFieldDisabled(`artifacts.${artifactPath}.spec.bucketName`, true)`

2022-07-20 09:56 UTC, satyam-harness commented on src/modules/72-triggers/pages/triggers/views/modals/SelectArtifactModal.tsx
> +    finalArtifact.spec.build = replaceTriggerDefaultBuild({
what i have written is correct, this change is for jenkins trigger, not s3

2022-07-20 09:57 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/AmazonS3ArtifactSource/AmazonS3ArtifactSource.tsx
> +                fromTrigger
okay

2022-07-20 09:58 UTC, satyam-harness commented on cypress/integration/72-triggers/AmazonS3Trigger.spec.ts
> +describe.skip('AmazonS3 Trigger', () => {
will fail if not skipped, as triggers are hidden from UI

2022-07-20 09:59 UTC, satyam-harness commented on src/modules/70-pipeline/strings/strings.en.yaml
> +amazonS3DependencyRequired: 'AmazonS3 Connector is required to fetch buckets.'
okay

2022-07-20 10:18 UTC, satyam-harness commented on src/modules/72-triggers/pages/triggers/utils/TriggersWizardPageUtils.ts
> +          !manifest?.spec?.filePathRegex &&
usecase -> when filePathRegex is runtime/fixed then we have to keep artifact enabled. so || will not work. But i checked we can skip 2nd condition as well now.

2022-07-20 10:25 UTC, satyam-harness commented on cypress/integration/72-triggers/AmazonS3Trigger.spec.ts
> +    cy.get('input[placeholder="Select or Add bucket name"]').click()
yes

2022-07-20 10:26 UTC, satyam-harness commented on cypress/fixtures/pipeline/api/triggers/amazonS3PipelineDetailsWithFilePathFixed.json
> +{
done, thank you

2022-07-20 10:26 UTC, satyam-harness commented on cypress/fixtures/pipeline/api/triggers/amazonS3pipelineDetailsWithRoutingIdCallWithFilePathFixed.json
> +{
done, thank you

2022-07-20 10:31 UTC, chetanvekariya-harness approved these changes

2022-07-20 10:31 UTC, chetanvekariya-harness commented on cypress/integration/72-triggers/AmazonS3Trigger.spec.ts
> +    cy.get('input[disabled]').should('be.visible')
Any other input with disabled state will match with this. Proper way to write this is finding input with name attr and then checking if it is disabled.

2022-07-20 10:34 UTC, satyam-harness commented
retrigger jest

2022-07-20 10:46 UTC, satyam-harness commented
retrigger jest

2022-07-21 01:33 UTC, udayvunnam approved these changes

2022-07-21 05:08 UTC, bhavya-sinha approved these changes

2022-07-21 05:14 UTC, merged