feat: [FFM-3580]: New target validation
harness/harness-core-ui pull request #10133
Opened 2022-07-20 14:28 UTC by crystal-fong

### Summary

When creating new targets, the dialog checks if user is creating a new target with an existing Identifier. 
Also checks the _name_ and _identifier_ are not missing before submission

Not in this PR:
Style fixes that conforms to UX standardisation

#### Screenshots

https://user-images.githubusercontent.com/95680496/180007630-659d097a-a6dd-457d-878d-239a8ff8170e.mov

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-20 14:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10133) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10133) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10133) it.</sub>

2022-07-20 14:33 UTC, crystal-fong commented on src/modules/75-cf/pages/target-management/targets/__tests__/NewTarget.test.tsx
> +  test.skip('it should call correct values when uploading a CSV file', async () => {
cannot get this to pass because it's saying I'm missing a mock. Left it in just in case someone could see what it is because I'm pretty sure I've mocked every hook in NewTarget

2022-07-21 08:23 UTC, crystal-fong commented
retrigger eslint

2022-07-21 09:51 UTC, knagurski requested changes
😢 this will only work for the current page of targets; we need to search the entire list of Targets. I think you'll need to do an API call to get an existing target and then consider it a duplicate if you get a result.

Good try though! I like the approach of using what you had at hand.

2022-07-28 08:55 UTC, closed without merging