fix: [CDS-39946]: infrastructure not updating on change of environment
harness/harness-core-ui pull request #10145
Opened 2022-07-21 07:16 UTC by AshwinBhatkal-Harness

### Summary

Infrastructure not updating on change of environment

#### Screenshots

https://user-images.githubusercontent.com/96711906/180153002-ec48f01d-8831-42c4-b448-28fdc65ff750.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-22 06:49 UTC, chetanvekariya-harness requested changes

2022-07-22 06:49 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructures/DeployInfrastructures.tsx
> +  const updateInfrastructuresList = /* istanbul ignore next */ (values: InfrastructureResponseDTO) => {
Why `istanbul ignore next` is added here ?

2022-07-22 06:49 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructures/__tests__/DeployInfrastructures.test.tsx
> +jest.mock('@harness/uicore', () => ({
We must not do this.

2022-07-22 06:49 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructures/__tests__/DeployInfrastructures.test.tsx
> +    expect(container).toMatchSnapshot()
No need to write snapshot testing here. Simple assertion would do just fine.
Snapshot testing is causing lot of issues when even simple style is changed in common component.

2022-07-22 06:49 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructures/__tests__/DeployInfrastructures.test.tsx
> +    expect(container).toMatchSnapshot()
Same as above.

2022-07-22 06:49 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructures/__tests__/DeployInfrastructures.test.tsx
> +    await waitFor(() => expect(showError).toHaveBeenCalled())
Assert on actual error message here. And remove mocking of showError.

2022-07-22 06:51 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructures/DeployInfrastructures.tsx
> +  const updateInfrastructuresList = /* istanbul ignore next */ (values: InfrastructureResponseDTO) => {
I'll test this with cypress

2022-07-22 09:47 UTC, chetanvekariya-harness approved these changes

2022-07-25 01:58 UTC, vkbansal approved these changes

2022-07-25 01:58 UTC, merged