feat: [CI-4765]: git clone step rebase
harness/harness-core-ui pull request #10140
Opened 2022-07-20 19:11 UTC by mtran7

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-21 01:49 UTC, udayvunnam commented on src/modules/70-pipeline/components/PipelineStudio/RightBar/RightBarUtils.tsx
> +            /* istanbul ignore next */
can we remove the coverage ignore comments and let the coverage be visible in reports, otherwise I see people hardly revisit these things?

2022-07-21 01:51 UTC, udayvunnam commented on src/modules/75-ci/components/PipelineSteps/GitCloneStep/GitCloneStep.stories.tsx
> +  // eslint-disable-next-line react/display-name
perhaps we should disable this rule for stories and tests :)

2022-07-21 01:53 UTC, udayvunnam commented on src/modules/75-ci/components/PipelineSteps/RunTestsStep/RunTestsStepBase.tsx
> +                connectorWidth={373}
Do we need a fixed width here than occupying the full width of parent?

2022-07-21 01:54 UTC, udayvunnam commented
Can you please add a gif or screenshots of the changes

2022-07-21 06:49 UTC, mtran7 commented on src/modules/75-ci/components/PipelineSteps/RunTestsStep/RunTestsStepBase.tsx
> +                connectorWidth={373}
I will revert for this and run step. On my laptop it was previously showing connector to be off but now 373 is off.

2022-07-21 14:27 UTC, d1wilko requested changes
It's a big one!

Added a few comments :)

2022-07-21 14:27 UTC, d1wilko commented on src/modules/75-ci/components/PipelineSteps/CIStep/ConnectorRefWithImage.tsx
> +              width={connectorWidth || 385}
I think this is better as `width={connectorWidth ?? 385}` - in theory connectorWidth could be 0 which is falsy and would switch to 385

2022-07-21 14:27 UTC, d1wilko commented on src/modules/75-ci/components/PipelineSteps/GitCloneStep/GitCloneStep.tsx
> +    | {
whats the | here for?

2022-07-21 14:27 UTC, d1wilko commented on src/modules/75-ci/components/PipelineSteps/GitCloneStep/GitCloneStepBase.tsx
> +  })
this is really confusing 🙈 

might be better as something like

`
const [codebaseRuntimeInputs, setCodebaseRuntimeInputs] = React.useState<CodebaseRuntimeInputsInterface>
(() => isRuntimeInput(codebaseConnector) ? {connectorRef: true, repoName: true} : {})
`
full disclosure I haven't tested that, but its definitely more readable!

2022-07-21 14:27 UTC, d1wilko commented on src/modules/75-ci/components/PipelineSteps/GitCloneStep/GitCloneStepInputSet.tsx
> +    ...(isRuntimeInput(codebaseConnector) && { connectorRef: true, repoName: true })
similar to example above

2022-07-21 15:50 UTC, mtran7 commented on src/modules/10-common/components/MultiTypeRadioGroup/MultiTypeRadioGroup.tsx
> +            rest?.allowableTypes && rest.allowableTypes.length > 1 && css.multiTypeInputs,
had tried but got an error 
<img width="630" alt="image" src="https://user-images.githubusercontent.com/43422351/180257896-cf92a55d-2f7b-4b51-b299-eeed511f41ea.png">

2022-07-25 22:51 UTC, mtran7 commented on src/modules/70-pipeline/components/PipelineStudio/RightBar/RightBarUtils.tsx
> +            /* istanbul ignore next */
done

2022-07-25 22:51 UTC, mtran7 commented on src/modules/75-ci/components/PipelineSteps/GitCloneStep/GitCloneStep.stories.tsx
> +  // eslint-disable-next-line react/display-name
done - this was just copied from another connector

2022-07-25 23:01 UTC, mtran7 commented on src/modules/70-pipeline/components/PipelineInputSetForm/CICodebaseInputSetForm.tsx
> +export type CodeBaseType = 'branch' | 'tag' | 'PR'
Good catch - I refactored and used enum CodebaseTypes from CIUtils instead of having this one that only declares type

2022-07-25 23:04 UTC, mtran7 commented on src/modules/75-ci/components/PipelineSteps/GitCloneStep/GitCloneStep.tsx
> +    | {
Issue when you do or operator and an interface. Instead, I created BuildInterface and used the | operator

2022-07-25 23:06 UTC, mtran7 commented on src/modules/75-ci/components/PipelineSteps/CIStep/ConnectorRefWithImage.tsx
> +              width={connectorWidth || 385}
0 ?? 385 is 0 
0 || 385 is 385, so we should keep ||

2022-07-25 23:08 UTC, mtran7 commented on src/modules/75-ci/components/PipelineSteps/CIStep/CIStep.tsx
> +      {Object.prototype.hasOwnProperty.call(enableFields, 'spec.connectorAndRepo') && formik && (
Good suggestion. This makes it more readable

2022-07-25 23:08 UTC, mtran7 commented on src/modules/75-ci/components/PipelineSteps/GitCloneStep/GitCloneStepBase.tsx
> +  })
good suggestion, made the change

2022-07-26 09:37 UTC, d1wilko reviewed
coming together - still some outstanding comments

2022-07-26 09:37 UTC, d1wilko commented on src/modules/75-ci/components/PipelineSteps/CIStep/CIStepOptionalConfig.tsx
> +      {Object.prototype.hasOwnProperty.call(enableFields, 'spec.depth') ? (
I think you missed this one

2022-07-26 09:37 UTC, d1wilko commented on src/modules/75-ci/components/PipelineSteps/CIStep/CIStep.tsx
> +              : css.bottomMargin2
thoughts here?

2022-07-26 09:37 UTC, d1wilko commented on src/modules/75-ci/components/PipelineSteps/CIStep/CIStepOptionalConfig.tsx
> +      {Object.prototype.hasOwnProperty.call(enableFields, 'spec.sslVerify') ? (
I think you missed this one

2022-07-27 18:10 UTC, vardanbansal-harness commented on src/modules/10-common/components/MultiTypeRadioGroup/MultiTypeRadioGroup.module.scss
> +    letter-spacing: 0.2px;
Do we not have the corresponding font variation (from [UIKit](https://uicore.harness.io/?path=/story/components-text--basic)) to use here?

2022-07-27 18:11 UTC, vardanbansal-harness commented on src/modules/70-pipeline/components/PipelineInputSetForm/CICodebaseInputSetForm.tsx
> +      setCodeBaseType(CodebaseTypes.BRANCH)
This is nice 👍, right case makes it more readable.

2022-07-27 18:14 UTC, vardanbansal-harness commented on src/services/pipeline-ng/index.tsx
> +    | 'GitClone'
One problem with this may be if someone tries to re-generate these types from swagger, this hardcoded value will be removed if it's not in the swagger.

2022-07-27 18:17 UTC, vardanbansal-harness submitted a review, later dismissed

2022-07-28 00:03 UTC, mtran7 commented on src/services/pipeline-ng/index.tsx
> +    | 'GitClone'
Right -- thanks for the reminder. Will need to have backend merge first, re-generate and push

2022-07-28 18:54 UTC, mtran7 commented on src/modules/10-common/components/MultiTypeRadioGroup/MultiTypeRadioGroup.module.scss
> +    letter-spacing: 0.2px;
We do for the label. Ex. Build Type. But not for the children radio labels 
![image](https://user-images.githubusercontent.com/43422351/181615723-46e85de7-8d64-418d-9c08-d8d82343b827.png)

2022-07-28 20:07 UTC, mtran7 commented on src/modules/70-pipeline/components/PipelineSteps/PipelineStepInterface.ts
> +  // HARDCODED TO REMOVE
remove comment

2022-08-01 19:08 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 84 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 84 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10140)

2022-08-05 02:25 UTC, udayvunnam submitted a review, later dismissed

2022-08-09 16:23 UTC, mtran7 commented
Coverage report effort to get close to 80%
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/43422351/183705397-c07b4278-6b9f-41d3-9c69-14fd4ceb1e1d.png">
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/43422351/183705439-48706baf-5918-4646-8784-fc865adb7897.png">
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/43422351/183705501-63618d97-713b-44cf-a839-59c2298a83e1.png">

2022-08-09 19:15 UTC, vardanbansal-harness approved these changes

2022-08-10 10:06 UTC, d1wilko requested changes
one question - otherwise looks good

2022-08-10 10:06 UTC, d1wilko commented on src/services/pipeline-ng/index.tsx
> +    | 'GitClone'
can this be removed now?

2022-08-13 00:27 UTC, mtran7 commented on src/modules/75-ci/components/PipelineSteps/CIStep/StepUtils.tsx
> +  const [previousBuildTypeValues, setPreviousBuildTypeValues] = React.useState<Record<string, string>>({
to persist previous value but not have it added to formik values

2022-08-13 22:14 UTC, tan-nhu submitted a review, later dismissed

2022-08-15 17:22 UTC, mtran7 commented
retrigger jest

2022-08-18 23:58 UTC, mtran7 commented
Unrelated failing flaky test src/modules/85-cv/components/HealthSourceDropDown/__tests__/HealthSourceDropDown.test.tsx

2022-08-19 01:29 UTC, mtran7 commented on src/services/pipeline-ng/index.tsx
> +    | 'GitClone'
done now

2022-08-19 01:30 UTC, merged