feat: [CCM-8226]: Inventory dashboard navigation
harness/harness-core-ui pull request #10164
Opened 2022-07-22 07:30 UTC by jyotiarora-harness

### Summary

Inventory dashboard navigation feature

#### Screenshots

<img width="1725" alt="Screenshot 2022-07-22 at 12 59 59 PM" src="https://user-images.githubusercontent.com/97077953/180387338-630dc9e9-d807-4ed9-8556-1a7f7e41bcbc.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-22 07:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10164) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10164) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10164) it.</sub>

2022-08-01 10:54 UTC, rishik30 requested changes

2022-08-01 10:54 UTC, rishik30 commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.tsx
> +    .filter((dashboardData: BIDashboardSummary) => {
what's the need of 2 separate filters? Can't we combine the logic under single filter callback?

2022-08-01 10:54 UTC, rishik30 commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.tsx
> +              <Link
add a space between the texts

2022-08-01 10:54 UTC, rishik30 commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.tsx
> +            items={filteredDashboardData || /* istanbul ignore next */ []}
no need for a default value. filter will make sure to return an empty array in case there's no data

2022-08-01 11:11 UTC, rajarshee-harness commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.tsx
> +        {loading ? <PageSpinner /> : null}
PageBody has a `loading` prop which will directly render a PageSpinner.

2022-08-01 11:11 UTC, rajarshee-harness commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.tsx
> +                            ? 'var(--primary-7)'
Directly use Icon's `color` prop?

2022-08-01 11:11 UTC, rajarshee-harness commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.tsx
> +            style={{ fontSize: 20, fontWeight: 'bold' }}
Use `FontVariation`

2022-08-01 11:40 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.tsx
> +    .filter((dashboardData: BIDashboardSummary) => {
Did the separate handling for the edge cases for both search and filter and combining them making it complex to understand

2022-08-01 12:34 UTC, rishik30 approved these changes

2022-08-01 14:27 UTC, kapilkumawat86 approved these changes

2022-08-01 16:40 UTC, merged