feat: [SRM-11182]: UX review comments
harness/harness-core-ui pull request #10168
Opened 2022-07-22 09:56 UTC by deepesh-ui

### Summary

Updated Title container for Templates card and Template studio  from SVG to  Styled component

#### Screenshots
<img width="1517" alt="Screenshot 2022-07-22 at 3 24 22 PM" src="https://user-images.githubusercontent.com/81554936/180414888-f776def6-7fe5-4fdd-93c8-f8dcb549c4fb.png">
<img width="1180" alt="Screenshot 2022-07-22 at 3 24 08 PM" src="https://user-images.githubusercontent.com/81554936/180414909-8b52f857-d53e-416f-b564-628193a071d7.png">

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-22 10:00 UTC, deepesh-ui commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +export const getTemplateTitleFromType = (
Inside **Create New Template**  Modal, we don't want  to populate the default new template name rather we are keeping it Empty.

2022-07-22 10:58 UTC, yc147 reviewed
When creating a new template, you have removed the default value for the name field i.e. New {entity} Template Name in case of monitored service template. If this is a real use case then let’s solve it in a way that in future other templates can also benefit.

Also, in case of monitored service template you are getting template type label from a separate string in the codebase instead of using template.type.

2022-07-22 10:58 UTC, yc147 requested changes
When creating a new template, you have removed the default value for the name field i.e. New {entity} Template Name in case of monitored service template. If this is a real use case then let’s solve it in a way that in future other templates can also benefit.

Also, in case of monitored service template you are getting template type label from a separate string in the codebase instead of using template.type.

2022-07-26 07:15 UTC, yc147 approved these changes

2022-07-26 10:29 UTC, praneshg239 approved these changes

2022-07-26 10:43 UTC, deepesh-ui commented
Coverage failure is due to newly added templates , which don't have any functionality only classes are added for future reference

<img width="938" alt="Screenshot 2022-07-26 at 4 09 28 PM" src="https://user-images.githubusercontent.com/81554936/180987331-7b9abd6c-62e4-45d9-821d-4bb4a4a8a883.png">

2022-07-26 10:54 UTC, merged