fix: [PIE-4585]: Custom artifact source
harness/harness-core-ui pull request #10174
Opened 2022-07-22 22:21 UTC by satyam-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-22 22:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10174) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10174) it.</sub>

2022-07-23 12:44 UTC, bhavya-sinha requested changes

2022-07-23 12:44 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactHelper.ts
> +    ENABLED_ARTIFACT_TYPES.CustomArtifact
This is already added, and is behind FF

2022-07-23 12:44 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/CustomArtifact/CustomArtifact.tsx
> +  const scriptType: ScriptType = formik.values?.spec?.shell || 'Bash'
Use string const

2022-07-23 12:44 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/CustomArtifact/CustomArtifact.tsx
> +              // className={css.minConfigBtn}
remove commented code

2022-08-01 18:57 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10174)

2022-09-07 04:25 UTC, satyam-harness commented
trigger cypress

2022-09-07 08:48 UTC, Sagar-Rajput7 approved these changes

2022-09-07 09:21 UTC, PratyushGar submitted a review, later dismissed

2022-09-07 09:24 UTC, PratyushGar commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactInterface.ts
> +export interface variableInterface {
```suggestion
export interface VariableInterface {
```
Interface must start with uppercase

2022-09-07 11:47 UTC, bhavya-sinha approved these changes

2022-09-07 14:17 UTC, bhavya-sinha approved these changes

2022-09-07 14:50 UTC, vkbansal-harness approved these changes

2022-09-07 14:50 UTC, merged