feat: [CI-4822]: CI Onboarding improvements
harness/harness-core-ui pull request #10224
Opened 2022-07-26 08:31 UTC by vardanbansal-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-27 16:03 UTC, d1wilko requested changes
Coming together nicely, a few questions :)

2022-07-27 16:03 UTC, d1wilko commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/SelectRepository.tsx
> +        ConnectorSelectionItems.filter((item: SelectOption) => item.value === validatedConnector.identifier)?.[0]
array find a better option here?

2022-07-27 16:03 UTC, d1wilko commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/SelectRepository.tsx
> +      const matchingConnector = connectorsEligibleForPreSelection?.filter(
find?

2022-07-27 17:11 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/GetStartedWithCI.tsx
> +        if (status === Status.SUCCESS && Array.isArray(data?.content) && data?.content && data.content.length > 0) {
Yeah I did that initially but then it starts to complain.

<img width="879" alt="image" src="https://user-images.githubusercontent.com/48940704/181308163-682ae96e-8b2f-4f88-98b8-41a2f88cadcd.png">

2022-07-27 17:17 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/SelectRepository.tsx
> +      const matchingConnector = connectorsEligibleForPreSelection?.filter(
Done.

2022-07-27 17:17 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/SelectRepository.tsx
> +        ConnectorSelectionItems.filter((item: SelectOption) => item.value === validatedConnector.identifier)?.[0]
Done.

2022-07-27 17:18 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/SelectRepository.tsx
> +  const getIcon = React.useCallback((type: ConnectorInfoDTO['type']): IconName | undefined => {
Removed.

2022-07-27 17:18 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/GetStartedWithCI.tsx
> +                  }}
This I am not aware of why it was done this way, @tan-nhu added this.

2022-07-27 17:18 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/GetStartedWithCI.tsx
> +  }, [fetchingGitConnectors, isFetchingSecret])
Well yes, for a moment didn't pay attention that this computation isn't really complex for a memo to be used. Removed.

2022-07-27 17:18 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/GetStartedWithCI.tsx
> +            const secretIdentidier = getIdentifierFromValue(
Great catch, thanks, done!

2022-07-27 17:18 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/GetStartedWithCI.tsx
> +          )?.[0]
Thanks for the tip! Done ✅

2022-07-27 17:25 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/GetStartedWithCI.tsx
> +                  }}
Well, I gave it a try and a ref also works. Done.

2022-07-27 17:37 UTC, mtran7 approved these changes

2022-07-28 08:49 UTC, d1wilko commented on src/modules/75-ci/pages/get-started-with-ci/GetStartedWithCI.tsx
> +        if (status === Status.SUCCESS && Array.isArray(data?.content) && data?.content && data.content.length > 0) {
yep so I think `Array.isArray(data?.content) && data?.content.length > 0)` should work

it might need to be `Array.isArray(data?.content) && data?.content?.length > 0)`

2022-07-28 08:52 UTC, d1wilko approved these changes
1 outstanding question but I'll not let it hold up the PR :)

2022-07-28 08:54 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/GetStartedWithCI.tsx
> +        if (status === Status.SUCCESS && Array.isArray(data?.content) && data?.content && data.content.length > 0) {
Sure will do it in a follow up PR

2022-07-28 08:54 UTC, merged