feat: [SRM-11235]: implementing UX review changes
harness/harness-core-ui pull request #10246
Opened 2022-07-27 05:25 UTC by harshilbits

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-27 05:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10246) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10246) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10246) it.</sub>

2022-07-27 09:20 UTC, harshilbits commented
retrigger titlecheck

2022-07-27 13:30 UTC, yc147 commented on src/modules/70-pipeline/components/PipelineStudio/TemplateBar/TemplateBar.tsx
> +        {
This can be simplified to 
`
[ {
  icon: 'command-switch',
  label: getString('pipeline.changeTemplateLabel'),
  onClick: onChangeTemplate
}, ....(!!onRemoveTemplate && {
  icon: 'main-trash',
  label: getString('pipeline.removeTemplateLabel'),
  onClick: openRemoveTemplateDialog
})]`

2022-07-27 13:31 UTC, devinder-harness approved these changes

2022-07-27 13:33 UTC, harshilbits commented on src/modules/70-pipeline/components/PipelineStudio/TemplateBar/TemplateBar.tsx
> +        {
Yeah , I also did the same initially but found the current way to be more readable.

2022-07-27 13:34 UTC, praneshg239 commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationWidget/components/ContinousVerificationWidgetSections/components/SelectVerificationType/SelectVerificationType.tsx
> +          <Text font={{ size: 'small' }}>{'Select a type that matches your deployment strategy.'}</Text>
Please use `yaml` for `'Select a type that matches your deployment strategy.'`

2022-07-27 13:35 UTC, harshilbits commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationWidget/components/ContinousVerificationWidgetSections/components/SelectVerificationType/SelectVerificationType.tsx
> +          <Text font={{ size: 'small' }}>{'Select a type that matches your deployment strategy.'}</Text>
good catch  , missed it.

2022-07-27 13:39 UTC, yc147 commented on src/modules/70-pipeline/components/PipelineStudio/TemplateBar/TemplateBar.tsx
> +        {
There is code repetition here. Which is not correct.

2022-07-27 13:41 UTC, yc147 requested changes
There is code repetition here. Which is not correct. Conditionally adding elements to array is a very natural way.

2022-07-27 13:58 UTC, harshilbits commented on src/modules/70-pipeline/components/PipelineStudio/TemplateBar/TemplateBar.tsx
> +        {
addressed !

2022-07-27 14:00 UTC, praneshg239 submitted a review, later dismissed

2022-07-27 14:05 UTC, yc147 submitted a review, later dismissed

2022-07-27 14:17 UTC, deepesh-ui commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationWidget/components/ContinousVerificationWidgetSections/components/SelectMonitoredServiceType/SelectMonitoredServiceType.tsx
> +            <Text>{'Monitored Service'}</Text>
use from strings.yml

2022-07-28 04:48 UTC, praneshg239 approved these changes

2022-07-28 04:49 UTC, yc147 approved these changes

2022-07-28 05:09 UTC, harshilbits commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationWidget/components/ContinousVerificationWidgetSections/components/SelectMonitoredServiceType/SelectMonitoredServiceType.tsx
> +            <Text>{'Monitored Service'}</Text>
done.

2022-07-28 05:13 UTC, kapilkumawat86 approved these changes

2022-07-28 05:14 UTC, upadhyay-an approved these changes

2022-07-28 05:15 UTC, merged