feat: [SRM-11246]: Template bar in MS  input set
harness/harness-core-ui pull request #10269
Opened 2022-07-28 03:21 UTC by deepesh-ui

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-28 03:29 UTC, praneshg239 submitted a review, later dismissed

2022-07-28 06:54 UTC, deepesh-ui commented
retrigger titlecheck

2022-07-28 07:08 UTC, deepesh-ui commented
retrigger titlecheck

2022-07-28 07:25 UTC, harshilbits requested changes

2022-07-28 07:25 UTC, harshilbits commented on src/modules/85-cv/pages/monitored-service/MonitoredServiceInputSetsTemplate/MonitoredServiceInputSetsTemplate.tsx
> +    const { template } = await getTemplate({ templateType: 'MonitoredService' })
Please move MonitoredService to templateType enum

2022-07-28 07:25 UTC, harshilbits commented on src/modules/85-cv/pages/monitored-service/MonitoredServiceInputSetsTemplate/MonitoredServiceInputSetsTemplate.tsx
> +                    templateRef: templateRefData.identifier as string,
what if templateRefData is null, good to have a null check or default values

2022-07-28 10:55 UTC, harshilbits approved these changes

2022-07-28 13:39 UTC, yc147 submitted a review, later dismissed

2022-07-29 06:16 UTC, yc147 requested changes
Let’s explore the possibility of doing it through RBAC

2022-09-23 03:25 UTC, closed without merging