feat: [CDS-40651]: Add checkbox, input for Kustomize Yaml Path
harness/harness-core-ui pull request #10278
Opened 2022-07-28 12:02 UTC by rameshx

### Summary

Shows a checkbox under Advanced section when `NG_OPTIMIZE_FETCH_FILES_KUSTOMIZE` FF is enabled
Shows an input for entering Kustomize Yaml Path when the checkbox is selected

#### Screenshots

https://user-images.githubusercontent.com/52284933/181499997-fc646a6f-c5f6-4b98-8ec4-d14903ace956.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-28 12:04 UTC, rameshx commented
retrigger titlecheck

2022-07-28 13:28 UTC, rameshx commented
dockerize

2022-07-29 05:44 UTC, rameshx commented
trigger cypress

2022-07-29 06:51 UTC, YounixIO submitted a review, later dismissed

2022-07-29 07:01 UTC, chetanvekariya-harness submitted a review, later dismissed
Better to address small comments.

2022-07-29 07:01 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/KustomizeWithGIT/__tests__/KustomizeWithGIT.test.tsx
> +    expect(container.querySelector('input[name="kustomizeYamlFolderPath"]')).toBeInTheDocument()
use queryByAttribute

2022-07-29 07:30 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/KustomizeWithGIT/KustomizeWithGIT.tsx
> +                                style={{ flex: 1 }}
inline style?

2022-07-29 07:32 UTC, bhavya-sinha requested changes

2022-07-29 07:32 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/KustomizeWithGIT/KustomizeWithGIT.tsx
> +                          name="skipResourceVersioning"
skipResourceVersioning should be inside advanced section, similar to other manifest

2022-07-29 07:32 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/KustomizeManifestSource/KustomizeManifestSource.tsx
> +              expressions,
Add coverage for this

2022-07-29 07:33 UTC, bhavya-sinha approved these changes

2022-07-29 09:24 UTC, rameshx commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/KustomizeWithGIT/KustomizeWithGIT.tsx
> +        optimizedKustomizeManifestCollection: !!kustomizeYamlFolderPath,
`optimizedKustomizeManifestCollection` is not added to the YAML, its value is based on `kustomizeYamlFolderPath` as the user can only give a path if `optimizedKustomizeManifestCollection` is true and vice-versa.

2022-07-29 10:11 UTC, bhavya-sinha approved these changes

2022-07-29 10:12 UTC, chetanvekariya-harness approved these changes

2022-07-29 10:55 UTC, rameshx commented
trigger cypress

2022-07-29 15:37 UTC, merged