feat: [PIE-4290]: Template gitx integration
harness/harness-core-ui pull request #10274
Opened 2022-07-28 10:04 UTC by depanshu-dhiman

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-01 18:53 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 37 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 37 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10274)

2022-08-08 09:49 UTC, depanshu-dhiman commented
dockerize

2022-08-08 10:54 UTC, yc147 commented on src/modules/72-templates-library/pages/TemplatesPage/views/TemplatesListView/TemplatesListView.tsx
> +    <Text
Wrap this inside Layout.Horizontal, give it a right padding and remove inlines style and max width. See how `RenderColumnLabel` is done.

2022-08-08 11:18 UTC, yc147 commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +  shouldGetComment?: boolean
We need to remove `shouldGetComment`, `showGitFields`, `isEdit`

2022-08-08 12:00 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +        {modalProps && (
just pass modalProps here

2022-08-08 12:02 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +        {modalProps && (
pass `template`, `gitDetails` and `storeMetadata` separately

2022-08-08 12:03 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +      delete (template as TemplateWithGitContextFormProps).repo
Remove this and next 4 lines.

2022-08-08 12:06 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +        if (updatedGitDetails) {
Remove this check of scope change in old flow will break.

2022-08-08 15:21 UTC, yc147 commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +  initialValues: NGTemplateInfoConfig & StoreMetadata
Don't combine there. add a new key `storeMetadata`

2022-08-08 15:23 UTC, yc147 commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +        if (isGitSyncEnabled) {
This check is not required.

2022-08-08 15:24 UTC, yc147 commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +                            if (item.type === StoreType.REMOTE) {
write a separate function for this.

2022-08-08 15:25 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +                    isEdit: !!templateIdentifier && templateIdentifier !== DefaultNewTemplateId,
Not needed.. solve using intent.

2022-08-08 15:26 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/TemplateStudioSubHeader.tsx
> +                        if (isGitSimplificationEnabled) {
Put this login inside TemplateContext.. Not need to expose `fetchTemplateV2` and `fetchTemplate`

2022-08-08 15:32 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +        shouldGetComment: !isGitSyncEnabled && storeMetadata?.storeType !== StoreType.REMOTE,
`shouldGetComment` not needed. Solve using `intent`

2022-08-08 15:33 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +          ...(isGitSimplificationEnabled
Do not combine `template` and `storeMetadata`

2022-08-08 15:33 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +        shouldGetComment: !isGitSyncEnabled && storeMetadata?.storeType !== StoreType.REMOTE
shouldGetComment not needed. Solve using intent

2022-08-08 15:35 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +        if (isGitSimplificationEnabled) {
Move this logic inside `TemplateContext` and expose only `fetchTemplate`

2022-08-08 15:36 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +          connectorRef: 'single_repo_gitx',
what are these values?

2022-08-11 12:45 UTC, depanshu-dhiman commented on src/modules/72-templates-library/pages/TemplatesPage/views/TemplatesListView/TemplatesListView.tsx
> +    <Text
Done

2022-08-12 12:16 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +        {modalProps && (
Done

2022-08-12 14:46 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +  shouldGetComment?: boolean
Done

2022-08-12 16:17 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +      delete (template as TemplateWithGitContextFormProps).repo
Done

2022-08-12 16:17 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +        if (updatedGitDetails) {
Done

2022-08-12 16:17 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +  initialValues: NGTemplateInfoConfig & StoreMetadata
Done

2022-08-12 16:21 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +        if (isGitSyncEnabled) {
This required for 3 different flows. Without git. With gitSync. With gitSimplification.

2022-08-12 16:28 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +                            if (item.type === StoreType.REMOTE) {
Done

2022-08-12 16:28 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +                    isEdit: !!templateIdentifier && templateIdentifier !== DefaultNewTemplateId,
Done

2022-08-13 07:53 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/TemplateStudioSubHeader.tsx
> +                        if (isGitSimplificationEnabled) {
Done

2022-08-13 08:06 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> -    [checkErrors, isGitSyncEnabled, template, stableVersion, saveAndPublish, gitDetails]
Done

2022-08-13 08:06 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +        shouldGetComment: !isGitSyncEnabled && storeMetadata?.storeType !== StoreType.REMOTE,
Done

2022-08-13 08:06 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +          ...(isGitSimplificationEnabled
Done

2022-08-13 08:06 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +          ...(isGitSimplificationEnabled
Done

2022-08-13 08:06 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +        shouldGetComment: !isGitSyncEnabled && storeMetadata?.storeType !== StoreType.REMOTE
Done

2022-08-13 08:07 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +        if (isGitSimplificationEnabled) {
Done

2022-08-13 08:08 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +          connectorRef: 'single_repo_gitx',
These were hardcoded strings because API wasn't ready. Replaced this with variables

2022-08-23 12:03 UTC, yc147 requested changes

2022-08-23 12:46 UTC, depanshu-dhiman commented on src/modules/72-templates-library/pages/TemplatesPage/views/TemplatesListView/TemplatesListView.tsx
> +  }, [hideMenu, supportingTemplatesGitx, isGitSyncEnabled])
done

2022-08-23 12:54 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +        if (supportingTemplatesGitx && extraInfo.storeMetadata) {
done

2022-08-23 12:54 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/TemplateStudioSubHeader.tsx
> +    !supportingTemplatesGitx || (supportingTemplatesGitx && !isLoading && !templatesErrorByIdentifier)
done

2022-08-23 12:54 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +        } else if (isGitSyncEnabled) {
done

2022-08-23 12:55 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +                      !!templateIdentifier && templateIdentifier !== DefaultNewTemplateId ? Intent.EDIT : Intent.START,
done

2022-08-23 13:00 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateContext/TemplateContext.tsx
> +        templatesErrorByIdentifier: undefined
`templateYamlError` done

2022-08-23 13:02 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +  const showErrorPanel = supportingTemplatesGitx && !isLoading && !!templatesErrorByIdentifier
done

2022-08-23 13:02 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateContext/TemplateContext.tsx
> +                isInitialized: false
This `isInitialized` refers to db intitialization. We can not set it `false` here. And it dispatch `TemplateContextActions.initialized()`.

Decouple your logic to show `templatesErrorByIdentifier` with `isInitialized`

2022-08-23 13:02 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +            {(isInitializedTemplate || (supportingTemplatesGitx && !isLoading)) && (
done

2022-08-23 13:02 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateContext/TemplateReducer.ts
> +  templatesErrorByIdentifier?: TemplateError
done

2022-08-23 13:03 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateContext/TemplateContext.tsx
> +  }, [repoIdentifier, branch, templateIdentifier])
done

2022-08-23 13:08 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +          [css.gitConfigDialog]: supportingTemplatesGitx
done

2022-08-23 13:08 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +          ...produce(template, draft => {
done

2022-08-23 13:08 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +        },
done

2022-08-23 14:11 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +    storeMetadata,
done

2022-08-23 14:17 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/DeleteTemplateModal/DeleteTemplateModal.tsx
> +      ...(isGitSyncEnabled
Done, but removed defaultTo because empty string was being sent in request.
For the new API, repoIdentifier is not applicable. So to avoid any confusion, removed helper defaultTo

2022-08-23 14:18 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateCard/TemplateCard.tsx
> +    supportingTemplatesGitx && (template as TemplateMetadataSummaryResponse)?.storeType === StoreType.REMOTE
done

2022-08-23 14:55 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateContext/TemplateContext.tsx
> +                isInitialized: false
done

2022-08-24 08:45 UTC, yc147 commented on src/modules/70-pipeline/components/PipelineStudio/SaveTemplateButton/useSaveAsTemplate.tsx
> +        storeMetadata: {
Pass `storeMetadata` in prop and don't use query params. 

Don't modify `gitDetails`

2022-08-24 08:51 UTC, yc147 commented on src/modules/70-pipeline/utils/useSaveTemplate.ts
> +        if (!isEmpty(updatedGitDetails) || storeMetadata?.storeType === StoreType.REMOTE) {
`(updatedGitDetails && !isEmpty(updatedGitDetails)) || storeMetadata?.storeType === StoreType.REMOTE`

2022-08-24 08:53 UTC, yc147 commented on src/modules/70-pipeline/utils/useSaveTemplate.ts
> +    [openSaveToGitDialog]
Remove use callback altogether

2022-08-24 09:13 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateContext/TemplateContext.tsx
> +        logger.info('Failed to fetch template')
dispatch(TemplateContextActions.initialized())

2022-08-24 09:15 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +            {(isInitializedTemplate || supportingTemplatesGitx) && (
Revert this line.

2022-08-24 13:29 UTC, depanshu-dhiman commented on src/modules/70-pipeline/utils/useSaveTemplate.ts
> +        if (!isEmpty(updatedGitDetails) || storeMetadata?.storeType === StoreType.REMOTE) {
done

2022-08-24 13:29 UTC, depanshu-dhiman commented on src/modules/70-pipeline/utils/useSaveTemplate.ts
> +    [openSaveToGitDialog]
done

2022-08-24 14:36 UTC, yc147 commented on src/framework/Templates/TemplateSelectorContext/useTemplateSelector.ts
> +  const parentEntityContext = useParentEntityContext()
You can not use `parentEntityContext` here.. pass it in `selectorData`

2022-08-24 15:56 UTC, yc147 commented on src/framework/Templates/TemplateSelectorContext/useTemplateSelector.ts
> +  parentEntityContext?: ParentEntityContext
Add 2 things `gitDetails`, `storeMetadata`

2022-08-24 16:09 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateSelector/TemplateSelector.tsx
> +          parentEntityContext={selectorData?.parentEntityContext}
Rename this to `storeMetadata`

2022-08-25 06:30 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateContext/TemplateContext.tsx
> +        logger.info('Failed to fetch template')
done

2022-08-25 06:37 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +            {(isInitializedTemplate || supportingTemplatesGitx) && (
done

2022-08-25 07:49 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> +    templateIdentifier: defaultTo(template.identifier, ''),
done

2022-08-26 05:50 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateSelector/TemplateSelector.tsx
> +          parentEntityContext={selectorData?.parentEntityContext}
done

2022-08-26 05:50 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateSelectorContext/useTemplateSelector.ts
> +  parentEntityContext?: ParentEntityContext
done

2022-08-26 05:50 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateSelectorContext/useTemplateSelector.ts
> +  const parentEntityContext = useParentEntityContext()
done

2022-08-30 09:28 UTC, yc147 reviewed
Remove `getStoreMetadataFromQuery`

2022-08-30 09:50 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +const remoteTemplateTypes = ['Step', 'Stage', 'Pipeline']
done

2022-08-30 09:50 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +      (!isTemplateGitxAccountEnabled && (!projectIdentifier || selectedScope !== Scope.PROJECT)),
done

2022-08-30 09:51 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +    [initialValues]
done

2022-08-30 09:52 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
>          ...(!isEmpty(values.repo) && {
done

2022-08-30 09:53 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
>        })
done

2022-08-30 09:55 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +    formik.setFieldValue('storeType', item.type)
done

2022-08-30 09:55 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +      setTimeout(() => {
will check later

2022-08-30 10:05 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +                    [css.gitFormWrapper]: supportingTemplatesGitx
done

2022-08-30 10:06 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +                            [css.gitNameIdDescriptionTags]: supportingTemplatesGitx
done

2022-08-30 10:06 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +                            [css.gitNameIdDescriptionTags]: supportingTemplatesGitx
done

2022-08-30 10:06 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +                              [css.gitNameIdDescriptionTags]: supportingTemplatesGitx
done

2022-08-30 10:12 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +                          !isGitSyncEnabled &&
done

2022-08-30 10:19 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +                                  [css.gitNameIdDescriptionTags]: supportingTemplatesGitx
done

2022-08-30 10:20 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +                              : { entityScope: Scope.ACCOUNT })}
done

2022-08-30 10:21 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
> +                            disableFields={pick(
not required

2022-08-30 11:24 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.tsx
>          ...(!isEmpty(values.repo) && {
Reverted. Need `!isEmpty(values.repo)` right now because this sets `updatedGitDetails` in `useSaveTemplate`.
Will have to refactor later if we want to remove this check

2022-08-30 11:27 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> +      if (supportingTemplatesGitx) {
Not required to reset branch as we always fetch from default only. Confirmed this by testing

2022-08-30 11:27 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> +    templateIdentifier: defaultTo(template.identifier, ''),
done

2022-08-30 11:27 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
>        setTemplate?.(selectedTemplate)
done

2022-08-30 11:28 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> +  React.useEffect(() => {
Cannot find this. Need your review again

2022-08-30 11:29 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> +      ...commonQueryParams,
done

2022-08-30 11:30 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> -    setSelectedTemplate(templates.find(item => item.versionLabel === template.versionLabel))
why

2022-08-30 11:31 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> +  }, [allowStableSelection, templateData])
Its hook dependency

2022-08-30 11:33 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> -          branch: selectedTemplate.gitDetails?.branch
need discussion about why

2022-08-30 11:33 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> -  const showNoResultsView = useMemo(
done

2022-08-30 11:33 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> +  const showErrorInPanel =
done

2022-08-30 11:33 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> +        {(loading || loadingTemplateYaml) && <PageSpinner />}
done

2022-08-30 11:34 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> +        {!supportingTemplatesGitx && !loading && templatesError && (
done

2022-08-30 11:34 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +        },
done

2022-08-30 11:37 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/TemplateStudioSubHeader.tsx
> -        <Container>
done

2022-08-30 12:05 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +          updateStoreMetadata(extraInfo.storeMetadata, updatedGitDetails)
Need `updatedGitDetails`

2022-08-30 12:09 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateDetails/TemplateDetails.tsx
> +                  disabled={allowBranchChange && !!templateYamlError && !selectedBranch}
done

2022-08-30 12:09 UTC, depanshu-dhiman commented on src/framework/Templates/TemplateSelectorContext/useTemplateSelector.ts
> +    [closeTemplateSelector, openTemplateSelector]
done

2022-08-30 12:10 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateInputs/TemplateInputs.tsx
> +    (template as NGTemplateInfoConfigWithGitDetails)?.spec
It was breaking that's why I added

2022-08-30 12:11 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateSelector/TemplateSelector.tsx
> +  }, [selectedTemplate, selectorData?.storeMetadata])
Updated to `storeMetadata`.  `setSelectedTemplate` not needed

2022-08-30 12:13 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateSelector/TemplateSelector.tsx
> +  const isUseDisabled = supportingTemplatesGitx && !selectedTemplate?.yaml
done

2022-08-30 12:15 UTC, depanshu-dhiman commented on src/modules/72-templates-library/hooks/__tests__/useTemplateSelector.test.tsx
> +      parentEntityContext: {}
done

2022-08-30 12:16 UTC, depanshu-dhiman commented on src/modules/10-common/interfaces/RouteInterfaces.ts
> +  storeType?: 'INLINE' | 'REMOTE'
done

2022-08-30 12:47 UTC, depanshu-dhiman commented on src/modules/70-pipeline/utils/getStoreMetadataFromQuery.ts
> +export const getStoreMetadataFromQueryParams = ({ connectorRef, repoName, branch, storeType }: any) => ({
done

2022-08-30 12:48 UTC, depanshu-dhiman commented on src/modules/75-cd/components/PipelineSteps/InfraProvisioning/InfraProvisioningBase.tsx
> +        storeMetadata
no

2022-08-30 12:55 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.module.scss
> +  width: 1160px;
fixed

2022-08-30 12:58 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +  const renderStudioCanvas = isInitializedTemplate && (
I only moved it, this was there earlier as well.

2022-08-30 12:59 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +  const { repoIdentifier, branch } = useQueryParams<GitQueryParams & TemplateStudioQueryParams>()
done

2022-08-30 13:00 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplatePipelineContext/TemplatePipelineContext.tsx
> +          branch: gitDetails?.branch,
Needed. When gitDetails is not there, it explodes

2022-08-30 13:01 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplatePipelineContext/TemplatePipelineContext.tsx
> +        branch: state.gitDetails?.branch,
Needed. When gitDetails is not there, it explodes

2022-08-30 13:02 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateCard/TemplateCard.tsx
> +        {isGitInfoAvailable && (
Branch is also there below, so need to check this

2022-08-30 13:07 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateCard/TemplateCard.tsx
> +              {isGitSyncEnabled && (
done

2022-08-30 13:07 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateCard/TemplateCard.tsx
> +        {isGitInfoAvailable && (
done

2022-08-30 13:10 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateCard/TemplateCard.tsx
> +  const isTemplateRemote = (template as TemplateMetadataSummaryResponse)?.storeType === StoreType.REMOTE
Need discussion

2022-08-30 13:33 UTC, depanshu-dhiman commented on src/modules/70-pipeline/components/PipelineStudio/SavePipelinePopover/SavePipelinePopover.tsx
> +    storeMetadata: {
No need of utility here as it's coming from state. Changed it

2022-08-30 13:33 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateContext/TemplateContext.tsx
> +  gitDetails?: EntityGitDetails
It's required

2022-08-30 13:34 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/TemplateStudioSubHeaderLeftView.tsx
> +                    intent: templateIdentifier !== DefaultNewTemplateId ? Intent.EDIT : Intent.START,
done, simplified

2022-08-30 13:35 UTC, depanshu-dhiman commented on src/modules/70-pipeline/components/PipelineStudio/RightDrawer/RightDrawer.tsx
> +        storeMetadata
Now it does. Had to add it because refactor wasn't possible otherwise

2022-08-30 15:33 UTC, yc147 commented on src/modules/85-sto-steps/components/PipelineStages/SecurityTestsStage/__tests__/SecurityStageHelpers.tsx
> +  gitDetails: {},
Revert

2022-08-30 15:39 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +  const renderStudioCanvas = isInitialized && !isEmpty(template) && (
Removed these checks

2022-08-30 15:49 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +          [css.gitConfigDialog]: !!storeMetadata
Check for `isEmpty`

2022-08-30 19:07 UTC, yc147 submitted a review, later dismissed

2022-08-31 06:08 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +  const renderStudioCanvas = isInitialized && !isEmpty(template) && (
done

2022-08-31 06:08 UTC, depanshu-dhiman commented on src/modules/85-sto-steps/components/PipelineStages/SecurityTestsStage/__tests__/SecurityStageHelpers.tsx
> +  gitDetails: {},
done

2022-08-31 06:08 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> +          [css.gitConfigDialog]: !!storeMetadata
done

2022-08-31 10:34 UTC, depanshu-dhiman commented
Cypress is flaky, passing in local
![Screenshot 2022-08-31 at 4 03 50 PM](https://user-images.githubusercontent.com/101629876/187659309-032f4bee-ea66-4f10-a6b0-9ecb39e663d6.png)

2022-08-31 10:36 UTC, kapilkumawat86 approved these changes

2022-08-31 10:38 UTC, depanshu-dhiman commented
trigger cypress

2022-08-31 11:39 UTC, sunnykesh-harness approved these changes

2022-08-31 12:06 UTC, depanshu-dhiman commented
trigger cypress

2022-08-31 12:13 UTC, merged