feat: [CI-2533]: zero state ci project overview
harness/harness-core-ui pull request #10306
Opened 2022-07-29 21:56 UTC by mtran7

### Summary

#### Screenshots
![image](https://user-images.githubusercontent.com/43422351/181848134-ae97bbbc-c753-49e6-aaa1-02053645d94d.png)
![image](https://user-images.githubusercontent.com/43422351/181848141-8acc4d66-1d00-4668-9db5-21cad50ece06.png)

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-29 21:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10306) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10306) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10306) it.</sub>

2022-08-01 18:44 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 17 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 17 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10306)

2022-08-03 04:06 UTC, udayvunnam approved these changes

2022-08-03 04:06 UTC, udayvunnam commented
perfect!

2022-08-03 09:15 UTC, d1wilko requested changes
Just 1 small issue - other than that it looks good to go :)

2022-08-03 09:15 UTC, d1wilko commented on src/modules/75-ci/pages/dashboard/CIDashboardPage.tsx
> +  // this for detecting whether the project have any pipelines or if pipelines then any execution or not
I find this sentence confusing

2022-08-03 16:48 UTC, vardanbansal-harness approved these changes

2022-08-03 19:03 UTC, mtran7 commented on src/modules/75-ci/pages/dashboard/CIDashboardPage.tsx
> +  // this for detecting whether the project have any pipelines or if pipelines then any execution or not
agreed - removed as it's not a necessary comment

2022-08-04 02:11 UTC, mtran7 commented
retrigger jest

2022-08-04 04:57 UTC, udayvunnam approved these changes

2022-08-04 09:41 UTC, d1wilko approved these changes
LGTM

2022-08-04 15:02 UTC, merged