Handle group search name
harness/harness-core-ui pull request #10308
Opened 2022-07-30 07:45 UTC by pbarapatre10

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-30 07:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10308) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10308) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: pbarapatre10<br/>:x: avinashmadhwani02<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10308) it.</sub>

2022-08-02 04:06 UTC, pbarapatre10 commented
retrigger standards

2022-08-02 05:45 UTC, avinashmadhwani02 requested changes

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/useLinkToSSOProviderModal.module.scss
> +    display: flex;
flex is directly available as Layout/Container property. you can remove from here

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/useLinkToSSOProviderModal.module.scss
> +    text-overflow: ellipsis;
You can use lineClamp property in <Text />

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/useLinkToSSOProviderModal.module.scss
> +    white-space: nowrap !important;
Do we need this for all spans inside wrapper?

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +      ).map(data => {
We can use a single loop instead of filter and map. Try using Array.reduce

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +    return data.description ? <Text>{data.description}</Text> : null
Are we going to leave the cell empty in case of no value? Should we add some placeholder instead? Check how we do in other places

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +                selectedSso?.ssoType === 'SAML'
Is this working? 
I think you can add a condition in Yup itself.

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +          checked={groupSearchRadioSelected?.dn === data.dn}
Value can be stored in formik instead of this state. I just remember the formik hook we can use here - useFormikContext

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +                      {selectedSso?.ssoType === 'LDAP' && (
It will be cleaner to create a separate component for Ldap form.

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +                      {selectedSso?.ssoType === 'LDAP' && (
Adding new forms in the future will follow the same, otherwise this component will become very big and complex

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +                                  setGroupSearchText((e?.target as any)?.value?.trim())
Why typecasting to any?

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +                              <div className={css.wrapper}>No results found</div>
Add no results found in the string framework

2022-08-02 05:45 UTC, avinashmadhwani02 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +                              <div className={css.wrapper}>No results found</div>
Do you need CSS here? Just make use of <Text />

2022-08-02 12:49 UTC, pbarapatre10 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +                selectedSso?.ssoType === 'SAML'
Yes, this is the only way it is working, else the previous SAML scenario was breaking

2022-08-02 12:50 UTC, pbarapatre10 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +    return data.description ? <Text>{data.description}</Text> : null
Yes, we will keep it empty. Have seen in some places that it is left null. Will check this with UX as well once in our next call.

2022-08-03 11:07 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 38 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 38 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10308)

2022-08-03 11:15 UTC, pbarapatre10 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +                              <div className={css.wrapper}>No results found</div>
Done

2022-08-03 11:15 UTC, pbarapatre10 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/useLinkToSSOProviderModal.module.scss
> +    display: flex;
Done!

2022-08-03 11:16 UTC, pbarapatre10 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/useLinkToSSOProviderModal.module.scss
> +    white-space: nowrap !important;
We are using this css at just one place, so Yes we need at all spans

2022-08-03 11:16 UTC, pbarapatre10 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +                      {selectedSso?.ssoType === 'LDAP' && (
Done

2022-08-03 11:17 UTC, pbarapatre10 commented on src/modules/20-rbac/modals/LinkToSSOProviderModal/views/LinkToSSOProviderForm.tsx
> +                                  setGroupSearchText((e?.target as any)?.value?.trim())
Fixed

2022-08-05 08:03 UTC, avinashmadhwani02 approved these changes

2022-08-05 09:56 UTC, swarajcheguri-harness approved these changes

2022-08-05 10:04 UTC, merged