fix: [cds-41153]: add repo name to releaserepo manifest
harness/harness-core-ui pull request #10305
Opened 2022-07-29 20:42 UTC by cjlee01

### Summary

Added the repo name field for the release repo manifest since it was missed during creation of steps

#### Screenshots
![image](https://user-images.githubusercontent.com/92757601/181840212-0d0680b4-55f7-4302-94b8-6a975bc18804.png)

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-29 20:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10305) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10305) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10305) it.</sub>

2022-07-29 22:55 UTC, mtran7 commented on src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoWizard/RepoDetails.tsx
> +const getAccountUrl = (prevStepData?: ConnectorConfigDTO): string => {
can directly return prevStepData?.connectorRef?.connector?.spec?.url || prevStepData?.url

2022-07-29 22:59 UTC, mtran7 commented on src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoWizard/RepoDetails.tsx
> +      if (formData.gitFetchType === 'Branch') {
create an enum for gitFetchType to cover Branch, Commit

2022-07-29 23:01 UTC, mtran7 commented on src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoWizard/RepoDetails.tsx
> +              return true
connectionType === 'Account' & expression type value should require repoName right?

2022-07-29 23:07 UTC, mtran7 commented
Have you looked at how these changes might impact manifest triggers? Usually if manifest has fields that are runtime inputs, it should prompt there as well for your selected manifest & on the Pipeline Input panel. Lemme know if you have questions

2022-07-29 23:12 UTC, mtran7 commented
What happens if this connector value is a runtime input? Does repo name become a runtime input?
<img width="788" alt="image" src="https://user-images.githubusercontent.com/43422351/181859217-a8175a3f-9f7b-41b3-9b38-2c61c9c2c70b.png">

Also, should test if the connector is an expression (if supported), then should repoName be required?

2022-07-30 00:49 UTC, cjlee01 commented on src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoWizard/RepoDetails.tsx
> +      if (formData.gitFetchType === 'Branch') {
fixed

2022-07-30 00:51 UTC, cjlee01 commented on src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoWizard/RepoDetails.tsx
> +const getAccountUrl = (prevStepData?: ConnectorConfigDTO): string => {
fixed

2022-07-30 01:07 UTC, cjlee01 commented on src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoWizard/RepoDetails.tsx
> +              return true
so basically this is checking whether the connector  has a urltype of repository or the connector is not fixed value which will let the validation through since reponame is not needed at those cases

2022-07-30 01:08 UTC, cjlee01 commented
@bhavya-sinha can you review this and see if i missed any places where i would need to add code to for adding this field?

2022-08-01 04:51 UTC, bhavya-sinha requested changes

2022-08-01 04:51 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestInterface.ts
> +  | 'ReleaseRepo'
Please do not add release Repo here. There is a separate interface for Gitops manifest.

2022-08-01 04:51 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/Manifesthelper.ts
> +  ReleaseRepo: 'ReleaseRepo'
same here. Move this to gitops manifest helper

2022-08-01 04:51 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/Manifesthelper.ts
> +  ReleaseRepo: [...gitStoreTypesWithHarnessStoreType, ManifestStoreMap.CustomRemote]
This too

2022-08-01 04:51 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/Manifesthelper.ts
> +  ReleaseRepo: 'pipeline.manifestTypeLabels.ReleaseRepo'
This

2022-08-01 19:03 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 7 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10305)

2022-08-02 22:43 UTC, cjlee01 commented on src/modules/70-pipeline/components/ManifestSelection/Manifesthelper.ts
> +  ReleaseRepo: 'pipeline.manifestTypeLabels.ReleaseRepo'
seperated this out

2022-08-02 22:44 UTC, cjlee01 commented on src/modules/70-pipeline/components/ManifestSelection/Manifesthelper.ts
> +  ReleaseRepo: [...gitStoreTypesWithHarnessStoreType, ManifestStoreMap.CustomRemote]
seperated this out

2022-08-02 22:44 UTC, cjlee01 commented on src/modules/70-pipeline/components/ManifestSelection/Manifesthelper.ts
> +  ReleaseRepo: 'ReleaseRepo'
seperated this out

2022-08-02 22:44 UTC, cjlee01 commented on src/modules/70-pipeline/components/ManifestSelection/ManifestInterface.ts
> +  | 'ReleaseRepo'
seperated this out

2022-08-02 23:25 UTC, mtran7 commented on src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoWizard/ReleaseRepoUtils.ts
> +const getRepoNameBasedonScopeReleaseRepo = (initialValues: ReleaseRepoManifest, prevStepData: any): string => {
BasedOn

2022-08-02 23:27 UTC, mtran7 commented on src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoWizard/RepoDetails.tsx
> +  return prevStepData?.connectorRef?.connector?.spec?.url || prevStepData?.url
can directly return

2022-08-03 01:17 UTC, bhavya-sinha approved these changes

2022-08-03 06:35 UTC, cjlee01 commented on src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoWizard/ReleaseRepoUtils.ts
> +const getRepoNameBasedonScopeReleaseRepo = (initialValues: ReleaseRepoManifest, prevStepData: any): string => {
fixed casing

2022-08-03 06:35 UTC, cjlee01 commented on src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoWizard/RepoDetails.tsx
> +  return prevStepData?.connectorRef?.connector?.spec?.url || prevStepData?.url
<img width="994" alt="image" src="https://user-images.githubusercontent.com/92757601/182540259-9bd54ab6-e916-4fc8-97b7-eb63e0910362.png">
fixed it

2022-08-04 01:18 UTC, bhavya-sinha approved these changes

2022-08-04 06:19 UTC, kapilkumawat86 approved these changes

2022-08-04 17:30 UTC, merged