feat: [CDS-41158]: Change EndTime to EOD for the dashboard APIs
harness/harness-core-ui pull request #10317
Opened 2022-08-01 07:38 UTC by Sagar-Rajput7

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-01 07:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10317) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10317) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10317) it.</sub>

2022-08-24 09:22 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 14 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 14 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10317)

2022-08-26 06:40 UTC, rameshx commented on src/modules/75-cd/pages/dashboard/dashboardUtils.ts
> +export function timeFormatting(timeRange: TimeRangeSelectorProps | null): [number, number] {
Rename `timeFormatting` to `formatTimeRange` or `getFormattedTimeRange`

2022-08-26 06:40 UTC, rameshx commented on src/modules/75-cd/pages/dashboard/dashboardUtils.ts
> +export const validTimeFormat = (timeRange: TimeRangeSelectorProps): TimeRangeSelectorProps => {
this can be renamed too to make it sound like function

2022-08-26 06:40 UTC, rameshx commented on src/modules/75-cd/pages/dashboard/dashboardUtils.ts
> +    timeRange.range[1] = new Date(defaultTo(timeRange.range[1], ''))
We can avoid this mutation so that the function can be a pure function

2022-08-26 17:05 UTC, rameshx requested changes

2022-08-26 17:05 UTC, rameshx commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsContent/ServiceDetailsSummary.tsx
> +  const timeServiceDetail = convertStringToDateTimeRange(serviceTimeRange)
Considering this function:
```
export const convertStringToDateTimeRange = (timeRange: TimeRangeSelectorProps): TimeRangeSelectorProps => {
  const convertedTimeRange = timeRange
  if (typeof timeRange.range[0] === 'string') {
    convertedTimeRange.range[0] = new Date(defaultTo(timeRange.range[0], ''))
    convertedTimeRange.range[1] = new Date(defaultTo(timeRange.range[1], ''))
  }
  return convertedTimeRange
}
```

The passed object (`timeRange`) is mutated so the code in lines 45 and 46 is unnecessary.

---

Util functions like `convertStringToDateTimeRange` shouldn't mutate the arguments. Here's how `convertStringToDateTimeRange` can look like:

```
export const convertStringToDateTimeRange = (timeRange: TimeRangeSelectorProps): TimeRangeSelectorProps => {
    return {...timeRange, range: timeRange.range?.map(el => typeof el === 'string' ? new Date(el) : el)}
}
```

Now `convertStringToDateTimeRange` returns a new object, so the code in lines 45 and 46 is necessary or you can remove them and use the returned object wherever required.

2022-08-29 10:14 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsContent/ServiceDetailsSummary.tsx
> +  const timeServiceDetail = convertStringToDateTimeRange(serviceTimeRange)
Thanks for the explanation

2022-08-29 10:29 UTC, rameshx approved these changes

2022-09-02 09:22 UTC, merged