test: [CDS-40178]: add tests for Command Scripts step
harness/harness-core-ui pull request #10361
Opened 2022-08-03 05:01 UTC by rameshx

### Summary

Adds tests for Command Scripts step

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-03 05:08 UTC, udayvunnam commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    const commandTypeSelectCaret = container
can we have a better query from RTL instead of class?

2022-08-03 05:09 UTC, udayvunnam commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    await act(async () => userEvent.click(within(findPopoverContainer()!).getByText(CommandType.Script)))
Is act needed here when userEvent is used?

2022-08-03 05:10 UTC, udayvunnam commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    expect(queryByNameAttribute('spec.workingDirectory', container)).toBeInTheDocument()
Reserve queryBy for quieres that you expect not to be present. Why queryBy instead of getBy or findBy

2022-08-03 05:12 UTC, udayvunnam requested changes
Remove all queryBy instances where not required.

2022-08-03 06:58 UTC, chetanvekariya-harness requested changes

2022-08-03 06:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    expect(getByDisplayValue(initialValues.spec.destinationPath)).toBeInTheDocument()
Add assertions to check for values of each of these fields

2022-08-03 06:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    await act(async () => userEvent.click(commandTypeSelectCaret!))
We do not need to use act with userEvent. It is needed only when you use fireEvent

2022-08-03 06:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/TailFilesEdit.test.tsx
> +    await act(async () => userEvent.click(tailFilesEditQueries.getByTestId(`remove-tailFile-${index}`)))
Remove act everywhere if you are using userEvent

2022-08-03 06:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/__tests__/CommandScriptsEdit.test.tsx
> +        <TestStepWidget
We should directly use CommandScriptsEdit component and test it. TestStepWidget can be used in test file of CommandScriptsStep.

2022-08-03 06:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/__tests__/CommandScriptsEdit.test.tsx
> +    describe.each([
If possible and not many test cases needs to be written then let's separate this out into individual test cases. This is not readable code.

2022-08-03 06:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/__tests__/CommandScriptsInputSet.test.tsx
> +      <TestStepWidget
Here as well. Let's use CommandScriptsInputSet directly. This test file should not care about parent component

2022-08-03 13:48 UTC, udayvunnam commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    const commandTypeSelectCaret = container
Okay, I see why you did this, some of the Form components are not accessible!

2022-08-04 06:07 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10361)

2022-08-04 06:12 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    const commandTypeSelectCaret = container
Updated the query so that it doesn't rely on class

2022-08-04 06:14 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    await act(async () => userEvent.click(within(findPopoverContainer()!).getByText(CommandType.Script)))
removed `act`s

2022-08-04 06:16 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    expect(queryByNameAttribute('spec.workingDirectory', container)).toBeInTheDocument()
`queryByNameAttribute` is just a util function defined in our App that queries by name attribute using `querySelector`, it's not from testing library

2022-08-04 06:20 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    expect(getByDisplayValue(initialValues.spec.destinationPath)).toBeInTheDocument()
`getByDisplayValue` returns element based on the value

2022-08-04 06:22 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    await act(async () => userEvent.click(commandTypeSelectCaret!))
Removed `act`s. It is not needed for `fireEvent` too.

2022-08-04 06:25 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/__tests__/CommandScriptsEdit.test.tsx
> +    describe.each([
It feels like unnecessary code duplication if we separate these tests are they are very similar.

2022-08-04 06:35 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    expect(getByDisplayValue(initialValues.spec.destinationPath)).toBeInTheDocument()
Add assertions which check values of each field

2022-08-04 06:37 UTC, chetanvekariya-harness submitted a review, later dismissed

2022-08-04 06:45 UTC, rameshx commented
retrigger titlecheck

2022-08-04 06:46 UTC, rameshx commented
trigger cypress

2022-08-04 06:47 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    expect(getByDisplayValue(initialValues.spec.destinationPath)).toBeInTheDocument()
`getByDisplayValue` returns element based on the value

2022-08-04 06:56 UTC, udayvunnam commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +
why queryByNameAttribute and !. We can try reliable test.

2022-08-04 06:57 UTC, udayvunnam commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    })
waitFor shouldn't have these many assertions within. We will waitFor(better yet use findBy) one and all other statemnets should come next.

Why queryBy again ?

2022-08-04 06:58 UTC, udayvunnam commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/TailFilesEdit.test.tsx
> +    initialValues.spec.tailFiles!.forEach(({ tailPattern, tailFile }, index) => {
Why are we overusing !?

2022-08-04 08:13 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +
using `!` as `userEvent.click` doesn't accept `null` but `queryByNameAttribute` could return `null` if the element isn't found (test fails in this case and that's fine)

2022-08-04 08:13 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/CommandEdit.test.tsx
> +    })
updated

2022-08-04 08:13 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/CommandScripts/Commands/__tests__/TailFilesEdit.test.tsx
> +    initialValues.spec.tailFiles!.forEach(({ tailPattern, tailFile }, index) => {
removed `!`

2022-08-04 08:15 UTC, udayvunnam approved these changes

2022-08-04 09:17 UTC, chetanvekariya-harness approved these changes

2022-08-04 09:18 UTC, merged