feat: [SRM-11219]: adding testcases
harness/harness-core-ui pull request #10369
Opened 2022-08-03 11:33 UTC by harshilbits

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-03 11:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10369) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10369) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10369) it.</sub>

2022-08-03 11:34 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10369)

2022-08-04 09:38 UTC, harshilbits commented
retrigger titlecheck

2022-08-04 10:04 UTC, reetika04 approved these changes

2022-08-04 10:06 UTC, harshilbits commented
retrigger jest

2022-08-04 10:25 UTC, devinder-harness requested changes

2022-08-04 10:25 UTC, devinder-harness commented on src/modules/85-cv/components/Notifications/components/SLONotificationRuleRow/SLONotificationRuleRow.constants.ts
> +  { label: 'Error Budget remaining minutes', value: SLOCondition.ERROR_BUDGET_REMAINING_MINUTES },
text should always come from `strings` file

2022-08-04 10:59 UTC, harshilbits commented on src/modules/85-cv/components/Notifications/components/SLONotificationRuleRow/SLONotificationRuleRow.constants.ts
> +  { label: 'Error Budget remaining minutes', value: SLOCondition.ERROR_BUDGET_REMAINING_MINUTES },
Sure , will be making this change in a separate PR. This PR is specifically for testcases.

2022-08-04 11:01 UTC, devinder-harness approved these changes

2022-08-04 11:04 UTC, harshilbits commented on src/modules/85-cv/components/Notifications/components/SLONotificationRuleRow/SLONotificationRuleRow.constants.ts
> +  { label: 'Error Budget remaining minutes', value: SLOCondition.ERROR_BUDGET_REMAINING_MINUTES },
As discussed,  this PR was specifically for testcases. Will make the change in a separate PR as I would have to make change at multiple places.

2022-08-04 11:17 UTC, deepesh-ui commented on src/modules/85-cv/components/Notifications/components/ConfigureMonitoredServiceAlertConditions/__tests__/ConfigureMonitoredServiceAlertConditions.test.tsx
> +    expect(deleteButton).toBeTruthy()
NIT: can we use toBeInTheDocument()

2022-08-04 11:19 UTC, deepesh-ui commented on src/modules/85-cv/components/Notifications/components/ConfigureSLOAlertConditions/__tests__/ConfigureSLOAlertConditions.test.tsx
> +    expect(valueInputField.value).toBe('5')
NIT: expect(valueInputField).toHaveValue('5')

2022-08-04 11:20 UTC, deepesh-ui approved these changes

2022-08-04 11:23 UTC, merged