feat: [CCM-8509]: Misc fixes in dashboard screen
harness/harness-core-ui pull request #10403
Opened 2022-08-04 15:26 UTC by jyotiarora-harness

### Summary

Fixes:
1. Overflow layout 
2. Error handling
3. Empty state handling
4. Free edition banner handling

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-04 15:28 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 9 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 9 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10403)

2022-08-05 05:14 UTC, jenil-harness commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.module.scss
> +  width: min(100%, 1155px);
Why this?

2022-08-05 05:17 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.module.scss
> +  width: min(100%, 1155px);
Due to the min-width changes in core layout overflow was happening in the screen, did the handling for the same

2022-08-05 06:38 UTC, jenil-harness commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.tsx
> +  const isEnterpriseEdition = isEnterprisePlan(licenseInformation, moduleName)
No need to default to Common here.

2022-08-05 06:39 UTC, jenil-harness commented on src/modules/75-ce/pages/perspective-list/PerspectiveListPage.tsx
> +export const NoDataPerspectivePage: (props: NoDataPerspectivePageProps) => JSX.Element = ({ showConnectorModal }) => {
We should move it to a common place

2022-08-05 06:54 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.tsx
> +  const isEnterpriseEdition = isEnterprisePlan(licenseInformation, moduleName)
module can be undefined as well, so needs to do the default handling, should I use the default value as `ModuleName.CE` here?

2022-08-05 07:11 UTC, rajarshee-harness commented on src/modules/75-ce/pages/bi-dashboards/__tests__/BIDashboard.test.tsx
> +          {isEnterpriseEdition ? <BIDashboardData /> : <LevelUpBanner message={'dashboards.upgrade'} />}
Why do we have this condition when `isEnterpriseEdition` is always true?

2022-08-05 08:03 UTC, rishik30 requested changes

2022-08-05 08:03 UTC, rishik30 commented on src/modules/75-ce/pages/bi-dashboards/BIDashboard.tsx
> +  const banner = <LevelUpBanner message={getString('dashboards.upgrade')} />
what's the need of storing it in a variable? Are we using it elsewhere too?

2022-08-05 08:03 UTC, rishik30 commented on src/modules/75-ce/pages/perspective-list/PerspectiveListPage.tsx
> +export const NoDataPerspectivePage: (props: NoDataPerspectivePageProps) => JSX.Element = ({ showConnectorModal }) => {
+1

2022-08-05 13:41 UTC, rajarshee-harness submitted a review, later dismissed

2022-08-05 13:44 UTC, rishik30 approved these changes

2022-08-05 14:04 UTC, rishik30 approved these changes

2022-08-05 15:25 UTC, rajarshee-harness approved these changes

2022-08-06 00:27 UTC, kapilkumawat86 approved these changes

2022-08-06 00:38 UTC, merged