fix: [CDS-40944]: prevent YAML to Visual switch on duplicate identifiers in pipelineTemplates
harness/harness-core-ui pull request #10505
Opened 2022-08-10 13:48 UTC by PratyushGar

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-10 13:50 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 6 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10505)

2022-08-10 14:25 UTC, vkbansal-harness approved these changes

2022-08-10 14:54 UTC, udayvunnam commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
> +import { getDuplicateStepsIdentifiersList } from './PipelineCanvasUtils'
nit: several plurals-  steps, identifiers, list
getDuplicateStepIdentifiers or getDuplicateStepIdentifierList

2022-08-10 14:56 UTC, udayvunnam commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
> +    return true
Is this expected? Can this change include a test?

2022-08-10 15:40 UTC, yc147 commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
> +    return true
This doesn't look write. How can this function return `true` when there are no stages. Function name should be `doesNoHaveDuplicateIdentifiersInYAML` or something like that.

2022-08-10 19:11 UTC, PratyushGar commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
> +    return true
Addressed

2022-08-11 05:00 UTC, vkbansal-harness approved these changes

2022-08-11 05:07 UTC, yc147 commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
>          showError(
Not the right place to show the error. This function is supposed to run a boolean. Moved the logic to show error out side this function.

2022-08-11 05:15 UTC, yc147 requested changes
Not the right place to show the error. This function is supposed to run a boolean. Moved the logic to show error out side this function.

2022-08-11 07:43 UTC, yc147 commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvasUtils.ts
> +  return idMap.filter((element, position, arr) => arr.indexOf(element) !== position)
This algo has non linear time complexity

2022-08-11 07:44 UTC, yc147 commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvasUtils.ts
> +  return idMap.filter((element, position, arr) => arr.indexOf(element) !== position)
Let's keep it for now as the list is not going to be too large. Ideally this should be solved in linear time complexity.

2022-08-11 07:54 UTC, PratyushGar commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvasUtils.ts
> +  return idMap.filter((element, position, arr) => arr.indexOf(element) !== position)
Sure, will address this in the next PR.

2022-08-11 08:10 UTC, yc147 approved these changes

2022-08-11 08:15 UTC, vkbansal-harness approved these changes

2022-08-11 08:16 UTC, merged