feat: [CDS-41528]: Add azure blueprint step
harness/harness-core-ui pull request #10512
Opened 2022-08-10 15:44 UTC by willd0yle

### Summary
Add azure blueprint step

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-10 15:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10512) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10512) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10512) it.</sub>

2022-08-10 15:46 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 321 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 321 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10512)

2022-08-30 10:34 UTC, Tamaraius approved these changes

2022-08-30 13:46 UTC, Tamaraius submitted a review, later dismissed

2022-08-30 16:54 UTC, rameshx requested changes

2022-08-30 16:54 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/AzureBlueprint.tsx
> +    }
This can be followed in the lines below, where there are similar spread syntax usages.

2022-08-30 16:54 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/AzureBlueprintRef.tsx
> +                label="Assignment Name"
Is it okay to not translate these labels?

2022-08-30 16:54 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/AzureBlueprintTypes.types.ts
> +}
I think some of these types are already present. Can we import them instead of defining again?

2022-08-30 16:54 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/InputSteps/__tests__/InputStep.test.tsx
> +    act(() => userEvent.type(timeout, '10m'))
`userEvent` is already wrapped in act

2022-08-30 16:54 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/InputSteps/__tests__/InputStep.test.tsx
> +    const assignmentName = await queryByAttribute('name', container, 'test.spec.configuration.assignmentName')
`queryByAttribute` doesn't return a promise

2022-08-30 16:54 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/InputSteps/__tests__/InputStep.test.tsx
> +    expect(assignmentName).toHaveDisplayValue('test name')
```suggestion
    userEvent.type(assignmentName!, 'test name')
    await waitFor(() => expect(assignmentName).toHaveDisplayValue('test name'))
```

2022-08-30 16:54 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/ScriptWizard/__tests__/ScriptWizard.test.tsx
> +    act(() => userEvent.click(changeText))
All `act`s that wrap `userEvent` or `fireEvent` can be removed

2022-08-30 16:54 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/ScriptWizard/__tests__/ScriptWizard.test.tsx
> +    act(() => userEvent.click(continueButton))
Test ends with clicking the continue button, maybe you can add an assertion after this.

2022-08-30 16:54 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/ScriptWizard/__tests__/ScriptWizard.test.tsx
> +    const newConnectorLabel = await getByText('newLabel pipeline.manifestType.gitConnectorLabel connector')
Unlike `findBy*` queries, `getBy*` queries don't return a promise.

2022-08-30 16:54 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/ScriptWizard/__tests__/ScriptWizard.test.tsx
> +    })
`userEvent.click` shouldn't be in `waitFor`.

2022-08-30 16:54 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/ScriptWizard/__tests__/ScriptWizard.test.tsx
> +    })
`userEvent.click(getByText('back'))` can be moved out of `waitFor` and an assertion can be added to assert something that happens after clicking 'back'.

2022-08-31 04:36 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/AzureBlueprintRef.tsx
> +                label="Assignment Name"
Please remove this and create string constant.

2022-08-31 09:29 UTC, willd0yle commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/AzureBlueprint.tsx
> +    }
Updated to use set from lodash

2022-08-31 09:29 UTC, willd0yle commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/AzureBlueprintTypes.types.ts
> +}
Importing from another azure step as they have the same types for store etc.

2022-08-31 09:29 UTC, willd0yle commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/AzureBlueprintRef.tsx
> +                label="Assignment Name"
Added the missing strings

2022-08-31 09:30 UTC, willd0yle commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/InputSteps/__tests__/InputStep.test.tsx
> +    act(() => userEvent.type(timeout, '10m'))
Updated all userEvents

2022-08-31 09:30 UTC, willd0yle commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/InputSteps/__tests__/InputStep.test.tsx
> +    act(() => userEvent.type(timeout, '10m'))
Removed acts from userEvents

2022-08-31 09:30 UTC, willd0yle commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/InputSteps/__tests__/InputStep.test.tsx
> +    const assignmentName = await queryByAttribute('name', container, 'test.spec.configuration.assignmentName')
Removed await for `queryByAttribute `

2022-08-31 09:31 UTC, willd0yle commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/ScriptWizard/__tests__/ScriptWizard.test.tsx
> +    act(() => userEvent.click(continueButton))
Removed the click as it was not needed.

2022-08-31 09:31 UTC, willd0yle commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/ScriptWizard/__tests__/ScriptWizard.test.tsx
> +    const newConnectorLabel = await getByText('newLabel pipeline.manifestType.gitConnectorLabel connector')
Updated.

2022-08-31 09:32 UTC, willd0yle commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/ScriptWizard/__tests__/ScriptWizard.test.tsx
> +    })
Updated to remove `waitFor`

2022-08-31 09:32 UTC, willd0yle commented on src/modules/75-cd/components/PipelineSteps/AzureBlueprint/ScriptWizard/__tests__/ScriptWizard.test.tsx
> +    })
Updated. Removed the back as it was also left from a previous test rewrite.

2022-08-31 10:04 UTC, Tamaraius approved these changes

2022-08-31 10:24 UTC, rameshx approved these changes

2022-08-31 10:52 UTC, merged