feat: [CCM-8133]: Cloud Integration
harness/harness-core-ui pull request #10530
Opened 2022-08-11 07:35 UTC by rajarshee-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-11 07:37 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 358 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 358 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10530)

2022-08-25 09:14 UTC, rishik30 requested changes

2022-08-25 09:14 UTC, rishik30 commented on src/modules/75-ce/components/CloudVisibilityModal/steps/EnableCostVisibilityStep.tsx
> +    cancelButtonText: 'Ignore',
use strings here

2022-08-25 09:14 UTC, rishik30 commented on src/modules/75-ce/components/CloudVisibilityModal/steps/EnableCostVisibilityStep.tsx
> +            onClick={async () => {
why do we have async function here?

2022-08-25 09:14 UTC, rishik30 commented on src/modules/75-ce/components/CreateConnector/CreateConnector.tsx
> +      list.push({ icon: 'service-kubernetes', title: 'Kubernetes' })
move titles to strings file

2022-08-25 15:55 UTC, rajarshee-harness commented on src/modules/75-ce/components/AutoStoppingModal/steps/InstallComponents.tsx
> +      <Text font={{ variation: FontVariation.BODY }} color={Color.GREY_600}>
I guess I did it so that p elements inherit `<Text>`'s style. Replaced it by iterating over the points.

2022-08-25 15:55 UTC, rajarshee-harness commented on src/modules/75-ce/components/AutoStoppingModal/steps/InstallComponents.tsx
> +        <p>{`4. ${getString('connectors.ceK8.providePermissionsStep.fileDescription.info4')}`}</p>
Done

2022-08-25 15:55 UTC, rajarshee-harness commented on src/modules/75-ce/components/CloudIntegrationTabs/CloudAccountsTab.tsx
> +          window.open(`${baseUrl}#${route}`)
This does open the link in a new tab for me.

2022-08-25 15:55 UTC, rajarshee-harness commented on src/modules/75-ce/components/AutoStoppingModal/steps/CreateSecret.tsx
> +                window.open(`${window.location.origin}/#/account/${accountId}/access-management/api-keys`)
This does open the link for me in a new tab.

2022-08-26 02:36 UTC, rajarshee-harness commented
retrigger coverage

2022-08-26 04:47 UTC, rajarshee-harness commented
retrigger coverage

2022-08-26 04:59 UTC, rajarshee-harness commented
retrigger jest

2022-08-26 05:44 UTC, jenil-harness commented on src/modules/75-ce/components/CloudIntegrationTabs/CloudAccountsTab.tsx
> +import { Menu, Popover, PopoverInteractionKind, Position, Spinner } from '@blueprintjs/core'
Spinner from blueprint?

2022-08-26 05:45 UTC, jenil-harness commented on src/modules/75-ce/components/CloudIntegrationTabs/CloudAccountsTab.tsx
> +          ;(column as any).openConnectorModal(true, connectorType, { connectorInfo: row.original.connector })
semicolon seems unnecessary

2022-08-26 07:08 UTC, rajarshee-harness commented on src/modules/75-ce/components/CloudIntegrationTabs/CloudAccountsTab.tsx
> +import { Menu, Popover, PopoverInteractionKind, Position, Spinner } from '@blueprintjs/core'
Replaced it `PageSpinner`

2022-08-26 07:10 UTC, rajarshee-harness commented on src/modules/75-ce/components/CloudIntegrationTabs/CloudAccountsTab.tsx
> +          ;(column as any).openConnectorModal(true, connectorType, { connectorInfo: row.original.connector })
Prettier adds this when casting at the start of line.

2022-08-26 07:26 UTC, rajarshee-harness commented
retrigger coverage

2022-08-26 07:27 UTC, jenil-harness commented on src/modules/75-ce/components/CloudIntegrationTabs/CloudAccountsTab.tsx
> +      types: ['CEAws', 'GcpCloudCost', 'CEAzure']
we don't have types for this?

2022-08-26 07:30 UTC, jenil-harness commented on src/modules/75-ce/components/CloudIntegrationTabs/K8sClustersTab.tsx
> +        <ReactTimeago date={status?.lastTestedAt || status?.testedAt || ''} />
What does it show when we pass it `''`?

2022-08-26 08:25 UTC, rajarshee-harness commented on src/modules/75-ce/components/CloudIntegrationTabs/CloudAccountsTab.tsx
> +      types: ['CEAws', 'GcpCloudCost', 'CEAzure']
We did, have replaced them.

2022-08-26 08:25 UTC, rajarshee-harness commented on src/modules/75-ce/components/CloudIntegrationTabs/K8sClustersTab.tsx
> +        <ReactTimeago date={status?.lastTestedAt || status?.testedAt || ''} />
It doesn't show anything. Similar condition is also used for status in connectors list page in account resources.

2022-08-26 08:45 UTC, rajarshee-harness commented on src/modules/75-ce/components/CloudIntegrationTabs/K8sClustersTab.tsx
> +  const isStatusSuccess = status?.status === 'SUCCESS'
Done

2022-08-26 08:45 UTC, rajarshee-harness commented on src/modules/75-ce/components/CloudIntegrationTabs/K8sClustersTab.tsx
> +  const isConnectorStatusSuccess = ccmk8sConnectorList?.[0]?.status?.status === 'SUCCESS'
Done

2022-08-26 08:55 UTC, rishik30 approved these changes

2022-08-26 09:01 UTC, praneshg239 approved these changes

2022-08-26 09:05 UTC, kapilkumawat86 approved these changes

2022-08-26 09:06 UTC, merged