fix: [CDS-41389]: added runtime support in env V2 with BE support for azure web app
harness/harness-core-ui pull request #10578
Opened 2022-08-12 10:55 UTC by vikrant-harness

### Summary

With the new env entity in place we don't have access to the fixed values that were set in the studio so we needed new API's to fetch those on the basis of env id and infra id

#### Screenshots

https://user-images.githubusercontent.com/106532291/184340347-7a13af58-5f51-4acd-a93d-687982b3ebdf.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-12 10:57 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 444 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 444 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10578)

2022-08-12 11:02 UTC, vikrant-harness commented
retrigger titlecheck

2022-08-12 12:42 UTC, AshwinBhatkal-Harness approved these changes

2022-08-12 13:31 UTC, depanshu-dhiman commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecInputForm.tsx
> +      getMultiTypeFromValue(connector) !== MultiTypeInputType.RUNTIME &&
I can see that `getMultiTypeFromValue(connector)` is getting called from multiple places, can this be stored in a variable and reused? Same for any other parameter like `subscriptionId`, `environmentRef`, etc

2022-08-12 13:41 UTC, depanshu-dhiman commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecInputForm.tsx
> +                if (fetchResourceUsingEnvId()) {
Shouldn't this be an else if? Unless there is a case where `refetchResourceGroupsV2` and `refetchResourceGroups` both calls are required.
I don't have full context so idk if 2 calls are required or not, but this looks like there can be a condition when both APIs will be called.

2022-08-12 13:41 UTC, depanshu-dhiman requested changes
Minor comments

2022-08-15 06:21 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecInputForm.tsx
> +      getMultiTypeFromValue(connector) !== MultiTypeInputType.RUNTIME &&
@depanshu-dhiman changed this in the latest commit

2022-08-15 06:21 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecInputForm.tsx
> +                if (fetchResourceUsingEnvId()) {
@depanshu-dhiman done

2022-08-15 06:32 UTC, vikrant-harness commented
retrigger jest

2022-08-15 06:57 UTC, vikrant-harness commented
retrigger jest

2022-08-15 11:40 UTC, Eric761 submitted a review, later dismissed

2022-08-16 10:49 UTC, vikrant-harness commented
trigger cypress

2022-08-16 11:30 UTC, YounixIO approved these changes

2022-08-16 11:57 UTC, Sagar-Rajput7 approved these changes

2022-08-16 12:25 UTC, depanshu-dhiman approved these changes

2022-08-16 13:18 UTC, Sagar-Rajput7 approved these changes

2022-08-16 13:20 UTC, YounixIO approved these changes

2022-08-16 13:41 UTC, merged