fix: [CDS-40398]: Show reconcile dialog when pipeline/template save fails
harness/harness-core-ui pull request #10635
Opened 2022-08-18 05:48 UTC by yc147

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-18 05:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10635) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10635) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10635) it.</sub>

2022-08-18 05:49 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10635)

2022-08-20 14:34 UTC, depanshu-dhiman commented on src/modules/70-pipeline/components/PipelineStudio/SaveTemplateButton/useSaveAsTemplate.tsx
> +      showError(getRBACErrorMessage(error), undefined, 'template.save.template.error')
Typecast error as RBACError.

2022-08-20 14:39 UTC, depanshu-dhiman commented on src/modules/70-pipeline/utils/useSaveTemplate.ts
> +    const response = await updateExistingTemplateLabelPromise({
This function does not exist anymore, please update swagger and use `updateExistingTemplateVersionPromise` everywhere

2022-08-20 14:44 UTC, depanshu-dhiman commented on src/modules/70-pipeline/utils/useSaveTemplate.ts
> -  const { isGitSyncEnabled: isGitSyncEnabledForProject, gitSyncEnabledOnlyForFF } = React.useContext(AppStoreContext)
These FFs are used in multiple places. For gitsync, there was a different error experience it seems, like setLoading was being called conditionally, showError(getRBACErrorMessage(error)) was being called conditionally.
Is this confirmed that it's not the case anymore?

2022-08-20 14:48 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> -  const { isGitSyncEnabled: isGitSyncEnabledForProject, gitSyncEnabledOnlyForFF } = React.useContext(AppStoreContext)
Same here. Please make sure gitSync doesn't break as gitSimplification changes will also need to be merged soon.

2022-08-20 14:50 UTC, depanshu-dhiman requested changes
Please address the comments

2022-08-20 14:52 UTC, yc147 commented on src/modules/70-pipeline/utils/useSaveTemplate.ts
> -  const { isGitSyncEnabled: isGitSyncEnabledForProject, gitSyncEnabledOnlyForFF } = React.useContext(AppStoreContext)
Yes

2022-08-20 14:52 UTC, yc147 commented on src/modules/70-pipeline/utils/useSaveTemplate.ts
> +    const response = await updateExistingTemplateLabelPromise({
Not required for this changes.

2022-08-20 14:53 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
> -  const { isGitSyncEnabled: isGitSyncEnabledForProject, gitSyncEnabledOnlyForFF } = React.useContext(AppStoreContext)
Yes

2022-08-20 14:54 UTC, yc147 commented on src/modules/70-pipeline/components/PipelineStudio/SaveTemplateButton/useSaveAsTemplate.tsx
> +      showError(getRBACErrorMessage(error), undefined, 'template.save.template.error')
Doesn't make any difference.

2022-08-20 15:17 UTC, depanshu-dhiman approved these changes

2022-08-20 15:46 UTC, kapilkumawat86 approved these changes

2022-08-20 15:46 UTC, merged