fix: remove coming soon banner and disabled unselected types on edit
harness/harness-core-ui pull request #10829
Opened 2022-08-27 11:46 UTC by vikrant-harness

### Summary

remove coming soon banner and disabled unselected types on edit

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-27 11:49 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10829)

2022-08-27 11:52 UTC, vikrant-harness commented
retrigger titlecheck

2022-08-27 12:50 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
> +        let itemContent: JSX.Element = <></>
Both these conditions can be combined in one. 
`if (isReadonly && item.value === selectedValue || !isReadonly) ? () : ()`

Also you can spread the item value in map itself.

2022-08-28 08:21 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
> +        let itemContent: JSX.Element = <></>
Added this in latest commit

2022-08-29 07:12 UTC, vkbansal-harness requested changes

2022-08-29 07:12 UTC, vkbansal-harness commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
> +        let itemContent: JSX.Element = <></>
use `filter` to filter out items

2022-08-29 07:31 UTC, chetanvekariya-harness requested changes

2022-08-29 07:31 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
> +                disabled={item.disabled || isReadonly}
isReadyonly not needed here if you are not reaching here if isReadonly = true.
Also, I think you should show disabled deployment type tile if isReadonly = true

2022-08-29 07:31 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
> +              {allowDisabledItemClick ? (
Please remove this. allowDisabledItemClick was true only for CG deployment type. For NG, we don't need to allow it.

2022-08-29 07:35 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
> +        let itemContent: JSX.Element = <></>
@vkbansal-harness addressed this in latest commit

2022-08-29 08:08 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
> +                disabled={item.disabled || isReadonly}
Done as discussed

2022-08-29 08:08 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
> +              {allowDisabledItemClick ? (
@chetanvekariya-harness Addressed this in latest commit

2022-08-29 08:34 UTC, vkbansal-harness approved these changes

2022-08-29 08:53 UTC, chetanvekariya-harness approved these changes

2022-09-01 04:40 UTC, merged