feat: [SCM-1]: Initial UI structure for SCM/Gitness MFE
harness/harness-core-ui pull request #10881
Opened 2022-08-29 23:08 UTC by tan-nhu

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-29 23:08 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield.svg) Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10881)

2022-08-29 23:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10881) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10881) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10881) it.</sub>

2022-08-29 23:49 UTC, tan-nhu commented
retrigger titlecheck

2022-08-31 19:46 UTC, tan-nhu commented
trigger cypress

2022-09-01 22:32 UTC, mtran7 commented on src/modules/10-common/RouteDefinitions.ts
> +  toSCMPullRequestDetail: withAccountId(
toSCMPullRequestDetails

2022-09-01 22:32 UTC, mtran7 commented on src/modules/10-common/RouteDefinitions.ts
> +  toSCMCommitDetail: withAccountId(
toSCMCommitDetails

2022-09-01 22:34 UTC, mtran7 commented on src/modules/10-common/RouteDefinitions.ts
> +      prId
suggestion to always calls id as `pullRequestId` instead of prId

2022-09-01 22:41 UTC, mtran7 commented on src/modules/10-common/RouteDefinitions.ts
> +      prId
Also, a question for Product... but do we want to call it Pull Request or Merge Request? Pull Request is more familiar because of GitHub but Merge Request may make more sense? 
https://blog.mergify.com/pull-request-vs-merge-request-whats-the-difference/

“. . . GitHub and Bitbucket choose the name “pull request” because the first manual action is to pull the feature branch. Tools such as GitLab and others choose the name “merge request” because the final action is to merge the feature branch.”

2022-09-01 23:09 UTC, tan-nhu commented on src/modules/10-common/RouteDefinitions.ts
> +  toSCMCommitDetail: withAccountId(
Done!

2022-09-01 23:09 UTC, tan-nhu commented on src/modules/10-common/RouteDefinitions.ts
> +      prId
Done!

2022-09-02 01:33 UTC, kapilkumawat86 approved these changes
approved with one comment

2022-09-02 01:52 UTC, tan-nhu commented on configs/webpack.common.js
> +    'scm/RepoFileDetail',
This looks similar to STO/OPA modules in which there are multiple views in one MFE app. For SCM they are not defined yet, just place-holders for now. These will be changed when we do the actual implementation.

2022-09-02 01:56 UTC, cseverino789 approved these changes

2022-09-02 02:06 UTC, kapilkumawat86 commented on configs/webpack.common.js
> +    'scm/RepoFileDetail',
ok

2022-09-02 04:38 UTC, merged

2022-09-02 04:41 UTC, abhinavrastogi-harness requested changes

2022-09-02 04:41 UTC, abhinavrastogi-harness commented on .swcrc
> +      "@scm/*": ["modules/60-scm/*"],
i am expecting SCM to be a top-level module (evident from the screenshot).
Any reason it's on layer 60 and not 75 like other modules (CD, CI etc).
Keeping it on layer 60 will allow other modules to import from it, making separation harder in the future.

2022-09-02 04:41 UTC, abhinavrastogi-harness commented on configs/webpack.common.js
> +const enableSCM = process.env.ENABLE_SCM !== 'false'
the `!== false` condition is to be used for GA modules, because it defaults to true.
I'd suggest to use `=== true` for SCM so that we control where the remote entry gets loaded.

2022-09-02 04:41 UTC, abhinavrastogi-harness commented on configs/webpack.common.js
> +  const scmModules = [
why are all pages mounted as separate apps? cant we create one scm app to keep the integration clean?
Chaos has done it that way already, and it works for top-level modules as expected.

2022-09-02 04:41 UTC, abhinavrastogi-harness commented on src/modules/10-common/RouteDefinitions.ts
> +  toSCMHome: withAccountId(() => `/scm/home`),
SCM routes should be in the child app. keeping it here defeats the purpose of a MFE.
to make any changes, SCM releases will be tied to NGUI.

2022-09-02 04:41 UTC, abhinavrastogi-harness commented on src/modules/10-common/interfaces/RouteInterfaces.ts
> +  extends RequireField<
why this complex type pick? what the goal here?

2022-09-02 04:41 UTC, abhinavrastogi-harness commented on src/modules/60-scm/RouteDestinations.tsx
> +  useEffect(() => {
why do we need a useeffect? cant we just return a `<Redirect>` component like other existing root redirects we already have?

2022-09-02 04:41 UTC, abhinavrastogi-harness commented on src/modules/RouteDestinations.tsx
> +      {SCM_ENABLED ? SCMRoutes.props.children : null}
can we move this to the end of the list? just to avoid any future collisions with common routes like connectors/templates etc.

2022-09-02 04:53 UTC, tan-nhu commented on .swcrc
> +      "@scm/*": ["modules/60-scm/*"],
Per plan, SCM would be used from CI and CD module (use SCM as Git source code management before build/deployment).

2022-09-02 04:54 UTC, tan-nhu commented on configs/webpack.common.js
> +const enableSCM = process.env.ENABLE_SCM !== 'false'
Will make the change in the follow up PR

2022-09-02 06:06 UTC, tan-nhu commented on configs/webpack.common.js
> +  const scmModules = [
It depends on the MFE app though. For example, OPA has an App that is mounted as a whole under some separated endpoints, but also has separated views that are mounted in existing modules such as in a tab (Policy Evaluations) in a pipeline execution; Policy Sets in pipeline config, etc...

Again, these are just place-holders as we don't have anything yet in SCM MFE. These could be changed later on.

2022-09-02 06:11 UTC, tan-nhu commented on src/modules/10-common/RouteDefinitions.ts
> +  toSCMHome: withAccountId(() => `/scm/home`),
Not really. A MFE app and its views can be mounted in Harness Platform differently from its standalone version. To give an example, OPA is mounted in three places when being embedded in Harness (Account, Org, Project), plus its views are mounted inside CI/CD pipelines. In standalone version, there's only one app with much simpler routing scheme.

SCM will have two different routing schemes for its embedded and standalone version. They don't look the same as in standalone version, there would be no Harness entities such as org, project, etc...

2022-09-02 06:13 UTC, tan-nhu commented on src/modules/10-common/interfaces/RouteInterfaces.ts
> +  extends RequireField<
It allows to enforce individual fields as required.