feat: [SRM-11694]: fixing multiple scenarios in templates, verify step and doing enhancements
harness/harness-core-ui pull request #10911
Opened 2022-08-30 15:30 UTC by harshilbits

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-30 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10911) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10911) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10911) it.</sub>

2022-08-30 15:32 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 7 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10911)

2022-08-31 16:22 UTC, tan-nhu approved these changes

2022-09-01 03:54 UTC, deepesh-ui commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationInputSetStep/components/TemplatisedRunTimeMonitoredService/TemplatisedRunTimeMonitoredService.tsx
> +        const spec = healthSource?.spec || {}
we are replicating logic from 
`HealthSourceInputset/components/HealthSourceInputsetForm/HealthSourceInputsetForm.tsx`
Shall we move the common code to a util ?

2022-09-01 04:26 UTC, praneshg239 commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationWidget/components/ContinousVerificationWidgetSections/components/SelectMonitoredServiceType/components/MonitoredServiceInputTemplatesHealthSources/MonitoredServiceInputTemplatesHealthSources.tsx
> +                          if (input.name !== 'identifier' && input.name !== 'name') {
move `'identifier'` and `'name'` to constants

2022-09-01 04:30 UTC, praneshg239 commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/utils.ts
> +  const monitoredServiceTemplateSpec = omit(spec?.monitoredService?.spec, ['monitoredServiceRef'])
wrap the whole function under 

```ts
if(spec?.monitoredService)
```

So that we no need to use `spec?.monitoredService?.` optional chaining everywhere else.

2022-09-01 04:32 UTC, praneshg239 commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/utils.ts
> +  path = `${path}.${hasQueries ? 'queries' : 'metricDefinitions'}`
simply return 

```ts
return `${path}.${hasQueries ? 'queries' : 'metricDefinitions'}`
```

2022-09-01 04:34 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/MonitoredServiceInputSetsTemplate/MonitoredServiceInputSetsTemplate.utils.ts
> +    case 'messageIdentifier':
NIT: we should refactor this file to take the string from constants

2022-09-01 04:35 UTC, praneshg239 commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationWidget/components/ContinousVerificationWidgetSections/components/SelectMonitoredServiceType/components/MonitoredServiceInputTemplatesHealthSources/MonitoredServiceInputTemplatesHealthSources.tsx
> +                } else if (input.name !== 'metricDefinitions' && input.name !== 'queries') {
move `'metricDefinitions'` and `'queries'` to constants

2022-09-01 04:36 UTC, praneshg239 requested changes
please check

2022-09-01 06:34 UTC, harshilbits commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/utils.ts
> +  const monitoredServiceTemplateSpec = omit(spec?.monitoredService?.spec, ['monitoredServiceRef'])
`spec?.monitoredService?.spec` is used only at one place.

2022-09-01 06:39 UTC, harshilbits commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationInputSetStep/components/TemplatisedRunTimeMonitoredService/TemplatisedRunTimeMonitoredService.tsx
> +        const spec = healthSource?.spec || {}
I have already moved few functions to utils : `src/modules/85-cv/components/PipelineSteps/ContinousVerification/utils.ts`

`getMetricDefinitions`
`doesHealthSourceHasQueries`
`getMetricDefinitionPath`

Above are the functions moved to utils , please feel free to reuse them.

2022-09-01 10:10 UTC, harshilbits commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationWidget/components/ContinousVerificationWidgetSections/components/SelectMonitoredServiceType/components/MonitoredServiceInputTemplatesHealthSources/MonitoredServiceInputTemplatesHealthSources.tsx
> +                } else if (input.name !== 'metricDefinitions' && input.name !== 'queries') {
done.

2022-09-01 10:11 UTC, harshilbits commented on src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationWidget/components/ContinousVerificationWidgetSections/components/SelectMonitoredServiceType/components/MonitoredServiceInputTemplatesHealthSources/MonitoredServiceInputTemplatesHealthSources.tsx
> +                          if (input.name !== 'identifier' && input.name !== 'name') {
done.

2022-09-01 10:15 UTC, harshilbits commented
retrigger titlecheck

2022-09-01 10:24 UTC, harshilbits commented
retrigger jest

2022-09-01 11:52 UTC, deepesh-ui approved these changes

2022-09-01 12:09 UTC, praneshg239 approved these changes

2022-09-01 12:19 UTC, merged