feat: [PIE-5113]: run time changes for timeout field for allowed values
harness/harness-core-ui pull request #10919
Opened 2022-08-31 11:36 UTC by dhruvUpadhyay07

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-08-31 11:41 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 13 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 13 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10919)

2022-08-31 13:36 UTC, ishantmehtaharness commented on src/modules/10-common/components/ConfigureOptions/ConfigureOptions.tsx
> +  allowedValuesType?: string
This is not needed, since ConfigureOptionsProps is extending ConfigureOptionsDialogProps
and allowedValuesType is there in ConfigureOptionsDialogProps

2022-08-31 13:38 UTC, ishantmehtaharness commented on src/modules/70-pipeline/components/InputSetView/utils/utils.tsx
> +  template: ServiceSpec | HarnessApprovalData
We can change it to any since there will be a lot of templates for different steps.

2022-08-31 13:39 UTC, ishantmehtaharness commented on src/modules/70-pipeline/components/InputSetView/TimeoutFieldInputSetView/TimeoutFieldInputSetView.tsx
> +  fieldPath: string
https://harness.slack.com/archives/C03RWNB0L1M/p1661940915879239
As discussed here, we might rename these to name and label

2022-09-01 11:11 UTC, dhruvUpadhyay07 commented
retrigger titlecheck

2022-09-01 11:23 UTC, ishantmehtaharness commented on src/modules/70-pipeline/components/InputSetView/utils/utils.tsx
> +        label={labelKey}
Changes in this file are not required. These are already done. Please rebase

2022-09-01 11:45 UTC, chetanvekariya-harness requested changes

2022-09-01 11:45 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/InputSetView/TimeoutFieldInputSetView/TimeoutFieldInputSetView.tsx
> +  disabled?: boolean | undefined
`?` and `undefined` both are not needed. Please use one of them.

2022-09-01 11:45 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/InputSetView/TimeoutFieldInputSetView/TimeoutFieldInputSetView.tsx
> +  readonly?: boolean
disabled is there. This prop is not needed.

2022-09-01 11:45 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/InputSetView/TimeoutFieldInputSetView/TimeoutFieldInputSetView.tsx
> +    name: !isEmpty(finalPath) ? `${finalPath}.timeout` : 'timeout',
Every field might already be doing this. So, while consuming component finalPath will be one extra prop to pass. Instead just pass name and use it here.

2022-09-01 11:45 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/InputSetView/TimeoutFieldInputSetView/TimeoutFieldInputSetView.tsx
> +      multiTypeDurationProps={{
Pass this as a prop named multiTypeDurationProps and use it here.

2022-09-01 11:45 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/InputSetView/TimeoutFieldInputSetView/TimeoutFieldInputSetView.tsx
> +      className={stepCss.checkbox}
Pass className from parent component as a prop and use it here.

2022-09-01 11:45 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/InputSetView/utils/utils.tsx
> +        label={labelKey}
+1

2022-09-01 13:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10919) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=10919) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dhruvUpadhyay07<br/>:x: ishantmehtaharness<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=10919) it.</sub>

2022-09-01 14:34 UTC, ishantmehtaharness approved these changes

2022-09-01 14:50 UTC, dhruvUpadhyay07 commented
retrigger jest

2022-09-01 15:00 UTC, chetanvekariya-harness approved these changes

2022-09-01 15:51 UTC, ishantmehtaharness approved these changes

2022-09-02 00:44 UTC, kapilkumawat86 approved these changes
approved but fix any

2022-09-02 00:44 UTC, kapilkumawat86 commented on src/modules/70-pipeline/components/InputSetView/utils/utils.tsx
> +  template: any
can we remove this any and use record or generic types

2022-09-02 03:24 UTC, merged