chore: [CDS-42624]: added unique tooltips for infra update secret field to support tooltips
harness/harness-core-ui pull request #11052
Opened 2022-09-06 09:31 UTC by vikrant-harness

### Summary

added unique tooltips for infra update secret field to support tooltips 

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

## [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-06 09:33 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11052)

2022-09-06 09:34 UTC, vikrant-harness commented
retrigger titlecheck

2022-09-06 09:37 UTC, vikrant-harness commented
retrigger titlecheck

2022-09-06 10:31 UTC, vikrant-harness commented
trigger cypress

2022-09-06 11:07 UTC, chetanvekariya-harness requested changes

2022-09-06 11:07 UTC, chetanvekariya-harness commented on src/modules/30-secrets/components/MutiTypeSecretInput/MultiTypeSecretInput.tsx
> +      label={label ? <HarnessDocTooltip tooltipId={dataTooltipId} labelText={label} /> : label}
Why is ternary needed ? Is't **label** required field ?

2022-09-06 11:07 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraDefinition/DeployInfraDefinition.tsx
> +        return 'deploymentTypeInfraDefinitionMethod'
If you are changing existing tooltip anchor already then let's make this function short and maintainable.
`const getSelectInfrastructureTypeHeaderToolTipId = (selectedDeploymentType) => ${selectedDeploymentType}InfraDefinitionMethod`

2022-09-06 11:07 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraDefinition/DeployInfraDefinition.tsx
> +                tooltipId={getSelectInfrastructureTypeUniqueToolTipId()}
I think this change will required change in tooltip repo. I hope you are aware of that.

2022-09-06 11:10 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraDefinition/DeployInfraDefinition.tsx
> +        return 'deploymentTypeInfraDefinitionMethod'
Sure will make this change , i am planning to extract tooltip change for infra in a seperate pr and multitype secret in a seperate pr

2022-09-06 11:17 UTC, vikrant-harness commented on src/modules/30-secrets/components/MutiTypeSecretInput/MultiTypeSecretInput.tsx
> +      label={label ? <HarnessDocTooltip tooltipId={dataTooltipId} labelText={label} /> : label}
No @chetanvekariya-harness the label is an optional field

2022-09-06 11:38 UTC, chetanvekariya-harness submitted a review, later dismissed

2022-09-06 11:38 UTC, chetanvekariya-harness commented on src/modules/30-secrets/components/MutiTypeSecretInput/MultiTypeSecretInput.tsx
> +    props.tooltipProps?.dataTooltipId || tooltipContext?.formName ? `${tooltipContext?.formName}_${name}` : ''
Prefer using `defaultTo` to avoid increase in cognitive complexity

2022-09-06 12:15 UTC, chetanvekariya-harness submitted a review, later dismissed

2022-09-06 15:32 UTC, kapilkumawat86 approved these changes

2022-09-09 15:20 UTC, YounixIO submitted a review, later dismissed

2022-09-09 17:14 UTC, vikrant-harness commented
trigger cypress

2022-09-09 17:45 UTC, vikrant-harness commented
trigger cypress

2022-09-10 05:14 UTC, vikrant-harness commented
trigger cypress

2022-09-10 07:26 UTC, vikrant-harness commented
trigger cypress

2022-09-13 09:56 UTC, YounixIO approved these changes

2022-09-13 09:57 UTC, Sagar-Rajput7 approved these changes

2022-09-13 09:59 UTC, merged