fix: [CDS-41374]: Fix incorrect condition
harness/harness-core-ui pull request #11068
Opened 2022-09-06 17:01 UTC by depanshu-dhiman

### Summary
Getting NPE in Templates UI. Fix for that.
RCA: https://github.com/harness/harness-core-ui/commit/eb81d2210136c3e018914fb59055aba4eb893350

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

## [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-06 17:03 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11068)

2022-09-07 01:50 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/DeployServiceStep/DeployServiceEntityInputStep.tsx
> +  if (!services?.length || !inputSetData?.readonly) {
```suggestion
  if (!services?.length || inputSetData?.readonly) {
```

2022-09-07 03:33 UTC, bhavya-sinha requested changes

2022-09-07 03:33 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/DeployServiceStep/DeployServiceEntityInputStep.tsx
> +  if (!services?.length || !inputSetData?.readonly) {
This will lead to another bug https://harness.atlassian.net/browse/CDS-41374

The above implementation is correct

2022-09-07 05:57 UTC, depanshu-dhiman commented
Closing as this might not suffice.

2022-09-07 05:57 UTC, closed without merging