feat: [SRM-11820] Update applicaiton tier on changing connector
harness/harness-core-ui pull request #11106
Opened 2022-09-08 04:50 UTC by deepesh-ui

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

## [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-08 04:52 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11106)

2022-09-09 12:28 UTC, praneshg239 requested changes

2022-09-09 12:28 UTC, praneshg239 commented on src/modules/85-cv/components/CloudMetricsHealthSource/CloudMetricsHealthSource.tsx
> +                          if (!formikProps?.values?.query?.length) {
shall we avoid return here by wrapping in `if(formikProps?.values?.query?.length{})`?

2022-09-09 12:28 UTC, praneshg239 commented on src/modules/85-cv/pages/health-source/connectors/Dynatrace/components/DynatraceMetricPacksToService/DynatraceMetricPacksToService.tsx
> +                <></>
NIT: shall we return `null` if something is not present? So that it will be easy for testing

2022-09-09 12:28 UTC, praneshg239 commented on src/modules/85-cv/pages/health-source/connectors/AppDynamics/Components/AppDCustomMetricForm/AppDCustomMetricForm.tsx
> +                        isConnectorRuntimeOrExpression || isApplicationRuntimeOrExpression || isTierRuntimeOrExpression
move this logic to a function

2022-09-09 12:54 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/AppDynamics/Components/AppDCustomMetricForm/AppDCustomMetricForm.tsx
> +                        isConnectorRuntimeOrExpression || isApplicationRuntimeOrExpression || isTierRuntimeOrExpression
done

2022-09-09 12:54 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/Dynatrace/components/DynatraceMetricPacksToService/DynatraceMetricPacksToService.tsx
> +                <></>
done

2022-09-09 12:54 UTC, deepesh-ui commented on src/modules/85-cv/components/CloudMetricsHealthSource/CloudMetricsHealthSource.tsx
> +                          if (!formikProps?.values?.query?.length) {
done

2022-09-09 15:56 UTC, merged