feat: [PL-26212]: Use Harness FF client SDK for feature flags
harness/harness-core-ui pull request #11162
Opened 2022-09-09 16:36 UTC by knagurski

TBA

2022-09-09 16:38 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 23 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 23 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11162)

2022-09-12 12:06 UTC, udayvunnam commented
:tada: LGTM! @knagurski how are we planning the transition? Entire App or by MFE or individual page/team on their own

2022-09-12 12:06 UTC, udayvunnam approved these changes

2022-09-12 12:13 UTC, willd0yle submitted a review, later dismissed

2022-09-12 12:38 UTC, knagurski commented
> 🎉 LGTM! @knagurski how are we planning the transition? Use it as switch for entire App or by MFE or individual page/team on their own

It'll be by environment. Initially I plan to configure Pre-QA to use the new SDK, evaluate how that works out and then move through the envs. Ideally this will be totally transparent for all teams, though we will need to pass on an SDK key to all devs targeting a specific env (or explain how to generate their own using the UAT FF project). At the moment I've made it so that the legacy API will continue to be used.

Regarding MFEs, if they are querying flags through the usual `useFeatureFlag` or `useFeatureFlags` hooks, they should have no issues at all and everything should continue to work as these are fed using the existing `AppStoreProvider`, which in turn is now fed from the SDK/legacy API. It should be possible to also pass along (or directly import) the SDK's version of `useFeatureFlag`/`useFeatureFlags`/`withFeatureFlags`/`ifFeatureFlag`

2022-09-14 11:12 UTC, abhinavrastogi-harness requested changes
Looks good overall. Few key things that I might consider as blockers:

1. support for reading baseurl, key, legacy flag etc from the runtime env. this will require injection of these values via `.Dockerfile` env and `index.html`
2. making feature-flags api call sequential is a performance regression. do we have any alternatives?

2022-09-14 11:12 UTC, abhinavrastogi-harness commented on src/framework/FeatureFlags/FeatureFlagsProvider.tsx
> +    <FFContextProvider
does the `FFContextProvider` block on a network call to fetch feature flags?

2022-09-14 11:12 UTC, abhinavrastogi-harness commented on src/framework/FeatureFlags/FeatureFlagsProvider.tsx
> +    return <LegacyFeatureFlagsProvider>{children}</LegacyFeatureFlagsProvider>
With this change, the legacy FF api call and rest of startup API calls will become sequential.
They happen in parallel currently.
This can have a drastic negative impact on app load performance.

2022-09-14 11:12 UTC, abhinavrastogi-harness commented on configs/webpack.common.js
> +      USE_LEGACY_FEATURE_FLAGS
i think these need to be runtime injections instead of build-time injections.
We might want different baseurl and keys for the same build in different environments (eg. QA and Prod).

2022-09-14 11:12 UTC, abhinavrastogi-harness commented on src/framework/FeatureFlags/LegacyFeatureFlagsProvider.tsx
> +    [featureFlags?.resource]
this will memoize on the reference to the `resource` key. are we sure this will regenerate the flags when we get a new response?
`featureFlags` is just a state variable.. so I am not sure if the reference will change.

2022-09-14 11:17 UTC, knagurski commented on configs/webpack.common.js
> +  if (!HARNESS_FF_SDK_BASE_URL.match(/https?:\/\//)) {
Good idea. I just added it as a _crossing t's, dotting i's_ kinda thing, but it's worth doing right!

2022-09-14 11:22 UTC, knagurski commented on src/framework/FeatureFlags/FeatureFlagsProvider.tsx
> +    <FFContextProvider
Yes, it will display the passed `fallback` component until the initial load is complete, then it will render the children.

2022-09-14 11:29 UTC, knagurski commented on src/framework/FeatureFlags/FeatureFlagsProvider.tsx
> +    return <LegacyFeatureFlagsProvider>{children}</LegacyFeatureFlagsProvider>
Yes, that's the case. I think I've figured out a pretty simple fix for this, but in my testing, as-is, it adds just under 1s to page load. Not too drastic, but I think we can do better... instead of having a `LegacyFeatureFlags` provider, we can instead have `AppStoreContext` make the API call only when `withFeatureFlags` passes an empty result set. So when the SDK is configured and fetches, it uses those flags and when it is bypassed (with `USE_LEGACY_FEATURE_FLAGS`), it just does what it does currently.

2022-09-14 11:30 UTC, knagurski commented on configs/webpack.common.js
> +      USE_LEGACY_FEATURE_FLAGS
That's a great call. Do we have an example of this being done for other features?

2022-09-14 11:34 UTC, knagurski commented on src/framework/FeatureFlags/LegacyFeatureFlagsProvider.tsx
> +    [featureFlags?.resource]
So, you're both correct and ¯\_(ツ)_/¯ at the same time. `resource` doesn't exist when the memo is first called, but does when the API call completes. Since the API will never be called again, I'm treating `resource` as a boolean to trigger the memo; it's contents will never change. In the FF React SDK, I do a similar thing, but use `JSON.stringify` on the result to change on key/value changes in the variable; but that's overkill in this case where I just want to know it exists.

2022-10-21 15:48 UTC, vkbansal-harness approved these changes

2022-10-23 03:29 UTC, udayvunnam approved these changes

2022-10-28 11:22 UTC, abhinavrastogi-harness commented on package.json
> +    "@harnessio/ff-react-client-sdk": "^1.0.0-alpha.10",
Can we mvoe to a stable version instead of 1.0.0-alpha.10 for the sdk?

2022-10-28 11:22 UTC, abhinavrastogi-harness commented on src/index.html
> +        async: 'HARNESS_FF_SDK_ASYNC' !== 'false'
Two potential improvements purely for semantics:
1. we usually append `_PLACEHOLDER` to anything that is meant to be replaced as a template variable.. eg. `HARNESS_FF_SDK_KEY_PLACEHOLDER` instead of `HARNESS_FF_SDK_KEY`
2. when this is merged, if there is any environment where the correct service variables/overrides are not present, something like 
```
'HARNESS_FF_SDK_BASE_URL' || 'https://config.feature-flags.uat.harness.io/api/1.0'
```
will always evaluate to `HARNESS_FF_SDK_BASE_URL` as a string instead of undefined & using the prod URL.

To solve this, we can use HTML comments to set the default values.. similar to other variables on line 38.

2022-10-28 11:22 UTC, abhinavrastogi-harness commented on yarn.lock
> +lodash.omit@^4.5.0:
does the SDK bring this dependency? 
Why are these not included in the SDK bundle?

2022-10-28 11:26 UTC, knagurski commented on package.json
> +    "@harnessio/ff-react-client-sdk": "^1.0.0-alpha.10",
Not yet. The SDK was written specifically for this purpose. The code is complete and tested, but the docs still need written and the SDK publicised. When those things are in place, we'll go GA. The `alpha` part more refers to it not being ready for public consumption, not an indicator of its stability.

2022-10-28 11:29 UTC, knagurski commented on src/index.html
> +        async: 'HARNESS_FF_SDK_ASYNC' !== 'false'
Regarding _"will always evaluate to HARNESS_FF_SDK_BASE_URL as a string instead of undefined & using the prod URL"_ because it will always be set by the docker script, it will either be a value (when the source variable is defined), or it will be blank. In the case of a blank string, it will be evaluated as falsey and fallback to the API.

2022-10-28 11:33 UTC, knagurski commented on src/index.html
> +        async: 'HARNESS_FF_SDK_ASYNC' !== 'false'
Regarding _"we usually append `_PLACEHOLDER` to anything that is meant to be replaced as a template variable"_ I saw an even mix of things using `_PLACEHOLDER` and not, so I just went with an example that was closer to how I was doing things. It's a good idea though, will update now 👍🏻

2022-10-28 11:38 UTC, knagurski commented on yarn.lock
> +lodash.omit@^4.5.0:
Bundling things with a library is a pretty wasteful practice and is specifically what `dependencies` are for. By bundling it we take away the ability for npm/yarn to handle version negotiation, meaning the final app's bundle size will definitely increase, rather than only _potentially_ increasing as happens with a `dependency`. IMO, bundling is something that should _only_ be done by the final app, not any of the upstream dependencies.

2022-10-28 15:19 UTC, knagurski commented on src/index.html
> +        async: 'HARNESS_FF_SDK_ASYNC' !== 'false'
Updated now with some local dev goodness and `_PLACEHOLDER` suffix

2022-10-28 15:20 UTC, knagurski commented on yarn.lock
> +lodash.omit@^4.5.0:
I should actually be able to eliminate this dependency completely in an upcoming release of the SDK

2022-11-09 11:34 UTC, abhinavrastogi-harness approved these changes

2022-11-09 11:35 UTC, knagurski commented on package.json
> +    "@harnessio/ff-react-client-sdk": "^1.0.0-alpha.10",
UPDATE: I'm reviewing a draft for the docs, so we're pretty close to a GA on the SDK 👍🏻 No code changes should be involved between `1.0.0-alpha.12` and `1.0.0`

2022-11-09 11:36 UTC, willd0yle approved these changes

2022-11-09 13:42 UTC, merged