feat: [PIE-5342]: Send parent entity details for applyTemplates and templateInputs
harness/harness-core-ui pull request #11242
Opened 2022-09-14 10:55 UTC by depanshu-dhiman

### Summary
Now applyTemplates and templateInputs call depends on a few extra params in case the parent entity is remote. This PR makes that change for all the references of GET API call.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-14 10:57 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11242)

2022-09-14 13:40 UTC, yc147 approved these changes

2022-09-14 14:37 UTC, depanshu-dhiman commented
trigger cypress

2022-09-15 05:44 UTC, yc147 commented on src/modules/70-pipeline/components/PipelineStudio/TemplateBar/TemplateBar.tsx
> -      ...createParentEntityQueryParams(storeMetadata, params, branch)
`TemplateBar` can be used `PipelineContext`. Pass `storeMetadata` in props.

2022-09-15 05:46 UTC, yc147 requested changes
TemplateBar can be used out side PipelineContext. Pass storeMetadata in props.

2022-09-15 12:47 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudio.tsx
> +    <TemplateVariablesContextProvider template={template} parentEntityData={parentEntityData}>
Pass the storeMetaData to `TemplateVariablesContextProvider`

2022-09-19 10:00 UTC, depanshu-dhiman commented
retrigger jest

2022-09-19 10:11 UTC, yc147 submitted a review, later dismissed

2022-09-19 11:49 UTC, YounixIO submitted a review, later dismissed

2022-09-19 14:41 UTC, AshwinBhatkal-Harness approved these changes

2022-09-20 05:47 UTC, AshwinBhatkal-Harness approved these changes

2022-09-20 06:55 UTC, yc147 approved these changes

2022-09-20 07:10 UTC, YounixIO approved these changes

2022-09-20 07:11 UTC, merged