fix: [PL-28236]: Editing the stage and pipeline template reseting the step what we have configured
harness/harness-core-ui pull request #11369
Opened 2022-09-21 16:58 UTC by sumanmabd

### Summary

For pipeline and stage Template, when we add any number of steps, and if we try to edit the template and press continue, the steps that we created will cleaned up. This is fixed.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-21 16:58 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield.svg) Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11369)

2022-09-22 10:17 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/PipelineTemplateCanvas/PipelineTemplateCanvasWrapper.tsx
> -  const [pipeline, setPipeline] = React.useState<PipelineInfoConfig>(createPipelineFromTemplate())
Revert this line pls. We are calling `createPipelineFromTemplate`

2022-09-22 10:17 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/StageTemplateCanvas/StageTemplateCanvasWrapper.tsx
> +  const [Template, setTemplate] = React.useState<PipelineInfoConfig>(createPipelineFromTemplate())
Revert

2022-09-22 10:18 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/StageTemplateCanvas/StageTemplateCanvasWrapper.tsx
> +      initialValue={Template}
Revert

2022-09-22 10:44 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/StageTemplateCanvas/StageTemplateCanvasWrapper.tsx
> +// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
Remove rule

2022-09-22 10:44 UTC, depanshu-dhiman commented on src/modules/72-templates-library/components/TemplateStudio/StageTemplateCanvas/StageTemplateCanvasWrapper.tsx
> +  // eslint-disable-next-line @typescript-eslint/explicit-function-return-type
Remove rule

2022-09-22 10:49 UTC, depanshu-dhiman approved these changes

2022-09-22 11:18 UTC, yc147 requested changes
This needs to be testing throughly.

2022-10-04 07:37 UTC, closed without merging