feat: [CI-5007]: Added`Configure Pipeline` step to CI onboarding wizard
harness/harness-core-ui pull request #11445
Opened 2022-09-26 04:53 UTC by vardanbansal-harness

### Summary

Jira : https://harness.atlassian.net/browse/CI-5654

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-26 04:55 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 51 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 51 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11445)

2022-09-28 12:52 UTC, d1wilko requested changes
Some small changes but looking good

Please test the hosted VMs new user flow as I am terrified of anything breaking 😆

2022-09-28 12:52 UTC, d1wilko commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/InfraProvisioningWizard.tsx
> +            isUsingHostedVMsInfra: CIE_HOSTED_VMS || false,
this can just be `isUsingHostedVMsInfra: CIE_HOSTED_VMS,` - even if feature flag doesn't exist this will default to false

2022-09-28 12:52 UTC, d1wilko commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/starter-templates.json
> +    "pipelineYaml": "pipeline:\n  name: Build  Dot NET Core\n  identifier: Build_Dot_NET_Core_1664221027597\n  projectIdentifier: CI_Sanity\n  orgIdentifier: default\n  stages:\n    - stage:\n
could these yamls be seperate yaml files that we stringify - it feels like they would be much easier to maintain

2022-09-28 12:56 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/InfraProvisioningWizard.tsx
> +            isUsingHostedVMsInfra: CIE_HOSTED_VMS || false,
Done.

2022-09-28 12:57 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/starter-templates.json
> +    "pipelineYaml": "pipeline:\n  name: Build  Dot NET Core\n  identifier: Build_Dot_NET_Core_1664221027597\n  projectIdentifier: CI_Sanity\n  orgIdentifier: default\n  stages:\n    - stage:\n
Yeah that's what I thought as well, but this is a temporary thing. We will replace these files by fetching them via api/git directly.

2022-09-28 13:57 UTC, vardanbansal-harness commented
> Some small changes but looking good
> 
> Please test the hosted VMs new user flow as I am terrified of anything breaking 😆

I've tested this with `CIE_HOSTED_VMS` FF enabled as well.

2022-09-28 14:31 UTC, d1wilko submitted a review, later dismissed

2022-09-28 16:55 UTC, mtran7 commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/ConfigurePipeline.tsx
> +    if (!forwardRef) {
!forwardRef || typeof forwardRef === 'function'

2022-09-28 17:02 UTC, mtran7 commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/ConfigurePipeline.tsx
> +              errorMessage={getString('common.getStarted.plsChoose', {
would spell out please as it's the same syllables and easier to read

2022-09-28 17:05 UTC, mtran7 commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/InfraProvisioningWizard.tsx
> +          if ((gitAuthenticationMethod === GitAuthenticationMethod.OAuth && validatedConnector) || validate?.()) {
add comment for validate?.() condition to go in this scope? Could it be validating for other methods too?

2022-09-28 17:06 UTC, mtran7 commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/__tests__/ConfigurePipeline.test.tsx
> +      fireEvent.click(dotNetStarterConfig)
Optional - to start using `userEvent.click`

2022-09-28 17:07 UTC, mtran7 commented on src/modules/75-ci/strings/strings.en.yaml
> +  starterPipeline: Start with a starter Pipeline
Maybe "Begin with a starter Pipeline". Saying start twice sounds a little funny

2022-09-28 18:14 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/ConfigurePipeline.tsx
> +              CIE_HOSTED_VMS ? enrichedPipelineObj : addK8sHostedInfraDetailsToPipelineStage(enrichedPipelineObj)
So the plan forward is that for hosted infra capabilities, we would only be supporting VMs and no other infra type with `CIE_HOSTED_VMS` defaulted to true, so this would become much simpler with only one infra type.

2022-09-28 18:14 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/ConfigurePipeline.tsx
> +    if (!forwardRef) {
Done.

2022-09-28 18:14 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/ConfigurePipeline.tsx
> +              errorMessage={getString('common.getStarted.plsChoose', {
Will do this separately in a follow up as it would trigger changes from CD module as since it's a commonly used string. Hope that's fine.

2022-09-28 18:14 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/InfraProvisioningWizard.tsx
> +          if ((gitAuthenticationMethod === GitAuthenticationMethod.OAuth && validatedConnector) || validate?.()) {
Done.

2022-09-28 18:14 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/__tests__/ConfigurePipeline.test.tsx
> +      fireEvent.click(dotNetStarterConfig)
That's something new! Thanks for letting me know, done.

2022-09-28 18:14 UTC, vardanbansal-harness commented on src/modules/75-ci/strings/strings.en.yaml
> +  starterPipeline: Start with a starter Pipeline
Yes, that sounds better, done.

2022-09-28 18:21 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/ConfigurePipeline.tsx
> +              errorMessage={getString('common.getStarted.plsChoose', {
Makes sense, done.

2022-09-29 16:41 UTC, mtran7 approved these changes

2022-10-10 15:11 UTC, mtran7 approved these changes

2022-10-10 15:11 UTC, mtran7 commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/InfraProvisioningWizard.module.scss
> +    .bp3-input-group {
[class*="..."] instead of global

2022-10-10 15:11 UTC, mtran7 commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/starter-templates/k8s.json
> +    "name": "Dot NET Core",
Should this be .NET?

2022-10-10 15:11 UTC, mtran7 commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/starter-templates/vm.json
> +    "name": "Dot NET Core",
.NET?

2022-10-10 15:11 UTC, mtran7 commented on src/modules/75-ci/utils/__test__/HostedBuildsUtils.test.ts
> +        'pipeline:\n  name: Build Dot NET Core\n  identifier: Build_Dot_NET_Core\n  projectIdentifier: testproj\n  orgIdentifier: default\n  stages:\n    - stage:\n        name: Build Dot NET Core Ap
.NET

2022-10-10 15:11 UTC, mtran7 commented on src/modules/75-ci/utils/__test__/HostedBuildsUtils.test.ts
> +      pipelineName: 'Build Dot Net',
.NET

2022-10-10 15:16 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/starter-templates/k8s.json
> +    "name": "Dot NET Core",
Pipeline name cannot have `.` in the name, hence had to add it as a word.

2022-10-10 15:16 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/starter-templates/vm.json
> +    "name": "Dot NET Core",
Same as above.

2022-10-10 15:20 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/InfraProvisioningWizard.module.scss
> +    .bp3-input-group {
Will clean up this in a follow up, this portion of ui is commented as of now.

2022-10-10 15:21 UTC, vardanbansal-harness commented on src/modules/75-ci/utils/__test__/HostedBuildsUtils.test.ts
> +        'pipeline:\n  name: Build Dot NET Core\n  identifier: Build_Dot_NET_Core\n  projectIdentifier: testproj\n  orgIdentifier: default\n  stages:\n    - stage:\n        name: Build Dot NET Core Ap
This is just test data.

2022-10-10 15:21 UTC, vardanbansal-harness commented on src/modules/75-ci/utils/__test__/HostedBuildsUtils.test.ts
> +      pipelineName: 'Build Dot Net',
Same as above.

2022-10-10 15:23 UTC, shaurya-harness approved these changes

2022-10-10 15:23 UTC, merged