fix: [PIE-5396]: crazy async bug
harness/harness-core-ui pull request #11566
Opened 2022-09-30 01:08 UTC by udayvunnam

### Summary

- Show loader until the execute API is resolved, do not leave blank modal which allows user click run pipeline multiple times

#### Screenshots
![Kapture 2022-09-30 at 06 26 47](https://user-images.githubusercontent.com/20707504/193168319-0a22702a-28cc-445f-aa20-8379e297a119.gif)

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-30 03:08 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/RunPipelineModal/RunPipelineForm.tsx
> -        return valuesPipeline as PipelineInfoConfig
but if we do not return from here, it will not wait for pre-flight check to complete

2022-09-30 03:09 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/RunPipelineModal/RunPipelineForm.tsx
> -            return handleRunPipeline(values, false)
instead we can remove the return here and handle loading state manually

2022-09-30 03:10 UTC, vkbansal-harness requested changes
see comments

2022-10-03 02:44 UTC, udayvunnam commented
^^ @vkbansal-harness @kapilkumawat86 please rereview

2022-10-03 04:57 UTC, kapilkumawat86 approved these changes

2022-10-03 05:07 UTC, merged