fix: [CCM-9217]: Don't Send BILLING if it's Coming From Previously Created Connectors
harness/harness-core-ui pull request #11596
Opened 2022-10-02 03:13 UTC by rajarshee-harness

### Summary

Don't send `BILLING` in `featuresEnabled` if it's coming from previously created connectors.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-02 03:14 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11596)

2022-10-13 10:50 UTC, jenil-harness requested changes

2022-10-13 10:50 UTC, jenil-harness commented on src/modules/35-connectors/components/CreateConnector/CEAzureConnector/Steps/CreateServicePrincipal/CreateServicePrincipal.tsx
> +  //   commands = [
Let's delete this rather then commenting.

2022-10-17 06:43 UTC, Sagar-Rajput7 approved these changes

2022-10-17 09:45 UTC, avinashmadhwani02 approved these changes

2022-10-17 09:54 UTC, merged