feat: [CDS-43579]: Add app settings and conn strings to Env Config and Service Overrides
harness/harness-core-ui pull request #11605
Opened 2022-10-02 19:44 UTC by Tamaraius

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-02 19:46 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 143 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 143 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11605)

2022-10-03 12:19 UTC, Tamaraius commented
retrigger titlecheck

2022-10-03 14:22 UTC, willd0yle submitted a review, later dismissed

2022-10-04 09:13 UTC, willd0yle submitted a review, later dismissed

2022-10-04 11:59 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/CustomVariables/CustomVariablesEditableStage.tsx
> +    fromEnvironmentConfiguration
Instead of having this as fromEnvironmentConfiguration we should instead take in a label for the button

2022-10-04 12:01 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/EnvironmentConfiguration/EnvironmentConfiguration.tsx
> +          break
nit: don't need break after default

2022-10-04 12:01 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/EnvironmentConfiguration/EnvironmentConfiguration.tsx
> +          break
nit: same as above

2022-10-04 12:03 UTC, Tamaraius commented on src/modules/70-pipeline/components/PipelineSteps/Steps/CustomVariables/CustomVariablesEditableStage.tsx
> +    fromEnvironmentConfiguration
addVariableLabel is actually a string name, and from Env Config page we have label consisting from multiple strings, that's why this 'fromEnvironmentConfiguration' is introduced, not to change addVariableLabel logic in other places where this component is being used

2022-10-04 12:03 UTC, Tamaraius commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/EnvironmentConfiguration/EnvironmentConfiguration.tsx
> +          break
will remove it

2022-10-04 12:03 UTC, Tamaraius commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/EnvironmentConfiguration/EnvironmentConfiguration.tsx
> +          break
will remove it

2022-10-04 12:14 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/EnvironmentConfiguration/EnvironmentConfiguration.tsx
> +                    <AzureWebAppConfigSelection
Why is azure web app config selection here?

2022-10-04 12:20 UTC, Tamaraius commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/EnvironmentConfiguration/EnvironmentConfiguration.tsx
> +                    <AzureWebAppConfigSelection
the component is being used for both Application strings and Connection settings, that was azure web app configuration

2022-10-04 12:22 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/ServiceOverrides/AddEditServiceOverride.tsx
> +    const parsedService = service?.data?.yaml && parse(service?.data?.yaml)
We already have this prop as part of the services prop that comes in to this component. This comes from the service list call

2022-10-04 12:22 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/ServiceOverrides/AddEditServiceOverride.tsx
> +                                <AzureWebAppConfigSelection
remove azure web app here as well

2022-10-04 12:23 UTC, Tamaraius commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/ServiceOverrides/AddEditServiceOverride.tsx
> +                                <AzureWebAppConfigSelection
this component should be here, it is used for displaying Application settings and Connection Strings

2022-10-04 12:25 UTC, Tamaraius commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/ServiceOverrides/AddEditServiceOverride.tsx
> +    const parsedService = service?.data?.yaml && parse(service?.data?.yaml)
will remove it, missed that it was part of yaml in services API call

2022-10-04 13:15 UTC, AshwinBhatkal-Harness requested changes
Please remove the azure config file from environment. Let's move it to some common code and extend it to azure web app

2022-10-05 11:30 UTC, AshwinBhatkal-Harness approved these changes

2022-10-05 12:07 UTC, willd0yle submitted a review, later dismissed

2022-10-06 10:41 UTC, willd0yle approved these changes

2022-10-06 11:20 UTC, merged