feat: [PIE-4605]: UI changes for Triggers authentication
harness/harness-core-ui pull request #11654
Opened 2022-10-04 09:22 UTC by pankajsingh-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-04 09:24 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 31 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 31 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11654)

2022-10-07 04:17 UTC, AshwinBhatkal-Harness commented on src/modules/30-secrets/components/SecretInput/SecretInput.tsx
> +              {secretReference && <div>{`<${secretReference['name'] ?? secretReference}>`}</div>}
Do we need to use secretReference if it is not an object

2022-10-07 04:19 UTC, AshwinBhatkal-Harness commented on src/modules/72-triggers/components/Triggers/WebhookTrigger/utils.tsx
> +        getString('triggers.validation.configureSecret'),
Same values twice?

2022-10-07 06:38 UTC, AshwinBhatkal-Harness requested changes
Need to add copy confirmation modal after selecting secret

2022-10-12 09:47 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/Triggers/WebhookTrigger/utils.tsx
> +        getString('triggers.validation.configureSecret'),
One is for name and another is for message. Updated the name ti the key

2022-10-12 12:25 UTC, pankajsingh-harness commented
trigger cypress

2022-10-12 12:31 UTC, pankajsingh-harness commented
retrigger coverage

2022-10-13 04:14 UTC, AshwinBhatkal-Harness approved these changes

2022-10-13 12:32 UTC, sunnykesh-harness submitted a review, later dismissed

2022-10-17 09:25 UTC, pankajsingh-harness commented on src/modules/30-secrets/components/SecretInput/SecretInput.tsx
> +              {secretReference && <div>{`<${secretReference['name'] ?? secretReference}>`}</div>}
Removed this logic now.

2022-10-17 09:40 UTC, AshwinBhatkal-Harness approved these changes

2022-10-17 11:57 UTC, sunnykesh-harness submitted a review, later dismissed

2022-10-17 14:58 UTC, vkbansal-harness approved these changes

2022-10-18 04:48 UTC, sunnykesh-harness approved these changes

2022-10-18 05:23 UTC, vkbansal-harness approved these changes

2022-10-18 05:23 UTC, merged