feat: [SRM-12285]: Elk enhancements
harness/harness-core-ui pull request #11674
Opened 2022-10-05 00:05 UTC by vasuki-kalluri

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-05 00:07 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11674)

2022-10-06 05:25 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/components/MapElkQueriesToService/components/MapQueriesToHarnessServiceLayout/MapQueriesToHarnessServiceLayout.tsx
> +                  identify_timestamp={identify_timestamp}
why we changing Name  from  camelCase to snake case ?

2022-10-06 05:42 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/components/MapElkQueriesToService/components/MapQueriesToHarnessServiceLayout/MapQueriesToHarnessServiceLayout.tsx
> +  const { mutate: getSampleData } = useGetELKLogSampleData({})
add loading and Error from  useGetELKLogSampleData, not use state level variables for it

2022-10-06 05:46 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/components/MapElkQueriesToService/components/MapQueriesToHarnessServiceLayout/MapQueriesToHarnessServiceLayout.tsx
> +              queryInputs={[formikProps, query]}
[formikProps.values.{Specific values causing change }, query]

2022-10-06 06:35 UTC, vasuki-kalluri commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/components/MapElkQueriesToService/components/MapQueriesToHarnessServiceLayout/MapQueriesToHarnessServiceLayout.tsx
> +  const { mutate: getSampleData } = useGetELKLogSampleData({})
Done

2022-10-06 07:11 UTC, vasuki-kalluri commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/components/MapElkQueriesToService/components/MapQueriesToHarnessServiceLayout/MapQueriesToHarnessServiceLayout.tsx
> +              queryInputs={[formikProps, query]}
Done

2022-10-06 07:29 UTC, vasuki-kalluri commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/components/MapElkQueriesToService/components/MapQueriesToHarnessServiceLayout/MapQueriesToHarnessServiceLayout.tsx
> +                  identify_timestamp={identify_timestamp}
Done

2022-10-06 07:54 UTC, praneshg239 commented on src/modules/85-cv/components/QueryViewer/QueryViewer.tsx
> +  }, [...Object.values(queryInputs ?? {}), query])
Don't use spread operator in dependencies. Wrap the value in `useMemo` and pass that value here

2022-10-06 07:55 UTC, harshilbits commented on src/modules/85-cv/components/QueryViewer/QueryViewer.tsx
> +  }, [...Object.values(queryInputs ?? {}), query])
Please assign this in a variable with a suitable name and use the variable here instead of spreading the values directly in dependency array.

2022-10-06 07:56 UTC, harshilbits commented on src/modules/85-cv/components/QueryViewer/types.ts
> +  queryInputs?: Array<any>
why are we using any ?

2022-10-06 07:56 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/components/MapElkQueriesToService/ElkMetricNameAndHostIdentifier.tsx
> +    if (formikProps.values.logIndexes) {
better to have null check here.

2022-10-06 07:57 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/tests/MapQueriesToHarnessService.test.tsx
>        //serviceInstance: MapElkToServiceFieldNames.SERVICE_INSTANCE,
get rid of commented code.

2022-10-06 07:57 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/tests/MapQueriesToHarnessService.test.tsx
>              //recordCount: 0
same

2022-10-06 07:58 UTC, praneshg239 commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/components/MapElkQueriesToService/ElkMetricNameAndHostIdentifier.tsx
> +  const handleSelectChange = (): void => {
NIT for current scenario: use `useCallback` for the functions that you are passing as props to other component.

Here, `handleSelectChange` is a function that is being passed to `FormInput.Select`, which is a simple component. Though it re-renders, it won't make much difference. But if it is a big feature component, it will get re-rendered every time because of this function being created newly for every re-render.

2022-10-06 08:08 UTC, vasuki-kalluri commented
retrigger cypress

2022-10-06 08:42 UTC, vasuki-kalluri commented on src/modules/85-cv/components/QueryViewer/QueryViewer.tsx
> +  }, [...Object.values(queryInputs ?? {}), query])
Done

2022-10-06 08:52 UTC, vasuki-kalluri commented on src/modules/85-cv/components/QueryViewer/types.ts
> +  queryInputs?: Array<any>
Can you please suggest which type to use. I cant find it. Can you pls let me know

2022-10-06 08:53 UTC, vasuki-kalluri commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/components/MapElkQueriesToService/ElkMetricNameAndHostIdentifier.tsx
> +    if (formikProps.values.logIndexes) {
formikProps is not optional here. Its mandatory

2022-10-06 09:08 UTC, vasuki-kalluri commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/tests/MapQueriesToHarnessService.test.tsx
>        //serviceInstance: MapElkToServiceFieldNames.SERVICE_INSTANCE,
Done

2022-10-06 09:08 UTC, vasuki-kalluri commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/components/MapElkQueriesToService/ElkMetricNameAndHostIdentifier.tsx
> +  const handleSelectChange = (): void => {
Done

2022-10-06 16:38 UTC, vasuki-kalluri commented
trigger cypress

2022-10-07 07:10 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/ElkHealthSource/components/MapQueriesToHarnessService/components/MapElkQueriesToService/ElkMetricNameAndHostIdentifier.tsx
> +    if (formikProps.values.logIndexes) {
```suggestion
    if (formikProps?.values?.logIndexes) {
```

2022-10-07 10:33 UTC, praneshg239 commented on src/modules/85-cv/components/QueryViewer/QueryViewer.tsx
> +  const queryInputDependencies = [...Object.values(queryInputs ?? {}), query]
Please do rebase, in the updated code I removed the useCallback itself here.

2022-10-07 10:34 UTC, praneshg239 requested changes
Please check

2022-10-07 15:58 UTC, vasuki-kalluri commented on src/modules/85-cv/components/QueryViewer/QueryViewer.tsx
> +  const queryInputDependencies = [...Object.values(queryInputs ?? {}), query]
I kept the original comments given by you and Harshil. I kept the useCallback and removed the .. from dependencies.

2022-10-07 18:26 UTC, deepesh-ui commented on src/modules/85-cv/components/QueryViewer/types.ts
> +  queryInputs?: Array<any>
Please remove this type , as this us unused

2022-10-07 18:26 UTC, deepesh-ui approved these changes

2022-10-07 18:36 UTC, merged