feat: [CI-5615]: Land to Test page if execution has failing tests
harness/harness-core-ui pull request #11672
Opened 2022-10-04 20:03 UTC by shaurya-harness

### Summary

Land onto Test page by default if tests are failing instead of Pipeline in Console view

#### Screenshots

https://user-images.githubusercontent.com/113332561/193914673-a8a4e11c-432a-4578-bd99-3f658bd108ba.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-04 20:04 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11672)

2022-10-06 05:49 UTC, vkbansal-harness commented on package.json
> -  "version": "0.322.6",
Why is it going from `6` to `9` ?

2022-10-06 06:07 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCard/ExecutionCard.tsx
> +  })
Is there a better API to get a report summary for all executions in the view instead of each execution? Please also note that we have continous polling for executions

2022-10-06 06:09 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCard/ExecutionCard.tsx
> +      }
Please take care of this in `src/modules/70-pipeline/pages/execution-list/ExecutionListTable/ExecutionListCells.tsx` `getExecutionPipelineViewLink`

Execution card will be obsolete and will be switched to new view anytime from now

2022-10-06 06:09 UTC, udayvunnam requested changes
Please check comments

2022-10-06 06:28 UTC, shaurya-harness commented on src/modules/70-pipeline/components/ExecutionCard/ExecutionCard.tsx
> +  })
we do not have an API for that, we have executionSummary but it does not contain the test reports.

2022-10-06 07:07 UTC, shaurya-harness commented on package.json
> -  "version": "0.322.6",
had rebase issues, fixed it

2022-10-06 07:08 UTC, shaurya-harness commented on src/modules/70-pipeline/components/ExecutionCard/ExecutionCard.tsx
> +
adding it to lazy

2022-10-06 07:47 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCard/ExecutionCard.tsx
> +
```
 useEffect(() => {
    if (HAS_CI && !reportSummary) {
      fetchReportSummary()
    }
  }, [reportSummary, fetchReportSummary, queryParams, HAS_CI])
```

no longer required

2022-10-06 07:48 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCard/ExecutionCard.tsx
> +      }
It can happen that reportSummary is loading and the click goes nowhere until then and there won't be any visual indication too

2022-10-06 07:52 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCard/ExecutionCard.tsx
> +      }
- we have polling which gets new data every 5 sec
- we can fetch the test summary only once we have the execution data available
- The click is blocked until then (we neither can show additional loading (polling)).

Please discuss these concerns with the designer and product.

cc: @kapilkumawat86

2022-10-06 07:56 UTC, vardanbansal-harness commented on src/modules/70-pipeline/components/ExecutionCard/ExecutionCard.tsx
> +      }
> It can happen that reportSummary is loading and the click goes nowhere until then and there won't be any visual indication too

Agreed, we need to add a visual indication, like `Loading...` or something to indicate some operation is happening.

2022-10-06 14:07 UTC, udayvunnam commented on src/services/ti-service/index.tsx
> +export const getReportSummaryPromise = (
this gets overridden if somebody regenerates service and also clicking on the execution card takes time without any indicator

2022-10-06 14:09 UTC, udayvunnam submitted a review, later dismissed

2022-10-06 14:11 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCard/ExecutionCard.tsx
> +        }
@vardanbansal-harness please consider UX and PM approval if this is okay. But I feel it would cause issues

2022-10-06 14:18 UTC, vardanbansal-harness commented on src/services/ti-service/index.tsx
> +export const getReportSummaryPromise = (
Agreed, will get this fixed as soon as this ticket is taken care of https://harness.atlassian.net/browse/CI-5765.

2022-10-10 12:41 UTC, kapilkumawat86 approved these changes

2022-10-10 13:02 UTC, vardanbansal-harness approved these changes

2022-10-10 13:04 UTC, merged