feat: [CHAOS-391]: Updating resources and terminologies
harness/harness-core-ui pull request #11686
Opened 2022-10-05 11:25 UTC by S-ayanide

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-05 11:29 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11686)

2022-10-05 12:11 UTC, arkajyotiMukherjee requested changes

2022-10-05 12:11 UTC, arkajyotiMukherjee commented on src/modules/20-rbac/pages/UserDetails/__tests__/mock.ts
> +              'chaos_chaosGameday_edit',
```suggestion
              'chaos_chaosgameday_edit',
```

2022-10-05 12:11 UTC, arkajyotiMukherjee commented on src/modules/75-chaos/strings/strings.en.yaml
> +ChaosExperiment: Chaos Experiment
```suggestion
chaosExperiment: Chaos Experiment
```

2022-10-05 12:11 UTC, arkajyotiMukherjee commented on src/modules/75-chaos/RouteDestinations.tsx
> +  resourceLabel: 'chaos.ChaosExperiment',
```suggestion
  moduleLabel: 'chaos.chaosExperiment',
  resourceLabel: 'chaos.chaosExperiment',
```

2022-10-05 12:11 UTC, arkajyotiMukherjee commented on src/modules/20-rbac/pages/UserDetails/__tests__/mock.ts
> +              'chaos_chaosGameday_edit',
```suggestion
              'chaos_chaosgameday_edit',
```

2022-10-05 12:11 UTC, arkajyotiMukherjee commented on src/modules/20-rbac/pages/UserDetails/__tests__/mock.ts
> +              'chaos_chaosGameday_edit',
```suggestion
              'chaos_chaosgameday_edit',
```

2022-10-05 13:27 UTC, imrajdas submitted a review, later dismissed

2022-10-05 13:39 UTC, arkajyotiMukherjee approved these changes

2022-10-06 04:29 UTC, abhinavrastogi-harness submitted a review, later dismissed

2022-10-06 07:53 UTC, abhinavrastogi-harness approved these changes

2022-10-06 07:55 UTC, imrajdas approved these changes

2022-10-06 07:56 UTC, merged