fix: [PL-28915]: Added provision for renewal Interval to be zero in HashiCorp vault
harness/harness-core-ui pull request #11824
Opened 2022-10-11 17:28 UTC by VikasMaddukuriHarness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-13 08:52 UTC, meenakshi-harness requested changes

2022-10-13 08:52 UTC, meenakshi-harness commented on src/modules/35-connectors/components/CreateConnector/HashiCorpVault/views/VaultConnectorFormFields.tsx
> +          {formik?.values['renewalIntervalMinutes'].toString() === '0' && (
why do we need to convert to string here?

2022-10-13 08:52 UTC, meenakshi-harness commented on src/modules/35-connectors/components/CreateConnector/HashiCorpVault/views/VaultConnectorFormFields.tsx
> +            <Text color={Color.ORANGE_900}>Harness will not renew the token if Renewal Interval is set to zero</Text>
Move text to string file.

2022-10-13 08:52 UTC, meenakshi-harness commented on src/modules/35-connectors/components/CreateConnector/HashiCorpVault/views/VaultConnectorFormFields.tsx
> +            <Text color={Color.ORANGE_900}>Harness will not renew the token if Renewal Interval is set to zero</Text>
Also lets get the colour of text reviewed by some UX person.

2022-10-13 08:52 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/utils/ConnectorUtils.ts
> +      connectorInfoSpec?.renewalIntervalMinutes === 0 ? 0 : connectorInfoSpec?.renewalIntervalMinutes || 10,
If this is required field lets make the default value as 10 in Form initial values itself and change this condition accordingly

2022-10-13 11:03 UTC, VikasMaddukuriHarness commented on src/modules/35-connectors/components/CreateConnector/HashiCorpVault/views/VaultConnectorFormFields.tsx
> +          {formik?.values['renewalIntervalMinutes'].toString() === '0' && (
vaultConfigForm has the renewalInterval as number. But we are passing a string here because of the rendering issue of number incase of 0. For this, we had to make it a string and compare it with "0"

2022-10-13 11:07 UTC, meenakshi-harness commented on src/modules/35-connectors/components/CreateConnector/HashiCorpVault/views/VaultConnectorFormFields.tsx
> +          {formik?.values['renewalIntervalMinutes'].toString() === '0' && (
I don't think so here we should have any rendering issue. Did we tried 
`formik?.values['renewalIntervalMinutes'] === 0` ?

2022-10-13 11:09 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/utils/ConnectorUtils.ts
> +    renewalIntervalMinutes: connectorInfoSpec?.renewalIntervalMinutes,
You have removed default value as 10. Is that expected? This is changing existing behaviour

2022-10-13 12:08 UTC, VikasMaddukuriHarness commented on src/modules/35-connectors/pages/connectors/utils/ConnectorUtils.ts
> +    renewalIntervalMinutes: connectorInfoSpec?.renewalIntervalMinutes,
This 10 is actually redundant. By default if there is not renewalINterval set, it will be set to 10.

2022-10-18 06:55 UTC, meenakshi-harness approved these changes

2022-10-18 08:59 UTC, swarajcheguri-harness approved these changes

2022-10-18 09:48 UTC, merged