fix: [CDS-44708]: Resolve template image not coming
harness/harness-core-ui pull request #11864
Opened 2022-10-13 07:57 UTC by depanshu-dhiman

### Summary
Template image was not coming because the list API does not return yaml anymore. We have to call template GET api to get yaml and extract template type from it so that the icon can be resolved.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-13 08:03 UTC, depanshu-dhiman commented
retrigger titlecheck

2022-10-13 10:23 UTC, depanshu-dhiman commented
retrigger coverage

2022-10-13 10:32 UTC, depanshu-dhiman commented
retrigger coverage

2022-10-13 14:59 UTC, yc147 commented on src/modules/70-pipeline/utils/templateUtils.tsx
> +export const getTemplateTypesByRefV2 = (
There is too much code repetition here.

2022-10-13 15:02 UTC, yc147 commented on src/modules/70-pipeline/utils/templateUtils.tsx
> +const getPromisesForTemplateGet = (
Again code repetition

2022-10-13 15:02 UTC, yc147 requested changes
Too much code repetition

2022-10-14 07:57 UTC, depanshu-dhiman commented on src/modules/70-pipeline/utils/templateUtils.tsx
> +const getPromisesForTemplateGet = (
Please check. I don't think there is because implementation is different. Query params are different. There is no body in API request. Many such differences

2022-10-14 08:36 UTC, yc147 requested changes
Please reduce the time and space complexity of this algorithm. Also there is a lot of code repetition.

2022-10-14 08:47 UTC, yc147 commented on src/modules/70-pipeline/utils/templateUtils.tsx
> +          const scopeBasedTemplateRef = getScopeBasedTemplateRef(response.data)
Extract this duplicate logic in a common function.

2022-10-14 09:41 UTC, depanshu-dhiman commented on src/modules/70-pipeline/utils/templateUtils.tsx
> +          const scopeBasedTemplateRef = getScopeBasedTemplateRef(response.data)
done

2022-10-14 09:49 UTC, yc147 commented on src/modules/70-pipeline/utils/templateUtils.tsx
> +const getPromisesForTemplateGet = (
We are unnecessarily increasing time and space complexity by creating first creating `scopedTemplates` object then looping over it's each key again. Where as all this can be accomplished by single loop over `templateRefs`.

2022-10-14 10:19 UTC, yc147 approved these changes

2022-10-14 11:00 UTC, vikrant-harness approved these changes

2022-10-14 11:11 UTC, merged