feat: [SRM-11733] Add Code Error Agents page under SRM
harness/harness-core-ui pull request #11881
Opened 2022-10-13 19:30 UTC by David-Kreiner

### Summary

Added button on left side of SRM module under the Project Setup dropdown to point to a new agent list page being created on Error Tracking micro-frontend. This new agent list and token page are children of a control page that I created that will allow for switching between these two pages using tab navigation. These changes are hidden behind the feature flag: SRM_ET_EXPERIMENTAL.

#### Screenshots

Before:
![image](https://user-images.githubusercontent.com/112413753/195691664-cd4aefe6-edcc-47b8-bd48-51348b2b36ce.png)

After:
![image](https://user-images.githubusercontent.com/112413753/195691714-40761d71-e1e2-42a8-a5f2-1aab88435bf0.png)

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [x] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-13 20:18 UTC, angelo-m-rodriguez submitted a review, later dismissed

2022-10-17 12:42 UTC, David-Kreiner commented
trigger rebase

2022-10-17 14:09 UTC, David-Kreiner commented
trigger cypress

2022-10-17 19:40 UTC, tan-nhu approved these changes

2022-10-18 05:07 UTC, abhinavrastogi-harness requested changes

2022-10-18 05:07 UTC, abhinavrastogi-harness commented on src/modules/85-cv/pages/code-errors-agent-control/CVCodeErrorsAgentsControl.tsx
> +  if (SRM_ET_EXPERIMENTAL) {
the page should not return empty based on FF.
dont render this component in the first place if the FF is false.. move the condition to the parent.

2022-10-18 05:07 UTC, abhinavrastogi-harness commented on src/modules/85-cv/pages/code-errors-agent-control/CVCodeErrorsAgentsControl.tsx
> +          className={css.pageHeaderHead}
dont change the header css (especially padding etc.)
we should use the standard header to match the rest of the app.

2022-10-18 05:07 UTC, abhinavrastogi-harness commented on src/modules/85-cv/pages/code-errors-agent-control/code-errors-agents-tokens/CVCodeErrorsAgentsTokens.tsx
> +  if (SRM_ET_EXPERIMENTAL) {
same.. dont return empty based on flag.
move condition to parent.,

2022-10-18 05:07 UTC, abhinavrastogi-harness commented on src/modules/85-cv/pages/code-errors-agent-control/code-errors-agents-tokens/__tests__/CVCodeErrors.test.tsx
> +    expect(container).toMatchSnapshot()
can we use assertions instead of snapshots?

2022-10-18 05:07 UTC, abhinavrastogi-harness commented on src/modules/85-cv/pages/code-errors-agent-control/code-errors-agents-tokens/__tests__/CVCodeErrors.test.tsx
> +    expect(container).not.toBeNull()
this is not a useful test 😅

2022-10-18 05:07 UTC, abhinavrastogi-harness commented on src/modules/85-cv/pages/code-errors-agent-control/code-errors-agents-tokens/__tests__/__snapshots__/CVCodeErrors.test.tsx.snap
> +exports[`Unit tests for CVCodeErrors Verify CodeErrors page renders and matches snapshot 1`] = `
you are snapshotting the jest object instead of the dom...

2022-10-18 05:07 UTC, abhinavrastogi-harness commented on src/modules/85-cv/pages/code-errors-agent-control/code-errors-agents-tokens/__tests__/__snapshots__/CVCodeErrors.test.tsx.snap
> +  "container": <div />,
and getting an empty div rendered

2022-10-18 05:07 UTC, abhinavrastogi-harness commented on src/modules/85-cv/strings/strings.en.yaml
> +codeErrorsAgents: '{{projectName}} Code Error Agents'
use `useScopedTitle` hook instead of appending project name by yourself. you'll get other features like scope icons etc for free

2022-10-20 01:23 UTC, David-Kreiner commented on src/modules/85-cv/pages/code-errors-agent-control/code-errors-agents-tokens/__tests__/CVCodeErrors.test.tsx
> +    expect(container).toMatchSnapshot()
Removed snapshots and added button assertions for navigation between the two pages with the tabs.

2022-10-20 01:25 UTC, David-Kreiner commented on src/modules/85-cv/pages/code-errors-agent-control/code-errors-agents-tokens/CVCodeErrorsAgentsTokens.tsx
> +  if (SRM_ET_EXPERIMENTAL) {
Moved to the CodeErrorsAgentControl

2022-10-20 01:27 UTC, David-Kreiner commented on src/modules/85-cv/pages/code-errors-agent-control/CVCodeErrorsAgentsControl.tsx
> +          className={css.pageHeaderHead}
This was done for a specific use case from our UI people and mockups to be able to fit a sub-header. I took this out for now but we may want to revisit in the future.

2022-10-20 15:20 UTC, tan-nhu submitted a review, later dismissed

2022-10-20 18:02 UTC, praneshg239 commented on src/modules/85-cv/pages/code-errors-agent-control/CVCodeErrors.module.scss
> +  padding-top: 10px;
<img width="818" alt="image" src="https://user-images.githubusercontent.com/95267551/197023967-d43e90ed-bd31-41cd-8b89-d237dd00fbb7.png">

you can make use of this pre-defined standard css variables from UICore

2022-10-20 18:03 UTC, praneshg239 commented on src/modules/85-cv/pages/code-errors-agent-control/CVCodeErrors.module.scss
> +  font-size: 13px;
Same for the font-size
<img width="903" alt="image" src="https://user-images.githubusercontent.com/95267551/197024332-260fc31e-5381-490c-a525-cda6ccdfb131.png">

2022-10-20 18:05 UTC, praneshg239 commented on src/modules/85-cv/pages/code-errors-agent-control/code-errors-agents-tokens/CVCodeErrorsAgentsTokens.tsx
> +    <>
No need of this fragment here. You can directly render `ChildAppMounter`

2022-10-20 18:09 UTC, praneshg239 commented on src/modules/85-cv/pages/code-errors-agent-control/code-errors-agents/CVCodeErrorsAgents.tsx
> +export const CVCodeErrorsAgents = (): JSX.Element => {
There is no much difference between `CVCodeErrorsAgentsTokens` and `CVCodeErrorsAgents` components. Only aspect which differs is `componentLocation`. So can we write a common component and pass `componentLocation` as props for that component?

2022-10-20 18:09 UTC, praneshg239 requested changes
Please check the comments

2022-10-21 04:23 UTC, abhinavrastogi-harness approved these changes

2022-10-21 05:43 UTC, praneshg239 approved these changes

2022-10-21 13:46 UTC, angelo-m-rodriguez approved these changes

2022-10-21 14:07 UTC, merged