feat: [SPG-539]: Project filter based on org and border changes in Module Container
harness/harness-core-ui pull request #11918
Opened 2022-10-17 14:03 UTC by avinashmadhwani02

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-17 15:41 UTC, abhinavrastogi-harness requested changes

2022-10-18 14:59 UTC, avinashmadhwani02 commented on src/modules/45-projects-orgs/RouteDestinations.tsx
> +          orgIdentifier
This is what I was looking for. Thanks

2022-10-19 04:02 UTC, abhinavrastogi-harness approved these changes

2022-10-19 04:19 UTC, deepesh-ui approved these changes

2022-10-19 04:20 UTC, merged