fix: [CDS-40969]: disable save button on yaml errors
harness/harness-core-ui pull request #11943
Opened 2022-10-18 13:46 UTC by radujomir

### Summary

Disable yaml save button when editor is invalid

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-19 08:29 UTC, yc147 approved these changes

2022-10-19 08:31 UTC, avinashmadhwani02 approved these changes

2022-10-19 08:35 UTC, mayankVermaHarness submitted a review, later dismissed

2022-10-19 09:36 UTC, radujomir commented
trigger rebase

2022-10-19 09:38 UTC, radujomir commented
trigger cypress

2022-10-19 10:16 UTC, abhinavrastogi-harness requested changes

2022-10-19 10:16 UTC, abhinavrastogi-harness commented on src/modules/30-secrets/pages/secretDetails/SecretDetails.tsx
> +import isEmpty from 'lodash/isEmpty'
```suggestion
import { isEmpty } from 'lodash-es'
```

2022-10-19 10:16 UTC, abhinavrastogi-harness commented on src/modules/30-secrets/pages/secretDetails/SecretDetails.tsx
> +  const [hasValidationErrors, setHasValidationErrors] = React.useState<boolean>(false)
I have the same question. What was the resolution here?

2022-10-19 10:16 UTC, abhinavrastogi-harness commented on src/modules/30-secrets/pages/secretDetails/SecretDetails.tsx
> +  const handleChange = React.useCallback(() => {
why do we need useCallback?

2022-10-19 10:16 UTC, abhinavrastogi-harness commented on src/modules/30-secrets/pages/secretDetails/SecretDetails.tsx
> +    requestAnimationFrame(() => {
why do we need raf?
copying and validating latest yaml to state on every frame seems very costly.

2022-10-19 13:01 UTC, radujomir commented on src/modules/30-secrets/pages/secretDetails/SecretDetails.tsx
> +  const handleChange = React.useCallback(() => {
we keep the same function to be executed until yamlhandler is changed

2022-10-19 13:01 UTC, radujomir commented on src/modules/30-secrets/pages/secretDetails/SecretDetails.tsx
> +import isEmpty from 'lodash/isEmpty'
will change

2022-10-19 13:02 UTC, radujomir commented on src/modules/30-secrets/pages/secretDetails/SecretDetails.tsx
> +    requestAnimationFrame(() => {
the onChange is handled until the value is updated, so we need to wait for the right state in order to perform some logic

2022-10-20 05:00 UTC, abhinavrastogi-harness approved these changes
depending on RAF for functionality seems hacky. that should not be needed unless you are working outside the React lifecycle.
it can bring new timing issues in the future.
Approved the PR for now.. but do look into refactoring this into a more stable and maintainable implementation.

2022-10-20 05:00 UTC, abhinavrastogi-harness commented on src/modules/30-secrets/pages/secretDetails/SecretDetails.tsx
> +import isEmpty from 'lodash/isEmpty'
please fix this before merging.

2022-10-24 06:25 UTC, radujomir commented
retrigger jest

2022-10-25 03:49 UTC, abhinavrastogi-harness approved these changes

2022-10-25 08:40 UTC, merged