fix: [PL-29182]: Hiding the Branch filter at the top and showing it in the executionList SubHeader in the ExecutionHistory Page
harness/harness-core-ui pull request #12041
Opened 2022-10-22 20:51 UTC by sumanmabd

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-27 07:39 UTC, sunnykesh-harness commented on src/strings/strings.en.yaml
> +allbranches: All Branches
Please define strings in one of modules. Support for this file is deprecated.

2022-10-27 12:51 UTC, cseverino789 approved these changes

2022-11-02 06:11 UTC, sumanmabd commented
retrigger jest

2022-11-02 07:36 UTC, sumanmabd commented
retrigger jest

2022-11-02 09:50 UTC, sumanmabd commented
retrigger jest

2022-11-02 11:48 UTC, sumanmabd commented
retrigger jest

2022-11-02 11:50 UTC, sumanmabd commented
retrigger jest

2022-11-02 11:55 UTC, depanshu-dhiman commented on src/modules/10-common/components/BranchFilter/BranchFilter.tsx
> +      {disabled ? null : showRefetchButon(disabled, repoName, error) ? (
Just use `showRefetchButon` since it already has a check for `disabled`

2022-11-02 11:58 UTC, depanshu-dhiman commented on src/modules/10-common/components/BranchFilter/BranchFilter.tsx
> +export const getBranchSelectOptions = (data: PMSPipelineListBranchesResponse[] = []): SelectOption[] => {
Is this required? `RepoBranchSelectV2` already has this exported, you can reuse from there

2022-11-02 12:00 UTC, sumanmabd commented on src/modules/10-common/components/BranchFilter/BranchFilter.tsx
> +export const getBranchSelectOptions = (data: PMSPipelineListBranchesResponse[] = []): SelectOption[] => {
you are saying about the BranchFilter component to be required ?or something else.

2022-11-02 12:03 UTC, depanshu-dhiman commented on src/modules/10-common/components/GitRemoteDetails/GitRemoteDetails.tsx
> +      ) : showBranch ? (
This will fail when `readOnly = true` and `showBranch = false`.

2022-11-02 12:06 UTC, depanshu-dhiman commented on src/modules/10-common/components/RepoBranchSelectV2/RepoBranchSelectV2.tsx
> +  isExecutionHistoryPage?: boolean
Revert if not needed

2022-11-02 12:09 UTC, depanshu-dhiman commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> -      {showSubHeader && <ExecutionListSubHeader {...rest} />}
Is `showSubHeader` not required anymore? Will we always show `ExecutionListSubHeader`?

2022-11-02 12:17 UTC, depanshu-dhiman commented on src/modules/70-pipeline/pages/execution-list/ExecutionListSubHeader/ExecutionListSubHeader.tsx
> +  const { borderless = true, onBranchChange, selectedBranch } = props
Can also destructure `showBranchFilter`

2022-11-02 12:18 UTC, depanshu-dhiman commented on src/modules/70-pipeline/pages/pipeline-details/PipelineDetails.tsx
> +  ) || { isExact: false }
Why `|| { isExact: false }` is required?

2022-11-02 12:20 UTC, depanshu-dhiman reviewed
Please address

2022-11-02 12:21 UTC, depanshu-dhiman commented on src/modules/10-common/components/BranchFilter/BranchFilter.tsx
> +export const getBranchSelectOptions = (data: PMSPipelineListBranchesResponse[] = []): SelectOption[] => {
`getBranchSelectOptions` is already defined in `RepoBranchSelectV2`. You can reuse that instead of redefining

2022-11-02 12:23 UTC, sumanmabd commented
retrigger jest

2022-11-02 17:56 UTC, sumanmabd commented on src/modules/10-common/components/BranchFilter/BranchFilter.tsx
> +      {disabled ? null : showRefetchButon(disabled, repoName, error) ? (
Okay

2022-11-02 18:00 UTC, sumanmabd commented on src/modules/10-common/components/BranchFilter/BranchFilter.tsx
> +export const getBranchSelectOptions = (data: PMSPipelineListBranchesResponse[] = []): SelectOption[] => {
yes i understood that it is already defined in the RepoBranchSelectV2. But there is extra code which we don't need it thats why i have defined here.

2022-11-02 18:06 UTC, sumanmabd commented on src/modules/10-common/components/GitRemoteDetails/GitRemoteDetails.tsx
> +      ) : showBranch ? (
will discuss with you tmrw.

2022-11-02 18:07 UTC, sumanmabd commented on src/modules/70-pipeline/pages/execution-list/ExecutionListSubHeader/ExecutionListSubHeader.tsx
> +  const { borderless = true, onBranchChange, selectedBranch } = props
yes.done

2022-11-02 22:59 UTC, sumanmabd commented
trigger cypress

2022-11-02 23:00 UTC, sumanmabd commented
trigger cypress

2022-11-04 06:51 UTC, udayvunnam commented on cypress/support/70-pipeline/constants.ts
> +export const executionSummaryAPI = `/pipeline/api/pipelines/execution/summary?routingId=accountId&accountIdentifier=accountId&projectIdentifier=project1&orgIdentifier=default&page=0&size=20&sort=star
We should avoid empty branch queryParam

2022-11-04 06:54 UTC, sumanmabd commented on cypress/support/70-pipeline/constants.ts
> +export const executionSummaryAPI = `/pipeline/api/pipelines/execution/summary?routingId=accountId&accountIdentifier=accountId&projectIdentifier=project1&orgIdentifier=default&page=0&size=20&sort=star
But initially to list all the executions of that pipeline, we are passing branch as empty for the API.

2022-11-04 06:56 UTC, udayvunnam commented on src/modules/10-common/components/BranchFilter/BranchFilter.tsx
> +  }, [loading, response, response?.data, response?.status, responseMessages])
we can avoid the effects and execute the logic as part of the render. use the useHook `lazy: disabled` instead

2022-11-04 06:57 UTC, udayvunnam commented on src/modules/10-common/components/BranchFilter/__tests__/BranchFilter.test.tsx
> +    expect(container).toMatchSnapshot()
Avoid snapshots, test what is expected by explicit assertions

2022-11-04 07:00 UTC, udayvunnam commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
>    const showSubHeader = hasExecutions || isAnyFilterApplied
isAnyFilterApplied should also consider the branch now. Please check. When the list is empty for a branch users should be able to go different branch

2022-11-04 08:08 UTC, sumanmabd commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
>    const showSubHeader = hasExecutions || isAnyFilterApplied
Yes. Checked.

2022-11-04 10:09 UTC, chetanvekariya-harness requested changes

2022-11-04 10:09 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepoBranchSelectV2/RepoBranchSelectV2.tsx
> +  isExecutionHistoryPage?: boolean
+1

2022-11-04 10:09 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +            disabled={disabled}
Pass `!hasExecutions` directly here. Initially, always All Branches is selected by default, right ?

2022-11-04 10:09 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +  const disabled = !hasExecutions ? selectedBranch === defaultBranchSelect : false
This disabled logic is not needed.

2022-11-04 10:09 UTC, chetanvekariya-harness commented on src/modules/75-cd/pages/pipeline-deployment-list/CDPipelineDeploymentList.tsx
> +  // const [branch, setBranch] = useState<string>()
Remove this.

2022-11-04 10:09 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +      branch: selectedBranch === defaultBranchSelect ? '' : selectedBranch,
As wrote in one of the above comment. Do not pass branch if selected branch is All Branches. This change will pass branch in the case of non-gitsync pipelines as well.

2022-11-04 10:24 UTC, sumanmabd commented
retrigger jest

2022-11-04 11:00 UTC, sumanmabd commented
retrigger jest

2022-11-04 11:03 UTC, sumanmabd commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +  const disabled = !hasExecutions ? selectedBranch === defaultBranchSelect : false
Done

2022-11-04 11:03 UTC, sumanmabd commented on src/modules/75-cd/pages/pipeline-deployment-list/CDPipelineDeploymentList.tsx
> +  // const [branch, setBranch] = useState<string>()
Done

2022-11-04 11:05 UTC, sumanmabd commented on src/modules/10-common/components/BranchFilter/BranchFilter.module.scss.d.ts
> + * Copyright 2021 Harness Inc. All rights reserved.
No, i have not created it. I know that it automatically generates the file

2022-11-04 11:10 UTC, sumanmabd commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +            disabled={disabled}
I can't pass there bcz if user is selected any branch and if there are no exeuctions in that selected branch, then user will not able to change the branch if it is disabled.

2022-11-04 11:11 UTC, sumanmabd commented on src/modules/10-common/components/BranchFilter/__tests__/BranchFilter.test.tsx
> +    expect(icon).toBeTruthy()
Okay

2022-11-07 06:51 UTC, sumanmabd commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +      branch: selectedBranch === defaultBranchSelect ? '' : selectedBranch,
Done

2022-11-07 07:33 UTC, sumanmabd commented
retrigger jest

2022-11-07 07:34 UTC, sumanmabd commented
trigger cypress

2022-11-07 07:35 UTC, sumanmabd commented
trigger cypress

2022-11-07 07:35 UTC, sumanmabd commented
retrigger jest

2022-11-07 07:36 UTC, sumanmabd commented
trigger cypress

2022-11-07 07:44 UTC, sumanmabd commented
trigger cypress

2022-11-07 19:08 UTC, sumanmabd commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
>    const showSubHeader = hasExecutions || isAnyFilterApplied
Done

2022-11-07 19:08 UTC, sumanmabd commented on src/modules/10-common/components/BranchFilter/BranchFilter.module.scss.d.ts
> + * Copyright 2021 Harness Inc. All rights reserved.
Resolved

2022-11-07 19:09 UTC, sumanmabd commented on src/modules/10-common/components/BranchFilter/BranchFilter.tsx
> +              refetch()
Done

2022-11-07 19:09 UTC, sumanmabd commented on src/modules/10-common/components/BranchFilter/__tests__/BranchFilter.test.tsx
> +    expect(container).toMatchSnapshot()
Done

2022-11-07 19:09 UTC, sumanmabd commented on src/modules/10-common/components/BranchFilter/__tests__/BranchFilter.test.tsx
> +    expect(icon).toBeTruthy()
Done

2022-11-08 05:01 UTC, chetanvekariya-harness requested changes

2022-11-08 07:37 UTC, depanshu-dhiman approved these changes

2022-11-08 07:43 UTC, chetanvekariya-harness approved these changes

2022-11-08 07:43 UTC, chetanvekariya-harness commented on src/modules/10-common/components/BranchFilter/__tests__/BranchFilter.test.tsx
> +jest.mock('@harness/uicore', () => ({
You should not mock this. You should only mock data and nothing else.

2022-11-08 07:43 UTC, chetanvekariya-harness commented on src/modules/75-cd/pages/pipeline-deployment-list/CDPipelineDeploymentList.tsx
> +  // const [branch, setBranch] = useState<string>()
The commented code is still there. What have you done here ?

2022-11-08 11:06 UTC, pbarapatre10 commented on src/modules/10-common/components/BranchFilter/BranchFilter.tsx
> +      showError(error?.message || getString('somethingWentWrong'))
nit: can we use some existing string constant here?

2022-11-08 11:10 UTC, pbarapatre10 commented on src/modules/75-cd/pages/pipeline-deployment-list/__tests__/CDPipelineDeploymentList.test.tsx
> +    return { data: jest.fn(), refetchh: jest.fn() }
typo in `refetchh` ?

2022-11-08 11:11 UTC, pbarapatre10 commented on src/modules/75-cf/pages/pipeline-deployment-list/__tests__/CFPipelineDeploymentList.test.tsx
> +    return { data: jest.fn(), refecth: jest.fn() }
same as above `refecth` typo.

2022-11-08 11:30 UTC, sumanmabd commented on src/modules/75-cd/pages/pipeline-deployment-list/__tests__/CDPipelineDeploymentList.test.tsx
> +    return { data: jest.fn(), refetchh: jest.fn() }
Done

2022-11-08 11:31 UTC, sumanmabd commented on src/modules/10-common/components/BranchFilter/__tests__/BranchFilter.test.tsx
> +jest.mock('@harness/uicore', () => ({
Hmm. done

2022-11-08 12:18 UTC, pbarapatre10 approved these changes

2022-11-08 12:30 UTC, chetanvekariya-harness approved these changes

2022-11-08 13:06 UTC, d1wilko approved these changes
CI related parts look good

2022-11-08 13:21 UTC, merged