fix: [CDS-45475]: partially hidden error message in create pipeline modal
harness/harness-core-ui pull request #12053
Opened 2022-10-25 12:11 UTC by vikrant-harness

### Summary

- To keep UX consistent the margin was removed but when error message pops-up it gets hidden behind the name-id field. so conditionally adding the margin when `formik` error populates

#### Screenshots

https://user-images.githubusercontent.com/106532291/197769692-77c1e07a-2385-4c30-a61d-1d1f34b6c800.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-25 16:08 UTC, rameshx requested changes

2022-10-25 16:08 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/CreateModal/PipelineCreate.tsx
> +                  errorCheck('name', formikProps) || get(formikProps, `errors.${getString('identifier').toLowerCase()}`)
Field names shouldn't be translated. Just use `errors.identifier`.

2022-10-25 16:08 UTC, rameshx commented on src/modules/75-cd/components/PipelineStudio/DeployStage/EditStageView/EditStageView.tsx
> +                                    get(formikProps, `errors.${getString('identifier').toLowerCase()}`)
this can be moved to a const as it is repeated

2022-10-25 16:32 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineStudio/DeployStage/EditStageView/EditStageView.tsx
> +                                    get(formikProps, `errors.${getString('identifier').toLowerCase()}`)
done

2022-10-25 17:40 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/CreateModal/PipelineCreate.tsx
> +                  errorCheck('name', formikProps) || get(formikProps, `errors.${getString('identifier').toLowerCase()}`)
@vikrant-harness Formik field names are part of the code and end up as name attributes on the input elements. We should only translate strings that the end user will see, hear, etc.

2022-10-25 17:44 UTC, rameshx submitted a review, later dismissed

2022-10-25 17:56 UTC, YounixIO submitted a review, later dismissed

2022-10-25 18:05 UTC, YounixIO approved these changes

2022-10-25 18:17 UTC, rameshx approved these changes

2022-10-25 19:37 UTC, PratyushGar approved these changes

2022-10-26 06:42 UTC, Tamaraius approved these changes

2022-10-27 08:14 UTC, merged