feat: [PL-29372]: Remove Swtich account feature flag from UI
harness/harness-core-ui pull request #12083
Opened 2022-10-27 07:02 UTC by avinashmadhwani02

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-27 07:05 UTC, pbarapatre10 submitted a review, later dismissed
LGTM

2022-10-27 07:10 UTC, abhinavrastogi-harness requested changes

2022-10-27 07:10 UTC, abhinavrastogi-harness commented on src/modules/10-common/modals/SwitchAccount/__snapshots__/SwitchAccount.test.tsx.snap
> -                aria-label="Harness"
please run `yarn` in local.. these labels should not be removed.
you need the newer version of uicore.

2022-10-28 11:06 UTC, abhinavrastogi-harness approved these changes

2022-11-02 04:39 UTC, pbarapatre10 approved these changes

2022-11-02 06:01 UTC, abhinavrastogi-harness approved these changes

2022-11-02 06:02 UTC, merged