feat: [PIE-6-53]: Allowed Values support for KubernetesInfraSpec
harness/harness-core-ui pull request #12105
Opened 2022-10-28 07:07 UTC by pankajsingh-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-28 08:20 UTC, pankajsingh-harness commented
retrigger titlecheck

2022-10-28 08:24 UTC, pankajsingh-harness commented
retrigger titlecheck

2022-10-28 11:26 UTC, ishantmehtaharness submitted a review, later dismissed
Looks Good
this is so simple to use. Thanks to Chetan and Ramesh

2022-10-28 11:31 UTC, chetanvekariya-harness requested changes

2022-10-28 11:31 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/KubernetesInfraSpec/KubernetesInfraSpec.tsx
> +                    allowedValuesType={ALLOWED_VALUES_TYPE.NUMBER}
Is this number field ? namespace is not number field. Please remove this change.

2022-10-28 11:31 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/KubernetesInfraSpec/KubernetesInfraSpec.tsx
> +                          allowedValuesType={ALLOWED_VALUES_TYPE.NUMBER}
Same as above. Remove this change.

2022-10-28 11:31 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/KubernetesInfraSpec/KubernetesInfraSpec.tsx
> +            templateProps={{
I think this change is required in Runtime view, not in Edit view. Please get in touch with Ramesh if you need more explanation.

2022-10-28 11:37 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/KubernetesInfraSpec/KubernetesInfraSpec.tsx
> +            templateProps={{
My bad. I think this change is fine.

2022-10-28 12:24 UTC, rameshx approved these changes

2022-10-29 05:10 UTC, pankajsingh-harness commented
retrigger jest

2022-10-29 05:14 UTC, pankajsingh-harness commented
retrigger jest

2022-10-31 05:50 UTC, chetanvekariya-harness requested changes

2022-10-31 05:50 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/KubernetesInfraSpec/KubernetesInfraSpec.tsx
> +                    allowedValuesType={ALLOWED_VALUES_TYPE.TEXT}
You do not need to make any change here. We are making changes for Number and ConnectorRef field and this field is neither of them.

2022-10-31 05:50 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/KubernetesInfraSpec/KubernetesInfraSpec.tsx
> +                          allowedValuesType={ALLOWED_VALUES_TYPE.TEXT}
Same as above.

2022-10-31 05:52 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/KubernetesInfraSpec/KubernetesInfraSpec.tsx
> +                    allowedValuesType={ALLOWED_VALUES_TYPE.TEXT}
This is related to last time changes we made for the number field. This field may have been missed last time. I found out this so updated. Do I need to create separate PR for this?

2022-11-03 05:11 UTC, chetanvekariya-harness submitted a review, later dismissed

2022-11-04 08:45 UTC, pankajsingh-harness commented
retrigger jest

2022-11-04 11:50 UTC, rameshx approved these changes

2022-11-04 12:15 UTC, chetanvekariya-harness approved these changes

2022-11-08 06:42 UTC, merged