fix: [PL-29414]: Adding Repo Filters across the listing pages
harness/harness-core-ui pull request #12120
Opened 2022-10-29 05:45 UTC by sumanmabd

### Summary

#### Screenshots

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/107131872/198815987-38271fcf-911c-4ee6-9dfc-cad578a8602f.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/107131872/198816001-7181b384-eeb3-464c-9fa0-7d429534a212.png">

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-09 08:58 UTC, udayvunnam commented on configs/devServerProxy.config.js
> +const targetLocalHost = (process.env.TARGET_LOCALHOST && JSON.parse(process.env.TARGET_LOCALHOST)) ?? false // set to false to target baseUrl environment instead of localhost
revert this and use .env instead for these configs to avoid accidental commits

2022-11-09 09:10 UTC, udayvunnam commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx
> +    setSelectedRepo(selected.value as string)
we can use either one of component state or URL state but not both

2022-11-09 09:42 UTC, udayvunnam commented on src/modules/72-templates-library/components/TemplateSelector/TemplateSelectorLeftView/TemplateSelectorLeftView.tsx
> +  ]
use API

2022-11-09 10:57 UTC, sumanmabd commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx
> +    setSelectedRepo(selected.value as string)
Done.

2022-11-09 10:58 UTC, sumanmabd commented on configs/devServerProxy.config.js
> +const targetLocalHost = (process.env.TARGET_LOCALHOST && JSON.parse(process.env.TARGET_LOCALHOST)) ?? false // set to false to target baseUrl environment instead of localhost
It happend by mistake, reverting.

2022-11-09 18:04 UTC, sumanmabd commented on src/modules/72-templates-library/components/TemplateSelector/TemplateSelectorLeftView/TemplateSelectorLeftView.tsx
> +  ]
Removed.

2022-11-09 19:04 UTC, yc147 requested changes
Move the logic of fetching `repoListData`, creating `repoSelectOptions`, `onClickHandler` and `showRefetchButton` inside `RepoFilter`.

You don't need to repeat this logic everywhere. Also the parent doesn't need to know about all this.

2022-11-09 20:52 UTC, sumanmabd commented
> Move the logic of fetching `repoListData`, creating `repoSelectOptions`, `onClickHandler` and `showRefetchButton` inside `RepoFilter`.
> 
> You don't need to repeat this logic in every component. Also the parent doesn't need to know about all this.

I can't reuse them, bcz there are three APIs that are getting fired depending on the page render. I can't pass different responses from the API to the single repoFilter Component. RepoFilter just filters the data we have given from the parent.

2022-11-09 21:10 UTC, yc147 reviewed
Create a common component and pass `useGetRepositoryList` as a prop
This components should have props  `getRepoListPromise`, `onRepoChange` and `className`.

2022-11-10 02:50 UTC, udayvunnam commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx
> +    updateQueryParams({ repoName: (selected.value || []) as string })
`[] as string` is improper. Undefined replaces the query Param to empty and we don't need empty array

2022-11-10 06:38 UTC, yc147 commented on src/modules/72-templates-library/pages/TemplatesPage/TemplatesPage.tsx
> +            onChange={selected => onChangeRepo(selected)}
Change to `onChange={onChangeRepo}`

2022-11-10 06:40 UTC, yc147 commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +  dropDownItems: SelectOption[]
Remove this

2022-11-10 06:41 UTC, yc147 commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +  selectedRepo: string
Change this to `value`

2022-11-10 06:41 UTC, yc147 commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +  placeholder?: string
Remove this

2022-11-10 06:42 UTC, yc147 commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +  onChange?: (selected: SelectOption) => void
onChange?: (repoName: string) => void

2022-11-10 06:42 UTC, yc147 commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +  onClick?: () => void
Remove this

2022-11-10 06:42 UTC, yc147 commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +  disabled?: boolean
Remove this

2022-11-10 06:42 UTC, yc147 commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +  showRefetchButton?: boolean
Remove this

2022-11-10 06:42 UTC, yc147 commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +  repoFilterClassName?: string
Change to `className`

2022-11-11 08:34 UTC, sunnykesh-harness requested changes
Please add some supporting cypress test for these changes.
 cc: @akash-nagarajan @naidu-harness

2022-11-11 13:41 UTC, d1wilko submitted a review, later dismissed
CI related parts look good

2022-11-11 15:04 UTC, udayvunnam commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +  >()
define only specific types that are available on this page

2022-11-11 15:07 UTC, udayvunnam commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +  }, [repoName])
We can avoid this effect and state and only use queryParams for the state

2022-11-12 13:51 UTC, sumanmabd commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +  >()
done

2022-11-14 03:03 UTC, sumanmabd commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +  }, [repoName])
Sure

2022-11-14 03:04 UTC, sumanmabd commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx
> +    updateQueryParams({ repoName: (selected.value || []) as string })
Okay

2022-11-14 03:35 UTC, vkbansal-harness approved these changes

2022-11-14 04:03 UTC, udayvunnam approved these changes

2022-11-14 04:43 UTC, merged