fix: [CDS-45013]: Artifact template linking support in services
harness/harness-core-ui pull request #12142
Opened 2022-10-31 11:10 UTC by samarth-sharma31

### Summary

#### Screenshots

NA

<img width="1792" alt="Screenshot 2022-10-31 at 2 23 53 PM" src="https://user-images.githubusercontent.com/96409598/198994750-8e1443ad-5a54-4caf-8b1f-8130a9a3f655.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-10 11:46 UTC, bhavya-sinha approved these changes

2022-11-10 13:11 UTC, yc147 approved these changes

2022-11-11 13:05 UTC, bhavya-sinha submitted a review, later dismissed

2022-12-07 12:02 UTC, bhavya-sinha submitted a review, later dismissed

2022-12-07 12:09 UTC, satyam-harness approved these changes

2022-12-07 12:46 UTC, bhavya-sinha approved these changes

2022-12-08 06:00 UTC, bhavya-sinha approved these changes

2022-12-08 11:00 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactConfigDrawer/ArtifactSourceTemplateDetails.tsx
> +  const queryParams = useParams<ProjectPathProps>()
This is duplicate of line 107 .

2022-12-08 11:21 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactConfigDrawer/ArtifactSourceTemplateDetails.tsx
> +              name: NameSchema({ requiredErrorMsg: getString('validation.nameRequired') })
Do we not need "identifier" validation here as `<FormInput.InputWithIdentifier/>` add name and  identifier field.

2022-12-08 11:39 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactListView/PrimaryArtifact/PrimaryArtifactView.tsx
> +    <section className={cx(css.rowItem, css.artifactSourceTemplateContainer, css.artifactRow)} key={'Dockerhub'}>
No, the key won't be required anymore -> this has been removed in this PR -> https://github.com/harness/harness-core-ui/pull/12871

2022-12-08 11:42 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AmazonMachineImage/AmazonMachineImage.tsx
> +      submitFormData?.(
This will submit the form twice. Once in validate and then in onSubmit. Validate should be used for validation onlu. [https://formik.org/docs/api/formik#validate-values-values--formikerrorsvalues--promiseany](url)

2022-12-08 11:44 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzureArtifacts.tsx
> +  const handleValidate = (formData: AzureArtifactsInitialValues) => {
Same as above

2022-12-08 11:44 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/CustomArtifact/CustomArtifact.tsx
> +  const handleValidate = (formData: CustomArtifactSource) => {
Same as above

2022-12-08 11:47 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ServiceV2ArtifactsSelection.tsx
> +      setTimeout(() => {
Is this timeout needed here? Not getting the context here why this has been added.

2022-12-08 11:55 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ServiceV2ArtifactsSelection.tsx
> +    await formikRef?.current?.submitForm()
This submitForm will not success. If this is added to validate the form, use validate instead of submit form/

2022-12-08 12:00 UTC, pankajsingh-harness commented on src/modules/70-pipeline/utils/stageHelpers.ts
> +    !!isTemplateContext
This will return `[...k8sRepositoryFormatTypes, ...nexus2RepositoryFormatTypes]` even when `isTemplateContext` is not passed as its optional value. 
Please check this and make it more typesafe.

2022-12-08 12:20 UTC, pankajsingh-harness requested changes
Added comments

2022-12-08 15:36 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactConfigDrawer/ArtifactSourceTemplateDetails.tsx
> +              name: NameSchema({ requiredErrorMsg: getString('validation.nameRequired') })
this is not required here.

2022-12-08 15:49 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AmazonMachineImage/AmazonMachineImage.tsx
> +      submitFormData?.(
done

2022-12-08 16:03 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactConfigDrawer/ArtifactSourceTemplateDetails.tsx
> +export function ArtifactSourceTemplateDetails(
yes on it.

2022-12-08 16:05 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactConfigDrawer/ArtifactSourceTemplateDetails.tsx
> +    projectIdentifier: string
was not required, removed

2022-12-08 16:05 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactConfigDrawer/ArtifactSourceTemplateDetails.tsx
> +  const queryParams = useParams<ProjectPathProps>()
done

2022-12-08 16:05 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/CustomArtifact/CustomArtifact.tsx
> +  const handleValidate = (formData: CustomArtifactSource) => {
discussed

2022-12-08 16:06 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ServiceV2ArtifactsSelection.tsx
> +    await formikRef?.current?.submitForm()
discussed over call and added comment as well

2022-12-08 16:17 UTC, samarth-sharma31 commented on src/modules/70-pipeline/utils/stageHelpers.ts
> +    !!isTemplateContext
done, moved the template check to the first in order

2022-12-08 16:23 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ServiceV2ArtifactsSelection.tsx
> +      setTimeout(() => {
yes it was not required, removed

2022-12-08 16:37 UTC, pankajsingh-harness submitted a review, later dismissed

2022-12-09 02:48 UTC, bhavya-sinha approved these changes

2022-12-09 03:53 UTC, pankajsingh-harness approved these changes

2022-12-09 06:13 UTC, merged