feat: [PL-26581]: Service versions showing NA in QA - hotfix
harness/harness-core-ui pull request #12242
Opened 2022-11-07 07:30 UTC by avinashmadhwani02

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-09 05:30 UTC, abhinavrastogi-harness requested changes

2022-11-09 05:30 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/ServiceVersions.tsx
> +    label: 'Pipelines under versions',
what is this string? why is it not just "Pipeline Service"?

2022-11-09 05:30 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/ServiceVersions.tsx
> +          const res = await fetch(row.url.startsWith('http') ? row.url : BASE_URL + row.url)
`for..await` will make the 20 api calls serial instead of parallel. 
Lets use the mechanism of `Promise.allSettled` like you suggested.

2022-11-09 05:49 UTC, avinashmadhwani02 commented on src/modules/33-auth-settings/pages/AccountOverview/views/ServiceVersions.tsx
> +    label: 'Pipelines under versions',
@naidu-harness has suggested this

2022-11-10 08:55 UTC, abhinavrastogi-harness approved these changes

2022-11-10 09:41 UTC, devinder-harness approved these changes

2022-11-10 09:43 UTC, merged