fix: [PL-29637]: Added template and template studio routes
harness/harness-core-ui pull request #12292
Opened 2022-11-08 14:04 UTC by avinashmadhwani02

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-08 14:43 UTC, abhinavrastogi-harness commented on src/modules/85-cv/RouteDestinations.tsx
> +    <RouteWithLayout
why is this added in `85-cv`?
it should be 45-projects or similar.

2022-11-08 14:43 UTC, abhinavrastogi-harness commented on src/modules/72-triggers/RouteDestinations.tsx
> +      path={routes.toTriggersDetailPage({ ...accountPathProps, ...triggerPathProps })}
project scope route destination should be in 45-projects only

2022-11-08 14:43 UTC, abhinavrastogi-harness commented on src/modules/10-common/navigation/MainNav/MainNav.tsx
> +    if (NEW_LEFT_NAVBAR_SETTINGS) {
what's this refactor for?

2022-11-08 15:33 UTC, kapilkumawat86 approved these changes

2022-11-09 05:28 UTC, abhinavrastogi-harness requested changes

2022-11-09 05:28 UTC, abhinavrastogi-harness commented on src/modules/10-common/navigation/MainNav/MainNav.tsx
> +    if (NEW_LEFT_NAVBAR_SETTINGS) {
okay. please add comments in the code to explain the business logic here

2022-11-09 05:28 UTC, abhinavrastogi-harness commented on src/modules/85-cv/RouteDestinations.tsx
> +    <RouteWithLayout
`TemplatesPage` comes from `@templates-library` module. .the route destination should be in that module.. not in CV

2022-11-10 07:01 UTC, kapilkumawat86 approved these changes

2022-11-10 07:04 UTC, abhinavrastogi-harness approved these changes

2022-11-10 08:55 UTC, merged