fix: [PLG-1552]: added lazy loading for stripe js
harness/harness-core-ui pull request #12326
Opened 2022-11-09 13:15 UTC by devinder-harness

### Summary
This PR removes duplicate `stripe.js` calls while `Initial App Load` as now it will be loaded only when user moves to `Plans` Page
https://harness.atlassian.net/browse/PLG-1552
https://harness.atlassian.net/browse/PLG-1551

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-09 13:30 UTC, dhruvUpadhyay07 approved these changes

2022-11-09 13:33 UTC, abhinavrastogi-harness requested changes

2022-11-09 13:33 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/subscriptions/plans/PlansPanel.tsx
> +export const PlanContainer = React.lazy(() => import('./PlanContainer'))
when `PlanContainer` is lazy loaded, it's a promise.
You need to wrap `<PlanContainer />` in `React.Suspense` when rendering it.

2022-11-09 13:33 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/subscriptions/plans/PlansPanel.tsx
> +export const PlanContainer = React.lazy(() => import('./PlanContainer'))
also, why is it exported? it was not exported earlier.

2022-11-10 04:16 UTC, abhinavrastogi-harness approved these changes

2022-11-10 12:00 UTC, devinder-harness commented
retrigger cypress-cv

2022-11-10 12:06 UTC, kapilkumawat86 approved these changes

2022-11-10 14:41 UTC, merged