fix: [cds-46460]: use clusterref if name doesn't exist
harness/harness-core-ui pull request #12398
Opened 2022-11-12 00:43 UTC by cjlee01

### Summary

Use cluster ref for the label names in the specify cluster dropdown if the name doesn't exist 

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-12 09:37 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/PipelineSteps/DeployClusterEntityStep/DeployClusterEntityInputStep.tsx
> +        label: clusterInList.name || clusterInList.clusterRef,
This should happen not here

2022-11-12 09:39 UTC, AshwinBhatkal-Harness requested changes
Please make the change in the useGetClustersData hook instead. 
Also, the bug tells ng ui merge step. So, why are we making the change here?

2022-11-12 19:36 UTC, cjlee01 commented on src/modules/75-cd/components/PipelineSteps/DeployClusterEntityStep/DeployClusterEntityInputStep.tsx
> +        label: clusterInList.name || clusterInList.clusterRef,
fixed this as per comment @AshwinBhatkal-Harness

2022-11-15 06:58 UTC, AshwinBhatkal-Harness approved these changes

2022-11-15 08:25 UTC, ishantmehtaharness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployClusters/DeployClusters.tsx
> +          return { label: defaultTo(cluster.name, ''), value: defaultTo(cluster.clusterRef, '') }
Shall we do cluster.name || cluster.clusterRef ?

2022-11-15 17:16 UTC, cjlee01 commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployClusters/DeployClusters.tsx
> +          return { label: defaultTo(cluster.name, ''), value: defaultTo(cluster.clusterRef, '') }
@AshwinBhatkal-Harness what do you think?

2022-11-15 19:32 UTC, ishantmehtaharness approved these changes
Looks Good

2022-11-16 08:34 UTC, vkbansal-harness approved these changes

2022-11-16 08:34 UTC, merged