feat: [CCM-9897]: [CCM AWS Connector] Choose Features Step Changes
harness/harness-core-ui pull request #12453
Opened 2022-11-15 17:21 UTC by rajarshee-harness

### Summary

#### Screenshots

<img width="1728" alt="Screenshot 2022-11-15 at 10 26 14 PM" src="https://user-images.githubusercontent.com/97532027/201984304-b133d0aa-abab-4f02-8418-9feb0a04d01e.png">

<img width="1728" alt="Screenshot 2022-11-15 at 10 47 25 PM" src="https://user-images.githubusercontent.com/97532027/201984319-e594ddb9-719b-4d5a-b560-58591fb18dd5.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-16 05:14 UTC, jenil-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +          <Text color={Color.GREY_900} style={{ fontWeight: 500 }}>
No `FontVariation` for this?

2022-11-16 05:15 UTC, jenil-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +    box-shadow: 0px 0px 1px rgba(40, 41, 61, 0.08), 0px 0.5px 2px rgba(96, 97, 112, 0.16);
Can we use predefined shadows or card component here?

2022-11-16 06:23 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +          <Text color={Color.GREY_900} style={{ fontWeight: 500 }}>
Couldn't find a `FontVariation` with fontSize 14 and fontWeight 500.

2022-11-16 06:24 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +    box-shadow: 0px 0px 1px rgba(40, 41, 61, 0.08), 0px 0.5px 2px rgba(96, 97, 112, 0.16);
There's no predefined value for this value and the Card component doesn't support `onMouseEnter` so couldn't use that.

2022-11-16 06:45 UTC, rishik30 approved these changes

2022-11-16 06:45 UTC, rishik30 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +import VisibilityIcon from '../images/ce-visibility.svg'
why have we not used the icons from uicore?

2022-11-16 07:37 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +import VisibilityIcon from '../images/ce-visibility.svg'
The same icons in UICore had height and width present in the element so couldn't override them to use smaller versions.

I will fix the icons in UICore and replace them in a follow up PR.

2022-11-16 10:50 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +          <Text color={Color.GREY_900} style={{ fontWeight: 500 }}>
You can use FORM_SUB_SECTION

2022-11-16 10:52 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/images/ce-settings.svg
> +<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-opacity=".3" d="m15.53 6.952-2.018-.246a5.086 5.086 0 0 0-.565-1.249l1.237-1.482a.219.219 0 0 0-.022-.306L12.725 2.3
We already have settings icon, do we have different settings icon for CE?

Please try to use the existing one.
Also, please add all these icons in uicore
Use currentColor instead of hardcoded color

2022-11-16 10:54 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +          <Text color={Color.GREY_900} style={{ fontWeight: 500 }}>
FORM_SUB_SECTION also has `letter-spacing: 0.5px;`

2022-11-16 11:03 UTC, avinashmadhwani02 requested changes

2022-11-16 11:03 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +    <Container onMouseEnter={setFeatureDetails}>
If not, we should add debounce. 
Also, do we want to reset onMouseLeave?

2022-11-16 11:03 UTC, avinashmadhwani02 commented on src/modules/35-connectors/strings/strings.en.yaml
> +        footer: <b>Default</b> from the Cost and Usage Report created in the previoue step. <b>This cannot be deselected.</b>
Can we make bold in code instead of adding <b> tag here?

2022-11-16 11:03 UTC, avinashmadhwani02 commented on src/modules/35-connectors/strings/strings.en.yaml
> +        footer: Adding <a target="_blank" href="https://docs.harness.io/article/80vbt5jv0q-set-up-cost-visibility-for-aws#aws_resource_optimization_using_auto_stopping_rules">these permissions</a> to
Same as above

2022-11-16 11:03 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +      font-size: 8px;
Can we use FontVariation?

2022-11-16 11:03 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +      font-weight: 500;
Font variation

2022-11-16 11:04 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/images/ce-settings.svg
> +<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-opacity=".3" d="m15.53 6.952-2.018-.246a5.086 5.086 0 0 0-.565-1.249l1.237-1.482a.219.219 0 0 0-.022-.306L12.725 2.3
Please follow SVG guidelines for all the SVG's

2022-11-16 11:06 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +              <FeatureCard
Can we use formik instead of maintaining state manually?

2022-11-16 11:11 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +          <Text color={Color.GREY_900} style={{ fontWeight: 500 }}>
It should be from the design-system, please check with UX.

2022-11-16 11:59 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +      font-weight: 500;
Done

2022-11-16 11:59 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +      font-size: 8px;
Couldn't find a FontVariation with fontSize 8.

2022-11-16 12:00 UTC, rajarshee-harness commented on src/modules/35-connectors/strings/strings.en.yaml
> +        footer: <b>Default</b> from the Cost and Usage Report created in the previoue step. <b>This cannot be deselected.</b>
Done

2022-11-16 12:00 UTC, rajarshee-harness commented on src/modules/35-connectors/strings/strings.en.yaml
> +        footer: Adding <a target="_blank" href="https://docs.harness.io/article/80vbt5jv0q-set-up-cost-visibility-for-aws#aws_resource_optimization_using_auto_stopping_rules">these permissions</a> to
Done

2022-11-16 12:00 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +            {feature?.prefix}
This shouldn't be optional. Have fixed it

2022-11-17 05:56 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +      font-size: 8px;
Done, now using a variation from design-system.

2022-11-17 05:56 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +import VisibilityIcon from '../images/ce-visibility.svg'
Done. 

Moved the icons to UICore.

2022-11-17 05:57 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +  icon: string
Changed this to `IconName` since the icons are moved to UICore.

2022-11-17 05:57 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +          <Text color={Color.GREY_900} style={{ fontWeight: 500 }}>
Done, now using a variation from design-system.

2022-11-17 08:57 UTC, rajarshee-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CrossAccountRoleStep1.tsx
> +    <Container onMouseEnter={setFeatureDetails}>
Replaced it with `onMouseOver`.

2022-11-17 09:24 UTC, avinashmadhwani02 approved these changes

2022-11-17 09:29 UTC, rishik30 approved these changes

2022-11-17 09:38 UTC, kapilkumawat86 approved these changes

2022-11-17 09:38 UTC, merged