fix: [PIE-6417]: removed useEffect to handle the repo change
harness/harness-core-ui pull request #12470
Opened 2022-11-16 12:39 UTC by sumanmabd

### Summary

Removed the useEffect and added the branch with state update in the onChange repo handler
#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-16 13:07 UTC, douglasnfrazao commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +    setSelectedBranch(undefined)
We don't need to verify anymore if repoName is null?

2022-11-16 13:11 UTC, sumanmabd commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +    setSelectedBranch(undefined)
lets say user selected a repo and removed the repo from the filter. now the repoName is null, and branch selected is also null. Fine right ? what ever the repo Name maybe , branch should be always should be set to null after the repo is changed in filter even if it is null.

2022-11-16 13:35 UTC, douglasnfrazao approved these changes
looks good

2022-11-16 16:19 UTC, sumanmabd commented
retrigger coverage

2022-11-16 16:24 UTC, udayvunnam submitted a review, later dismissed

2022-11-17 01:16 UTC, sumanmabd commented
retrigger coverage

2022-11-17 03:39 UTC, sumanmabd commented
retrigger cypress-cd

2022-11-17 04:22 UTC, sumanmabd commented
retrigger coverage

2022-11-17 05:24 UTC, chetanvekariya-harness submitted a review, later dismissed

2022-11-17 07:14 UTC, udayvunnam commented
add coverage for the newly added function

2022-11-17 12:15 UTC, sunnykesh-harness requested changes

2022-11-21 03:42 UTC, sunnykesh-harness reviewed
Unblocking as this is solving few other important issue but please track the new issues created with this change. It will be good if all can be fixed together and we avoid any regression.

2022-11-24 10:32 UTC, udayvunnam submitted a review, later dismissed

2022-11-25 09:56 UTC, sunnykesh-harness approved these changes

2022-11-25 10:12 UTC, udayvunnam approved these changes

2022-11-25 10:19 UTC, chetanvekariya-harness approved these changes

2022-11-25 10:56 UTC, kapilkumawat86 approved these changes

2022-11-25 10:57 UTC, merged