fix: [CDS-46713]: Added support for Repository & Artifact/Image Path for Artifactory trigger
harness/harness-core-ui pull request #12475
Opened 2022-11-16 16:37 UTC by pankajsingh-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-17 08:55 UTC, AshwinBhatkal-Harness approved these changes

2022-11-17 08:57 UTC, bhavya-sinha submitted a review, later dismissed

2022-11-17 10:31 UTC, chetanvekariya-harness requested changes

2022-11-17 10:31 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/ArtifactoryArtifactPath.tsx
> +          label: imagePath.imagePath || '',
use `defaultTo(imagePath.imagePath, '')` to keep low cognitive complexity

2022-11-17 10:31 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/ArtifactoryArtifactPath.tsx
> +    if (getMultiTypeFromValue(formikProps?.values?.repository) === MultiTypeInputType.RUNTIME) return true
If parent field is Runtime then we allow user to create new items in the dropdown. Please follow same approach here. Do not disable the field

2022-11-17 10:31 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/ArtifactoryArtifactPath.tsx
> +          <ConfigureOptions
Use `SelectConfigureOption` component here.

2022-11-17 10:31 UTC, chetanvekariya-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
> +                  <ServerlessArtifactoryRepository
Is this intended ? Earlier it was text field and now it will be select field.

2022-11-17 10:31 UTC, chetanvekariya-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
> +                      <ArtifactoryArtifactPath
Is it intended that we do not want to allow Runtime and expression for these field ?

2022-11-17 10:45 UTC, satyam-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
> +                      <ArtifactoryArtifactPath
yes, for triggers we do not support runtime, for expressions discussion is still going on, so as of now we have removed expressions support as well

2022-11-17 10:46 UTC, satyam-harness submitted a review, later dismissed

2022-11-17 10:53 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
> +                  <ServerlessArtifactoryRepository
Yes. This is the change. That has been done to support **repository** dropdown

2022-11-17 12:44 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/ArtifactoryArtifactPath.tsx
> +          <ConfigureOptions
Done

2022-11-17 12:46 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/ArtifactoryArtifactPath.tsx
> +    if (getMultiTypeFromValue(formikProps?.values?.repository) === MultiTypeInputType.RUNTIME) return true
This is confusing due to variable name. Updated the variable name. This function is to check whether load imagePathList data or not?

2022-11-17 12:46 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/ArtifactoryArtifactPath.tsx
> +          label: imagePath.imagePath || '',
Done

2022-11-17 15:36 UTC, pankajsingh-harness commented
retrigger cypress-cd

2022-11-17 15:36 UTC, pankajsingh-harness commented
retrigger cypress-pipeline

2022-11-17 15:55 UTC, chetanvekariya-harness approved these changes

2022-11-17 16:05 UTC, AshwinBhatkal-Harness approved these changes

2022-11-18 06:09 UTC, pankajsingh-harness commented
retrigger cypress-pipeline

2022-11-18 06:41 UTC, merged