Pl 23301 browser router swaraj 3 new
harness/harness-core-ui pull request #12491
Opened 2022-11-17 10:23 UTC by swarajcheguri-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-17 11:02 UTC, abhinavrastogi-harness requested changes

2022-11-17 11:02 UTC, abhinavrastogi-harness commented on src/3rd-party/ThirdPartyIntegrations.tsx
> +        accountId: accounts?.find(({ uuid }) => useLocation().pathname.includes(uuid as string))?.uuid || ''
calling hooks inline (and conditionally) is not allowed. make it like this across all files:


```
const myLocation = useLocation()

useEffect(() => {
...
myLocation.pathnames.includes...
})
```

note the use of `myLocation` instead of `location` here to avoid conflict with `window.location`.

obviously, we can come up with a better name than `myLocation`.

2022-11-17 13:04 UTC, swarajcheguri-harness commented on src/3rd-party/ThirdPartyIntegrations.tsx
> +        accountId: accounts?.find(({ uuid }) => useLocation().pathname.includes(uuid as string))?.uuid || ''
did not observe that useLocation was hook . Sorry

2022-11-21 11:14 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/MonacoEditor/MonacoEditor.tsx
> +      if (window.browserRouterEnabled) {
since `getLocationPathName` already checks for `window.browserRouterEnabled`, why do we need this condition again?

2022-11-21 11:14 UTC, abhinavrastogi-harness commented on src/framework/utils/WindowLocation.ts
> +    pathName = `/${nameSpace}ng/`
we should add a `__DEV__` check here before appending `ng` to the path.
in local there will be no namespace or `ng`.

2022-11-21 11:16 UTC, swarajcheguri-harness commented on src/framework/utils/WindowLocation.ts
> +    pathName = `/${nameSpace}ng/`
when browserRouter is enabled we are adding ng as basePath for the browserRouter so ng will be always be there

2022-11-21 11:20 UTC, swarajcheguri-harness commented on src/modules/10-common/components/MonacoEditor/MonacoEditor.tsx
> +      if (window.browserRouterEnabled) {
we want  to give pathname as  '/ ' when browswerRouter is enabled and also is __DEV__  in other cases it cany be anything what getLocationPathname gives

2022-11-21 11:24 UTC, abhinavrastogi-harness commented on src/framework/utils/WindowLocation.ts
> +    pathName = `/${nameSpace}ng/`
in local when browser router is enabled, basepath will just be `/`, right? it wont be `/ng/` 🤔

2022-11-22 05:35 UTC, abhinavrastogi-harness approved these changes

2022-11-22 05:36 UTC, merged