fix: [PIE-5846]: canvas drag issues in pipeline graph
harness/harness-core-ui pull request #12501
Opened 2022-11-17 14:26 UTC by rameshx

### Summary

- Fixes an issue where the graph permanently ends up in dragging state despite mouse clicks.
- Fixes an issue causing the graph to move quickly when it is dragged and then positioned by dragging the canvas.
- `mousemove` events are throttled using `requestAnimationFrame` instead of lodash throttle.

**Issues:**

https://user-images.githubusercontent.com/52284933/202470141-4f6ddd10-86da-4412-8a0e-8358bfcabb63.mov

2022-11-17 15:10 UTC, vkbansal-harness requested changes

2022-11-18 05:07 UTC, rameshx commented on package.json
> +    "raf-schd": "^4.0.3",
removed the dependency and added required func to common util

2022-11-18 06:48 UTC, PratyushGar approved these changes

2022-11-18 07:13 UTC, kapilkumawat86 approved these changes

2022-11-18 07:14 UTC, merged