fix: [CDS-45720]: fixed config file for filestore
harness/harness-core-ui pull request #12502
Opened 2022-11-17 15:02 UTC by radujomir

### Summary

Fixed config details for Harness files

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-17 15:23 UTC, radujomir commented
retrigger titlecheck

2022-11-17 15:29 UTC, AshwinBhatkal-Harness commented on src/modules/31-filestore/utils/FileStoreUtils.tsx
> +export const isRuntimeInput = (str: any): boolean => typeof str === 'string' && str?.includes(RUNTIME_INPUT_VALUE)
We have a util already for this - isValueRuntimeInput

2022-11-17 15:30 UTC, AshwinBhatkal-Harness commented on src/modules/31-filestore/components/MultiTypeFileSelect/FileStoreSelect/FileStoreSelectField.tsx
> +  const fileStoreValue = !isRuntimeInput(get(formik?.values, name.substr(0, name.length - 3)))
What are we doing here?

2022-11-17 15:33 UTC, radujomir commented on src/modules/31-filestore/components/MultiTypeFileSelect/FileStoreSelect/FileStoreSelectField.tsx
> +  const fileStoreValue = !isRuntimeInput(get(formik?.values, name.substr(0, name.length - 3)))
by default the name is pathname and it looks for path->path->files[0], in case it is runtime input we need to skip extracting the value

2022-11-17 15:54 UTC, AshwinBhatkal-Harness commented on src/modules/31-filestore/components/MultiTypeFileSelect/FileStoreSelect/FileStoreSelectField.tsx
> +  const fileStoreValue = !isRuntimeInput(get(formik?.values, name.substr(0, name.length - 3)))
Ideally we should be showing this as runtime input. Not a fixed component here

2022-12-16 03:45 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesWizard/ConfigFilesSteps/MultiConfigSelectField/MultiConfigSelectField.tsx
> +                  className={'configureOptions'}
Class name should not be hardcoded here. As classes get minified in prod build. Use css module class names.

2022-12-16 03:46 UTC, pankajsingh-harness requested changes
Added comment

2022-12-16 06:07 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/ConfigFilesSelection/ConfigFilesWizard/ConfigFilesSteps/MultiConfigSelectField/MultiConfigSelectField.tsx
> +              allowedTypes={defaultTo(allowableTypes, [MultiTypeInputType.FIXED, MultiTypeInputType.RUNTIME])}
We should not be doing this. allowableTypes should be passed to the component instead. No default to. Passing to the component ensures the relevant types are present in any view that component is used

2022-12-20 03:51 UTC, AshwinBhatkal-Harness approved these changes

2022-12-20 03:55 UTC, pankajsingh-harness approved these changes

2022-12-20 13:11 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2022-12-21 10:52 UTC, litvinovstas approved these changes

2022-12-21 11:01 UTC, AshwinBhatkal-Harness approved these changes

2022-12-21 11:27 UTC, merged