fix: [PIE-6461]: Handled type error for the API prop
harness/harness-core-ui pull request #12511
Opened 2022-11-18 03:34 UTC by sumanmabd

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-18 06:07 UTC, vkbansal-harness requested changes

2022-11-18 06:07 UTC, vkbansal-harness commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +    if (isPipelinePage) refetchRepoForPipelines()
Instead of writing the logic like this. Please update the logic of `lazy` based on flags

2022-11-18 07:40 UTC, chetanvekariya-harness approved these changes

2022-11-18 07:40 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +    error: ErrorForPipelines,
Follow proper camel-case here. `errorForPipeline`

2022-11-18 09:48 UTC, chetanvekariya-harness requested changes

2022-11-18 09:48 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +    lazy: isTemplatesPage
This should be false in case of Templates page. Reverse your condition here.

2022-11-18 11:10 UTC, sumanmabd commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +    lazy: isTemplatesPage
yes @chetanvekariya-harness before when we are in the call. it is refetched by my mistake. Corrected it. Now, you can check.Thanks

2022-11-18 12:00 UTC, udayvunnam commented on src/modules/70-pipeline/pages/execution-list/ExecutionListSubHeader/ExecutionListSubHeader.tsx
> +            isExecutionsPage={true}
nit: `isExecutionsPage` is enough

2022-11-18 12:08 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepoFilter/__tests__/RepoFilter.test.tsx
> +    expect(useGetRepositoryList).toHaveBeenLastCalledWith(
These are always called. You should check if data is appearing in dropdown. That would be right way to test.

2022-11-18 12:08 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepoFilter/__tests__/RepoFilter.test.tsx
> +    expect(useGetExecutionRepositoriesList).toBeCalled()
Same here.

2022-11-18 12:08 UTC, chetanvekariya-harness commented on src/modules/72-templates-library/pages/TemplatesPage/__tests__/TemplatesPage.test.tsx
> +    expect(useGetRepositoryList).toBeCalled()
Same here.

2022-11-18 18:01 UTC, sumanmabd commented on src/modules/10-common/components/RepoFilter/__tests__/RepoFilter.test.tsx
> +    expect(useGetRepositoryList).toHaveBeenLastCalledWith(
Done

2022-11-18 18:01 UTC, sumanmabd commented on src/modules/10-common/components/RepoFilter/__tests__/RepoFilter.test.tsx
> +    expect(useGetExecutionRepositoriesList).toBeCalled()
Done

2022-11-18 18:01 UTC, sumanmabd commented on src/modules/10-common/components/RepoFilter/__tests__/RepoFilter.test.tsx
> +    expect(getRepoListForTemplate).toBeCalled()
Done

2022-11-19 19:57 UTC, samarth-sharma31 requested changes

2022-11-19 19:57 UTC, samarth-sharma31 commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +    data: repoListOfPipeline,
I feel that the repo filter component has become much more complex and i think we can simplify it as follows ->

We can have three wrappers around repo filter --> **PipelinesPageRepoFilter**, **ExecutionsPageRepoFilter**, **TemplatesPageRepoFilter**

All three wrappers will use the common **RepoFilter** component -> which can accept -> onRefetch, repositories, isLoading, error as new props along with the existing props and the three parent wrappers will contain their own data fetching logic and then can pass them as above mentioned props to the common RepoFilter component

I feel this approach will help us in making it more simpler and cleaner with less if else checks in common component.
Also will make it more scalable, as in future if we want to integrate repo filter at any other page - it will be more intuitive to create a wrapper for data fetching (similar to **PipelinesPageRepoFilter**, **ExecutionsPageRepoFilter**, **TemplatesPageRepoFilter**)  as compared to adding more checks in the common component.

@sumanmabd @udayvunnam @chetanvekariya-harness @vkbansal-harness Please let me know your thoughts on this.

2022-11-23 11:37 UTC, sumanmabd commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +    data: repoListOfPipeline,
sure. Closing this PR, fix for this raised in other PR - https://github.com/harness/harness-core-ui/pull/12533

2022-11-23 11:37 UTC, closed without merging