fix: [PIE-6484]: calling Repo list API from parent
harness/harness-core-ui pull request #12533
Opened 2022-11-19 23:03 UTC by sumanmabd

### Summary
Refactoring the repoFilter component code. Passed reponses of APIs from parent to repoFilter, which handles filtering.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-20 09:21 UTC, sumanmabd commented
retrigger jest

2022-11-20 09:22 UTC, sumanmabd commented
retrigger cypress-cv

2022-11-20 09:34 UTC, sumanmabd commented
retrigger cypress-cv

2022-11-22 08:43 UTC, pankajsingh-harness commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +  error?: GetDataError<Failure | Error> | null
error is used here to just check if it's empty or not. You can pass isError boolean param from the parent element this way it will remove the dependency from restful-react as we have started migration from restful-react to React Query

2022-11-22 08:44 UTC, pankajsingh-harness requested changes
Added comment

2022-11-22 08:45 UTC, sumanmabd commented on src/modules/10-common/components/RepoFilter/RepoFilter.tsx
> +  error?: GetDataError<Failure | Error> | null
Cool. Nice one to remove dependency of restful-react.

2022-11-23 12:09 UTC, samarth-sharma31 approved these changes

2022-11-24 02:27 UTC, pankajsingh-harness approved these changes

2022-11-24 04:57 UTC, udayvunnam commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx
> +              onRefetch={onRefetch}
Why don't you pass the `refetch` directly instead of another wrapper function around it

2022-11-24 05:08 UTC, udayvunnam commented on src/modules/72-templates-library/pages/TemplatesPage/TemplatesPage.tsx
> +              isError={!isEmpty(errorOfRepoForTemplates)}
no need for `isEmpty` `!!error` should be enough

2022-11-24 07:42 UTC, shaurya-harness approved these changes

2022-11-24 07:57 UTC, merged