feat: [CDS-46734]: Supported runtime for fields in Jira steps
harness/harness-core-ui pull request #12570
Opened 2022-11-22 05:10 UTC by sonaligoyal-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-01 08:40 UTC, sonaligoyal-harness commented
retrigger jest

2022-12-01 14:47 UTC, rameshx approved these changes

2022-12-01 14:47 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraApproval/helper.ts
> +  allowedValues?.map(allowedValue => ({
If `allowedValues` can be falsy, it's better to update param type to  `JiraFieldAllowedValueNG[] | undefined` and return type too.

2022-12-01 14:47 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraCreate.tsx
> +      template?.spec?.fields?.forEach((obj, index) => {
Inside if block `template.spec.fields` will be truthy
```suggestion
      template.spec.fields.forEach((obj, index) => {
```

2022-12-01 14:47 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraCreateDeploymentMode.tsx
> +              )
Can we avoid mutating `initialValues`? Is it possible to do this by using formik's `setFieldValue`?

2022-12-01 14:47 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraFieldsRenderer.tsx
> +    }
Can this be done using `setFieldValue` instead of directly mutating values?

2022-12-01 14:47 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraFieldsRenderer.tsx
> +              props.formik.setFieldValue(formikFieldPath, valueArr.toString())
`valueArr?.join(',')` can be removed `valueArr.toString()` will join using `,`
```suggestion
              props.formik.setFieldValue(formikFieldPath, valueArr.toString())
```

2022-12-01 14:47 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/helper.ts
> +export const processMultiSelectTypeInputRuntimeValues = (selectedFieldValue: string) => {
update arg type as `selectedFieldValue` can be an array

2022-12-01 14:47 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraUpdate/JiraUpdateDeploymentMode.tsx
> +          <div key={field.name}>
If the wrapper `div` is not required, remove it, and add the key to `FormInput.MultiTextInput`.

2022-12-01 19:00 UTC, sonaligoyal-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraCreateDeploymentMode.tsx
> +              )
Here, we need to update initialValues so cannot be done using setFieldValue

2022-12-02 08:51 UTC, rameshx submitted a review, later dismissed

2022-12-02 11:17 UTC, chetanvekariya-harness requested changes

2022-12-02 11:17 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraCreateDeploymentMode.tsx
> +  }, [issueTypeFixedValue])
connectorRefFixedValue and projectKeyFixedValue are also required here.

2022-12-02 11:17 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraCreateDeploymentMode.tsx
> +  }, [issueMetaResponse?.data])
You might want to add `projectKeyFixedValue` and `issueTypeFixedValue` here.

2022-12-02 11:17 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraFieldsRenderer.tsx
> +  const allowableTypes: AllowedTypes = props.deploymentMode
I think this should be passed from props, similar to how it has been done for other steps.

2022-12-02 11:17 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraUserMultiTypeInput.tsx
> +  const allowableTypes: AllowedTypes = props?.deploymentMode
Same as above. Double check if you should pass this as props.

2022-12-02 11:17 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraUpdate/JiraUpdateDeploymentMode.tsx
> +          <FormInput.MultiTextInput
should we use TextFieldInputSetView component ?

2022-12-02 11:17 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraFieldsRenderer.tsx
> +          <MultiSelectTypeInput
For this, **SelectInputSetView** can be used as it handles Allowed Values automatically.

2022-12-02 11:26 UTC, sonaligoyal-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraCreateDeploymentMode.tsx
> +  }, [issueTypeFixedValue])
If we pass it, api will be hit unnecessarily which we don't want

2022-12-02 11:27 UTC, sonaligoyal-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraFieldsRenderer.tsx
> +  const allowableTypes: AllowedTypes = props.deploymentMode
For now, I haven't added that support because it is already a risky change which we are putting forward. We will pick this in next enhancement.

2022-12-02 11:35 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraCreateDeploymentMode.tsx
> +  }, [issueTypeFixedValue])
Could you try it out once ?

2022-12-02 11:37 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraFieldsRenderer.tsx
> +    }
+1

2022-12-02 14:59 UTC, sonaligoyal-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraFieldsRenderer.tsx
> +          <MultiSelectTypeInput
Didn't update this component as we don't want formik to be used internally also here

2022-12-02 14:59 UTC, sonaligoyal-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraUpdate/JiraUpdateDeploymentMode.tsx
> +          <FormInput.MultiTextInput
done

2022-12-02 15:17 UTC, sonaligoyal-harness commented
retrigger jest

2022-12-02 15:45 UTC, chetanvekariya-harness approved these changes

2022-12-02 17:07 UTC, Eric761 approved these changes

2022-12-02 17:21 UTC, merged