feat: [PIE-6208]: adding discard button to the closing without saving dialog
harness/harness-core-ui pull request #12614
Opened 2022-11-23 18:48 UTC by Sagar-Rajput7

### Summary

#### Screenshots

<img width="522" alt="image" src="https://user-images.githubusercontent.com/98325173/203624888-893ca7eb-d2dc-40ee-af8f-92c437f6c293.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-23 21:36 UTC, devinder-harness submitted a review, later dismissed

2022-11-23 21:44 UTC, PratyushGar approved these changes

2022-11-23 22:00 UTC, satyam-harness submitted a review, later dismissed

2022-11-24 05:28 UTC, udayvunnam submitted a review, later dismissed

2022-11-24 06:21 UTC, chetanvekariya-harness requested changes

2022-11-24 06:21 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
> +          customButtonClass={css.customButtons}
I think we should have same experience and styling for NavigationCheck component. Could you add styles directly to modal inside NavigationCheck component and just pass showDiscardButton and onDiscardButtonClick props from here ?

2022-11-25 05:17 UTC, chetanvekariya-harness approved these changes

2022-11-25 05:17 UTC, chetanvekariya-harness commented on src/modules/10-common/components/NavigationCheck/NavigationCheck.tsx
> +  discardFunction,
**onDiscardButtonClick** or **handleDiscardButtonClick** are better names as a prop

2022-11-25 06:46 UTC, Sagar-Rajput7 commented on src/modules/10-common/components/NavigationCheck/NavigationCheck.tsx
> +  discardFunction,
Changed to onDiscardButtonClick

2022-11-25 07:37 UTC, chetanvekariya-harness approved these changes

2022-11-25 09:52 UTC, sonaligoyal-harness approved these changes

2022-11-25 09:53 UTC, merged