feat: [CI-6141]: bitrise and github action plugin for CI step
harness/harness-core-ui pull request #12638
Opened 2022-11-24 16:22 UTC by shaurya-harness

### Summary

 bitrise and github action plugin for CI step

#### Screenshots

![Screenshot 2022-11-23 at 2 56 14 PM](https://user-images.githubusercontent.com/113332561/203829827-dff63ac3-27d3-473d-9102-985a71d2d104.png)
![Screenshot 2022-11-23 at 2 56 28 PM](https://user-images.githubusercontent.com/113332561/203829841-903a4cc3-4b48-4361-87f9-b86ee473deb6.png)

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-30 13:59 UTC, d1wilko submitted a review, later dismissed
Nothing concerning stands out :)

2022-12-15 10:57 UTC, shaurya-harness commented
retrigger coverage

2022-12-15 12:36 UTC, shaurya-harness commented
retrigger coverage

2022-12-15 13:07 UTC, shaurya-harness commented
retrigger coverage

2022-12-16 10:43 UTC, d1wilko requested changes
few small changes but looking good

2022-12-16 10:43 UTC, d1wilko commented on src/modules/10-common/components/MultiTypeMap/MultiTypeMap.tsx
> +  placeholder?: Array<string>
I'm not too keen on this being array - perhaps it would be better as 2 separate string variable

if you need to keep it as an array maybe rename it to something like placeholders

2022-12-16 10:43 UTC, d1wilko commented on src/modules/10-common/components/MultiTypeMapInputSet/MultiTypeMapInputSet.tsx
> +  placeholder?: Array<string>
same concern as above

2022-12-16 10:43 UTC, d1wilko commented on src/modules/75-ci/components/PipelineSteps/StepCommonFields/StepCommonFields.tsx
> +  disableRunAsUser?: boolean
I think it is best to have affirmative variables instead of negative variables

something like enableRunAsUser can be easier to follow later in the code :)

2022-12-16 12:35 UTC, shaurya-harness commented on src/modules/75-ci/components/PipelineSteps/StepCommonFields/StepCommonFields.tsx
> +  disableRunAsUser?: boolean
@d1wilko this is mostly being used as an enabled field for a lot of steps, so I added a negative variable for 1 particular use case, if I change it to affirmative one will need to add it for multiple steps and increase scope of regression.

2022-12-16 12:35 UTC, shaurya-harness commented on src/modules/10-common/components/MultiTypeMap/MultiTypeMap.tsx
> +  placeholder?: Array<string>
@d1wilko kept it as an array since there were 2 placeholders one for key and one for value in a key:value scenario. will update the naming to cater that.

2022-12-16 13:23 UTC, d1wilko submitted a review, later dismissed
LGTM :)

2022-12-16 13:23 UTC, d1wilko commented on src/modules/75-ci/components/PipelineSteps/StepCommonFields/StepCommonFields.tsx
> +  disableRunAsUser?: boolean
fair enough :)

2022-12-16 15:02 UTC, vardanbansal-harness submitted a review, later dismissed

2023-01-03 17:15 UTC, vardanbansal-harness approved these changes

2023-01-04 04:59 UTC, shaurya-harness commented
retrigger jest

2023-01-04 04:59 UTC, shaurya-harness commented
retrigger coverage

2023-01-04 05:01 UTC, merged