feat: [CDS-46669]: Add Gitops Fetch Linked Apps Step
harness/harness-core-ui pull request #12664
Opened 2022-11-27 13:40 UTC by ishantmehtaharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-27 14:12 UTC, ishantmehtaharness commented
retrigger titlecheck

2022-11-28 13:52 UTC, GeorgiosP requested changes

2022-11-28 13:52 UTC, GeorgiosP commented on src/modules/75-cd/components/GitOpsFetchLinkedApps/GitOpsFetchLinkedApps.tsx
> +export class GitOpsFetchLinkedApps extends PipelineStep<StepElementConfig> {
Please convert this to a functional component, legacy components previous written as class components are ok, but we should avoid writing new components as classes.

2022-11-28 13:52 UTC, GeorgiosP commented on src/modules/75-cd/components/GitOpsFetchLinkedApps/GitOpsFetchLinkedApps.tsx
> +    // this._hasStepVariables = false
Should this be commented out?

2022-11-28 14:48 UTC, GeorgiosP commented on src/modules/75-cd/components/GitOpsFetchLinkedApps/GitOpsFetchLinkedApps.tsx
> +export class GitOpsFetchLinkedApps extends PipelineStep<StepElementConfig> {
on order to leverage function components with the pipelinestep factory we will need to refactor that to support function components which would be large change. 

let's leave this as is for now. but we should look to leverage composition over inheritance in the future, since javascript is a functional language.

2022-11-28 14:49 UTC, GeorgiosP approved these changes

2022-11-28 14:53 UTC, ishantmehtaharness commented on src/modules/75-cd/components/GitOpsFetchLinkedApps/GitOpsFetchLinkedApps.tsx
> +export class GitOpsFetchLinkedApps extends PipelineStep<StepElementConfig> {
Sure, as discussed, we will bring it up in UI-Council meeting

2022-11-28 14:55 UTC, ishantmehtaharness commented
These 2 tests are flaky? Failing on my PR continuously
src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AmazonS3Artifact/__tests__/AmazonS3.test.tsx
src/modules/85-cv/pages/slos/components/CVCreateSLOV2/__tests__/CVCreateSLOV2.test.tsx

2022-11-28 15:00 UTC, Tamaraius approved these changes

2022-11-28 15:38 UTC, merged