feat: [CDS-47109]: fixed images in connectivityMode step
harness/harness-core-ui pull request #12707
Opened 2022-11-29 13:15 UTC by Sagar-Rajput7

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-29 15:57 UTC, PratyushGar commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +      return {
Connectors.SPOT can be used here and for others

2022-11-29 16:14 UTC, Sagar-Rajput7 commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +      return {
all these constants exist in lower modules so, we can not import them here.

2022-11-29 16:41 UTC, ishantmehtaharness commented on src/modules/10-common/components/ConnectivityMode/ConnectorCardImages/awsDelegate.svg
> +<svg width="334" height="201" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M27.555 135.037a.5.5 0 0 1-.616-.348 432.71 432.71 0 0 0-.573-2.034c-.815
Do we want these svgs in uicore repo?

2022-11-30 06:14 UTC, ishantmehtaharness submitted a review, later dismissed

2022-12-07 00:14 UTC, cjlee01 submitted a review, later dismissed

2022-12-07 04:21 UTC, pankajsingh-harness requested changes

2022-12-07 04:21 UTC, pankajsingh-harness commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +  connectorType?: ConnectorInfoDTO['type']
make connectorType  required. Get connectorLabel here in this component instead of parent element in src/modules/35-connectors/components/CreateConnector/commonSteps/ConnectivityModeStep/ConnectivityModeStep.tsx. That will reduce number of props.

2022-12-07 04:21 UTC, pankajsingh-harness commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +const getDelegateCardInfoForConnectorType = (connectorType: ConnectorInfoDTO['type']): DelegateCardProps => {
Return only icon and iconPlatform name from this util and then use them in img tag. That will reduce repeated img tag for all the switch case.

eg: 
const {icon, iconPlatform} = getDelegateCardInfoForConnectorType(connectorType)

2022-12-07 04:21 UTC, pankajsingh-harness commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +      icon: connectorDelegateCard.iconPlatform,
Use iconPlatform here: `<img src={iconPlatform} width="100%" `/>` from the above.

2022-12-07 04:21 UTC, pankajsingh-harness commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +  const connectorDelegateCard = getDelegateCardInfoForConnectorType(connectorType)
const {icon, iconPlatform} = getDelegateCardInfoForConnectorType(connectorType)

2022-12-07 04:21 UTC, pankajsingh-harness commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +const getDelegateCardInfoForConnectorType = (connectorType: ConnectorInfoDTO['type']): DelegateCardProps => {
This will also make the code more type safe as now its just returning JSX element. So any jsx element can be returned. After update it will return IconName.

2022-12-07 04:21 UTC, pankajsingh-harness commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +      icon: connectorDelegateCard.icon,
Same as above

2022-12-07 04:21 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/CreateConnector/commonSteps/ConnectivityModeStep/ConnectivityModeStep.tsx
> +                    connectorLabel={ConnectorLabels[props.type as ConnectorInfoDTO['type']]}
Pass only connectorType from here and calculate connectorLabel using connectorType in the component itself. That will reduce number of props.

2022-12-07 08:16 UTC, Sagar-Rajput7 commented on src/modules/35-connectors/components/CreateConnector/commonSteps/ConnectivityModeStep/ConnectivityModeStep.tsx
> +                    connectorLabel={ConnectorLabels[props.type as ConnectorInfoDTO['type']]}
We can't as the label mapping is only present and 35-connector and and this function is at a 10-common so we can't import that here.

2022-12-07 08:17 UTC, Sagar-Rajput7 commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +  connectorType?: ConnectorInfoDTO['type']
We can't as the label mapping is only present and 35-connector and this function is at a 10-common so we can't import that here.

2022-12-07 08:21 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/CreateConnector/commonSteps/ConnectivityModeStep/ConnectivityModeStep.tsx
> +                    connectorLabel={ConnectorLabels[props.type as ConnectorInfoDTO['type']]}
Got it @Sagar-Rajput7

2022-12-07 11:15 UTC, Sagar-Rajput7 commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +  const connectorDelegateCard = getDelegateCardInfoForConnectorType(connectorType)
Done

2022-12-07 11:15 UTC, Sagar-Rajput7 commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +      icon: connectorDelegateCard.icon,
Done

2022-12-07 11:15 UTC, Sagar-Rajput7 commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +      icon: connectorDelegateCard.iconPlatform,
Done

2022-12-07 11:15 UTC, Sagar-Rajput7 commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +const getDelegateCardInfoForConnectorType = (connectorType: ConnectorInfoDTO['type']): DelegateCardProps => {
Done

2022-12-07 11:17 UTC, pankajsingh-harness commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +  icon: string
Use IconName instead of string for both these.

2022-12-07 11:19 UTC, Sagar-Rajput7 commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +  icon: string
I am passing an SVG here hence it as a string only

2022-12-07 11:22 UTC, pankajsingh-harness submitted a review, later dismissed

2022-12-07 11:32 UTC, ishantmehtaharness submitted a review, later dismissed

2022-12-07 11:43 UTC, avinashmadhwani02 requested changes

2022-12-07 11:43 UTC, avinashmadhwani02 commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +    case 'Azure':
ConnectivityMode is a common component and it shouldn't understand different connectors and delegates. We can take icons from Parent component instead

2022-12-07 13:44 UTC, ishantmehtaharness approved these changes

2022-12-07 13:44 UTC, Sagar-Rajput7 commented on src/modules/10-common/components/ConnectivityMode/ConnectivityMode.tsx
> +    case 'Azure':
Done

2022-12-07 13:45 UTC, merged