feat: [SRM-13119]: adding Query section for the Common Healthsource design
harness/harness-core-ui pull request #12721
Opened 2022-11-30 04:54 UTC by harshilbits

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-09 04:17 UTC, harshilbits commented
retrigger titlecheck

2022-12-09 09:53 UTC, deepeshk1204 commented on src/modules/85-cv/components/CommonMultiItemsSideNav/components/CommonSelectedAppsSideNav/components/GroupedSideNav/components/MetricMenu.tsx
> +    <>
do we need this fragment

2022-12-09 09:56 UTC, deepeshk1204 commented on src/modules/85-cv/components/CommonQueryViewer/CommonQueryViewer.tsx
> +export function QueryContent(props: QueryContentProps): JSX.Element {
Lets have one component per file

2022-12-09 10:01 UTC, deepesh-ui commented on src/modules/85-cv/components/CommonMultiItemsSideNav/components/CommonSelectedAppsSideNav/components/GroupedSideNav/components/MetricMenu.tsx
> +    <>
is this fragment needed

2022-12-09 10:02 UTC, deepesh-ui commented on src/modules/85-cv/components/CommonQueryViewer/CommonQueryViewer.tsx
> +export function QueryContent(props: QueryContentProps): JSX.Element {
Can we have one component per file

2022-12-09 10:07 UTC, deepesh-ui commented on src/modules/85-cv/components/CommonQueryViewer/CommonQueryViewer.tsx
> +            {onEditQuery && (
Edit button is common in both cases with template and without template , we should see if we can refactor this

2022-12-09 10:09 UTC, deepesh-ui commented on src/modules/85-cv/components/CommonQueryViewer/CommonQueryViewer.tsx
> +    queryLabel,
will we have different name for query ? if not we can remove queryLabel

2022-12-09 10:16 UTC, deepesh-ui commented on src/modules/85-cv/components/CommonQueryViewer/res.json
> +  {
do we need this file ?

2022-12-09 10:19 UTC, deepesh-ui commented on src/modules/85-cv/components/CommonQueryViewer/types.ts
> +  isAutoFetch?: boolean
will we have autofetch as per current design?

2022-12-09 10:21 UTC, deepesh-ui commented on src/modules/85-cv/components/CommonRecords/CommonRecords.module.scss
> +      left: calc(100% - 73px);
can we align these px values to --variables ?

2022-12-09 10:26 UTC, deepesh-ui commented on src/modules/85-cv/components/CommonRecords/CommonRecords.tsx
> +        {queryNotExecutedMessage || getString('cv.monitoringSources.commonHealthSource.submitQueryToSeeRecords')}
as per new design  we won't have different error messages

2022-12-09 10:28 UTC, deepesh-ui commented
@harshilbits   the design of common healthsource and this component are not aligned , are we planning to pick it later ?

<img width="822" alt="image" src="https://user-images.githubusercontent.com/81554936/206681624-421df6df-021b-49b0-912b-e8cce74e83bb.png">

2022-12-11 14:48 UTC, harshilbits commented on src/modules/85-cv/components/CommonQueryViewer/types.ts
> +  isAutoFetch?: boolean
removed

2022-12-11 14:50 UTC, harshilbits commented on src/modules/85-cv/components/CommonQueryViewer/CommonQueryViewer.tsx
> +    queryLabel,
removed

2022-12-11 14:50 UTC, harshilbits commented on src/modules/85-cv/components/CommonQueryViewer/CommonQueryViewer.tsx
> +export function QueryContent(props: QueryContentProps): JSX.Element {
moved to seperate file.

2022-12-11 14:51 UTC, harshilbits commented on src/modules/85-cv/components/CommonMultiItemsSideNav/components/CommonSelectedAppsSideNav/components/GroupedSideNav/components/MetricMenu.tsx
> +    <>
removed

2022-12-11 14:56 UTC, harshilbits commented on src/modules/85-cv/components/CommonRecords/CommonRecords.module.scss
> +      left: calc(100% - 73px);
removed

2022-12-11 14:56 UTC, harshilbits commented on src/modules/85-cv/components/CommonQueryViewer/res.json
> +  {
removed

2022-12-11 15:02 UTC, harshilbits commented on src/modules/85-cv/components/CommonQueryViewer/CommonQueryViewer.tsx
> +            {onEditQuery && (
not needed in new design. Removed it.

2022-12-11 15:24 UTC, harshilbits commented
> @harshilbits the design of common healthsource and this component are not aligned , are we planning to pick it later ?
> 
> <img alt="image" width="822" src="https://user-images.githubusercontent.com/81554936/206681624-421df6df-021b-49b0-912b-e8cce74e83bb.png">

Updated the design @deepesh-ui

2022-12-12 04:19 UTC, praneshg239 commented on src/modules/85-cv/components/CVSetupSourcesView/SetupSourceLayout/SetupSourceLayout.module.scss
> +      padding: 2px var(--spacing-none) 2px 2px !important;
Add css variable for `2px`

2022-12-12 04:20 UTC, praneshg239 commented on src/modules/85-cv/components/CommonMultiItemsSideNav/components/CommonSelectedAppsSideNav/CommonSelectedAppsSideNav.module.scss
> +    padding: 0px 10px 0px 14px;
use css variables

2022-12-12 04:21 UTC, praneshg239 commented on src/modules/85-cv/components/CommonMultiItemsSideNav/components/CommonSelectedAppsSideNav/CommonSelectedAppsSideNav.module.scss
> +    box-shadow: inset 0px -1px 0px #d9dae6;
use colours from ui-core css variables

2022-12-12 04:21 UTC, praneshg239 commented on src/modules/85-cv/components/CommonMultiItemsSideNav/components/CommonSelectedAppsSideNav/CommonSelectedAppsSideNav.module.scss
> +    box-shadow: inset 0px -1px 0px #d9dae6;
same here

2022-12-12 04:22 UTC, praneshg239 commented on src/modules/85-cv/components/CommonMultiItemsSideNav/components/CommonSelectedAppsSideNav/CommonSelectedAppsSideNav.module.scss
> +    color: #22222a;
use colour variables

2022-12-12 04:24 UTC, praneshg239 commented on src/modules/85-cv/components/CommonQueryViewer/components/CommonQueryViewerDialog/CommonQueryViewDialog.tsx
> +        <FormInput.TextArea name={MapGCPLogsToServiceFieldNames.QUERY} className={css.formQueryBox} />
do we need to import the field names from `MapGCPLogsToServiceFieldNames`? Shall we create our own for CHS?

2022-12-12 04:25 UTC, praneshg239 commented on src/modules/85-cv/components/CommonRecords/CommonRecords.module.scss
> +  border-radius: 8px;
every where please use css variables for color and number values

2022-12-12 04:28 UTC, praneshg239 commented on src/modules/85-cv/pages/health-source/HealthSourceDrawer/component/defineHealthSource/DefineHealthSource.tsx
> +  const isSumoLogicEnabled = useFeatureFlag(FeatureFlag.SRM_SUMO) || true
remove `true`

2022-12-12 04:29 UTC, praneshg239 commented on src/modules/85-cv/components/CommonQueryViewer/components/CommonQueryViewerDialog/CommonQueryViewDialog.tsx
> +        <FormInput.TextArea name={MapGCPLogsToServiceFieldNames.QUERY} className={css.formQueryBox} />
We are already defining it in `CommonHealthSource.constants.ts`, refer it from there

2022-12-12 04:39 UTC, praneshg239 requested changes
Please check

2022-12-12 05:03 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/HealthSourceDrawer/component/defineHealthSource/DefineHealthSource.tsx
> +  const isSumoLogicEnabled = useFeatureFlag(FeatureFlag.SRM_SUMO) || true
done.

2022-12-12 06:21 UTC, harshilbits commented on src/modules/85-cv/components/CVSetupSourcesView/SetupSourceLayout/SetupSourceLayout.module.scss
> +      padding: 2px var(--spacing-none) 2px 2px !important;
done.

2022-12-12 06:21 UTC, harshilbits commented on src/modules/85-cv/components/CommonMultiItemsSideNav/components/CommonSelectedAppsSideNav/CommonSelectedAppsSideNav.module.scss
> +    padding: 0px 10px 0px 14px;
done.

2022-12-12 06:22 UTC, harshilbits commented on src/modules/85-cv/components/CommonQueryViewer/components/CommonQueryViewerDialog/CommonQueryViewDialog.tsx
> +        <FormInput.TextArea name={MapGCPLogsToServiceFieldNames.QUERY} className={css.formQueryBox} />
done.

2022-12-12 06:24 UTC, harshilbits commented on src/modules/85-cv/components/CommonRecords/CommonRecords.module.scss
> +  border-radius: 8px;
This is old css came as part of copying old component of Records.

2022-12-12 07:33 UTC, praneshg239 submitted a review, later dismissed

2022-12-12 09:11 UTC, harshilbits commented
retrigger jest

2022-12-12 09:16 UTC, praneshg239 commented on src/modules/85-cv/components/CommonMultiItemsSideNav/CommonMultiItemsSideNav.utils.ts
> +      copyMetric.splice(index, 1)
this logic is repeated below, can this be combined?

2022-12-12 09:18 UTC, harshilbits commented on src/modules/85-cv/components/CommonMultiItemsSideNav/CommonMultiItemsSideNav.utils.ts
> +      copyMetric.splice(index, 1)
This is copied from old component . This will be refactored as part of Deepesh's side nav refactoring .

2022-12-12 09:19 UTC, praneshg239 commented on src/modules/85-cv/pages/health-source/HealthSourceDrawer/component/defineHealthSource/DefineHealthSource.utils.ts
> +    case Connectors.SUMOLOGIC:
we are having Sumologic metric and logs as separate health sources right? So do we need this still?

2022-12-12 09:20 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/HealthSourceDrawer/component/defineHealthSource/DefineHealthSource.utils.ts
> +    case Connectors.SUMOLOGIC:
That will be done ...when we are working on Define Health source screen. As of now , no changes are done on Define health source screen as it will impact the existing health sources.

2022-12-12 09:22 UTC, harshilbits commented on src/modules/85-cv/components/CommonMultiItemsSideNav/CommonMultiItemsSideNav.tsx
> +                setCreatedMetrics(oldMetrics => {
Again , this can get changed as per the sidenav refactoring by Deepesh to use functions instead of using state. If it is not changed..., can pick this up as part of next pr.

2022-12-12 09:23 UTC, harshilbits commented on src/modules/85-cv/components/CommonMultiItemsSideNav/components/CommonSelectedAppsSideNav/CommonSelectedAppsSideNav.module.scss
> +    box-shadow: inset 0px -1px 0px #d9dae6;
done.

2022-12-12 10:18 UTC, deepesh-ui approved these changes

2022-12-12 10:46 UTC, harshilbits commented
Coverage is failing for the old components which were copied from old codebase.

2022-12-12 11:03 UTC, merged