feat: [CDS-46526]: jenkins v2 trigger
harness/harness-core-ui pull request #12723
Opened 2022-11-30 05:58 UTC by satyam-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-04 06:03 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +        return {
This can be moved to some function and used. Same thing is used above as well.

2023-01-04 06:04 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +              connectorRefValue && getMultiTypeFromValue(connectorRefValue) === MultiTypeInputType.FIXED
This logic can be moved to a const

2023-01-04 06:05 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +                  ? 'Fetching jobs...'
This need to be moved to yaml.

2023-01-04 06:08 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +  const getInitialValues = (): JenkinsRegistrySpec => {
Does this function needed? We can remove this.

2023-01-04 06:08 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +    artifactPath: Yup.string()
Are we not showing any error message for this field? Is this field not required?

2023-01-04 06:10 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +  const primarySchema = Yup.object().shape(schemaObject)
This can be merged in with schemaObject.

2023-01-04 06:10 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +        formName="imagePath"
Add proper from name. As form name is used for tooltip ids.

2023-01-05 05:21 UTC, satyam-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +        formName="imagePath"
done

2023-01-05 05:21 UTC, satyam-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +  const primarySchema = Yup.object().shape(schemaObject)
done

2023-01-05 05:22 UTC, satyam-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +    artifactPath: Yup.string()
yes this is not required field

2023-01-05 05:22 UTC, satyam-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +  const getInitialValues = (): JenkinsRegistrySpec => {
done

2023-01-05 05:23 UTC, satyam-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +                  ? 'Fetching jobs...'
done

2023-01-05 05:23 UTC, satyam-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +              connectorRefValue && getMultiTypeFromValue(connectorRefValue) === MultiTypeInputType.FIXED
okay

2023-01-05 12:02 UTC, satyam-harness commented
retrigger jest

2023-01-05 12:50 UTC, pankajsingh-harness requested changes

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +  { label: 'Maven', value: RepositoryFormatTypes.Maven },
These label should be moved to yaml

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +  const connectorRefValue = defaultTo(getGenuineValue(prevStepData?.connectorId?.value), '')
Use import { getConnectorIdValue } from '@pipeline/components/ArtifactsSelection/ArtifactUtils' to get connector value. Also verify the flow by creating new connector as well.

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +  const feedValue = defaultTo(getGenuineValue(formik.values.feed || ''), '')
```suggestion
const feedValue = defaultTo(formik.values.feed, '')
```

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +  const projectValue = defaultTo(getGenuineValue(formik.values.project || ''), '')
```suggestion
 const projectValue = defaultTo(formik.values.project, '')
```

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +  const packageTypeValue = defaultTo(getGenuineValue(formik.values.packageType || ''), '')
```suggestion
   const packageTypeValue = defaultTo(formik.values.packageType, '')
```

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +      return [{ label: `Loading ${label}...`, value: `Loading ${label}...` }]
Add this label to yaml

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +      org: 'automation-cdc'
Is this hard coded value of org expected?

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +  const connectorRefValue = defaultTo(getGenuineValue(prevStepData?.connectorId?.value), '')
```suggestion
  const connectorRef = getConnectorIdValue(prevStepData)
```
After this updated update use of connectorRef

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +        (project: AzureDevopsProject) =>
`export interface AzureDevopsProject {
  id?: string
  name?: string
}`

Check with BE team why id and name are optional field value here? Ask them to make them required field in swagger if these are not optional in BE by adding notNull decorator in BE interface

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +        (feed: AzureArtifactsFeed) =>
Same as above

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +        (packageItem: AzureArtifactsPackage) =>
Same as above

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +              selectItems={getItems(fetchingProjects, 'Projects', projectItems)}
`Projects` should comes from yaml and not be hardcoded

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +                  items: getItems(fetchingProjects, 'Projects', projectItems),
Same as above

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +            selectItems={getItems(fetchingFeeds, 'Feeds', feedItems)}
Same as above

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +                items: getItems(fetchingFeeds, 'Feeds', feedItems),
Same as above

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +                    org: 'automation-cdc',
Is the hard coding values expected?

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +            selectItems={getItems(fetchingPackages, 'Packages', packageItems)}
Same as above

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +                items: getItems(fetchingPackages, 'Packages', packageItems),
Same as above

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +                    org: 'automation-cdc',
Same as above

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +  const connectorRefValue = getGenuineValue(prevStepData?.connectorId?.value || prevStepData?.identifier)
```suggestion
  const connectorRef = getConnectorIdValue(prevStepData)
```

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +  const getJobItems = (jobs: JobDetails[]): SelectWithSubmenuOption[] => {
`export interface JobDetails {
  folder?: boolean
  jobName?: string
  parameters?: JobParameter[]
  url?: string
}`

Same as above. Why all values are optional in interface?

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +          const parentJobName = formik.values.jobName?.split('/')[0]
This logic is repeated at multiple places. This can be extracted out as an util and used at all places.

2023-01-05 12:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +            label={'Job Name'}
This need to come form yaml not be hard coded here

2023-01-05 13:15 UTC, satyam-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +      org: 'automation-cdc'
yes

2023-01-05 13:17 UTC, satyam-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +        (project: AzureDevopsProject) =>
okay

2023-01-05 13:18 UTC, satyam-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzuerArtifacts.tsx
> +              selectItems={getItems(fetchingProjects, 'Projects', projectItems)}
okay

2023-01-05 14:48 UTC, pankajsingh-harness approved these changes

2023-01-05 15:16 UTC, satyam-harness commented
retrigger jest

2023-01-06 04:17 UTC, vikrant-harness approved these changes

2023-01-06 05:20 UTC, kapilkumawat86 approved these changes

2023-01-06 05:23 UTC, merged