fix: [PIE-6602]: Fixed - NextGen - Even-though the pipeline is executed through trigger, it marks as manual execution
harness/harness-core-ui pull request #12763
Opened 2022-12-01 13:45 UTC by pankajsingh-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-01 17:12 UTC, sribalij commented on src/modules/70-pipeline/utils/triggerUtils.ts
> +    case 'WEBHOOK':
Only WEBHOOK_CUSTOM should be a third party system right?
Other should be "Triggered by <webhook/artifact/manifest> trigger?

2022-12-02 05:38 UTC, pankajsingh-harness commented on src/modules/70-pipeline/utils/triggerUtils.ts
> +    case 'WEBHOOK':
Update the same

2022-12-02 05:42 UTC, pankajsingh-harness commented
retrigger eslint

2022-12-02 05:42 UTC, pankajsingh-harness commented
retrigger cypress-cv

2022-12-02 05:43 UTC, pankajsingh-harness commented
retrigger cypress-cd

2022-12-02 05:43 UTC, pankajsingh-harness commented
retrigger coverage

2022-12-02 05:51 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2022-12-02 06:15 UTC, udayvunnam commented on src/modules/70-pipeline/pages/execution-list/ExecutionListTable/ExecutionListCells.tsx
> +  }
Please move this block to the top.

CI trigger info has to be shown on the first level

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/20707504/205227140-c059a44e-1452-45ad-a8a3-6e3d014ea58e.png">

With the PR change it became 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20707504/205227507-ba10287b-e073-49df-a983-595248be8e15.png">

Earlier this was working since the CI info is present with 'WEBHOOK' OR 'MANUAL'

2022-12-02 06:16 UTC, udayvunnam commented on src/modules/70-pipeline/pages/execution-list/ExecutionListTable/ExecutionListCells.tsx
> +  return <TriggerInfoCellWithIconAndText iconName={manualIconName} text={manualGetText()} />
default the triggerType to 'MANUAL' on start of the function to avoid this additional code path

2022-12-02 06:17 UTC, udayvunnam commented on src/modules/70-pipeline/utils/triggerUtils.ts
> +      }
Artifact and manifest have different icons 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/20707504/205228026-73af4282-4d7c-4a5e-a863-f12f64a204af.png">https://www.figma.com/file/4HavSweFhZeVsJoaWwSrj8/Pipelines?node-id=3962%3A399339&t=fU2mRovH9YkUcTfS-1

2022-12-02 06:17 UTC, udayvunnam requested changes
Please check comments

2022-12-02 10:08 UTC, pankajsingh-harness commented on src/modules/70-pipeline/pages/execution-list/ExecutionListTable/ExecutionListCells.tsx
> +  return <TriggerInfoCellWithIconAndText iconName={manualIconName} text={manualGetText()} />
Done

2022-12-02 10:08 UTC, pankajsingh-harness commented on src/modules/70-pipeline/pages/execution-list/ExecutionListTable/ExecutionListCells.tsx
> +  }
Done

2022-12-02 10:27 UTC, AshwinBhatkal-Harness approved these changes

2022-12-02 10:30 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/utils/triggerUtils.ts
> +      }
@udayvunnam According to this UX, it looks like the icon is of the type of manifest triggering the pipeline. Is that what is expected? Or we need a generic one? Like for artifact

2022-12-02 10:32 UTC, pankajsingh-harness commented on src/modules/70-pipeline/utils/triggerUtils.ts
> +      }
@AshwinBhatkal-Harness We don't get the subType information in the api. So we cann't show subType specific icons as of now.

2022-12-02 10:43 UTC, udayvunnam approved these changes

2022-12-02 10:44 UTC, merged