fix: [PL-27875]: hide disconnected delegates until user clicks on “Use only delegates with the following tags”
harness/harness-core-ui pull request #12769
Opened 2022-12-01 15:17 UTC by douglasnfrazao

### Summary

Hide disconnected delegates until the user selects "Use only delegates with the following tags”

#### Screenshots

BEFORE:
<img width="1728" alt="Captura de Tela 2022-12-01 às 12 16 19" src="https://user-images.githubusercontent.com/8864960/205089782-31eea726-d0fb-4121-960e-4d6c1b04049b.png">

AFTER:
<img width="1728" alt="Captura de Tela 2022-12-01 às 12 13 46" src="https://user-images.githubusercontent.com/8864960/205089824-2fe32811-dfb5-4889-a87d-c37a2b639b7c.png">
<img width="1728" alt="Captura de Tela 2022-12-01 às 12 13 56" src="https://user-images.githubusercontent.com/8864960/205089849-b056ca36-1f37-43de-8214-a6bd3322acbf.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-01 15:23 UTC, douglasnfrazao commented
retrigger titlecheck

2022-12-01 18:56 UTC, tan-nhu approved these changes

2022-12-01 23:35 UTC, kapilkumawat86 approved these changes

2022-12-01 23:41 UTC, kapilkumawat86 requested changes
Please check again issues days hide delegate list to use selects the use delegate, @abhinavrastogi-harness

2022-12-13 05:48 UTC, abhinavrastogi-harness reviewed
1. Can we hide the header of the table as well when the table is not being shown
2. We should add tests for the case when the table is visible

2022-12-14 11:53 UTC, douglasnfrazao commented
@abhinavrastogi-harness the PR was updated removing the table header and creating tests

2022-12-20 09:40 UTC, abhinavrastogi-harness approved these changes

2022-12-20 09:41 UTC, kapilkumawat86 approved these changes

2023-01-05 18:37 UTC, douglasnfrazao commented
retrigger jest

2023-01-05 18:52 UTC, douglasnfrazao commented
retrigger coverage

2023-01-06 02:09 UTC, kapilkumawat86 approved these changes

2023-01-06 14:05 UTC, Kira-Jennings commented on src/modules/35-connectors/components/CreateConnector/commonSteps/DelegateSelectorStep/DelegateSelector/DelegateSelector.tsx
> +            <Text font={{ size: 'medium', weight: 'semi-bold' }} color={Color.BLACK}>
Could a font variation be used here?

2023-01-06 14:05 UTC, Kira-Jennings approved these changes

2023-01-06 14:08 UTC, merged