feat: Service for ASG-AMI
harness/harness-core-ui pull request #12777
Opened 2022-12-01 18:20 UTC by vikrant-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-02 19:30 UTC, vikrant-harness commented
retrigger titlecheck

2022-12-09 04:07 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/PipelineSteps/Common/GenericServiceSpec/GenericServiceSpec.module.scss
> +.nested-section-card-asg {
why are we making a asg change in generic service spec?

2022-12-09 04:08 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2022-12-09 06:26 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineSteps/Common/GenericServiceSpec/GenericServiceSpec.module.scss
> +.nested-section-card-asg {
Will rename this to be generic one

2022-12-10 07:18 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineSteps/Common/GenericServiceSpec/GenericServiceSpec.module.scss
> +.nested-section-card-asg {
Done

2022-12-10 07:47 UTC, YounixIO submitted a review, later dismissed

2022-12-10 11:34 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2022-12-11 18:03 UTC, radujomir requested changes

2022-12-11 18:03 UTC, radujomir commented on src/services/cd-ng-rq/hooks/useGetServiceAccessListQuery.ts
>      | 'Asg'
already provided

2022-12-11 20:24 UTC, vikrant-harness commented on src/services/cd-ng-rq/hooks/useGetServiceAccessListQuery.ts
>      | 'Asg'
Done

2022-12-11 20:33 UTC, AshwinBhatkal-Harness approved these changes

2022-12-11 20:58 UTC, radujomir approved these changes

2022-12-12 08:23 UTC, YounixIO approved these changes

2022-12-12 08:23 UTC, merged