Fix:[BT-2485]:Added the new jira labelling for NGUI
harness/harness-core-ui pull request #12792
Opened 2022-12-02 11:09 UTC by sumathippeswamy

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-02 12:31 UTC, devesh-harness requested changes

2022-12-02 12:31 UTC, devesh-harness commented on scripts/ci/release-branch-cut.sh
>  scripts/ci/release-branch-update-jiras.sh
Here we have to give new script name that we have created instead of previous one.

2022-12-02 12:31 UTC, devesh-harness commented on scripts/ci/jira-tagging-NGUI-QA.sh
> +KEYS=$(git log --pretty=oneline --format="%s" --abbrev-commit ${PREVIOUS_RELEASE_BRANCH}..${CURRENT_RELEASE_BRANCH} | grep -o -iE '('${PROJECTS}')' | sort | uniq)
form where we are getting the value for PROJECTS?

2022-12-02 12:36 UTC, devesh-harness requested changes

2022-12-02 12:36 UTC, devesh-harness commented on scripts/ci/jira-tagging-NGUI-QA.sh
> +## echo "$CURRENT_RELEASE_BRANCH"
Branch will have suffix origin, 
eg - "origin/release/0.${PREVIOUS_RELEASE_VERSION}.x"

2022-12-02 15:42 UTC, sumathippeswamy commented on scripts/ci/jira-tagging-NGUI-QA.sh
> +KEYS=$(git log --pretty=oneline --format="%s" --abbrev-commit ${PREVIOUS_RELEASE_BRANCH}..${CURRENT_RELEASE_BRANCH} | grep -o -iE '('${PROJECTS}')' | sort | uniq)
It is reading from read-jira-projects.sh

2022-12-08 14:37 UTC, nataraja2018 commented on scripts/ci/jira-tagging-NGUI-QA.sh
> +# Copyright 2022 Harness Inc. All rights reserved.
use small letters in scripts.

2023-02-27 00:02 UTC, closed without merging