feat: [SRM-13222]: Show exact error message on Stepper component
harness/harness-core-ui pull request #12806
Opened 2022-12-05 04:34 UTC by deepesh-ui

### Summary

#### Screenshots

<img width="958" alt="Screenshot 2022-12-05 at 9 56 56 AM" src="https://user-images.githubusercontent.com/81554936/205550349-e976c515-23c2-4e97-958b-b2c553339276.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-05 07:34 UTC, praneshg239 requested changes
Please check the comments

2022-12-05 12:46 UTC, deepesh-ui commented on src/modules/85-cv/components/CVStepper/components/Step/Step.tsx
> +      runValidationOnMount
done, on readability we can discuss

2022-12-05 13:56 UTC, deepesh-ui commented
retrigger jest

2022-12-05 13:57 UTC, deepesh-ui commented
retrigger coverage

2022-12-05 14:05 UTC, deepesh-ui commented
retrigger titlecheck

2022-12-05 14:11 UTC, deepesh-ui commented
retrigger titlecheck

2022-12-05 15:34 UTC, harshilbits commented on cypress/integration/85-cv/slos/CreateCompositeSLO.spec.ts
> +  it.only('should show all validations.', () => {
please remove only

2022-12-05 15:35 UTC, harshilbits commented on src/modules/85-cv/components/CVStepper/components/Step/Step.tsx
> +                {!step.errorMessage?.length ? (
null check for errorMessage

2022-12-05 15:41 UTC, harshilbits commented on src/modules/85-cv/pages/slos/CVSLODetailsPage/DetailsPanel/views/CompositeSLOConsumption/CompositeSLOConsumption.utils.tsx
> +      {durationAsString(slo?.errorBudgetBurned)}
destructure fields from slo

2022-12-05 16:39 UTC, deepesh-ui commented on src/modules/85-cv/components/ChangeTimeline/components/TimelineSlider/TimelineSlider.tsx
> +      if (startXPercentage && endXPercentage && !hideSlider) {
this was causing multiple renders got introduced as part of ticket SRM-11364

2022-12-05 16:42 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/CVSLODetailsPage/DetailsPanel/views/CompositeSLOConsumption/CompositeSLOConsumption.utils.tsx
> +      {durationAsString(slo?.errorBudgetBurned)}
being used only once , so didn't destructure

2022-12-05 17:12 UTC, deepesh-ui commented on src/modules/85-cv/components/CVStepper/components/Step/Step.tsx
> +                {!step.errorMessage?.length ? (
step will never be undefined , errorMessage might be undefined  i.e so !_undefined_?.length, which will not break

2022-12-05 17:12 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/components/CVCreateSLOV2/components/CreateCompositeSloForm/CreateCompositeSloForm.utils.ts
> +    errors: { periodLength, periodLengthType, periodType }
done

2022-12-06 01:45 UTC, deepesh-ui commented
retrigger jest

2022-12-06 03:54 UTC, praneshg239 commented on src/modules/85-cv/components/CVStepper/components/Step/Step.tsx
> +      runValidationOnMount
@deepesh-ui I am still seeing the same code, not seeing the change

2022-12-06 04:10 UTC, deepesh-ui commented on cypress/integration/85-cv/slos/CreateCompositeSLO.spec.ts
> +  it.only('should show all validations.', () => {
done

2022-12-06 04:12 UTC, praneshg239 approved these changes

2022-12-06 05:02 UTC, merged