fix: [CDS-46424]: jenkins artifact api validationa added
harness/harness-core-ui pull request #12840
Opened 2022-12-06 08:51 UTC by satyam-harness

### Summary

#### Screenshots
after
<img width="637" alt="image" src="https://user-images.githubusercontent.com/96036463/205864498-f9eaa5ad-b276-446e-a878-05d298c435d4.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/96036463/205864531-92cb3ba2-8d59-47e3-baa7-69bd921abaf0.png">

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-07 06:56 UTC, satyam-harness commented
retrigger typecheck

2022-12-07 06:57 UTC, satyam-harness commented
retrigger typecheck

2022-12-07 06:59 UTC, satyam-harness commented
retrigger jest

2022-12-07 06:59 UTC, satyam-harness commented
retrigger typecheck

2022-12-07 09:55 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +    jobName: encodeURIComponent(encodeURIComponent(jobNameValue?.label || ''))
Why encoding this two times?

2022-12-07 09:57 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +    jobName: encodeURIComponent(encodeURIComponent(jobNameValue?.label || ''))
Same As above

2022-12-07 09:58 UTC, rameshx requested changes

2022-12-07 09:58 UTC, rameshx commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +  })
This will create a new memoized function on every render. Use `useCallback`.

2022-12-07 09:58 UTC, rameshx commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +  })
You can also simply move the function outside the component.

2022-12-07 09:58 UTC, rameshx commented on src/modules/70-pipeline/strings/strings.en.yaml
> +    connectorForJobname: connector is required to fetch job name
The rest of the validation strings are capitalized.

2022-12-07 09:58 UTC, rameshx commented on src/modules/70-pipeline/strings/strings.en.yaml
> +    jobConnectorRequired: Jobname and connector are required to fetch
```suggestion
    jobConnectorRequired: Job name and connector are required to fetch
```

2022-12-07 09:59 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +    return (
Use src/modules/10-common/components/ItemRenderer/ItemRendererWithMenuItem.tsx for this.

2022-12-07 10:02 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +                  getMultiTypeFromValue(connectorRefValue) === MultiTypeInputType.RUNTIME ||
Replace this condition with the variable canFetchBuildsOrArtifacts declared above

2022-12-07 10:04 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +                    defaultErrorText={
This can be moved to a variable and used here.

2022-12-07 10:09 UTC, pankajsingh-harness reviewed
Added some comments

2022-12-09 07:15 UTC, satyam-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +    return (
addressed

2022-12-09 07:16 UTC, satyam-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +    jobName: encodeURIComponent(encodeURIComponent(jobNameValue?.label || ''))
this is required, once BE will make a fix for this then in UI we will make fix

2022-12-09 07:16 UTC, satyam-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +    jobName: encodeURIComponent(encodeURIComponent(jobNameValue?.label || ''))
this is required, once BE will make a fix for this then in UI we will make fix

2022-12-09 07:16 UTC, satyam-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +  })
done

2022-12-09 07:16 UTC, satyam-harness commented on src/modules/70-pipeline/strings/strings.en.yaml
> +    connectorForJobname: connector is required to fetch job name
done

2022-12-09 07:16 UTC, satyam-harness commented on src/modules/70-pipeline/strings/strings.en.yaml
> +    jobConnectorRequired: Jobname and connector are required to fetch
done

2022-12-09 07:16 UTC, satyam-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/JenkinsArtifact/JenkinsArtifact.tsx
> +                  getMultiTypeFromValue(connectorRefValue) === MultiTypeInputType.RUNTIME ||
done

2022-12-09 07:52 UTC, satyam-harness commented
retrigger jest

2022-12-09 07:54 UTC, pankajsingh-harness approved these changes

2022-12-09 09:29 UTC, PratyushGar approved these changes

2022-12-09 09:33 UTC, satyam-harness commented
ticket to add coverage -> https://harness.atlassian.net/browse/CDS-47510

2022-12-12 02:53 UTC, merged