fix: [CI-6350]: "run in debug mode" execution action for CI pipelines
harness/harness-core-ui pull request #12902
Opened 2022-12-08 08:02 UTC by shaurya-harness

### Summary

"run in debug mode" execution action for CI pipelines
#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-15 10:05 UTC, shaurya-harness commented
retrigger jest

2022-12-15 11:00 UTC, d1wilko requested changes
small suggestions - but looking good

2022-12-15 11:32 UTC, shaurya-harness commented on src/modules/70-pipeline/pages/execution-list/ExecutionList.tsx
> +  const [loadingonReRunInDebugMode, setLoadingOnReRunInDebugMode] = useState(false)
sure

2022-12-15 11:32 UTC, shaurya-harness commented on src/modules/70-pipeline/pages/execution-list/ExecutionListTable/ExecutionListCells.tsx
> +            pipelineIdentifier: defaultTo(pipelineIdentifier || data.pipelineIdentifier, ''),
yes

2022-12-15 11:32 UTC, shaurya-harness commented on src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionLandingPage.tsx
> +            executionIdentifier: defaultTo(response?.data?.planExecution?.uuid, ''),
yes

2022-12-15 12:08 UTC, d1wilko requested changes
sorry one last change

2022-12-15 12:08 UTC, d1wilko commented on src/modules/70-pipeline/pages/execution-list/ExecutionListTable/ExecutionListCells.tsx
> +    originalExecutionId: defaultTo(data.planExecutionId, ''),
sorry can we change these 2 to ?? aswell - sorry I missed them

2022-12-15 12:19 UTC, shaurya-harness commented
retrigger jest

2022-12-15 12:22 UTC, shaurya-harness commented on src/modules/70-pipeline/pages/execution-list/ExecutionListTable/ExecutionListCells.tsx
> +    originalExecutionId: defaultTo(data.planExecutionId, ''),
sure

2022-12-15 13:07 UTC, d1wilko approved these changes
LGTM :)

2022-12-19 08:13 UTC, bhavya-sinha approved these changes

2022-12-19 08:26 UTC, ishantmehtaharness approved these changes
Looks Good

2023-01-03 17:15 UTC, vardanbansal-harness approved these changes

2023-01-04 05:02 UTC, merged