feat: [SRM-13214]: rendering labels for change sources from the api call
harness/harness-core-ui pull request #12986
Opened 2022-12-13 08:23 UTC by karansaraswat19

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-13 09:15 UTC, karansaraswat19 commented
retrigger titlecheck

2022-12-13 09:17 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.utils.ts
> +  category: CategoryCountDetails | undefined,
use `optional` operator

2022-12-13 09:24 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.utils.ts
> +    percentage: category?.percentageChange && isNaN(category?.percentageChange) ? 0 : category?.percentageChange || 0
Can you please explain the logic in words here?

2022-12-13 09:25 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.utils.ts
> +    percentage: category?.percentageChange && isNaN(category?.percentageChange) ? 0 : category?.percentageChange || 0
NIT: 
also use `Number.isNaN` if you want to check the given value is `NaN`, `isNaN` will simply check whether the value is number or not.

2022-12-13 09:26 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.utils.ts
> +  categoryType: ChangeSourceDTO['category'] | 'Changes',
why `'Changes'` is not included in the backend response?

2022-12-13 11:18 UTC, deepesh-ui commented on src/modules/85-cv/pages/monitored-service/CVMonitoredService/__test__/CVMonitoredService.mock.ts
> +    Deployment: { count: 0, countInPrecedingWindow: 0, percentageChange: 0 },
should we remove countInPrecedingWindow ?

2022-12-13 12:12 UTC, karansaraswat19 commented on src/modules/85-cv/pages/monitored-service/CVMonitoredService/__test__/CVMonitoredService.mock.ts
> +    Deployment: { count: 0, countInPrecedingWindow: 0, percentageChange: 0 },
Right now backend is sending all three fields. Will remove it later.

2022-12-15 12:29 UTC, karansaraswat19 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.utils.ts
> +  categoryType: ChangeSourceDTO['category'] | 'Changes',
Because they are sending a map with key as a desired enum class, so they can't add into it

2022-12-15 12:30 UTC, karansaraswat19 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.types.ts
> +  id: string | undefined
tried this, it was showing some error

2022-12-16 02:38 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.types.ts
> +  id: string | undefined
We can connect and check this

2022-12-16 11:16 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.tsx
> +  const changeSummaryList = useMemo(() => calculateChangePercentage(getString, ffIntegration, data?.resource), [data?.resource])
🔥

2022-12-16 11:18 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.utils.ts
> +  if (featureFlag) {
name the feature flag with appropriate name, like `isMetricThresholdsEnabled`, `isCategoryEnabled` like that. So that it will be easily readable.

2022-12-16 11:18 UTC, praneshg239 approved these changes

2022-12-16 11:19 UTC, karansaraswat19 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.utils.ts
> +  if (featureFlag) {
ok, will take care of it from next time

2022-12-16 11:38 UTC, harshilbits commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.utils.ts
> +    const count = category?.count && isNaN(category?.count) ? 0 : category.count || 0
wrap these into small util functions to make it more readable.

For eg. `getCount`, `getPreviousCount`, `getPercentage`

2022-12-16 11:40 UTC, harshilbits commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.utils.ts
> +      const total = {
wrap this to a function `getTotal`

2022-12-19 11:48 UTC, deepesh-ui commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.types.ts
> +  id?: string
why have we made id optional ?

2022-12-19 13:14 UTC, karansaraswat19 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.types.ts
> +  id?: string
because backend is sending total also now, which can be undefined rn, will take care of it later

2022-12-19 13:48 UTC, karansaraswat19 commented
retrigger cypress-cd

2022-12-19 13:48 UTC, karansaraswat19 commented
retrigger jest

2022-12-19 16:08 UTC, deepesh-ui submitted a review, later dismissed

2022-12-20 01:46 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.tsx
> +    useFeatureFlag(FeatureFlag.SRM_FF_INTEGRATION) || (startTime === 0 && endTime === 0 ? true : false)
you can simply write 

```ts
const ffIntegration =
    useFeatureFlag(FeatureFlag.SRM_FF_INTEGRATION) || (startTime === 0 && endTime === 0)
```

2022-12-20 01:48 UTC, praneshg239 requested changes
Please check the comments

2022-12-20 05:12 UTC, karansaraswat19 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.tsx
> +    useFeatureFlag(FeatureFlag.SRM_FF_INTEGRATION) || (startTime === 0 && endTime === 0 ? true : false)
Yes, I will change that. This is done just for testing purposes. I will remove this logic after ff is removed

2022-12-20 07:14 UTC, praneshg239 commented on src/modules/10-common/featureFlags.ts
> +  SRM_FF_INTEGRATION = 'SRM_FF_INTEGRATION',
please check the feature flag name, it is more generic. Please use precise name

2022-12-20 07:15 UTC, praneshg239 commented on src/modules/10-common/featureFlags.ts
> +  SRM_FF_INTEGRATION = 'SRM_FF_INTEGRATION',
cc: @arpit-harness

2022-12-20 07:22 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.tsx
> +    useFeatureFlag(FeatureFlag.SRM_FF_INTEGRATION) || (startTime === 0 && endTime === 0 ? true : false)
mock feature flag hook like,

```ts
import * as FeatureFlag from '@common/hooks/useFeatureFlag'
.
.
.
beforeAll(() => {
   jest.spyOn(FeatureFlag, 'useFeatureFlag').mockReturnValue(true)
})

```

2022-12-20 07:55 UTC, praneshg239 approved these changes

2022-12-20 08:51 UTC, karansaraswat19 commented
retrigger coverage, cypress-pipeline

2022-12-20 09:02 UTC, karansaraswat19 commented
retrigger coverage

2022-12-20 09:26 UTC, deepesh-ui approved these changes

2022-12-20 09:35 UTC, merged