fix: env group scoped changes
harness/harness-core-ui pull request #12997
Opened 2022-12-13 11:54 UTC by vikrant-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-13 12:56 UTC, vikrant-harness commented
retrigger titlecheck

2022-12-20 03:53 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/FormMultiTypeEnvironmentGroupField/FormMultiTypeEnvironmentGroupField.module.scss
> +#tag {
Styling id on element?

2022-12-20 03:55 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/PipelineInputSetForm/EnvironmentsInputSetForm/MultiEnvironmentsInputSetForm.tsx
> +                            environmentGroupRef: get(deploymentStageInputSet, 'environmentGroup.envGroupRef'),
Why is this required?

2022-12-20 05:18 UTC, vikrant-harness commented on src/modules/70-pipeline/components/PipelineInputSetForm/EnvironmentsInputSetForm/MultiEnvironmentsInputSetForm.tsx
> +                            environmentGroupRef: get(deploymentStageInputSet, 'environmentGroup.envGroupRef'),
Because in RPF under envGroup we store environment Identifiers the envGroupRef contains the information about the scope

2022-12-20 08:03 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/FormMultiTypeEnvironmentGroupField/FormMultiTypeEnvironmentGroupField.module.scss
> +#tag {
?

2022-12-20 08:03 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/PipelineInputSetForm/EnvironmentsInputSetForm/MultiEnvironmentsInputSetForm.tsx
> +                            environmentGroupRef: get(deploymentStageInputSet, 'environmentGroup.envGroupRef'),
Can we just pass scope instead?

2022-12-20 08:05 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureEntityStep/DeployInfrastructureEntityInputStep.tsx
> +  let envToFetchInfraInputs = environmentIdentifier
Let's move this logic outside this component. The component should only worry about the environment identifier and not anything else

2022-12-20 08:05 UTC, AshwinBhatkal-Harness requested changes
Need changes in DeployInfrastructureEntityInputStep. Let's move this logic outside this component. The component should only worry about the environment identifier and not anything else

2022-12-20 09:39 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureEntityStep/DeployInfrastructureEntityInputStep.tsx
> +  let envToFetchInfraInputs = environmentIdentifier
Done

2022-12-20 09:39 UTC, vikrant-harness commented on src/modules/70-pipeline/components/FormMultiTypeEnvironmentGroupField/FormMultiTypeEnvironmentGroupField.module.scss
> +#tag {
It assigns a unique name we are good with this change

2022-12-20 10:34 UTC, AshwinBhatkal-Harness approved these changes

2022-12-20 10:54 UTC, YounixIO approved these changes

2022-12-20 11:22 UTC, Eric761 approved these changes

2022-12-20 11:48 UTC, merged