fix: [PIE-6990]: Added missing PipelineVariablesContextProvider for InputSetForm to support autosuggestion for expressions
harness/harness-core-ui pull request #13029
Opened 2022-12-14 11:42 UTC by pankajsingh-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-14 11:52 UTC, pankajsingh-harness commented
retrigger titlecheck

2022-12-16 09:58 UTC, satyam-harness approved these changes

2022-12-16 12:03 UTC, ishantmehtaharness approved these changes

2022-12-16 12:04 UTC, merged

2022-12-16 12:04 UTC, vkbansal-harness requested changes

2022-12-16 12:04 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/InputSetForm/InputSetForm.tsx
> +        pipeline={parse<Pipeline>(defaultTo(pipeline?.data?.yamlPipeline, ''))?.pipeline as PipelineInfoConfig}
This will parse yaml everytime. why not memoize it?

2022-12-16 12:06 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/InputSetForm/InputSetForm.tsx
> +        pipeline={parse<Pipeline>(defaultTo(pipeline?.data?.yamlPipeline, ''))?.pipeline as PipelineInfoConfig}
@vkbansal-harness I have merged this. Lets me Raise another PR with the change