feat: [PL-29846]: remove hash from NGUI code
harness/harness-core-ui pull request #13051
Opened 2022-12-15 13:56 UTC by swarajcheguri-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-04 11:35 UTC, abhinavrastogi-harness submitted a review, later dismissed

2023-01-04 11:42 UTC, mayankVermaHarness requested changes

2023-01-04 11:42 UTC, mayankVermaHarness commented on cypress/utils/windowLocation.ts
> +  return ''
Return `path` here instead of empty string

2023-01-04 11:43 UTC, mayankVermaHarness requested changes

2023-01-04 11:43 UTC, mayankVermaHarness commented on cypress/utils/windowLocation.ts
> +  return ''
```suggestion
  return path
```

2023-01-05 09:14 UTC, rameshx approved these changes

2023-01-05 09:15 UTC, abhinavrastogi-harness approved these changes

2023-01-05 10:07 UTC, mayankVermaHarness approved these changes

2023-01-05 10:14 UTC, merged