feat: [CDS-47746]: Added terragrunt provisioner
harness/harness-core-ui pull request #13096
Opened 2022-12-19 11:29 UTC by sonaligoyal-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-22 11:20 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/Common/Terragrunt/TerragruntHelper.ts
> +              : ''
using lodash set will help in reducing this code

2022-12-22 22:35 UTC, pankajsingh-harness requested changes

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/InputSteps/RemoteVarSection.tsx
> +  const { accountId, projectIdentifier, orgIdentifier } = useParams<{
Same as above

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/InputSteps/TgPlanConfigSection.tsx
> +  const { accountId, projectIdentifier, orgIdentifier } = useParams<{
Same as above

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/InputSteps/TgPlanConfigSection.tsx
> +  let connectorVal = get(formik.values, `${path}.${configPath}.store.spec.connectorRef`)
Same as other file comment on same type of code

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/InputSteps/TgPlanInputStep.tsx
> +  const { accountId, projectIdentifier, orgIdentifier } = useParams<{
Same as above

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/InputSteps/TgPlanVarFiles.tsx
> +      <Label style={{ color: Color.GREY_900, paddingBottom: 'var(--spacing-medium)' }}>
Label will be shown even if there is no varFiles. Is that expected? Or add length condition here

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/TerragruntPlan.tsx
> +  const { accountId, projectIdentifier, orgIdentifier } = useParams<{
Same as above

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/TerragruntPlan.tsx
> +  const { repoIdentifier, branch } = useQueryParams<GitQueryParams>()
```suggestion
  const { repoIdentifier, branch, sectionId } = useQueryParams<PipelineStudioQueryParams>()
```

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/TerragruntPlan.tsx
> +  const DIALOG_PROPS: IDialogProps = {
Same as other files

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/TerragruntPlan.tsx
> +export class TerragruntPlan extends PipelineStep<TGPlanFormData> {
We can split this file into 2. One having class definition other having componnet

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/VariableView/TgPlanConfigSection.tsx
> +            className={pipelineVariableCss.variablePaddingL4}
check class name. `className={pipelineVariableCss.variablePaddingL3}` use above

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/VariableView/TgPlanConfigSection.tsx
> +                  className={pipelineVariableCss.variablePaddingL4}
Same as above

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/VariableView/TgPlanConfigSection.tsx
> +            } else if (varFile?.varFile?.type === 'Remote') {
Replace this `Remote` hardcoding with const.

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/VariableView/TgPlanVariableView.tsx
> +            className={pipelineVariableCss.variablePaddingL4}
Class name mismatch

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntRollback/TerragruntRollback.tsx
> +const setInitialValues = (data: TGRollbackData): TGRollbackData => {
This is not setting any value. This can be renamed to `getInitialValues`

2022-12-22 22:35 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntRollback/TerragruntRollback.tsx
> +                <div className={cx(stepCss.formGroup, stepCss.lg)}>
Check for consistent className for size.

2022-12-26 12:29 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/Common/Terragrunt/EditView/TerragruntEditView.tsx
> +              // Handle on success
This is not required for our case but it is required prop so passed it as empty here.

2022-12-26 12:37 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/Common/Terragrunt/EditView/TerragruntEditView.tsx
> +              const valObj = cloneDeep(formik.values)
yes

2022-12-27 18:16 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/Common/Terragrunt/TerragruntInterface.ts
> +  targets?: any
this is done intentionally to support values in runtime and various other places

2022-12-27 18:17 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/Common/Terragrunt/TerragruntInterface.ts
> +  environmentVariables?: any
this is done intentionally to support values in runtime and various other places

2022-12-27 18:35 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/Common/Terragrunt/EditView/TerragruntEditView.tsx
> +              <div className={cx(stepCss.formGroup, stepCss.sm)}>
This is standard css for timeout which is being used across all the steps mostly.

2022-12-27 18:54 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/Common/Terragrunt/TerragruntHelper.ts
> +export const onSubmitTGPlanData = (values: any): TGPlanFormData => {
yes, it is already in todo for future enhancement

2022-12-27 18:57 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/TerragruntPlan.tsx
> +export class TerragruntPlan extends PipelineStep<TGPlanFormData> {
will pick it up with other enhancement

2022-12-27 19:06 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/Common/Terragrunt/EditView/TGVarFileList.tsx
> +          {varFile?.varFile?.type === getString('remote') && <Icon name="remote" className={css.iconPosition} />}
Here, I am using from strings.yaml as this component is rendering remote var file list and not remote backend config.
So it may mislead it here.

2022-12-27 19:27 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/Common/Terragrunt/VariableView/TerragruntVariableView.tsx
> +              className={pipelineVariableCss.variablePaddingL4}
verified and it is expected as per ux

2022-12-27 19:28 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/TerragruntPlan/InputSteps/TgPlanVarFiles.tsx
> +      <Label style={{ color: Color.GREY_900, paddingBottom: 'var(--spacing-medium)' }}>
this is expected behaviour

2022-12-28 06:03 UTC, pankajsingh-harness approved these changes

2022-12-28 06:20 UTC, Eric761 approved these changes

2022-12-28 06:46 UTC, YounixIO commented
Coverage to be updated in separate PR.

2022-12-28 06:47 UTC, merged