feat: [CI-6587]: Make Pipeline Studio compliant for Simplified YAML
harness/harness-core-ui pull request #13307
Opened 2023-01-05 08:52 UTC by vardanbansal-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-05 08:58 UTC, vardanbansal-harness commented on src/modules/10-common/components/YAMLBuilder/YamlBuilder.tsx
> -    //for optimization, restrict setting value to editor if previous and current json inputs are the same.
This optimization is not needed as it's causing the pipeline create modal to open up in a loop.

2023-01-13 01:38 UTC, vardanbansal-harness commented on src/modules/70-pipeline/components/PipelineStudio/SavePipelinePopover/SavePipelinePopover.tsx
> +    if (CI_YAML_VERSIONING) {
For simplified YAML, we have to rely on the identifier returned by backend in pipeline save api response as UI won't be sending an identifier in pipeline body as part of pipeline save request.

2023-01-13 06:24 UTC, vkbansal-harness requested changes

2023-01-13 06:24 UTC, vkbansal-harness commented on src/modules/10-common/components/YAMLBuilder/YamlBuilder.tsx
> +import { debounce, truncate, throttle, defaultTo, attempt, every, isEqualWith, isNil, get } from 'lodash-es'
Blocking this PR until code and product walk-trough is given to pipeline team

2023-01-19 23:55 UTC, closed without merging