feat: [CDS-49884]: TAS RollingDeployment and RollingRollback step
harness/harness-core-ui pull request #13311
Opened 2023-01-05 10:26 UTC by PratyushGar

### Summary

#### Screenshots
![image](https://user-images.githubusercontent.com/100121280/210757345-2b8e1bce-d777-462f-b1fc-6ddad9b205a0.png)
![image](https://user-images.githubusercontent.com/100121280/210757474-170a1c9a-034f-43cf-9ca4-3d5d55f723c7.png)
![image](https://user-images.githubusercontent.com/100121280/210757508-465d0c68-2677-49ea-8154-2d6911b24d4e.png)
![image](https://user-images.githubusercontent.com/100121280/210758437-36d4e463-e7e7-4c3b-843c-370c0e5e8a39.png)

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-09 07:21 UTC, vkbansal-harness requested changes

2023-01-09 07:21 UTC, vkbansal-harness commented on src/modules/75-cd/components/PipelineSteps/TasRollingDeploymentStep/TasRollingDeploymentStep.tsx
> +                  <ConfigureOptions
Please use inbuilt configuration options

2023-01-09 07:23 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/TasRollingDeploymentStep/__tests__/__snapshots__/TasRollingDeployment.test.tsx.snap
> +</div>
snapshot only has container divs

2023-01-09 07:23 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/TasRollingRollbackStep/__tests__/__snapshots__/TasRollingRollbackStep.test.tsx.snap
> +exports[`TASRollingRollbackStepStep tests Variables view renders fine 1`] = `<div />`;
Can you check these snapshots again?

2023-01-09 08:18 UTC, PratyushGar commented on src/modules/75-cd/components/PipelineSteps/TasRollingDeploymentStep/TasRollingDeploymentStep.tsx
> +                  <ConfigureOptions
Done 👍

2023-01-09 08:18 UTC, PratyushGar commented on src/modules/75-cd/components/PipelineSteps/TasRollingDeploymentStep/__tests__/__snapshots__/TasRollingDeployment.test.tsx.snap
> +</div>
Thanks, updated.

2023-01-09 08:19 UTC, PratyushGar commented on src/modules/75-cd/components/PipelineSteps/TasRollingRollbackStep/__tests__/__snapshots__/TasRollingRollbackStep.test.tsx.snap
> +exports[`TASRollingRollbackStepStep tests Variables view renders fine 1`] = `<div />`;
Yes, empty snapshot is desired, as rollback steps have no spec, so empty div is generated, as generic (name, identifier, timeout) field is handled globally.

2023-01-09 09:04 UTC, rameshx approved these changes

2023-01-09 09:23 UTC, vkbansal-harness approved these changes

2023-01-15 16:36 UTC, pankajsingh-harness approved these changes

2023-01-16 02:45 UTC, kapilkumawat86 approved these changes

2023-01-16 02:48 UTC, merged