chore:[CDS-49763]:pipeline-studio-banner
harness/harness-core-ui pull request #13326
Opened 2023-01-06 05:52 UTC by namanharness

### Summary

Adding Service and Environment v2 transition banner on pipeline and template studio
#### Screenshots

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/110456765/210938926-2f33c005-532c-48eb-b1bb-c5715497dc60.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-10 07:49 UTC, rameshx requested changes

2023-01-10 07:49 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/EndOfLifeBanner.tsx
> +  }, [])
This effect has missing dependencies. `showBanner` can be obtained from `showBannerSession` so this effect is not needed.

2023-01-10 07:49 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/EndOfLifeBanner.tsx
> +    if (showBannerSession == 'false') setShowBanner(false)
```suggestion
    if (showBannerSession === 'false') setShowBanner(false)
```

2023-01-10 07:49 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/EndOfLifeBanner.tsx
> +              January. We have an automated migration tool to support our users. Please contact
Add to strings

2023-01-10 09:52 UTC, rameshx submitted a review, later dismissed

2023-01-10 09:52 UTC, rameshx commented on src/modules/10-common/strings/strings.en.yaml
> +svcEnvV2Truncated: '  Harness has made a significant update to the services and environments in CD. Services and Environments now have definitions that are associated with the respective object and c
space at the beginning
```suggestion
svcEnvV2Truncated: 'Harness has made a significant update to the services and environments in CD. Services and Environments now have definitions that are associated with the respective object and can be managed ...'
```

2023-01-10 09:54 UTC, namanharness commented on src/modules/10-common/strings/strings.en.yaml
> +svcEnvV2Truncated: '  Harness has made a significant update to the services and environments in CD. Services and Environments now have definitions that are associated with the respective object and c
done

2023-01-10 09:55 UTC, rameshx submitted a review, later dismissed

2023-01-11 00:53 UTC, thisrohangupta commented
Yes this looks good @namanharness

2023-01-11 04:05 UTC, sonaligoyal-harness submitted a review, later dismissed

2023-01-11 06:03 UTC, sonaligoyal-harness submitted a review, later dismissed

2023-01-11 06:10 UTC, rameshx submitted a review, later dismissed

2023-01-11 08:48 UTC, samarth-sharma31 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/TemplateStudioSubHeader.tsx
> +    <Layout.Vertical>
Please attach a video of the behaviour when reconcile is also visible

2023-01-11 10:16 UTC, namanharness commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/TemplateStudioSubHeader.tsx
> +    <Layout.Vertical>
https://user-images.githubusercontent.com/110456765/211779463-ce7a9eef-d8c0-4f08-a913-b887aeeaa69d.mov

2023-01-11 12:59 UTC, AshwinBhatkal-Harness approved these changes

2023-01-11 13:13 UTC, rameshx approved these changes

2023-01-11 13:48 UTC, merged