feat: [SRM-13463]: Template fix for common assign component
harness/harness-core-ui pull request #13374
Opened 2023-01-10 03:53 UTC by deepesh-ui

### Summary

Fix for Template scenarios in Assign component

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-11 04:03 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/components/CustomMetricForm/components/CommonCustomMetricFormContainer/CommonCustomMetricFormContainerLayout/CommonCustomMetricFormContainer.tsx
> +        <AssignQuery
Please destructure properties from `values`

2023-01-11 04:06 UTC, harshilbits commented on src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/components/CustomMetricForm/components/Assign/components/RiskProfile/components/ServiceInstance/ServiceInstance.tsx
> +  const isServiceInstanceFixed = getMultiTypeFromValue(serviceInstance) === MultiTypeInputType.FIXED
Why we need to add separate code for serviceInstance. It should be controlled by formik directly once user the sets the value in the text field.

2023-01-11 04:45 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/components/CustomMetricForm/components/Assign/components/RiskProfile/components/ServiceInstance/ServiceInstance.tsx
> +  const isServiceInstanceFixed = getMultiTypeFromValue(serviceInstance) === MultiTypeInputType.FIXED
This is to update value to empty when user switches from fixed value to expression

2023-01-11 04:53 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/components/CustomMetricForm/components/CommonCustomMetricFormContainer/CommonCustomMetricFormContainerLayout/CommonCustomMetricFormContainer.tsx
> +        <AssignQuery
done

2023-01-11 05:07 UTC, praneshg239 commented
@deepesh-ui From the video, if we are switching the type of input which had a default value, to runtime or expression and switching back to fixed, it should take the default value again.

2023-01-11 05:11 UTC, praneshg239 commented on src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/components/CustomMetricForm/components/Assign/AssignQuery.tsx
> +export default function AssignQuery({
👏

2023-01-11 05:14 UTC, praneshg239 approved these changes

2023-01-11 05:15 UTC, praneshg239 commented on src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/components/CustomMetricForm/components/Assign/components/RiskProfile/components/ServiceInstance/ServiceInstance.tsx
> +                onChange={(_value, _valueType, multiType) => {
NIT: Why we are using `_` as prefix for the parameters here? We can still give precise name for them right?

2023-01-11 05:17 UTC, praneshg239 commented on src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/components/CustomMetricForm/components/Assign/components/RiskProfile/components/ServiceInstance/ServiceInstance.tsx
> +    const hasFixedValueInExpression =
instead doing this, we can simply set the value upon type change right?

2023-01-11 05:19 UTC, praneshg239 requested changes
Please check

2023-01-11 05:47 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/components/CustomMetricForm/components/Assign/components/RiskProfile/components/ServiceInstance/ServiceInstance.tsx
> +                onChange={(_value, _valueType, multiType) => {
was showing lint error

2023-01-12 03:56 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/components/CustomMetricForm/components/Assign/components/RiskProfile/components/ServiceInstance/ServiceInstance.tsx
> +    const hasFixedValueInExpression =
done

2023-01-12 09:50 UTC, harshilbits approved these changes

2023-01-12 09:52 UTC, merged