feat: [CDS-50191]: display UTC current time label on schedule panel f…
harness/harness-core-ui pull request #13393
Opened 2023-01-10 14:35 UTC by douglasnfrazao

…or cron triggers

### Summary

Adds a label to display the current UTC time on cron triggers so the users don't have to guess when inputting the fields.

#### Screenshots

<img width="1061" alt="Captura de Tela 2023-01-10 às 11 25 00" src="https://user-images.githubusercontent.com/8864960/211579648-6244d0f0-a05e-42d9-8131-ae6886d6e3e3.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-10 14:38 UTC, douglasnfrazao commented
retrigger titlecheck

2023-01-16 17:23 UTC, douglasnfrazao commented
retrigger jest

2023-01-17 13:46 UTC, douglasnfrazao commented
retrigger cypress-pipeline

2023-01-17 14:50 UTC, pankajsingh-harness requested changes
@douglasnfrazao We need add this feature `src/modules/72-triggers/components/Triggers/ScheduledTrigger/ScheduledTrigger.tsx` also

2023-01-17 14:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/views/SchedulePanel.tsx
> +          Current UTC Time: {currentDate.getUTCHours()}:{currentDate.getUTCMinutes()}
`Current UTC Time:` this should comes from yaml and not hard coded here.

2023-01-17 14:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/views/SchedulePanel.tsx
> +  fixedUTCTime?: boolean
```suggestion
  isFixedUTCTime?: boolean
```

2023-01-17 14:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/TriggersWizardPage.tsx
> +  fixedUTCTimeSchedulePanel?: boolean
```suggestion
  isFixedUTCTimeSchedulePanel?: boolean
```

2023-01-17 14:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/TriggersWizardPage.tsx
> +  const { fixedUTCTimeSchedulePanel } = props
How `fixedUTCTimeSchedulePanel` is passed to this component?

2023-01-17 14:50 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/views/SchedulePanel.tsx
> +  const currentDate = fixedUTCTime ? new Date('2023-01-10T10:00:00') : new Date()
Is this `new Date('2023-01-10T10:00:00')` hard coded value for date expected?

2023-01-17 18:32 UTC, douglasnfrazao commented on src/modules/72-triggers/pages/triggers/views/SchedulePanel.tsx
> +  const currentDate = fixedUTCTime ? new Date('2023-01-10T10:00:00') : new Date()
@pankajsingh-harness yes, that's to be able to test, because of the snapshot that keeps changing if not hard coded

2023-01-17 18:32 UTC, douglasnfrazao commented on src/modules/72-triggers/pages/triggers/TriggersWizardPage.tsx
> +  const { fixedUTCTimeSchedulePanel } = props
It's passed on the test for that page

2023-01-18 03:20 UTC, douglasnfrazao commented
retrigger jest

2023-01-18 03:21 UTC, douglasnfrazao commented
retrigger coverage

2023-01-30 23:52 UTC, tan-nhu approved these changes

2023-01-31 03:37 UTC, pankajsingh-harness submitted a review, later dismissed

2023-01-31 12:48 UTC, knagurski commented on src/modules/10-common/strings/strings.en.yaml
> +currentUTCTime: 'Current UTC Time:'
Any particular reason for extracting this here when it's only used in your new code?

2023-01-31 12:51 UTC, knagurski commented on src/modules/72-triggers/pages/triggers/__tests__/SchedulePanel.test.tsx
> +              <SchedulePanel {...defaultTriggerConfigDefaultProps} formikProps={formikProps} isFixedUTCTime={true} />
Nitpick, but you don't need to pass `true` for boolean props
```suggestion
              <SchedulePanel {...defaultTriggerConfigDefaultProps} formikProps={formikProps} isFixedUTCTime />
```

2023-01-31 12:58 UTC, knagurski commented on src/modules/72-triggers/components/steps/SchedulePanel/SchedulePanel.tsx
> +          {getString('triggers.schedulePanel.currentUTCTime')} {currentDate.getUTCHours()}:{currentDate.getUTCMinutes()}
Looks like the minutes will not be 2 digits of the 1st 10 mins of the hour, so you'll get things like `10:4` instead of `10:04`

2023-01-31 12:58 UTC, knagurski commented on src/modules/72-triggers/pages/triggers/__tests__/__snapshots__/SchedulePanel.test.tsx.snap
> +              0
Looks like the time is kinda broken

2023-01-31 13:00 UTC, knagurski commented on src/modules/72-triggers/pages/triggers/views/SchedulePanel.tsx
> +          {getString('triggers.schedulePanel.currentUTCTime')} {currentDate.getUTCHours()}:{currentDate.getUTCMinutes()}
Same here, it'll be `10:0` instead of `10:00`

2023-01-31 15:04 UTC, douglasnfrazao commented on src/modules/72-triggers/pages/triggers/__tests__/SchedulePanel.test.tsx
> +              <SchedulePanel {...defaultTriggerConfigDefaultProps} formikProps={formikProps} isFixedUTCTime={true} />
that's true

2023-01-31 15:23 UTC, douglasnfrazao commented on src/modules/72-triggers/pages/triggers/views/SchedulePanel.tsx
> +          {getString('triggers.schedulePanel.currentUTCTime')} {currentDate.getUTCHours()}:{currentDate.getUTCMinutes()}
that's true, fixed

2023-01-31 15:50 UTC, knagurski commented on src/modules/72-triggers/pages/triggers/__tests__/__snapshots__/TriggersWizardPage.test.tsx.snap
> +                        0
This still looks off, was it updated?

2023-01-31 15:52 UTC, knagurski commented on src/modules/72-triggers/pages/triggers/views/SchedulePanel.tsx
> +  isFixedUTCTime
Will make absolutely no difference to the code, but it's probably a good practice to default this to `false`, otherwise it could be a `boolean` or `undefined`. Total nitpick since the code will treat `false` and `undefined` the same.
```suggestion
  isFixedUTCTime = false
```

2023-01-31 19:58 UTC, douglasnfrazao commented
retrigger coverage

2023-01-31 20:09 UTC, merged