feat: [SRM-13484]: added no data available card for slo downtime component
harness/harness-core-ui pull request #13409
Opened 2023-01-11 12:30 UTC by karansaraswat19

### Summary

Made a new SLODowntime component with NoDataCard

#### Screenshots

<img width="1728" alt="Screenshot 2023-01-11 at 5 37 58 PM" src="https://user-images.githubusercontent.com/110607964/211806833-5699ef9a-9962-4e44-a34a-e3f224b77e87.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-12 03:13 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/SLODowntime/SLODowntime.tsx
> +          //   onClick={() => {
remove commented code

2023-01-12 03:13 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/SLODowntime/SLODowntime.tsx
> +        <Text flex style={{ textAlign: 'center', lineHeight: '24px' }}>
can we avoid using px specific value

2023-01-12 03:14 UTC, deepesh-ui requested changes
Please add this behind a feature flag

2023-01-12 13:48 UTC, karansaraswat19 commented
retrigger coverage

2023-01-13 04:40 UTC, deepesh-ui approved these changes

2023-01-16 11:36 UTC, karansaraswat19 commented
retrigger coverage

2023-01-16 11:36 UTC, karansaraswat19 commented
retrigger cypress-cd

2023-01-16 13:27 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/SLODowntimePage/SLODowntimePage.tsx
> +  const learnMoreLink = 'https://docs.harness.io/category/ko19u4brsv-howtos-service-reliability-management'
remove this link

2023-01-16 13:32 UTC, harshilbits commented on src/modules/85-cv/pages/slos/SLODowntimePage/SLODowntimePage.tsx
> +  const learnMoreLink = 'https://docs.harness.io/category/ko19u4brsv-howtos-service-reliability-management'
Please check how the harness docs link is used at other places .

2023-01-16 13:32 UTC, harshilbits approved these changes

2023-01-17 10:10 UTC, karansaraswat19 commented
retrigger coverage

2023-01-17 10:11 UTC, karansaraswat19 commented
retrigger cypress-cv

2023-01-17 10:11 UTC, karansaraswat19 commented
retrigger cypress-cd

2023-01-17 10:11 UTC, karansaraswat19 commented
retrigger cypress-cv

2023-01-17 10:31 UTC, karansaraswat19 commented
retrigger cypress-cd

2023-01-17 10:50 UTC, praneshg239 approved these changes

2023-01-17 10:52 UTC, praneshg239 requested changes

2023-01-17 10:52 UTC, praneshg239 commented on src/modules/85-cv/pages/slos/SLODowntimePage/SLODowntimePage.tsx
> +      <RedirectLink link={learnMoreLink} text={getString('common.learnMore')} />
`learnMoreLink` is empty string right? From line 27.

2023-01-17 10:53 UTC, karansaraswat19 commented on src/modules/85-cv/pages/slos/SLODowntimePage/SLODowntimePage.tsx
> +      <RedirectLink link={learnMoreLink} text={getString('common.learnMore')} />
yes that is the one

2023-01-17 10:54 UTC, praneshg239 commented on src/modules/85-cv/pages/slos/SLODowntimePage/SLODowntimePage.tsx
> +      <RedirectLink link={learnMoreLink} text={getString('common.learnMore')} />
Why we are giving empty link here?

2023-01-17 11:01 UTC, karansaraswat19 commented on src/modules/85-cv/pages/slos/SLODowntimePage/SLODowntimePage.tsx
> +      <RedirectLink link={learnMoreLink} text={getString('common.learnMore')} />
right now, I don't have any link to redirect to. So, it opens the same page rn. Will add the link later.

2023-01-17 11:02 UTC, praneshg239 commented on src/modules/85-cv/pages/slos/SLODowntimePage/SLODowntimePage.tsx
> +      <RedirectLink link={learnMoreLink} text={getString('common.learnMore')} />
ok

2023-01-17 11:02 UTC, praneshg239 approved these changes

2023-01-18 09:28 UTC, reetika04 commented on src/modules/85-cv/pages/slos/SLODowntimePage/SLODowntimePage.tsx
> +        <Text flex style={{ textAlign: 'center', lineHeight: 'var(--spacing-7)' }}>
Nit: Please avoid using inline styles.

2023-01-18 09:28 UTC, reetika04 commented on src/modules/85-cv/pages/slos/SLODowntimePage/SLODowntimePage.tsx
> +              resourceIdentifier: projectIdentifier
The resource identifier cannot be projectIdentifier, if this is create button the resourceIdentifier is not needed.

2023-01-18 09:28 UTC, reetika04 commented on src/modules/85-cv/pages/slos/SLODowntimePage/SLODowntimePage.tsx
> +  const RedirectLink = ({ link, text }: { link: string; text: string }): JSX.Element => (
You can use a Button and use Link variation.

2023-01-18 09:34 UTC, reetika04 commented on src/modules/85-cv/pages/slos/SLODowntimePage/SLODowntimePage.tsx
> +        <Text flex style={{ textAlign: 'center', lineHeight: 'var(--spacing-7)' }}>
You can use an existing variation

2023-01-18 10:41 UTC, avinashmadhwani02 commented on src/modules/85-cv/assets/noDowntimeData.svg
> +<svg width="320" height="200" viewBox="0 0 320 200" fill="none" xmlns="http://www.w3.org/2000/svg">
you can try optimising this svg using https://jakearchibald.github.io/svgomg/

2023-01-18 11:08 UTC, karansaraswat19 commented on src/modules/85-cv/assets/noDowntimeData.svg
> +<svg width="320" height="200" viewBox="0 0 320 200" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2023-01-19 04:45 UTC, karansaraswat19 commented
retrigger jest

2023-01-19 04:46 UTC, karansaraswat19 commented
retrigger coverage

2023-01-19 04:46 UTC, karansaraswat19 commented
retrigger cypress-cv

2023-01-19 05:01 UTC, reetika04 approved these changes

2023-01-19 05:23 UTC, praneshg239 approved these changes

2023-01-19 07:35 UTC, abhinavrastogi-harness commented on src/modules/10-common/RouteDefinitions.ts
> +      const path = `resources/slo-downtime`
shouldn't this path be prefixed with `/cv` or `/srm`?
since the name is `toCVSLODowntime`..

2023-01-19 07:35 UTC, abhinavrastogi-harness commented on src/modules/85-cv/assets/noDowntimeData.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="320" height="200" fill="none"><path fill="url(#a)" fill-opacity=".2" d="M279.853 141.997c.605 23.394-44.417 43.535-100.561 44.988-56.143 1.453-102.147-1
please run this image through an optimiser: https://jakearchibald.github.io/svgomg/

2023-01-19 07:35 UTC, abhinavrastogi-harness commented on src/modules/85-cv/strings/strings.en.yaml
> +  label: Downtime
the create button should not say "+ Downtime", right? seems like you are creating a downtime.
It should say "+ SLO" or "+ SLO Downtime" I think.

2023-01-19 08:19 UTC, karansaraswat19 commented on src/modules/85-cv/strings/strings.en.yaml
> +  label: Downtime
I did exactly as it was in the mocks.

2023-01-19 08:24 UTC, karansaraswat19 commented on src/modules/85-cv/assets/noDowntimeData.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="320" height="200" fill="none"><path fill="url(#a)" fill-opacity=".2" d="M279.853 141.997c.605 23.394-44.417 43.535-100.561 44.988-56.143 1.453-102.147-1
I did it, @avinashmadhwani02 suggested that in the above comment

2023-01-19 09:05 UTC, abhinavrastogi-harness approved these changes

2023-01-19 09:48 UTC, merged