feat: [CDS-47126]: force delete env
harness/harness-core-ui pull request #13540
Opened 2023-01-18 01:42 UTC by RajBaviskar

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-20 03:34 UTC, RajBaviskar commented
retrigger coverage

2023-01-20 06:49 UTC, RajBaviskar commented
retrigger jest

2023-01-20 06:50 UTC, RajBaviskar commented
retrigger sonar

2023-01-20 07:41 UTC, RajBaviskar commented
retrigger jest

2023-01-20 08:33 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentsList/__test__/EnvironmentsList.test.tsx
> +    jest.spyOn(FeatureFlag, 'useFeatureFlags').mockReturnValue({
We should not be doing this. TestWrapper has a prop that we can use to set feature flags

2023-01-20 08:35 UTC, AshwinBhatkal-Harness requested changes
Move the feature flag mock as testWrapper props

2023-01-20 08:54 UTC, RajBaviskar commented
> Move the feature flag mock as testWrapper props
changed.

2023-01-20 09:08 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2023-01-20 09:29 UTC, PratyushGar approved these changes

2023-01-21 00:07 UTC, RajBaviskar commented
retrigger cypress-cd

2023-01-23 04:12 UTC, vkbansal-harness approved these changes

2023-01-23 07:32 UTC, arkajyotiMukherjee approved these changes

2023-01-23 07:37 UTC, merged