feat:[CDS-40894]: add refresh button in service & overview dashboard
harness/harness-core-ui pull request #13636
Opened 2023-01-23 20:12 UTC by namanharness

### Summary

#### Screenshots

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/110456765/215415974-000406c1-7ef8-41db-a31c-8284785ea71c.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/110456765/215416002-da80bb3c-271e-47e4-ae0e-63c8afe0847b.png">

https://user-images.githubusercontent.com/110456765/215415575-ac66d140-4c77-4774-a133-6a3acce3f7fc.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-24 08:47 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/Services/ServiceInstancesWidget/ServiceInstancesWidget.tsx
> +  refrehServiceInstanceWidget?: boolean
```suggestion
  refreshServiceInstanceWidget?: boolean
```

2023-01-24 08:58 UTC, Sagar-Rajput7 requested changes
passing state as a prop and then using useEffect on that to trigger refetch doesn't seem to be the right way here, let's sync and discuss some better ways for these.

2023-01-24 09:12 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/Services/ServicesContent/ServicesContent.tsx
> +              setRefreshServiceDashboard(!refreshServiceDashboard)
```suggestion - The above can cause render issues
              setRefreshServiceDashboard(currentRefreshValue => !currentRefreshValue)
```

2023-01-24 09:14 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/pages/dashboard/CDDashboardPage.tsx
> +                  setRefreshOverview(!refreshOverview)
Same as previou comment

2023-01-24 09:15 UTC, AshwinBhatkal-Harness requested changes
Add disabled state to refresh button

2023-01-27 10:19 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/Services/ServicesContent/ServicesContent.tsx
> +  const getServicesGrowthTrendQueryParams: GetServicesGrowthTrendQueryParams = useMemo(
```suggestion
  const servicesGrowthTrendQueryParams: GetServicesGrowthTrendQueryParams = useMemo(
```

As it's not a function, but a const object carrying some values.

2023-01-27 10:19 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/Services/ServicesContent/ServicesContent.tsx
> +    () => ({
we don't need to use a memo here.

2023-01-27 10:20 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/Services/ServicesContent/ServicesContent.tsx
> +  const { data: getServicesGrowthTrendData, refetch: refetchGetServicesGrowthTrend } = useGetServicesGrowthTrend({
```suggestion
  const { data: servicesGrowthTrendData, refetch: refetchGetServicesGrowthTrend } = useGetServicesGrowthTrend({
```
same as above

2023-01-27 10:30 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/Services/ServicesContent/ServicesContent.tsx
> +            }}
```suggestion
            onClick={refreshServices}
```

2023-01-27 10:34 UTC, Sagar-Rajput7 commented on src/modules/75-cd/pages/dashboard/CDDashboardPage.tsx
> +                onClick={() => refreshCdDashboardPage()}
```suggestion
                onClick={refreshCdDashboardPage}
```

2023-01-27 10:36 UTC, Sagar-Rajput7 commented on src/modules/75-cd/pages/dashboard/CDDashboardPage.tsx
> +                title="Deployments Health"
use getString here

2023-01-27 11:04 UTC, Sagar-Rajput7 commented on src/modules/75-cd/pages/dashboard/CDDashboardPage.module.scss
> +}
```suggestion
.refreshButton {
    justify-content: flex-end;
    margin-right: 12px;
    margin-top: 4px;
}
```

2023-01-27 11:08 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/Services/ServicesContent/ServicesContent.tsx
> +    setTimeout(() => setRefreshButton(false), 2000)
rather than doing this we can rely on loading states of each API refetched.

2023-01-30 07:26 UTC, Sagar-Rajput7 approved these changes

2023-01-30 07:46 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/Services/ServicesContent/ServicesContent.module.scss
> +    margin: 20px;
Would margin top still be 0 with this line? If yes, move this above margin-top

2023-01-30 07:53 UTC, namanharness commented on src/modules/75-cd/components/Services/ServicesContent/ServicesContent.module.scss
> +    margin: 20px;
yes it does , making the change

2023-01-30 08:34 UTC, AshwinBhatkal-Harness approved these changes

2023-01-30 08:47 UTC, Sagar-Rajput7 approved these changes

2023-01-30 08:50 UTC, merged