fix: [CDS-50960]: added test coverage for artifactdigest
harness/harness-core-ui pull request #13691
Opened 2023-01-26 00:34 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-27 20:53 UTC, sahithikolichala commented
retrigger cypress-cd

2023-01-27 20:54 UTC, sahithikolichala commented
retrigger titlecheck

2023-01-27 21:00 UTC, sahithikolichala commented
retrigger titlecheck

2023-01-27 21:36 UTC, devinder-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +  return defaultTo(items, [])
why we need `defaultTo(items, [])` ? when we already have `items: SelectOption[]` which is `non-optional` ?

2023-01-27 21:36 UTC, devinder-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +  // const [digestItems, setDigestItems] = React.useState<any>(digestDefaultValue)
We can remove commented code

2023-01-27 21:36 UTC, devinder-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +      if (data && get(data, 'data', {}) && get(data, 'data.metadata', {}) && get(data, 'data.metadata.SHA', '')) {
can be written as `if(get(data, 'data.metadata.SHA', ''))` ?

2023-01-27 21:36 UTC, devinder-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +      if (data && get(data, 'data', {}) && get(data, 'data.metadata', {}) && get(data, 'data.metadata.SHAV2', '')) {
same as above

2023-01-27 21:47 UTC, sahithikolichala commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +      if (data && get(data, 'data', {}) && get(data, 'data.metadata', {}) && get(data, 'data.metadata.SHA', '')) {
ya will change to that

2023-01-28 06:35 UTC, satyam-harness approved these changes

2023-01-30 02:58 UTC, pankajsingh-harness requested changes

2023-01-30 02:58 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +    return [{ label: `Loading ${label}...`, value: `Loading ${label}...` }]
These values should not be hard coded here. These should comes from yaml.

2023-01-30 05:19 UTC, sahithikolichala commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +    return [{ label: `Loading ${label}...`, value: `Loading ${label}...` }]
ok will change this

2023-01-30 18:51 UTC, sahithikolichala commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +    return [{ label: `Loading ${label}...`, value: `Loading ${label}...` }]
fixed this https://github.com/harness/harness-core-ui/pull/13691/files#diff-6757bde8318ac524dfd8a0ce2a2a72ae4c419b0b68fe6364bfba5370743a758cR65

as the loading string is coming from https://github.com/harness/harness-core-ui/pull/13691/files#diff-6757bde8318ac524dfd8a0ce2a2a72ae4c419b0b68fe6364bfba5370743a758cR65

2023-01-30 21:59 UTC, sahithikolichala commented
retrigger jest

2023-01-30 22:00 UTC, sahithikolichala commented
retrigger cypress-cd

2023-01-31 03:39 UTC, pankajsingh-harness approved these changes

2023-01-31 05:52 UTC, chetanvekariya-harness approved these changes

2023-01-31 05:52 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/__tests/ArtifactDigestField.test.tsx
> +    expect(container).toMatchSnapshot()
We can avoid snapshot testing.

2023-01-31 05:52 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/__tests/ArtifactDigestField.test.tsx
> +    const loadingBucketsOption = await findByText(
variable name could be `loadingDigestOption`

2023-01-31 05:52 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/__tests/ArtifactDigestField.test.tsx
> +    const loadingBucketsOption = await findByText(
variable...

2023-01-31 05:53 UTC, sonaligoyal-harness approved these changes

2023-01-31 06:11 UTC, merged