fix: [CI-6862]: re-run in debug mode feature flag
harness/harness-core-ui pull request #13748
Opened 2023-01-30 07:35 UTC by shaurya-harness

### Summary

re-run in debug mode feature flag

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-30 08:36 UTC, vardanbansal-harness approved these changes

2023-01-30 09:30 UTC, d1wilko submitted a review, later dismissed
LGTM

2023-01-31 16:27 UTC, kapilkumawat86 approved these changes

2023-01-31 16:27 UTC, ishantmehtaharness submitted a review, later dismissed
Looks Good

2023-02-01 05:14 UTC, shaurya-harness commented
retrigger jest

2023-02-01 05:30 UTC, shaurya-harness commented
retrigger coverage

2023-02-10 15:55 UTC, d1wilko requested changes
1 small change :)

2023-02-10 15:55 UTC, d1wilko commented on src/modules/10-common/featureFlags.ts
> +  CI_REMOTE_DEBUG = 'CI_REMOTE_DEBUG'
this needs a comma at the end I think

2023-02-10 16:01 UTC, shaurya-harness commented on src/modules/10-common/featureFlags.ts
> +  CI_REMOTE_DEBUG = 'CI_REMOTE_DEBUG'
yes, updated

2023-02-10 16:03 UTC, merged

2023-02-10 16:04 UTC, d1wilko approved these changes
LGTM