feat: [CI-6657]: allow expression for codebase reponame
harness/harness-core-ui pull request #13818
Opened 2023-02-01 14:31 UTC by shaurya-harness

### Summary

allow expression for codebase reponame

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-02 05:28 UTC, shaurya-harness commented
retrigger jest

2023-02-02 10:57 UTC, d1wilko requested changes
one small question - otherwise looks good

2023-02-02 10:57 UTC, d1wilko commented on src/modules/70-pipeline/components/PipelineInputSetForm/CICodebaseInputSetForm.tsx
> +  }, [viewTypeMetadata?.isTemplateBuilder])
should this include `viewTypeMetadata?.isTemplateDetailDrawer`?

2023-02-03 04:49 UTC, shaurya-harness commented on src/modules/70-pipeline/components/PipelineInputSetForm/CICodebaseInputSetForm.tsx
> +  }, [viewTypeMetadata?.isTemplateBuilder])
yes we have been using the same for all codebase properties , check AllowableTypesForCodebaseProperties at line 628

2023-02-10 16:11 UTC, d1wilko requested changes

2023-02-10 16:11 UTC, d1wilko commented on src/modules/70-pipeline/components/PipelineInputSetForm/CICodebaseInputSetForm.tsx
> +  }, [viewTypeMetadata?.isTemplateBuilder])
Sorry I mean should the array at the end of the useMemo not also include `viewTypeMetadata?.isTemplateDetailDrawer`

2023-02-10 16:13 UTC, d1wilko approved these changes
LGTM :)

2023-02-10 16:13 UTC, shaurya-harness commented on src/modules/70-pipeline/components/PipelineInputSetForm/CICodebaseInputSetForm.tsx
> +  }, [viewTypeMetadata?.isTemplateBuilder])
right, updated

2023-02-10 17:03 UTC, shaurya-harness commented
retrigger jest

2023-02-10 17:11 UTC, merged