fix: [CDS-51785]: made api call as optional conditionally
harness/harness-core-ui pull request #13829
Opened 2023-02-01 21:36 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-03 23:35 UTC, sahithikolichala commented
retrigger titlecheck

2023-02-07 17:18 UTC, sahithikolichala commented
retrigger coverage

2023-02-07 17:19 UTC, sahithikolichala commented
retrigger jest

2023-02-07 17:37 UTC, sahithikolichala commented
retrigger jest

2023-02-07 17:38 UTC, sahithikolichala commented
retrigger jest

2023-02-08 05:07 UTC, vkbansal-harness requested changes

2023-02-08 05:07 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus2Artifact/Nexus2Artifact.tsx
> +            /* istanbul ignore next */
do not put `/* istanbul ignore next */` just to increase the coverage. It should be used only with variable assignments and default values

2023-02-08 05:24 UTC, sahithikolichala commented
retrigger jest

2023-02-08 05:36 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus2Artifact/Nexus2Artifact.tsx
> +    /* istanbul ignore next */
do not put /* istanbul ignore next */ just to increase the coverage. It should be used only with variable assignments and default values

2023-02-08 05:36 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus2Artifact/Nexus2Artifact.tsx
> +    /* istanbul ignore next */
do not put /* istanbul ignore next */ just to increase the coverage. It should be used only with variable assignments and default values

2023-02-08 05:36 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus2Artifact/Nexus2Artifact.tsx
> +    /* istanbul ignore next */
do not put /* istanbul ignore next */ just to increase the coverage. It should be used only with variable assignments and default values

2023-02-08 05:36 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus2Artifact/Nexus2Artifact.tsx
> +    /* istanbul ignore next */
do not put /* istanbul ignore next */ just to increase the coverage. It should be used only with variable assignments and default values

2023-02-08 05:36 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus2Artifact/Nexus2Artifact.tsx
> +                    /* istanbul ignore next */
do not put /* istanbul ignore next */ just to increase the coverage. It should be used only with variable assignments and default values

2023-02-08 05:37 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus2Artifact/Nexus2Artifact.tsx
> +                    } /* istanbul ignore else */ else {
do not put /* istanbul ignore else */ just to increase the coverage. It should be used only with single `if` statements and not in `if...else`

2023-02-08 05:37 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus2Artifact/Nexus2Artifact.tsx
> +    } /* istanbul ignore else */ else if (Array.isArray(data?.data?.buildDetailsList)) {
do not put /* istanbul ignore else */ just to increase the coverage. It should be used only with single `if` statements and not in `if...else`

2023-02-08 05:38 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus2Artifact/Nexus2Artifact.tsx
> +                        /* istanbul ignore next */
do not put /* istanbul ignore next */ just to increase the coverage. It should be used only with variable assignments and default values

2023-02-08 05:58 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactInterface.ts
> +  canFetchTags?: any
why any?

2023-02-08 05:58 UTC, vkbansal-harness approved these changes

2023-02-08 06:19 UTC, satyam-harness approved these changes

2023-02-08 06:19 UTC, merged