feat: [PIE-6227]: add logs settings in preference store and condiiton…
harness/harness-core-ui pull request #13885
Opened 2023-02-03 12:37 UTC by vikrant-harness

…ally show the log data

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-06 07:52 UTC, vkbansal-harness requested changes

2023-02-06 07:52 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +  function LogSettingsPreferenceComp(): JSX.Element {
Move this component outside

2023-02-06 07:52 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +  }, [])
```suggestion
  }, [logsInfoViewSettings, logsDateTimeViewSettings])
```

2023-02-06 07:52 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +    logsInfoViewSettings ? Boolean(logsInfoViewSettings === 'true') : true
```suggestion
    logsInfoViewSettings ? logsInfoViewSettings === 'true' : true
```

2023-02-06 07:52 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +    logsDateTimeViewSettings ? Boolean(logsDateTimeViewSettings === 'true') : true
```suggestion
    logsDateTimeViewSettings ? logsDateTimeViewSettings === 'true' : true
```

2023-02-06 07:52 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +  }, [])
Also handle else conditions

2023-02-06 07:56 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +  }, [])
We just need this on mount of the component and this for the default true case if we don't have it in preference store then it just adds base true to the store

2023-02-06 08:04 UTC, satyam-harness approved these changes

2023-02-06 08:10 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +  function LogSettingsPreferenceComp(): JSX.Element {
done

2023-02-06 08:10 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +    logsInfoViewSettings ? Boolean(logsInfoViewSettings === 'true') : true
done

2023-02-06 08:10 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +    logsDateTimeViewSettings ? Boolean(logsDateTimeViewSettings === 'true') : true
done

2023-02-06 08:46 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +    <Container padding={{ bottom: 'xxlarge' }}>
Why do we need container and layout both here?

2023-02-06 08:50 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +    logsInfoViewSettings ? logsInfoViewSettings === 'true' : true
Is it saved as 'true' in preference store? Can we change it from our end?

2023-02-06 08:51 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +  }, [])
This must be throwing an es lint warning. Let's add the es lint comment for this

2023-02-06 08:53 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +          getString={getString}
Let's remove getString from props

2023-02-06 08:55 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +    logsInfoViewSettings ? logsInfoViewSettings === 'true' : true
If we set the preference to true instead of 'true', this can be simplified with defaultTo

2023-02-06 08:55 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/components/MultiLogLine/MultiLogLine.tsx
> +  const showLogInfo = logsInfoViewSettings === 'true'
Why is this condition different from the one in LogsContent?

2023-02-06 08:58 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/components/MultiLogLine/MultiLogLine.tsx
> +        } as any
as React.css properties

2023-02-06 08:59 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/components/MultiLogLine/MultiLogLine.tsx
> +          gridTemplateColumns: `${Math.max(defaultTo(limit.toString().length, 3), 3)}ch${showLogInfo ? ' 5ch' : ''}${
We can generate 3 classes and then use them with 'classnames' instead of this. This looks confusing and can be very sensitive to update

2023-02-06 09:00 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +function LogSettingsPreferenceComp(props: LogSettingsPreferenceProps): JSX.Element {
```suggestion
function LogSettingsPreference(props: LogSettingsPreferenceProps): JSX.Element {
```

2023-02-06 09:27 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/components/MultiLogLine/MultiLogLine.tsx
> +  const showLogInfo = logsInfoViewSettings === 'true'
Perference store only has the ability to save strings not boolean

2023-02-06 09:28 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +    logsInfoViewSettings ? logsInfoViewSettings === 'true' : true
Perference store has string support

2023-02-06 09:43 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +    <Container padding={{ bottom: 'xxlarge' }}>
Removed

2023-02-06 09:43 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +          getString={getString}
Done

2023-02-06 09:44 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/components/MultiLogLine/MultiLogLine.tsx
> +        } as any
Done

2023-02-06 09:44 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +function LogSettingsPreferenceComp(props: LogSettingsPreferenceProps): JSX.Element {
Done

2023-02-06 09:44 UTC, vkbansal-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +  }, [])
We also need to support update on change of the values.

2023-02-06 09:54 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/components/MultiLogLine/MultiLogLine.tsx
> +          gridTemplateColumns: `${Math.max(defaultTo(limit.toString().length, 3), 3)}ch${showLogInfo ? ' 5ch' : ''}${
We have to generate 4 classNames that would end up duplicating the code a lot or pass CSS variables that would do the same handling like here

2023-02-06 10:06 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +  }, [])
This useEffect is only setting the preference store for the first time it is not defined after this all the changes will be handled by the onSubmit of the modal

2023-02-06 10:24 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2023-02-06 12:00 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/useLogsSettings.tsx
> +        setShowLogLevel(logsInfoViewSettings === 'true')
Shouldn't this be the similar condition as line 23?

2023-02-06 12:01 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/useLogsSettings.tsx
> +export function useLogSettingsPreference(): LogsSettingsReturn {
The file name and hook name are different

2023-02-06 12:01 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/LogsContent/useLogsSettings.tsx
> +  function LogsSettingsPreferenceComp(): JSX.Element {
This can be moved out

2023-02-06 13:00 UTC, AshwinBhatkal-Harness approved these changes

2023-02-06 13:00 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/useLogsSettings.tsx
> +        setShowLogLevel(logsInfoViewSettings === 'true')
Done

2023-02-06 13:13 UTC, vkbansal-harness approved these changes

2023-02-06 13:42 UTC, vikrant-harness commented on src/modules/70-pipeline/components/LogsContent/LogsContent.tsx
> +  }, [])
Fixed this

2023-02-07 04:09 UTC, vkbansal-harness approved these changes

2023-02-07 04:17 UTC, AshwinBhatkal-Harness approved these changes

2023-02-07 06:03 UTC, merged