feat: [CDS-49756]: Added test cases for Service Detail page - Env Part
harness/harness-core-ui pull request #13933
Opened 2023-02-06 19:25 UTC by Sagar-Rajput7

### Summary

#### Screenshots

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/98325173/217065915-bf8c7c7a-489d-4b23-b36b-71d32cac4797.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-06 19:45 UTC, vikrant-harness commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsSummaryV2/__test__/ServiceDetailsMocks.tsx
> +              host: 'ec2-54-87-31-191.compute-1.amazonaws.com',
All these seems to be valid credentials ?  We shouldn't expose them if they are valid ?

2023-02-06 19:46 UTC, litvinovstas approved these changes

2023-02-06 19:49 UTC, litvinovstas requested changes
please modify mock data from valid to invalid

2023-02-06 20:08 UTC, vikrant-harness approved these changes

2023-02-07 00:44 UTC, kapilkumawat86 approved these changes

2023-02-07 05:16 UTC, merged