feat: [IDP-155]: add IDP rbac entities to NG
harness/harness-core-ui pull request #13944
Opened 2023-02-07 06:55 UTC by sarthakkasat

### Summary
Adding IDP related RBAC permissions and resourceTypes to NG
Relevant docs [here](https://harness.atlassian.net/wiki/spaces/IDP/pages/21282816244/Access+Control+Tech+Spec+WIP)

### Jira Links
[IDP-155](https://harness.atlassian.net/browse/IDP-155)

#### Screenshots
<img width="1792" alt="Screenshot 2023-02-07 at 11 01 09 AM" src="https://user-images.githubusercontent.com/109350689/217170029-12dfa34a-9c13-4384-a6d8-75663f5c5b7f.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-07 08:31 UTC, bhavya-sinha requested changes

2023-02-07 08:31 UTC, bhavya-sinha commented on src/modules/75-idp/RouteDestinations.tsx
> +import { ResourceType, PermissionIdentifier } from 'microfrontends'
Import is incorrect.

2023-02-07 09:03 UTC, abhinavrastogi-harness commented on src/modules/20-rbac/interfaces/ResourceType.ts
> +  IDP_POLICY = 'IDP_POLICY'
why is the resource called `IDP_POLICY`? Is this related to the governance module?

2023-02-07 10:18 UTC, sarthakkasat commented on src/modules/20-rbac/interfaces/ResourceType.ts
> +  IDP_POLICY = 'IDP_POLICY'
It is not related to governance model, will change the name to IDP_ADMIN

2023-02-09 09:41 UTC, bhavya-sinha approved these changes

2023-02-09 11:06 UTC, jenil-harness approved these changes

2023-02-15 08:56 UTC, sarthakkasat commented
retrigger jest

2023-02-15 09:51 UTC, sarthakkasat commented
retrigger cypress-cv

2023-02-24 18:54 UTC, sarthakkasat commented
retrigger jest

2023-02-27 03:14 UTC, abhinavrastogi-harness approved these changes

2023-02-27 09:03 UTC, bhavya-sinha approved these changes

2023-02-27 09:22 UTC, merged