fix: [PIE-8173]: AMI Artifact version not showing data in run pipeline modal
harness/harness-core-ui pull request #13988
Opened 2023-02-08 13:20 UTC by pankajsingh-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-16 17:38 UTC, sahithikolichala approved these changes

2023-02-16 22:04 UTC, sahithikolichala commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AmazonMachineImage/AmazonMachineImage.tsx
> +    if (!fetchingRegions && regionData?.resource) {
please add the condition on regions back . Otherwise this would go into infinite loop
when regions are mocked

2023-02-16 22:06 UTC, sahithikolichala requested changes
Please add condition for regions back on useeffect,without that it would run into infinite loop

2023-02-20 02:22 UTC, pankajsingh-harness commented
retrigger coverage

2023-02-20 07:26 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AmazonMachineImage/__test__/AmazonMachineImage.test.tsx
> +  ...jest.requireActual('services/cd-ng'),
Should this not be 'services/cd-ng-rq'?

2023-02-20 07:33 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AmazonMachineImage/AmazonMachineImage.tsx
> +    if (!fetchingRegions && regionData?.resource) {
@sahithikolichala all the tests are passing and this is not going in infinite loop also. This should not go in infinite loop if we add proper dependency to useEffect.

2023-02-20 07:33 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AmazonMachineImage/__test__/AmazonMachineImage.test.tsx
> +  ...jest.requireActual('services/cd-ng'),
Done

2023-02-20 08:34 UTC, litvinovstas approved these changes

2023-02-20 10:10 UTC, merged