feat: [CI-6562]: run pipeline modal for v1 pipeline repository changes
harness/harness-core-ui pull request #13987
Opened 2023-02-08 12:30 UTC by shaurya-harness

### Summary

As part of Harness YAML simplification process that's currently going on, we've added new run pipeline modal for V1 Pipeline, pertaining to follow high level changes:

1. This PR includes changes to open new run pipeline modal with just codebase related changes
2. Repo is a first class element in new simplified yaml and values will be fetched from new inputs api
3.. All these changes are being controlled by a feature flag CI_YAML_VERSIONING.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-08 21:03 UTC, vardanbansal-harness commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/CICodebaseInputSetFormV1.tsx
> +    formik?.setFieldValue(codeBaseTypePath, newType)
@shaurya-harness the version of formik we're currently using does not guarantee batching above two `setFieldValue` calls. Instead use `setValues` from formik. Docs with more details https://docs.google.com/document/d/11QYKW7lDtVQ_gUUQvCeEB6v3CsZz5g_yHidcspgdXs0/edit#heading=h.5hyrjy2fma40

2023-02-08 21:05 UTC, vardanbansal-harness requested changes
Pls take care of the comment related to formik below.

2023-02-23 04:50 UTC, shaurya-harness commented
retrigger jest

2023-02-23 11:13 UTC, d1wilko requested changes
Coming together nicely - added some things to consider

2023-02-23 11:13 UTC, d1wilko commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/RunPipelineFormV1.tsx
> +  useEffect(() => {
move higher in file :)

2023-02-23 11:13 UTC, d1wilko commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/useRunPipelineModalV1.tsx
> +    // }
can we get rid of this?

2023-02-24 05:15 UTC, vardanbansal-harness commented on src/modules/70-pipeline/pages/execution-list/ExecutionListTable/ExecutionListCells.tsx
> +            ? CI_YAML_VERSIONING && module?.valueOf().toLowerCase() === moduleToModuleNameMapping.ci.toLowerCase()
Have added this util but might take time to get it merged. We can clean this up after that happens.

2023-02-24 05:16 UTC, vardanbansal-harness commented on src/modules/70-pipeline/v1/components/PipelineCanvasV1/PipelineCanvasV1.tsx
> +  // }
+1

2023-02-24 05:49 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/PipelineCanvasV1/PipelineCanvasV1.tsx
> +  // }
@vardanbansal-harness  this is your code, will delete this but we might need to add it back when run modal supports selection of old input sets

2023-02-24 06:32 UTC, vardanbansal-harness commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/CICodebaseInputSetFormV1.tsx
> +      !isUndefined(codebaseConnector)
+1

2023-02-24 06:34 UTC, vardanbansal-harness commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/CICodebaseInputSetFormV1.tsx
> +    if (!loadingConnectorDetails && !isUndefined(connectorDetails)) {
or just `connectorDetails` with it's truthy value should be good enough

2023-02-24 06:35 UTC, vardanbansal-harness commented on src/modules/70-pipeline/components/ExecutionActions/ExecutionActions.tsx
> +  onReRunInDebugMode?: any
avoid any, it becomes difficult later on to remove them or make them adhere to a specific type

2023-02-24 10:16 UTC, shaurya-harness commented on src/modules/70-pipeline/components/ExecutionActions/ExecutionActions.tsx
> +    CI_YAML_VERSIONING && module?.valueOf().toLowerCase() === moduleToModuleNameMapping.ci.toLowerCase()
will cleanup later, after Vardan's changes

2023-02-24 10:18 UTC, shaurya-harness commented on src/modules/70-pipeline/components/ExecutionActions/ExecutionActions.tsx
> +  onReRunInDebugMode?: any
right, makes sense

2023-02-24 10:18 UTC, shaurya-harness commented on src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionHeader/ExecutionHeader.tsx
> +                ? CI_YAML_VERSIONING && module?.valueOf().toLowerCase() === moduleToModuleNameMapping.ci.toLowerCase()
will cleanup later, after Vardan's changes

2023-02-24 10:18 UTC, shaurya-harness commented on src/modules/70-pipeline/pages/execution/ExecutionPipelineView/ExecutionGraphView/ExecutionStageDetailsHeader/ExecutionStageDetailsHeader.tsx
> +    CI_YAML_VERSIONING && module?.valueOf().toLowerCase() === moduleToModuleNameMapping.ci.toLowerCase()
will cleanup later, after Vardan's changes

2023-02-24 10:19 UTC, shaurya-harness commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListTable/PipelineListCells.tsx
> +    CI_YAML_VERSIONING && module?.valueOf().toLowerCase() === moduleToModuleNameMapping.ci.toLowerCase()
will cleanup later, after Vardan's changes

2023-02-24 10:19 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/PipelineCanvasV1/PipelineCanvasV1.tsx
> +// }
@vardanbansal-harness this is your code, will delete this but we might need to add it back when run modal supports selection of old input sets

2023-02-24 10:22 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/CICodebaseInputSetFormV1.tsx
> +    if (!loadingConnectorDetails && !isUndefined(connectorDetails)) {
sure, makes sense

2023-02-24 10:23 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/CICodebaseInputSetFormV1.tsx
> +      !isUndefined(codebaseConnector)
done

2023-02-24 10:24 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/useRunPipelineModalV1.tsx
> +    // }
yes, wont need this until we make other changes in run modal first

2023-02-24 10:26 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/CICodebaseInputSetFormV1.tsx
> +  }, [loadingConnectorDetails, connectorDetails])
yes, cleaning it up

2023-02-24 10:26 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/CICodebaseInputSetFormV1.tsx
> +  useEffect(() => {
done

2023-02-24 10:29 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/RunPipelineFormV1.tsx
> +  useEffect(() => {
yes

2023-02-24 13:21 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/RunPipelineModalV1/CICodebaseInputSetFormV1.tsx
> +          }
right, updated

2023-02-27 12:21 UTC, vkbansal-harness approved these changes

2023-02-28 06:28 UTC, shaurya-harness commented
retrigger jest

2023-02-28 11:09 UTC, d1wilko approved these changes
lgtm :)

2023-02-28 11:16 UTC, vkbansal-harness approved these changes

2023-02-28 11:50 UTC, merged