feat: [SRM-13596]: Downtime list view component
harness/harness-core-ui pull request #14055
Opened 2023-02-12 21:26 UTC by karansaraswat19

### Summary

#### Screenshots
![Screenshot 2023-02-13 at 2 44 17 AM](https://user-images.githubusercontent.com/110607964/218338158-c3b3a7da-92d4-4dc1-8adf-8a3f63dc88a1.png)

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-13 04:29 UTC, abhinavrastogi-harness requested changes
The standard UX for search on any listing page is to put it in the secondary header, in the same line as the "Create" buttons. Eg:
<img width="1456" alt="Screenshot 2023-02-13 at 9 57 22 AM" src="https://user-images.githubusercontent.com/47316575/218370465-226fc25d-a31e-46ff-95bc-15c24b5d800f.png">

Any filters/dropdowns should also be in the same row. Eg: 
<img width="1456" alt="Screenshot 2023-02-13 at 9 58 19 AM" src="https://user-images.githubusercontent.com/47316575/218370583-4c548a87-5db5-42b7-b4ff-c94032bd50ba.png">

2023-02-14 12:29 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/SLODowntimePage/components/DowntimeList/DowntimeList.constants.ts
> +export const defaultOption = { label: 'All', value: 'all' }
getString('all')

2023-02-14 12:30 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/SLODowntimePage/components/DowntimeList/DowntimeList.constants.ts
> +export const defaultOption = { label: 'All', value: 'all' }
check src/modules/85-cv/pages/slos/CVSLOListingPage.utils.ts

2023-02-14 12:30 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/SLODowntimePage/components/DowntimeList/DowntimeList.module.scss
> +    border-radius: 4px;
use css variables instead of px

2023-02-14 12:33 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/SLODowntimePage/components/DowntimeList/DowntimeList.utils.ts
> +    case 'Days':
check oneHour, oneDay  in src/modules/85-cv/strings/strings.en.yaml, add the missing ones

2023-02-15 12:28 UTC, karansaraswat19 commented
retrigger jest

2023-02-15 17:25 UTC, closed without merging