fix: [CDS-53327]: added warning modal on exiting for other deployment…
harness/harness-core-ui pull request #14070
Opened 2023-02-13 16:03 UTC by PratyushGar

… types from CD onboarding wizard

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-13 17:26 UTC, rameshx submitted a review, later dismissed

2023-02-13 18:10 UTC, Sagar-Rajput7 approved these changes

2023-02-13 18:20 UTC, pankajsingh-harness requested changes

2023-02-13 18:20 UTC, pankajsingh-harness commented on src/modules/75-cd/pages/get-started-with-cd/SelectWorkload/SelectDeploymentType.tsx
> +                    <Container className={css.previewLink}>
This will not be accessible using keyboard.  We should `Link` from `uicore` without `href `

[https://uicore.harness.io/?path=/docs/components-link--basic](https://uicore.harness.io/?path=/docs/components-link--basic)

2023-02-13 18:31 UTC, PratyushGar commented on src/modules/75-cd/pages/get-started-with-cd/SelectWorkload/SelectDeploymentType.tsx
> +                    <Container className={css.previewLink}>
Thanks @pankajsingh-harness , agreed, checking.
I did replace `Link` with the container as the route was now conditional on modal confirmation, so link cannot be used here.

2023-02-13 19:29 UTC, PratyushGar commented on src/modules/75-cd/pages/get-started-with-cd/SelectWorkload/SelectDeploymentType.tsx
> +                    <Container className={css.previewLink}>
Thanks @pankajsingh-harness , addressed the comment

2023-02-14 06:02 UTC, pankajsingh-harness approved these changes

2023-02-14 07:58 UTC, Eric761 approved these changes

2023-02-14 08:09 UTC, Sagar-Rajput7 approved these changes

2023-02-14 08:25 UTC, merged