feat: [CDS-51743]: added bamboo connector support
harness/harness-core-ui pull request #14089
Opened 2023-02-14 16:22 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-14 16:55 UTC, sahithikolichala commented
retrigger jest

2023-02-14 16:56 UTC, sahithikolichala commented
retrigger coverage

2023-02-16 23:46 UTC, sahithikolichala commented
retrigger jest

2023-02-16 23:54 UTC, sahithikolichala commented
retrigger coverage

2023-02-17 00:17 UTC, sahithikolichala commented
retrigger coverage

2023-02-17 23:31 UTC, sahithikolichala commented
retrigger titlecheck

2023-02-18 03:05 UTC, satyam-harness approved these changes

2023-02-18 05:14 UTC, AshwinBhatkal-Harness commented on src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx
> -    if (!loading && connectorFetchError) {
Why are removing this?

2023-02-18 05:15 UTC, AshwinBhatkal-Harness commented on src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
> -  const { getRBACErrorMessage } = useRBACError()
Same here

2023-02-18 05:22 UTC, AshwinBhatkal-Harness commented on src/modules/35-connectors/components/CreateConnector/BambooConnector/CreateBambooConnector.tsx
> +// import { pick } from 'lodash-es'
nit: remove comment

2023-02-19 22:47 UTC, sahithikolichala commented
retrigger jest

2023-02-20 05:03 UTC, AshwinBhatkal-Harness approved these changes

2023-02-20 13:21 UTC, pankajsingh-harness requested changes

2023-02-20 13:21 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/CreateConnector/NexusConnector/StepAuth/StepNexusAuthentication.tsx
> -  selectedArtifact?: 'Nexus2Registry' | 'Nexus3Registry'
There should be no change in this file. This is related to Nexus Authentication

2023-02-20 13:21 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/CreateConnector/NexusConnector/StepAuth/StepNexusAuthentication.tsx
> -  const { prevStepData, nextStep, accountId, selectedArtifact } = props
Same as above

2023-02-20 13:21 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/CreateConnector/NexusConnector/StepAuth/StepNexusAuthentication.tsx
> -  const version = selectedArtifact ? getVersion(selectedArtifact) : '2.x'
Same as above

2023-02-20 13:21 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/CreateConnector/NexusConnector/StepAuth/StepNexusAuthentication.tsx
> -          nexusVersion: version
Same as above

2023-02-20 13:21 UTC, pankajsingh-harness commented on src/modules/35-connectors/pages/connectors/utils/ConnectorUtils.ts
> +        type: 'UsernamePassword',
This hardcoding?

2023-02-20 13:21 UTC, pankajsingh-harness commented on src/modules/35-connectors/strings/strings.en.yaml
> +  bambooUrlRequired: 'Bamboo URL is required'
For required validation we can use 
```
getString('common.validation.fieldIsRequired', { name: getString(connectors.bamboo.bambooUrl) })
```

2023-02-20 13:21 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/CreateConnector/BambooConnector/StepAuth/StepBambooAuthentication.tsx
> +            bambooUrl: Yup.string().trim().required(getString('connectors.bamboo.bambooUrlRequired')),
```suggestion
            bambooUrl: Yup.string().trim().required(getString('common.validation.fieldIsRequired', { name: getString(connectors.bamboo.bambooUrl) })),
```

2023-02-20 18:27 UTC, sahithikolichala commented on src/modules/35-connectors/pages/connectors/utils/ConnectorUtils.ts
> +        type: 'UsernamePassword',
yes, because in bamboo we have only one type  and it is usernamepassword

2023-02-20 18:41 UTC, sahithikolichala commented on src/modules/35-connectors/components/CreateConnector/BambooConnector/CreateBambooConnector.module.scss
> +/*
yes, added it as separate if we need any changes

2023-02-20 18:44 UTC, sahithikolichala commented on src/modules/35-connectors/components/CreateConnector/NexusConnector/StepAuth/StepNexusAuthentication.tsx
> -  selectedArtifact?: 'Nexus2Registry' | 'Nexus3Registry'
oh this must be merge conflict issue
will resolve this

2023-02-21 02:33 UTC, sahithikolichala commented
retrigger jest

2023-02-21 17:15 UTC, sahithikolichala commented
retrigger coverage

2023-02-21 17:45 UTC, sahithikolichala commented
retrigger titlecheck

2023-02-21 19:07 UTC, satyam-harness submitted a review, later dismissed

2023-02-22 03:29 UTC, pankajsingh-harness submitted a review, later dismissed

2023-02-22 05:55 UTC, sunnykesh-harness reviewed
Have we verified the connector details page for this new connector?

2023-02-22 05:55 UTC, sunnykesh-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx
> +    loading,
Is this getting used? For adding a new connector, this file should not have any change.

2023-02-22 05:55 UTC, sunnykesh-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
> +import useRBACError from '@rbac/utils/useRBACError/useRBACError'
Changes in this file is also not required.

2023-02-22 05:55 UTC, sunnykesh-harness commented on src/modules/35-connectors/components/CreateConnector/BambooConnector/__tests__/CreateBambooConnector.test.tsx
> +describe('Create Bamboo connector wizard', () => {
Too many snapshots  (4000+) lines in this test suites. Most of things are duplicated with existing tests for other connectors as steps are reused.  Good to have just 1-2 snapshot for bamboo specific steps and cover other with assertion.

2023-02-22 16:09 UTC, sahithikolichala commented
retrigger coverage

2023-02-22 18:05 UTC, sahithikolichala commented
retrigger coverage

2023-02-23 04:54 UTC, sunnykesh-harness approved these changes

2023-02-23 05:08 UTC, pankajsingh-harness submitted a review, later dismissed

2023-02-23 05:19 UTC, satyam-harness submitted a review, later dismissed

2023-02-23 05:40 UTC, cjlee01 submitted a review, later dismissed

2023-02-23 17:04 UTC, tan-nhu approved these changes

2023-02-23 17:15 UTC, tan-nhu approved these changes

2023-02-23 17:17 UTC, ishantmehtaharness submitted a review, later dismissed
Looks Good Sahithi

2023-02-23 17:23 UTC, pankajsingh-harness submitted a review, later dismissed

2023-02-23 17:30 UTC, sahithikolichala commented
retrigger jest

2023-02-23 17:37 UTC, sahithikolichala commented
retrigger coverage

2023-02-23 18:42 UTC, tan-nhu approved these changes

2023-02-23 18:47 UTC, sahithikolichala commented
retrigger jest

2023-02-23 18:55 UTC, ishantmehtaharness approved these changes

2023-02-23 19:47 UTC, cjlee1 approved these changes

2023-02-23 19:49 UTC, cjlee01 approved these changes

2023-02-24 04:26 UTC, sunnykesh-harness approved these changes

2023-02-24 04:41 UTC, merged