fix: [CDS-53362]: fixed to clear the child(dependent field) dropdown values on parent field changes
harness/harness-core-ui pull request #14097
Opened 2023-02-14 21:47 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-15 05:25 UTC, pankajsingh-harness requested changes

2023-02-15 05:25 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzureArtifacts.tsx
> +                    setFeedsData([])
Here we have to reset all the tree fields data. So basically we have to set those options whose values we are updating.

2023-02-15 05:25 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/AzureArtifacts/AzureArtifacts.tsx
> +                    setFeedsData([])
```suggestion
                    setFeedsData([])
                    setPackageData([])
                    setVersionData([])
```

2023-02-15 18:20 UTC, sahithikolichala commented
retrigger cypress-rest

2023-02-15 18:21 UTC, sahithikolichala commented
retrigger cypress-pipeline

2023-02-15 18:21 UTC, sahithikolichala commented
retrigger titlecheck

2023-02-15 19:39 UTC, sahithikolichala commented
retrigger titlecheck

2023-02-15 19:43 UTC, sahithikolichala commented
retrigger cypress-cv

2023-02-16 15:17 UTC, sahithikolichala commented
retrigger jest

2023-02-16 15:31 UTC, sahithikolichala commented
retrigger coverage

2023-02-16 18:09 UTC, cjlee01 approved these changes

2023-02-20 13:28 UTC, pankajsingh-harness approved these changes

2023-02-20 18:27 UTC, merged