feat: Dynamic favicon support based on pipeline execution status
harness/harness-core-ui pull request #14154
Opened 2023-02-20 14:40 UTC by samarth-sharma31

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-10 04:28 UTC, abhinavrastogi-harness requested changes

2023-03-10 04:28 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/hooks/useDocumentFavicon.ts
> +export function useDocumentFavicon(pipelineStatus: PipelineExecutionSummary['status']) {
let's move this hook to `10-common`.  other modules may also need to change the favicon in the future.
we can keep only the `getFavIconInfoFromStatus` util in `70-pipeline`.

2023-03-10 04:28 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/hooks/useDocumentFavicon.ts
> +  const favIconSourceType = __DEV__ || isOnPrem() ? FavIconSourceTypes.STATIC : FavIconSourceTypes.CDN
check `window.HARNESS_ENABLE_CDN` before setting CDN url to favicon.

2023-03-10 04:28 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/hooks/useDocumentFavicon.ts
> +  useDeepCompareEffect(() => {
let's avoid `deepcompareEffect`.. instead use `useEffect` if none of the dependencies is a nested object.

2023-03-10 04:28 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/hooks/useDocumentFavicon.ts
> +  }, [pipelineStatus, selectedProject, favIconSourceType])
why is selectedProject a dependency here?

2023-03-10 04:28 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/hooks/useDocumentFavicon.ts
> +    const linkElementIco = document.getElementById('favicon-x-icon') as HTMLLinkElement
can we cache the Link element using `useMemo` to prevent DOM lookup everytime?

2023-03-14 10:31 UTC, samarth-sharma31 commented on src/modules/70-pipeline/hooks/useDocumentFavicon.ts
> +    const linkElementIco = document.getElementById('favicon-x-icon') as HTMLLinkElement
done!

2023-03-14 10:32 UTC, samarth-sharma31 commented on src/modules/70-pipeline/hooks/useDocumentFavicon.ts
> +  }, [pipelineStatus, selectedProject, favIconSourceType])
yes, not required. Removed

2023-03-14 10:32 UTC, samarth-sharma31 commented on src/modules/70-pipeline/hooks/useDocumentFavicon.ts
> +  useDeepCompareEffect(() => {
done

2023-03-14 10:32 UTC, samarth-sharma31 commented on src/modules/70-pipeline/hooks/useDocumentFavicon.ts
> +  const favIconSourceType = __DEV__ || isOnPrem() ? FavIconSourceTypes.STATIC : FavIconSourceTypes.CDN
done

2023-03-14 10:32 UTC, samarth-sharma31 commented on src/modules/70-pipeline/hooks/useDocumentFavicon.ts
> +export function useDocumentFavicon(pipelineStatus: PipelineExecutionSummary['status']) {
done

2023-03-15 16:43 UTC, abhinavrastogi-harness commented on src/modules/10-common/hooks/useDocumentFavicon.ts
> +// eslint-disable-next-line no-restricted-imports
the eslint rule is in place for a reason. let's not bypass it 😅

2023-03-15 16:43 UTC, abhinavrastogi-harness commented on src/modules/10-common/hooks/useDocumentFavicon.ts
> +import { getFavIconTypeFromPipelineStatus, SUPPORTED_FAVICON_STATUS_TYPES } from '@pipeline/utils/statusHelpers'
`useDocumentFavicon` should not be aware of pipelines. run the pipeline logic in the execution view, and then pass the final icon to this hook.

2023-03-15 16:43 UTC, abhinavrastogi-harness commented on src/modules/10-common/hooks/useDocumentFavicon.ts
> +import type { PipelineExecutionSummary } from 'services/pipeline-ng'
same. common components should not depend on specific services. It'll make it impossible to move this component out of NGUI later, or for other microfrontends to reuse it.

2023-03-15 16:43 UTC, abhinavrastogi-harness commented on src/modules/10-common/hooks/useDocumentFavicon.ts
> +const EXECUTION_STATUS_VS_FAVICON_INFO_MAP = {
this map is specific to Pipelines.. it should not be in 10-common

2023-03-15 16:43 UTC, abhinavrastogi-harness commented on src/modules/10-common/hooks/useDocumentFavicon.ts
> +const getFavIconInfoFromStatus = (
same. move to pipelines.

2023-03-15 16:43 UTC, abhinavrastogi-harness commented on src/modules/10-common/hooks/useDocumentFavicon.ts
> +const shouldUseStaticSource = () => __DEV__ || isOnPrem() || !(window as any).HARNESS_ENABLE_CDN
dont use `any`. instead declare this variable is available on Window in `global.d.ts`

2023-03-15 16:43 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/utils/statusHelpers.ts
> +export enum SUPPORTED_FAVICON_STATUS_TYPES {
why do we need a new enum? why not just use `PipelineExecutionSummary['status']` directly?

2023-03-16 15:02 UTC, samarth-sharma31 commented on src/modules/70-pipeline/utils/statusHelpers.ts
> +export enum SUPPORTED_FAVICON_STATUS_TYPES {
agreed, removed

2023-03-16 15:03 UTC, samarth-sharma31 commented on src/modules/10-common/hooks/useDocumentFavicon.ts
> +const shouldUseStaticSource = () => __DEV__ || isOnPrem() || !(window as any).HARNESS_ENABLE_CDN
done

2023-03-16 15:03 UTC, samarth-sharma31 commented on src/modules/10-common/hooks/useDocumentFavicon.ts
> +const getFavIconInfoFromStatus = (
done

2023-03-16 15:03 UTC, samarth-sharma31 commented on src/modules/10-common/hooks/useDocumentFavicon.ts
> +// eslint-disable-next-line no-restricted-imports
resolved

2023-03-16 15:04 UTC, samarth-sharma31 commented on src/modules/10-common/hooks/useDocumentFavicon.ts
> +import type { PipelineExecutionSummary } from 'services/pipeline-ng'
done

2023-03-16 15:04 UTC, samarth-sharma31 commented on src/modules/10-common/hooks/useDocumentFavicon.ts
> +const EXECUTION_STATUS_VS_FAVICON_INFO_MAP = {
done

2023-03-17 05:36 UTC, abhinavrastogi-harness approved these changes

2023-03-17 05:42 UTC, kapilkumawat86 approved these changes

2023-03-17 05:42 UTC, merged

2023-03-17 05:43 UTC, samarth-sharma31 commented on package.json
> +    "custom-coverage": "npx new-files-coverage-check --e !**/*.test.tsx !**/*.test.ts !**/*.snap !**/*.js !**/*.scss !**/*.mock.ts !**/*.spec.ts !**/*.d.ts !**/*.json !**/*.types.ts !**/types.ts !**/
sure @abhinavrastogi-harness , i'll do this change in a follow up PR, this one is merged