feat: [CDS-53356]:move-template
harness/harness-core-ui pull request #14211
Opened 2023-02-22 18:05 UTC by litvinovstas

### Summary
Added option to move inline template to remote

#### Screenshots
<img width="318" alt="Screenshot 2023-02-22 at 19 02 37" src="https://user-images.githubusercontent.com/102949579/220716992-00082a6d-1967-49ed-a58f-98893d2fd4ce.png">
<img width="787" alt="Screenshot 2023-02-22 at 19 05 14" src="https://user-images.githubusercontent.com/102949579/220717001-ef24054c-46e4-47a0-be3e-d9314dc00371.png">

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-23 03:54 UTC, AshwinBhatkal-Harness commented
The spacing between version label and the name is more than others. Also the version label header style is different
![image](https://user-images.githubusercontent.com/96711906/220817891-21a1e1ba-16cc-4517-a175-1c2e7552655e.png)

2023-02-23 03:57 UTC, AshwinBhatkal-Harness commented on src/modules/72-templates-library/pages/TemplatesPage/views/TemplateListCardContextMenu/TemplateListCardContextMenu.tsx
> +    if ((template as TemplateMetadataSummaryResponse)?.storeType === StoreType.INLINE) {
Let's not do this here. If there are other versions of the template that needs to be moved, then it will restrict them. Let's push this menu item directly

We could instead show them a proper error message after processing the template list data and we find no inline versions

2023-02-23 04:03 UTC, AshwinBhatkal-Harness commented on src/modules/72-templates-library/components/MigrateTemplateResource/MoveTemplateResource.tsx
> +                <PageSpinner message={getString('loading')} />
We can use a container spinner and give it the same height as the modal. This will look clean

2023-02-23 04:05 UTC, AshwinBhatkal-Harness commented on src/modules/72-templates-library/components/MigrateTemplateResource/MoveTemplateResource.tsx
> +        versionLabel: versionLabel || DefaultStableVersionValue,
We don't want this || check. version label should always contain a value before entering this function. Let's add validation if required

2023-02-23 04:07 UTC, AshwinBhatkal-Harness commented on src/modules/72-templates-library/components/MigrateTemplateResource/MoveTemplateResource.tsx
> +  const getReourceTypeText = useCallback((): string => {
typo: getResourceTypeText

2023-02-23 04:08 UTC, AshwinBhatkal-Harness commented on src/modules/72-templates-library/components/MigrateTemplateResource/MoveTemplateResource.tsx
> +  }, [templates])
disable es lint warning here

2023-02-23 04:10 UTC, AshwinBhatkal-Harness commented on src/modules/72-templates-library/components/MigrateTemplateResource/MoveTemplateResource.tsx
> +      showError(err.message ?? getString('somethingWentWrong'))
Use getRBACErrorMessage instead

2023-02-23 04:11 UTC, AshwinBhatkal-Harness requested changes
We need to only show those versions in the version label dropdown that have not already been moved to git

2023-02-23 18:43 UTC, AshwinBhatkal-Harness commented on src/modules/72-templates-library/strings/strings.en.yaml
> +moveTemplateWarning: All existing versions are already in remote repository
nit: moveTemplateToRemoteWarning

2023-02-24 16:19 UTC, litvinovstas commented
retrigger jest

2023-02-27 05:49 UTC, AshwinBhatkal-Harness approved these changes

2023-02-27 06:00 UTC, vkbansal-harness approved these changes

2023-02-27 06:00 UTC, merged