fix: [PIE-8316]: handle to string for number inputs and remove defaul…
harness/harness-core-ui pull request #14242
Opened 2023-02-24 06:09 UTC by vikrant-harness

…ts from YAML in run pip form

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-24 06:24 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2023-02-24 10:35 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2023-02-24 12:55 UTC, AshwinBhatkal-Harness approved these changes

2023-02-24 22:30 UTC, Eric761 approved these changes

2023-02-25 07:20 UTC, vkbansal-harness requested changes

2023-02-25 07:20 UTC, vkbansal-harness commented on src/modules/10-common/components/ConfigureOptions/ConfigureOptionsUtils.ts
> -        parsedInput[InputSetFunction.DEFAULT] = yamlParse(fnArgs)
This will break list values as default value

2023-02-25 07:37 UTC, closed without merging