feat: [CDS-51743]: added code for bamboostep
harness/harness-core-ui pull request #14568
Opened 2023-03-10 00:10 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-13 20:19 UTC, sahithikolichala commented
retrigger coverage

2023-03-13 20:24 UTC, sahithikolichala commented
retrigger jest

2023-03-14 05:36 UTC, pankajsingh-harness requested changes

2023-03-14 05:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/BambooStep/BambooStep.tsx
> +          onUpdate={(values: any) => onUpdate?.(this.processFormData(values))}
```suggestion
          onUpdate={(values: BambooStepData) => onUpdate?.(this.processFormData(values))}
```

2023-03-14 05:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/BambooStep/BambooStep.tsx
> +          onChange={(values: any) => onChange?.(this.processFormData(values))}
```suggestion
          onChange={(values: BambooStepData) => onChange?.(this.processFormData(values))}
```

2023-03-14 05:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/BambooStep/BambooStep.tsx
> +        onChange={(values: any) => onChange?.(this.processFormData(values))}
```suggestion
        onChange={(values: BambooStepData) => onChange?.(this.processFormData(values))}
```

2023-03-14 05:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/BambooStep/BambooStep.tsx
> +        onUpdate={(values: any) => onUpdate?.(this.processFormData(values))}
```suggestion
        onUpdate={(values: BambooStepData) => onUpdate?.(this.processFormData(values))}
```

2023-03-14 05:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/BambooStep/BambooStepBase.tsx
> +          <ConfigureOptions
```suggestion
          < SelectConfigureOptions
```
To support allowed values. Check [https://harness.atlassian.net/wiki/spaces/PD/pages/21173404394/Allowed+Values+-+Pipeline+Team+-+Dev+changes](https://harness.atlassian.net/wiki/spaces/PD/pages/21173404394/Allowed+Values+-+Pipeline+Team+-+Dev+changes)

2023-03-14 05:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/BambooStep/BambooStepBase.tsx
> +          <ConfigureOptions
Check for allowed values support for this field.

2023-03-14 05:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/BambooStep/BambooStepInputSet.tsx
> +function BambooStepInputSet(formContentProps: any): JSX.Element {
Add proper type here

2023-03-14 05:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/BambooStep/types.tsx
> +  formik?: any
Add proper type here

2023-03-14 05:36 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/BambooArtifactSource/BambooArtifactSource.tsx
> +                      {plansError ? get(plansError, 'data.message', '') : 'Cannot Fetch Plans'}
Move this hard coding to yaml.

2023-03-14 05:36 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/BambooArtifactSource/BambooArtifactSource.tsx
> +                      {artifactPathError ? get(artifactPathError, 'data.message', '') : 'Cannot Fetch Artifact Paths'}
Same as above

2023-03-14 05:36 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/BambooArtifactSource/BambooArtifactSource.tsx
> +                      {buildError ? get(buildError, 'data.message', '') : 'Cannot Fetch Builds'}
Same as above

2023-03-15 16:54 UTC, pankajsingh-harness commented on src/modules/70-pipeline/strings/strings.en.yaml
> +cannotFetchOptions: Loading {{fieldName}}...
We have this `loadingFieldOptions: Loading {{fieldName}}s...` in `src/modules/10-common/strings/strings.en.yaml`

2023-03-16 05:03 UTC, pankajsingh-harness approved these changes

2023-03-16 14:13 UTC, merged