fix: [CDS-53795]: fixed ami tags and filters to be array type at runtime
harness/harness-core-ui pull request #14590
Opened 2023-03-10 21:43 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-10 22:55 UTC, sahithikolichala commented
retrigger jest

2023-03-14 23:52 UTC, sahithikolichala commented
retrigger jest

2023-03-14 23:53 UTC, sahithikolichala commented
retrigger coverage

2023-03-15 16:49 UTC, pankajsingh-harness requested changes

2023-03-15 16:49 UTC, pankajsingh-harness commented on src/modules/10-common/components/MultiTypeTagSelector/MultiTypeArrayTagSelector.tsx
> +  setAsArray?: boolean
We can remove this now

2023-03-15 16:49 UTC, pankajsingh-harness commented on src/modules/10-common/components/MultiTypeTagSelector/MultiTypeTagSelector.tsx
> +  setAsArray?: boolean
We can remove this now

2023-03-15 19:31 UTC, sahithikolichala commented
retrigger jest

2023-03-15 19:31 UTC, sahithikolichala commented
retrigger coverage

2023-03-16 05:01 UTC, pankajsingh-harness approved these changes

2023-03-16 14:13 UTC, kapilkumawat86 approved these changes

2023-03-16 14:13 UTC, merged