feat: [CDS-55098]:dynamic-secret-field-shell-script-step
harness/harness-core-ui pull request #14618
Opened 2023-03-13 10:11 UTC by litvinovstas

### Summary
Fixed issue with display runtime secret field in shell script step, into run pipeline modal

#### Screenshots
<img width="739" alt="Screenshot 2023-03-13 at 11 09 06" src="https://user-images.githubusercontent.com/102949579/224671481-4ebdfd50-5253-4a0b-842b-fdd340307266.png">
<img width="734" alt="Screenshot 2023-03-13 at 11 09 13" src="https://user-images.githubusercontent.com/102949579/224671490-a5961ba9-c070-4114-940b-6ea2f6087da6.png">

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-13 10:14 UTC, litvinovstas commented
retrigger titlecheck

2023-03-13 10:58 UTC, litvinovstas commented
retrigger jest

2023-03-13 11:23 UTC, litvinovstas commented
retrigger cypress-pipeline

2023-03-13 11:24 UTC, litvinovstas commented
retrigger cypress-cd

2023-03-13 11:26 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/ShellScriptStep/shellScriptTypes.ts
> +export enum ShellScriptSecrets {
Can we rename this to a singular form? 
```suggestion
export enum ShellScriptSecret {
```

2023-03-13 17:43 UTC, pankajsingh-harness requested changes

2023-03-13 17:43 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/ShellScriptStep/shellScriptTypes.ts
> +export enum ShellScriptSecret {
Use `Exclude<SecretDTOV2['type'], 'SecretFile' | 'SecretText'>` in place of creating new source of truth in the UI again. We should try to use as much type from the services as possible to have BE as single source of truth.

2023-03-13 17:43 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/ShellScriptStep/shellScriptTypes.ts
> +export enum ScriptType {
Use `ShellScriptStepInfo['shell']` in place of declaring new enum.

2023-03-13 19:23 UTC, litvinovstas commented on src/modules/75-cd/components/PipelineSteps/ShellScriptStep/shellScriptTypes.ts
> +export enum ScriptType {
mostly i added enum for using constants, because as i see in most part of project using for them text values

2023-03-14 08:43 UTC, litvinovstas commented
retrigger jest

2023-03-14 17:50 UTC, litvinovstas commented
retrigger cypress-pipeline

2023-03-15 11:04 UTC, pankajsingh-harness approved these changes

2023-03-15 11:18 UTC, rameshx approved these changes

2023-03-15 11:54 UTC, litvinovstas commented
retrigger cypress-pipeline

2023-03-15 13:02 UTC, merged