feat: [CDS-53344]: Show warning message and update usergroup list
harness/harness-core-ui pull request #14627
Opened 2023-03-13 13:55 UTC by sonaligoyal-harness

### Summary

#### Screenshots

https://user-images.githubusercontent.com/98508399/224913555-b1c946ee-9c73-4667-bb69-39cf0286e662.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-14 06:28 UTC, satyam-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/__tests__/HarnessApproval.test.tsx
> +    // return { data: {}, refetch: jest.fn(), error: null, loading: false }
can u remove this?

2023-03-14 06:29 UTC, sonaligoyal-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/__tests__/HarnessApproval.test.tsx
> +    // return { data: {}, refetch: jest.fn(), error: null, loading: false }
yes

2023-03-14 06:30 UTC, satyam-harness approved these changes

2023-03-14 06:42 UTC, rameshx requested changes

2023-03-14 06:42 UTC, rameshx commented on src/modules/10-common/components/MultiSelectEntityReference/MultiSelectEntityReference.tsx
> +            `${checkedItems[selectedScope]?.scopedItemsTotal}` && (
strings are being compared instead of numbers, move this condition to the top and use it here

2023-03-14 06:42 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/HarnessApprovalStepMode.tsx
> +    return await Promise.all(promises).then(responses => {
`await` is not need here

2023-03-14 06:42 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/HarnessApprovalStepMode.tsx
> +    return await Promise.all(promises).then(responses => {
How is the error handled if any of the promises reject?

2023-03-14 06:43 UTC, avinashmadhwani02 commented on src/modules/10-common/components/MultiSelectEntityReference/MultiSelectEntityReference.tsx
> +          {`${(scopeCountMap?.get(selectedScope) as string[])?.length}` <
why the conditon is in ``?

2023-03-14 06:43 UTC, avinashmadhwani02 commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/HarnessApprovalStepMode.tsx
> +      getMultiTypeFromValue(formikUserGroups) === MultiTypeInputType.FIXED &&
Please use `if` to make it more readable

2023-03-14 06:43 UTC, avinashmadhwani02 commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/HarnessApprovalStepMode.tsx
> +      formikUserGroups?.map((userGroup: any) => {
use forEach for looping instead of map

2023-03-14 06:43 UTC, avinashmadhwani02 commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/HarnessApprovalStepMode.tsx
> +    return await Promise.all(promises).then(responses => {
Do we need any error handling for API's?

Promise.all will be rejected if any of the API fails

2023-03-14 06:43 UTC, avinashmadhwani02 commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/HarnessApprovalStepMode.tsx
> +      responses.forEach((response, idx: number) => {
we can make use of .map

2023-03-14 06:44 UTC, rameshx commented on src/modules/10-common/strings/strings.en.yaml
> +warningMessage: 'Some of the User Groups referenced in this scope have been updated.'
update the string key to be more specific as this is in common

2023-03-15 06:53 UTC, sonaligoyal-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/HarnessApprovalStepMode.tsx
> +    return await Promise.all(promises).then(responses => {
done

2023-03-15 06:53 UTC, sonaligoyal-harness commented on src/modules/10-common/components/MultiSelectEntityReference/MultiSelectEntityReference.tsx
> +          {`${(scopeCountMap?.get(selectedScope) as string[])?.length}` <
removed

2023-03-15 06:53 UTC, sonaligoyal-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/HarnessApprovalStepMode.tsx
> +    return await Promise.all(promises).then(responses => {
done

2023-03-15 09:54 UTC, rameshx approved these changes

2023-03-15 09:54 UTC, rameshx commented on src/modules/10-common/components/UserGroupsReference/__test__/__snapshots__/UserGroupsReference.test.tsx.snap
> +      <div />
Just pointing out these empty divs, ignore if they are expected

2023-03-15 09:54 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/HarnessApprovalStepMode.tsx
> +        showError(e)
How does the error toast look? Don't we need to extract the error message?

2023-03-15 10:20 UTC, sonaligoyal-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/HarnessApprovalStepMode.tsx
> +        showError(e)
At one other place also, it is shown in similar manner for this api call.
So handled it in the same manner

2023-03-15 10:20 UTC, sonaligoyal-harness commented on src/modules/10-common/components/UserGroupsReference/__test__/__snapshots__/UserGroupsReference.test.tsx.snap
> +      <div />
sure, will update it with next PR.

2023-03-15 10:21 UTC, satyam-harness approved these changes

2023-03-15 11:21 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Approval/HarnessApprovalStepMode.tsx
> +        showError(e)
@sonaligoyal-harness Please verify that the error toast renders fine/is readable.

2023-03-17 05:20 UTC, rameshx approved these changes

2023-03-17 06:13 UTC, satyam-harness approved these changes

2023-03-17 06:59 UTC, avinashmadhwani02 approved these changes

2023-03-17 07:02 UTC, merged