fix: [CI-6661]: fix execution graph view for V1 simplified yaml
harness/harness-core-ui pull request #14739
Opened 2023-03-20 13:50 UTC by shaurya-harness

### Summary

fix execution graph view for V1 simplified yaml
for V1 yaml : backend does not send NG_EXECUTION node and STEP_GROUP node type has been changed to GROUP in the execution detail api
this PR takes that into consideration to fix the execution graph view

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-20 15:04 UTC, d1wilko requested changes
1 question - but otherwise looking good :)

2023-03-20 15:04 UTC, d1wilko commented on src/modules/70-pipeline/utils/execUtils.ts
> +            })?.[0] || ''
I found this quite confusing - maybe it could be simplified something like

`
const parentNodeId = Object.keys(nodeAdjacencyListMap || {}).find(key => {
  const val = nodeAdjacencyListMap[key];
  return val?.children?.includes(nodeData.uuid!);
}) || '';

`

2023-03-20 16:18 UTC, shaurya-harness commented on src/modules/70-pipeline/utils/execUtils.ts
> +            })?.[0] || ''
sure @d1wilko that can be done, I re-used the same code we were using for v0 yaml

2023-03-21 09:07 UTC, d1wilko approved these changes
LGTM :)

2023-03-28 05:17 UTC, vkbansal-harness approved these changes

2023-03-28 06:47 UTC, merged