fix: [CDS-53660]: modified to use api calls for nexus groupid and artifactid
harness/harness-core-ui pull request #14749
Opened 2023-03-20 23:59 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-29 07:56 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus2Artifact/Nexus2Artifact.tsx
> +                              nexusSourceType: 'Nexus3Registry'
Make this `Nexus2Registry` and the API will start working fine.

2023-03-30 04:03 UTC, sahithikolichala commented
retrigger jest

2023-03-30 04:28 UTC, sahithikolichala commented
retrigger jest

2023-03-31 13:02 UTC, pankajsingh-harness requested changes

2023-04-04 09:41 UTC, pankajsingh-harness commented
Do not merge this PR until delegates are updated. https://harness.atlassian.net/browse/CDS-58560

2023-04-18 22:45 UTC, sahithikolichala commented
Closing because of merge conflicts

2023-04-18 22:45 UTC, closed without merging