feat: [SRM-14325]: removed feature flag SRM_INTERNAL_CHANGE_SOURCE_FF
harness/harness-core-ui pull request #14777
Opened 2023-03-21 11:59 UTC by deepesh-ui

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-22 04:16 UTC, praneshg239 approved these changes

2023-03-23 05:15 UTC, karansaraswat19 requested changes

2023-03-23 05:15 UTC, karansaraswat19 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesSourceCard/ChangesSourceCard.utils.ts
> +  return {
here also

2023-03-23 05:15 UTC, karansaraswat19 commented on src/modules/85-cv/components/ChangeTimeline/ChangeTimeline.tsx
> +        return {
I have mistakenly put return in arrow functions. We can remove them.

2023-03-23 05:15 UTC, karansaraswat19 commented on src/modules/85-cv/components/ChangeTimeline/ChangeTimeline.utils.ts
> +      return {
here too

2023-03-23 07:34 UTC, deepesh-ui commented on src/modules/85-cv/components/ChangeTimeline/ChangeTimeline.tsx
> +        return {
done

2023-03-23 09:02 UTC, praneshg239 approved these changes

2023-03-24 04:43 UTC, karansaraswat19 approved these changes

2023-03-24 04:45 UTC, merged