feat: [PL-32035]: pagination, sort, search updates for services, templates, environments and environment groups
harness/harness-core-ui pull request #14840
Opened 2023-03-23 21:35 UTC by rameshx

### Summary

Updates services, templates, environments, and environment groups to:

- support customizable page size
- persist pagination data in query params
- add new page size options
- fix misc. bugs

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-24 06:50 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2023-03-24 07:03 UTC, vkbansal-harness submitted a review, later dismissed

2023-03-24 07:37 UTC, abhinavrastogi-harness requested changes

2023-03-24 07:37 UTC, abhinavrastogi-harness commented on src/modules/72-templates-library/pages/TemplatesPage/TemplatesPage.tsx
> +              <ResultsViewHeader
Can we use the standard `<ListHeader>` component instead?

2023-03-24 07:37 UTC, abhinavrastogi-harness commented on src/modules/72-templates-library/pages/TemplatesPage/TemplatesPageUtils.tsx
> +export const TEMPLATES_DEFAULT_SORT: [SortFields, Sort] = [SortFields.LastUpdatedAt, Sort.DESC]
can we reuse the standard "Last Modified" sort method instead of this custom "LastUpdated" one?
https://github.com/harness/harness-core-ui/blob/develop/src/modules/10-common/utils/sortUtils.ts#L15

2023-03-24 07:37 UTC, abhinavrastogi-harness commented on src/modules/72-templates-library/pages/TemplatesPage/views/ResultsViewHeader/ResultsViewHeader.tsx
> +  })()
all of this can be removed if we use the new `ListHeader` component with the standard sorting params.

2023-03-24 07:37 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/DashboardList/DashboardList.tsx
> +          {sortList}
Again, we can replace this with the `ListHeader` component to simplify and standardise sorting

2023-03-24 07:37 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/EnvironmentsV2/PageTemplate/utils.ts
> +export const usePageQueryParamOptions = <T extends CommonPaginationQueryParams>(): UseQueryParamsOptions<
this hook seems to be repeated in a few files.. cant we reuse it?

2023-03-24 07:37 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/Services/ServicesListPage/ServicesListPage.tsx
> +  const [sort, setSort] = useState<string[]>(savedSortOption ?? queryParams.sort)
let's re-use sorting enums from https://github.com/harness/harness-core-ui/blob/develop/src/modules/10-common/utils/sortUtils.ts#L15

2023-03-24 07:37 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/Services/ServicesListPage/ServicesListPage.tsx
> +            <SortOption
We should use the `ListHeader` component

2023-03-24 07:37 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/Services/utils/ServiceUtils.ts
> +export const useServicesQueryParamOptions = (): UseQueryParamsOptions<ServicesQueryParamsWithDefaults> => {
another repeatition of this hook

2023-03-24 23:42 UTC, rameshx commented on src/modules/72-templates-library/pages/TemplatesPage/TemplatesPage.tsx
> +              <ResultsViewHeader
removed `ResultsViewHeader` and used `ListHeader`

2023-03-24 23:43 UTC, rameshx commented on src/modules/72-templates-library/pages/TemplatesPage/TemplatesPageUtils.tsx
> +export const TEMPLATES_DEFAULT_SORT: [SortFields, Sort] = [SortFields.LastUpdatedAt, Sort.DESC]
added a new entry to the enum in https://github.com/harness/harness-core-ui/blob/develop/src/modules/10-common/utils/sortUtils.ts#L15 as last modified is not supported by the templates API

2023-03-24 23:44 UTC, rameshx commented on src/modules/75-cd/components/DashboardList/DashboardList.tsx
> +          {sortList}
UI for this is a bit different so `ListHeader` cannot be used here.

2023-03-24 23:44 UTC, rameshx commented on src/modules/75-cd/components/Services/ServicesListPage/ServicesListPage.tsx
> +  const [sort, setSort] = useState<string[]>(savedSortOption ?? queryParams.sort)
used enums

2023-03-24 23:45 UTC, rameshx commented on src/modules/75-cd/components/Services/ServicesListPage/ServicesListPage.tsx
> +            <SortOption
UI for this is a bit different so `ListHeader` cannot be used here. There are also tickets to update the Services UI.

2023-03-24 23:52 UTC, rameshx commented on src/modules/75-cd/components/EnvironmentsV2/PageTemplate/utils.ts
> +export const usePageQueryParamOptions = <T extends CommonPaginationQueryParams>(): UseQueryParamsOptions<
Created a new generic hook to extract common code.
It's impossible to entirely remove these hooks as different lists need different default parameters and access to the feature flag.

2023-03-24 23:52 UTC, rameshx commented on src/modules/75-cd/components/Services/utils/ServiceUtils.ts
> +export const useServicesQueryParamOptions = (): UseQueryParamsOptions<ServicesQueryParamsWithDefaults> => {
Created a new generic hook to extract common code.
It's impossible to entirely remove these hooks as different lists need different default parameters and access to the feature flag.

2023-03-31 04:14 UTC, abhinavrastogi-harness approved these changes

2023-03-31 06:20 UTC, vkbansal-harness approved these changes

2023-03-31 06:26 UTC, rameshx commented
This needs to be force merged as Sonar check is failing because of duplicate code that cannot be deduped.

2023-03-31 08:15 UTC, merged