feat: [CDS-57974]: Redesign Service Dashboard page - (removed Manage services page)
harness/harness-core-ui pull request #14955
Opened 2023-03-29 20:34 UTC by Sagar-Rajput7

### Summary

#### Screenshots

Before:

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/98325173/228660832-df9a16f0-f501-49e9-b0bf-6a9c9bffeecc.png">

After:

<img width="1727" alt="Screenshot 2023-03-30 at 2 02 39 AM" src="https://user-images.githubusercontent.com/98325173/228660666-07b16698-e253-48eb-b234-29841294dd67.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-30 14:42 UTC, douglasnfrazao submitted a review, later dismissed

2023-03-30 15:38 UTC, rameshx requested changes

2023-03-30 15:38 UTC, rameshx commented on src/modules/75-cd/components/DashboardList/DashboardList.module.scss
> +.subHeaderStyles {
styles suffix is unnecessary

2023-03-30 18:06 UTC, AshwinBhatkal-Harness approved these changes

2023-03-31 03:04 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/DashboardList/DashboardList.module.scss
> +.subHeaderStyles {
Done

2023-03-31 03:04 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/DashboardList/DashboardList.module.scss
> +.dialogStyles {
Done

2023-03-31 03:05 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/DashboardList/DashboardList.tsx
> +        isOpen={true}
Done, used useToggleOpen.
Thanks for pointing this out, I missed it as I moved this code from another existing file.

2023-03-31 03:05 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/DashboardList/DashboardList.tsx
> +  )
Done

2023-03-31 03:05 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/Services/Services.tsx
> +              onClick={refetchServiceDashboard.current as () => void}
removed and used chaining

2023-03-31 03:05 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/Services/ServicesList/ServicesList.tsx
>      [data]
Done

2023-03-31 06:16 UTC, rameshx commented on src/modules/75-cd/components/DashboardList/DashboardList.tsx
> +    <Dialog
this will be defined on every render, if you want to use it as a function that returns JSX instead of a function component then change the usage to `NewServiceDialog()` or define this outside to use it as a component

2023-03-31 06:16 UTC, rameshx commented on src/modules/75-cd/components/Services/ServicesList/ServicesList.tsx
> +  }
define this outside the component body

2023-03-31 06:16 UTC, rameshx commented on src/modules/75-cd/components/DashboardList/DashboardList.tsx
> +    <Dialog
You can also simply use a `const` instead of a function, like `const newServiceDialog = <Dialog...` and use it as `{newServiceDialog}`

2023-03-31 08:34 UTC, rameshx approved these changes

2023-03-31 10:52 UTC, rameshx approved these changes

2023-03-31 10:55 UTC, sonaligoyal-harness approved these changes

2023-03-31 10:56 UTC, merged