feat: [PL-32258]: Session time out refresh logic
harness/harness-core-ui pull request #14977
Opened 2023-03-30 14:17 UTC by swarajcheguri-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-03 04:17 UTC, udayvunnam commented on src/framework/app/App.tsx
> +const MAX_REFRESH_TIME = 120
nit: MAX_REFRESH_TIME_IN_MINUTES

2023-04-03 04:17 UTC, abhinavrastogi-harness requested changes

2023-04-03 04:17 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +    }
this can be done in a functional way like
```
Math.min(Math.max(num, min), max);
```

2023-04-03 04:17 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +  const checkAndRefreshToken = debounce((): void => {
it's better to create a named debounce function, instead of an anonymous fn.
it makes testing easier, and debugging also.

2023-04-03 04:17 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +      refreshToken({ queryParams: getQueryParams() as any })
what is `getQueryParams()` here? and why is it `any`?

2023-04-03 04:17 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +  // considering user to be acitve when user is either doing mouse or key board events
typo in `active`

2023-04-03 04:17 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +    trackUserActivity()
you need to remove the event listeners on unmount. otherwise this can cause a memory leak.

2023-04-03 04:17 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +  const trackUserActivity = () => {
no need to create a separate function for this.. move this code inline into the useEffect below

2023-04-03 04:17 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +      })
why do we need the anonymous wrapper?
```
document.addEventListener('mousedown', checkAndRefreshToken)
```
is better and allows easy unbinding also

2023-04-03 04:17 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +    if (document) {
why would `document` ever be undefined? is it nullable in typescript?

2023-04-03 04:17 UTC, abhinavrastogi-harness commented on src/framework/utils/SessionUtils.ts
> +export const parseJwtToken = (token: string) => {
please add exhaustive test cases for all new session related functions because they are very high impact changes.

2023-04-03 04:17 UTC, abhinavrastogi-harness commented on src/framework/utils/SessionToken.ts
> +  getLastTokenIssuedTime: (): number => {
these two functions implementations can be combined in a util.. the only difference is in ready the key `iat` or `exp`. those values can be passed as params

2023-04-03 04:18 UTC, udayvunnam commented on src/framework/app/App.tsx
>      }
why not move/scroll considered activity? should we instead use interval to checkAndRefreshToken on an active browser tab?

2023-04-03 10:31 UTC, swarajcheguri-harness commented on src/framework/app/App.tsx
> +      refreshToken({ queryParams: getQueryParams() as any })
since BE swagger did not have queryparams  for routing id and they said they did not provide this query params for any of the BE api calls and still FE is sending it. Will Speak to them to add query params for refresh token , but for now added 'any' for typescript purpose

2023-04-03 10:32 UTC, swarajcheguri-harness commented on src/framework/app/App.tsx
>      }
since during the discussion we thought there are softwares which move mouse to keep session active to get around those software did not consider mouse movements

2023-04-04 04:23 UTC, mayankVermaHarness commented on src/framework/app/App.tsx
> +  }, 500)
Should we increase this 500 ms to say around 2 seconds? 500ms seems like a very small timeframe.

2023-04-04 04:26 UTC, mayankVermaHarness commented on src/framework/utils/__tests__/SessionUtils.test.ts
> +        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoVG9rZW4iOiI2NDJhOTljMzY5MTExOTJkZWEzMzY3NGYiLCJpc3MiOiJIYXJuZXNzIEluYyIsImV4cCI6MTY4MDYwNDE5MSwiZW52IjoiZ2F0ZXdheSIsImlhdCI6MTY4MDUxNzczMX0.bl-q6
Let's ensure that the tokens in this test file aren't active tokens from Harness prod. Or if possible, use a token from preQA/QA; OR a dummy JWT token that can be parsed but isn't valid for any other purpose.

2023-04-04 04:54 UTC, swarajcheguri-harness commented on src/framework/utils/__tests__/SessionUtils.test.ts
> +        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoVG9rZW4iOiI2NDJhOTljMzY5MTExOTJkZWEzMzY3NGYiLCJpc3MiOiJIYXJuZXNzIEluYyIsImV4cCI6MTY4MDYwNDE5MSwiZW52IjoiZ2F0ZXdheSIsImlhdCI6MTY4MDUxNzczMX0.bl-q6
this token is from pre QA

2023-04-04 10:41 UTC, udayvunnam approved these changes

2023-04-04 11:17 UTC, mayankVermaHarness approved these changes

2023-04-04 14:41 UTC, abhinavrastogi-harness approved these changes

2023-04-04 14:41 UTC, merged