fix: [CDS-54325]:remove expression type from jenkins build job params
harness/harness-core-ui pull request #15020
Opened 2023-04-01 20:29 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-03 08:57 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
> +        allowableTypes={
@namanharness this will remove expression support from all the field for the Jenkins step. You can apply the same logic here: [https://github.com/harness/harness-core-ui/blob/develop/src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStepBase.tsx#L537](https://github.com/harness/harness-core-ui/blob/develop/src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStepBase.tsx#L537)

2023-04-03 08:58 UTC, pankajsingh-harness requested changes
Comment

2023-04-03 09:41 UTC, satyam-harness approved these changes

2023-04-03 16:17 UTC, namanharness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStepBase.tsx
> -          allowedTypes={allowableTypes}
the component `MultiTypeFieldSelector` where this is used has Fixed and Runtime as default Allowed types , so removing this defaults allowed types to Runtime & Fixed

2023-04-04 05:45 UTC, pankajsingh-harness approved these changes

2023-04-04 05:49 UTC, samarth-sharma31 approved these changes

2023-04-04 09:28 UTC, merged