fix: [SRM-14466]: Update correct icons and display title text
harness/harness-core-ui pull request #15052
Opened 2023-04-04 07:22 UTC by praneshg239

### Summary

#### Screenshots

<img width="1792" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/95267551/229717466-4a686f29-4459-4f62-9b18-3a4b892c0ab1.png">
<img width="1792" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/95267551/229717474-3d602c01-9037-4e09-a1e3-7539d426d016.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-04 12:36 UTC, karansaraswat19 requested changes

2023-04-04 15:29 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesAndServiceDependency/components/ChangesTable/components/ChangeEventCard/__tests__/ChangeEventCard.mock.ts
> +    type: 'HarnessFF' as any
It internally renders `InternalCSEventCard` component only right?
```ts
      case ChangeSourceTypes.HarnessFF:
      case ChangeSourceTypes.CustomFF:
      case ChangeSourceTypes.CustomDeploy:
      case ChangeSourceTypes.CustomIncident:
      case ChangeSourceTypes.CustomInfrastructure:
      case ChangeSourceTypes.HarnessCE:
        return <InternalCSEventCard data={data?.resource} />
```

2023-04-05 04:05 UTC, deepesh-ui commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesAndServiceDependency/components/ChangesTable/components/ChangeEventCard/__tests__/ChangeEventCard.mock.ts
> +    type: 'HarnessFF' as any
We depend on type field , so UI wise we should not face any issue
Lets use the already present mock data **HarnessFFMockData** from  InternalCSEventCard.mock.ts

2023-04-05 07:20 UTC, karansaraswat19 approved these changes

2023-04-05 07:21 UTC, karansaraswat19 commented
retrigger jest

2023-04-05 07:22 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesAndServiceDependency/components/ChangesTable/components/ChangeEventCard/__tests__/ChangeEventCard.mock.ts
> +    type: 'HarnessFF' as any
Updated

2023-04-05 07:31 UTC, deepesh-ui approved these changes

2023-04-05 07:45 UTC, merged