feat: [CI-7448]: v1 input sets for simplified yaml
harness/harness-core-ui pull request #15111
Opened 2023-04-06 12:32 UTC by shaurya-harness

### Summary

 v1 input sets for simplified yaml

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-17 06:45 UTC, vardanbansal-harness approved these changes

2023-04-17 09:27 UTC, pankajsingh-harness requested changes

2023-04-17 09:27 UTC, pankajsingh-harness commented on src/modules/70-pipeline/v1/components/InputSetFormV1/useSaveInputSetV1.ts
> +    PipelineType<InputSetPathProps> & { accountId: string }
Same as above

2023-04-17 09:27 UTC, pankajsingh-harness commented on src/modules/70-pipeline/v1/components/InputSetFormV1/useSaveInputSetV1.ts
> +            throw new Error(getString('common.validation.identifierIsRequired'))
If this Error is not handled it will break the page. We can show toast notification instead of throwing Error.

2023-04-17 09:27 UTC, pankajsingh-harness commented on src/modules/70-pipeline/v1/components/InputSetFormV1/useSaveInputSetV1.ts
> +          throw e
Same as above

2023-04-17 09:27 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/views/V1/WebhookPipelineInputPanelV1.tsx
> +  const { orgIdentifier, accountId, projectIdentifier, pipelineIdentifier } = useParams<{
```suggestion
  const { orgIdentifier, accountId, projectIdentifier, pipelineIdentifier } = useParams<PipelinePathProps>()
```

2023-04-17 09:37 UTC, d1wilko submitted a review, later dismissed
Looks good :)

I have added some suggestions for readability - but I'll leave it up to you if you want to implement

2023-04-17 09:37 UTC, d1wilko commented on src/modules/10-common/RouteDefinitions.ts
> +      }
could we do something like

let returnString = "/${basePath}..." // <- this is a terrible name for this variable lol

return queryString.length ? "${returnString}?${queryString}" : returnString

my thinking is that if returnString ever changed - we would only need to change it in 1 place instead of 2

2023-04-17 09:37 UTC, d1wilko commented on src/modules/70-pipeline/v1/components/InputSetFormV1/FormikInputSetFormV1.tsx
> +    hasEditPermission && (isGitSyncEnabled ? true : !hasStoreTypeMismatch(storeType, inputSetStoreType, isEdit))
would this be the same like
`hasEditPermission && (isGitSyncEnabled || !hasStoreTypeMismatch(storeType, inputSetStoreType, isEdit))`

2023-04-17 09:37 UTC, d1wilko commented on src/modules/70-pipeline/v1/components/InputSetFormV1/FormikInputSetFormV1.tsx
> +    const initialValues = !isEmpty(inputSet.data) ? getPipelineData(inputSet.data) : getPipelineData(inputSetYaml)
might be best to flip these round for readability
`const initialValues = isEmpty(inputSet.data) ? getPipelineData(inputSetYaml) : getPipelineData(inputSet.data)`

2023-04-17 13:47 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/InputSetFormV1/FormikInputSetFormV1.tsx
> +                        onClick={e => {
this is in particular added to handle setFormErrors which throws error on create/update api response

2023-04-17 14:11 UTC, d1wilko approved these changes
lgtm

2023-04-17 15:03 UTC, vardanbansal-harness submitted a review, later dismissed

2023-04-18 05:12 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/InputSetFormV1/FormikInputSetFormV1.tsx
> +  const NameIdSchema = Yup.object({
avoiding this since not using getValidationDetails util

2023-04-18 07:06 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/InputSetFormV1/InputSetFormV1.tsx
> +  const [loadFromCache, setLoadFromCache] = React.useState<string>(defaultLoadFromCacheHeader)
cant keep it as boolean since we pass loadFromCache to headers

2023-04-18 07:06 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/InputSetFormV1/useSaveInputSetV1.ts
> +            throw new Error(getString('common.validation.identifierIsRequired'))
we have a catch block below this to handle error, there was one missing case, added change for that

2023-04-18 07:06 UTC, shaurya-harness commented on src/modules/70-pipeline/v1/components/InputSetFormV1/useSaveInputSetV1.ts
> +          throw e
added change for this

2023-04-18 07:26 UTC, vardanbansal-harness approved these changes

2023-04-19 04:44 UTC, merged