feat: [CDS-58244]: restrict readonly secret manager for terraform/ter…
harness/harness-core-ui pull request #15172
Opened 2023-04-12 11:29 UTC by sonaligoyal-harness

…ragrunt steps

### Summary

#### Screenshots

<img width="1626" alt="Screenshot 2023-04-12 at 3 21 29 PM" src="https://user-images.githubusercontent.com/98508399/231444068-57d48edb-5920-438f-a566-20db7f0958dd.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-12 11:55 UTC, rameshx requested changes
Components like `EntityReference`, `ReferenceSelect`, etc. should not take a prop like `isInfraProvisionerSecretManager`. The prop should be generic.

2023-04-12 11:56 UTC, chetanvekariya-harness requested changes

2023-04-12 11:56 UTC, chetanvekariya-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
> +        isInfraProvisionerSecretManager={isInfraProvisionerSecretManager}
Common components should not be outside context aware. This prop is specific. We can pass common/generic prop that takes care of readonly part inside this component. That way, consumers will be free to implement their own logic for readonly state. 
Please rename prop name to something generic.

2023-04-12 12:17 UTC, chetanvekariya-harness requested changes

2023-04-12 12:17 UTC, chetanvekariya-harness commented on src/modules/10-common/components/EntityReference/EntityReference.tsx
> +    CDS_NOT_ALLOW_READ_ONLY_SECRET_MANAGER_TERRAFORM_TERRAGRUNT_PLAN &&
This FF logic also should be moved outside.

2023-04-25 10:17 UTC, satyam-harness approved these changes

2023-04-25 10:19 UTC, rameshx approved these changes

2023-04-25 10:19 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/TerraformPlan/TerraformPlan.tsx
> +                        </Text>
can be moved to a component to reuse

2023-04-25 10:23 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/TerraformPlan/TerraformPlan.tsx
> +                        </Text>
It was minor warning message. So didn't think of making a common one.
Should we make it ?

2023-04-25 10:37 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/TerraformPlan/TerraformPlan.tsx
> +                        </Text>
Not necessary. Ignore 🙂

2023-04-25 10:42 UTC, chetanvekariya-harness commented on src/modules/10-common/components/ReferenceSelect/ReferenceSelect.tsx
> +  isRecordDisabled?: (item: any) => boolean
any?

2023-04-25 10:42 UTC, chetanvekariya-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx
> +  isRecordDisabled?: (item: any) => boolean
any?

2023-04-25 10:42 UTC, chetanvekariya-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx
> +  isRecordDisabled?: (val?: any) => boolean
any?

2023-04-25 10:42 UTC, chetanvekariya-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
> +  isRecordDisabled?: (item: any) => boolean
any?

2023-04-25 10:42 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/TerraformPlan/TerraformPlan.tsx
> +                    renderRecordDisabledWarning={val => {
We should not take any argument here. We can directly render component,

2023-04-25 11:00 UTC, sonaligoyal-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx
> +  isRecordDisabled?: (item: any) => boolean
We have it is as any only for record in index file also.

2023-04-25 11:02 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/TerraformPlan/TerraformPlan.tsx
> +                    renderRecordDisabledWarning={val => {
How can we distinguish for not showing if no connector is readonly?

2023-04-25 11:11 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/TerraformPlan/TerraformPlan.tsx
> +                    renderRecordDisabledWarning={val => {
If it is readonly then only call this function. Is it no possible?

2023-04-25 11:13 UTC, chetanvekariya-harness commented on src/modules/10-common/components/EntityReference/EntityReference.tsx
> +      {renderRecordDisabledWarning?.(isMultiSelect ? isMultiSelectRecordDisabled : isRecordDisabled?.(selectedRecord))}
Call this render function only when flag is true. Is it possible to do?

2023-04-25 11:21 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/TerraformPlan/TerraformPlan.tsx
> +                    renderRecordDisabledWarning={val => {
yes, updating it

2023-04-25 11:31 UTC, sonaligoyal-harness commented on src/modules/10-common/components/EntityReference/EntityReference.tsx
> +      {renderRecordDisabledWarning?.(isMultiSelect ? isMultiSelectRecordDisabled : isRecordDisabled?.(selectedRecord))}
done

2023-04-25 11:58 UTC, chetanvekariya-harness approved these changes

2023-04-25 11:59 UTC, sonaligoyal-harness commented on src/modules/10-common/components/EntityReference/EntityReference.tsx
> +        renderRecordDisabledWarning}
sure

2023-04-25 12:11 UTC, rameshx submitted a review, later dismissed

2023-04-25 12:54 UTC, satyam-harness approved these changes

2023-04-25 13:24 UTC, sunnykesh-harness approved these changes

2023-04-25 18:21 UTC, merged