feat: [CET-1197]: CET notification wizard
harness/harness-core-ui pull request #15221
Opened 2023-04-18 12:19 UTC by guycastel

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-19 17:29 UTC, guycastel commented
retrigger jest

2023-04-20 04:55 UTC, abhinavrastogi-harness requested changes
Instead of moving components down, can we consider moving the ET module to the same layer as other major modules (75-et would be the correct layer)

2023-04-20 05:48 UTC, guycastel commented
@abhinavrastogi-harness Putting ET at 75-et was the plan but currently [it's used in 70-pipeline](https://github.com/harness/harness-core-ui/blob/5142071b533b0c78091edcd54bf3e1ee82dc2825/src/modules/70-pipeline/pages/execution/ExecutionErrorTrackingView/ExecutionErrorTrackingView.tsx) so has to be below unless there's another way.

2023-04-20 08:42 UTC, guycastel commented
retrigger cypress-cd

2023-04-20 08:42 UTC, guycastel commented
retrigger jest

2023-04-20 08:56 UTC, abhinavrastogi-harness approved these changes

2023-04-20 09:28 UTC, SahilKr24 approved these changes

2023-04-20 10:01 UTC, d1wilko approved these changes
LGTM

2023-04-20 10:03 UTC, deepesh-ui approved these changes

2023-04-20 10:03 UTC, kapilkumawat86 approved these changes

2023-04-20 10:03 UTC, jyotiarora-harness approved these changes

2023-04-20 13:33 UTC, cseverino789 approved these changes

2023-04-20 13:39 UTC, merged

2023-04-20 13:50 UTC, guycastel commented on src/modules/85-cv/components/Notifications/components/useSRMNotificationModal/useSRMNotificationModal.tsx
> +import Overview from '@et/components/Notifications/Steps/Overview'
On first iteration of this PR I moved `NotificationMethod` and `Overview` from `70-pipeline` to `60-et` because otherwise you can't use them in `60-et` (those are the components I need to pass to ET MFE).
It is no longer relevant since I ended up changing `60-et` to be `75-et` so the components can stay in `70-pipelines` and be used in `75-et`.
I hope this answers the question.

2023-04-20 13:51 UTC, guycastel commented on src/modules/70-pipeline/components/Notifications/NotificationTypeOptions.ts
Yes it was checked and tested.

2023-04-20 13:52 UTC, guycastel commented on src/modules/60-et/ErrorTracking.types.ts
> + * Copyright 2022 Harness Inc. All rights reserved.
Missed that...
Something should generate/update this section but I'm not sure what it is 🤔