feat: [CDS-58511]: digest for GAR
harness/harness-core-ui pull request #15223
Opened 2023-04-18 12:47 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-26 20:41 UTC, sahithikolichala submitted a review, later dismissed

2023-05-02 08:33 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactInterface.ts
>      repositoryName: string
Lets verify the artifact source template crud flow for GAR

2023-05-02 08:40 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +    case 'GoogleArtifactRegistry':
Lets use enum here --> ENABLED_ARTIFACT_TYPES.GoogleArtifactRegistry

ENABLED_ARTIFACT_TYPES.DockerRegistry

2023-05-02 08:51 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +  const useGetErrorText = () => defaultErrorText || staticErrorText
const defaultDigestError =  defaultTo(defaultErrorText, staticErrorText)

2023-05-02 08:54 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +  const useGetArtifactDigestResponse = (artifact: ArtifactType): any => {
Lets move this hook to a separate file

2023-05-02 09:10 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/GoogleArtifactRegistry/GoogleArtifactRegistry.tsx
> +    // const digest = isValueFixed(formData['digest'])
please remove

2023-05-02 09:12 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +    const {
This will not scale when we add 7 more artifacts here - >lets refactor it to make it more scalable as discussed on callParent 1 —> DockerArtifactDigestField

const { data, loading, refetch, error } = useMutateAsGet(useGetLastSuccessfulBuildForDocker, {
  queryParams: {
    imagePath: formik?.values?.imagePath,
    connectorRef: connectorRefValue,
    accountIdentifier: accountId,
    orgIdentifier,
    projectIdentifier
  },
  requestOptions: {
    headers: {
      'content-type': 'application/json'
    }
  },
  lazy: true,
  body: {
    tag: formik?.values?.tag?.value
  }
})

return (
	
	<ArtifactDigestFieldBase data={data} loading={loading} error={error} refetch={refetch} />
)






Parent 2 —> GarArtifactDigestField

 const {
      data: dataGar,
      loading: loadingGar,
      refetch: refetchGar,
      error: errorGar
    } = useMutateAsGet(useGetLastSuccessfulBuildForGoogleArtifactRegistry, {
      queryParams: {
        accountIdentifier: accountId,
        projectIdentifier,
        orgIdentifier,
        connectorRef: connectorRefValue,
        project: formik?.values?.spec?.project,
        region: formik?.values?.spec?.region,
        repositoryName: formik?.values?.spec?.repositoryName,
        package: formik?.values?.spec?.package
      },
      requestOptions: {
        headers: {
          'content-type': 'application/json'
        }
      },
      lazy: true,
      body: {
        version: formik?.values?.spec?.version
      }
    })

return (
	
	<ArtifactDigestFieldBase data={data} loading={loading} error={error} refetch={refetch} />
)




…..Parent 3,4,5,6



<ArtifactDigestFieldBase />

cc: @YounixM

2023-05-02 12:03 UTC, namanharness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactInterface.ts
>      repositoryName: string
Done

2023-05-02 12:12 UTC, namanharness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +    const {
Refactored the code , please review now

2023-05-03 06:10 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +  const useGetErrorText = defaultTo(defaultErrorText, staticErrorText)
please rename this --> useGetErrorText --> defaultDigestErrorMessage

2023-05-03 06:11 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
> +      case ENABLED_ARTIFACT_TYPES.GoogleArtifactRegistry:
can we pass this from the parent directly

2023-05-03 06:12 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/DockerRegistryArtifact/DockerRegistryArtifact.tsx
> +                  <DockerRegistryDigestFieldWrapper
Lets rename this to -> DockerArtifactDigestField

2023-05-03 06:13 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/DockerRegistryArtifact/DockerRegistryDigestFieldWrapper.tsx
> +export function DockerRegistryDigestFieldWrapper({
https://github.com/harness/harness-core-ui/pull/15223/files#r1183273723

2023-05-03 06:14 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/GoogleArtifactRegistry/GarDigestFieldWrapper.tsx
> +export function GarDigestFieldWrapper({
Lets rename this to -> GarArtifactDigestField

2023-05-03 06:21 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +import { useStrings } from 'framework/strings'
this will break eslint, please check

2023-05-03 06:25 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +  switch (selectedArtifact) {
we can move this to artifact digest field wrappers which we created - lets discuss this on call further

2023-05-03 06:25 UTC, namanharness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +import { useStrings } from 'framework/strings'
what alternative should we choose? 
should i pass this as well from parent?

2023-05-03 06:25 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +
https://github.com/harness/harness-core-ui/pull/15223/files#r1183280783

2023-05-03 09:58 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ArtifactImagePathTagView/ArtifactDigestField.tsx
>   */
Rename to BaseArtifactDigestField

2023-05-03 09:59 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/DockerRegistryArtifact/DockerRegistryDigestFieldWrapper.tsx
> + * that can be found in the licenses directory at the root of this repository, also available at
Lets rename the file so that it is consistent with the main component

2023-05-03 10:00 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/DockerRegistryArtifact/DockerRegistryDigestFieldWrapper.tsx
> +interface GarDigestFieldWrapperProps {
Rename to DockerArtifactDigestFieldProps

2023-05-03 10:05 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/DockerRegistryArtifact/DockerRegistryDigestFieldWrapper.tsx
> +  const digestDetails: ArtifactDigestWrapperDetails = {
Lets use useMemo to ensure digest details is not recreated

2023-05-03 10:13 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +  const values = { ...specValues }
Use produce for immutability

2023-05-03 12:04 UTC, namanharness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/DockerRegistryArtifact/DockerRegistryDigestFieldWrapper.tsx
> +  const digestDetails: ArtifactDigestWrapperDetails = {
skipping useMemo usage here as discussed since their is no heavy computation , adding a hook would be unnecessary

2023-05-04 07:06 UTC, samarth-sharma31 approved these changes

2023-05-04 07:48 UTC, rameshx commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +    getMultiTypeFromValue(version) !== MultiTypeInputType.RUNTIME
this is fine but you can do something like

```
[project, region, version,...].every(el => getMultiTypeFromValue(el) !==  MultiTypeInputType.RUNTIME)
```

2023-05-04 07:49 UTC, rameshx approved these changes

2023-05-04 07:55 UTC, namanharness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +    getMultiTypeFromValue(version) !== MultiTypeInputType.RUNTIME
Will take care of this next time , thanks @rameshx !

2023-05-04 09:01 UTC, samarth-sharma31 requested changes

2023-05-04 09:01 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/GoogleArtifactsRegistrySource/GoogleArtifactRegistrySource.tsx
> +    body: { version: versionValue, pipelineRuntimeYaml },
Please confirm this with @Abhishek-CDC , this should not be -> pipelineRuntimeYaml
instead it should be -> runtimeInputYaml

2023-05-04 10:14 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/GoogleArtifactsRegistrySource/GoogleArtifactRegistrySource.tsx
> +    body: { version: versionValue, pipelineRuntimeYaml },
Updated

2023-05-04 11:46 UTC, bhavya-sinha approved these changes

2023-05-05 06:30 UTC, merged