feat: [CDS-53660]: integrated grupid and artifactid with apis and beh…
harness/harness-core-ui pull request #15240
Opened 2023-04-18 21:41 UTC by sahithikolichala

…indff

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-19 06:02 UTC, pankajsingh-harness requested changes

2023-04-19 06:02 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/Nexus2ArtifactSource/Nexus2ArtifactSource.tsx
> +  const groupItemRenderer = memoize((item: { label: string }, { handleClick }) => (
Use the common component here also that use in Nexus2

2023-04-19 06:02 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/Nexus2ArtifactSource/Nexus2ArtifactSource.tsx
> +    <div key={item.label.toString()}>
Same as above

2023-04-19 06:02 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/NexusArtifactSource/NexusArtifactSource.tsx
> +  const groupItemRenderer = memoize((item: { label: string }, { handleClick }) => (
Same as above

2023-04-19 06:02 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/NexusArtifactSource/NexusArtifactSource.tsx
> +  const artifactIdItemRenderer = memoize((item: { label: string }, { handleClick }) => (
Same as above

2023-04-19 16:14 UTC, sahithikolichala commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus3Artifact/Nexus3Artifact.tsx
> +          fieldName: getString('common.subscriptions.tabs.plans')
oops somehow these changes got merged, will fix this

2023-04-19 22:52 UTC, sahithikolichala commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Nexus2Artifact/__test__/Nexus2Artifact.test.tsx
> -    const queryByNameAttribute = (name: string): HTMLElement | null => queryByAttribute('name', container, name)
i dont need to modify the test values are already updated

2023-04-20 05:05 UTC, pankajsingh-harness approved these changes

2023-04-20 05:05 UTC, pankajsingh-harness commented on src/modules/70-pipeline/strings/strings.en.yaml
> +  loadingGroupIds: Loading GroupIds...
Check if we can delete this now

2023-04-20 05:05 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/helper.ts
> +interface RequestOptions {
Check if we can use this from service index file.

2023-04-20 05:05 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/NexusArtifact/NexusArtifact.tsx
> +  } = useMutateAsGet(useGetGroupIds, {
Use the helper here also

2023-04-20 05:05 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/NexusArtifact/NexusArtifact.tsx
> +  } = useMutateAsGet(useArtifactIds, {
Same as above

2023-04-24 02:50 UTC, pankajsingh-harness approved these changes

2023-04-24 05:34 UTC, satyam-harness submitted a review, later dismissed

2023-04-25 04:10 UTC, sahithikolichala commented
retrigger jest

2023-04-25 14:26 UTC, YounixIO approved these changes

2023-04-25 14:26 UTC, merged