feat: [CDS-58027]: Added support for Env group at Env & Artifact card and Env Table view
harness/harness-core-ui pull request #15276
Opened 2023-04-20 03:54 UTC by Sagar-Rajput7

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-21 08:26 UTC, rameshx requested changes

2023-04-21 08:26 UTC, rameshx commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsSummaryV2/ServiceDetailDriftTable.tsx
> +  const RenderEnvName: Renderer<CellProps<ArtifactDeploymentDetail>> = ({ row }) => {
This should be defined outside

2023-04-21 08:26 UTC, rameshx commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsSummaryV2/ServiceDetailDriftTable.tsx
> +  const RenderLatestVersion: Renderer<CellProps<ArtifactDeploymentDetail>> = ({ row }) => {
define all cells outside

2023-04-21 08:26 UTC, rameshx commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsSummaryV2/ServiceDetailsSummaryV2.module.scss
> +      background: rgba(11, 11, 13, 0.1);
Do we have a color var for this?

2023-04-21 08:26 UTC, rameshx commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsSummaryV2/ServiceDetailsEnvView.tsx
> +const latestTimeAndArtifact = (data: ArtifactDeploymentDetail[] | undefined): ArtifactDeploymentDetail => {
```suggestion
const getLatestTimeAndArtifact = (data: ArtifactDeploymentDetail[] | undefined): ArtifactDeploymentDetail => {
```

2023-04-21 08:26 UTC, rameshx commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsSummaryV2/ServiceDetailsEnvView.tsx
> +  const dropDownOptions = React.useMemo(() => {
```suggestion
  const dropdownOptions = React.useMemo(() => {
```

2023-04-21 08:26 UTC, rameshx commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsSummaryV2/ServiceDetailsEnvView.tsx
> +    [envRefetch]
FYI, queryParams are not added to the dependencies

2023-04-25 14:12 UTC, rameshx approved these changes

2023-04-25 14:12 UTC, rameshx commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsSummaryV2/ServiceDetailDriftTable.tsx
> +    [getString]
missing dependencies

2023-04-25 14:12 UTC, rameshx commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsSummaryV2/ServiceDetailsSummaryV2.module.scss
> +  div[id='envGrpText'] {
nit
```suggestion
  #envGrpText {
```

2023-04-25 14:17 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/ServiceDetails/ServiceDetailsSummaryV2/ServiceDetailsSummaryV2.module.scss
> +  div[id='envGrpText'] {
Thanks will fix in the next pr.

2023-04-25 17:22 UTC, Eric761 approved these changes

2023-04-25 17:57 UTC, merged