feat: [code-213]: add useGenerate token hook
harness/harness-core-ui pull request #15330
Opened 2023-04-22 21:40 UTC by cjlee01

### Summary

Created a hook to generate api token for usage with harness for git scm 

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-22 21:45 UTC, cjlee01 commented
retrigger titlecheck

2023-04-24 17:33 UTC, cjlee01 commented on src/modules/10-common/navigation/MainNav/MainNav.tsx
> +  console.log(paths.toUser(params))
removed

2023-04-24 17:33 UTC, cjlee01 commented on configs/devServerProxy.config.js
> +  '/code-search': {
yeah will remove it @tan-nhu

2023-04-24 19:18 UTC, tan-nhu requested changes

2023-04-24 19:18 UTC, tan-nhu commented on src/modules/60-code/CodeApp.tsx
> +          setToken(err)
Show a toaster here

2023-04-24 19:34 UTC, sahithikolichala approved these changes

2023-04-24 19:55 UTC, tan-nhu approved these changes

2023-04-24 20:14 UTC, merged