fix: [CDS-59131]: added connectorRef field for container step
harness/harness-core-ui pull request #15520
Opened 2023-05-02 20:30 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

<img width="622" alt="Screen Shot 2023-05-02 at 1 30 20 PM" src="https://user-images.githubusercontent.com/57372986/235779039-a9e306d4-eef0-49e0-8a93-de76c2eccca2.png">

2023-05-02 20:45 UTC, sonaligoyal-harness requested changes
To enable allowed values support when this field is made runtime, ConnectorConfigureOptions component need to be added in the code

2023-05-02 20:49 UTC, sonaligoyal-harness commented on src/modules/75-cd/components/PipelineSteps/ContainerStep/OptionalConfiguration.tsx
> +          label={<Text color={Color.GREY_900}>{getString('connectors.title.harnessImageConnectorRef')}</Text>}
Nit: label can be added without providing any color and also width for this field looks inconsistent compared to other optional fields

2023-05-02 23:56 UTC, sahithikolichala commented
retrigger jest

2023-05-03 17:06 UTC, sonaligoyal-harness submitted a review, later dismissed

2023-05-03 17:12 UTC, sahithikolichala commented
retrigger jest

2023-05-03 23:07 UTC, sahithikolichala commented
worked on increasing coverage, current coverage report is
<img width="1347" alt="Screen Shot 2023-05-03 at 4 05 20 PM" src="https://user-images.githubusercontent.com/57372986/236069632-57ba1364-8722-451c-882d-1a3708883668.png">

2023-05-04 10:44 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/ContainerStep/OptionalConfiguration.tsx
> +          multiTypeProps={{ allowableTypes: [MultiTypeInputType.FIXED, MultiTypeInputType.RUNTIME] }}
Is `expression`  type not needed here? Some fields in the flow has `expression` support some don't.

2023-05-04 14:28 UTC, pankajsingh-harness approved these changes

2023-05-04 17:01 UTC, sonaligoyal-harness approved these changes

2023-05-04 17:15 UTC, pankajsingh-harness approved these changes

2023-05-04 17:19 UTC, sahithikolichala commented
retrigger cypress-rest

2023-05-04 17:29 UTC, sahithikolichala commented
retrigger cypress-pipeline

2023-05-04 19:01 UTC, sahithikolichala commented
retrigger cypress-pipeline

2023-05-05 05:06 UTC, merged