feat: [CDS-68201]: retry failed pipeline option with last failed, selective stage and entire pipline added
harness/harness-core-ui pull request #15598
Opened 2023-05-05 12:09 UTC by PratyushGar

### Summary

- Moved duration and startTime upon hover

| Before | After |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/100121280/236450812-b20f8de6-78cc-4ce9-9481-4aef42c98c2b.png) | ![image](https://user-images.githubusercontent.com/100121280/236450743-e789f804-d56b-4934-9246-37ef2bc72e0b.png) |

- Retry Failed pipeline option combined with re-run pipeline ( Repeat icon removed with split button )
![image](https://user-images.githubusercontent.com/100121280/236452323-7f84a470-5537-42f1-b7a4-d22635b97751.png)
1. Re-run from last stage will pre-select last stage
2. Selected Stages(s) --> Retry failed pipelines
3. Entire pipeline --> Re-run pipeline

https://user-images.githubusercontent.com/100121280/236453801-01b7ca78-8bed-45aa-a165-7747cdcc07cb.mov

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-05 12:30 UTC, rameshx requested changes

2023-05-05 12:30 UTC, rameshx commented on src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionHeader/ExecutionHeader.tsx
> +              <SplitButtonOption onClick={reRunPipeline} text={'Entire Pipeline'} />
add text to strings

2023-05-05 12:30 UTC, rameshx commented on src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionHeader/ExecutionHeader.tsx
> +  })
`memo` is not useful if defined inside, move this out and pass props

2023-05-05 12:35 UTC, udayvunnam commented
Is this only applicable on execution details page, how about execution ist page retry ?

2023-05-05 12:39 UTC, PratyushGar commented
> Is this only applicable on execution details page, how about execution ist page retry ?

I'll check wth UX team whether we want to add similar option in Kebab menu there, as we don't have re-run button there

2023-05-05 13:18 UTC, rameshx approved these changes

2023-05-05 13:18 UTC, rameshx commented on src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionHeader/ExecutionHeader.tsx
> +  getString: UseStringsReturn['getString']
Nit: no need to pass getString as a prop, hook can be used inside

2023-05-06 13:18 UTC, SagarRajput7 approved these changes

2023-05-06 13:19 UTC, Sagar-Rajput7 approved these changes

2023-05-08 09:12 UTC, PratyushGar commented
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/100121280/236785162-3a2a924f-0aca-4e9d-a979-35c9a095f1ea.png">
Coverage is low for existing files

2023-05-08 10:03 UTC, merged