feat: [CDS-68453]: added search for servicelisting
harness/harness-core-ui pull request #15606
Opened 2023-05-05 21:10 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-06 14:34 UTC, YounixIO submitted a review, later dismissed

2023-05-08 20:56 UTC, tan-nhu approved these changes

2023-05-08 21:02 UTC, mtran7 approved these changes

2023-05-09 04:37 UTC, pankajsingh-harness requested changes

2023-05-09 04:37 UTC, pankajsingh-harness commented on src/modules/75-cd/components/Services/ServicesListPage/ServicesListPage.tsx
> +                setSearchTerm(val)
We need to trim the value here otherwise spaces will be added in the searchTerm.

2023-05-09 16:36 UTC, pankajsingh-harness approved these changes

2023-05-09 16:40 UTC, sahithikolichala commented
retrigger cypress-pipeline

2023-05-09 16:41 UTC, sahithikolichala commented
retrigger cypress-pipeline

2023-05-09 17:23 UTC, sahithikolichala commented
retrigger cypress-rest

2023-05-09 22:32 UTC, sahithikolichala commented
retrigger cypress-rest

2023-05-10 09:11 UTC, YounixIO approved these changes

2023-05-10 09:11 UTC, merged