fix: [CDS-53020]: added local time for cron trigger
harness/harness-core-ui pull request #15671
Opened 2023-05-09 19:17 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

<img width="1053" alt="Screen Shot 2023-05-09 at 12 16 59 PM" src="https://github.com/harness/harness-core-ui/assets/57372986/efbc185d-4513-448d-a606-999168a63fd3">

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-09 23:25 UTC, devinder-harness approved these changes

2023-05-10 01:39 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/views/SchedulePanel.tsx
> +            {getString('triggers.schedulePanel.currentTime')}
@sahithikolichala as of now we have to make same changes in file `src/modules/72-triggers/components/steps/SchedulePanel/SchedulePanel.tsx` also as we have still not GA trigger refactor FF.

2023-05-10 01:41 UTC, pankajsingh-harness requested changes
Need to add same changes in `src/modules/72-triggers/components/steps/SchedulePanel/SchedulePanel.tsx` file also as we have not GA the  trigger refactoring FF till now

2023-05-10 20:44 UTC, mtran7 approved these changes

2023-05-10 20:49 UTC, tan-nhu commented on src/modules/72-triggers/components/steps/SchedulePanel/SchedulePanel.tsx
> +        <Layout.Horizontal flex>
`flex` is not needed here, as `Layout.Horizontal/Vertical` is already a flex container.

2023-05-10 20:49 UTC, tan-nhu approved these changes

2023-05-11 02:31 UTC, pankajsingh-harness approved these changes

2023-05-11 03:50 UTC, YounixIO approved these changes

2023-05-11 03:51 UTC, merged