feat: [PL-38708]: Using v2 API to fetch connectors list in select connector modal
harness/harness-core-ui pull request #15725
Opened 2023-05-12 05:22 UTC by avinashmadhwani02

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-16 16:17 UTC, tan-nhu approved these changes

2023-05-17 02:54 UTC, pankajsingh-harness requested changes

2023-05-17 02:54 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx
> -                  ...(version && { version })
This will remove filtering of Nexus2 & Nexus3 connectors. 
Please check this PR. https://github.com/harness/harness-core-ui/pull/14843
We need to add the support for version query param for connector list V2 API is this is removed from here.

For more details check: https://harness.atlassian.net/browse/CDS-53879

2023-05-17 02:54 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
> -  version?: string
This was added for https://harness.atlassian.net/browse/CDS-53879. This need not be removed

2023-05-17 02:54 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
> -    version,
Same as above.

2023-05-17 02:54 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx
> -  version?: string
This was added as part of https://harness.atlassian.net/browse/CDS-53879.
this need not to be removed.

2023-05-17 02:54 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx
> -  version,
Same as above

2023-05-17 02:54 UTC, pankajsingh-harness commented on src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
> -    version,
Same as above

2023-05-25 13:14 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx
> -                  ...(version && { version })
Passing `version` query param in V2 API, it's supported by backend now.

2023-05-25 14:28 UTC, abhinavrastogi-harness submitted a review, later dismissed

2023-05-25 15:18 UTC, Eric761 submitted a review, later dismissed

2023-05-25 16:38 UTC, pankajsingh-harness approved these changes

2023-05-26 14:29 UTC, pankajsingh-harness approved these changes

2023-05-27 04:37 UTC, harshilbits approved these changes

2023-05-27 13:14 UTC, vikrant-harness approved these changes

2023-05-27 14:14 UTC, vardanbansal-harness approved these changes

2023-05-28 03:10 UTC, merged