fix: [CDS-54939]: adding infrastructure to the executiondetails
harness/harness-core-ui pull request #15797
Opened 2023-05-16 00:19 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-16 17:47 UTC, sahithikolichala commented
trigger cypress-rest

2023-05-17 02:34 UTC, pankajsingh-harness commented on src/modules/70-pipeline/pages/execution/ExecutionPipelineView/ExecutionGraphView/ExecutionGraph/components/CD/CDInfo/CDInfo.tsx
> +            <Layout.Horizontal padding={{ right: 'medium', bottom: 'small', left: 'small' }}>
This can be moved to a component and used for environment & infrastructure both.

2023-05-17 02:42 UTC, pankajsingh-harness commented on src/modules/75-cd/components/CDStageDetails/CDStageDetails.tsx
> +              infrastructureId: get(stage, 'moduleInfo.cd.infraExecutionSummary.infrastructureIdentifier', null),
Don't this break the link if infrastructureId is null? Do we need we add check for this?

2023-05-17 02:42 UTC, pankajsingh-harness commented on src/modules/75-cd/components/CDStageDetails/CDStageDetails.tsx
> +              environmentIdentifier: get(stage, 'moduleInfo.cd.infraExecutionSummary.identifier', null),
Don't this break the link if environmentIdentifier is null? Do we need we add check for this?

2023-05-17 19:58 UTC, sahithikolichala commented on src/modules/75-cd/components/CDStageDetails/CDStageDetails.tsx
> +              infrastructureId: get(stage, 'moduleInfo.cd.infraExecutionSummary.infrastructureIdentifier', null),
no, infrastructureId is optional here 
https://github.com/harness/harness-core-ui/blob/develop/src/modules/10-common/interfaces/RouteInterfaces.ts#L186

2023-05-18 17:03 UTC, sahithikolichala commented
retrigger jest

2023-05-18 17:16 UTC, sahithikolichala commented
retrigger cypress-cv

2023-05-19 02:42 UTC, AshwinBhatkal-Harness requested changes
This is also breaking the UI on the right where the error message is shown. Can we please fix it

2023-05-19 02:42 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/CDStageDetails/CDStageDetails.tsx
> +              {gitOpsClusters.map(cluster => {
Can we check how this will scale when we are deploying to 10 clusters or more?

2023-05-19 02:43 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/CDStageDetails/CDStageDetails.tsx
> +              {gitOpsClusters.map(cluster => {
What about showing the infra details on the top left of the page where we currently show the environment details?

2023-05-19 23:09 UTC, sahithikolichala commented
@AshwinBhatkal-Harness  @pankajsingh-harness  the ui for gitops clusters looks like this now
<img width="1000" alt="Screen Shot 2023-05-19 at 2 24 59 PM" src="https://github.com/harness/harness-core-ui/assets/57372986/8aa2f191-0837-4c4b-9975-72ba4d91ab4f">
![Screen Shot 2023-05-19 at 2 25 30 PM](https://github.com/harness/harness-core-ui/assets/57372986/bff2eabb-8d5f-416a-a5a9-39ab19b2db21)

2023-05-22 19:07 UTC, sahithikolichala commented
@AshwinBhatkal-Harness  fixed the ux and it looks as this:
<img width="1726" alt="Screen Shot 2023-05-22 at 12 07 33 PM" src="https://github.com/harness/harness-core-ui/assets/57372986/b809a92a-bbae-4a7d-8e70-d74058a1d148">

2023-05-22 22:04 UTC, sahithikolichala commented
retrigger jest

2023-05-23 03:47 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/CDStageDetails/CDStageDetails.tsx
> +            {gitOpsClusters.length ? (
duplicate check

2023-05-23 03:47 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/CDStageDetails/CDStageDetails.tsx
> +                  <span className={css.primary6} style={{ textDecoration: 'underline dotted' }}>
Can we use Text component instead?

2023-05-23 04:25 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/CDStageDetails/CDStageDetails.tsx
> +          <div>
Do we not need a length check for infrastructure?

2023-06-22 20:04 UTC, closed without merging