fix: [CDS-69485]: Adds support to fetch resolved service yaml for artifactory artifact source for evaluation of repo format
harness/harness-core-ui pull request #15807
Opened 2023-05-16 11:16 UTC by samarth-sharma31

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-18 10:54 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2023-05-18 11:02 UTC, pankajsingh-harness requested changes

2023-05-18 11:04 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactConfigDrawer/ArtifactSourceTemplateDetails.tsx
> +                    <FormInput.Text
Also in YAML are we using name as identifier also for artifact created using template
```
- name: test-name
  identifier: test-name
  template:
    templateRef: account.testdocker
    versionLabel: v1
```

2023-05-18 11:58 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactConfigDrawer/ArtifactSourceTemplateDetails.tsx
> +                    <FormInput.Text
Summary of call with @pankajsingh-harness  - >

This does not remove the identifier field as we are passing it as empty string initially and then overriding the value with name field (existing behaviour only - no changes around this)

- name: test-name
  identifier: test-name
  template:
    templateRef: account.testdocker
    versionLabel: v1

Also this is the standard template node construct which is true for all kinds of templates - that's why the yaml structure is like this

I'll create a thread with PM and take the confirmation on the new input.

2023-05-19 09:42 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactConfigDrawer/ArtifactSourceTemplateDetails.tsx
> +                    <FormInput.Text
Have de coupled this change from this PR - we'll be taking that up in a follow up PR
Have a ticket to track this -> https://harness.atlassian.net/browse/CDS-69770

2023-05-19 09:54 UTC, pankajsingh-harness approved these changes

2023-05-19 09:56 UTC, AshwinBhatkal-Harness approved these changes

2023-05-19 10:39 UTC, merged