feat: [CDS-69023]: render auditEvent data from audit trail API under supplementary details
harness/harness-core-ui pull request #15818
Opened 2023-05-16 21:24 UTC by Eric761

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-17 05:44 UTC, abhinavrastogi-harness commented on src/modules/38-audit-trail/components/EventSummary/__tests__/EventSummary.test.tsx
> +    expect(drawer).toMatchSnapshot()
can we avoid large snapshots of the entire drawer and just use assertions instead?

2023-05-17 05:44 UTC, abhinavrastogi-harness commented on src/modules/38-audit-trail/strings/strings.en.yaml
> +  orgIdentifier: Org Identifier
I don't think we are supposed to shorten Organization to Org

2023-05-17 05:46 UTC, AshwinBhatkal-Harness approved these changes

2023-05-17 06:26 UTC, samarth-sharma31 commented on src/modules/38-audit-trail/components/EventSummary/EventSummary.tsx
> +            .map(auditData => (
Please check if we can do it in 1 iteration - instead of filtering and then using map again - we can directly use map and only return SupplementaryDetailRow when !!auditData.value

2023-05-17 06:27 UTC, samarth-sharma31 approved these changes

2023-05-17 11:20 UTC, avinashmadhwani02 commented on src/modules/38-audit-trail/utils/RequestUtil.tsx
> +export const getPipelineExecutionEventSupplementaryDetails = (
let's not put pipeline related things in audit trails. we can connect on a call and design this properly,

2023-05-17 11:21 UTC, avinashmadhwani02 requested changes
let's not put pipeline related things in audit trails. we can connect on a call and design this properly,
Audit trail should be independent of modules/ resources, that's why we have factory pattern,

2023-05-17 11:33 UTC, Eric761 commented
@avinashmadhwani02 Yes, I understand that the audit trail should be independent of modules/resources; for this reason, I only added the resourceSupplemenatryDetails field when registering a resource type and used it to display audit event data. I put this function getPipelineExecutionEventSupplementaryDetails in the audit module utils folder because it's used in two places: first, when registering resource types, and second, in the jest test case file, because if we put it in the pipeline module, we won't be able to import it from the lower module, as far as I know. 
However, if you believe this can be properly designed, we can connect on a call to discuss the same.

2023-05-17 16:33 UTC, Eric761 commented on src/modules/38-audit-trail/components/EventSummary/EventSummary.tsx
> +            .map(auditData => (
Made the change

2023-05-17 19:39 UTC, Eric761 commented on src/modules/38-audit-trail/strings/strings.en.yaml
> +  orgIdentifier: Org Identifier
This was decided by PM (@SudarshanPurohit )
https://harness.atlassian.net/browse/CDS-69023

2023-05-17 19:40 UTC, Eric761 commented on src/modules/38-audit-trail/components/EventSummary/__tests__/EventSummary.test.tsx
> +    expect(drawer).toMatchSnapshot()
Sure, added assertions instead of snapshot

2023-05-18 05:48 UTC, Eric761 commented on src/modules/38-audit-trail/strings/strings.en.yaml
> +  orgIdentifier: Org Identifier
Done

2023-05-18 07:28 UTC, avinashmadhwani02 approved these changes

2023-05-18 08:57 UTC, avinashmadhwani02 approved these changes

2023-05-18 09:23 UTC, avinashmadhwani02 approved these changes

2023-05-18 09:33 UTC, AshwinBhatkal-Harness approved these changes

2023-05-18 12:38 UTC, merged