fix: [CDS-69254]: setting pipelinestudio to yamlview if for any error
harness/harness-core-ui pull request #15816
Opened 2023-05-16 18:29 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-17 17:29 UTC, vikrant-harness commented on src/modules/70-pipeline/components/PipelineStudio/PipelineStudioInternal/PipelineStudioInternal.tsx
> +    // //         <React.Fragment>
commented code ?

2023-05-17 17:37 UTC, rameshx requested changes

2023-05-17 17:37 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/PipelineStudioInternal/PipelineStudioInternal.tsx
> +// import { Button, ButtonVariation, Container, Layout, Text } from '@harness/uicore'
remove

2023-05-17 17:37 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/PipelineStudioInternal/PipelineStudioInternal.tsx
> +// import { String } from 'framework/strings'
remove

2023-05-17 17:37 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/PipelineStudioInternal/PipelineStudioInternal.tsx
> +    // // }
remove commented code

2023-05-17 17:37 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/__tests__/PipelineStudio.test.tsx
> +  test.skip('should render error experience when there is error in js code', () => {
let's remove these tests instead of skipping and add a new test to assert the new behaviour

2023-05-17 18:28 UTC, PratyushGar commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
> +
Can we also show a toast so that the user know why he/she was redirected to the YAML view, as upon toggling it switches back to the YAML view which can be confusing - that whether the visual view is not supported ( in this case it goes to Visual and then to YAML encountering the error)

https://github.com/harness/harness-core-ui/assets/100121280/0afacc1a-b4dc-44ed-8d3b-1b13014c3823

2023-05-17 19:07 UTC, sahithikolichala commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
> +
yes @PratyushGar  we will show a toast to say the yaml is invalid
Ideally when the yaml is invalid, BE api to validate the yaml has to say it as invalid, If BE fixes this , toaster would show up the reason why the yaml is invalid

2023-05-22 22:07 UTC, sahithikolichala commented
@PratyushGar  modified the behavior and now it looks as this

https://github.com/harness/harness-core-ui/assets/57372986/9db73127-7baf-4927-84ef-e329d8ba3b92

2023-05-23 06:16 UTC, rameshx requested changes

2023-05-23 06:16 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
> +      // showError('not able to load pipeline studio')
please remove this commented line

2023-05-23 06:16 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/__tests__/PipelineStudio.test.tsx
> +// eslint-disable-next-line jest/no-disabled-tests
remove

2023-05-23 06:16 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/__tests__/PipelineStudio.test.tsx
> +  // eslint-disable-next-line jest/no-disabled-tests
this can be removed too

2023-05-23 06:16 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/__tests__/PipelineStudio.test.tsx
> +    expect(getByText('pipeline.advancedOptions')).toBeInTheDocument()
test name no longer matches what it tests

2023-05-23 06:16 UTC, rameshx commented on src/modules/70-pipeline/strings/strings.en.yaml
> +loadingErrorMsg: 'The pipeline yaml schema is invalid. please review the pipeline yaml in the pipeline studio’s yaml editor view to resolve.'
```suggestion
loadingErrorMsg: 'The pipeline yaml schema is invalid. Please review the pipeline yaml in the pipeline studio’s yaml editor view to resolve.'
```

2023-05-24 04:06 UTC, sahithikolichala commented
retrigger jest

2023-05-24 04:09 UTC, sahithikolichala commented
retrigger coverage

2023-05-24 04:18 UTC, sahithikolichala commented
retrigger titlecheck

2023-05-24 05:31 UTC, rameshx approved these changes

2023-05-24 05:51 UTC, PratyushGar approved these changes

2023-05-24 17:58 UTC, YounixIO approved these changes

2023-05-24 17:58 UTC, merged