feat:[CDS-52441]: add coverage for gcf steps gen 1/2
harness/harness-core-ui pull request #15824
Opened 2023-05-17 08:49 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-17 09:01 UTC, chetanvekariya-harness requested changes

2023-05-17 09:01 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GenTwo/DeployCloudFunctionTrafficShiftStep/__tests__/DeployCloudFunctionTrafficShiftStep.test.tsx
> +          timeout: RUNTIME_INPUT_VALUE,
Give trafficPercent here and assert on that.

2023-05-18 11:57 UTC, chetanvekariya-harness submitted a review, later dismissed

2023-05-18 11:57 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GenOne/__tests__/DeployCloudFunctionStepGenOne.test.tsx
> +    const fieldInput = queryByNameAttribute('spec.updateFieldMask', container)
Let's call this updateFieldMaskInput. We can change this in next PR.

2023-05-18 12:22 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GenOne/__tests__/DeployCloudFunctionStepGenOne.test.tsx
> +    const fieldInput = queryByNameAttribute('spec.updateFieldMask', container)
sure

2023-05-18 12:40 UTC, chetanvekariya-harness approved these changes

2023-05-19 05:46 UTC, samarth-sharma31 approved these changes

2023-05-19 06:03 UTC, merged