feat: [CET-1225]: CET active agents card in subscription page
harness/harness-core-ui pull request #15828
Opened 2023-05-17 11:14 UTC by guycastel

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-18 11:14 UTC, guycastel commented
retrigger titlecheck

2023-05-18 12:54 UTC, guycastel commented
retrigger jest

2023-05-18 14:20 UTC, ricksjames approved these changes

2023-05-18 16:38 UTC, tan-nhu submitted a review, later dismissed

2023-05-18 20:27 UTC, cseverino789 requested changes

2023-05-18 20:27 UTC, cseverino789 commented on src/modules/10-common/strings/strings.en.yaml
> +    whatIsActiveAgentTooltip: The agent actively monitors the Java applications for run-time exceptions, log events, and any custom events that are configured by the user.
We already have similar Strings for the Active Agent tool tip...

https://github.com/harness/harness-core-ui/blob/ce5e67c88c1fd56697ee3eeaa71ffb1752c40717/src/modules/10-common/strings/strings.en.yaml#LL587C35-L587C35

  cetAgentToolTip: An agent is an independent unit of software that you install on a host or in a container that tracks for errors continuously and sends the error tracking data to the Harness Platform.**

2023-05-23 08:01 UTC, guycastel commented
retrigger cypress-cv

2023-05-23 10:51 UTC, dhruvUpadhyay07 approved these changes

2023-05-23 13:25 UTC, merged