fix: [CDS-59590]: removed featureflag AZURE_WEBAPP_NG_JENKINS_ARTIFACTS
harness/harness-core-ui pull request #15844
Opened 2023-05-17 20:15 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-22 22:12 UTC, sahithikolichala commented
retrigger titlecheck

2023-05-23 04:04 UTC, sahithikolichala commented
retrigger titlecheck

2023-05-23 04:50 UTC, pankajsingh-harness requested changes

2023-05-23 04:50 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ServiceV2ArtifactsSelection.tsx
> -      AZURE_WEBAPP_NG_JENKINS_ARTIFACTS &&
Now `ENABLED_ARTIFACT_TYPES.Jenkins` need to be added in https://github.com/harness/harness-core-ui/blob/develop/src/modules/70-pipeline/components/ArtifactsSelection/ArtifactHelper.ts#L183.

2023-05-23 04:50 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ServiceV2ArtifactsSelection.tsx
> -      AZURE_WEBAPP_NG_JENKINS_ARTIFACTS &&
Also the FF need to be removed from featureFlag file.
https://github.com/harness/harness-core-ui/blob/develop/src/modules/10-common/featureFlags.ts#LL91C1-L91C1

2023-05-23 04:50 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactsSelection.tsx
> -      AZURE_WEBAPP_NG_JENKINS_ARTIFACTS &&
Now ENABLED_ARTIFACT_TYPES.Jenkins need to be added in https://github.com/harness/harness-core-ui/blob/develop/src/modules/70-pipeline/components/ArtifactsSelection/ArtifactHelper.ts#L183.

2023-05-23 16:42 UTC, closed without merging