SEI-1835: Maturity Modal quiz screen
harness/harness-core-ui pull request #15894
Opened 2023-05-22 07:24 UTC by sharath-levelops

### Summary

Update Quiz screen for Software Delivery Maturity Modal as suggested in new figma 

#### Screenshots
<img width="1792" alt="Screenshot 2023-05-22 at 12 52 33 PM" src="https://github.com/harness/harness-core-ui/assets/95604854/bdb5c0eb-658e-44d1-957d-ded24007e98e">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-27 07:44 UTC, sharath-levelops commented
retrigger typecheck

2023-06-02 13:05 UTC, abhinavrastogi-harness requested changes
There's a lot of basic design issues in the code. Lets discuss on the code walkthrough next week.

2023-06-02 13:05 UTC, abhinavrastogi-harness commented on src/modules/50-assessments/assets/CCM.svg
> +<svg width="20" height="18" viewBox="0 0 20 18" fill="none" xmlns="http://www.w3.org/2000/svg">
many issues in these svg files. 
see https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/1963262066/SVG+Guidelines+Best+Practices.

2023-06-02 13:05 UTC, abhinavrastogi-harness commented on src/modules/50-assessments/assets/CCM.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M1.56864 2.3791C1.56864 2.04773 1.83727 1.7791 2.16864 1.7791H7.16439C7.49576 1.7791 7.76438 1.51047 7.76438 1.1791C7.76438 0.847731 7.49576 0.579102
you have duplicated the same SVG with different colors. instead set fill to `currentColor` and use css to change colors.

2023-06-02 13:05 UTC, abhinavrastogi-harness commented on src/modules/50-assessments/components/AssessmentOverview/AssessmentOverview.tsx
> +                <img src={`https://logo.clearbit.com/${companyName}?size=14`} alt="" width={16} height={16} />
please dont hotlink third-party images directly into Harness. we are an enterprise product.
security and licensing is a very serious issue.

2023-06-02 13:05 UTC, abhinavrastogi-harness commented on src/modules/50-assessments/components/AssessmentOverview/__tests__/AssessmentOverview.test.tsx
> +// eslint-disable-next-line jest-no-mock
dont disable eslint rules. they are added for a reason.
`useParams` doesn't need to be mocked. wrap your component in `TestWrapper` to get the same behaviour for free.

2023-06-02 13:05 UTC, abhinavrastogi-harness commented on src/modules/50-assessments/components/AssessmentOverview/__tests__/AssessmentOverview.test.tsx
> +jest.mock('framework/strings', () => ({
this is already the default behaviour. remove this.

2023-06-02 13:05 UTC, abhinavrastogi-harness commented on src/modules/50-assessments/components/AssessmentOverview/__tests__/AssessmentOverview.test.tsx
> +    expect(getByTestId('page-spinner')).toBeInTheDocument()
just checking the loader is not a useful test. what about the content of the page?

2023-06-05 09:51 UTC, sharath-levelops commented on src/modules/20-rbac/strings/strings.en.yaml
> -  invite: Invite
Fixed https://github.com/harness/harness-core-ui/pull/15894/commits/4b3d237663ea29ccd069d01f02e19fd33a9ccb8a

2023-06-08 15:15 UTC, sharath-levelops commented on src/modules/50-assessments/components/AssessmentOverview/__tests__/AssessmentOverview.test.tsx
> +jest.mock('framework/strings', () => ({
wrapped with `TestWrapper`

2023-06-08 15:15 UTC, sharath-levelops commented on src/modules/50-assessments/components/AssessmentOverview/__tests__/AssessmentOverview.test.tsx
> +// eslint-disable-next-line jest-no-mock
Wrapped with `TestWrapper`

2023-06-08 15:16 UTC, sharath-levelops commented on src/modules/20-rbac/RouteDestinations.tsx
> +    [PermissionIdentifier.INVITE_USER]: <String stringID="common.invite" />
Reverted

2023-06-08 19:30 UTC, sharath-levelops commented on src/modules/50-assessments/components/AssessmentOverview/AssessmentOverview.tsx
> +                <img src={`https://logo.clearbit.com/${companyName}?size=14`} alt="" width={16} height={16} />
Since the assessment can take up in any company, we need to display the respective logo. Wei Guo, suggested me to use https://dashboard.clearbit.com/docs?ref=clearbit-blog.ghost.io#logo-api to fetch the icons for all the companies

2023-06-08 19:31 UTC, sharath-levelops commented on src/modules/50-assessments/assets/CCM.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M1.56864 2.3791C1.56864 2.04773 1.83727 1.7791 2.16864 1.7791H7.16439C7.49576 1.7791 7.76438 1.51047 7.76438 1.1791C7.76438 0.847731 7.49576 0.579102
We are wrapping the svg within `img` tag. So, I could not update the color of the svg using `currentColor`. Any suggestion how can I achieve it?

2023-06-09 06:54 UTC, sharath-levelops commented on src/modules/50-assessments/assets/CCM.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M1.56864 2.3791C1.56864 2.04773 1.83727 1.7791 2.16864 1.7791H7.16439C7.49576 1.7791 7.76438 1.51047 7.76438 1.1791C7.76438 0.847731 7.49576 0.579102
Created a ticket to consume after we push the icon to uicore
https://harness.atlassian.net/browse/SEI-2140

2023-06-09 06:54 UTC, sharath-levelops commented on src/modules/50-assessments/assets/CCM.svg
> +<svg width="20" height="18" viewBox="0 0 20 18" fill="none" xmlns="http://www.w3.org/2000/svg">
Will be addressed as part of https://harness.atlassian.net/browse/SEI-2140

2023-06-09 12:16 UTC, abhinavrastogi-harness commented on src/stringTypes.ts
> +  'assessments.yourTopOpportunities': string
all assessment strings can be moved to the assessment module strings.yaml file

2023-06-09 12:16 UTC, abhinavrastogi-harness approved these changes

2023-06-09 12:21 UTC, sharath-levelops commented on src/stringTypes.ts
> +  'assessments.yourTopOpportunities': string
I have added in [50-assessments/strings/string.en.yaml](src/modules/50-assessments/strings/strings.en.yaml), this file got updated automatically.

2023-06-09 14:21 UTC, harshilbits commented on src/modules/50-assessments/components/ImproveMaturity/ImproveMaturity.tsx
> +    if (!values?.questionLevelMaturityList) return
Move the logic from line 68 to 73 to utils

2023-06-11 13:01 UTC, sharath-levelops commented on src/modules/50-assessments/components/AssessmentResults/components/ResultTable/ResultTable.utils.tsx
> +export const getWeightageChartOptions = (weightage: number): Highcharts.Options => {
Addressed

2023-06-11 13:02 UTC, sharath-levelops commented on src/modules/50-assessments/components/ImproveMaturity/ImproveMaturity.tsx
> +    const selectedCapabilites = tableData.filter(questionMaturity => questionMaturity.selected)
Addressed

2023-06-11 13:02 UTC, sharath-levelops commented on src/modules/50-assessments/components/ImproveMaturity/ImproveMaturity.tsx
> +    if (!values?.questionLevelMaturityList) return
Addressed

2023-06-12 04:47 UTC, harshilbits approved these changes

2023-06-12 05:50 UTC, sharath-levelops commented
retrigger cypress-rest

2023-06-12 06:49 UTC, abhinavrastogi-harness approved these changes

2023-06-12 06:51 UTC, harshilbits approved these changes

2023-06-12 07:11 UTC, sharath-levelops commented
retrigger jest

2023-06-12 07:12 UTC, sharath-levelops commented
retrigger coverage

2023-06-12 07:42 UTC, sharath-levelops commented
retrigger jest

2023-06-12 07:43 UTC, sharath-levelops commented
retrigger cypress-cv

2023-06-12 08:53 UTC, merged