fix: [CI-7974]: V1 simplified yaml bugbash fixes for triggers and inputsets
harness/harness-core-ui pull request #15896
Opened 2023-05-22 07:30 UTC by shaurya-harness

### Summary

V1 simplified yaml bugbash fixes for triggers and inputsets

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-22 08:58 UTC, d1wilko requested changes
Some small comments but coming together nice

I did notice that the 3 trigger wizard files have the same code copied - should some of it be broken into a util or something? - I don't feel too strongly about that so will leave it up to you :)

2023-05-22 08:58 UTC, d1wilko commented on src/modules/70-pipeline/components/InputSetSelector/InputSetSelector.tsx
> +  isV1simplifiedYaml?: boolean
this is nitpicking but should this have a capital S in simplified?

2023-05-22 08:58 UTC, d1wilko commented on src/modules/70-pipeline/pages/inputSet-list/InputSetList.tsx
> +      (isSimplifiedYAMLEnabled(module, CI_YAML_VERSIONING) && isEmpty(pipelineInputs?.inputs))
was removing the `!` before `isEmpty(` on purpose? - cool if it is, but seems to change the logic quite a bit.

2023-05-22 08:58 UTC, d1wilko commented on src/modules/70-pipeline/pages/inputSet-list/InputSetList.tsx
> +  }, [template, pipelineInputs])
this feels like confusing code - maybe it could be simplified something like
```
useEffect(() => {
    const condition = 
        (!isSimplifiedYAMLEnabled(module, CI_YAML_VERSIONING) && !template?.data?.inputSetTemplateYaml) ||
        (isSimplifiedYAMLEnabled(module, CI_YAML_VERSIONING) && isEmpty(pipelineInputs?.inputs));

    setPipelineHasRuntimeInputs(!condition);
  }, [template, pipelineInputs]);
  ```

2023-05-22 14:01 UTC, shaurya-harness commented on src/modules/70-pipeline/components/InputSetSelector/InputSetSelector.tsx
> +  isV1simplifiedYaml?: boolean
yeah, let me add that

2023-05-22 14:02 UTC, shaurya-harness commented on src/modules/70-pipeline/pages/inputSet-list/InputSetList.tsx
> +      (isSimplifiedYAMLEnabled(module, CI_YAML_VERSIONING) && isEmpty(pipelineInputs?.inputs))
yes it's intentional, the old evaluation caused a bug

2023-05-22 14:03 UTC, shaurya-harness commented on src/modules/70-pipeline/pages/inputSet-list/InputSetList.tsx
> +  }, [template, pipelineInputs])
sure, can change that accordingly

2023-05-22 14:05 UTC, shaurya-harness commented
> Some small comments but coming together nice
> 
> I did notice that the 3 trigger wizard files have the same code copied - should some of it be broken into a util or something? - I don't feel too strongly about that so will leave it up to you :)

yeah I noticed that too, not sure why the triggers team has that kind of a setup although they reuse webhook trigger for scheduled trigger. will take this up with them @d1wilko

2023-05-22 14:35 UTC, d1wilko approved these changes
LGTM

2023-05-23 08:48 UTC, pankajsingh-harness approved these changes

2023-05-23 09:53 UTC, merged