feat: [PL-38933]: Favourites initial commit
harness/harness-core-ui pull request #15905
Opened 2023-05-22 10:50 UTC by avinashmadhwani02

### Summary

figma - https://www.figma.com/file/H5adZ2kwJcyhM5U62AttOu/Favorites?type=design&node-id=803-189536&t=SipbJI3hYeJNXl4j-0

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-30 10:09 UTC, sunnykesh-harness approved these changes

2023-05-30 12:37 UTC, abhinavrastogi-harness requested changes

2023-05-30 12:37 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/FavoriteStar/FavoriteStar.tsx
> +  orgIdentifier?: string
a better interface could be:
```
resource: {
    id: string
    type: ...
    scope?: {
        projectIdentifier?: string
        orgIdentifier?: string
    }
}
```

2023-05-30 12:37 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/FavoriteStar/FavoriteStar.tsx
> +      showError(getString('common.previousActionInProgress'))
no need for a toast here.. just return silently

2023-06-01 10:44 UTC, avinashmadhwani02 commented on src/modules/10-common/components/FavoriteStar/FavoriteStar.tsx
> +  orgIdentifier?: string
done

2023-06-01 10:44 UTC, avinashmadhwani02 commented on src/modules/10-common/components/FavoriteStar/FavoriteStar.tsx
> +      showError(getString('common.previousActionInProgress'))
done

2023-06-01 15:38 UTC, sunnykesh-harness approved these changes

2023-06-01 15:41 UTC, merged