feat:[CDS-52441]: add coverage for gcf service spec
harness/harness-core-ui pull request #15922
Opened 2023-05-23 06:30 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-25 08:58 UTC, chetanvekariya-harness requested changes

2023-05-25 08:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helper.ts
> +export const pipelineContextKubernetes = {
Why is this here ? There is nothing related Kubernetes that we need to test.

2023-05-25 08:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helper.ts
> +export const pipelineContextECSManifests = {
Same as above..

2023-05-25 08:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/GoogleCloudFunctionServiceSpec.test.tsx
> +    const gcfFunctionAliasDefinitionBranchInput = queryByNameAttribute(
Why this kind of name? We do not have such manifest type in GCF.

2023-05-25 08:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helperUtils.ts
> +/*
rename file to `helper.ts`

2023-05-25 08:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helperUtils.ts
> +      manifest: {
We do not need to test multiple but same manifests. Testing one is enough. Moreover, GCF does not allow multiple manifests, I guess.

2023-05-25 09:33 UTC, chetanvekariya-harness commented on jest.config.js
> +    'src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/**/*.{ts,tsx}',
Remove this.

2023-05-25 09:35 UTC, namanharness commented on jest.config.js
> +    'src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/**/*.{ts,tsx}',
done

2023-05-25 09:35 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helperUtils.ts
> +      manifest: {
done

2023-05-25 09:35 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helperUtils.ts
> +/*
done

2023-05-25 09:35 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/GoogleCloudFunctionServiceSpec.test.tsx
> +    const gcfFunctionAliasDefinitionBranchInput = queryByNameAttribute(
yes , updated

2023-05-25 09:35 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helper.ts
> +export const pipelineContextECSManifests = {
removed

2023-05-25 09:35 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helper.ts
> +export const pipelineContextKubernetes = {
removed

2023-05-25 11:04 UTC, chetanvekariya-harness requested changes

2023-05-25 15:40 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helper.ts
> +      useFromStage: {
i think its not needed here since its a propagated stage? can you please confirm?

2023-05-26 09:32 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helper.ts
> +      serviceDefinition: {
added

2023-05-26 09:32 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helper.ts
> +      serviceRef: 'Service_1',
added

2023-05-26 09:32 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helper.ts
> +      serviceDefinition: {
added

2023-05-26 09:44 UTC, chetanvekariya-harness approved these changes

2023-05-26 09:44 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helper.ts
> +export const updateStageArgGcfFunctionAliasDefinition = {
These names are wrong...
updateStageArgGCFGenOneDefinition OR updateStageArgGoogleCloudFunctionGenOneDefinition.
There is nothing call `AliasDefinition` in GCF. It was in Lambda.

2023-05-26 11:19 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/helper.ts
> +export const updateStageArgGcfFunctionAliasDefinition = {
Sure

2023-05-26 11:28 UTC, sonaligoyal-harness approved these changes

2023-05-26 12:06 UTC, chetanvekariya-harness approved these changes

2023-05-26 12:32 UTC, Sagar-Rajput7 approved these changes

2023-05-26 12:34 UTC, vikrant-harness approved these changes

2023-05-26 13:06 UTC, merged