feat: [CCM-12557]: replaced CENG_ENABLED flag with licensing information
harness/harness-core-ui pull request #15949
Opened 2023-05-24 11:28 UTC by rishik30

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-12 09:54 UTC, avinashmadhwani02 submitted a review, later dismissed

2023-07-14 01:14 UTC, devinder-harness requested changes

2023-07-14 01:14 UTC, devinder-harness commented on src/modules/10-common/pages/welcome/WelcomePageV2.tsx
>          chaos: true
this should not be driven by license

2023-07-14 06:34 UTC, rishik30 commented on src/modules/10-common/pages/welcome/WelcomePageV2.tsx
>          chaos: true
done

2023-07-14 07:40 UTC, avinashmadhwani02 submitted a review, later dismissed

2023-07-14 08:20 UTC, devinder-harness approved these changes

2023-07-14 15:16 UTC, devinder-harness approved these changes

2023-07-17 07:48 UTC, avinashmadhwani02 approved these changes

2023-07-18 11:42 UTC, merged