feat: [CDS-69800]: Show trigger status and message in activity history page
harness/harness-core-ui pull request #15964
Opened 2023-05-25 10:54 UTC by sonaligoyal-harness

### Summary

#### Screenshots

<img width="461" alt="Screenshot 2023-05-25 at 4 19 35 PM" src="https://github.com/harness/harness-core-ui/assets/98508399/777bc3b5-eb9b-41f5-a48d-cf506584638f">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-25 11:41 UTC, chetanvekariya-harness approved these changes

2023-05-25 12:14 UTC, PratyushGar approved these changes

2023-05-26 06:38 UTC, pankajsingh-harness requested changes

2023-05-26 06:38 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/TriggerLandingPage/TriggerActivityHistoryPage/TriggerActivityList.tsx
> +          {capitalize(data?.message?.split('_').join(' '))}
Do not do this processing in UI. Show the message as it is. Id need BE should make this change.

2023-05-31 08:59 UTC, pankajsingh-harness approved these changes

2023-05-31 09:15 UTC, Eric761 approved these changes

2023-06-02 06:11 UTC, YounixIO approved these changes

2023-06-02 06:12 UTC, merged