fix: [CDS-69873]: logs auto closing when blob call is made
harness/harness-core-ui pull request #15970
Opened 2023-05-25 17:31 UTC by vikrant-harness

### Summary

- toggled manually updated state in the updateSection reducer action 

#### Screenshots

https://github.com/harness/harness-core-ui/assets/106532291/e0530595-900c-4a73-8e5c-2ebab915ca64

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-25 17:38 UTC, Eric761 submitted a review, later dismissed

2023-05-25 17:45 UTC, AshwinBhatkal-Harness approved these changes

2023-05-25 17:45 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2023-05-25 18:22 UTC, PratyushGar submitted a review, later dismissed

2023-05-26 04:50 UTC, chetanvekariya-harness approved these changes

2023-05-26 06:20 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2023-05-26 06:21 UTC, rameshx submitted a review, later dismissed

2023-05-26 06:25 UTC, PratyushGar approved these changes

2023-05-26 06:37 UTC, PratyushGar submitted a review, later dismissed

2023-05-26 06:38 UTC, sonaligoyal-harness approved these changes

2023-05-26 06:43 UTC, rameshx requested changes

2023-05-26 06:43 UTC, rameshx commented on src/modules/70-pipeline/components/LogsContent/LogsState/actions.ts
> +        dispatch({ type: ActionType.ToggleSection, payload })
the action type that is dispatched is different from the newly added type `ActionType.UpdateManuallyToggled`

2023-05-26 06:54 UTC, rameshx approved these changes

2023-05-26 07:33 UTC, AshwinBhatkal-Harness approved these changes

2023-05-26 08:01 UTC, YounixIO approved these changes

2023-05-26 08:01 UTC, merged