feat: [CDS-69868]: add AccordionTab support to DeploySetup Shell
harness/harness-core-ui pull request #15992
Opened 2023-05-28 08:22 UTC by PratyushGar

### Summary

Changes behind FF `CDS_PIPELINE_STUDIO_UPGRADES`

- Added Accordion Tab support in CD - DeployStageSetupShell
- Moved error strip from component level to parent stageSetupShell

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-29 12:47 UTC, PratyushGar commented on src/modules/10-common/components/NameIconHeader/NameIconHeader.tsx
> +export default NameIconHeader
This will be imported by all setupShell (CD,Build,Approval,FF,STO)

2023-05-29 13:45 UTC, PratyushGar commented on src/modules/10-common/components/NameIconHeader/NameIconHeader.tsx
> +        {getString('common.stage')}: {name}
Thanks, addressed

2023-05-29 13:53 UTC, srdjan-harness approved these changes

2023-05-29 15:47 UTC, srdjan-harness requested changes

2023-05-29 15:47 UTC, srdjan-harness commented on src/modules/75-cd/components/PipelineStudio/DeployStageSetupShell/DeployStageSetupShell.tsx
> +    return `${getString('common.stage')}: ${stageName} }`
last curly bracket is not needed

2023-05-30 07:03 UTC, PratyushGar commented on src/modules/75-cd/components/PipelineStudio/DeployStageSetupShell/DeployStageSetupShell.tsx
> +    return `${getString('common.stage')}: ${stageName} }`
Thanks, updated

2023-05-30 07:04 UTC, satyam-harness approved these changes

2023-05-30 07:33 UTC, bhavya-sinha approved these changes

2023-05-30 08:05 UTC, srdjan-harness approved these changes

2023-05-30 08:26 UTC, vikrant-harness approved these changes

2023-05-30 08:33 UTC, merged