fix: [CI-7615]: maintain running status for background step node in a step group for a running stage
harness/harness-core-ui pull request #16038
Opened 2023-05-30 15:09 UTC by shaurya-harness

### Summary

maintain running status for background step node in a step group for a running stage

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-31 08:26 UTC, PratyushGar approved these changes

2023-05-31 08:47 UTC, d1wilko requested changes
1 suggestion - otherwise looking good :)

2023-05-31 08:47 UTC, d1wilko commented on src/modules/70-pipeline/utils/executionUtils.ts
> +}
this feels quite complicated - I feel it could be simplified a bit like

```
const getGroupSeperatedRunningIdentifiers = (
  nodeMap: { [key: string]: ExecutionNode },
  runningStageStepIdentifiers: string[]
): string[] => {
  const groupIdentifiers: string[] = Object.values(nodeMap)
    .filter(val => val.stepType === StepNodeType.STEP_GROUP && val.identifier)
    .map(val => val.identifier);

  if (groupIdentifiers.length === 0) return runningStageStepIdentifiers;

  return runningStageStepIdentifiers
    .filter(identifier =>
      groupIdentifiers.some(groupIdentifier =>
        identifier.includes(groupIdentifier) && identifier.replace(`${groupIdentifier}_`, '')
      )
    );
}
```

2023-05-31 08:49 UTC, shaurya-harness commented on src/modules/70-pipeline/utils/executionUtils.ts
> +}
sure @d1wilko , will update. Thanks

2023-05-31 09:44 UTC, shaurya-harness commented on src/modules/70-pipeline/utils/executionUtils.ts
> +}
the filter condition is not working properly here @d1wilko , the identifier does not get replaced

2023-05-31 10:05 UTC, shaurya-harness commented on src/modules/70-pipeline/utils/executionUtils.ts
> +}
I have cleaned up the rest

2023-05-31 10:14 UTC, PratyushGar approved these changes

2023-06-01 08:40 UTC, d1wilko approved these changes
LGTM

2023-06-02 05:31 UTC, merged