feat: [CDS-69584]: Add status and errors details dialog for trigger on triggers list page
harness/harness-core-ui pull request #16073
Opened 2023-05-31 15:18 UTC by srdjan-harness

### Summary

- Display Success and Failed status
- When status is Failed show tooltip with messages list (cropped messages) and button "Click to view error details"
- When click on "Click to view error details" open error details modal

#### Screenshots

Uploading Trigger status and tooltip.mov…

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-31 17:49 UTC, tan-nhu commented on src/modules/72-triggers/pages/triggers/views/subviews/TriggerStatusCell.tsx
> +  const renderTooltip = () => {
To optimize a bit, this can be wrapped in a useCallback hook

2023-05-31 17:53 UTC, tan-nhu commented on src/modules/72-triggers/pages/triggers/views/subviews/WarningTooltip.tsx
> +      <Text color={Color.BLUE_400} onClick={onClick} style={{ cursor: 'pointer' }}>
Use Button, onClick on a Text breaks accessibility.

`<Button text="Link 1" variation={ButtonVariation.LINK} />`

2023-06-01 06:07 UTC, PratyushGar submitted a review, later dismissed

2023-06-01 16:32 UTC, srdjan-harness commented
retrigger cypress-rest

2023-06-02 13:33 UTC, srdjan-harness commented
retrigger coverage

2023-06-02 15:27 UTC, tan-nhu submitted a review, later dismissed

2023-06-02 15:37 UTC, PratyushGar submitted a review, later dismissed

2023-06-02 16:52 UTC, vardanbansal-harness approved these changes

2023-06-05 07:23 UTC, sonaligoyal-harness submitted a review, later dismissed

2023-06-05 10:59 UTC, abhinavrastogi-harness requested changes

2023-06-05 10:59 UTC, abhinavrastogi-harness commented on src/modules/72-triggers/pages/triggers/views/subviews/TriggerStatusCell.tsx
> +        errorDeatailsText={getString('common.viewErrorDetails')}
spelling of `errorDeatailsText` is wrong

2023-06-05 10:59 UTC, abhinavrastogi-harness commented on src/modules/72-triggers/pages/triggers/views/subviews/WarningTooltip.tsx
> +  errorDeatailsText: string
spelling

2023-06-05 10:59 UTC, abhinavrastogi-harness commented on src/modules/72-triggers/pages/triggers/views/subviews/WarningTooltip.tsx
> +/*
why does this need to be a separate component?

2023-06-05 10:59 UTC, abhinavrastogi-harness commented on src/modules/72-triggers/pages/triggers/views/subviews/WarningTooltip.tsx
> +interface WarningTooltipProps {
this is not a good interface for a re-usable component.. I think you can just directly render the content wherever needed

2023-06-05 10:59 UTC, abhinavrastogi-harness commented on src/modules/72-triggers/pages/triggers/views/subviews/__tests__/TriggerStatus.test.tsx
> +    expect(container).toMatchSnapshot()
please use assertions instead of snapshots to validate render results

2023-06-05 10:59 UTC, abhinavrastogi-harness commented on src/modules/72-triggers/pages/triggers/views/subviews/useTriggerStatusErrorModal/useTriggerStatusErrorModal.tsx
> +  const [showModal, hideModal] = useModalHook(
use `<ModalDialog>` component instead of `useModalHook` as this is deprecated

2023-06-07 19:23 UTC, srdjan-harness commented
retrigger jest
retrigger coverage

2023-06-07 19:23 UTC, srdjan-harness commented
retrigger coverage

2023-06-07 22:05 UTC, tan-nhu approved these changes

2023-06-08 10:05 UTC, abhinavrastogi-harness approved these changes

2023-06-08 10:05 UTC, merged