fix: [CDS-70771]: fixed the selection of stages in stageselect dropdown
harness/harness-core-ui pull request #16080
Opened 2023-05-31 20:04 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

https://github.com/harness/harness-core-ui/assets/57372986/2726851d-9f4f-4e6b-8b3b-9ab975972871

2023-05-31 20:12 UTC, rameshx submitted a review, later dismissed

2023-05-31 21:22 UTC, PratyushGar approved these changes

2023-05-31 22:42 UTC, sahithikolichala commented
retrigger titlecheck

2023-06-01 05:09 UTC, vikrant-harness approved these changes

2023-06-01 05:34 UTC, pankajsingh-harness submitted a review, later dismissed

2023-06-01 05:45 UTC, tan-nhu submitted a review, later dismissed

2023-06-01 06:05 UTC, PratyushGar approved these changes

2023-06-01 06:05 UTC, PratyushGar approved these changes

2023-06-01 16:58 UTC, sahithikolichala commented
retrigger jest

2023-06-02 04:18 UTC, pankajsingh-harness requested changes
This fix will not work. We discussed the fix here https://github.com/harness/harness-core-ui/pull/16083/commits/9cc9513de0277f5e07ef247ac71c2ba56498aef7.

2023-06-02 04:39 UTC, pankajsingh-harness approved these changes

2023-06-02 10:31 UTC, YounixIO approved these changes

2023-06-02 10:31 UTC, merged