fix: [CDS-69814]: modified service api call to take yaml
harness/harness-core-ui pull request #16082
Opened 2023-05-31 23:27 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-01 19:01 UTC, tan-nhu approved these changes

2023-06-01 19:07 UTC, cjlee01 approved these changes

2023-06-02 03:39 UTC, pankajsingh-harness commented on src/modules/75-cd/components/PipelineSteps/DeployServiceStep/NewEditServiceModal.tsx
> +    yaml: JSON.stringify({
`JSON.stringify` will not convert the value to `yaml`. Use `yamlStringify` from `src/modules/10-common/utils/YamlHelperMethods.ts`

2023-06-02 03:40 UTC, pankajsingh-harness requested changes
JSON.stringify will not convert the value to yaml. Use yamlStringify from src/modules/10-common/utils/YamlHelperMethods.ts

2023-06-02 04:52 UTC, pankajsingh-harness approved these changes

2023-06-02 13:10 UTC, sahithikolichala commented
retrigger jest

2023-06-02 13:36 UTC, sahithikolichala commented
retrigger jest

2023-06-02 13:59 UTC, merged