fix: [CDS-69376]: improved error message for GCR and ECR connectors
harness/harness-core-ui pull request #16118
Opened 2023-06-02 00:05 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LI
<img width="725" alt="Screen Shot 2023-06-01 at 4 59 52 PM" src="https://github.com/harness/harness-core-ui/assets/57372986/d69520b2-4882-4a88-8228-3c34658c65a5">
CENSE_AGREEMENT.md)

2023-06-02 19:06 UTC, sahithikolichala commented
retrigger titlecheck

2023-06-02 20:45 UTC, cjlee01 approved these changes

2023-06-02 20:56 UTC, cjlee01 commented
![alt screenshot]
(https://i.imgur.com/WdBMIcZ.png "pr creation")

2023-06-05 04:26 UTC, pankajsingh-harness requested changes

2023-06-05 04:26 UTC, pankajsingh-harness commented on src/modules/75-ce/components/Connectors/AWSCOConnector/AWSCOConnector.tsx
> +      Step1
This need to be removed

2023-06-05 04:26 UTC, pankajsingh-harness commented on src/modules/35-connectors/common/ConnectorTestConnection/ConnectorTestConnection.tsx
> +              url={props?.prevStepData?.dockerRegistryUrl}
Is `dockerRegistryUrl` present for all the connectors? There is not such prop in the interface. This is not complaining as the interface is generic object. There is `url` prop in the `ConnectorTestConnectionProps` interface. Can we use that?

2023-06-05 23:58 UTC, cjlee01 approved these changes

2023-06-06 00:02 UTC, tan-nhu approved these changes

2023-06-06 14:25 UTC, jenil-harness approved these changes

2023-06-06 15:18 UTC, swarajcheguri-harness approved these changes

2023-06-06 15:58 UTC, pankajsingh-harness approved these changes

2023-06-06 17:25 UTC, merged