fix: [CDS-70776]: fixed the initialvalues for artifactory
harness/harness-core-ui pull request #16115
Opened 2023-06-01 18:56 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>
- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

https://github.com/harness/harness-core-ui/assets/57372986/70970c45-17ac-4b30-b8ea-a456be90edf8

2023-06-01 22:26 UTC, sahithikolichala commented
retrigger cyrpress-rest

2023-06-01 22:29 UTC, sahithikolichala commented
retrigger cypress-rest

2023-06-01 22:31 UTC, sahithikolichala commented
retrigger titlecheck

2023-06-01 22:38 UTC, sahithikolichala commented
retrigger titlecheck

2023-06-01 22:44 UTC, sahithikolichala commented
retrigger titlecheck

2023-06-02 03:10 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +      tag: specValues?.artifactPath,
Is this expected? We are assigning `artifactPath` value to tag here.

2023-06-02 03:10 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +      tagRegex: specValues?.artifactPathFilter
Same as above

2023-06-02 03:10 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +      tag: specValues?.artifactPath,
@samarth-sharma31

2023-06-02 03:10 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +      artifactPathValues.tag = { label: specValues?.artifactPath as string, value: specValues?.artifactPath as string }
Same as above. Using `artifactPath` as `tag`

2023-06-02 21:10 UTC, sahithikolichala commented
retrigger cypress-rest

2023-06-03 19:15 UTC, samarth-sharma31 requested changes

2023-06-03 19:15 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactUtils.ts
> +      tag: specValues?.artifactPath,
This is not the best approach to handle this as this might invite more similar bugs - I'm already working on fixing the same issue tracked via an internally raised ticket (https://harness.atlassian.net/browse/CDS-69682)

@sahithikolichala you can assign the CFD to me i can take care of this

2023-06-05 20:03 UTC, samarth-sharma31 commented
As discussed, closing this PR as this issue will be fixed by a separate PR -> https://github.com/harness/harness-core-ui/pull/16081

2023-06-05 20:03 UTC, closed without merging