feat: [CDS-70840]: disable lower graph and added message regarding the expired stage
harness/harness-core-ui pull request #16378
Opened 2023-06-14 15:22 UTC by vikrant-harness

### Summary

- Disable the lower graph in case of expired stage and added an info message

#### Screenshots

https://github.com/harness/harness-core-ui/assets/106532291/22e151f7-8ba0-4d6e-81be-05c885579dcb

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-14 16:12 UTC, rameshx requested changes

2023-06-14 16:55 UTC, PratyushGar commented on src/modules/70-pipeline/pages/execution/ExecutionPipelineView/ExecutionGraphView/ExecutionStageDetails/ExecutionStageDetails.module.scss
> +$dot-color: #7590a8;
Also, we have `var(--grey-200)` that can be used

2023-06-15 05:23 UTC, Eric761 submitted a review, later dismissed

2023-06-15 05:27 UTC, PratyushGar approved these changes

2023-06-15 05:28 UTC, Eric761 approved these changes

2023-06-15 07:50 UTC, rameshx approved these changes

2023-06-15 08:59 UTC, merged