feat: [CI-7836]: gitness integration - connectorRef as a non required field for …
harness/harness-core-ui pull request #16374
Opened 2023-06-14 14:56 UTC by shaurya-harness

### Summary

gitness integration - connectorRef as a non required field for codebase
this PR takes care of : 
1. while creating/editing a pipeline connectorRef will be an optional field if clone codebase is enabled, at BE if repoName is provided but connectorRef is not then they will assume to fetch from gitness
2. in case codebase is set as runtime input then connectorRef will also be optional for triggers/input sets
3. the above points will also apply to templates with build stage
4. currently fetchDefaultBranchForRepo api is only called if we have a connectorRef in the yaml, this behaviour will change to fetch the default branch without connectorRef (if not provided)

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-14 15:36 UTC, d1wilko requested changes
mostly looks good - but some questions

2023-06-14 15:36 UTC, d1wilko commented on src/modules/70-pipeline/components/PipelineInputSetForm/CICodebaseInputSetForm.tsx
> +                      {isBuildRuntimeInput && !showBuildAsDisabledTextField && (
I think we should still show these fields if the connector is a runtime input?

2023-06-14 15:36 UTC, d1wilko commented on src/modules/70-pipeline/components/PipelineInputSetForm/CICodebaseInputSetForm.tsx
> +                      {buildIncludesRuntimeInput && (
I think these should also show if connector is runtime input?

2023-06-21 07:14 UTC, shaurya-harness commented on src/modules/70-pipeline/components/PipelineInputSetForm/CICodebaseInputSetForm.tsx
> +                      {buildIncludesRuntimeInput && (
yes adding it back

2023-06-21 07:14 UTC, shaurya-harness commented on src/modules/70-pipeline/components/PipelineInputSetForm/CICodebaseInputSetForm.tsx
> +                      {isBuildRuntimeInput && !showBuildAsDisabledTextField && (
yes adding it back

2023-07-17 00:03 UTC, closed without merging