feat: [PL-38632]: Adding support for Service Discovery
harness/harness-core-ui pull request #16395
Opened 2023-06-15 12:41 UTC by S-ayanide

### Summary

This feature implements Service Discovery, Discovery Agent creation and Network Map implementation under project settings

#### Screenshots

![Screenshot 2023-06-15 at 6 08 55 PM](https://github.com/harness/harness-core-ui/assets/34975209/67d0985a-79fd-4215-9d83-08eb0d16aaf9)
![Screenshot 2023-06-15 at 6 09 04 PM](https://github.com/harness/harness-core-ui/assets/34975209/1fd2bf72-d082-4f74-a1b6-b9dca2e91979)
![Screenshot 2023-06-15 at 6 09 41 PM](https://github.com/harness/harness-core-ui/assets/34975209/00f43286-4d45-438b-9880-39e3f537f54d)
![Screenshot 2023-06-15 at 6 09 46 PM](https://github.com/harness/harness-core-ui/assets/34975209/c041e349-714f-4208-b8ff-01cef293944d)
![Screenshot 2023-06-15 at 6 09 52 PM](https://github.com/harness/harness-core-ui/assets/34975209/d230a11a-eefe-4e7b-a2c0-64819d76cbe6)
![Screenshot 2023-06-15 at 6 10 04 PM](https://github.com/harness/harness-core-ui/assets/34975209/80b8d943-7ea0-41e1-ab0f-57d5396dd4e8)

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-15 13:19 UTC, abhinavrastogi-harness requested changes

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/images/related-networks.svg
icons should be in uicore/icons

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/images/service-settings.svg
i think we already have these icons in uicore

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/discovery-details/views/network-map/EmptyStateNetworkMap.tsx
> +          text="Create New Network Map"
externalise all strings

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/discovery-details/views/network-map/NetworkMapTable.tsx
> +                text="New Network Map"
externalise strings

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/discovery-details/views/network-map/NetworkMapTable.tsx
> +            <TableV2<DatabaseNetworkMapCollection>
all list pages should use the <ListHeader /> component with standard sorting capabilities

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/discovery-details/views/network-map/NetworkMapTable.tsx
> +                  Header: 'NETWORK MAPS',
externalise all strings

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/discovery-details/views/settings/ListItems.tsx
> +import { Color, FontVariation, StyledProps } from '@harness/design-system'
this and few other components seem duplicated from `ServiceDetails` . 
please re-use these compomnents.

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/discovery-details/views/settings/Settings.module.scss
please remove empty files

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/home/DiscoveryPage.tsx
> +              <Page.Body className={css.discoveryAgentTable}>
all list pages should use the <ListHeader /> component with standard sorting capabilities

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/home/views/create-discovery-agent/CreateDAgent.tsx
> +          showError('Invalid configuration, either required fields were not filled or validation has failed')
externalise

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/home/views/create-discovery-agent/CreateDAgent.tsx
> +        height="7vh"
suspiciously specific. why is this using relative values? cant we hardcode the height in px?

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/home/views/create-discovery-agent/CreateDAgent.tsx
> +              discoveryNamespace: Yup.string().trim().required('Please select a discovery namespace')
externalise strings

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/home/views/empty-state/EmptyStateDiscoveryAgent.tsx
> +      <Link to={'#'} target="_blank">
broken link?

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/network-map-studio/NetworkMapStudio.tsx
> +  const handleTabChange = (tabID: StudioTabs): void => {
can we check if existing TabNavigation component can be reused?
https://uicore.harness.io/?path=/story/components-tabnavigation--basic

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/73-discovery/pages/network-map-studio/views/select-service/SelectService.tsx
> +              <TableV2<DatabaseServiceCollection>
all list pages should use the standard `<ListHeader />` component with standard sorting

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/services/servicediscovery/index.tsx
do we really need to ship all 12k lines of the service for all customers? 😅 
why have we given `*` for allowPaths?

2023-06-15 13:19 UTC, abhinavrastogi-harness commented on src/modules/RouteDestinations.tsx
> +import discoveryRoutes from '@discovery/RouteDestinations'
can we look into a dynamic import for this module? we should avoid loading all this code for 99% of the users who wont be using this right now.

2023-06-19 03:43 UTC, arkajyotiMukherjee commented on configs/restful-react.config.js
> +  'servicediscovery': {
We are using swagger 2.0. Do we need to create the spec in Open API v3?

2023-06-19 08:31 UTC, arkajyotiMukherjee commented on src/services/servicediscovery/index.tsx
we will change it to only required APIs

2023-06-20 05:22 UTC, S-ayanide commented on src/modules/73-discovery/components/NumberedList/NumberedList.tsx
> +const NumberedList: React.FC<NumberedListProps> = props => {
This component is used for the design below actually, its not the regular <li> item, the numbers along with its content also takes a showLine props which determines if the left vertical lines would render or not.

<img width="745" alt="Screenshot 2023-06-20 at 1 21 08 PM" src="https://github.com/harness/harness-core-ui/assets/34975209/73baec00-ba06-4463-8461-92c1f7e39179">

2023-06-23 05:14 UTC, amityt commented on src/modules/73-discovery/pages/discovery-details/views/discovered-resources/DiscoveredServices.tsx
> +const DiscoveredServices: React.FC = () => {
Hi @abhinavrastogi-harness , currently the backend apis don't have the sorting functionality. 😅  The API dev is still under progress, once it is available, will add the <ListHeader />

2023-06-23 05:30 UTC, S-ayanide commented on src/modules/73-discovery/pages/network-map-studio/NetworkMapStudio.tsx
> +  const handleTabChange = (tabID: StudioTabs): void => {
The functionality is same with both the approaches, but the UX design specifically required a different UI, like the one below, which will not be very straight forward with TabNavigation component

<img width="745" alt="Screenshot 2023-06-23 at 1 30 17 PM" src="https://github.com/harness/harness-core-ui/assets/34975209/a0d127e7-52b5-4736-9313-ed640952c4ab">

2023-06-23 05:31 UTC, S-ayanide commented on src/modules/73-discovery/pages/network-map-studio/views/select-service/SelectService.module.scss
> +  div[class*='TableV2--row TableV2--card'] {
The table design for SelectService is specifically different, the in-build styling wouldn't look the same without some extra modification

<img width="745" alt="Screenshot 2023-06-23 at 1 31 07 PM" src="https://github.com/harness/harness-core-ui/assets/34975209/a8d592f2-6c59-4a45-9fe6-97877633228a">

2023-06-23 10:34 UTC, abhinavrastogi-harness commented on configs/restful-react.config.js
> +  'servicediscovery': {
yes. we should be using open api v3 for all new apis

2023-06-26 03:50 UTC, S-ayanide commented
retrigger titlecheck

2023-06-26 04:33 UTC, AnshuH commented
retrigger titlecheck

2023-06-26 11:11 UTC, SahilKr24 reviewed
Some of these could be important, please a took before merging, Thanks.

2023-06-26 11:11 UTC, SahilKr24 commented on src/modules/73-discovery/pages/home/views/create-discovery-agent/CreateDAgent.tsx
> +                imageRegistry: 'index.docker.io/shovan1995',
are we using this for stress also

2023-06-26 11:11 UTC, SahilKr24 commented on src/modules/73-discovery/pages/network-map-studio/NetworkMapStudio.tsx
> +  const [title, setTitle] = useState<string>('Untitled Network Map')
external strings

2023-06-26 11:11 UTC, SahilKr24 commented on src/modules/73-discovery/pages/network-map-studio/NetworkMapStudio.tsx
> +              <Text color={title === 'Untitled Network Map' ? Color.GREY_200 : Color.GREY_900} font="medium">
external strings

2023-06-26 11:11 UTC, SahilKr24 commented on src/modules/73-discovery/pages/network-map-studio/views/select-service/SelectService.tsx
> +    for (let index = 0; index < selectedServices.length - 1; index++) {
can't we use map for this?

2023-06-26 11:11 UTC, SahilKr24 commented on src/modules/73-discovery/pages/network-map-studio/views/select-service/SelectService.tsx
> +              text={'Create Network Map'}
external strings

2023-06-26 11:11 UTC, SahilKr24 commented on src/modules/73-discovery/pages/network-map-studio/views/select-service/SelectService.tsx
> +        <Container className={css.bottomNav} padding={'medium'} height="8vh">
fixed height?

2023-06-26 11:43 UTC, arkajyotiMukherjee commented
retrigger jest

2023-06-28 04:10 UTC, abhinavrastogi-harness approved these changes

2023-06-28 04:13 UTC, merged