feat: [FFM-7936]: listing archived flags
harness/harness-core-ui pull request #16420
Opened 2023-06-19 13:21 UTC by crystal-fong

Users are able to archive a flag
The 'Archived' card will appear
Users can click the Archived card and view the list of archived flag
Users can restore an archived flag
The restored flag will appear back in the normal flag listing

When users not delete a flag, it will be permanently deleted

#### Screenshots

https://github.com/harness/harness-core-ui/assets/95680496/7e6158e1-cc9b-419c-9120-c2369179105a

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-22 10:20 UTC, knagurski commented on src/services/cf/index.tsx
> +  forceDelete?: boolean
Does this mean that the backend now archives by default? That's a breaking change. Is it in production yet?

2023-06-22 10:31 UTC, crystal-fong commented on src/services/cf/index.tsx
> +  forceDelete?: boolean
the BE logic should also be behind a FF

2023-06-23 09:17 UTC, crystal-fong commented on src/modules/75-cf/components/FlagArchiving/__tests__/useRestoreFlagDialog.test.tsx
> +      expect(screen.getAllByText(error)[0]).toBeInTheDocument()
some weird mocking causes the error toaster to appear more than once but I'm too sick of this PR :D

2023-06-23 14:15 UTC, d1wilko requested changes
I don't understand feature flags lol - some small suggestions, but coming together nicely

2023-06-23 14:15 UTC, d1wilko commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +        optionItems.shift()
I appreciate you didn't write the initial code here - but using the shift function assumes edit will always be the first element... if someone changed the code above and added an option in first this would break

perhaps this should be changed to not include edit option in the first place if noEdit is true?

2023-06-23 14:15 UTC, d1wilko commented on src/modules/75-cf/pages/feature-flags/components/FlagTableFilters.tsx
> +    filters.pop()
again this assumes ARCHIVED will always be the last element... it could break if new options are added

2023-06-23 14:15 UTC, d1wilko commented on src/modules/75-cf/pages/feature-flags/components/__tests__/FlagTableFilters.test.tsx
> +    ;(flagEnabled = true), (archivingFFEnabled = false)
is the semicolon at the start here right?

2023-06-23 14:18 UTC, crystal-fong commented on src/modules/75-cf/pages/feature-flags/components/__tests__/FlagTableFilters.test.tsx
> +    ;(flagEnabled = true), (archivingFFEnabled = false)
yeaaah prettier added this automatically

2023-06-26 09:55 UTC, laura-mannus commented on src/modules/75-cf/components/FlagDetailsOptionsMenuButton/FlagDetailsOptionsMenuButton.tsx
> +    archiveFlag: deleteFeatureFlag,
any way we could rename to just be `archiveFlag` since we aren't using the delete term anymore

2023-06-26 10:00 UTC, laura-mannus commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +    archiveFlag: deleteFlag
same here, just seems odd we refer to delete here. Can we just have archive?

2023-06-26 10:03 UTC, crystal-fong commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +    archiveFlag: deleteFlag
the delete functionality still exists, the archive and delete functionality is just differentiated by a query parameter so if I change it here, hard delete would look like I'm archiving

2023-06-26 10:10 UTC, crystal-fong commented on src/modules/75-cf/components/FlagArchiving/useRestoreFlagDialog.tsx
> +  )
I've removed the useMemo now and queryParams is no longer a function

2023-06-26 10:10 UTC, crystal-fong commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +        optionItems.shift()
that's a fair point, I've updated it now ty

2023-06-26 12:58 UTC, knagurski commented on src/modules/75-cf/components/FlagArchiving/__tests__/useArchiveFlagDialog.test.tsx
> +const archiveFeatureFlagMock = jest.fn()
Looks like these mocks aren't cleared between tests, so running the tests in different order could give different results. Can we put in a `jest.clearAllMocks` in a `beforeEach` block?

2023-06-26 13:05 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags/components/__tests__/FlagTableFilters.test.tsx
> +  test('It should not show Archived card if there are no archived flags', async () => {
Out of curiosity, what happens if you are in the archived flags view with a single archived flag and then you restore it? If archived flags disappears, then we'd need to make sure the user is redirected. Would it maybe make more sense to always show the Archived Flags card like any other card?

2023-06-26 13:09 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags/components/__tests__/FlagTableFilters.test.tsx
> +    renderComponent()
It's usually a better idea to pass these into the `renderComponent` function instead of using global variables, otherwise you can have unexpected results and tests will fail if you reorder them.

2023-06-26 13:12 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags/components/__tests__/FlagTableFilters.test.tsx
> +    ;(flagEnabled = true), (archivingFFEnabled = false)
That's the downside of using JS without semicolons... sometimes they're needed and can't reliably be auto-injected at runtime. Though in this case a line break between seems fine in my IDE.
```suggestion
    flagEnabled = true
    archivingFFEnabled = false
```

2023-06-26 13:14 UTC, crystal-fong commented on src/modules/75-cf/pages/feature-flags/components/__tests__/FlagTableFilters.test.tsx
> +  test('It should not show Archived card if there are no archived flags', async () => {
<img width="1455" alt="image" src="https://github.com/harness/harness-core-ui/assets/95680496/23831cb7-421f-496a-a0db-402ac91e7d65">
it'll look like ^

2023-06-26 13:15 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags/components/__tests__/FlagTableFilters.test.tsx
> +  test('It should not show Archived card if there are no archived flags', async () => {
So it just kinda orphans it 🤔

2023-06-26 13:19 UTC, knagurski commented on src/modules/75-cf/components/FlagArchiving/__tests__/useArchiveFlagDialog.test.tsx
> +const archiveFeatureFlagMock = jest.fn()
Ideally it should just be `jest.fn()` on line 32 and then you create and pass in only in the tests you actually need it for (i.e. only those you assert on it)

2023-06-26 13:20 UTC, knagurski commented on src/modules/75-cf/components/FlagArchiving/__tests__/useRestoreFlagDialog.test.tsx
> +      expect(screen.getAllByText(error)[0]).toBeInTheDocument()
It's not that it appears more than once, it's that it doesn't disappear between tests. We have a wee bit of code in FF-UI that kills it off between tests.

2023-06-26 13:21 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags/components/__tests__/FlagTableFilters.test.tsx
> +  test('It should not show Archived card if there are no archived flags', async () => {
We don't remove any other filters based on availability of data. Could be worth confirming if that's really what we want to do here.

2023-06-26 13:29 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags/components/FlagTableFilters.tsx
> +  // remove Archived filter card if there are no flags that are archived and if Archiving FF is toggled OFF
Super minor, totally not a blocker
```suggestion
  // remove Archived filter card if there are no flags that are archived or if Archiving FF is toggled OFF
```

2023-06-26 13:36 UTC, knagurski commented on src/modules/75-cf/components/FlagOptionsMenuButton/__tests__/FlagOptionsMenuButton.test.tsx
>      const isArchivingFfOn = true
Not a blocker in the least, but since `FF` is short for `Feature Flag`, not Featureflag`, then both f's should be capitalised. #justsayin 😛 
```suggestion
    const isArchivingFFOn = true
```

2023-06-26 13:37 UTC, knagurski commented on src/modules/75-cf/components/FlagOptionsMenuButton/__tests__/FlagOptionsMenuButton.test.tsx
> +describe('FlagOptionsMenuButton', () => {
🙌🏻

2023-06-26 13:41 UTC, knagurski commented on src/modules/75-cf/components/FlagArchiving/useRestoreFlagDialog.tsx
> +    }
Just curious if this can be simplified?
```suggestion
    action: handleRestore
```

2023-06-26 13:47 UTC, knagurski commented on src/modules/75-cf/components/FlagArchiving/useRestoreFlagDialog.tsx
> +      <String stringID="cf.featureFlags.archiving.restoreDescription" vars={{ flagName: flagData.name }} useRichText />
Looks like the actual string doesn't have any HTML in it. You can remove `useRichText`, otherwise `flagData.name` becomes a stored XSS attack vector.

2023-06-26 13:51 UTC, knagurski commented on src/modules/75-cf/components/FlagArchiving/useRestoreFlagDialog.tsx
> +    ),
I think the `message` in the confirmation dialog has a bit of stupid CSS attached to get text to break if it's too long, but we poorly done and causes words to get cut off in weird ways. We might need to add a wrapper around the content and apply the correct CSS.
```suggestion
    message: (
      <span style={{ wordBreak: 'break-word' }}>
        {getString('cf.featureFlags.archiving.restoreDescription', { flagName: flagData.name })}
      </span>
    ),
```

2023-06-26 13:54 UTC, knagurski commented on src/modules/75-cf/components/FlagArchiving/useRestoreFlagDialog.tsx
> +      refetchFlags?.()
You can get rid of having to do this by defaulting `refetchFlags` to `() => void 0`. `() => {}` would also work, but ESLint will whinge at you
```suggestion
      refetchFlags()
```

2023-06-26 14:10 UTC, knagurski commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +      optionItems = [
Super minor, but instead of having an array that's never used, but overwritten in a bunch of places, you can just return the new option items

2023-06-26 14:11 UTC, knagurski commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +    let optionItems = [] as RbacMenuItemProps[]
If you do want to keep this, then type the variable, not the value
```suggestion
    let optionItems: RbacMenuItemProps[] = []
```

2023-06-26 14:14 UTC, knagurski commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +          ...planEnforcementProps
I don't think we should combine these two buttons like this. They do fundamentally different things and the permissions are different.

2023-06-26 14:21 UTC, knagurski commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +          icon: flagData.archived ? 'redo' : 'edit',
With all these ternaries, I think a better way would be to have an `if`/`else` instead.

2023-06-26 14:33 UTC, knagurski commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +          }
A lot of the options are repeated. It might make sense to compose them instead of duplicating them. e.g.

```typescript
const options: Record<string, RbacMenuItemProps> = {
  restore: {
    // ...
  },
  edit: {
    // ...
  },
  archive: {
    // ...
  },
  delete: {
    // ...
  }
}

// ...

if (FFM_7921_ARCHIVING_FEATURE_FLAGS) {
  if (flagData.archived) {
    return [options.restore, options.delete]
  } else {
    return [options.edit, options.archive]
  }
}
// ...
```

2023-06-27 13:01 UTC, crystal-fong commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +          }
that works very nicely 👍

2023-06-27 13:02 UTC, crystal-fong commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +    let optionItems = [] as RbacMenuItemProps[]
I had to add that array bc TS was giving off that the contents of the array couldn't be applied to `RbacMenuItemProps`

2023-06-27 13:02 UTC, crystal-fong commented on src/modules/75-cf/components/FlagArchiving/useRestoreFlagDialog.tsx
> +    }
can do

2023-06-27 13:33 UTC, d1wilko approved these changes
some small comments - but not worth slowing down the PR for :) good work!

Also should check if test failures are associated with this PR

2023-06-27 13:33 UTC, d1wilko commented on src/modules/75-cf/pages/feature-flags/components/__tests__/FlagTableFilters.test.tsx
> +// let archivingFFEnabled = false
probs worth removing these?

2023-06-27 13:33 UTC, d1wilko commented on src/modules/75-cf/pages/feature-flags/components/__tests__/FlagTableFilters.test.tsx
> +  // })
worth removing this?

2023-06-27 13:33 UTC, d1wilko commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +  const menuItems = useMemo(() => {
I know this isn't your original code, so I don't mind if you keep it as is but this menuItems function hurts my soul lol

I'd have it something like below - renamed so it is clear it is a function, no external variables so it is a pure function and get rid of useMemo because it is a premature optimisation on a really simple function - but I know it is not your code :)

`
const getMenuItems = (archiveFeatureFlag, flagData, options) => {
  if (archiveFeatureFlag) {
      if (flagData.archived) {
        return [options.restore, options.delete]
      } else {
        return [options.edit, options.archive]
      }
    } else {
      return [options.edit, options.delete]
    }
}
`

2023-06-27 13:35 UTC, crystal-fong commented on src/modules/75-cf/pages/feature-flags/components/__tests__/FlagTableFilters.test.tsx
> +// let archivingFFEnabled = false
🤦‍♀️ yes

2023-06-28 09:56 UTC, knagurski commented on src/modules/75-cf/components/FlagArchiving/__tests__/useRestoreFlagDialog.test.tsx
> +}
No real need to assign to a variable and then return that variable
```suggestion
const renderComponent = (props: Partial<RestoreFlagDialogProps> = {}): RenderResult =>
  render(
    <TestWrapper>
      <WrapperComponent
        flagData={archivedMockFeature as Feature}
        onRefetch={jest.fn()}
        queryParams={{
          accountIdentifier: 'mockAccountIdentifier',
          orgIdentifier: 'mockOrgIdentifier',
          projectIdentifier: 'mockProjectIdentifier'
        }}
        {...props}
      />
    </TestWrapper>
  )
```

2023-06-28 10:01 UTC, crystal-fong commented on src/modules/75-cf/components/FlagArchiving/__tests__/useRestoreFlagDialog.test.tsx
> +}
this doesn't seem to be a blocker but I can address it in the next PR

2023-06-28 10:15 UTC, knagurski commented on src/modules/75-cf/components/FlagArchiving/useRestoreFlagDialog.tsx
> +      showError(e.message)
The reason you're having to use `getAllByText` in the test for this is because `handleResponseError` is doing this exact thing (`src/modules/75-cf/hooks/useResponseError.tsx` line 33) and in fact the app is displaying double errors. You can delete this line and it should work fine.

2023-06-28 10:22 UTC, knagurski commented on src/modules/75-cf/components/FlagArchiving/useRestoreFlagDialog.tsx
> +        <String stringID="cf.featureFlags.archiving.restoreDescription" vars={{ flagName: flagData.name }} />
Out of curiosity, why use the `<String />` component instead of just `getString`?
```suggestion
        {getString('cf.featureFlags.archiving.restoreDescription', { flagName: flagData.name })}
```

2023-06-28 10:24 UTC, knagurski commented on src/modules/75-cf/components/FlagArchiving/useRestoreFlagDialog.tsx
> +  onRefetch: () => void
Not a blocker, but this should be probably be `onRestore`, not `onRefetch` since this component isn't refetching and then calling this, it's restoring and then calling it.

2023-06-28 10:26 UTC, knagurski commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +      },
This should have the same permissions as archive.

2023-06-28 10:43 UTC, crystal-fong commented on src/modules/75-cf/components/FlagArchiving/useRestoreFlagDialog.tsx
> +        <String stringID="cf.featureFlags.archiving.restoreDescription" vars={{ flagName: flagData.name }} />
just habit since it what I used whenever I needed a string with a var

2023-06-28 10:54 UTC, crystal-fong commented on src/modules/75-cf/components/FlagArchiving/useRestoreFlagDialog.tsx
> +  onRefetch: () => void
??? don't understand. It's the refetch flag function I'm passing in as prop

2023-06-28 10:57 UTC, knagurski commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +      },
Archive/Delete:
```
permission: {
  resource: { resourceType: ResourceType.FEATUREFLAG },
  permission: PermissionIdentifier.DELETE_FF_FEATUREFLAG
}
```

Restore:
```
permission: {
  resource: { resourceType: ResourceType.ENVIRONMENT, resourceIdentifier: environment },
  permission: PermissionIdentifier.DELETE_FF_FEATUREFLAG
}
```

They ain't the same

2023-06-28 10:59 UTC, crystal-fong commented on src/modules/75-cf/components/FlagOptionsMenuButton/FlagOptionsMenuButton.tsx
> +      },
👍

2023-06-28 13:23 UTC, knagurski approved these changes
Really awesome work! Shaping up very nicely!

2023-06-28 13:34 UTC, laura-mannus approved these changes

2023-06-28 13:58 UTC, merged