fix: [SSCA-66] total count from server data
harness/harness-core-ui pull request #16434
Opened 2023-06-20 05:39 UTC by udayvunnam

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-20 07:02 UTC, rameshx submitted a review, later dismissed

2023-06-20 10:07 UTC, pankajsingh-harness submitted a review, later dismissed

2023-06-21 06:28 UTC, bhavya-sinha requested changes

2023-06-21 06:28 UTC, bhavya-sinha commented on src/modules/70-pipeline/pages/execution/ExecutionArtifactsView/__tests__/ExecutionArtifactListView.test.tsx
> +    userEvent.type(screen.getByRole('searchbox'), 'my search term')
This will break. Please rebase your branch from develop and fix it.

2023-06-21 06:28 UTC, rameshx commented on src/modules/70-pipeline/pages/execution/ExecutionArtifactsView/PolicyViolations/PolicyViolationsTableCells.tsx
> +      </Text>
`data.supplier` is used twice, intentional?

2023-06-21 07:12 UTC, pankajsingh-harness submitted a review, later dismissed

2023-06-21 09:35 UTC, pankajsingh-harness approved these changes

2023-06-21 09:38 UTC, bhavya-sinha approved these changes

2023-06-21 09:38 UTC, merged