feat: [PL-38840]: Typescript and Jest Upgrades
harness/harness-core-ui pull request #16431
Opened 2023-06-20 01:59 UTC by bhavya-sinha

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-20 07:57 UTC, rameshx requested changes

2023-06-20 07:57 UTC, rameshx commented on src/modules/10-common/components/ConfigureOptions/SelectConfigureOptions/__tests__/SelectConfigureOptions.test.tsx
> +  })
As we are using the latest version of `userEvent`, the only change required would be to replace all `userEvent.x` to `await userEvent.x`. It should not be wrapped in `act`.

2023-06-20 08:54 UTC, praneshg239 commented on src/modules/10-common/components/ConfigureOptions/SelectConfigureOptions/__tests__/SelectConfigureOptions.test.tsx
> +  })
Yes, I saw this only after adding `act` to some files. Rest of the files `act` was not added. I am reverting the places I added `act`.

2023-06-20 09:24 UTC, vikrant-harness submitted a review, later dismissed

2023-06-21 03:25 UTC, udayvunnam approved these changes

2023-06-21 03:45 UTC, vikrant-harness approved these changes

2023-06-21 04:31 UTC, rameshx approved these changes

2023-06-21 04:39 UTC, AshwinBhatkal-Harness commented on src/modules/10-common/components/ConfigureOptions/SelectConfigureOptions/__tests__/SelectConfigureOptions.test.tsx
> +  await userEvent.click(allowedValuesRadio)
await should not be necessary in such cases? Can we not do without it?

It makes sense for findByText or when you want to wait for the element that is to be clicked.

2023-06-21 04:49 UTC, praneshg239 commented on src/modules/10-common/components/ConfigureOptions/SelectConfigureOptions/__tests__/SelectConfigureOptions.test.tsx
> +  await userEvent.click(allowedValuesRadio)
It is mandate in the latest version of jest.

2023-06-21 04:54 UTC, praneshg239 commented on src/modules/10-common/components/ConfigureOptions/SelectConfigureOptions/__tests__/SelectConfigureOptions.test.tsx
> +  await userEvent.click(allowedValuesRadio)
As it is promise based, if we are not adding `await` then tests are failing.

2023-06-21 05:14 UTC, AshwinBhatkal-Harness approved these changes

2023-06-21 05:15 UTC, deepesh-ui approved these changes

2023-06-21 06:14 UTC, devinder-harness approved these changes

2023-06-21 06:14 UTC, jyotiarora-harness approved these changes

2023-06-21 06:18 UTC, bhavya-sinha commented on src/modules/10-common/components/ConfigureOptions/SelectConfigureOptions/__tests__/SelectConfigureOptions.test.tsx
> +  })
fixed all

2023-06-21 06:21 UTC, merged

2023-06-21 06:21 UTC, shaurya-harness approved these changes