feat: [CDS-56694]:Rancher infrastructure
harness/harness-core-ui pull request #16445
Opened 2023-06-20 13:11 UTC by litvinovstas

### Summary
Added rancher infrastructure

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-20 21:42 UTC, litvinovstas commented
retrigger jest

2023-06-21 06:31 UTC, bhavya-sinha requested changes

2023-06-21 06:31 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/RancherInfrastructureSpec/__tests__/RancherInfraStructureSpec.test.tsx
> +    fireEvent.click(getByText(container, 'Submit'))
Please rebase with develop and fix this

2023-06-22 05:54 UTC, litvinovstas commented
retrigger cypress-cv

2023-06-22 05:54 UTC, litvinovstas commented
retrigger cypress-rest

2023-06-22 06:37 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/PipelineSteps/RancherInfrastructureSpec/RancherInfrastructureSpec.tsx
> +type CommonConnector = 'Rancher'
NIT: can use connector enum here

2023-06-22 06:41 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/PipelineSteps/RancherInfrastructureSpec/RancherInfrastructureSpec.tsx
> +const RancherInfrastructureSpecInputForm: React.FC<RancherInfrastructureSpecEditableProps & { path: string }> = ({
NIT: could split these into maybe 3 files, Edit, inputset, and parent

2023-06-22 06:45 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/PipelineSteps/RancherInfrastructureSpec/__tests__/RancherInfraStructureSpec.test.tsx
> +    expect(container).toBeDefined()
I see multiple occurrences of `expect(container).toBeDefined()`, we are not asserting any useful info here.
Maybe here we can assert what the test title says, for e.g. we can assert the visibility of input or other fields with there default states e.g. whether its fixed/runtime/expression, etc.

2023-06-22 20:18 UTC, litvinovstas commented on src/modules/75-cd/components/PipelineSteps/RancherInfrastructureSpec/RancherInfrastructureSpec.tsx
> +const RancherInfrastructureSpecInputForm: React.FC<RancherInfrastructureSpecEditableProps & { path: string }> = ({
we are using same pattern on project level.

2023-06-22 20:32 UTC, Sagar-Rajput7 approved these changes

2023-06-23 04:27 UTC, reetika04 approved these changes

2023-06-23 05:12 UTC, bhavya-sinha approved these changes

2023-06-23 05:20 UTC, merged