fix: [CDS-72838]: removed Featureflag CDS_NG_TRIGGER_SELECTIVE_STAGE_…
harness/harness-core-ui pull request #16527
Opened 2023-06-22 18:59 UTC by sahithikolichala

…EXECUTION

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-22 22:23 UTC, sahithikolichala commented
retrigger titlecheck

2023-06-22 22:23 UTC, sahithikolichala commented
retrigger cypress-rest

2023-06-22 23:00 UTC, sahithikolichala commented
retrigger cypress-rest

2023-06-23 07:12 UTC, ishantmehtaharness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactTriggerConfigPanel.tsx
> +      <StageSelection formikProps={formikProps} /> : null
This is wrong here

`<StageSelection formikProps={formikProps} /> : null` <> This should be changed to `<StageSelection formikProps={formikProps} />`

2023-06-23 07:14 UTC, ishantmehtaharness commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactTriggerConfigPanel.tsx
> +      <StageSelection formikProps={formikProps} /> : null
@abhinavrastogi-harness @knagurski - Shouldn't this fail in Eslint or any other lint checks?

2023-06-23 07:16 UTC, ishantmehtaharness commented on src/modules/72-triggers/pages/triggers/TriggerLandingPage/TriggerDetailPage/TriggerDetailPage.tsx
> +
We can directly add it to the array, instead of pushing it to the array here

2023-06-23 07:21 UTC, ishantmehtaharness commented on src/modules/72-triggers/pages/triggers/__tests__/webhookMockResponses.ts
> +      }
this seems to be the same data as written in a previous file. we can re-use

2023-06-23 07:21 UTC, ishantmehtaharness requested changes
https://github.com/harness/harness-core-ui/pull/16527/files#r1239430609

2023-07-03 21:23 UTC, sahithikolichala commented on src/modules/72-triggers/components/steps/ArtifactTriggerConfigPanel/ArtifactTriggerConfigPanel.tsx
> +      <StageSelection formikProps={formikProps} /> : null
yes ideally it should fail

2023-07-03 22:24 UTC, sahithikolichala commented
retrigger cypress-rest

2023-07-03 23:11 UTC, sahithikolichala commented
retrigger eslint

2023-07-03 23:11 UTC, sahithikolichala commented
retrigger prettier

2023-07-04 11:31 UTC, pankajsingh-harness approved these changes

2023-07-04 15:05 UTC, ishantmehtaharness approved these changes
Looks Good, thanks for addressing review comments

2023-07-05 17:00 UTC, sahithikolichala commented
retrigger cypress-rest

2023-07-06 09:43 UTC, merged