feat: [CDS-72340]: Align template inputs with pipeline
harness/harness-core-ui pull request #16552
Opened 2023-06-23 14:45 UTC by srdjan-harness

### Summary

If the template is used in the pipeline and we add/set more runtime inputs in the template,  we wants to prevent rendering these new input set fields when we open pipeline before reconciliation

#### Screenshots

<img width="1415" alt="template-update-fix" src="https://github.com/harness/harness-core-ui/assets/69592850/f15c70c1-f2f2-4825-9676-1105a5f06018">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-23 17:40 UTC, srdjan-harness commented
retrigger titlecheck

2023-06-23 17:43 UTC, srdjan-harness commented
retrigger titlecheck

2023-06-23 17:44 UTC, srdjan-harness commented
retrigger jest

2023-07-07 14:12 UTC, pankajsingh-harness approved these changes

2023-07-20 09:26 UTC, rameshx requested changes

2023-07-20 09:26 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/PipelineTemplateBuilder/TemplatePipelineSpecifications/TemplatePipelineSpecifications.tsx
> +  const { checkPipelineTemplateChange, requiredAction, disableForm } = useCheckTemplateTemplateChange()
`Template` is present twice in `useCheckTemplateTemplateChange`

2023-07-20 09:26 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/PipelineTemplateBuilder/TemplatePipelineSpecifications/useCheckPipelineTemplateChange.tsx
> +    const setRequiredActionDebounce = debounce(setRequiredAction, 100)
`debounce(setRequiredAction, 100)` can be moved inside `useMemo` and defined outside the effect to avoid creating a debounced function on every run of the effect

2023-07-20 09:26 UTC, rameshx commented on src/modules/70-pipeline/utils/pipelineReconcileUtils.ts
> +  // This means that in some edge cases algorithm winn not work as expected.
Can we fix all typos in these comments?

2023-07-20 09:26 UTC, rameshx commented on src/modules/72-templates-library/components/TemplateStageSpecifications/useCheckStageTemplateChange.tsx
> +    const setRequiredActionDebounce = debounce(setRequiredAction, 100)
let's use `useMemo` and define this outside the effect

2023-07-20 09:26 UTC, rameshx commented on src/modules/72-templates-library/components/TemplateStageSpecifications/useCheckStageTemplateChange.tsx
> +}
This enum looks similar to the one in `useCheckPipelineTemplateChange.tsx`, let's reuse

2023-07-20 09:26 UTC, rameshx commented on src/modules/72-templates-library/components/TemplateStageSpecifications/TemplateStageSpecifications.tsx
> +      )}
Can we create a component for this? This looks very similar to the element in `TemplatePipelineSpecifications.tsx`. It will also help in removing duplicate styles of `templateChangedWarning`.

2023-07-21 04:01 UTC, rameshx submitted a review, later dismissed

2023-07-21 09:17 UTC, PratyushGar approved these changes

2023-07-21 09:26 UTC, rameshx approved these changes

2023-07-21 09:28 UTC, sonaligoyal-harness approved these changes

2023-07-21 09:38 UTC, merged

2023-07-21 09:47 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineStudio/PipelineTemplateBuilder/TemplatePipelineSpecifications/useCheckPipelineTemplateChange.tsx
> +import { useCallback, useEffect, useState } from 'react'
This file does not have license information.

2023-07-21 09:47 UTC, pankajsingh-harness commented on src/modules/70-pipeline/hooks/useReconcile.ts
> +import React, { useEffect } from 'react'
This file also does not have license info

2023-07-21 09:47 UTC, pankajsingh-harness commented on src/modules/70-pipeline/hooks/useReconcile.ts
> +  storeMetadata?: StoreMetadata | undefined
```suggestion
  storeMetadata?: StoreMetadata
```

2023-07-21 09:47 UTC, pankajsingh-harness commented on src/modules/70-pipeline/utils/pipelineReconcileUtils.ts
> +import { flatMap, isArray, isPlainObject, map, concat, keys, get } from 'lodash-es'
Same as above