fix: [CDS-72729]: AWS sam step update values on edit
harness/harness-core-ui pull request #16562
Opened 2023-06-26 09:13 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-26 09:27 UTC, chetanvekariya-harness requested changes

2023-06-26 09:27 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/AwsSam/AwsSamDeployStep/AwsSamDeployStep.tsx
> +        onChange={(formData: AwsSamDeployStepInitialValues) => onUpdate?.(this.processFormData(formData))}
onChange should be called here. Access it from props and use it here.

2023-06-26 09:33 UTC, namanharness commented on src/modules/75-cd/components/PipelineSteps/AwsSam/AwsSamDeployStep/AwsSamDeployStep.tsx
> +        onChange={(formData: AwsSamDeployStepInitialValues) => onUpdate?.(this.processFormData(formData))}
Yes , updated

2023-06-26 09:34 UTC, chetanvekariya-harness approved these changes

2023-06-26 10:01 UTC, pankajsingh-harness approved these changes

2023-06-27 10:48 UTC, YounixIO approved these changes

2023-06-27 10:55 UTC, merged