feat: [PL-39723]: EULA for Harness AIDA
harness/harness-core-ui pull request #16750
Opened 2023-07-05 15:05 UTC by mayankVermaHarness

### Summary

JIRA: https://harness.atlassian.net/browse/PL-39723
EULA for Harness AIDA

#### Screenshots

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-06 07:37 UTC, ishantmehtaharness commented on src/modules/23-default-settings/strings/strings.en.yaml
> +    1. Limitation of Liability. To the maximum extent permitted by applicable law, Harness shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of o
We have multiple `1. `
Is this expected? do we need proper numbering

2023-07-13 08:21 UTC, mayankVermaHarness commented on src/modules/23-default-settings/strings/strings.en.yaml
> +    1. Limitation of Liability. To the maximum extent permitted by applicable law, Harness shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of o
Yes, this gets converted to proper numbering when we convert this markdown to HTML. Please check the video/screenshots in PR description.

2023-08-22 05:03 UTC, abhinavrastogi-harness requested changes

2023-08-22 05:03 UTC, abhinavrastogi-harness commented on package.json
> +    "@harnessio/react-ng-manager-client": "file:.yalc/@harnessio/react-ng-manager-client",
needs to be fixed

2023-08-23 03:48 UTC, abhinavrastogi-harness commented on src/modules/27-platform/strings/strings.en.yaml
> +      **Harness AI Developer Assistant (AIDA) Terms**
Can we consider loading this text from Contentful?
It'll avoid committing the huge text to the strings framework, and allow docs team to change it without requiring a code deployment.

2023-08-23 08:21 UTC, namanharness commented on package.json
> +    "@harnessio/react-ng-manager-client": "file:.yalc/@harnessio/react-ng-manager-client",
fixed

2023-08-24 18:46 UTC, abhinavrastogi-harness approved these changes

2023-08-24 19:45 UTC, mayankVermaHarness commented on src/modules/27-platform/default-settings/utils/utils.ts
> +export const AidaAgreementType = 'AIDA'
```suggestion
export const AgreementType = {
  AIDA: 'AIDA'
}
```

2023-08-24 19:46 UTC, mayankVermaHarness commented on src/modules/27-platform/strings/strings.en.yaml
> +      **Harness AI Developer Assistant (AIDA) Terms**
As discussed, we will get this from Strapi.

2023-08-24 19:49 UTC, mayankVermaHarness commented on src/modules/27-platform/default-settings/components/__test__/EulaComponents.test.tsx
> +      fireEvent.click(input)
For clicks, prefer using `userEvent.click`

2023-08-24 19:57 UTC, namanharness commented on src/modules/27-platform/default-settings/utils/utils.ts
> +export const AidaAgreementType = 'AIDA'
<img width="888" alt="image" src="https://github.com/harness/harness-core-ui/assets/110456765/2dc070f0-587a-432a-9d68-4f8397338ae4">

Getting this when putting it in object

2023-08-24 19:58 UTC, mayankVermaHarness commented
@namanharness I was the author of original PR, so I can't approve this.

2023-08-24 20:12 UTC, namanharness approved these changes

2023-08-24 20:14 UTC, namanharness commented on src/modules/27-platform/default-settings/components/__test__/EulaComponents.test.tsx
> +      fireEvent.click(input)
Will update in next PR

2023-08-24 20:14 UTC, namanharness commented on src/modules/27-platform/default-settings/utils/utils.ts
> +export const AidaAgreementType = 'AIDA'
Will update in next PR

2023-08-24 20:29 UTC, merged