Setup sei mfe
harness/harness-core-ui pull request #16760
Opened 2023-07-06 05:12 UTC by thanh-levelops

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-20 13:01 UTC, sharath-levelops commented
retrigger titlecheck

2023-07-20 18:39 UTC, tan-nhu commented on src/modules/75-sei/pages/home/SEIHomePage.tsx
> +  const module = 'sei'
Can we use `ModuleName.SEI` here instead of declare another constant?

2023-07-20 18:39 UTC, tan-nhu commented on src/modules/75-sei/pages/home/SEIHomePage.tsx
> +    ...licenseInformation?.['SEI'],
`SEI` can be referenced as `ModuleName.SEI`?

2023-07-20 18:40 UTC, tan-nhu approved these changes

2023-07-20 19:29 UTC, SahilKr24 approved these changes

2023-07-20 21:25 UTC, abhinavrastogi-harness requested changes

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/10-common/RouteDefinitions.ts
> +  toSEIPropels: withAccountId(() => `/sei/propels/#/admin/propels`)
We should not have hash routes hardcoded here.
there routes are consumed by `BrowserRouter`. there might be some side-effects of putting `#` in the URL paths themselves.

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/SEICustomMicroFrontendProps.types.ts
> +    useGetToken: typeof useGetToken
microfrontend should not use the token directly. why is this needed?

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/SEICustomMicroFrontendProps.types.ts
> +    useAccountId: typeof useAccountId
this data is already available to all microfrontends via AppStoreContext. why do we need these hooks to be passed?

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/components/SEISideNav/SEISideNav.module.scss
> +.main {
this file is entirely style overrides.. why is this needed?

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/components/SEISideNav/SEISideNav.tsx
> +              <SidebarLink to={routes.toAccessControl(params)} label={getString('accessControl')} />
why aren't we using the `ProjectSetupMenu` component directly? That includes the Access Control route, and a few other common project setup pages like connectors, secrets etc.

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/components/SEISideNav/__test__/SEISideNav.test.tsx
> +    expect(container).toMatchSnapshot()
please use assertions instead of snapshots throughout all tests

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/pages/home/SEIHomePage.tsx
> +  const projectCreateSuccessHandler = (project?: Project): void => {
can we re-use this from a common util? almost all modules have this code duplicated.

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/pages/home/SEIHomePage.tsx
> +  const showTrialPages = createdFromNG || NG_LICENSES_ENABLED
this condition is already present in `LicenseStoreContext`. cant we reuse it from there?

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/pages/home/SEITrialPage/SEITrialPage.tsx
> +          href="https://www.harness.io/company/contact-sales?utm_source=Website&utm_medium=internal&utm_content=Contact-Sales-STO-Pricing"
move all hardcoded urls to `const` declarations at the top of the files

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/pages/home/SEITrialPage/__test__/SEITrialHomePage.test.tsx
> +    expect(container).toMatchSnapshot()
use assertions instead of snapshot

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/pages/home/__test__/SEIHomePage.test.tsx
> +    expect(container).toMatchSnapshot()
no need for snapshots if assertions are present

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/pages/home/__test__/__snapshots__/SEIHomePage.test.tsx.snap
remove all snapshots possible

2023-07-20 21:25 UTC, abhinavrastogi-harness commented on src/modules/75-sei/pages/home/images/sei.svg
> +<svg width="1127" height="470" viewBox="0 0 1127 470" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
has this svg been run through the optimiser/minifier?
why is this an svg? it could be a smaller png since it's a pretty complex image, used as a background.

2023-08-02 07:19 UTC, sharath-levelops commented
@abhinavrastogi-harness @tan-nhu I have addressed all the review comments. Please take a look

2023-08-08 17:00 UTC, abhinavrastogi-harness submitted a review, later dismissed

2023-08-08 17:00 UTC, abhinavrastogi-harness commented on src/modules/10-common/navigation/ModuleList/__tests__/__snapshots__/ModuleList.test.tsx.snap
> +                href="/account/undefined/sei"
`undefined` looks wrong in the snapshot. are you not getting the account id correctly here?

2023-08-09 05:55 UTC, sharath-levelops commented on src/modules/10-common/navigation/ModuleList/__tests__/__snapshots__/ModuleList.test.tsx.snap
> +                href="/account/undefined/sei"
Updated the test and snapshot, https://github.com/harness/harness-core-ui/pull/16760/commits/96d40fd9af43ab5d42f0575fbc773482e48c272f

2023-08-09 08:24 UTC, tan-nhu approved these changes

2023-08-09 19:30 UTC, abhinavrastogi-harness approved these changes
Let's move the SEI module to the "Optimize processes" section of the nav configuration screen.
LGTM apart from that.

2023-08-10 04:41 UTC, merged