feat: [CDS-70882]: Show GitOps at Org Level
harness/harness-core-ui pull request #16772
Opened 2023-07-06 12:06 UTC by ishantmehtaharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-06 14:12 UTC, ishantmehtaharness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +  // const showGitOpsCard = (accountId || orgIdentifier) && !projectIdentifier
We have enabled it for the account level.
once all the changes are done, we will enable for org level.

2023-07-06 16:15 UTC, pankajsingh-harness approved these changes

2023-07-06 16:24 UTC, chetanvekariya-harness submitted a review, later dismissed

2023-07-07 09:25 UTC, abhinavrastogi-harness requested changes

2023-07-07 09:25 UTC, abhinavrastogi-harness commented on src/modules/10-common/RouteDefinitions.ts
> +  toOrgResourcesGitOps: withAccountId(({ entity, orgIdentifier }: AccountLevelGitOpsPathProps & OrgPathProps) => {
why do we have a org-specific route here? 
if the resource only exists in org scope, we dont need to use `getScopeBasedRoute`.
And if the resource exists in multiple scopes, the route should not be specific to orgs.

2023-07-07 09:25 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +  // const showGitOpsCard = (accountId || orgIdentifier) && !projectIdentifier
can we remove the commented code.. we can add it back from git history when it's needed.

2023-07-07 09:25 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +        : routes.toAccountResourcesGitOps({ accountId, entity: 'agents' })
use the same route in both, and `getScopeBasedRoute` should handle the condition

2023-07-07 09:25 UTC, abhinavrastogi-harness commented on src/modules/90-gitops/RouteDestinations.tsx
> +      <GitOpsPage />
we don't need to render the same component again and again with different routes unless some props are different.
You can pass an array of routes to the `path` prop.

2023-07-07 09:49 UTC, ishantmehtaharness commented on src/modules/10-common/RouteDefinitions.ts
> +  toOrgResourcesGitOps: withAccountId(({ entity, orgIdentifier }: AccountLevelGitOpsPathProps & OrgPathProps) => {
Yes, I agree.. I have combined account and org level functions

2023-07-07 09:50 UTC, ishantmehtaharness commented on src/modules/90-gitops/RouteDestinations.tsx
> +      <GitOpsPage />
Interesting, I didnt know that, Although it was very straightforward, since its an array. I missed it. Thank You for pointing it out

2023-07-07 09:51 UTC, ishantmehtaharness commented on src/modules/90-gitops/RouteDestinations.tsx
> +      <GitOpsPage />
This also fixes already written code for account level.

2023-07-07 15:21 UTC, abhinavrastogi-harness approved these changes

2023-07-07 17:00 UTC, cjlee01 approved these changes

2023-07-07 17:10 UTC, sahithikolichala approved these changes

2023-07-07 17:19 UTC, merged