feat: [CHAOS-2009]: UI fixes for service discovery
harness/harness-core-ui pull request #16773
Opened 2023-07-06 13:04 UTC by amityt

### Summary

Fixes the following:

1. Disable discovery agent installation if not permitted
2. page is not refreshed after service discovery agent creation
3. show identity not auto generated id in discovery agent listing page
4. While api responding with non success code UI need to show it.. it is missing in discovery agent creation and network map creation page
5. Service resources page missing
6. Remove cluster info from service details

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-10 03:39 UTC, S-ayanide commented on src/modules/73-discovery/components/ServiceDetails/ServiceDetails.tsx
> +              //To be added
Let's remove commented code

2023-07-10 03:49 UTC, S-ayanide commented on src/modules/73-discovery/pages/network-map-studio/views/select-service/SelectService.tsx
>          showSuccess('Network Map Created Successfully')
Can we add this to strings.en

2023-07-10 03:50 UTC, S-ayanide commented on src/modules/73-discovery/pages/home/views/create-discovery-agent/CreateDAgent.tsx
> +      showError(error.data?.description || error.data?.message)
error's message could be an array in this case since there are multiple Yup validation, its better to map and do this instead. Please pull the latest changes for this update,

2023-07-10 03:51 UTC, S-ayanide reviewed
Please pull the latest changes and resolve the conflicts

2023-07-11 11:03 UTC, amityt commented on src/modules/73-discovery/pages/home/views/create-discovery-agent/CreateDAgent.tsx
> +      showError(error.data?.description || error.data?.message)
@S-ayanide , for Yup validation we are not throwing array of errors:

`const dAgentFormValdiation = await dAgentFormRef.current.validateForm()
        if (!isEmpty(dAgentFormValdiation)) {
          return showError(getString('discovery.dAgentCreateError'))
        }`

This is coming from the API call. Tested this locally as well.

2023-07-11 11:38 UTC, S-ayanide requested changes

2023-07-11 11:38 UTC, S-ayanide commented on src/modules/73-discovery/pages/home/views/create-discovery-agent/CreateDAgent.tsx
> +      showError(error.data?.description || error.data?.message)
Yes this was removed `dAgentCreateError` we were showing a generic error, but now instead we are throwing Yup errors

2023-07-11 11:38 UTC, S-ayanide commented on src/modules/73-discovery/pages/home/views/create-discovery-agent/CreateDAgent.tsx
> +      showError(error.data?.description || error.data?.message)
This to be specific

```
else {
      Object.values(errors).map(err => showError(err))
}

2023-07-11 12:08 UTC, S-ayanide approved these changes

2023-07-11 12:25 UTC, arkajyotiMukherjee approved these changes

2023-07-11 12:54 UTC, merged