fix: [CI-8735]: AIDA integration bug fix for pipelines with multiple failed steps
harness/harness-core-ui pull request #16784
Opened 2023-07-06 23:54 UTC by vardanbansal-harness

### Summary

1. Add missing `useEffect` dependencies.
2. Cancel in-progress api calls on change of a step.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-07 05:37 UTC, pankajsingh-harness requested changes

2023-07-07 05:37 UTC, pankajsingh-harness commented on src/modules/10-common/utils/utils.ts
> +export const isUserAbortedRequest = (err: unknown) => {
Pass signal in the request and then check for Abort Error. `The user aborted a request` this error message is from the browser and if the user has set a different browser language it will not work.

2023-07-07 15:50 UTC, vardanbansal-harness commented on src/modules/10-common/utils/utils.ts
> +export const isUserAbortedRequest = (err: unknown) => {
Done @pankajsingh-harness, thanks for the suggestion.

2023-07-10 11:39 UTC, pankajsingh-harness approved these changes

2023-07-10 17:06 UTC, ishantmehtaharness approved these changes
Looks Good Vardan

2023-07-10 17:07 UTC, merged