feat: [CET-1548] Update Error Tracking event list tab in CD to show e…
harness/harness-core-ui pull request #16878
Opened 2023-07-13 00:25 UTC by ricksjames

…vents related to the CD service, environment, and executionId.

### Summary

Update Error Tracking event list tab in CD to show events related to the CD service, environment, and executionId.

#### Screenshots

![Screenshot 2023-07-07 at 3 11 47 PM](https://github.com/harness/harness-core-ui/assets/972107/747fa373-d474-445b-8f47-1daae6cb9ba1)

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-13 13:26 UTC, ricksjames commented
retrigger cypress-cv

2023-07-14 01:47 UTC, abeg777 submitted a review, later dismissed

2023-07-14 03:32 UTC, pankajsingh-harness submitted a review, later dismissed

2023-07-14 04:49 UTC, rameshx requested changes

2023-07-14 04:49 UTC, rameshx commented on src/modules/70-pipeline/pages/execution/ExecutionErrorTrackingView/ExecutionErrorTrackingView.tsx
> +  const serviceIds = cdStageInfo?.serviceIdentifiers
Nit: `?.` is not needed as `cdStageInfo` will be `{}` if `pipelineExecutionDetail?.pipelineExecutionSummary?.moduleInfo?.cd` is falsy

2023-07-14 04:49 UTC, rameshx commented on src/modules/70-pipeline/pages/execution/ExecutionErrorTrackingView/ExecutionErrorTrackingView.tsx
> +      {module == 'ci' ? (
use `===`

2023-07-14 15:12 UTC, ricksjames commented on src/modules/70-pipeline/pages/execution/ExecutionErrorTrackingView/ExecutionErrorTrackingView.tsx
> +  const serviceIds = cdStageInfo?.serviceIdentifiers
fixed.

2023-07-14 15:12 UTC, ricksjames commented on src/modules/70-pipeline/pages/execution/ExecutionErrorTrackingView/ExecutionErrorTrackingView.tsx
> +      {module == 'ci' ? (
fixed.

2023-07-14 15:15 UTC, rameshx approved these changes

2023-07-14 15:19 UTC, abeg777 approved these changes

2023-07-14 15:26 UTC, merged

2023-07-14 15:27 UTC, knagurski commented
Force merged due to lack of coverage in untouched code.