fix: [CDS-73422]: modified ux for pipeline exec summary
harness/harness-core-ui pull request #16907
Opened 2023-07-14 19:22 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-17 22:36 UTC, sahithikolichala commented
modified ux 

<img width="1728" alt="Screenshot 2023-07-17 at 3 35 35 PM" src="https://github
<img width="1728" alt="Screenshot 2023-07-17 at 3 35 44 PM" src="https://github.com/harness/harness-core-ui/assets/57372986/e29c91ab-5b73-4036-8f09-6f119946471e">
.com/harness/harness-core-ui/assets/57
<img width="1726" alt="Screenshot 2023-07-17 at 3 36 01 PM" src="https://github.com/harness/harness-core-ui/assets/57372986/c6ec3886-63af-40e0-aa8d-e678694657cd">
372986/1ee526ec-5111-41da-a720-ebb5421f7811">

2023-07-17 22:36 UTC, sahithikolichala commented
<img width="1728" alt="Screenshot 2023-07-17 at 3 36 25 PM" src="https://github.com/harness/harness-core-ui/assets/57372986/3901804f-cb42-4a17-8f95-715fd8880d14">

2023-07-18 00:05 UTC, sahithikolichala commented
retrigger cypress-cv

2023-07-18 00:05 UTC, sahithikolichala commented
retrigger titlecheck

2023-07-18 04:37 UTC, rameshx requested changes

2023-07-18 04:37 UTC, rameshx commented on src/modules/70-pipeline/pages/execution/ExecutionPipelineView/ExecutionGraphView/ExecutionStageDetailsHeader/ExecutionStageDetailsHeader.tsx
> +              {stage?.name}sdfdsfds
remove

2023-07-18 04:37 UTC, rameshx commented on src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionMetadata/ExecutionMetadata.tsx
> +      <div className={`${classList}`} {...additionalAttrs}>
use `classnames`

2023-07-18 04:38 UTC, rameshx commented
@sahithikolichala Could you add before and after screenshots in the description?

2023-07-18 17:41 UTC, sahithikolichala commented
retrigger titlecheck

2023-07-18 17:42 UTC, sahithikolichala commented
@rameshx  added the screenshots before and after

2023-07-18 17:52 UTC, rameshx approved these changes

2023-07-18 18:17 UTC, sahithikolichala commented
retrigger cypress-cv

2023-07-18 18:47 UTC, srdjan-harness requested changes

2023-07-18 18:47 UTC, srdjan-harness commented on src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionMetadata/ExecutionMetadata.tsx
> +  const cIInfo = HAS_CI && ciData
to keep camel sase style maybe is better to have `ciInfo`

2023-07-18 18:47 UTC, srdjan-harness commented on src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionMetadata/ExecutionMetadata.tsx
> +    cIInfo || cdInfo
i would rather add var for this ciOrCdInfo or cicdInfo below `const cdInfo = HAS_CD && cdData` as condition is used in three places.

2023-07-18 19:22 UTC, srdjan-harness approved these changes

2023-07-18 19:24 UTC, rameshx approved these changes

2023-07-18 20:16 UTC, merged