feat: [CDS-74044]: Added support for post prod rollback in service v1 dashboard
harness/harness-core-ui pull request #16927
Opened 2023-07-17 21:43 UTC by Sagar-Rajput7

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-20 06:50 UTC, PratyushGar commented on src/modules/75-cd/strings/strings.en.yaml
> +    instanceDataEmptyOrMisMatch: Either the instance data is empty or there's a data mismatch. Please re-select the desired row and try again.
```suggestion
    instanceDataEmptyOrMismatch: Either the instance data is empty or there's a data mismatch. Please re-select the desired row and try again.
```

2023-07-20 06:50 UTC, PratyushGar commented on src/modules/75-cd/components/ServiceDetails/ActiveServiceInstances/InstancesDetails/InstancesDetailsDialog.tsx
> +        <div className="separator" style={{ marginTop: '14px', borderTop: '1px solid var(--grey-100)' }} />
Move styles to css

2023-07-20 07:37 UTC, Sagar-Rajput7 commented on src/modules/75-cd/strings/strings.en.yaml
> +    instanceDataEmptyOrMisMatch: Either the instance data is empty or there's a data mismatch. Please re-select the desired row and try again.
done

2023-07-20 07:37 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/ServiceDetails/ActiveServiceInstances/InstancesDetails/InstancesDetailsDialog.tsx
> +        <div className="separator" style={{ marginTop: '14px', borderTop: '1px solid var(--grey-100)' }} />
done

2023-07-20 07:38 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/ServiceDetails/ActiveServiceInstances/InstancesDetails/InstancesDetailsDialog.tsx
> +        <div className="separator" style={{ marginTop: '14px', borderTop: '1px solid var(--grey-100)' }} />
done

2023-07-20 11:56 UTC, PratyushGar approved these changes

2023-07-20 11:56 UTC, PratyushGar commented on src/modules/75-cd/components/ServiceDetails/ActiveServiceInstances/InstancesDetails/InstancesDetailsDialog.tsx
> +  //serviceType
nit: Do remove in subsequent PRs if not needed

2023-07-20 11:56 UTC, PratyushGar commented on src/modules/75-cd/components/ServiceDetails/ActiveServiceInstances/InstancesDetails/InstancesDetailsDialog.tsx
> +  const [rollbackInprogress, setRollbackInprogress] = useState<boolean>(false)
```suggestion
  const [rollbackInProgress, setRollbackInProgress] = useState<boolean>(false)
```

2023-07-20 12:11 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/ServiceDetails/ActiveServiceInstances/InstancesDetails/InstancesDetailsDialog.tsx
> +  //serviceType
I will update it to more descriptive comment

2023-07-20 12:24 UTC, rameshx requested changes

2023-07-20 12:24 UTC, rameshx commented on src/modules/75-cd/components/ServiceDetails/ActiveServiceInstances/InstancesDetails/InstancesDetailsDialog.tsx
> +    }
Updating the state directly in the body of useMemo is not recommended. Can this be moved to a change handler or an effect?

2023-07-20 12:24 UTC, rameshx commented on src/modules/75-cd/components/ServiceDetails/ActiveServiceInstances/ActiveServiceInstancesContentV2.tsx
> +  }
`JSON.stringify` does not preserve order. This can fail in some cases.

2023-07-20 17:10 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/ServiceDetails/ActiveServiceInstances/ActiveServiceInstancesContentV2.tsx
> +  }
done

2023-07-20 17:10 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/ServiceDetails/ActiveServiceInstances/InstancesDetails/InstancesDetailsDialog.tsx
> +    }
done

2023-07-20 17:10 UTC, Sagar-Rajput7 commented on src/modules/75-cd/components/ServiceDetails/ActiveServiceInstances/InstancesDetails/InstancesDetailsDialog.tsx
> +  const [rollbackInprogress, setRollbackInprogress] = useState<boolean>(false)
done

2023-07-21 03:55 UTC, rameshx approved these changes

2023-07-21 04:45 UTC, PratyushGar approved these changes

2023-07-21 05:28 UTC, merged