feat: [PL-38321]: Changed verify delegate text
harness/harness-core-ui pull request #16934
Opened 2023-07-18 08:23 UTC by avinashmadhwani02

### Summary

Text change required in verify delegate step.

JIRA - https://harness.atlassian.net/browse/PL-38321

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-18 08:41 UTC, avinashmadhwani02 commented
retrigger titlecheck

2023-07-18 10:37 UTC, mayankVermaHarness requested changes

2023-07-18 10:37 UTC, mayankVermaHarness commented on src/modules/30-delegates/strings/strings.en.yaml
> +  clickDoneAndCheckLater: Checking if the delegate is installed. It might take 1-2 minutes for the installation. Once installation is successful, your delegate will be populated on your your delegate
```suggestion
  clickDoneAndCheckLater: Checking if the delegate is installed. It might take 1-2 minutes for the installation. Once installation is successful, your delegate will be populated on your delegate listing page.
```

2023-07-18 10:39 UTC, mayankVermaHarness approved these changes

2023-07-19 05:35 UTC, sunnykesh-harness approved these changes

2023-07-19 05:41 UTC, merged