fix: [CDS-70014]: ordering support for infrastructures
harness/harness-core-ui pull request #16955
Opened 2023-07-19 04:20 UTC by satyam-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-31 07:04 UTC, satyam-harness commented
retrigger titlecheck

2023-08-02 06:24 UTC, rameshx requested changes
Use `{provided.placeholder}` at all places to prevent the container from collapsing when dragging.

2023-08-02 06:24 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/EnvironmentEntitiesList/EnvironmentEntitiesList.tsx
> +  }
As drag and drop will only change the order, a shallow clone of the array should work. Deep clones are not required here.

2023-08-02 06:24 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/InfrastructureEntitiesList/InfrastructureEntitiesList.tsx
> +  }
As drag and drop will only change the order, a shallow clone of the array should work. Deep clones are not required here.

You can use `produce` to avoid deep cloning `values`.

2023-08-02 06:24 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/InfrastructureEntitiesList/InfrastructureEntitiesList.tsx
> +              </div>
`{provided.placeholder}` needs to be used to prevent the container from collapsing when dragging an item. See https://github.com/harness/harness-core-ui/blob/225c59025e3c3c8da8ecddfe30e720c99b1b2290/src/modules/75-cd/components/PipelineSteps/CommandScripts/CommandList.tsx#L152

2023-08-03 11:40 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/InfrastructureEntitiesList/InfrastructureEntitiesList.tsx
> +              </div>
addressed

2023-08-03 11:40 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/EnvironmentEntitiesList/EnvironmentEntitiesList.tsx
> +  }
addressed

2023-08-03 13:20 UTC, rameshx requested changes

2023-08-03 13:20 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineInputSetForm/EnvironmentsInputSetForm/__tests__/SingleEnvironmentInputSetForm/selectRuntimeEnv.test.tsx
> +  test.skip('environment with multiple input types is selected with infra', async () => {
I'm unsure why this test is skipped, but let's ensure this case is not breaking in the UI.

2023-08-03 13:20 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/EnvironmentEntitiesList/EnvironmentEntitiesList.tsx
> +    })
draft should not be used directly, use the value returned by produce

2023-08-03 13:20 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/InfrastructureEntitiesList/InfrastructureEntitiesList.tsx
> +    infraList.splice(destinationIndex, 0, itemToMove[0])
`cloneDeep` is not needed. Use spread syntax or `clone`.

2023-08-03 13:20 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/InfrastructureEntitiesList/InfrastructureEntitiesList.tsx
> +    })
Update this to something like this:
```suggestion
    const updatedValues = produce(values, draft => {
    set(draft, `infrastructures.${environmentIdentifier}`, infraList)
    })
    setSelectedInfrastructures && setSelectedInfrastructures(getAllFixedInfrastructures(updatedValues, environmentIdentifier))
```

2023-08-03 13:20 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/EnvironmentEntitiesList/EnvironmentEntitiesList.tsx
> +    const environmentsList = cloneDeep(values.environments) as SelectOption[]
`cloneDeep` is not required

2023-08-03 13:20 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/EnvironmentEntitiesList/EnvironmentEntityCard/EnvironmentEntityCard.tsx
> +      {provided => {
Ensure `{provided.placeholder}` is not needed here.

2023-08-03 13:20 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/InfrastructureEntitiesList/InfrastructureEntityCard.tsx
> +      {provided => {
Ensure `{provided.placeholder}` is not needed here.

2023-08-04 04:17 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/InfrastructureEntitiesList/InfrastructureEntityCard.tsx
> +      {provided => {
I think for `Draggable` `{provided.placeholder}` is not supported, its only supported in `Droppable`

2023-08-04 05:44 UTC, satyam-harness commented
retrigger cypress-cv

2023-08-04 07:16 UTC, rameshx submitted a review, later dismissed

2023-08-04 08:16 UTC, satyam-harness commented on src/modules/70-pipeline/components/PipelineInputSetForm/EnvironmentsInputSetForm/__tests__/SingleEnvironmentInputSetForm/selectRuntimeEnv.test.tsx
> +  test.skip('environment with multiple input types is selected with infra', async () => {
fixed

2023-08-04 08:49 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureEntityStep/DeployInfrastructureEntityInputStep.tsx
> +  console.log('infrastructuresList', { infrastructuresList })
let's remove this

2023-08-04 08:54 UTC, rameshx submitted a review, later dismissed

2023-08-04 10:29 UTC, chetanvekariya-harness approved these changes

2023-08-04 11:15 UTC, rameshx approved these changes

2023-08-08 05:55 UTC, satyam-harness commented
trigger rebase

2023-08-08 06:47 UTC, satyam-harness commented
retrigger cypress-cv

2023-08-08 07:53 UTC, satyam-harness commented
UT coverage ticket https://harness.atlassian.net/browse/CDS-76658

2023-08-08 08:44 UTC, merged