feat: [CDS-70212]:multiple manifests
harness/harness-core-ui pull request #16961
Opened 2023-07-19 06:31 UTC by litvinovstas

### Summary
Multiple manifest

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-21 08:03 UTC, litvinovstas commented
retrigger titlecheck

2023-07-24 08:58 UTC, litvinovstas commented
retrigger cypress-cv

2023-07-24 10:00 UTC, chetanvekariya-harness approved these changes

2023-07-24 10:00 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestSelection.tsx
> +  const isKubernetesOrNativeHelm = React.useMemo(() => {
This is not needed as it is not doing any heavy calculation.

2023-07-24 10:00 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/GoogleCloudFunctionServiceSpecEditable.test.tsx
> +  jest.spyOn(FeatureFlag, 'useFeatureFlags').mockReturnValue({
You can pass this to TestWrapper component directly. We should not mock values like this.

2023-07-24 10:00 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/K8sServiceSpec.tsx
> +  protected defaultValues: KubernetesServiceSpec = {
This makes primaryManifestRef as Runtime input for all deployments which are using this component. Is this intended ?

2023-07-24 10:00 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestListView/ManifestListViewMultiple.tsx
> +function ManifestListViewMultiple({
This component is same as other component with few additions. Can't we use existing component instead of creating new one?

2023-07-24 10:00 UTC, chetanvekariya-harness reviewed
Please check comments.

2023-07-24 12:28 UTC, jenil-harness approved these changes

2023-07-24 12:56 UTC, chetanvekariya-harness requested changes
Could you please address or response to comments.

2023-07-24 13:16 UTC, litvinovstas commented on src/modules/75-cd/components/PipelineSteps/GoogleCloudFunction/GoogleCloudFunctionServiceSpec/__tests__/GoogleCloudFunctionServiceSpecEditable.test.tsx
> +  jest.spyOn(FeatureFlag, 'useFeatureFlags').mockReturnValue({
it will be improved in next coverage pr.

2023-07-24 13:16 UTC, litvinovstas commented on src/modules/70-pipeline/components/ManifestSelection/ManifestSelection.tsx
> +  const isKubernetesOrNativeHelm = React.useMemo(() => {
it will be improved in next coverage pr.

2023-07-24 13:17 UTC, chetanvekariya-harness approved these changes

2023-07-24 13:17 UTC, litvinovstas commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/K8sServiceSpec.tsx
> +  protected defaultValues: KubernetesServiceSpec = {
By default value not including in service.

2023-07-24 13:18 UTC, litvinovstas commented on src/modules/70-pipeline/components/ManifestSelection/ManifestListView/ManifestListViewMultiple.tsx
> +function ManifestListViewMultiple({
New disegn , big changes, and new compoennt.

2023-07-24 13:46 UTC, merged