feat: [CDS-74583]:Fixed-issue-with-empty-variables-field
harness/harness-core-ui pull request #17112
Opened 2023-07-27 06:21 UTC by litvinovstas

### Summary
Fixed issue with unsaved empty array for variables in stage. in overview tab advanced section.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-27 12:00 UTC, rameshx requested changes

2023-07-27 12:00 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/CustomVariables/CustomVariables.tsx
> +        : (undefined as unknown as AllNGVariables[])
This doesn't look right. If `variables` can be undefined, we should update `CustomVariablesData` to make `variables` optional.

2023-07-27 12:01 UTC, litvinovstas commented on src/modules/70-pipeline/components/PipelineSteps/Steps/CustomVariables/CustomVariables.tsx
> +/* istanbul ignore next */
it should be covered by jest in separated pr.

2023-07-27 12:04 UTC, litvinovstas commented on src/modules/70-pipeline/components/PipelineSteps/Steps/CustomVariables/CustomVariables.tsx
> +        : (undefined as unknown as AllNGVariables[])
improved

2023-07-27 12:15 UTC, satyam-harness submitted a review, later dismissed

2023-07-27 12:35 UTC, rameshx submitted a review, later dismissed

2023-07-27 12:39 UTC, Sagar-Rajput7 approved these changes

2023-07-28 08:17 UTC, d1wilko approved these changes
some suggestions but not worth holding up the PR for :)

2023-07-28 08:17 UTC, d1wilko commented on src/modules/70-pipeline/components/PipelineSteps/Steps/CustomVariables/CustomVariableEditable.tsx
> +                    values.variables?.length > 0 && (
not an issue but I think you could get away with `values?.variables?.length && (` here

2023-07-28 08:17 UTC, d1wilko commented on src/modules/70-pipeline/components/PipelineSteps/Steps/CustomVariables/CustomVariableInputSet.tsx
> +      {initialValues?.variables && initialValues.variables?.length > 0 && (
same as above but not worth holding up the PR for

2023-07-28 08:17 UTC, d1wilko commented on src/modules/70-pipeline/components/PipelineSteps/Steps/CustomVariables/CustomVariablesEditableStage.tsx
> +                  {values?.variables && values.variables?.length > 0 ? (
same as above

2023-07-28 08:17 UTC, d1wilko commented on src/modules/75-ci/components/PipelineStudio/BuildStageSpecifications/BuildStageSpecifications.tsx
> +        if (values?.variables && values.variables?.length > 0) {
same as above

2023-07-28 09:00 UTC, rameshx approved these changes

2023-07-28 09:26 UTC, satyam-harness approved these changes

2023-07-28 11:07 UTC, merged