fix: CDS-74852
harness/harness-core-ui pull request #17118
Opened 2023-07-27 10:17 UTC by MondalSayantan

### Summary

Fixed issue when switching from runtime value to fixed value, default values are set in shell and image field.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-27 10:29 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineSteps/ContainerStep/ContainerStepInputSet.tsx
> +                formik.setFieldValue(`${prefix}spec.shell`, 'Sh')
is it 'Shell' or 'Sh' ?

2023-07-27 10:31 UTC, MondalSayantan commented on src/modules/75-cd/components/PipelineSteps/ContainerStep/ContainerStepInputSet.tsx
> +                formik.setFieldValue(`${prefix}spec.shell`, 'Sh')
![image](https://github.com/harness/harness-core-ui/assets/62999423/98de48ed-208b-4307-a95d-ea1bd60730b4)
Should be 'Sh'

2023-07-27 10:37 UTC, MondalSayantan commented on src/modules/75-cd/components/PipelineSteps/ContainerStep/ContainerStepInputSet.tsx
> +                formik.setFieldValue(`${prefix}spec.shell`, 'Sh')
![image](https://github.com/harness/harness-core-ui/assets/62999423/da13daa2-f047-45d8-af3c-b2bef48a3470)

2023-07-27 13:22 UTC, chetanvekariya-harness requested changes

2023-07-27 13:22 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ContainerStep/ContainerStepInputSet.tsx
> +        onChange={val => {
There is nothing specific about these fields so that they might not work. This has to be issue with all the fields, mostly likely only in TemplateUsage view. Let's try to fix this at one place and generically.

2023-07-28 06:10 UTC, MondalSayantan commented
This seems to be a bigger issue of pipeline validation after discussing with @chetanvekariya-harness. I am closing this PR for now.

2023-07-28 06:10 UTC, closed without merging