feat: [CDS-74523]: add validations for remote input set selection across multiple panels
harness/harness-core-ui pull request #17137
Opened 2023-07-27 15:50 UTC by Eric761

### Summary

Customer does not require feature branch selection at this time. All we need to do now is improve our validation and error handling for remote Input set selection.

Ticket: https://harness.atlassian.net/browse/CDS-74523
Parent Ticket: https://harness.atlassian.net/browse/CDS-71997

- Every time a `remote InputSet` is chosen, we validate it and display a spinner while doing so.
- If not found in current git context :
     - Appropriate error message will be displayed
     - Checkbox will be unchecked and disabled. 
- If found in the current git context, check icon will be displayed.
- Only after all validations have been successful, Apply Input Set button will be enabled.

#### Screenshots

<img width="1728" alt="Screenshot 2023-07-28 at 1 48 32 PM" src="https://github.com/harness/harness-core-ui/assets/73639897/c8fcddaa-3960-4393-b272-3f031179c932">

#### Demo Video

https://github.com/harness/harness-core-ui/assets/73639897/3e1ae47f-6950-479d-b43c-b1d16933ffe1

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-28 10:32 UTC, vikrant-harness submitted a review, later dismissed

2023-07-28 11:59 UTC, sunnykesh-harness submitted a review, later dismissed

2023-07-28 12:15 UTC, rameshx requested changes

2023-07-28 12:15 UTC, rameshx commented on src/modules/70-pipeline/components/InputSetSelector/InputSetSelector.module.scss
> +  width: 550px !important;
let's increase this to 600

2023-07-28 12:15 UTC, rameshx commented on src/modules/70-pipeline/components/InputSetSelector/InputSetSelector.tsx
> +    for (const inputSetErrorMetaData of inputSetErrorMap.values()) {
use `Array.prototype.some`

2023-07-28 12:15 UTC, rameshx commented on src/modules/70-pipeline/components/InputSetSelector/InputSetSelector.tsx
> +        removeInvalidInputSet(prevSelectedInputSets, inputSetId, inputSetContainsError)
If `inputSetContainsError` is false then directly return the previous state. Only call `removeInvalidInputSet` when removal is necessary. After this, `removeInvalidInputSet` doesn't need the arg `inputSetContainsError`.

2023-07-28 12:15 UTC, rameshx commented on src/modules/70-pipeline/components/InputSetSelector/InputSetSelector.tsx
> +      })
same as above

2023-07-28 12:15 UTC, rameshx commented on src/modules/70-pipeline/components/InputSetSelector/utils.ts
> +  return clonedInputSets
Optimize this to remove the item in one loop.

2023-08-16 15:06 UTC, satyam-harness approved these changes

2023-08-16 15:23 UTC, Eric761 commented on src/modules/70-pipeline/components/InputSetSelector/utils.ts
> +  return clonedInputSets
done

2023-08-16 15:27 UTC, rameshx approved these changes

2023-08-16 15:27 UTC, rameshx commented on src/modules/70-pipeline/components/InputSetSelector/utils.ts
> +  remove(clonedInputSets, set => set.value === inputSetId)
`Array.prototype.filter` can be used to do this in one loop, but this is fine and much better than the previous code.

2023-08-16 15:36 UTC, merged