fix: [CI-8885]: delete codebase properties only if no CI stage/template with co…
harness/harness-core-ui pull request #17264
Opened 2023-08-03 13:54 UTC by shaurya-harness

### Summary

delete codebase properties only if no CI stage/template with codebase enabled

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-03 15:47 UTC, d1wilko submitted a review, later dismissed
LGTM :)

2023-08-03 15:56 UTC, vardanbansal-harness submitted a review, later dismissed

2023-08-03 19:36 UTC, PratyushGar commented on src/modules/70-pipeline/components/PipelineStudio/StageBuilder/StageBuilder.tsx
> +
We have resolvedPipeline present in `PipelineVariableContextProvider`

`const { originalPipeline } = usePipelineVariables()`

Can you please check, this should provide the resolved original pipeline directly, fetching and parsing should not be required here?

2023-08-03 19:49 UTC, PratyushGar commented on src/modules/75-ci/components/PipelineStudio/BuildStageSetupShell/BuildStageSetupShell.tsx
> +  })
We have resolvedPipeline present in `PipelineVariableContextProvider`

Can you please check if that can be used directly?

2023-08-03 20:01 UTC, PratyushGar requested changes

2023-08-03 20:01 UTC, PratyushGar commented on src/modules/75-ci/components/PipelineStudio/BuildStageSetupShell/BuildStageSetupShell.tsx
> +
We have resolvedPipeline present in `PipelineVariableContextProvider`

Can you please check if that can be used directly, as an API call would happen on each key change in pipeline YAML? 

If not, instead can we check for CI stage property and templateRef (addition/deletion change) only to make an API call, this will avoid unnecessary API calls

2023-08-04 06:10 UTC, vardanbansal-harness submitted a review, later dismissed

2023-08-04 09:09 UTC, d1wilko submitted a review, later dismissed

2023-08-07 07:23 UTC, PratyushGar approved these changes

2023-08-07 07:23 UTC, PratyushGar commented on src/modules/70-pipeline/components/PipelineStudio/StageBuilder/StageBuilderUtil.ts
>    })
nit: .some can be used for early exit to avoid iterations for pipeline with many stages
```suggestion
  return !pipeline?.stages?.some(stage => {
    const templateRef = stage.stage?.template?.templateRef
    return stage.stage?.type === 'CI' || (templateRef && templateTypes[templateRef] === 'CI')
  })
```

2023-08-07 08:14 UTC, d1wilko approved these changes
LGTM

2023-08-07 17:03 UTC, d1wilko approved these changes
LGTM

2023-08-08 05:05 UTC, merged