feat: [CODE-713]: Expose Gitness API service to harness-core-ui
harness/harness-core-ui pull request #17289
Opened 2023-08-04 20:09 UTC by tan-nhu

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-04 20:12 UTC, tan-nhu commented
retrigger titlecheck

2023-08-06 14:23 UTC, shaurya-harness submitted a review, later dismissed

2023-08-07 15:12 UTC, abhinavrastogi-harness requested changes

2023-08-07 15:12 UTC, abhinavrastogi-harness commented on configs/restful-react.config.js
> +  code: {
can we use the new openapi client instead?
once we add this, it'll take many quarters to get it removed again due to code dependencies.

2023-08-07 15:12 UTC, abhinavrastogi-harness commented on src/services/code/overrides.yaml
> +allowpaths: ['*']
why are all paths being added? we should allow only the used paths to optimise what we ship.

2023-08-07 15:12 UTC, abhinavrastogi-harness commented on src/services/code/swagger.yaml
can we avoid committing the api spec? it bloats the repo unnecessarily.

2023-08-07 17:31 UTC, tan-nhu commented on configs/restful-react.config.js
> +  code: {
We are using restful-react in Gitness, eventually we'll migrate to the new openapi at some point, but it needs to come from Gitness first. Right now, I don't want to make it complicated for the teams to work on with two sets of API calls.

2023-08-07 19:11 UTC, tan-nhu commented on src/services/code/overrides.yaml
> +allowpaths: ['*']
Added allowPaths to `repos` only for now.

2023-08-07 19:13 UTC, tan-nhu commented on src/services/code/swagger.yaml
I don't think we should remove the spec. It's there to keep track of changes from API side.

2023-08-07 22:34 UTC, abhinavrastogi-harness commented on src/services/code/swagger.yaml
APi changes will reflect in the generated service automatically. 
You can add it to `.gitignore` if you still want to keep it in the repo.
Do you see any specific benefits from committing the API spec?

2023-08-07 22:36 UTC, abhinavrastogi-harness commented on configs/restful-react.config.js
> +  code: {
It'll still be the same API even if it's a different client. I don't think we are planning to pass these hooks down to the microfrontend, right? Gitness MFE  already has it's own clients generated.

When is Gitness planned to be migrated to OpenAPI?
Why is this service needed in NGUI in the first place?

2023-08-08 00:02 UTC, tan-nhu commented on src/services/code/swagger.yaml
The spec is used as a reference what is changed from backend side (the source), not what is generated (the output). It's used to communicate as the source of truth from backend. Let's say if backend publishes some breaking changes, without the source, you can't tell and track back. 

Versioning is important.

2023-08-08 00:06 UTC, tan-nhu commented on configs/restful-react.config.js
> +  code: {
It's not the same API if you have naming different.

`When is Gitness planned to be migrated to OpenAPI?`

No date specified. I don't think Gitness is any different than other API services currently under resful-react.

`Why is this service needed in NGUI in the first place?`

It's for CIE integration. CIE needs a way to call Gitness APIs directly.

2023-08-08 16:17 UTC, hitesharinga commented
Approving since CI team is waiting for this.

2023-08-08 16:55 UTC, merged