chore: [CDS-73844]: add allowed values ability to manifest fields
harness/harness-core-ui pull request #17334
Opened 2023-08-09 14:28 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-10 14:50 UTC, pankajsingh-harness submitted a review, later dismissed

2023-08-10 14:50 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/AbstractSteps/List/__tests__/List.test.tsx
> +      <Formik initialValues={initialValues} onSubmit={() => {}} formName="TestWrapper">
Instead of disabling the no-empty-function here. We can use `onSubmit={jest.fn()}`

2023-08-10 15:10 UTC, rameshx requested changes

2023-08-10 15:10 UTC, rameshx commented on src/modules/70-pipeline/components/AbstractSteps/List/List.tsx
This should not be inside `AbstractSteps`. Please move the `List` folder to `src/modules/70-pipeline/components`.

2023-08-10 15:10 UTC, rameshx commented on src/modules/70-pipeline/components/AbstractSteps/List/List.tsx
> +                    fieldPath={fieldPath!}
`fieldPath` is optional at the type level, ensure this doesn't cause a runtime error

2023-08-10 15:10 UTC, rameshx commented on src/modules/70-pipeline/components/AbstractSteps/List/List.tsx
> +                    fieldPath={fieldPath!}
or make `fieldPath` required

2023-08-14 10:19 UTC, namanharness commented on src/modules/70-pipeline/components/AbstractSteps/List/List.tsx
> +                    fieldPath={fieldPath!}
this shouldnt cause runtime error because , if fieldPath is not provided it will provide an empty array ⬇️ 
, so can we keep this as optional @rameshx ?

<img width="876" alt="image" src="https://github.com/harness/harness-core-ui/assets/110456765/8e3a5d34-e09f-4a99-befc-31848948cfa1">

2023-08-14 12:48 UTC, chetanvekariya-harness approved these changes

2023-08-14 12:48 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/List/List.tsx
> +                    fieldPath={fieldPath!}
Why `!` at the end ?
`fieldPath={fieldPath}` should be good enough or we can pass something falsy as default value, so that it is more readable.

2023-08-14 12:48 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/List/List.tsx
> +                  <TextFieldInputSetView
We always need to render this component even if individual field are not expression. Please make sure this is working properly. From code it looks like it might work only for expressions.

2023-08-14 12:48 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/List/__tests__/List.test.tsx
> +      {/* eslint-disable-next-line @typescript-eslint/no-empty-function */}
nit: this can be removed now since you fixed the issue.

2023-08-14 12:48 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/CustomRemoteManifest/CustomRemoteManifest.tsx
> +                        onChange={/* istanbul ignore next */ value => formik.setFieldValue('extractionScript', value)}
Is this intended?

2023-08-15 06:29 UTC, namanharness commented on src/modules/70-pipeline/components/List/List.tsx
> +                  <TextFieldInputSetView
expressions here is an array ⬇️  
so according to logic when expressions is empty array we have to return the component when expressions is empty else return TextFieldInputView 
<img width="760" alt="image" src="https://github.com/harness/harness-core-ui/assets/110456765/b4f630f1-7323-4469-9c36-013485f4fe22">

2023-08-15 07:00 UTC, namanharness commented on src/modules/70-pipeline/components/List/List.tsx
> +                  <TextFieldInputSetView
although from further debugging i observed that we are taking expressions from a hook and then using it , so @chetanvekariya-harness you can tell me the approach to handle this , i will update it accordingly

2023-08-17 04:44 UTC, sonaligoyal-harness approved these changes

2023-08-17 04:45 UTC, merged