fix: [CDS-76291]: add banner to prevent user to aid in setting up the barrier
harness/harness-core-ui pull request #17350
Opened 2023-08-10 11:08 UTC by Eric761

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-10 12:05 UTC, rameshx requested changes

2023-08-10 12:05 UTC, rameshx commented on src/modules/70-pipeline/strings/strings.en.yaml
> +  infoLink: https://developer.harness.io/docs/continuous-delivery/x-platform-cd-features/cd-steps/flow-control/synchronize-deployments-using-barriers/
This should not be in strings. Define a constant in any util or constants file

2023-08-10 12:05 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Barrier/Barrier.module.scss
> +  span[data-icon='info'] {
Let's pass `className` to `<Icon />`

2023-08-10 12:37 UTC, Eric761 commented on src/modules/70-pipeline/components/PipelineSteps/Steps/Barrier/Barrier.module.scss
> +  span[data-icon='info'] {
done

2023-08-10 12:47 UTC, Eric761 commented on src/modules/70-pipeline/strings/strings.en.yaml
> +  infoLink: https://developer.harness.io/docs/continuous-delivery/x-platform-cd-features/cd-steps/flow-control/synchronize-deployments-using-barriers/
done @rameshx

2023-08-10 13:00 UTC, rameshx submitted a review, later dismissed

2023-08-10 14:32 UTC, pankajsingh-harness submitted a review, later dismissed

2023-08-11 10:18 UTC, rameshx approved these changes

2023-08-11 13:13 UTC, pankajsingh-harness approved these changes

2023-08-11 15:52 UTC, PratyushGar approved these changes

2023-08-12 05:23 UTC, merged