feat: [CDS-74988]: Add support of activity history page for artifact trigger type
harness/harness-core-ui pull request #17365
Opened 2023-08-10 21:09 UTC by sonaligoyal-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-11 08:37 UTC, vikrant-harness reviewed
The Text color in the popover looks odd , is this approved by design team ?

2023-08-11 09:04 UTC, sonaligoyal-harness commented
Yes, it was approved by team.

2023-08-11 09:39 UTC, samarth-sharma31 commented on src/modules/72-triggers/pages/triggers/views/TriggersListSection.tsx
> +    data.type !== TriggerTypes.SCHEDULE && data.type !== TriggerTypes.WEBHOOK && data.type !== 'Artifact'
Can we use the trigger types (TriggerTypes.ARTIFACT) const which is already present instead of strings at all places
export const TriggerTypes = {
  WEBHOOK: 'Webhook',
  NEW_ARTIFACT: 'NewArtifact',
  SCHEDULE: 'Scheduled',
  MANIFEST: 'Manifest',
  ARTIFACT: 'Artifact',
  MULTIREGIONARTIFACT: 'MultiRegionArtifact'
}

This is present in file -> src/modules/72-triggers/pages/triggers/utils/TriggersWizardPageUtils.ts


Benefits -->
It makes code more maintainable and scalable for future as we exactly know the usages

2023-08-11 09:39 UTC, samarth-sharma31 commented on src/modules/72-triggers/pages/triggers/utils/TriggersListUtils.ts
> +  triggerType !== 'Scheduled' && triggerType !== 'Webhook' && triggerType !== 'Artifact'
https://github.com/harness/harness-core-ui/pull/17365/files#r1291123916

2023-08-11 09:39 UTC, samarth-sharma31 commented on src/modules/72-triggers/pages/triggers/utils/TriggerActivityUtils.tsx
> +        value={selectedTriggerType === 'Artifact' ? selectedPayloadRow : payloadValue()}
https://github.com/harness/harness-core-ui/pull/17365/files#r1291123916

2023-08-11 12:56 UTC, sonaligoyal-harness commented on src/modules/72-triggers/pages/triggers/views/TriggersListSection.tsx
> +    data.type !== TriggerTypes.SCHEDULE && data.type !== TriggerTypes.WEBHOOK && data.type !== 'Artifact'
Sure will update this.
As it was well maintained because of typescript so used it that way.
But will update it in next PR which is related to TriggerExplorer .

2023-08-11 13:06 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/TriggerLandingPage/TriggerActivityHistoryPage/TriggerActivityList.tsx
> +    if (selectedTriggerType === 'Artifact') {
We need to add `MultiRegionArtifact` with or condition here. As BE is treating both of them separately but in UI we treat them in similar manner.

2023-08-11 13:06 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/TriggerLandingPage/TriggerActivityHistoryPage/TriggerActivityList.tsx
> +    if (selectedTriggerType === 'Artifact') {
`type?: 'Webhook' | 'Artifact' | 'Manifest' | 'Scheduled' | 'MultiRegionArtifact'` this is there in `NGTriggerEventHistoryResponse`

2023-08-11 13:06 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/utils/TriggerActivityUtils.tsx
> +        value={selectedTriggerType === 'Artifact' ? selectedPayloadRow : payloadValue()}
This is properly defined in `type?: 'Webhook' | 'Artifact' | 'Manifest' | 'Scheduled' | 'MultiRegionArtifact'`. So we should use string only. Not the enum type.

2023-08-11 13:06 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/utils/TriggersListUtils.ts
> +  triggerType !== 'Scheduled' && triggerType !== 'Webhook' && triggerType !== 'Artifact'
Same as above.

2023-08-11 13:06 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/TriggerLandingPage/TriggerActivityHistoryPage/TriggerActivityList.tsx
> +    if (selectedTriggerType === 'Artifact') {
```suggestion
    if (selectedTriggerType === 'Artifact' || selectedTriggerType === 'MultiRegionArtifact') {
```

2023-08-11 13:07 UTC, pankajsingh-harness requested changes
We need to add `MultiRegionArtifact` type check also

2023-08-16 08:24 UTC, pankajsingh-harness requested changes

2023-08-16 08:24 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/utils/TriggerActivityUtils.tsx
> +        value={selectedTriggerType === 'Artifact' ? selectedPayloadRow : payloadValue()}
@sonaligoyal-harness, here We need to add check for MultiRegionArtifact also

2023-08-16 10:19 UTC, pankajsingh-harness approved these changes

2023-08-16 10:48 UTC, Eric761 approved these changes

2023-08-16 10:48 UTC, merged