feat: [CDS-77006]: added changeRequest number field for change Task
harness/harness-core-ui pull request #17415
Opened 2023-08-15 19:58 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-29 05:06 UTC, pankajsingh-harness requested changes

2023-08-29 05:06 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/helper.ts
> +export const processFormData = (values: ServiceNowUpdateData, onSubmit = false): ServiceNowUpdateData => {
Rename this properly.

2023-08-29 05:06 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/helper.ts
> +  const updateMultipleObj = values.spec?.updateMultiple
Is this change for both types of templates?

2023-08-29 05:16 UTC, sonaligoyal-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/ServiceNowUpdateStepMode.tsx
> +  const taskTypeOptions: SelectOption[] = [
Is this list fixed and independent of metadata api?

2023-08-29 18:43 UTC, sahithikolichala commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/ServiceNowUpdateStepMode.tsx
> +  const taskTypeOptions: SelectOption[] = [
yes it is fixed

2023-08-29 18:44 UTC, sahithikolichala commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/helper.ts
> +export const processFormData = (values: ServiceNowUpdateData, onSubmit = false): ServiceNowUpdateData => {
what do you mean by renaming?

2023-08-29 18:45 UTC, sahithikolichala commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/helper.ts
> +  const updateMultipleObj = values.spec?.updateMultiple
yes!

2023-08-30 06:00 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/helper.ts
> +export const processFormData = (values: ServiceNowUpdateData, onSubmit = false): ServiceNowUpdateData => {
Rename `onSubmit` properly. `onSubmit ` seems to be a function but here it is boolean. We can rename this to some boolean variable.
https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

2023-09-11 14:00 UTC, sahithikolichala commented
> @sahithikol are we supporting runtime option for these fields? if yes, then we need to update deployment mode file of servicenow update and approval steps. CC: @pankajsingh-harness
@sonaligoyal-harness  for now no runtime support for these yet

2023-09-12 04:36 UTC, pankajsingh-harness requested changes
Make sure to have proper field name to match with the interface. There seems to be mismatch with spec with updateMultiple

2023-09-12 04:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/ServiceNowUpdateStepMode.tsx
> +      value: getString('pipeline.taskOptions.planning')
The value should be in sync with BE. Please check with BE if they are using the same values. Also label may change but the value should not. So keep values fixed.

2023-09-12 04:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/ServiceNowUpdateStepMode.tsx
> +                  <FormInput.MultiTextInput
Do we need not to support allowed values in this flow? Ideally we should. Please pass allowed values-related fields if we need to support allowed values.

2023-09-12 04:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/ServiceNowUpdateStepMode.tsx
> +                      onChange={value => formik.setFieldValue('spec.updateMultiple.spec.changeRequestNumber', value)}
We should set the same field as the runtime field. Here we are checking for different field for runtime and setting value of different field.

2023-09-12 04:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/ServiceNowUpdateStepMode.tsx
> +                  {getMultiTypeFromValue(formik.values.spec?.updateMultiple?.changeTaskType) ===
```suggestion
                  {getMultiTypeFromValue(formik.values.spec?.updateMultiple?.spec?.changeTaskType) ===
```

2023-09-12 04:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/ServiceNowUpdateStepMode.tsx
> +                    name={`spec.updateMultiple.spec.changeRequestNumber`}
```suggestion
                    name={`spec.updateMultiple.changeRequestNumber`}
```
Make sure name matches with the interface.

2023-09-12 04:36 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/ServiceNowUpdateStepMode.tsx
> +                      variableName="spec.updateMultiple.spec.changeRequestNumber"
```suggestion
                      variableName="spec.updateMultiple.changeRequestNumber"
```

2023-09-15 04:48 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/ServiceNowUpdateStepMode.tsx
> +        {(formik.values.spec.ticketType === TaskTypes.CHANGE_TASK && !formik.values?.spec?.updateMultipleFlag) ||
Is the `spec` value always present? If `spec` can be undefined anyway this will break the page due to an undefined error.

2023-09-15 04:48 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/ServiceNowUpdateStepMode.tsx
> +        {formik.values.spec.ticketType === TaskTypes.CHANGE_TASK && CDS_NG_UPDATE_MULTIPLE_SNOW_CHANGE_REQUEST ? (
Same as above

2023-09-15 04:48 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/helper.ts
> +export const processFormData = (values: any, fromSubmit = false): ServiceNowUpdateData => {
Why this `values: any` change? We have proper type before

2023-09-15 04:48 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/types.ts
> +export interface SnowUpdateData extends StepElementConfig {
Why is this new interface needed? Do you know if we can't use the existing one? `ServiceNowUpdateData`

2023-09-15 04:53 UTC, pankajsingh-harness commented
Also check @sonaligoyal-harness comment here: https://github.com/harness/harness-core-ui/pull/17415#issuecomment-1698600706

2023-09-15 09:09 UTC, pankajsingh-harness submitted a review, later dismissed

2023-09-19 06:10 UTC, pankajsingh-harness approved these changes

2023-09-19 16:38 UTC, sahithikolichala commented
retrigger cypress-pipeline

2023-09-20 04:19 UTC, pankajsingh-harness approved these changes

2023-09-20 05:01 UTC, rameshx approved these changes

2023-09-20 05:01 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineSteps/Steps/ServiceNowUpdate/types.ts
> +export enum TaskTypes {
enum should be singular
```suggestion
export enum TaskType {
```

2023-09-20 14:53 UTC, merged