fix: [PL-39198]: add organizations API search to create project page
harness/harness-core-ui pull request #17597
Opened 2023-08-28 05:03 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-28 07:43 UTC, mayankVermaHarness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/ProjectForm.tsx
> +                        console.log('eadf', e)
remove log

2023-08-29 13:11 UTC, pankajsingh-harness requested changes

2023-08-29 13:11 UTC, pankajsingh-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/CreateProject.tsx
> +        refetchOrg={refetchOrg}
Instead of passing `refetchOrg` use useEffect hook on `orgSearchTerm` and `refetchOrg`

2023-08-29 13:11 UTC, pankajsingh-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/CreateProject.tsx
> +    debounce: 300
```suggestion
    debounce: 300
    lazy: true
```

2023-08-29 13:11 UTC, pankajsingh-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/CreateProject.tsx
> +    debounce: 300
```
useEffect(() => { refetchOrg() }, [orgSearchTerm])
```

2023-08-29 13:11 UTC, pankajsingh-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/CreateProject.tsx
> +        refetchOrg={refetchOrg}
useEffect(() => { refetchOrg() }, [orgSearchTerm])

2023-08-29 13:13 UTC, chetanvekariya-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/CreateProject.tsx
> +    debounce: 300
+1

2023-08-29 15:20 UTC, namanharness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/ProjectForm.tsx
> +                          refetchOrg?.()
i added this for a reason, i have solved it and attached the video for the bug and fix in another comment

2023-08-29 15:23 UTC, namanharness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/ProjectForm.tsx
> +  const [orgValue, setOrgValue] = React.useState<string>('')
reason of adding this:
https://harness.slack.com/archives/C01K0MDQXL3/p1693322612289469?thread_ts=1693312632.499509&cid=C01K0MDQXL3

2023-08-29 15:48 UTC, pankajsingh-harness requested changes

2023-08-29 15:48 UTC, pankajsingh-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/ProjectForm.tsx
> +  const [orgValue, setOrgValue] = React.useState<string>('')
```suggestion
  const [orgValue, setOrgValue] = React.useState<string>(initialOrgIdentifier)
```

2023-08-29 15:48 UTC, pankajsingh-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/ProjectForm.tsx
> +        orgIdentifier: orgValue || initialOrgIdentifier,
```suggestion
        orgIdentifier: orgValue,
```

2023-08-29 15:48 UTC, pankajsingh-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/ProjectForm.tsx
> +  const [orgValue, setOrgValue] = React.useState<string>('')
useEffect(() => {setOrgValue(initialOrgIdentifier)}, [initialOrgIdentifier])

2023-08-29 15:48 UTC, pankajsingh-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/ProjectForm.tsx
> +                      onChange={e => {
This should not needed after making the change:
```
useEffect(() => {setOrgValue(initialOrgIdentifier)}, [initialOrgIdentifier])
```
As the value of initialOrgIdentifier changes after the API call that will update the `orgValue` which in turn changes the formik initialValues which will reset the form with new initialValues as  `enableReinitialize: true`

2023-08-30 08:31 UTC, pankajsingh-harness approved these changes

2023-08-30 11:08 UTC, sunnykesh-harness approved these changes

2023-08-30 11:08 UTC, merged