chore: [PL-40980]: add EULA behind FF PL_EULA_ENABLED
harness/harness-core-ui pull request #17638
Opened 2023-08-29 18:59 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-30 04:21 UTC, pankajsingh-harness commented on src/modules/27-platform/default-settings/RouteDestinations.tsx
> +  DefaultSettingsFactory.registerSettingHandler(SettingType.AIDA, {
Move this also under FF flag as this will set settingMap & categoryToSettingMap even if it is not used.

2023-08-30 04:22 UTC, pankajsingh-harness requested changes
Move registerSettingHandler for SettingType.AIDA under FF flag as this will set settingMap & categoryToSettingMap even if it is not used.

2023-08-30 06:28 UTC, pankajsingh-harness submitted a review, later dismissed

2023-08-30 07:53 UTC, mayankVermaHarness requested changes
Please update version in `package.json`

2023-08-30 07:57 UTC, mayankVermaHarness submitted a review, later dismissed

2023-08-30 15:20 UTC, mayankVermaHarness approved these changes

2023-08-30 15:42 UTC, pankajsingh-harness submitted a review, later dismissed

2023-08-30 21:06 UTC, abhinavrastogi-harness approved these changes

2023-08-31 05:17 UTC, mayankVermaHarness commented on src/modules/27-platform/strings/strings.en.yaml
> +  harnessAida: Harness AI Developer Assistant
Don't we already have `platform.aida.aida` String that is the same as this? Check line 98

2023-08-31 05:18 UTC, mayankVermaHarness approved these changes

2023-08-31 05:22 UTC, merged

2023-08-31 07:25 UTC, namanharness commented on src/modules/27-platform/strings/strings.en.yaml
> +  harnessAida: Harness AI Developer Assistant
right but this was the exact phrase which Abhinav suggested in this thread: https://harness.slack.com/archives/C05NVMUUMEJ/p1693417289771909

so applied this only.