feat: [PL-40677]: add enable/disable notification channel
harness/harness-core-ui pull request #17632
Opened 2023-08-29 09:58 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-30 20:09 UTC, samarth-sharma31 commented on src/modules/27-platform/default-settings/RouteDestinations.tsx
> +DefaultSettingsFactory.registerCategory('NOTIFICATIONS', {
Lets use SettingGroups enum instead of using the 'NOTIFICATIONS' directly

2023-08-31 03:57 UTC, pankajsingh-harness commented on src/modules/27-platform/default-settings/RouteDestinations.tsx
> +DefaultSettingsFactory.registerCategory('NOTIFICATIONS', {
@samarth-sharma31 this is fine. 
```
export type SettingCategory = SettingDTO['category']

export interface SettingDTO {
  allowOverrides: boolean
  allowedScopes: ('ACCOUNT' | 'ORGANIZATION' | 'PROJECT')[]
  allowedValues?: string[]
  category:
    | 'CD'
    | 'CI'
    | 'CE'
    | 'CV'
    | 'CF'
    | 'STO'
    | 'CORE'
    | 'PMS'
    | 'TEMPLATESERVICE'
    | 'GOVERNANCE'
    | 'CHAOS'
    | 'SCIM'
    | 'GIT_EXPERIENCE'
    | 'CONNECTORS'
    | 'EULA'
    | 'NOTIFICATIONS'
  defaultValue?: string
  groupIdentifier: string
  identifier: string
  isSettingEditable: boolean
  name: string
  orgIdentifier?: string
  projectIdentifier?: string
  settingSource?: 'ACCOUNT' | 'ORG' | 'PROJECT' | 'DEFAULT'
  value?: string
  valueType: 'String' | 'Boolean' | 'Number'
}

```

2023-08-31 04:07 UTC, pankajsingh-harness requested changes
NIT: Added some comments related to the naming convention.

2023-08-31 04:07 UTC, pankajsingh-harness commented on src/modules/10-common/constants/Utils.ts
> +  ENABLE_MSTEAM_NOTIFICATION_IDENTIFIER = 'enable_msTeams_notification',
```suggestion
  ENABLE_MSTEAM_NOTIFICATION = 'enable_msTeams_notification',
```

2023-08-31 04:07 UTC, pankajsingh-harness commented on src/modules/10-common/constants/Utils.ts
> +  ENABLE_SLACK_NOTIFICATION_IDENTIFIER = 'enable_slack_notification'
```suggestion
  ENABLE_SLACK_NOTIFICATION = 'enable_slack_notification'
```

2023-08-31 04:07 UTC, pankajsingh-harness commented on src/modules/27-platform/default-settings/interfaces/SettingType.types.ts
> +  ENABLED_NOTIFICATION_CHANNELS_GROUP_IDENTIFIER = 'enabled_notification_channels'
NIT: Follow similar naming convention of have same key and value.
```suggestion
  ENABLED_NOTIFICATION_CHANNELS = 'enabled_notification_channels'
```

2023-08-31 04:07 UTC, pankajsingh-harness commented on src/modules/27-platform/default-settings/RouteDestinations.tsx
> +DefaultSettingsFactory.registerGroupHandler(SettingGroups.ENABLED_NOTIFICATION_CHANNELS_GROUP_IDENTIFIER, {
NIT: Keep `registerGroupHandler` & `registerSettingHandler` together for better code readability. Move this above `registerSettingHandler` of this `groupId`

2023-08-31 07:33 UTC, pankajsingh-harness submitted a review, later dismissed

2023-08-31 10:08 UTC, mayankVermaHarness commented on src/modules/10-common/constants/Utils.ts
> +  ENABLE_MSTEAM_NOTIFICATION = 'enable_msTeams_notification',
```suggestion
  ENABLE_MSTEAMS_NOTIFICATION = 'enable_msTeams_notification',
```

2023-08-31 10:35 UTC, namanharness commented on src/modules/10-common/constants/Utils.ts
> +  ENABLE_MSTEAM_NOTIFICATION = 'enable_msTeams_notification',
done

2023-08-31 10:46 UTC, mayankVermaHarness approved these changes

2023-08-31 11:58 UTC, Eric761 approved these changes

2023-08-31 13:07 UTC, merged