feat: [CI-8700]: gitness CI integration
harness/harness-core-ui pull request #17656
Opened 2023-08-30 12:12 UTC by shaurya-harness

### Summary

gitness CI integration

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-05 14:20 UTC, d1wilko requested changes
Some comments but looks good to me for the most part!

I'd ask @vardanbansal-harness to have a look aswell incase I missed things :)

2023-09-05 14:20 UTC, d1wilko commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/InfraProvisioningWizard.tsx
> +          : ''
this feels a little cleaner like this

```
let fullRepoName = '';

if (selectRepositoryRef?.current?.repository) {
    fullRepoName = getFullRepoName(selectRepositoryRef.current.repository);
} else if (CODE_ENABLED) {
    fullRepoName = selectRepositoryRef.current?.gitnessRepository?.uid || '';
}
```

nested ternarys feel icky to me lol

2023-09-05 14:20 UTC, d1wilko commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/SelectRepository.tsx
> +        repositories &&
I think you can remove this line - the array test will return false if undefined

2023-09-05 14:20 UTC, d1wilko commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/SelectRepository.tsx
> +        gitnessRepositories &&
i think this can be removed

2023-09-05 15:43 UTC, shaurya-harness commented on src/modules/10-common/components/ReferenceSelect/ReferenceSelect.tsx
> +        useGitProviderComponent={rest.useGitProviderComponent}
yes, updated this

2023-09-05 15:54 UTC, shaurya-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/InfraProvisioningWizard.tsx
> +          : ''
makes sense

2023-09-05 15:55 UTC, shaurya-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/SelectRepository.tsx
> +        gitnessRepositories &&
agreed

2023-09-05 16:16 UTC, d1wilko submitted a review, later dismissed
LGTM - but worth getting another set of eyes on it :)

2023-09-05 18:17 UTC, tan-nhu submitted a review, later dismissed

2023-09-06 08:38 UTC, d1wilko approved these changes

2023-09-06 18:18 UTC, vardanbansal-harness commented on src/modules/70-pipeline/components/PipelineStudio/RightBar/RightBarUtils.tsx
> +  const renderConnectorField = (): JSX.Element => {
Is this code duplicated in `CICodebaseInputSetForm` as well?

2023-09-06 18:21 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/InfraProvisioningWizard.tsx
> +    (repository?: UserRepoResponse, gitnessRepoName?: string, pipelineName?: string): string => {
Maybe abstract `repository?: UserRepoResponse, gitnessRepoName?: string, pipelineName?: string` as a different type? I usually wrap it once number of args gets > 2.

2023-09-07 04:02 UTC, shaurya-harness commented on src/modules/70-pipeline/components/PipelineStudio/RightBar/RightBarUtils.tsx
> +  const renderConnectorField = (): JSX.Element => {
CICodebaseInputSetForm renders it a little differently, onchange is different and configureOptionsProps are not used there

2023-09-07 04:03 UTC, shaurya-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/Constants.ts
> +  dummyGitnessHarnessConnector?: ConnectorInfoDTO
self explanatory 😄

2023-09-07 04:04 UTC, shaurya-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/InfraProvisioningWizard.tsx
> +    (repository?: UserRepoResponse, gitnessRepoName?: string, pipelineName?: string): string => {
sure, can be done

2023-09-07 14:50 UTC, d1wilko approved these changes

2023-09-07 15:17 UTC, vardanbansal-harness approved these changes

2023-09-08 04:33 UTC, shaurya-harness commented
retrigger jest

2023-09-08 04:34 UTC, shaurya-harness commented
retrigger prettier

2023-09-08 04:34 UTC, shaurya-harness commented
retrigger typecheck

2023-09-08 04:34 UTC, shaurya-harness commented
retrigger sonar

2023-09-08 04:34 UTC, shaurya-harness commented
retrigger standards

2023-09-08 04:34 UTC, shaurya-harness commented
retrigger build

2023-09-08 04:35 UTC, shaurya-harness commented
retrigger titlecheck

2023-09-08 04:35 UTC, shaurya-harness commented
retrigger fetaurenamecheck

2023-09-08 04:35 UTC, shaurya-harness commented
retrigger cypress-rest

2023-09-08 04:35 UTC, shaurya-harness commented
retrigger cypress-cd

2023-09-08 04:36 UTC, shaurya-harness commented
retrigger cypress-pipeline

2023-09-08 04:36 UTC, shaurya-harness commented
retrigger cypress-cv

2023-09-08 04:36 UTC, shaurya-harness commented
retrigger coverage

2023-09-08 04:36 UTC, shaurya-harness commented
fix prettier

2023-09-08 06:48 UTC, shaurya-harness commented
retrigger eslint

2023-09-08 06:57 UTC, vikrant-harness commented on src/modules/27-platform/connectors/components/ConnectorReferenceField/__tests__/__snapshots__/FormMultiTypeGitProviderAndConnectors.test.tsx.snap
> +<div>
Can we avoid such huge snapshot testing and instead assert on the UI

2023-09-08 06:58 UTC, vikrant-harness commented on src/modules/70-pipeline/components/InputSetForm/FormikInputSetForm.tsx
> +    const connectorFromPipelineData = initialValues?.pipeline?.properties?.ci?.codebase?.connectorRef
NIT : can use get here to avoid optional chainings.

2023-09-11 15:38 UTC, shaurya-harness commented on src/modules/70-pipeline/components/InputSetForm/FormikInputSetForm.tsx
> +    const connectorFromPipelineData = initialValues?.pipeline?.properties?.ci?.codebase?.connectorRef
done

2023-09-11 15:38 UTC, shaurya-harness commented on src/modules/27-platform/connectors/components/ConnectorReferenceField/__tests__/__snapshots__/FormMultiTypeGitProviderAndConnectors.test.tsx.snap
> +<div>
removed the basic ones

2023-09-11 15:42 UTC, d1wilko approved these changes
LGTM

2023-09-11 15:43 UTC, vardanbansal-harness submitted a review, later dismissed

2023-09-12 13:53 UTC, d1wilko submitted a review, later dismissed
LGTM

2023-09-12 14:02 UTC, vardanbansal-harness approved these changes

2023-09-12 14:40 UTC, vikrant-harness submitted a review, later dismissed

2023-09-12 16:21 UTC, d1wilko approved these changes
LGTM

2023-09-13 03:56 UTC, merged