feat: [CDS-78378]: added telemetry events for support ticket deflection modal
harness/harness-core-ui pull request #17664
Opened 2023-08-30 20:45 UTC by vikrant-harness

### Summary

- Added telemetry events for the support ticket deflection modal for the following usecases.
- one event when the user opens the "submit ticket" wizard.
- Then another event when user goes to step 2. Include the "question/problem" they typed as metadata on this event.
- Another event on submission of the ticket, with key ticket details as metadata.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-30 20:57 UTC, abhinavrastogi-harness requested changes

2023-08-30 20:57 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/DocsChat/DocsChat.tsx
> +              trackEvent(SupportTicketActions.SubmitTicketModalOpen, {
this event should be inside the SubmitTicketModal when it renders the first time.

2023-08-30 21:03 UTC, vikrant-harness commented on src/modules/10-common/components/DocsChat/DocsChat.tsx
> +              trackEvent(SupportTicketActions.SubmitTicketModalOpen, {
Done

2023-08-30 21:05 UTC, abhinavrastogi-harness approved these changes

2023-08-31 04:10 UTC, pankajsingh-harness approved these changes

2023-08-31 05:46 UTC, dhruvUpadhyay07 approved these changes

2023-08-31 07:09 UTC, merged