feat: [CI-9448]: CI new side nav changes
harness/harness-core-ui pull request #17758
Opened 2023-09-06 15:43 UTC by shaurya-harness

### Summary

CI new side nav changes

#### Screenshots

![Screenshot 2023-09-08 at 9 52 39 AM](https://github.com/harness/harness-core-ui/assets/113332561/55058599-00de-4a7b-b646-8ae1e4e8a5d6)
<img width="1728" alt="Screenshot 2023-09-08 at 12 24 03 PM" src="https://github.com/harness/harness-core-ui/assets/113332561/ec7c8eb7-0790-4f19-94cd-2f64bf91288b">
<img width="1728" alt="Screenshot 2023-09-08 at 12 24 15 PM" src="https://github.com/harness/harness-core-ui/assets/113332561/4d3094a2-c49e-4a35-92d8-c665242687b7">

https://github.com/harness/harness-core-ui/assets/113332561/ff68d54a-adcb-40e8-aae7-6e55941e8b7a

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-06 18:28 UTC, vardanbansal-harness approved these changes

2023-09-08 04:36 UTC, vardanbansal-harness approved these changes

2023-09-08 05:23 UTC, avinashmadhwani02 requested changes

2023-09-08 05:23 UTC, avinashmadhwani02 commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +        {getStartedWithCIFirst ? (
This is still dependent on API call. Can you check how the links are appearing in all modules?

2023-09-08 05:23 UTC, avinashmadhwani02 commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +          <SideNav.Link
Is overview for build available in Account scope as well?

2023-09-08 05:23 UTC, avinashmadhwani02 commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +            label={getString('pipelines')}
do we have pipelines in Org scope?

2023-09-08 05:23 UTC, avinashmadhwani02 commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +            icon="nav-pipeline"
same?
Also, is the icon same for builds and pipelines?

2023-09-08 05:23 UTC, avinashmadhwani02 commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +            {renderCommonNavLinks()}
common links can be rendered always. you should put conditions on conditional links

2023-09-08 05:23 UTC, avinashmadhwani02 commented on src/modules/75-ci/CIRouteDestinations.tsx
> +      <PipelineRouteDestinations mode={mode} />
```suggestion
      PipelineRouteDestinations({mode}).props.children
```

2023-09-08 05:23 UTC, avinashmadhwani02 commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +      setGetStartedWithCIFirst(status === 'SUCCESS' && (data as PagePMSPipelineSummaryResponse)?.totalElements === 0)
We must be fetching pipelines on Overview page. Should we redirect user to Overview page first and if the pipelines are not present we can redirect to GetStarted page. This way side nav links will not be dependent on API call. Thoughts?

2023-09-08 06:14 UTC, shaurya-harness commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +      setGetStartedWithCIFirst(status === 'SUCCESS' && (data as PagePMSPipelineSummaryResponse)?.totalElements === 0)
side nav is still not dependent on api call, just the ordering is
as mentioned default ordering is there without api call as well, on api call we are just changing the ordering in nav since product wants to keep get started on top in no pipeline scenario

2023-09-08 06:14 UTC, shaurya-harness commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +            icon="nav-pipeline"
adding new one

2023-09-08 06:14 UTC, shaurya-harness commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +            label={getString('pipelines')}
no, my bad, fixing this

2023-09-08 06:14 UTC, shaurya-harness commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +          <SideNav.Link
no, my bad, fixing this

2023-09-08 06:14 UTC, shaurya-harness commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +        {getStartedWithCIFirst ? (
default ordering is there without api call as well, on api call we are just changing the ordering in nav since product wants to keep get started on top in no pipeline scenario

2023-09-08 06:36 UTC, avinashmadhwani02 commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +      setGetStartedWithCIFirst(status === 'SUCCESS' && (data as PagePMSPipelineSummaryResponse)?.totalElements === 0)
The re-ordering will happen after some delay, which is not a good experience. 
In case of all modules it will be very evident. 

We can merge this PR for now, but you should check the case all modules with product once.

2023-09-08 07:01 UTC, shaurya-harness commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +      setGetStartedWithCIFirst(status === 'SUCCESS' && (data as PagePMSPipelineSummaryResponse)?.totalElements === 0)
okay, will check with product
merged the other changes

2023-09-08 07:21 UTC, shaurya-harness commented on src/modules/75-ci/components/CISideNav/CISideNavV2.tsx
> +            {renderCommonNavLinks()}
there are no conditional links, only ordering

2023-09-08 09:50 UTC, merged