feat: [CDS-78716]: yaml simplification phase 1
harness/harness-core-ui pull request #17769
Opened 2023-09-07 08:54 UTC by srdjan-harness

### Summary

PR includes yaml simplification phase 1 features (0-30 days).

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-29 08:14 UTC, srdjan-harness commented on package.json
> +    "@harnessio/react-pipeline-service-client": "1.8.0",
Check if 1.8.0 is stable version

2023-09-29 08:18 UTC, srdjan-harness commented on src/modules/10-common/components/ConfigureOptions/AllowedValuesField.tsx
What for is this change?

2023-09-29 08:22 UTC, srdjan-harness commented on src/modules/70-pipeline/common/components/PipelineStudio/IDBContext/IDBActions.ts
> +  type: IDBActions.initialize
Rename to initialized /  initializationSuccess

2023-09-29 08:56 UTC, srdjan-harness commented on src/modules/70-pipeline/common/components/PipelineStudio/IDBContext/IDBContext.tsx
> +  // disabling this because this the definition of usePipelineContext
update comment  usePipelineContext > useIDBContext

2023-09-29 08:57 UTC, srdjan-harness commented on src/modules/70-pipeline/common/components/PipelineStudio/IDBContext/IDBReducer.ts
> +        initialized: true
add initializing: false

2023-09-29 08:58 UTC, srdjan-harness commented on src/modules/70-pipeline/common/components/PipelineStudio/IDBContext/IDBReducer.ts
> +        initializationFailed: payload
add initializing: false

2023-09-29 15:15 UTC, srdjan-harness commented on src/modules/70-pipeline/components/PipelineStudio/RightBar/RightBar.tsx
> +          iconProps={{ size: 20 }}
Why we are decreasing size?

2023-09-29 15:26 UTC, srdjan-harness commented on src/modules/70-pipeline/strings/strings.en.yaml
> +inputListInfo: List of variables that you will see in run form will be managed here.
"List of variables ..." is this correct? This should be "List of inputs...."?

2023-09-29 19:25 UTC, srdjan-harness commented on src/modules/75-cd/components/PipelineSteps/AzureArm/AzureArm.tsx
> +        getString?.('cd.azureArm.required', { name: getString?.('pipeline.location') })
Check this

2023-10-02 09:46 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/RightBar/RightBar.tsx
> +          iconProps={{ size: 20 }}
The size is updated to make all icons in the right bar the same size.

2023-10-02 09:48 UTC, rameshx commented on package.json
> +    "@harnessio/react-pipeline-service-client": "1.8.0",
1.8.0 is stable and the latest 1.9.0 is stable too

2023-10-03 09:25 UTC, PratyushGar commented on src/modules/10-common/components/ConfigureOptions/AllowedValuesField.tsx
allowedValue key is different in inputs contract, rather than processing it onSubmit and transforming it back in initialValues, added support for custom key and onChange handler

2023-10-03 09:36 UTC, srdjan-harness commented
retrigger jest

2023-10-05 06:56 UTC, srdjan-harness commented
retrigger titlecheck

2023-10-05 06:56 UTC, srdjan-harness commented
retrigger jest

2023-10-05 06:56 UTC, srdjan-harness commented
retrigger cypress-cv

2023-10-05 06:57 UTC, srdjan-harness commented
retrigger cypress-rest

2023-10-09 21:07 UTC, abhinavrastogi-harness requested changes

2023-10-09 21:07 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/components/CreatePipelineButton/VersionSelector/VersionSelector.tsx
> +    <Container margin={{ bottom: 'medium' }}>
components should not have built-in margins. infact the whole `Container` wrapper can be replaced by a fragment `<>`.
Let the parent add the container with margins if needed. that makes the component more reusable.

2023-10-09 21:07 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/components/CreatePipelineButton/useCreatePipelineModalY1.tsx
> +import { ShowModal, useModalHook } from '@harness/use-modal'
please use `ModalDialog` instead of `useModal`.
also, `useCreatePIpelineModal` should not be a hook. it should be a component like `CreatePipelineModal` which can be controlled via `useToggle` hook where needed.

2023-10-09 21:07 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/components/CreatePipelineButton/useCreatePipelineModalY1.tsx
> +import { ShowModal, useModalHook } from '@harness/use-modal'
this one is a blocker.

2023-10-09 21:07 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
> +      updatePipeline(latestPipeline).then(async () => {
why not `await updatePipeline(latestPipeline)`?

2023-10-09 21:07 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
> +          updateGitDetails(updatedGitDetails, latestPipeline).then(() => {
same here.. await would be cleaner

2023-10-09 21:07 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/utils.ts
this can be moved to `src/modules/70-pipeline/utils`?

2023-10-09 21:19 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/y1/components/InputFactory/InputComponent.tsx
it should be `v1` instead of `y1`?

2023-10-09 21:33 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/y1/components/InputFactory/InputComponentFactory.ts
> +inputComponentFactory.registerComponent(new NumberInput())
why do we need to call a constructor via `new`? why cant these just be plain react JSX elements like `<NumberInput />` or just `NumberInput` as a reference?

2023-10-10 10:03 UTC, chetanvekariya-harness reviewed
Reviewed majorly everything, except components that are almost exactly copied just to use V1 context.
Specifically reviewed IDBContext, PipelineContext, CreatePipeline, PipelineCanvas etc.

2023-10-12 11:42 UTC, srdjan-harness commented on src/modules/70-pipeline/common/components/UnhandledErrorMessage/UnhandledErrorMessage.tsx
I've extended AppErrorBoundary and use it in PipelineContextInternal and PipelineContextInternalY1

2023-10-12 12:12 UTC, srdjan-harness commented on src/modules/70-pipeline/common/components/VersionTag/VersionTag.module.scss
> +.versionTag:global(.bp3-tag) {
In the next  PR (TemplateStudio changes) we will replace this with new component YamlVersionBadge. This one will be deleted. FYI this is what we have in new component. Color depends on yaml version.
<img width="1284" alt="Screenshot 2023-10-12 at 14 09 03" src="https://github.com/harness/harness-core-ui/assets/69592850/6aa2041f-8383-448e-8760-744b09dddbe1">

2023-10-13 09:40 UTC, srdjan-harness commented on src/modules/70-pipeline/common/components/PipelineStudio/IDBContext/IDBContext.tsx
moved and added unit tests

2023-10-13 09:47 UTC, srdjan-harness commented on cypress/integration/70-pipeline/PipelineCanvas.spec.ts
> +    cy.wait(1000)
This is required because form is re-rendering. From some reason cypress is referencing to input that is detached. Strange is that old implementation rerenders exactly the same number of times and exact "props" are changed.
We spend to much time already trying to fix this. We will try in the templates studio, as we have similar refactoring there.

2023-10-13 10:11 UTC, srdjan-harness commented on src/modules/70-pipeline/components/CreatePipelineButton/CreatePipelineButton.tsx
> +  const { openCreatePipelineModalY1 } = useCreatePipelineModalY1()
this is not mistake, we are using Y1 for all YAML V1 related components

2023-10-13 14:12 UTC, srdjan-harness commented on src/modules/70-pipeline/common/hooks/useThunkReducer.tsx
> +  console.log('%c Action:' + action + ' ', 'background: #222; color: #bada55', { ...data })
this could be useful for debugging. I've added env variable THUNK_REDUCER_LOGGER

2023-10-13 14:14 UTC, srdjan-harness commented on src/modules/70-pipeline/components/InputSetSelector/InputSetSelector.tsx
> +  isY1
V1 is already taken by CI team.

2023-10-13 14:18 UTC, srdjan-harness commented on src/modules/70-pipeline/y1/components/InputFactory/InputComponent.tsx
we are using Y1 for components, same applies to this folder, we can consider renaming this in the future... when we remove ...V1 components create by CI team.

2023-10-13 16:33 UTC, srdjan-harness commented on src/modules/70-pipeline/common/components/PipelineStudio/IDBContext/utils.ts
> +export const deletePipelineCache = async <T = unknown>({
This make sense as we are using in all other placed "idb" term. Most probably we will never need abstraction inhere, in case we get this requirement wee can use  "Cache" or "LocalCache".

2023-10-16 09:42 UTC, srdjan-harness commented on src/modules/70-pipeline/common/components/PipelineStudio/PipelineLoaderContext/PipelineLoaderContext.tsx
This file is in the /common folder. we will keep it inhere. We will consider moving this file once we start with visual part.

2023-10-16 09:44 UTC, srdjan-harness commented on src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
> +      updatePipeline(latestPipeline).then(async () => {
done

2023-10-16 09:52 UTC, srdjan-harness commented on src/modules/70-pipeline/components/CreatePipelineButton/VersionSelector/VersionSelector.module.scss
> +  > div[class*='PillToggle--item'] {
Child styling of PillToggle is not supported. This is only way. Bdw, This css will be simplified in next PR (templates studio PR) as UX team has changed styles.

2023-10-16 09:54 UTC, srdjan-harness commented on src/modules/70-pipeline/components/CreatePipelineButton/useCreatePipelineModalY1.tsx
> +import { ShowModal, useModalHook } from '@harness/use-modal'
There is 54 files that are using useModal. We will not include this refactoring as its a big task and will introduce a lot of noise in this PR.

2023-10-16 09:57 UTC, srdjan-harness commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/utils.ts
This can remain inhere as only PipelineContext is using this functions.

2023-10-16 10:01 UTC, srdjan-harness commented on src/modules/70-pipeline/y1/components/InputFactory/InputComponentFactory.ts
> +inputComponentFactory.registerComponent(new NumberInput())
We don't see any downside.

2023-10-16 10:51 UTC, srdjan-harness commented on src/modules/70-pipeline/y1/components/InputFactory/Inputs/BooleanInput.tsx
> +  public internalType = PrimitiveInputType.boolean
We have union of types: export type InputComponentType = PrimitiveInputType | DerivedInputType which is used fro componentBank. We have created two enums to distinguish between generic and specific/derived inputs.

2023-10-16 10:53 UTC, srdjan-harness commented on src/modules/70-pipeline/y1/components/InputFactory/Inputs/ObjectInput.tsx
> +export class ObjectInput extends InputComponent<InputsFormValues> {
Yes, we need wrapper to render "not implemented" complex object as fallback.

2023-10-16 10:58 UTC, srdjan-harness commented on src/modules/70-pipeline/y1/components/InputsForm/InputRow.tsx
> +export function InputRow({ input }: InputRowProps): React.ReactElement {
InputRow and InputRowHeader are strongly coupled.

2023-10-16 11:03 UTC, srdjan-harness commented on src/modules/70-pipeline/y1/components/PipelineCanvas/PipelineErrors/usePipelineErrorsY1.tsx
> +  } = usePipelineContextY1()
We cannot do this as context type is different. We will reduce code duplication when we start visual part implementation.

2023-10-16 20:55 UTC, PratyushGar commented on src/modules/70-pipeline/components/PipelineStudio/CreateModal/PipelineCreate.tsx
> +  const resolvedPipelineIdentifier = canSelectVersion ? DefaultNewPipelineId : pipelineIdentifier
No, since the modal has moved outside to the listing page, pipelineIdentifier will not be present, and to distinguish between the modal opening from the hook used for V1 flow, this was added. Since this was used for all isEdit permissions as well, added it on top to set DefaultNewPipelineId as a fallback, to let the current flow work.

There would be some changes in this flow, once the visual view support is added

2023-10-16 20:57 UTC, PratyushGar commented on src/modules/70-pipeline/components/PipelineStudio/CreateModal/PipelineCreate.tsx
> +            {(!isEdit || canSelectVersion) && (
To let the new create modal only present on the initial listing flow to drive the modal to show the `Start with template` label even if isEdit flag based on identifier is not true

2023-10-19 07:58 UTC, chetanvekariya-harness submitted a review, later dismissed

2023-10-19 07:59 UTC, chetanvekariya-harness commented
Approved based on discussion we did on call. Do not have enough time to go through all changes again.
Attendees: @srdjan-harness , @rameshx , @PratyushGar , @chetanvekariya-harness

2023-10-23 21:33 UTC, abhinavrastogi-harness approved these changes

2023-10-25 05:00 UTC, chetanvekariya-harness approved these changes

2023-10-25 07:13 UTC, srdjan-harness commented
retrigger sonar

2023-10-26 20:42 UTC, abhinavrastogi-harness approved these changes

2023-10-27 05:41 UTC, srdjan-harness commented
retrigger sonar

2023-10-27 09:12 UTC, litvinovstas approved these changes

2023-10-28 03:35 UTC, PratyushGar approved these changes

2023-10-30 11:22 UTC, merged