feat: [PL-39416]: add secret runtime usage
harness/harness-core-ui pull request #17829
Opened 2023-09-11 08:02 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-27 05:31 UTC, chetanvekariya-harness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/utils.ts
> +  return useMemo(() => {
Better to keep this in component. Makes debugging easier in future

2023-09-27 07:05 UTC, rameshx commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +  const entityFilterListItems: any = useMemo(() => {
Let's avoid `any` here

2023-09-27 07:07 UTC, rameshx commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +        getString: getString
`getString` doesn't have to be passed from here. Hooks can be used in the Cell components.

2023-09-27 07:07 UTC, rameshx commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +        Header: 'Event',
Add to strings

2023-09-27 07:09 UTC, rameshx commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +    [data, isGitSyncEnabled]
Both dependencies are incorrect. Let's remove these two and add `getString` and `eslint-disable-next-line react-hooks/exhaustive-deps` can be removed after that.

2023-09-27 07:10 UTC, rameshx commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +            placeholder={'Entity'}
Add to strings or use existing string

2023-09-27 07:10 UTC, rameshx commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +            placeholder={'Scope'}
same as above

2023-09-27 07:10 UTC, rameshx commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +      {isEmpty(data) && !loading && !error && <NoDataCard message={'No Secrets found with matching query'} />}
same as above

2023-09-27 07:12 UTC, rameshx commented on src/modules/10-common/strings/strings.en.yaml
> +runTimeusage: 'Runtime Usage'
```suggestion
runtimeUsage: 'Runtime Usage'
```

2023-09-27 07:16 UTC, rameshx commented on src/modules/75-chaos/RouteDestinations.tsx
> +          <SecretRunTimeUsage />
```suggestion
          <SecretRuntimeUsage />
```

2023-09-28 05:03 UTC, chetanvekariya-harness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/utils.ts
> +    { label: 'Project', value: 'project' }
+1

2023-09-29 07:04 UTC, namanharness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/SecretRuntimeUsage.tsx
> +      ...useGetSecretRuntimeUsageQueryParams(page, searchTerm)
these params are passed at 2 files so added it in util file.
also the function that returns params uses a hook so it has to be turned into a hook, i made this change because React was throwing error before, any solutions in your mind?

2023-09-29 07:33 UTC, mayankVermaHarness commented on src/modules/10-common/RouteDefinitions.ts
> +      const path = `resources/secrets/${secretId}/runtimeusage`
Noticed we use hyphen-casing in URL paths.

```suggestion
      const path = `resources/secrets/${secretId}/runtime-usage`
```

2023-09-29 07:37 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +    error: any
This may fail the lint check as we have new rules that disallow `any` in new files.
Consider using `unknown`?

2023-09-29 08:14 UTC, mayankVermaHarness commented on src/modules/27-platform/secrets/RouteDestinations.tsx
> +    </RouteWithLayout>
Please check whether this is enough to add it to secrets of all 3 scopes:
`Project, Org and Account`

2023-09-29 08:14 UTC, mayankVermaHarness commented on src/modules/27-platform/secrets/pages/secretDetailsHomePage/SecretDetailsHomePage.tsx
> +                  isRefereceView ? setTab(SecretDetailsTabs.REFERENCE) : undefined
Spelling:

```suggestion
                setIsReference={isReferenceView => {
                  isReferenceView ? setTab(SecretDetailsTabs.REFERENCE) : undefined
```

2023-09-29 08:14 UTC, mayankVermaHarness commented on src/modules/45-projects-orgs/RouteDestinations.tsx
> +    </RouteWithLayout>
+1

2023-09-29 08:14 UTC, mayankVermaHarness commented on src/modules/75-chaos/RouteDestinations.tsx
> +      >
Does `Chaos` module have a separate page for Secrets?

2023-09-29 08:25 UTC, namanharness commented on src/modules/75-chaos/RouteDestinations.tsx
> +      >
Yes

<img width="1792" alt="image" src="https://github.com/harness/harness-core-ui/assets/110456765/228d911b-54ba-4e84-af49-fdc51938d4ab">

2023-09-29 10:19 UTC, namanharness commented on src/modules/45-projects-orgs/RouteDestinations.tsx
> +    </RouteWithLayout>
one is for Project side nav and other is for Account side nav
this pattern is followed in this file for all other secret routes as well

2023-09-29 10:38 UTC, namanharness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +  const isGitSyncEnabled = isGitSyncEnabledForProject && !gitSyncEnabledOnlyForFF
removing it

2023-09-29 12:22 UTC, namanharness commented on src/modules/27-platform/secrets/RouteDestinations.tsx
> +    </RouteWithLayout>
i checked Secret runtime usage of all 3 scope and it is working fine

2023-09-29 16:15 UTC, rameshx commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
Why is this needed?

2023-09-29 16:15 UTC, rameshx commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +  const columns: Column<RuntimeSetupUsageDTOColumnData>[] = [
use `useMemo` for this

2023-09-29 16:15 UTC, rameshx commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/utils.ts
> +  getString: (key: StringKeys, vars?: Record<string, any>) => string
rename to `getScopeOptions` or `getScropSelectOptions`

2023-09-29 16:15 UTC, rameshx commented on src/modules/45-projects-orgs/RouteDestinations.tsx
> +      path={routes.toSecretDetailsRuntimeUsage({ ...accountPathProps, ...projectPathProps, ...secretPathProps })}
This should take different `sidebarProps` and `path` values, or else this will be exactly similar to the route at line 432.

2023-09-29 16:41 UTC, rameshx commented on src/modules/45-projects-orgs/RouteDestinations.tsx
>        path={routes.toSecretDetailsRuntimeUsage({ ...accountPathProps, ...projectPathProps, ...secretPathProps })}
Could you check if `accountPathProps` is needed? The route before this is only taking org and secret path props. Visit both new routes in the UI after the change to ensure they are working as expected.

2023-10-03 14:28 UTC, namanharness commented on src/modules/45-projects-orgs/RouteDestinations.tsx
>        path={routes.toSecretDetailsRuntimeUsage({ ...accountPathProps, ...projectPathProps, ...secretPathProps })}
done

2023-10-03 15:02 UTC, rameshx submitted a review, later dismissed

2023-10-10 06:55 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/__tests__/RuntimeUsageList.test.tsx
> +  return { data: secretRuntimeUsageData, refetch: () => Promise.resolve(secretRuntimeUsageData) }
Seems like `useListActivities` is mocked twice—Line 21 and Line 32.

2023-10-10 06:57 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/__tests__/RuntimeUsageList.test.tsx
> +    const paginationElement = container.querySelector('div[class*="Pagination--pageSizeDropdown"]') as HTMLInputElement
Try to use a more specific selector. If the change the way we generate classes, this will break. You can use a `test-id` in case nothing else works.

2023-10-10 07:00 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/__tests__/entitySecretRuntimeUsage.json
> +{
Nit: Can be put in a `mock` folder and json file name can be `entitySecretRuntimeUsageMock.json` (added `Mock` at the end)

2023-10-10 07:05 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +// eslint-disable-next-line react/function-component-definition
this comment may not be needed.

2023-10-10 07:09 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +              window.open(`${windowLocationUrlPartBeforeHash()}#${targetUrl}`, '_blank')
Let's get rid of hash here (`#`) here as we now use BrowserRouter fully. Make sure appropriate slash (`/`) exist in the final URL.

2023-10-10 07:09 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +              window.open(`${windowLocationUrlPartBeforeHash()}#${targetUrl}`, '_blank')
Let's get rid of hash here (`#`) here as we now use BrowserRouter fully. Make sure appropriate slash (`/`) exist in the final URL.

2023-10-10 07:11 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +  // eslint-disable-next-line
This comment may not be needed.

2023-10-10 07:19 UTC, mayankVermaHarness commented on src/modules/27-platform/strings/strings.en.yaml
> +
Can be removed

2023-10-10 07:21 UTC, mayankVermaHarness commented on src/modules/45-projects-orgs/RouteDestinations.tsx
> +    </RouteWithLayout>
Added this exact same Route with the Exact same components and path at **three places** in this file?

2023-10-10 07:39 UTC, namanharness commented on src/modules/45-projects-orgs/RouteDestinations.tsx
> +    </RouteWithLayout>
one of them is redundant , removing that

2023-10-12 23:23 UTC, abhinavrastogi-harness requested changes

2023-10-12 23:23 UTC, abhinavrastogi-harness commented on package.json
> +  "version": "0.366.0",
undo this change

2023-10-12 23:23 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +          const clonedResponse = response.clone()
is this coming because of a bad rebase?

2023-10-15 05:18 UTC, namanharness commented on src/framework/app/App.tsx
> +          const clonedResponse = response.clone()
dropped the unnecessary commits

2023-10-15 05:25 UTC, namanharness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +          {`${getString('typeLabel')}: ${scopeName}`}
yes

2023-10-15 08:28 UTC, namanharness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +      {scopeId && (
yes for project and org we have a name which can be taken from scopeId but for account we only show Account right side of || takes care of Account scope and left side for project and org

2023-10-16 21:11 UTC, abhinavrastogi-harness requested changes

2023-10-16 21:11 UTC, abhinavrastogi-harness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/SecretRuntimeUsage.tsx
> +    // istanbul ignore next
remove

2023-10-16 21:11 UTC, abhinavrastogi-harness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/SecretRuntimeUsage.tsx
> +import { ResponseSecretResponseWrapper, useListActivities } from 'services/cd-ng'
can we use the ng manager client from npm instead

2023-10-16 21:11 UTC, abhinavrastogi-harness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/utils.ts
> +/*
utils should not be inside views.
if these functions are specific to runtime usage, they should not be utils. move them into the corresponding files.
if they are re-usable, move them out to layer utils.

2023-10-16 21:11 UTC, abhinavrastogi-harness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/utils.ts
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
remove

2023-10-16 21:11 UTC, abhinavrastogi-harness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/utils.ts
> +    { label: getString('account'), value: 'account' },
value should be value enums here. not strings

2023-10-16 21:11 UTC, abhinavrastogi-harness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/utils.ts
> +export const useSecretRuntimeUsageTimeData = (): { threeMonthsBack: Date; currentDate: number } => {
why does need to be a hook?

2023-10-16 21:11 UTC, abhinavrastogi-harness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/utils.ts
> +    activityTypes: ['ENTITY_USAGE'],
this should be an enum, right? BE must be sending it.

2023-10-16 21:11 UTC, abhinavrastogi-harness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/utils.ts
> +    endTime: moment(useSecretRuntimeUsageTimeData().currentDate).valueOf(),
inline invocation of a hook?
also, why does it need to be wrapped in `moment()`?

2023-10-16 21:11 UTC, abhinavrastogi-harness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/utils.ts
> +/* istanbul ignore next */
remove

2023-10-18 11:14 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +              let baseUrl = windowLocationUrlPartBeforeHash()
For the purpose of this PR, `windowLocationUrlPartBeforeHash` can remain here.

`windowLocationUrlPartBeforeHash` internally manages whether the flag for browserRouter is enabled or not.

We are managing this in a parallel PR: https://github.com/harness/harness-core-ui/pull/17717

2023-10-18 12:10 UTC, namanharness commented on src/modules/27-platform/secrets/pages/secretDetailsHomePage/SecretDetailsHomePage.tsx
> +                  isReferenceView ? setTab(SecretDetailsTabs.REFERENCE) : undefined
Scaling it to accomodate original logic :
https://github.com/harness/harness-core-ui/blob/021605714a4ca8c5cd9479bd1a51aadf527e1f11/src/modules/27-platform/secrets/pages/secrets/views/SecretsListView/SecretsList.tsx#L268

2023-10-22 11:29 UTC, namanharness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/SecretRuntimeUsage.tsx
> +    // istanbul ignore next
if i remove this then branch coverage fails.

2023-10-22 15:56 UTC, namanharness commented on src/modules/10-common/pages/entityUsage/views/EntityUsageListView/EntityUsageList.module.scss
> +  align-items: center;
<img width="1424" alt="image" src="https://github.com/harness/harness-core-ui/assets/110456765/219e3e47-b7fe-4526-b519-3849be52800c">
removing this completely is causing this (⬆️ img) , what should we do?

2023-10-22 16:12 UTC, namanharness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +              window.open(`${baseUrl}${targetUrl}`, '_blank')
no

2023-10-22 16:23 UTC, namanharness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +              const targetUrl = await entityData.getEntityURL()
when we click on the entity column then we generate this URL.
right now we only show secrets referenced in Connector.
can we discuss on the better approaches for this over call?

2023-10-23 11:37 UTC, namanharness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/utils.ts
> +  return useMemo(() => {
https://github.com/harness/harness-core-ui/pull/17829#discussion_r1363709757

2023-10-24 05:52 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/views/EntityUsageListView/EntityUsageList.module.scss
> +  align-items: center;
You can directly use flex on `<Layout.Horizontal />` as a prop. 

Example: ```<Layout.Horizontal flex={{ justifyContent: 'space-between', alignItems: 'center' }} spacing="medium">```

2023-10-24 05:56 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/RuntimeUsageList.tsx
> +  apiReturnProps: {
Can this be imported from service directly?

2023-10-25 08:19 UTC, mayankVermaHarness commented on src/modules/10-common/pages/entityUsage/views/RuntimeUsageView/SecretRuntimeUsage.tsx
> +import { ResponseSecretResponseWrapper, useListActivities } from 'services/cd-ng'
BE team didn't write these using the OpenAPI v3 spec.

2023-10-25 08:23 UTC, mayankVermaHarness commented on src/modules/45-projects-orgs/RouteDestinations.tsx
> +    <RouteWithLayout
Same Route added twice in this file.

2023-10-25 10:03 UTC, namanharness commented on src/modules/45-projects-orgs/RouteDestinations.tsx
> +    <RouteWithLayout
updated

2023-10-25 13:11 UTC, mayankVermaHarness approved these changes

2023-10-26 05:40 UTC, abhinavrastogi-harness approved these changes

2023-10-26 06:05 UTC, sonaligoyal-harness approved these changes

2023-10-26 06:22 UTC, merged