feat: [PL-41000]: Public Access: Second Cut
harness/harness-core-ui pull request #17831
Opened 2023-09-11 08:50 UTC by mayankVermaHarness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-21 07:59 UTC, rameshx commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/__tests__/EnablePublicAccess.test.tsx
> +    await userEvent.click(enableButton!)
`getBy*` or `findBy*` is more suitable here as we want to ensure that the button is present. It will also help in avoiding `!`.

2023-09-21 07:59 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
> +        publicAccessResponse: { public: true, errorMessage: '' } //obj.data?.publicAccessResponse
Should the commented code `obj.data?.publicAccessResponse` be replaced with `{ public: true, errorMessage: '' }`?

2023-09-21 07:59 UTC, rameshx commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
> +  // TODO:: CHECK HERE
Is this resolved?

2023-09-21 08:10 UTC, PratyushGar commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
> +        publicAccessResponse: { public: true, errorMessage: '' } //obj.data?.publicAccessResponse
Thanks, updated

2023-09-21 09:20 UTC, knagurski commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/EnablePublicAccess.tsx
> +            showError(defaultTo(res.responseMessages?.[0]?.message, getString('somethingWentWrong')))
Not an issue, but just curious why the use of `defaultTo` if the same thing can be achieved with
```suggestion
            showError(res.responseMessages?.[0]?.message || getString('somethingWentWrong'))
```

2023-09-21 09:23 UTC, knagurski commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/EnablePublicAccess.tsx
> +          showError(defaultTo(get(error, 'data.messsage'), get(error, 'message')))
Typo here
```suggestion
          showError(defaultTo(get(error, 'data.message'), get(error, 'message')))
```

2023-09-21 09:25 UTC, knagurski commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/EnablePublicAccess.tsx
> +              {getString('platform.authSettings.publicAccess.allowPublicResources')}{' '}
Not an issue, but I hate how we have to do silly things like `{' '}` to get JSX and prettier to let us keep spaces.

2023-09-21 09:25 UTC, knagurski commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/EnablePublicAccess.tsx
> +              <HarnessDocTooltip useStandAlone tooltipId={'allowPublicResources'} />
```suggestion
              <HarnessDocTooltip useStandAlone tooltipId="allowPublicResources" />
```

2023-09-21 09:31 UTC, knagurski commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/EnablePublicAccess.tsx
> +              <HarnessDocTooltip useStandAlone tooltipId={'allowPublicResources'} />
Any reason not to use the tooltip prop in the `Text` component instead of bringing this is specifically?
```typescript
<Text tooltipProps={{dataTooltipId: 'idOfToolTip'}}>
  Some text
</Text>
```

2023-09-21 09:36 UTC, knagurski commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/__tests__/EnablePublicAccess.test.tsx
> +    expect(dialogContainer).toBeTruthy()
Instead of using `toBeTruthy`, think about it from a user's point of view. `toBeInTheDocument` or `toBeVisible` do the same thing, but convey what you're trying to prove.
```suggestion
    expect(dialogContainer).toBeInTheDocument()
```

2023-09-21 09:37 UTC, knagurski commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/__tests__/EnablePublicAccess.test.tsx
> +    const enableButton = queryByTextFromRTL(dialogContainer as HTMLElement, 'enable')
Try to use `getByRole` instead of by text if possible. It's closer to how a user perceives the application.
```suggestion
    const enableButton = getByRole(dialogContainer as HTMLElement, 'button', { name: 'enable' })
```

2023-09-21 09:42 UTC, knagurski commented on src/modules/70-pipeline/components/PipelineStudio/AdvancedOptions/AdvancedOptions.tsx
> +                ></Text>
Is this needed? There's no text in it.

2023-09-21 09:43 UTC, knagurski commented on src/modules/70-pipeline/components/PipelineStudio/AdvancedOptions/AdvancedOptions.tsx
> +                />
Is there a `FormInput.*` version of this so you drop the manual juggling of values and event handlers?

2023-09-21 09:44 UTC, knagurski commented on src/modules/70-pipeline/components/PipelineStudio/AdvancedOptions/AdvancedOptions.tsx
> +              <Text font={{ variation: FontVariation.H5 }}>
Is this a title? If so, then `Heading` (with the appropriate `level` prop) the more accessible way of doing this.

2023-09-21 10:21 UTC, knagurski commented on src/modules/70-pipeline/components/PipelineStudio/SavePipelinePopover/SavePipelinePopover.tsx
> +  }
Could you have just included `!isMetadataUpdated` as the first thing?
```suggestion
  // Enable save even if isUpdated is false if metadata has changed
  const isSaveDisabled = !isMetadataUpdated || isReadonly || !isUpdated || isIntermittentLoading
```

As-is, if it gets to `|| isMetadatUpdated` it'll set to true and then you immediately flip it with the next statement.

2023-09-21 10:23 UTC, knagurski commented on src/modules/70-pipeline/components/PipelineStudio/SavePipelinePopover/SavePipelinePopover.tsx
> +  if (isMetadataUpdated) {
Do you need `|| isMetadataUpdated` here? Doesn't appear like it'll change anything since the next statement flips `isSaveDisabled` if it is true
```suggestion
  let isSaveDisabled = isReadonly || !isUpdated || isIntermittentLoading
  if (isMetadataUpdated) {
```

2023-09-21 12:22 UTC, mayankVermaHarness commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/EnablePublicAccess.tsx
> +            showError(defaultTo(res.responseMessages?.[0]?.message, getString('somethingWentWrong')))
Istanbul considers `||` as a branch and gives coverage issues.

2023-09-21 12:42 UTC, mayankVermaHarness commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/EnablePublicAccess.tsx
> +              <HarnessDocTooltip useStandAlone tooltipId={'allowPublicResources'} />
Internally renders a div with `display: flex`. Will have to override styles to make it `inline`.

2023-09-22 11:20 UTC, mayankVermaHarness commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/EnablePublicAccess.tsx
> +              {getString('platform.authSettings.publicAccess.allowPublicResources')}{' '}
Removed. It wasn't needed.

2023-09-22 11:20 UTC, mayankVermaHarness commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/EnablePublicAccess.tsx
> +              <HarnessDocTooltip useStandAlone tooltipId={'allowPublicResources'} />
Done.

2023-09-22 11:21 UTC, mayankVermaHarness commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/__tests__/EnablePublicAccess.test.tsx
> +    expect(dialogContainer).toBeTruthy()
Done

2023-09-22 11:21 UTC, mayankVermaHarness commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/__tests__/EnablePublicAccess.test.tsx
> +    const enableButton = queryByTextFromRTL(dialogContainer as HTMLElement, 'enable')
Thanks for the suggestion. Done.

2023-09-22 11:23 UTC, mayankVermaHarness commented on src/modules/27-platform/auth-settings/pages/Configuration/EnablePublicAccess/__tests__/EnablePublicAccess.test.tsx
> +    await userEvent.click(enableButton!)
Used getByRole as per @knagurski 's comment.

2023-09-22 11:55 UTC, PratyushGar commented on src/modules/70-pipeline/components/PipelineStudio/SavePipelinePopover/SavePipelinePopover.tsx
> +  if (isMetadataUpdated) {
Thanks, got missed while testing

2023-09-22 11:55 UTC, PratyushGar commented on src/modules/70-pipeline/components/PipelineStudio/AdvancedOptions/AdvancedOptions.tsx
> +              <Text font={{ variation: FontVariation.H5 }}>
Done across all title in the page

2023-09-22 11:56 UTC, PratyushGar commented on src/modules/70-pipeline/components/PipelineStudio/AdvancedOptions/AdvancedOptions.tsx
> +                ></Text>
Done, removed. Thanks

2023-09-22 13:03 UTC, bhavya-sinha approved these changes

2023-09-22 13:50 UTC, rameshx approved these changes

2023-09-22 14:14 UTC, srdjan-harness requested changes

2023-09-22 14:14 UTC, srdjan-harness commented on src/modules/70-pipeline/components/PipelineStudio/SavePipelinePopover/SavePipelinePopover.tsx
> +  }
Is this logic correct. if isReadonly or isIntermittentLoading should it be disabled?
something like this:
`isReadonly  || isIntermittentLoading || (!isUpdated  && !isMetadataUpdated)`

2023-09-22 16:11 UTC, srdjan-harness approved these changes

2023-09-23 19:41 UTC, samarth-sharma31 approved these changes

2023-09-25 06:53 UTC, merged