feat: rbac for policies
harness/harness-core-ui pull request #18079
Opened 2023-09-21 16:10 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-28 21:11 UTC, sahithikolichala commented
retrigger prettier

2023-09-28 21:11 UTC, sahithikolichala commented
retrigger cypress-cd

2023-09-28 21:12 UTC, sahithikolichala commented
retrigger cypress-cv

2023-09-28 21:12 UTC, sahithikolichala commented
retrigger cypress-pipeline

2023-09-28 21:12 UTC, sahithikolichala commented
retrigger standards

2023-09-28 21:12 UTC, sahithikolichala commented
retrigger titlecheck

2023-10-10 04:16 UTC, sahithikolichala commented
retrigger eslint

2023-10-10 04:16 UTC, sahithikolichala commented
retrigger jest

2023-10-10 04:17 UTC, sahithikolichala commented
retrigger titlecheck

2023-10-10 04:42 UTC, tan-nhu submitted a review, later dismissed

2023-10-10 04:56 UTC, sahithikolichala commented
retrigger eslint

2023-10-10 04:56 UTC, sahithikolichala commented
retrigger jest

2023-10-10 18:56 UTC, abhinavrastogi-harness requested changes

2023-10-10 18:56 UTC, abhinavrastogi-harness commented on src/modules/20-rbac/factories/RbacFactory.tsx
> -
unnecessary change

2023-10-10 18:56 UTC, abhinavrastogi-harness commented on src/modules/20-rbac/pages/ResourceGroupDetails/ResourceGroupDetails.tsx
> +      : resourceTypeData?.data?.resourceTypes || []
this seems unecessarily complicated. 
why does this need to be conditional on the FF? you can just skip registering the entities in RouteDestinations conditionally.

2023-10-10 18:56 UTC, abhinavrastogi-harness commented on src/modules/25-governance/GovernanceApp.tsx
> +      baseRoutePath={path}
what is `baseRoutePath`? the framework already passes `renderUrl` and `matchPath` which should be sufficient

2023-10-10 18:56 UTC, abhinavrastogi-harness commented on src/modules/25-governance/RouteDestinations.tsx
> +RbacFactory.registerResourceCategory(ResourceCategory.GOVERNANCE, {
make this registration conditional. then you don't need to change anything in rbac layer, because that is shared and risky.

2023-10-10 19:14 UTC, sahithikolichala commented on src/modules/25-governance/GovernanceApp.tsx
> +      baseRoutePath={path}
i think this is used in the governance mfe 
I can refactor but will do later

2023-10-10 19:17 UTC, sahithikolichala commented on src/modules/20-rbac/pages/ResourceGroupDetails/ResourceGroupDetails.tsx
> +      : resourceTypeData?.data?.resourceTypes || []
this is not just for registring.
If FF is not enabled, iGOVernancePolicy and Policyset should not be listed out

2023-10-10 19:18 UTC, sahithikolichala commented on src/modules/25-governance/RouteDestinations.tsx
> +RbacFactory.registerResourceCategory(ResourceCategory.GOVERNANCE, {
as mentioned above , when ff is not enabled, policy and policysets must not be listed
If those are not listed, we dont need any conditions on registrations

2023-10-10 19:19 UTC, sahithikolichala commented on src/modules/20-rbac/pages/ResourceGroupDetails/ResourceGroupDetails.tsx
> +      : resourceTypeData?.data?.resourceTypes || []
I have asked BE to not list tthem, but looks like they have some issues!

2023-10-10 22:43 UTC, tan-nhu submitted a review, later dismissed

2023-10-10 23:38 UTC, abhinavrastogi-harness commented on src/modules/25-governance/RouteDestinations.tsx
> +RbacFactory.registerResourceCategory(ResourceCategory.GOVERNANCE, {
since you have removed conditions on rendering, you need to make these registrations conditional.
these are also duplicated.

2023-10-10 23:41 UTC, abhinavrastogi-harness approved these changes

2023-10-10 23:55 UTC, cjlee01 approved these changes

2023-10-11 00:17 UTC, tan-nhu approved these changes

2023-10-11 04:06 UTC, merged