feat: [PLG-2808]: plans page new flow
harness/harness-core-ui pull request #18092
Opened 2023-09-22 12:03 UTC by dhruvUpadhyay07

### Summary

#### Screenshots

NA

https://github.com/harness/harness-core-ui/assets/64455881/e5321b59-8d70-41e4-9215-46f1e03d6aa4

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-26 14:37 UTC, devinder-harness submitted a review, later dismissed

2023-09-27 08:01 UTC, mayankVermaHarness commented on src/modules/27-platform/auth-settings/pages/subscriptions/SubscriptionTab.tsx
> +      <Layout.Horizontal className={css.subscriptionTabButtons} spacing="medium"></Layout.Horizontal>
Empty Layout component? Doesn't have any children.

2023-09-27 08:02 UTC, mayankVermaHarness commented on src/modules/27-platform/auth-settings/pages/subscriptions/SubscriptionsPage.tsx
> +      const plansPage = false || currentUrl.includes('tab=PLANS') || currentUrl.includes('/plans')
```suggestion
      const plansPage = currentUrl.includes('tab=PLANS') || currentUrl.includes('/plans')
```

2023-09-27 08:02 UTC, mayankVermaHarness commented on src/modules/27-platform/auth-settings/pages/subscriptions/SubscriptionsPage.tsx
> +      isPlansPage={false || window.location.href.includes('/plans')}
```suggestion
      isPlansPage={window.location.href.includes('/plans')}
```

2023-09-27 08:09 UTC, mayankVermaHarness commented on src/modules/10-common/components/AccountSideNav/AccountSideNav.tsx
> +      {NG_LICENSES_ENABLED && <SidebarLink exact label={'Plans'} to={routes.toPlans({ accountId })} />}
Use strings framework for `'Plans'`

2023-09-27 08:09 UTC, mayankVermaHarness requested changes
Added a few comments.

2023-09-27 08:10 UTC, mayankVermaHarness commented
Will this need to be onboarded to Nav 2.0 (new Nav)?
CC: @avinashmadhwani02

2023-10-03 15:57 UTC, devinder-harness approved these changes

2023-10-04 17:00 UTC, devinder-harness approved these changes

2023-10-05 08:33 UTC, mayankVermaHarness commented on src/modules/10-common/pages/SettingsPages/AccountSettingsPage.tsx
> +              route={routesV2.toPlans({ accountId, module })}
All routes seem to be from RoutesV2 in this file. Intended?

2023-10-05 08:35 UTC, mayankVermaHarness commented on src/modules/27-platform/auth-settings/RouteDestinations.tsx
> +        <RouteWithLayout
Do we also need to add this to RouteDestinationsV2 i.e. `src/modules/27-platform/auth-settings/SettingsRouteDestinations.tsx`?

2023-10-05 08:37 UTC, mayankVermaHarness approved these changes

2023-10-10 07:44 UTC, mayankVermaHarness approved these changes

2023-10-10 19:15 UTC, devinder-harness approved these changes

2023-10-11 14:38 UTC, merged