feat: [CDS-80395]: Org project split view
harness/harness-core-ui pull request #18213
Opened 2023-09-29 07:44 UTC by MondalSayantan

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-04 11:01 UTC, avinashmadhwani02 requested changes

2023-10-04 11:01 UTC, avinashmadhwani02 commented on src/modules/45-projects-orgs/pages/projects/views/OrgProjectSplitView/OrgProjectSplitView.module.scss
> +.colorbox {
Are we using this?

2023-10-04 11:04 UTC, avinashmadhwani02 commented on src/modules/45-projects-orgs/pages/projects/views/OrgProjectSplitView/OrgProjectSplitView.tsx
> +  projData: any
why any?

2023-10-04 11:05 UTC, avinashmadhwani02 commented on src/modules/45-projects-orgs/pages/projects/views/OrgProjectSplitView/OrgProjectSplitView.tsx
> +  projData: any
avoid use of any?
are you not getting eslint error?

2023-10-04 16:25 UTC, MondalSayantan commented on src/modules/45-projects-orgs/components/ScopeSelector/ProjectScopeSelector/ProjectScopeSelector.tsx
> +            onClick={onClick}
variable name changed for more clarity

2023-10-04 16:31 UTC, MondalSayantan commented on src/modules/45-projects-orgs/components/ScopeSelector/ProjectScopeSelector/ProjectScopeSelector.tsx
> +            projDataLoading={loading}
done

2023-10-04 16:32 UTC, MondalSayantan commented on src/modules/45-projects-orgs/components/ScopeSelector/ProjectScopeSelector/ProjectScopeSelector.tsx
>    const { preference: sortPreference = SortMethod.LastModifiedDesc, setPreference: setSortPreference } =
created new preferencestore as discussed `projectSelectorViewTypeV2`

2023-10-04 16:33 UTC, MondalSayantan commented on src/modules/45-projects-orgs/pages/projects/views/OrgProjectSplitView/OrgProjectSplitView.tsx
> +            <Layout.Vertical padding={{ right: 'medium' }} height={'82%'} style={{ overflow: 'auto' }}>
removed inline styling

2023-10-04 16:35 UTC, MondalSayantan commented on src/modules/45-projects-orgs/pages/projects/views/OrgProjectSplitView/OrgProjectSplitView.tsx
> +        <Layout.Vertical width={276}>
This solution is acceptable as discussed over call

2023-10-04 16:35 UTC, MondalSayantan commented on src/modules/45-projects-orgs/pages/projects/views/OrgProjectSplitView/OrgProjectSplitView.tsx
> +  projData: any
used correct types

2023-10-05 09:02 UTC, avinashmadhwani02 approved these changes

2023-10-05 09:47 UTC, pankajsingh-harness approved these changes

2023-10-05 10:31 UTC, chetanvekariya-harness approved these changes

2023-10-05 10:31 UTC, chetanvekariya-harness commented on src/modules/45-projects-orgs/components/ScopeSelector/ProjectScopeSelector/ProjectScopeSelector.tsx
> +      {orgDataLoading && loading ? (
Is this order change intended ? Earlier it was above ListHeader.

2023-10-05 10:31 UTC, chetanvekariya-harness commented on src/modules/45-projects-orgs/pages/projects/views/OrgProjectSplitView/OrgProjectSplitView.tsx
> +          <Pagination
Looks like pagination will appear even if there no data. Is it intended ? Does feel like good user experience.

2023-10-05 10:40 UTC, MondalSayantan commented on src/modules/45-projects-orgs/pages/projects/views/OrgProjectSplitView/OrgProjectSplitView.tsx
> +          <Pagination
Pagination does not appear when there is no data
<img width="1792" alt="image" src="https://github.com/harness/harness-core-ui/assets/62999423/a638840d-14ab-4080-8b46-a339eb0c7c56">

2023-10-05 10:41 UTC, MondalSayantan commented on src/modules/45-projects-orgs/components/ScopeSelector/ProjectScopeSelector/ProjectScopeSelector.tsx
> +      {orgDataLoading && loading ? (
No specific reason for this order change, just seemed well suited here to me

2023-10-05 11:50 UTC, merged