feat: [CDS-79743]: Enhance Target Revisin Field in UpdateGitOps App step
harness/harness-core-ui pull request #18226
Opened 2023-10-01 16:23 UTC by ishantmehtaharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-09 12:15 UTC, litvinovstas submitted a review, later dismissed

2023-10-09 12:25 UTC, chetanvekariya-harness requested changes

2023-10-09 12:25 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/UpdateGitOpsAppStep/useApplications.tsx
> +        let _sourceType = app.app?.status?.sourceType
Why not write `sourceType`? Why this practice of using _? Just curious.

2023-10-09 12:25 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/UpdateGitOpsAppStep/__tests__/UpdateGitopsAppStep.test.tsx
> +      expect(container).toMatchSnapshot('with initial values')
NO SNAPSHOT TESTING. This has been emphazied a lot by many people. Including our architects. Please add assertions to cover your changes.

2023-10-09 12:25 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/UpdateGitOpsAppStep/__tests__/UpdateGitopsAppStep.test.tsx
> +      expect(container).toMatchSnapshot('input sets')
Same as above.

2023-10-09 12:34 UTC, satyam-harness submitted a review, later dismissed

2023-10-09 15:32 UTC, ishantmehtaharness commented on src/modules/75-cd/components/PipelineSteps/UpdateGitOpsAppStep/__tests__/UpdateGitopsAppStep.test.tsx
> +      expect(container).toMatchSnapshot('with initial values')
I have created a follow up ticket for test cases
https://harness.atlassian.net/browse/CDS-81157

2023-10-09 15:33 UTC, litvinovstas submitted a review, later dismissed

2023-10-09 18:13 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/UpdateGitOpsAppStep/UpdateGitOpsAppStep.tsx
> +    /* istanbul ignore else */
Does it create any issue if you do not add this comment?

2023-10-09 18:13 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/UpdateGitOpsAppStep/__tests__/UpdateGitopsAppStep.test.tsx
> +      expect(container).toMatchSnapshot('with initial values')
But, let's also remove this test case. If coverage passed in future because of this snapshot test then we will never pick up coverage ticket you created.

2023-10-09 18:21 UTC, chetanvekariya-harness approved these changes

2023-10-09 18:31 UTC, litvinovstas approved these changes

2023-10-10 06:53 UTC, jenil-harness approved these changes

2023-10-10 09:38 UTC, kalyansai-harness commented
@chetanvekariya-harness @satyam-harness I am seeing some comments here. Are we good to go here?

2023-10-10 16:06 UTC, merged