feat: [FFM-9506]: Add FF Proxy Key Management tile to Account Resources
harness/harness-core-ui pull request #18248
Opened 2023-10-03 09:16 UTC by laura-mannus

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-03 13:00 UTC, crystal-fong submitted a review, later dismissed
would it be worth having a unit test to ensure the tile is hidden if the FF isn't enabled?

2023-10-04 08:17 UTC, crystal-fong submitted a review, later dismissed

2023-10-04 11:02 UTC, Kira-Jennings submitted a review, later dismissed

2023-10-04 14:01 UTC, bhavya-sinha approved these changes

2023-10-04 14:06 UTC, knagurski commented on src/modules/10-common/components/ResourceCardList/__tests__/ResourceCardList.test.tsx
> +    renderComponent()
Extracting the `renderComponent` function on a per-test basis isn't really needed. I'd just render directly.
```suggestion
    render(
      <TestWrapper
        path={ACCOUNT_LEVEL_GITOPS_ROUTE}
        pathParams={ACCOUNT_PATH_PARAMS}
        defaultFeatureFlagValues={{ FFM_9497_PROXY_KEY_MANAGEMENT: false }}
      >
        <ResourceCardList />
      </TestWrapper>
    )
```

2023-10-04 14:07 UTC, knagurski commented on src/modules/10-common/components/ResourceCardList/__tests__/ResourceCardList.test.tsx
> +    renderComponent()
Same here
```suggestion
    render(
      <TestWrapper
        path={ACCOUNT_LEVEL_GITOPS_ROUTE}
        pathParams={ACCOUNT_PATH_PARAMS}
        defaultFeatureFlagValues={{ FFM_9497_PROXY_KEY_MANAGEMENT: true }}
      >
        <ResourceCardList />
      </TestWrapper>
    )

```

2023-10-04 14:09 UTC, knagurski commented on src/modules/10-common/RouteDefinitions.ts
> +  ),
There's a v2 of this file too I think for the new layout

2023-10-04 15:43 UTC, laura-mannus commented on src/modules/10-common/RouteDefinitions.ts
> +  ),
I am going to address this is another ticket :) for the v2 navigation

2023-10-04 17:10 UTC, abhinavrastogi-harness reviewed
Can we get the FF module color added in the tile background?

2023-10-04 17:14 UTC, abhinavrastogi-harness requested changes

2023-10-04 17:14 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +    lazy: !PIE_GIT_BI_DIRECTIONAL_SYNC
why was the `orgIdentifier` check removed? I think it was ensuring that we only make this api call for account scope settings?

2023-10-04 17:14 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +              {showGitOpsEntities && option.icon.includes('gitops') && !option.icon.includes('key') && (
this should be controlled via a property added in `ResourceOption`. 
Doing an array search is not the right way.

2023-10-05 08:37 UTC, laura-mannus commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +    lazy: !PIE_GIT_BI_DIRECTIONAL_SYNC
Apologies @abhinavrastogi-harness I don't know why this was removed, I have reinstated it :)

2023-10-05 09:17 UTC, laura-mannus commented on src/modules/10-common/components/ResourceCardList/__tests__/ResourceCardList.test.tsx
> +    renderComponent()
Thank you, have addressed

2023-10-05 09:17 UTC, laura-mannus commented on src/modules/10-common/components/ResourceCardList/__tests__/ResourceCardList.test.tsx
> +    renderComponent()
Thanks, have resolved

2023-10-05 10:08 UTC, knagurski commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +              )}
I don't think this should be part of the PR. I think something may have gone wrong in a merge.

2023-10-05 10:09 UTC, knagurski commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +      orgIdentifier
Again, it looks like something went wrong in a merge, we have no need to touch bi directional sync

2023-10-05 10:18 UTC, laura-mannus commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +              )}
This is part of the pr, I needed to fix this logic so an arrow doesn't show under our tile because it contains 'gitops'

2023-10-05 10:19 UTC, laura-mannus commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +      orgIdentifier
yeah I don't know why this part of the code keeps changing on me

2023-10-05 13:05 UTC, laura-mannus commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +              {showGitOpsEntities && option.icon.includes('gitops') && !option.icon.includes('key') && (
Thanks, I have update this

2023-10-05 13:07 UTC, laura-mannus commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> -              {showGitOpsEntities && option.icon.includes('gitops') && <div className={css.arrowDown} />}
I removed `showGitIOpsEntities` because if this is true `showMoreOptions` will be true also

2023-10-05 13:12 UTC, laura-mannus commented
@abhinavrastogi-harness I have consulted with our UX and she does not want to add a colour to the tile, especially because this navigation will be changed over soon

2023-10-05 15:27 UTC, knagurski approved these changes
Looks good to me 👍🏻. We'll need to make sure this is added to the new nav version of this page too

2023-10-05 15:29 UTC, crystal-fong approved these changes

2023-10-05 15:29 UTC, laura-mannus commented
@knagurski PR for new nav here https://github.com/harness/harness-core-ui/pull/18313 :)

2023-10-06 20:26 UTC, abhinavrastogi-harness approved these changes

2023-10-09 09:18 UTC, merged