feat: [PLG-2860]: canny autthenitication using canny sdk
harness/harness-core-ui pull request #18277
Opened 2023-10-04 11:18 UTC by dhruvUpadhyay07

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-11 20:05 UTC, abhinavrastogi-harness requested changes

2023-10-11 20:05 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/ResourceCenter/utils.ts
> +const appId = '6450229969594e0bc28b76ef'
this should come from the env config, to allow overriding and avoid hardcoding

2023-10-11 20:05 UTC, abhinavrastogi-harness commented on src/index.html
> +                (e.src = 'https://canny.io/sdk.js'),
this origin needs to be whitelisted in the CSP policy
https://github.com/harness/harness-core-ui/blob/develop/docker/entrypoint.sh#L57

2023-10-11 20:05 UTC, abhinavrastogi-harness commented on src/index.html
> +      window.CANNY_ENABLE = 'CANNY_ENABLE_PLACEHOLDER' === 'true'
can we follow the same pattern as above third-party integrations?

`window.HARNESS_ENABLE_CANNY`

2023-10-11 20:05 UTC, abhinavrastogi-harness commented on docker/entrypoint.sh
> +sed -i "s|CANNY_ENABLE|$CANNY_ENABLE|" index.html
you are using the variable `CANNY_ENABLE_PLACEHOLDER` in HTML, but a defining a different variable here. it'll always be undefined.

Also, can we use the same pattern as other third-party integrations?

2023-10-11 20:40 UTC, kapil-harness requested changes

2023-10-11 20:40 UTC, kapil-harness commented on src/modules/10-common/components/ResourceCenter/utils.ts
> +          name: currentUserInfo.accounts?.[0].companyName
why to pick first account from a list of account the user is part of? rather we should pick the account in which the user is logged into.

2023-10-11 20:40 UTC, kapil-harness commented on src/modules/10-common/components/ResourceCenter/utils.ts
> +          id: currentUserInfo.accounts?.[0].companyName,
companyId should be accountId, reference slack thread: https://harness.slack.com/archives/C05CKH0G10W/p1696549500494369

2023-10-15 04:30 UTC, dhruvUpadhyay07 commented
retrigger cypress-pipeline

2023-10-16 15:57 UTC, abhinavrastogi-harness commented on docker/entrypoint.sh
> +sed -i "s|<\!-- harnessAppId -->|<script>window.harnessAppId = '$HARNESS_APP_ID'</script>|" index.html
we should use the thirdparty name here.. call it `cannyAppId`

2023-10-16 15:57 UTC, abhinavrastogi-harness commented on docker/entrypoint.sh
> +  sed -i "s|#cspHeadersPlaceholder|add_header Content-Security-Policy-Report-Only \"script-src 'self' 'unsafe-inline' https://canny.io/sdk.js https://*.harness.io https://widget.saberfeedback.com htt
CSP should have only the origins we want to connect to.
adding a filepath like `/sdk.js` will not work.

2023-10-16 15:57 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/ResourceCenter/ResourceCenter.tsx
> +  const account = accounts?.find(({ uuid }) => pathname.includes(uuid as string)) || {}
we already have accountInfo in AppStoreContext. We don't need to iterate over this list to extract it.

2023-10-16 15:57 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/ResourceCenter/utils.ts
> +import type { GatewayAccountRequestDTO, UserInfo } from 'services/cd-ng'
This is not the correct DTO to use (1. it's gateway account, 2. it's a request DTO).

Use `AccountDTO`, which is the same as used in AppStoreContext.

2023-10-16 18:07 UTC, abhinavrastogi-harness commented on docker/entrypoint.sh
> +sed -i "s|<\!-- cannyAppId -->|<script>window.cannyAppId = '$HARNESS_APP_ID'</script>|" index.html
the RHS is still called `HARNESS_APP_ID`.. this should also be `CANNY_APP_ID`.

2023-10-16 20:15 UTC, devinder-harness approved these changes

2023-10-17 01:26 UTC, merged