fix: [PL-37909]: refresh button in delegate task logs modal
harness/harness-core-ui pull request #18304
Opened 2023-10-05 10:54 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-10 19:25 UTC, abhinavrastogi-harness requested changes

2023-10-10 19:25 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/DelegateTaskLogs/DelegateTaskLogs.tsx
> +              color="var(--primary-7)"
why is the color given in both css and styledprops? one of them should be removed.

2023-10-10 19:25 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/DelegateTaskLogs/DelegateTaskLogs.tsx
> +export const DelegateTaskLogs: React.FC<DelegateTaskLogsModalApiProps> = ({
is this used directly anywhere?
if not, we can just merge the component with the dialog wrapper. 
this will avoid the need to pass `apiProps`, which is not a good design

2023-10-10 19:25 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/DelegateTaskLogs/DelegateTaskLogs.tsx
> +  apiProps: {
should not be needed

2023-10-10 19:25 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/DelegateTaskLogs/DelegateTaskLogs.tsx
> +    refetch: (props: any) => Promise<void>
remove explicit `any`. use proper types if needed.

2023-10-11 10:05 UTC, namanharness commented on src/modules/10-common/components/DelegateTaskLogs/DelegateTaskLogs.tsx
> +    lazy: true
with new changes, the hook is called on opening the connection test modal itself but we want it to to open when delegate task modal is open so lazy will be required

2023-10-11 10:07 UTC, namanharness commented on src/modules/10-common/components/DelegateTaskLogs/DelegateTaskLogs.tsx
> +              color="var(--primary-7)"
Icon was not accepting the blue(primary-7) color when added inline or added in external css
but for some reason idk yet it was accepting when i added it to both so i added it at both places.
if you know why this behaviour exists then please do tell.

2023-10-11 10:07 UTC, namanharness commented on src/modules/10-common/components/DelegateTaskLogs/DelegateTaskLogs.tsx
> +export const DelegateTaskLogs: React.FC<DelegateTaskLogsModalApiProps> = ({
Yes i have removed this component

2023-10-11 20:18 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/DelegateTaskLogs/DelegateTaskLogs.tsx
> +      {error && <PageError message={error.message} />}
error should be shown only when `!loading`. otherwise both will show up at the same time.

2023-10-11 20:18 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/DelegateTaskLogs/DelegateTaskLogs.tsx
> +    lazy: true
can you try passing `lazy: !isOpen`?
it should prevent the call when modal is closed, but automatically make the call when it opens.

2023-10-11 20:18 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/DelegateTaskLogs/DelegateTaskLogs.tsx
> +const getTaskLogsQueryParams = (
what is the point of this function? it's just returning what's passed to it.. and only adding pageSize with a fixed value of 100?

2023-10-11 20:18 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/DelegateTaskLogs/DelegateTaskLogs.tsx
> +                refetch({ queryParams: { ...queryParams } })
```suggestion
                refetch({ queryParams })
```

2023-10-12 21:31 UTC, abhinavrastogi-harness approved these changes

2023-10-12 22:03 UTC, sahithikolichala approved these changes
Please add a test case for referesh

2023-10-13 10:18 UTC, pankajsingh-harness approved these changes

2023-10-15 08:44 UTC, merged