fix: [BT-4414]: Create CODEOWNERS
harness/harness-core-ui pull request #18436
Opened 2023-10-12 17:01 UTC by AnshuH

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-12 22:11 UTC, abhinavrastogi-harness requested changes

2023-10-12 22:11 UTC, abhinavrastogi-harness commented on .github/CODEOWNERS
> +.github/ @harness/build-engineering
we already have a codeowners file in the root of the repo. can we add this rule to the same file?

2023-10-12 22:11 UTC, abhinavrastogi-harness commented on .github/pull_request_template.md
> +- messagecheck: `trigger messagecheck`
we already have a `titlecheck` PR check, and this seems redundant. 
if this one is the standard one, can we also remove the old one at the same time?

2023-10-16 10:05 UTC, AnshuH commented on .github/pull_request_template.md
> +- messagecheck: `trigger messagecheck`
We're testing a centralized Pull Request check for repositories. Currently optional, but will become mandatory using a single template soon.

2023-10-17 06:50 UTC, merged