fix: [CDS-81701]: fixed to remove the extra entry on spec for ondelegate
harness/harness-core-ui pull request #18472
Opened 2023-10-16 21:32 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-19 13:42 UTC, AnshuH commented
trigger recency

2023-10-20 21:59 UTC, sahithikolichala commented
retrigger messageCheck

2023-10-20 22:00 UTC, sahithikolichala commented
retrigger messageCheck

2023-10-21 08:05 UTC, rameshx requested changes

2023-10-21 08:05 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/ShellScriptStep/ExecutionTargetGroup.tsx
> +              formik.setFieldValue(name, e.currentTarget.value === 'targethost' ? false : true)
```suggestion
              formik.setFieldValue(name, e.currentTarget.value !== 'targethost')
```

2023-10-21 08:05 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/ShellScriptStep/OptionalConfiguration.tsx
> +  const onDelegateVal = get(formValues, `${fieldName}`)
```suggestion
  const onDelegateVal = get(formValues, fieldName)
```

2023-10-21 08:05 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/ShellScriptStep/ShellScriptInputSetStep.tsx
> +            <HarnessDocTooltip tooltipId={'exec-target'} labelText={'Execution Target'} />
Can we add the label to strings?

2023-10-21 08:05 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/ShellScriptStep/helper.ts
> +  return values.spec?.onDelegate !== '' ? values.spec?.onDelegate : true
The function's return type is `string`, but this ternary can return true.

2023-10-23 22:42 UTC, sahithikolichala commented
retrigger typecheck

2023-10-24 06:49 UTC, rameshx approved these changes

2023-10-24 14:00 UTC, PratyushGar approved these changes

2023-10-24 14:31 UTC, merged