feat: [CDS-80915]: Update MultiTypeMap and MultiTypeMapInputSet to support default/allowed values
harness/harness-core-ui pull request #18569
Opened 2023-10-20 18:56 UTC by rameshx

### Summary

This updates MultiTypeMap and MultiTypeMapInputSet components to add default/allowed values support to the value field

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-25 06:32 UTC, chetanvekariya-harness approved these changes

2023-10-25 06:32 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/InputSetView/MultiTypeMapInputSet/__test__/MultiTypeMapInputSet.test.tsx
> +    expect(queryByNameAttribute('test[0].key', container)).toBeTruthy()
Can we use toBeInTheDocument instead? I think this could return `null` and `null` is truthy.

2023-10-25 06:32 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/InputSetView/MultiTypeMapInputSet/__test__/MultiTypeMapInputSet.test.tsx
> +    expect(container).toMatchSnapshot()
Can we add assertions instead of multiple snapshots?

2023-10-25 06:58 UTC, rameshx commented on src/modules/70-pipeline/components/InputSetView/MultiTypeMapInputSet/__test__/MultiTypeMapInputSet.test.tsx
> +    expect(queryByNameAttribute('test[0].key', container)).toBeTruthy()
Marking as resolved as this is an existing test and `null` is always falsy.

2023-10-25 06:59 UTC, rameshx commented on src/modules/70-pipeline/components/InputSetView/MultiTypeMapInputSet/__test__/MultiTypeMapInputSet.test.tsx
> +    expect(container).toMatchSnapshot()
Marking as resolved as this is an existing test

2023-10-25 08:38 UTC, d1wilko approved these changes
No issues stand out :)

2023-10-25 14:56 UTC, chris-harness commented
I notice in the video that the size of the "Key" input box in the step form changes when the input type is changed. The vertical spacing between environment variables also seems wider than it used to be on that form, and feels a bit excessive.

See timestamp 0:16 in the screen recording for examples of both issues.

2023-10-25 22:17 UTC, chris-harness requested changes
When I run a step using the "input" mode for an env var, with validation configured, the value placed in the environment variable incorrectly includes the validation description. The CI Pod gets `Critical.allowedValues(0,Critical,High,Medium,Low,Info)` in the env var when it should just receive the selected value `Critical`

2023-10-25 22:42 UTC, rameshx commented
> I notice in the video that the size of the "Key" input box in the step form changes when the input type is changed. The vertical spacing between environment variables also seems wider than it used to be on that form, and feels a bit excessive.
> 
> See timestamp 0:16 in the screen recording for examples of both issues.

Refactored all styles of the component to use grid. Updated the video.

2023-10-25 22:47 UTC, rameshx commented
> When I run a step using the "input" mode for an env var, with validation configured, the value placed in the environment variable incorrectly includes the validation description. The CI Pod gets `Critical.allowedValues(0,Critical,High,Medium,Low,Info)` in the env var when it should just receive the selected value `Critical`

Thanks for testing this e2e. Could you share the execution link?

2023-10-26 14:34 UTC, chris-harness commented
> > When I run a step using the "input" mode for an env var, with validation configured, the value placed in the environment variable incorrectly includes the validation description. The CI Pod gets `Critical.allowedValues(0,Critical,High,Medium,Low,Info)` in the env var when it should just receive the selected value `Critical`
> 
> Thanks for testing this e2e. Could you share the execution link?

I ran it locally, with QA env as the backend. I suspect you don't have access to the account, though: https://localhost:8181/ng/account/BdsgiWzwT7CQFeJl9XkQ3A/all/orgs/default/projects/STO/pipelines/Chris_Demo/executions/J9xAOATaTYCjt5jOgdu7Ug/pipeline?storeType=INLINE&stage=4RqL1ioARS--rHhVV0oefQ

Here's the YAML for the step:
```yaml
                  - step:
                      type: Security
                      name: OWASP 1
                      identifier: OWASP_1
                      spec:
                        privileged: true
                        settings:
                          policy_type: orchestratedScan
                          scan_type: repository
                          repository_project: chris_nodegoat
                          repository_branch: <+codebase.branch>
                          product_name: owasp
                          product_config_name: owasp
                          sto_dump_runner_logs: "true"
                          sto_plugin_normalization: "true"
                          fail_on_severity: <+input>.default(0).allowedValues(0,Critical,High,Medium,Low,Info)
                        imagePullPolicy: Always
                      when:
                        stageStatus: Success
```

2023-10-26 21:20 UTC, chris-harness approved these changes

2023-10-27 06:30 UTC, kalyansai-harness commented
@chetanvekariya-harness @d1wilko could you please review the PR soon.

2023-10-27 06:34 UTC, chetanvekariya-harness approved these changes

2023-10-27 06:34 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/InputSetView/MultiTypeMapInputSet/ValueInputSet.tsx
> +export function ValueInputSet(props: ValueInputSetProps): JSX.Element {
nit: MultiTypeMapValueInputSet would be more suitable component name

2023-10-27 08:12 UTC, d1wilko approved these changes
LGTM

2023-10-27 08:24 UTC, merged