[CDS-80629] fix incorrect error message artifactory artifactFilter
harness/harness-core-ui pull request #18716
Opened 2023-10-31 07:39 UTC by shivanand-harness

### Summary

Jira Ticket: https://harness.atlassian.net/browse/CDS-80629

When user enter Artifact Filter in Artifactory Generic artifact and if there is no artifactPath corresponding to it, BE sends and empty list and UI shows No artifact paths found with given Artifact Directory.
We can improve this message to consider Artifact Filter.

#### Screenshots

<img width="1112" alt="image" src="https://github.com/harness/harness-core-ui/assets/148759765/6d34ae33-8067-4753-815e-e8e6e05f1ee7">
<img width="1118" alt="image" src="https://github.com/harness/harness-core-ui/assets/148759765/d8600e09-b29e-4ee4-88cb-c42cf4d03e94">

https://github.com/harness/harness-core-ui/assets/148759765/b6477ec1-01e2-4511-9316-a89785ea0a70

https://github.com/harness/harness-core-ui/assets/148759765/21e4feb9-7656-48f5-9d2b-dca8b0c23631

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-31 07:43 UTC, vikrant-harness submitted a review, later dismissed

2023-10-31 08:56 UTC, chetanvekariya-harness requested changes

2023-10-31 08:56 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/strings/strings.en.yaml
> +noArtifactPaths:
We can make this message generic like this
noArtifactPaths: No artifact paths found with given {{filterField}}

2023-10-31 08:56 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
> +                              isServerlessDeploymentTypeSelected={false}
Is this hard-coding intended ? `isServerlessDeploymentTypeSelected={false}`

2023-10-31 09:52 UTC, chetanvekariya-harness requested changes

2023-10-31 09:52 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
>                                tagError={artifactoryTagError}
Why is `isServerlessDeploymentTypeSelected` removed? There is huge logic based on this in `NoTagResults` component?

2023-10-31 10:28 UTC, shivanand-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
>                                tagError={artifactoryTagError}
previously `isServerlessDeploymentTypeSelected ` is used to show the different message if generic artifactory is selected. however that message is depends on filter selected which was not handled in the `NoTagResults` component. because of this, component always render same message even if we select different filters.

now I removed the flag to use different message and added logic to show default error text. `NoTagResults` this component shows the default error text if `isServerlessDeploymentTypeSelected` is false

2023-10-31 10:43 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
>                                tagError={artifactoryTagError}
We discussed this. The huge logic was in same file, but in different component. Because two components were in same file, it appeared that NoTagResults is having huge logic. 
We should create separate file for NoTagResults and remove `isServerlessDeploymentTypeSelected` props as it is being passed as `false` from all components after this PR's changes.

2023-10-31 10:44 UTC, chetanvekariya-harness submitted a review, later dismissed

2023-11-02 07:37 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
> +                              defaultErrorText={
We can extract in a memoized variable above and then use it here.
This will help in increasing readability and will be more optimized

2023-11-03 05:47 UTC, shivanand-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/Artifactory.tsx
> +                              defaultErrorText={
@samarth-sharma31 we need formik instance which is not available outside render... so extracted to function to get the error text

2023-11-06 07:48 UTC, shivanand-harness commented
trigger messagecheck

2023-11-06 08:50 UTC, chetanvekariya-harness approved these changes

2023-11-06 09:08 UTC, samarth-sharma31 approved these changes

2023-11-06 09:14 UTC, shivanand-harness commented
trigger messagecheck

2023-11-06 09:53 UTC, shivanand-harness commented
trigger messagecheck

2023-11-06 09:57 UTC, merged