feat: [PLG-2997]: updating intitials for names for companies
harness/harness-core-ui pull request #18724
Opened 2023-10-31 11:32 UTC by dhruvUpadhyay07

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-31 11:50 UTC, kapil-harness requested changes

2023-10-31 11:50 UTC, kapil-harness commented on src/modules/10-common/components/ResourceCenter/utils.ts
> +const getInitials = name => {
I think for username 'Kapil.choudhary@harness.io' the output will be 'kci'

@dhruvUpadhyay07 lets first split on the basis of '@' then split on the basis of '.' to get the initials of first and last name

2023-10-31 12:03 UTC, dhruvUpadhyay07 commented on src/modules/10-common/components/ResourceCenter/utils.ts
> +const getInitials = name => {
We are doing that if you check the canny object

2023-10-31 12:07 UTC, kapil-harness commented on src/modules/10-common/components/ResourceCenter/utils.ts
> +const getInitials = name => {
ok, makes sense

2023-10-31 12:08 UTC, kapil-harness requested changes

2023-10-31 12:08 UTC, kapil-harness commented on src/modules/10-common/components/ResourceCenter/utils.ts
> +      name: initializeList.includes(account?.companyName.toLowerCase())
This change is not universal, so where is the list of accounts for which you have to do this change?

2023-10-31 12:09 UTC, dhruvUpadhyay07 commented on src/modules/10-common/components/ResourceCenter/utils.ts
> +      name: initializeList.includes(account?.companyName.toLowerCase())
Its declared at the top

2023-10-31 12:11 UTC, kapil-harness approved these changes

2023-10-31 13:14 UTC, kapil-harness requested changes

2023-10-31 13:14 UTC, kapil-harness commented on src/modules/10-common/components/ResourceCenter/utils.ts
> +const initializeList = ['disney']
@dhruvUpadhyay07 are we sure that company name for Disney is 'disney'? don't you think accountId would be a better check?

2023-12-19 19:44 UTC, bot2-harness commented
This PR has been automatically closed due to inactivity.

2023-12-19 19:44 UTC, closed without merging