[CDS-80297] Bugfix cds 80297 fix jenkins poll freq validation
harness/harness-core-ui pull request #18744
Opened 2023-11-02 07:21 UTC by shivanand-harness

### Summary
Input set:

when timeout fixed in pipeline, no validation for value greater than timeout.

when timeout runtime and provided value in input set, incorrect message when value greater than timeout: Retry interval should not be more than timeout

Triggers: similar issue 

#### Screenshots
**case 1: Timeout is fixed and polling frequency is set as runtime**
<img width="1728" alt="Screenshot 2023-11-02 at 12 25 02 PM" src="https://github.com/harness/harness-core-ui/assets/148759765/9c880eff-cb0f-4ace-ad4d-ebcabef5cf84">
<img width="1728" alt="Screenshot 2023-11-02 at 12 24 29 PM" src="https://github.com/harness/harness-core-ui/assets/148759765/78640186-8809-456b-a779-f7a02e29e936">
<img width="1728" alt="Screenshot 2023-11-02 at 12 24 16 PM" src="https://github.com/harness/harness-core-ui/assets/148759765/52d84f79-9d9b-4852-ab03-9dd79e47cae5">

Demo Video:
https://github.com/harness/harness-core-ui/assets/148759765/c43ba7fd-0658-4e45-ae75-a782a7db1cef

**case 2: Polling frequency is fixed and Timeout is set as runtime**
<img width="1728" alt="Screenshot 2023-11-02 at 12 22 21 PM" src="https://github.com/harness/harness-core-ui/assets/148759765/48652895-3f0a-4faf-93d2-9723d12ec055">
<img width="1727" alt="Screenshot 2023-11-02 at 12 21 57 PM" src="https://github.com/harness/harness-core-ui/assets/148759765/b4f08291-5596-4465-8092-eb38ef85848f">
<img width="1728" alt="Screenshot 2023-11-02 at 12 21 45 PM" src="https://github.com/harness/harness-core-ui/assets/148759765/161340cc-48c1-4b13-b6f8-ecadf17c786f">

Demo Video: 
Uploading Screen Recording 2023-11-02 at 12.33.11 PM.mov…

**case 3: Both Polling frequency and Timeout is set as runtime**
<img width="1728" alt="Screenshot 2023-11-02 at 12 26 50 PM" src="https://github.com/harness/harness-core-ui/assets/148759765/fd273581-a8c0-4c5a-b9d3-219c3dc44044">
<img width="1728" alt="Screenshot 2023-11-02 at 12 26 16 PM" src="https://github.com/harness/harness-core-ui/assets/148759765/fbeea395-050d-449b-8c05-9602aea58e12">
<img width="1728" alt="Screenshot 2023-11-02 at 12 26 03 PM" src="https://github.com/harness/harness-core-ui/assets/148759765/27c39140-d13b-480e-95d8-59fc76469f33">

Demo Video: 
https://github.com/harness/harness-core-ui/assets/148759765/aa5ac559-fc4d-443e-98f7-9b0f7213fe9e

**case 4: Both Polling frequency and Timeout is fixed**
<img width="1728" alt="Screenshot 2023-11-02 at 12 30 24 PM" src="https://github.com/harness/harness-core-ui/assets/148759765/a4896774-f132-48eb-97ad-6ba3e0842fe1">
<img width="1728" alt="Screenshot 2023-11-02 at 12 30 07 PM" src="https://github.com/harness/harness-core-ui/assets/148759765/8cc04c53-6eb4-4038-8288-a43456378fcc">

Demo Video: 
https://github.com/harness/harness-core-ui/assets/148759765/a2c32855-1708-4068-94d8-b352a2ec913a

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-03 05:57 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
>      template,
Coverage check is failing for jenkins step and artifact wizard, please check if we can add it in the current PR itself

2023-11-03 06:39 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
> +      !isEmpty(allValues?.timeout)
Same as above. If this is not needed then we can remove entire new argument `allValues`

2023-11-03 06:39 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
> +      !isEmpty(allValues?.spec?.consoleLogPollFrequency)
Is this even possible if it is required field ? Can consoleLogPollFrequency ever be empty?

2023-11-03 07:03 UTC, shivanand-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
> +      !isEmpty(allValues?.spec?.consoleLogPollFrequency)
This is just to make sure all the values required for validation are available and valid

2023-11-03 07:03 UTC, shivanand-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
> +      !isEmpty(allValues?.timeout)
This is just to make sure all the values required for validation are available and valid

2023-11-03 13:26 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
> +      !isEmpty(allValues?.timeout)
I think if we reach here with `allValues?.timeout` being empty then we have bigger concern. But, this is not an major concern, I agree. But, what if `allValues?.timeout` is expression. You can not use it for minimum in that case. So, please check that once.

2023-11-03 13:26 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
> +      !isEmpty(allValues?.spec?.consoleLogPollFrequency)
Same as above.

2023-11-06 05:02 UTC, shivanand-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
> +      !isEmpty(allValues?.timeout)
@chetanvekariya-harness we already handled this case with this condition `getMultiTypeFromValue(template?.timeout) === MultiTypeInputType.FIXED &&`. in template if value is fixed means in allValues it should be fixed value.

2023-11-06 05:02 UTC, shivanand-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
> +      !isEmpty(allValues?.spec?.consoleLogPollFrequency)
same applies here...

2023-11-06 05:42 UTC, chetanvekariya-harness submitted a review, later dismissed

2023-11-06 05:42 UTC, chetanvekariya-harness reviewed
Please cover this under jest.

2023-11-06 09:59 UTC, shivanand-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
>      template,
@samarth-sharma31 actually I dont have access to prod app so could not check the coverage check details. I have already raised a request for this. so I think I can take this separately once I get the access

2023-11-07 06:07 UTC, shivanand-harness commented
trigger messagecheck

2023-11-08 12:22 UTC, shivanand-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
>      template,
I have created separate ticket for improving the coverage... because existing code has very low coverage < 20. will improve this separately

2023-11-08 12:56 UTC, chetanvekariya-harness requested changes

2023-11-08 13:20 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/__tests__/OptionalConfiguration.test.tsx
> +  test('Basic snapshot: with readonly true', () => {
Make title proper.

2023-11-08 13:20 UTC, chetanvekariya-harness commented on src/modules/72-triggers/components/Triggers/ArtifactTrigger/__tests__/ArtifactTriggerWizard.test.tsx
> +    expect(container).toMatchSnapshot()
Remove this.

2023-11-08 13:37 UTC, chetanvekariya-harness approved these changes

2023-11-09 05:49 UTC, pankajsingh-harness requested changes

2023-11-09 05:49 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
> +      getMultiTypeFromValue(template?.timeout) === MultiTypeInputType.FIXED &&
NIT: We can define util function to check for run-time field
```
export const isFieldRuntime = (fieldPath: string, template?: ServiceSpec): boolean =>
  getMultiTypeFromValue(get(template, fieldPath)) === MultiTypeInputType.RUNTIME
```

2023-11-09 05:49 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/Triggers/ArtifactTrigger/ArtifactTriggerWizard.tsx
> +            orgPipeline: initialValues?.originalPipeline || values?.pipeline,
This change needs to made for other kinds of triggers as well.

- src/modules/72-triggers/components/Triggers/ManifestTrigger/ManifestTriggerWizard.tsx:1131
- src/modules/72-triggers/components/Triggers/ScheduledTrigger/ScheduledTriggerWizard.tsx:860
- src/modules/72-triggers/components/Triggers/WebhookTrigger/WebhookTriggerWizard.tsx:1293
- src/modules/72-triggers/pages/triggers/TriggersWizardPage.tsx: 1973

2023-11-09 10:37 UTC, pankajsingh-harness approved these changes

2023-11-09 11:03 UTC, chetanvekariya-harness approved these changes

2023-11-09 11:07 UTC, shivanand-harness commented on src/modules/72-triggers/components/Triggers/ArtifactTrigger/ArtifactTriggerWizard.tsx
> +            orgPipeline: initialValues?.originalPipeline || values?.pipeline,
updated

2023-11-10 08:18 UTC, samarth-sharma31 commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
>      const errors = {} as any
Please test this for step template flow as well - Jenkins Build Step template where poll frequency is runtime

2023-11-10 09:01 UTC, shivanand-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStep/JenkinsStep.tsx
>      const errors = {} as any
@samarth-sharma31 uploaded video in PR description

2023-11-10 09:15 UTC, samarth-sharma31 approved these changes

2023-11-10 11:54 UTC, shivanand-harness commented
created separate ticket for improving coverage as existing coverage for these files are very less (<20).

2023-11-10 12:15 UTC, merged