feat: [PL-42158]: accept and show error message for unauthorized msg
harness/harness-core-ui pull request #18815
Opened 2023-11-06 09:00 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-07 13:58 UTC, mayankVermaHarness commented on src/framework/app/App.tsx
> +              })
Let's NOT abstract out the complexity here. This is a critical piece and I would prefer to keep statements right here instead of in a separate function altogether. Let all statements remain here, even if it means that same code is written twice.

2023-11-07 14:10 UTC, mayankVermaHarness commented on src/framework/utils/SessionUtils.ts
> +  UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
This is how it is on backend. Let's maintain the same here.

2023-11-08 08:54 UTC, namanharness commented on src/framework/utils/SessionUtils.ts
> +  UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
done

2023-11-08 08:55 UTC, namanharness commented on src/framework/app/App.tsx
> +              })
did that so that in future if we are handling many cases we have a common f(x) to handle it.
reverted it back to the original way

2023-11-21 12:53 UTC, mayankVermaHarness commented on src/framework/app/App.tsx
>              // if 401 occurred due to a reason other than whitelist, logout nevertheless
Let's update the comment

2023-11-21 15:41 UTC, mayankVermaHarness submitted a review, later dismissed
This is strongly tied to the NG-Auth-UI PR: https://github.com/harness/harness-auth-ui/pull/229

They should be released together.

2023-11-21 22:19 UTC, abhinavrastogi-harness requested changes

2023-11-21 22:19 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +            const unauthorizedErrorMessage = getUnauthorizedErrorMessage(res, 'UNAUTHORIZED')
why not use the constants defined on lines 47-48?

2023-11-21 22:19 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +              forceLogout(clonedResponse.status === 401 ? ErrorCode.UNAUTHORIZED : undefined)
instead of duplicating this, can't we handle all of this in one block? it seems only the error code is different. the handling after that is all the same.

2023-11-21 22:19 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +              sessionStorage.setItem('UNAUTHORIZED', msg)
why do we need to use session storage? we had used it earlier for SSO errors because they involve a third-party redirect, which prevents using query params.
for our internal redirects, just adding a query param `errorCode` on the signin page should be sufficient.

2023-11-21 22:19 UTC, abhinavrastogi-harness commented
no tests added/changed for this?

2023-11-21 22:20 UTC, namanharness commented on src/framework/app/App.tsx
> +              forceLogout(clonedResponse.status === 401 ? ErrorCode.UNAUTHORIZED : undefined)
https://github.com/harness/harness-core-ui/pull/18815#discussion_r1384959211

2023-11-22 11:51 UTC, mayankVermaHarness commented on src/framework/app/App.tsx
> +              sessionStorage.setItem('UNAUTHORIZED', msg)
@abhinavrastogi-harness We can't send the entire long message (received from backend) in URL to Auth-UI as a query param, hence saved it in `sessionStorage`.

2023-11-27 17:49 UTC, abhinavrastogi-harness approved these changes

2023-11-28 12:55 UTC, mayankVermaHarness approved these changes

2023-11-28 13:07 UTC, merged