fix: [CDS-80292]: add mapping for jenkinsBuildV2 in pipeline execution view
harness/harness-core-ui pull request #18841
Opened 2023-11-07 06:29 UTC by shivanand-harness

### Summary

Jira Ticket: https://harness.atlassian.net/browse/CDS-80292

Fix: there was no mapping for JenkinsBuildV2 in UI side for pipeline execution view. After discussion with Deepak Puthraya
cloned JenkinsBuild and created mapping for JenkinsBuildV2.

#### Screenshots

Before Fix: 

https://github.com/harness/harness-core-ui/assets/148759765/c1894b1a-4c0f-49ed-9a95-17dda3759454

After Fix:

https://github.com/harness/harness-core-ui/assets/148759765/cbae2bb7-9d13-4a6d-b042-701720d68b4d

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-07 07:39 UTC, shivanand-harness commented
retrigger eslint

2023-11-07 08:43 UTC, shivanand-harness commented
retrigger eslint-warnings

2023-11-07 08:43 UTC, shivanand-harness commented
retrigger eslint_warnings

2023-11-08 12:24 UTC, shivanand-harness commented
created separate ticket to improve the coverage as existing code has very low coverage. https://harness.atlassian.net/browse/CDS-83772

2023-11-08 15:31 UTC, rameshx approved these changes

2023-11-08 16:05 UTC, chetanvekariya-harness approved these changes

2023-11-08 16:05 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/__tests__/JenkinsStep.test.tsx
> +    expect(container).toMatchSnapshot()
Let's avoid snapshot testing?

2023-11-08 16:05 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/JenkinsStep.tsx
> +  protected defaultValues: JenkinsStepData = {
I don't see any change here that is different than existing step. What has changed?
Don't we need `type: StepType.JenkinsBuildV2`?

2023-11-08 16:11 UTC, chetanvekariya-harness requested changes
Please check comments.

2023-11-09 05:04 UTC, shivanand-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/JenkinsStep.tsx
> +  protected defaultValues: JenkinsStepData = {
yes, missed at one place. Updated now.

2023-11-09 08:03 UTC, shivanand-harness commented
retrigger eslint

2023-11-09 10:05 UTC, rameshx submitted a review, later dismissed

2023-11-09 11:09 UTC, vikrant-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/__tests__/__snapshots__/JenkinsStep.test.tsx.snap
> +exports[`Jenkins step tests Basic snapshot - deploymentform mode 1`] = `
Let's avoid such huge snapshots

2023-11-09 11:10 UTC, vikrant-harness approved these changes

2023-11-09 12:35 UTC, chetanvekariya-harness requested changes

2023-11-09 12:35 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/__tests__/JenkinsStep.test.tsx
> +jest.mock('@common/components/YAMLBuilder/YamlBuilder')
Not needed.

2023-11-09 12:35 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/__tests__/JenkinsStep.test.tsx
> +    factory.registerStep(new JenkinsStepV2())
Registering once should be fine.

2023-11-09 12:35 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/__tests__/JenkinsStep.test.tsx
> +    const response = new JenkinsStepV2().validateInputSet({
You can render component, submit form and check errors to appear on screen/dom. That will cover entire flow.

2023-11-09 12:35 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/__tests__/__snapshots__/JenkinsStep.test.tsx.snap
> +  "timeout": "Value must be greater than or equal to \\"10s\\"",
This can be removed.

2023-11-09 12:35 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/__tests__/JenkinsStep.test.tsx
> +    const errorResponse = new JenkinsStepV2().validateInputSet(inputData)
Same as above.

2023-11-09 12:35 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/__tests__/JenkinsStep.test.tsx
> +    const errorResponse = new JenkinsStepV2().validateInputSet(inputData)
Same as above.

2023-11-10 10:42 UTC, chetanvekariya-harness approved these changes

2023-11-10 10:44 UTC, chetanvekariya-harness approved these changes

2023-11-10 10:44 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/__tests__/JenkinsStepV2.test.tsx
> +      expect(queryByText('{}')).toBeInTheDocument()
nit: we can pick up any error text and check that it should not be in the document.

2023-11-10 10:49 UTC, shivanand-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JenkinsStepV2/__tests__/JenkinsStepV2.test.tsx
> +      expect(queryByText('{}')).toBeInTheDocument()
yes will do it in next PR

2023-11-10 10:52 UTC, rameshx approved these changes

2023-11-10 10:57 UTC, vikrant-harness approved these changes

2023-11-10 11:49 UTC, merged