feat: [CDS-82861]: added cluster select dropdown
harness/harness-core-ui pull request #18862
Opened 2023-11-07 23:57 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-15 04:10 UTC, sahithikolichala commented
trigger messagecheck

2023-11-15 21:38 UTC, sahithikolichala commented
retrigger lint

2023-11-15 21:39 UTC, sahithikolichala commented
retrigger eslint

2023-11-16 01:17 UTC, sahithikolichala commented
retrigger eslint

2023-11-17 04:46 UTC, samarth-sharma31 commented on src/modules/10-common/components/MultiTypeEntitySelector/MultiTypeEntitySelector.tsx
> +// import { useStrings } from 'framework/strings'
this can be removed if not required

2023-11-17 04:48 UTC, samarth-sharma31 commented on src/modules/10-common/components/MultiTypeEntitySelector/MultiTypeEntitySelector.tsx
> +import {
Can you please add screenshots and video in the PR and description as well

2023-11-17 05:08 UTC, sahithikolichala commented on src/modules/10-common/components/MultiTypeEntitySelector/MultiTypeEntitySelector.tsx
> +import {
added video on the slack as the video is too big https://harness.slack.com/archives/C05HZMXAGGG/p1700169100443049

2023-11-17 05:36 UTC, samarth-sharma31 requested changes

2023-11-17 05:36 UTC, samarth-sharma31 commented on src/modules/10-common/components/MultiTypeEntitySelector/MultiTypeEntitySelector.tsx
> +const MultiTypeEntitySelector = (props: MultiTypeEntitySelectorProps): React.ReactElement => {
Also the CSS for the Multi cluster component looks very off - please check multi service and Multi env selection for reference - ideally it should be similar to that UX wise

2023-11-17 05:36 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/AddCluster.module.scss
> +.highlightCluster {
Please try to use css variables where ever possible

2023-11-17 05:36 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/SelectCluster.tsx
> +  //   useLinkClusters,
please remove if not required

2023-11-17 05:36 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/SelectCluster.tsx
> +// import { getErrorMessage } from '@triggers/components/Triggers/ManifestTrigger/ManifestWizardPageUtils'
please remove if not required

2023-11-17 05:36 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/SelectCluster.tsx
> +    return getClusterListFromSourcePromise({
Please check error handling if this fails

2023-11-17 05:36 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/SelectCluster.tsx
> +    if (props?.selectedRecords?.length) {
props wil be defined, no need for optional chaining

2023-11-17 05:36 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/SelectCluster.tsx
> +            // const key = `${_item.identifier}${DELIMITER}${_item.scopeLevel}`
please remove if not required

2023-11-17 05:36 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/__tests__/SelectCluster.test.tsx
> +const clusters = [
mocks can be added to a separate file

2023-11-17 05:36 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/utils/singleEnvironment/processSingleEnvironmentInitialValues.ts
> +                agentIdentifier: gitOpsCluster?.agentIdentifier
do we need optional chaining here ?

2023-11-20 00:06 UTC, sahithikolichala commented on src/modules/10-common/components/MultiTypeEntitySelector/MultiTypeEntitySelector.tsx
> +const MultiTypeEntitySelector = (props: MultiTypeEntitySelectorProps): React.ReactElement => {
@samarth-sharma31  can you point me to the right component

2023-11-22 19:21 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/GitOpsCluster.tsx
> +      label={props.label || 'Clusters'}
please use getString() for default values

2023-11-22 19:21 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/GitOpsCluster.tsx
> +      placeholder={props.label || 'Select'}
https://github.com/harness/harness-core-ui/pull/18862/files#r1402622430

2023-11-22 19:25 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployClusterEntityStep/DeployClusterEntityInputStep.tsx
> +          allowMultiple={isMultipleCluster || true}
Please test for readonly -> true flow

2023-11-23 00:30 UTC, sahithikolichala commented
retrigger eslint

2023-11-23 05:29 UTC, samarth-sharma31 approved these changes

2023-11-28 00:20 UTC, sahithikolichala commented
retrigger jest

2023-11-28 00:20 UTC, sahithikolichala commented
retrigger coverage

2023-11-28 00:32 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/__tests__/GitOpsCluster.test.tsx
> +    expect(form).toMatchSnapshot()
please dont add snapshot tests.. use assertions instead

2023-11-28 00:44 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/DeployCluster.tsx
> +          allowMultiple={isMultiCluster || true}
hardcoded `true`?

2023-11-28 00:44 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/DeployCluster.tsx
> +          loading={false}
hardcoded `false`?

2023-11-28 00:44 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/DeployCluster.tsx
> +  // const [error, setError] = useState('')
let's remove commented code

2023-11-28 00:44 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/DeployCluster.tsx
> +    const selItems = items.map(item => ({
```suggestion
    const selItems: ClusterItem[] = items.map(item => ({
```

2023-11-28 00:44 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/DeployCluster.tsx
> +    })) as ClusterItem[]
```suggestion
    }))
```

2023-11-28 00:44 UTC, abhinavrastogi-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/DeployCluster.tsx
> +/* eslint-disable duplicate-data-tooltip-id */
why is this needed?

2023-11-28 02:32 UTC, sahithikolichala commented
retrigger jest

2023-11-28 04:19 UTC, sahithikolichala commented
trigger sonar

2023-11-29 06:09 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/utils/multiEnvironment/processMultiEnvironmentFormValues.ts
> +        // istanbul ignore next
why have we added this comment ?

2023-11-29 06:09 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/utils/multiEnvironment/processMultiEnvironmentFormValues.ts
> +        // istanbul ignore next
https://github.com/harness/harness-core-ui/pull/18862/files#r1408791107

2023-11-29 06:09 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/utils/multiEnvironment/processMultiEnvironmentFormValues.ts
> +  // istanbul ignore next
https://github.com/harness/harness-core-ui/pull/18862/files#r1408791107

2023-11-29 06:10 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/utils/singleEnvironment/processSingleEnvironmentFormValues.ts
> +        getMultiTypeFromValue(selectedClusters as any) === MultiTypeInputType.RUNTIME
please avoid any whenever possible

2023-11-29 06:16 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/GitOpsCluster.tsx
> +      environmentIdentifier: defaultTo(get(props, 'envRef'), '')
I don't think we need to use lodash get for props - will they be undefined in any scenario

2023-11-29 06:17 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/GitOpsCluster.tsx
> +      name={defaultTo(get(props, 'name'), getString('common.clusters'))}
https://github.com/harness/harness-core-ui/pull/18862/files#r1408796936

2023-11-29 06:17 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/GitOpsCluster.tsx
> +      label={defaultTo(get(props, 'label'), getString('common.clusters'))}
https://github.com/harness/harness-core-ui/pull/18862/files#r1408796936

2023-11-29 06:18 UTC, samarth-sharma31 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/GitOpsCluster.tsx
> +        // istanbul ignore next
Why have we added this ?

2023-11-29 06:21 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployClusterEntityStep/DeployClusterEntityInputStep.tsx
> +    if (isValueRuntimeInput(values as any)) {
please try to avoid any whenever possible

2023-11-29 06:23 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployClusterEntityStep/DeployClusterEntityInputStep.tsx
> +            selectedData={getSelectedClustersFromOptions((formik?.values as any)?.gitOpsClusters) as any}
this will get evaluated on every render, please check if this can be memoized

2023-11-29 06:25 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployClusterEntityStep/__tests__/DeployClusterEntityInputStep.test.tsx
> +      content: [
Please move mocks to a separate file

2023-11-29 06:26 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployClusterEntityStep/__tests__/DeployClusterEntityStep.test.tsx
> +      content: [
Please move mocks to a separate file

2023-11-29 06:27 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/DeployCluster.tsx
> +  // istanbul ignore next
please remove this

2023-11-29 06:28 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/DeployCluster.tsx
> +    getMultiTypeFromValue(isMultiCluster ? (values.clusters?.[environmentIdentifier] as any) : values.cluster) ===
lets not use any

2023-11-29 06:28 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/useGetClustersData.test.tsx
> +      data: {
Please move mocks to a separate file

2023-11-29 14:59 UTC, sahithikolichala commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/GitOpsCluster.tsx
> +      environmentIdentifier: defaultTo(get(props, 'envRef'), '')
This is to help getting cover branches

2023-11-29 14:59 UTC, sahithikolichala commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/GitOpsCluster.tsx
> +      name={defaultTo(get(props, 'name'), getString('common.clusters'))}
same here

2023-11-29 15:05 UTC, sahithikolichala commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/GitOpsCluster.tsx
> +        // istanbul ignore next
This cannot be covered thru unit test, so to get coverage

2023-11-29 17:16 UTC, kalyansai-harness commented on src/modules/70-pipeline/components/FormMultiTypeEntitySelector/FormMultiTypeEntitySelector.tsx
> +  // istanbul ignore next
why is this?

2023-11-29 19:01 UTC, sahithikolichala commented
retrigger jest

2023-11-29 20:35 UTC, abhinavrastogi-harness approved these changes

2023-11-30 17:12 UTC, vikrant-harness commented on src/modules/70-pipeline/components/FormMultiTypeEntitySelector/FormMultiTypeEntitySelector.tsx
> +              isNewConnectorLabelVisible: isNewConnectorLabelVisible,
can we rename this ? this should be isNewClusterLabelVisible ?

2023-11-30 17:13 UTC, vikrant-harness commented on src/modules/70-pipeline/components/FormMultiTypeEntitySelector/FormMultiTypeEntitySelector.tsx
> +            onMultiSelectChange(val as string)
we should have separate prop for single select change right ? this is still calling onMultiSelectChange here ? But this will be triggered when we add only single select options ?

2023-11-30 17:14 UTC, vikrant-harness commented on src/modules/70-pipeline/components/FormMultiTypeEntitySelector/FormMultiTypeEntitySelectorField.module.scss
> +  padding: 8px 16px;
let's use vars here rather than hardcoding values

2023-11-30 17:14 UTC, vikrant-harness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/GitOpsCluster/AddCluster.module.scss
> +  margin: -8px -16px;
let's use vars here

2023-11-30 17:16 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/DeployCluster.tsx
> +  // const [error, setError] = useState('')
@sahithikolichala this is still there

2023-11-30 17:17 UTC, vikrant-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/DeployCluster.tsx
> +        setFieldValue(`gitOpsClusters`, RUNTIME_INPUT_VALUE)
this will cause race conditions , we should never do multiple setFieldValue , instead use setValues here

2023-11-30 17:44 UTC, sahithikolichala commented on src/modules/70-pipeline/components/FormMultiTypeEntitySelector/FormMultiTypeEntitySelector.tsx
> +            onMultiSelectChange(val as string)
The onchange functionality is same for both multiselect and single select @vikrant-harness

2023-12-01 07:29 UTC, chetanvekariya-harness submitted a review, later dismissed
Good to address comments regarding better practices. But, I do not see any major code issue. I am good if feature is tested well.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/__tests__/ClusterEntitiesList.test.tsx
> +      <TestWrapper
TestWrapper is not needed.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/__tests__/ClusterEntitiesList.test.tsx
> +      <TestWrapper
Same as above.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/__tests__/ClusterEntitiesList.test.tsx
> +    const clusterEntities = await findByTestId(container, 'cluster-entities-list')
Assert on each clusters presence.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/useGetClustersData.test.tsx
> +describe('useGetClustersData for success case', () => {
useGetClustersData tests

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/useGetClustersData.test.tsx
> +jest.mock('@harness/uicore', () => ({
Remove this.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/useGetClustersData.test.tsx
> +    expect(clustersList?.length).toBeGreaterThan(0)
Why not expect on exact width?

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/useGetClusterData_error.test.tsx
> +jest.mock('@harness/uicore', () => ({
Remove this.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/useGetClusterData_error.test.tsx
> +describe('useGetClustersData for success case', () => {
Title is not correct. Also club this and below into one. We do not need to create entire suit for one test case. These call can be clubbed into one suit.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/DeployCluster.test.tsx
> +    useFormikContextMock.mockReturnValue({
Wrap component into formik instead

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/DeployCluster.test.tsx
> +      <TestWrapper
TestWrapper not needed.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/DeployCluster.test.tsx
> +    useFormikContextMock.mockReturnValue({
Same as above.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/DeployCluster.test.tsx
> +    waitFor(() => expect(dialog).toBeFalsy())
After removing better to check that that cluster is not present on UI

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/DeployCluster.test.tsx
> +    expect(await screen.findByPlaceholderText('<+input>')).toBeVisible()
We do not need to check if value can be marked as Runtime input because this component is already tested in uicore. If would be okay if you are testing if Runtime input is allowed.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/DeployCluster.test.tsx
> +    })
Where are we selecting cluster, clicking on Apply Changes and verify if cluster got selected properly ? Title of test says `select a cluster`, assertions don't seem to comply with title.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/DeployCluster.tsx
> +    getMultiTypeFromValue(isMultiCluster ? (values.clusters?.[environmentIdentifier] as any) : values.cluster) ===
+1

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployClusterEntityStep/__tests__/DeployClusterEntityStep.test.tsx
> +    useFormikContextMock.mockReturnValue({
Wrap component in Formik instead

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployClusterEntityStep/__tests__/DeployClusterEntityInputStep.test.tsx
> +    useFormikContextMock.mockReturnValue({
Use TestStepWidget while rendering component instead.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployClusterEntityStep/__tests__/DeployClusterEntityInputStep.test.tsx
> +  const useFormikContextMock = jest.spyOn(Formik, 'useFormikContext')
Use TestStepWidget while rendering component instead. Sample applies everywhere and remove all mocking except for props and API responses.

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployClusterEntityStep/DeployClusterEntityInputStep.tsx
> +    if (isValueRuntimeInput(values as any)) {
+1

2023-12-01 07:29 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/FormMultiTypeEntitySelector/FormMultiTypeEntitySelector.tsx
> +export function MultiTypeEntitySelectorField(props: EntityGroupProps): React.ReactElement {
Component name can be same as file name
Also, we have used specific names for other entities as well. So, we can follow that.
File and component name can be changed to `FormMultiTypeGitOpsClusterField`

2023-12-02 00:39 UTC, sahithikolichala commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/useGetClustersData.test.tsx
> +    expect(clustersList?.length).toBeGreaterThan(0)
width?

2023-12-02 00:44 UTC, sahithikolichala commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/__tests__/ClusterEntitiesList.test.tsx
> +      <TestWrapper
It is needed, as clusterentities has strings internally 
Can you please say why it is not needed?

2023-12-02 00:53 UTC, sahithikolichala commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/DeployCluster.test.tsx
> +      <TestWrapper
why is it not needed?

2023-12-02 00:58 UTC, sahithikolichala commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/DeployCluster.test.tsx
> +    })
I wanted to test the select functionality, but the component internally uses MultiTypeReferenceInput
It is running into some issues.
This might need some refactor of the component, I will take it up as a separate task

2023-12-04 07:00 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/DeployCluster.test.tsx
> +    })
It opens modal in portal div, if that is the issue.
If content is not appearing then it might be issue with props or API mocking.

2023-12-04 07:01 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/DeployCluster.test.tsx
> +      <TestWrapper
TestWrapper is needed when you want to pass path, pathParams or feature flag values etc. You are doing none here. So, it is not needed. Check if it is working without TestWrapper.

2023-12-04 07:02 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/useGetClusterData_error.test.tsx
> +describe('useGetClustersData for success case', () => {
You would have to use jest.clearAllMocks inside afterEach.

2023-12-04 07:02 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/useGetClustersData.test.tsx
> +    expect(clustersList?.length).toBeGreaterThan(0)
Sorry, I meant length.

2023-12-04 07:04 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/__tests__/ClusterEntitiesList.test.tsx
> +      <TestWrapper
Explained in one of other comments. It is not needed if you are not passing path, pathParams etc. Try it without TestWrapper.

2023-12-04 22:06 UTC, sahithikolichala commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/__tests__/ClusterEntitiesList.test.tsx
> +      <TestWrapper
i still dont get but i am passing path , and path params here
also without testwrapper it breaks for strings reference

2023-12-04 22:06 UTC, sahithikolichala commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/__tests__/ClusterEntitiesList.test.tsx
> +      <TestWrapper
i need testwrapper, component has reference for strings internally 
without testwrapper it fails

2023-12-04 22:12 UTC, sahithikolichala commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/useGetClusterData_error.test.tsx
> +describe('useGetClustersData for success case', () => {
Tried that but does not seem to pass!

2023-12-04 22:13 UTC, sahithikolichala commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/DeployCluster/__tests__/DeployCluster.test.tsx
> +      <TestWrapper
It does not work without TestWrapper

2023-12-05 07:51 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/DeployEnvironmentEntityStep/__tests__/ClusterEntitiesList.test.tsx
> +      <TestWrapper
Cool. Resolving comment then.

2023-12-11 19:52 UTC, sahithikolichala commented
Video recording for the feature

https://github.com/harness/harness-core-ui/assets/57372986/1a466f0e-bd57-43cd-93fa-95c745ef9dbc

2023-12-12 03:33 UTC, abhinavrastogi-harness approved these changes

2023-12-12 03:37 UTC, merged