fix: [PL-41423]: show By Type RG entities summary in RG list page
harness/harness-core-ui pull request #19103
Opened 2023-11-22 13:17 UTC by namanharness

### Summary
Bugs Fixed: 
- In resource group list page, entities which were added through `By Type` were not showing any info. it used to show , All Environments in that case as well.
- No delegates component was rendered on top of the page body , fixed it. 
[Link](https://harness.atlassian.net/browse/PL-42981)

Before:
https://harness.slack.com/files/U05JTAGLHJT/F05TZC924P2/screen_recording_2023-09-21_at_1.38.58_pm.mov

After: 

https://github.com/harness/harness-core-ui/assets/110456765/be4743a9-8339-4498-a77a-cc5f7df9a296

| Before | After |
|--------|--------|
| <img width="1792" alt="image" src="https://github.com/harness/harness-core-ui/assets/110456765/cdb225b0-cfe1-4048-b319-4a875a790e97"> | <img width="1792" alt="image" src="https://github.com/harness/harness-core-ui/assets/110456765/59f04f2f-b227-4165-bace-de93777c5e30"> | 

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-22 13:27 UTC, namanharness commented on src/modules/20-rbac/components/ResourceGroupList/ResourceGroupListView.tsx
> +                if (!!resource?.attributeFilter) {
for By Type entities, `attributeFilter` object comes from BE

2023-11-22 13:50 UTC, ishantmehtaharness submitted a review, later dismissed
Looks good to me

2023-11-22 14:58 UTC, namanharness commented
This fix is part of Platform Bugathon and the test cases will be after it
cc @kalyansai-harness @gn-harness

2023-11-22 15:08 UTC, ishantmehtaharness approved these changes

2023-11-22 15:19 UTC, pankajsingh-harness commented on src/modules/27-platform/delegates/pages/delegates/DelegatesPage.module.scss
> +  margin-top: calc(0.25 * 915px);
@namanharness this will not work with different screen size.

2023-11-22 15:22 UTC, namanharness commented on src/modules/27-platform/delegates/pages/delegates/DelegatesPage.module.scss
> +  margin-top: calc(0.25 * 915px);
what would be the right fix? would margin top of 25% work?

2023-11-22 15:30 UTC, pankajsingh-harness commented on src/modules/27-platform/delegates/pages/delegates/DelegatesPage.module.scss
> +  margin-top: calc(0.25 * 915px);
You can use 
```
    height: calc(100vh - 97px); // Header height is 97px
    justify-content: center;
```

2023-11-22 15:43 UTC, namanharness commented on src/modules/27-platform/delegates/pages/delegates/DelegatesPage.module.scss
> +  margin-top: calc(0.25 * 915px);
thanks for helping out @pankajsingh-harness

2023-11-22 16:02 UTC, pankajsingh-harness approved these changes

2023-11-22 16:56 UTC, namanharness commented on src/modules/20-rbac/components/ResourceGroupList/ResourceGroupListView.tsx
> +                if (!isUndefined(resource?.attributeFilter)) {
lint was failing that on the condition that double negation is not required meaning 
`if (resource?.attributeFilter)` is sufficient but added the !isUndefined check for safety.

should i just keep the condition like this? `if(resource?.attributeFilter)`

2023-11-22 20:37 UTC, abhinavrastogi-harness requested changes

2023-11-22 20:37 UTC, abhinavrastogi-harness commented on src/modules/27-platform/delegates/pages/delegates/DelegatesPage.module.scss
> +  height: calc(100vh - 97px); // Header height is 97px
pages should not define their own height. instead just set the global css variable
`--page-header-height: 97px` and the layout framework should handle everything else correctly.

2023-11-28 17:28 UTC, abhinavrastogi-harness commented on src/modules/27-platform/delegates/pages/delegates/DelegatesPage.module.scss
> +  height: calc(100vh - 97px); // Header height is 97px
eg. https://github.com/harness/harness-core-ui/blob/develop/src/modules/45-projects-orgs/pages/projects/ProjectsPage.module.scss#L9

2023-11-29 10:59 UTC, mayankVermaHarness commented on src/modules/20-rbac/components/ResourceGroupList/ResourceGroupListView.tsx
> +                if (!isUndefined(resource?.attributeFilter)) {
Yes

2023-12-04 17:47 UTC, abhinavrastogi-harness commented on src/modules/27-platform/delegates/pages/delegates/DelegatesPage.module.scss
> +  height: calc(100vh);
you need to remove the height.. otherwise this just overrides and causes overflow

2023-12-04 20:58 UTC, abhinavrastogi-harness approved these changes
Approving to unblock the main feature.
But CSS needs to be fixed in a follow up. The page height is still not correct.

2023-12-05 05:54 UTC, merged