feat: [code-1155]: add harness support for triggers
harness/harness-core-ui pull request #19206
Opened 2023-11-29 22:59 UTC by cjlee01

### Summary

add harness support for triggers

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-30 03:26 UTC, sahithikolichala commented on src/modules/72-triggers/pages/triggers/utils/TriggersWizardPageUtils.ts
> +            if (this.parent.sourceRepo === HARNESS) {
dont we need to check for null

2023-11-30 03:27 UTC, sahithikolichala commented on src/modules/72-triggers/pages/triggers/utils/TriggersWizardPageUtils.ts
> +              if (repoName) return true
use either if() { } else {} ... there are different patterns
https://github.com/harness/harness-core-ui/pull/19206/files#diff-ba3f0864e3d2d46954436587f50f3619ce3c53ec0e480e2fd8dde2afe2685601R177
be consistent

2023-11-30 06:18 UTC, cjlee01 commented on src/modules/72-triggers/pages/triggers/utils/TriggersWizardPageUtils.ts
> +            if (this.parent.sourceRepo === HARNESS) {
added null check

2023-12-08 08:08 UTC, pankajsingh-harness requested changes
As discussed over call, Please make the required changes.

2023-12-13 10:52 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/Triggers/utils.tsx
> +  Required<WebhookTriggerConfigV2>['type'],
Made this Object TypeSafe so there are many changes due to this.

2023-12-13 11:08 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/Triggers/utils.tsx
> +  Required<WebhookTriggerConfigV2>['type'],
Just change in key name. No change in value.

2023-12-13 11:09 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/Triggers/utils.tsx
> -export const CUSTOM = 'Custom'
Use value from GitSourceProviders instead of defining again.

2023-12-13 11:09 UTC, pankajsingh-harness commented on src/modules/72-triggers/components/Triggers/utils.tsx
> -export const AwsCodeCommit = 'AwsCodeCommit'
Use value from GitSourceProviders. Instead of defining again

2023-12-13 11:11 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/utils/TriggersListUtils.ts
> -export const GitSourceProviders: Record<
Removed this duplicate object

2023-12-13 11:15 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/utils/TriggersListUtils.ts
>  export const getSourceRepoOptions = (getString: (str: StringKeys) => string): { label: string; value: string }[] => [
Removed this duplicate function

2023-12-13 11:32 UTC, pankajsingh-harness commented on src/modules/72-triggers/pages/triggers/utils/TriggersListUtils.ts
> -export const getSourceRepoOptions = (getString: (str: StringKeys) => string): { label: string; value: string }[] => [
Removed this duplicate function

2023-12-13 13:42 UTC, pankajsingh-harness approved these changes

2023-12-13 18:26 UTC, merged