feat: [CDS-86103]: user license view ui changes
harness/harness-core-ui pull request #19285
Opened 2023-12-05 23:39 UTC by sahithikolichala

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-06 19:09 UTC, satyam-harness submitted a review, later dismissed

2023-12-06 23:24 UTC, abhinavrastogi-harness requested changes
how come there's no tests updated for this change? looks like a change in business logic, which should be unit tested. Especially because this is hard to test with real data as it involves licensing corner cases.

2023-12-06 23:24 UTC, abhinavrastogi-harness commented on src/modules/27-platform/auth-settings/pages/subscriptions/overview/CDUsageInfo.tsx
> +          <Text>{Math.ceil(count / workloads)}%</Text>
`workloads` defaults to `0`.. which will lead to division by zero error, and display `Infinity%` probably or crash.

2023-12-06 23:24 UTC, abhinavrastogi-harness commented on src/modules/27-platform/auth-settings/pages/subscriptions/overview/CDUsageInfo.tsx
> +            computedCount={Math.ceil((usage?.cd?.serviceLicenses?.count || 0) / 3)}
looks like the only difference in the above and here is the division by `60` or by `3`. can we move that condition here, and avoid duplicating the entire tree?

2023-12-06 23:24 UTC, abhinavrastogi-harness commented on src/modules/27-platform/auth-settings/pages/subscriptions/overview/SubscriptionUtils.tsx
> +export const MAX_LICENSES = 1000000
this looks wrong. why are we hardcoding max licenses in the UI?

2023-12-07 00:36 UTC, sahithikolichala commented on src/modules/27-platform/auth-settings/pages/subscriptions/overview/SubscriptionUtils.tsx
> +export const MAX_LICENSES = 1000000
This was asked by @AnshuH  to have this default Value and compare

2023-12-07 00:39 UTC, sahithikolichala commented on src/modules/27-platform/auth-settings/pages/subscriptions/overview/CDUsageInfo.tsx
> +          <Text>{Math.ceil(count / workloads)}%</Text>
not really, this block is executed only when the workloads is greater than MAX_LICENSES

2023-12-07 01:18 UTC, sahithikolichala commented on src/modules/27-platform/auth-settings/pages/subscriptions/overview/CDUsageInfo.tsx
> +            computedCount={Math.ceil((usage?.cd?.serviceLicenses?.count || 0) / 3)}
ya, i can refactor this as follow up

2023-12-07 03:42 UTC, abhinavrastogi-harness approved these changes

2023-12-07 18:25 UTC, cjlee01 approved these changes

2023-12-07 22:54 UTC, merged