Chore/cds 85888 step panel yaml builder
harness/harness-core-ui pull request #19317
Opened 2023-12-07 08:24 UTC by PratyushGar

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-20 11:15 UTC, rameshx requested changes

2023-12-20 11:15 UTC, rameshx commented on src/modules/70-pipeline/y1/components/StepPanel/StepPanel.module.scss
> +div.zeroMargin {
Can we remove the div tag?

2023-12-20 11:15 UTC, rameshx commented on src/modules/70-pipeline/y1/components/StepPanel/StepPanel.module.scss
> +  padding: var(--spacing-5) var(--spacing-xlarge) var(--spacing-5) var(--spacing-xlarge) !important;
```suggestion
  padding: var(--spacing-5) var(--spacing-xlarge);
```

2023-12-20 11:15 UTC, rameshx commented on src/modules/70-pipeline/y1/components/StepPanel/StepRenderer.tsx
> +                  <InputComponentRenderer
I think this needs `key`

2023-12-20 11:15 UTC, rameshx commented on src/modules/70-pipeline/y1/components/StepPanel/StepRenderer.tsx
> +                  path={input.path}
Add `key`

2023-12-20 11:15 UTC, rameshx commented on src/modules/70-pipeline/y1/components/StepPanel/StepRenderer.tsx
> +                  allowableTypes={[MultiTypeInputType.FIXED, MultiTypeInputType.RUNTIME, MultiTypeInputType.EXPRESSION]} // TODO:: fetch from context or prop
```suggestion
                  allowableTypes={[MultiTypeInputType.FIXED, MultiTypeInputType.RUNTIMEV1, MultiTypeInputType.EXPRESSION]} // TODO:: fetch from context or prop
```

2023-12-20 11:15 UTC, rameshx commented on src/modules/70-pipeline/y1/components/StepPanel/StepRenderer.tsx
> +                allowableTypes={[MultiTypeInputType.FIXED, MultiTypeInputType.RUNTIME, MultiTypeInputType.EXPRESSION]} // TODO:: fetch from context or prop
```suggestion
                allowableTypes={[MultiTypeInputType.FIXED, MultiTypeInputType.RUNTIMEV1, MultiTypeInputType.EXPRESSION]} // TODO:: fetch from context or prop
```

2023-12-20 11:15 UTC, rameshx commented on src/modules/70-pipeline/y1/components/StepPanel/types.ts
> +  UseStepTemplate = 'Use_Step_Template',
The values can be in pascal case instead of pascal and snake case
```suggestion
  AddStep = 'AddStep',
  AddStepGroup = 'AddStepGroup',
  UseStepTemplate = 'UseStepTemplate',
```

2023-12-20 11:15 UTC, rameshx commented on src/modules/70-pipeline/y1/components/StepPanel/types.ts
> +  GithubActions = 'action'
or camelCase if these cannot be changed

2023-12-20 11:15 UTC, rameshx commented on src/modules/70-pipeline/y1/components/utils.ts
> +export const getLastStageIndexInPath = (dotNotationPath: string[]): number => {
If this receives an array of strings, we can rename the param to `path`, as it will become a dot notation after joining with `.`.

2023-12-20 11:15 UTC, rameshx commented on src/modules/70-pipeline/y1/components/utils.ts
> +  dotNotationPath: string[],
Can be renamed to `path` as there are no `.`s at this point.

2023-12-20 11:40 UTC, rameshx commented
<img width="264" alt="image" src="https://github.com/harness/harness-core-ui/assets/52284933/a13c3d4a-fed5-4e93-9cac-1ac4e69949d7">

left and right padding are different

2023-12-26 12:29 UTC, PratyushGar commented on src/modules/70-pipeline/y1/components/StepPanel/types.ts
> +  GithubActions = 'action'
Yes, sure. Actually, this was the exact key that CI plugins use to categorize, since it is kept on hold now, will update it needed back once the contracts are finalised for them

2023-12-27 07:35 UTC, PratyushGar commented
> left and right padding look inconsistent
> 
> <img alt="image" width="264" src="https://private-user-images.githubusercontent.com/52284933/291879855-a13c3d4a-fed5-4e93-9cac-1ac4e69949d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjI4MTYsIm5iZiI6MTcwMzY2MjUxNiwicGF0aCI6Ii81MjI4NDkzMy8yOTE4Nzk4NTUtYTEzYzNkNGEtZmVkNS00ZTkzLTljYWMtMWFjNGU2OTk0OWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA3MzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyOTkyZDVjNTJmNDVlNDAyZWQ0MzQ2NmUyYzNmMmRmNWZmMmIxMzE1YmIwMzFkZjJmY2NmMjczNTBmODllNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TK1U-fRZiMuKVb-Nl8c5TKxC0cNKyptBMNMS0PChH6M">
> loading spinner UI is overflowing
> 
>  Screen.Recording.2023-12-21.at.9.58.52.AM.mov 
> right borders are stripped for some fields and update, cancel buttons need bottom spacing
> 
> <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/52284933/292088658-c28ebd41-f115-4fd2-bab7-c8e2ae86b573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjI4MTYsIm5iZiI6MTcwMzY2MjUxNiwicGF0aCI6Ii81MjI4NDkzMy8yOTIwODg2NTgtYzI4ZWJkNDEtZjExNS00ZmQyLWJhYjctYzhlMmFlODZiNTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA3MzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NzUyMjAwNmE2OTc5ODcwZTk2N2MxNTc2MjllYjkxMTRmYmIyNjNiNDg0YmU0MmQ2YTcwOWRlZGFjOWI5ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2M7HvVC2p5PvmngdMPaehUlD67mzamJbzKADfUKp-jU">

Thanks, addressed them in the latest commit

2023-12-28 10:23 UTC, litvinovstas commented on src/modules/70-pipeline/components/PipelineStudio/PipelineSchema/JsonSchemaExtractor.tsx
> +        // let oneOfObjectWithInternalType: JsonNode | undefined
remove comment

2024-01-03 05:54 UTC, rameshx approved these changes

2024-01-04 11:46 UTC, srdjan-harness approved these changes

2024-01-04 12:15 UTC, merged