fix: [PL-42879]: show org when create  project inside org
harness/harness-core-ui pull request #19336
Opened 2023-12-08 08:11 UTC by namanharness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-08 09:38 UTC, chetanvekariya-harness requested changes
Let's write test case for this.

2023-12-08 11:18 UTC, chetanvekariya-harness requested changes

2023-12-08 11:18 UTC, chetanvekariya-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/__tests__/ProjectForm.test.tsx
> +      <TestWrapper path="/account/:accountId" pathParams={{ accountId: 'testAcc' }}>
If you are creating project inside org them url should be for organization here. The use cases that you need to write tests for are -

1. If org from param is getting selected if it is present in url and field should be disabled
2. If orgId is not present in url then it should select default org and field should be enabled.

None is getting covered here. Rather than writing test case for your logic, you are writing your logic again in test case.
Your changes can be covered in test case if you write test cases for CreateProject component which is where you made changes.
In general, change can be covered using test cases only if you write test case for component you made change in or any component which is parent in that tree. Writing test cases for any children component will never cover your change.

2023-12-08 12:20 UTC, namanharness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/__tests__/ProjectForm.test.tsx
> +      <TestWrapper path="/account/:accountId" pathParams={{ accountId: 'testAcc' }}>
You are right with the points mentioned, i will update the PR with test for CreateProject covering the mentioned scenarios.

2023-12-14 04:44 UTC, chetanvekariya-harness approved these changes

2023-12-14 04:44 UTC, chetanvekariya-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/__tests__/CreateProject.test.tsx
> +  beforeEach(jest.clearAllMocks)
nit: This might not be needed

2023-12-14 04:44 UTC, chetanvekariya-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/__tests__/CreateProject.test.tsx
> +  test('Assert Org Field is disabled when project is created from Org', async () => {
title: "org field should be disabled when project is created from org scope"

2023-12-14 04:44 UTC, chetanvekariya-harness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/__tests__/CreateProject.test.tsx
> +  test('Assert Org Field is not disabled when project is created from Account', async () => {
nit: similar to above

2023-12-14 09:13 UTC, rameshx requested changes

2023-12-14 09:26 UTC, namanharness commented on src/modules/45-projects-orgs/modals/ProjectModal/views/CreateProject.tsx
> +        disableSelect={!!orgIdPathParam || false}
right , updated, please review

2023-12-14 09:29 UTC, rameshx approved these changes

2023-12-14 09:31 UTC, chetanvekariya-harness submitted a review, later dismissed

2023-12-14 12:12 UTC, mayankVermaHarness approved these changes

2023-12-14 13:14 UTC, rameshx approved these changes

2023-12-14 13:26 UTC, merged