feat: [CI-10684]: CI gitness integration with new UX
harness/harness-core-ui pull request #19348
Opened 2023-12-10 14:39 UTC by karansaraswat19

### Summary

#### Screenshots

![Screenshot 2023-12-10 at 8 00 53 PM (2)](https://github.com/harness/harness-core-ui/assets/110607964/4c143996-317c-4fbc-83c2-e07c2312c5d9)
![Screenshot 2023-12-10 at 8 01 07 PM (2)](https://github.com/harness/harness-core-ui/assets/110607964/43eb70f2-5df4-43e4-b9f4-2782f920d296)
![Screenshot 2023-12-10 at 8 01 16 PM (2)](https://github.com/harness/harness-core-ui/assets/110607964/6c3f594a-d804-416e-86f2-f3339488ef9b)

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-11 07:00 UTC, karansaraswat19 commented
retrigger jest

2023-12-13 20:30 UTC, vardanbansal-harness submitted a review, later dismissed

2023-12-14 07:52 UTC, ishantmehtaharness commented on src/modules/10-common/components/GitProviderSelect/__tests__/GitProviderSelect.test.tsx
> +    expect(container).toMatchSnapshot()
We should avoid snapshot testing as much as possible
cc: @chetanvekariya-harness

2023-12-14 07:53 UTC, ishantmehtaharness commented on src/modules/70-pipeline/components/PipelineStudio/CloneCodebaseForm/__tests__/CloneCodebaseForm.test.tsx
> +    expect(container).toMatchSnapshot()
https://github.com/harness/harness-core-ui/pull/19348/files#r1426358467

2023-12-14 10:15 UTC, shaurya-harness approved these changes

2023-12-14 10:40 UTC, chetanvekariya-harness requested changes
You can avoid writing test cases and add proper test cases later, if these changes are urgently required. Let's not add new snapshots.

2023-12-14 10:42 UTC, chetanvekariya-harness commented on src/modules/10-common/components/GitProviderSelect/__tests__/GitProviderSelect.test.tsx
> +    expect(container).toMatchSnapshot()
Thanks, @ishantmehtaharness . That is correct.

2023-12-14 10:50 UTC, chetanvekariya-harness commented on src/modules/10-common/components/GitProviderSelect/__tests__/GitProviderSelect.test.tsx
> +    expect(container).toMatchSnapshot()
@karansaraswat19 - Remove `expect(container).toMatchSnapshot()`

2023-12-14 10:52 UTC, karansaraswat19 commented
@chetanvekariya-harness @ishantmehtaharness will remove the snapshots in a follow-up PR

2023-12-14 10:53 UTC, ishantmehtaharness approved these changes
If this is urgent, then lets merge. Else we should add proper jest tests, rather than snapshots

2023-12-14 10:53 UTC, ishantmehtaharness commented
Coverage, Eslint failing

2023-12-14 10:54 UTC, chetanvekariya-harness approved these changes
As discussed, with @karansaraswat19 , he will be removing snapshots in the next PR which will be raised immediately after this one. So, approving just because I had blocked this PR because of that. Meaningful, reviews to be taken from CI team.

2023-12-14 16:31 UTC, merged