feat: [FFM-10037]: Adding generic error if percentage rollout fails
harness/harness-core-ui pull request #19414
Opened 2023-12-13 16:17 UTC by laura-mannus

### Summary
Previously if the API failed  to patch it said "Unable to serve object"

#### Screenshots

<img width="997" alt="Add Flag to Target Group" src="https://github.com/harness/harness-core-ui/assets/103498167/1937fbb3-3f06-4713-8b91-ec322a8be369">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-13 17:06 UTC, knagurski requested changes

2023-12-13 17:06 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/FlagSettingsPanel/FlagSettingsPanel.tsx
> +        showError(getString('cf.segmentDetail.addFlagToTargetGroupError'))
I don't think we want to do this. It bypasses the error handling for git and governance errors. A failure here might not be due to a problem with the shape of things, it could be that a policy has been violated or there a git merge conflict.

2023-12-13 17:06 UTC, Kira-Jennings approved these changes

2023-12-13 17:09 UTC, Kira-Jennings commented on src/modules/75-cf/pages/target-group-detail/components/FlagSettingsPanel/FlagSettingsPanel.tsx
> +        showError(getString('cf.segmentDetail.addFlagToTargetGroupError'))
Should we show the caught `error` by default and if none exists show the generic?

2023-12-13 17:14 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/FlagSettingsPanel/FlagSettingsPanel.tsx
> +        showError(getString('cf.segmentDetail.addFlagToTargetGroupError'))
I think the best solution might be to update the validation to prevent submission of negative values rather than try to manipulate the error.

2023-12-14 09:48 UTC, Kira-Jennings commented on src/modules/75-cf/pages/target-group-detail/components/FlagSettingsPanel/FlagSettingsPanel.tsx
> +        showError(getString('cf.segmentDetail.addFlagToTargetGroupError'))
In this case maybe the back end should update the message being sent, instead of UI trying to manipulate the error text. UI validation would be a good extra layer on top to prevent submission but in case it somehow does get submitted then the error message should be more informative

2023-12-14 10:33 UTC, laura-mannus commented on src/modules/75-cf/pages/target-group-detail/components/FlagSettingsPanel/FlagSettingsPanel.tsx
> +        showError(getString('cf.segmentDetail.addFlagToTargetGroupError'))
Thank you both, appreciate the review, going to close this and re-evaluate 👍

2023-12-14 10:33 UTC, closed without merging