feat: [CDS-86951]:manfiest-values-files-expression
harness/harness-core-ui pull request #19462
Opened 2023-12-15 09:51 UTC by litvinovstas

### Summary
1.Provided expression supporting for values yaml and files for manifests

#### Screenshots
![Uploading Screenshot 2023-12-15 at 11.51.03.png…]()

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-18 14:10 UTC, rameshx requested changes

2023-12-18 14:10 UTC, rameshx commented on src/modules/70-pipeline/components/ManifestSelection/DragnDropPaths.tsx
> +  isExpressionEnable?: boolean
expression type should be rendered based on `allowableTypes`. If expression type is not supported in some cases then exclude expression type in `allowableTypes`

2023-12-18 14:10 UTC, rameshx commented on src/modules/70-pipeline/components/ManifestSelection/DragnDropPaths.tsx
> +                    ) as AllowedTypes)
We don't need these conditions if `allowableTypes` already excludes/includes expression type.

2023-12-18 14:10 UTC, rameshx commented on src/modules/70-pipeline/components/ManifestSelection/ManifestListView/__tests__/ManifestListViewMultiple.test.tsx
> +    expect(container).toBeDefined()
I think `container` will always be defined. We can check something that happens after clicking `functionDefinitionManifestEditButton`.

2023-12-18 14:10 UTC, rameshx commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/CommonManifestDetails/ManifestDetailsCoreSection.tsx
> +          isExpressionEnable={isGitTypeManifestStore(defaultTo(get(prevStepData, 'store'), ''))}
This condition can be used to filter `allowableTypes` as required.

2023-12-18 14:10 UTC, rameshx commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/MultiTypeListOrFileSelectList.tsx
> +  isExpressionEnable?: boolean
Same as above. A new prop for conditionally allowing expressions is not required when it supports `allowableTypes`.

2023-12-18 14:38 UTC, litvinovstas commented on src/modules/70-pipeline/components/ManifestSelection/DragnDropPaths.tsx
> +                    ) as AllowedTypes)
This condition is using for all manifest types, with prop chaining. initially not had supporting for expression values, now is enabling only for some specific scenarios for k8s/helm manifests, for other deployment types it will be provided step by step.
for excluding some regression scenarios provide isExpressionEnable property only for specific cases. other scenarios still continue working as expected, in future this property and condition will be removed, when supporting for expression will be provided for all manifests cases.

2023-12-18 15:09 UTC, litvinovstas commented on src/modules/70-pipeline/components/ManifestSelection/ManifestListView/__tests__/ManifestListViewMultiple.test.tsx
> +    expect(container).toBeDefined()
improved

2023-12-19 04:24 UTC, rameshx approved these changes

2023-12-19 06:35 UTC, Eric761 approved these changes

2023-12-19 06:36 UTC, merged