fix: [CDS-87146]: Code module old nav to new nav redirects
harness/harness-core-ui pull request #19519
Opened 2023-12-19 13:11 UTC by avinashmadhwani02

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-21 12:41 UTC, avinashmadhwani02 commented
trigger messagecheck

2023-12-22 07:08 UTC, MondalSayantan approved these changes

2023-12-28 17:01 UTC, abhinavrastogi-harness approved these changes

2023-12-28 20:45 UTC, tan-nhu commented
I tested with a couple of URLs, they are not redirected correctly.

OLD: https://localhost:8181/ng/account/_OKE5H2PQKOUfzFFDuD4FA/code/default/CODE
REDIRECT TO: https://localhost:8181/ng/account/_OKE5H2PQKOUfzFFDuD4FA/module/code/orgs/default/settings
SHOULD BE: https://localhost:8181/ng/account/_OKE5H2PQKOUfzFFDuD4FA/module/code/orgs/default/projects/CODE

OLD: https://localhost:8181/ng/account/_OKE5H2PQKOUfzFFDuD4FA/code/default/CODE/gitness
REDIRECT TO: https://localhost:8181/ng/account/_OKE5H2PQKOUfzFFDuD4FA/module/code/orgs/default/projects/CODEgitness/repos
SHOULD BE: https://localhost:8181/ng/account/_OKE5H2PQKOUfzFFDuD4FA/module/code/orgs/default/projects/CODE/repos/gitness

OLD: https://localhost:8181/ng/account/_OKE5H2PQKOUfzFFDuD4FA/code/default/CODE/gitness/files/main/~/.githooks/pre-commit
REDIRECT TO: https://localhost:8181/ng/account/_OKE5H2PQKOUfzFFDuD4FA/module/code/orgs/default/projects/CODEgitness/files/main/~/.githooks/pre-commit
SHOULD BE: https://localhost:8181/ng/account/_OKE5H2PQKOUfzFFDuD4FA/module/code/orgs/default/projects/CODE/repos/gitness/files/main/~/.githooks/pre-commit

Etc...

2023-12-28 20:46 UTC, tan-nhu requested changes
Tested with a bunch of old URLs, none worked with the redirect.

2024-01-05 20:41 UTC, tan-nhu commented on src/modules/RouteDestinationsV2.tsx
> +  const path = !_path ? 'repos' : _path !== 'search' ? `repos/${_path}` : _path
This constructs correct CODE URLs for V2.

2024-01-05 20:41 UTC, tan-nhu approved these changes

2024-01-05 22:44 UTC, hitesharinga approved these changes

2024-01-05 22:54 UTC, merged

2024-01-05 23:01 UTC, cjlee01 commented
Lgtm tested some of the cases as well