feat: [CDS-86801]: support S3 manifest store in serverlessAwsLambda service defination
harness/harness-core-ui pull request #19548
Opened 2023-12-20 11:36 UTC by shivanand-harness

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-21 05:23 UTC, shivanand-harness commented
retrigger standards

2023-12-21 21:43 UTC, rameshx commented on src/modules/70-pipeline/components/ManifestSelection/ManifestListView/ManifestListView.tsx
> +              configOverridePath: [ManifestDataType.ServerlessAwsLambda].includes(selectedManifest as ManifestTypes)
Is this additional `includes` check required? It only reaches here if the case at 460 with the `includes` check satisfies.

2023-12-21 21:46 UTC, rameshx submitted a review, later dismissed

2023-12-22 05:55 UTC, pankajsingh-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/ServerlessLambdaWithS3/ServerlessLambdaWithS3.tsx
> +                {get(enableFields, 'region', true) && (
Do we need to show this field even if region is not in enabled field as passing default value as true.

2023-12-22 06:03 UTC, chetanvekariya-harness reviewed
Please write jest test cases.

2023-12-22 06:03 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/ServerlessLambdaWithS3/ServerlessLambdaWithS3.tsx
> +                {get(enableFields, 'region', true) && (
Looks like `region`, `bucketName` are not passed from anywhere this component is used. Do we need this condition for these fields?

2023-12-22 06:04 UTC, chetanvekariya-harness requested changes
Please write test cases.

2023-12-22 06:19 UTC, shivanand-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/ServerlessLambdaWithS3/ServerlessLambdaWithS3.tsx
> +                {get(enableFields, 'region', true) && (
enableFields prop is optional, if want to show/hide based on condition then we can use enableFields, else all fields will be shown

2023-12-22 06:19 UTC, shivanand-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/ServerlessLambdaWithS3/ServerlessLambdaWithS3.tsx
> +                {get(enableFields, 'region', true) && (
enableFields prop is optional, if want to show/hide based on condition then we can use enableFields, else all fields will be shown

2023-12-22 07:53 UTC, ishantmehtaharness commented
PR has conflicts

2023-12-22 15:44 UTC, chetanvekariya-harness requested changes

2023-12-22 15:44 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestListView/ManifestListView.tsx
> +      case [ManifestDataType.ServerlessAwsLambda, ManifestDataType.Values].includes(
This change is not covered using test cases.

2023-12-22 15:44 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/ValuesYamlManifestSource/ValuesYamlManifestSource.tsx
> +    const manifestStoreType = get(props.template, `${props.manifestPath}.spec.store.type`, null)
This change is not covered in test case.

2023-12-26 15:54 UTC, ishantmehtaharness approved these changes
looks good to me

2023-12-27 05:06 UTC, shivanand-harness commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/ValuesYamlManifestSource/ValuesYamlManifestSource.tsx
> +    const manifestStoreType = get(props.template, `${props.manifestPath}.spec.store.type`, null)
covered tests

2023-12-27 05:06 UTC, shivanand-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestListView/ManifestListView.tsx
> +      case [ManifestDataType.ServerlessAwsLambda, ManifestDataType.Values].includes(
covered

2023-12-27 05:13 UTC, vikrant-harness approved these changes

2023-12-27 05:18 UTC, namanharness approved these changes

2023-12-27 05:20 UTC, merged