feat: [CDS-86868] search and pagination for infra definitions
harness/harness-core-ui pull request #19583
Opened 2023-12-26 10:13 UTC by kanikamittal09

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-27 15:13 UTC, kanikamittal09 commented
trigger messagecheck

2023-12-28 12:10 UTC, ishantmehtaharness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureDefinition.tsx
> +                    setSearchTerm(text.trim())
Can text be null or undefined here? In that case we should add null check

2023-12-28 12:10 UTC, ishantmehtaharness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureDefinition.tsx
> +                    setSearchTerm(text.trim())
else `.trim()` will fail

2023-12-28 12:10 UTC, ishantmehtaharness submitted a review, later dismissed
looks good, with `.trim()` check, please check that

2024-01-03 07:02 UTC, pankajsingh-harness requested changes

2024-01-03 07:02 UTC, pankajsingh-harness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureDefinition.tsx
> -const DEFAULT_PAGE_SIZE_FOR_INFRASTRUCTURES = 1000
Do not make these changes. Keep this. This has been done to load more templates.

2024-01-03 07:15 UTC, pankajsingh-harness approved these changes

2024-01-03 09:40 UTC, kanikamittal09 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureDefinition.tsx
> -const DEFAULT_PAGE_SIZE_FOR_INFRASTRUCTURES = 1000
discussed offline , changes only related to infra listing page

2024-01-03 10:07 UTC, kanikamittal09 commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureDefinition.tsx
> +                    setSearchTerm(text.trim())
changed it to `text?.trim()`

2024-01-04 06:18 UTC, ishantmehtaharness approved these changes
Looks good

2024-01-04 13:08 UTC, pankajsingh-harness approved these changes

2024-01-04 13:43 UTC, merged