chore: [PL-43844]: implement no-external-snapshot custom eslint rule to prevent new external snapshot addition
harness/harness-core-ui pull request #19627
Opened 2024-01-03 07:29 UTC by chetanvekariya-harness

### Summary
- We have pre-commit hook that prevents internal and new external snapshot addition. But. it can be bypassed by force-commit
- Implemented new eslint rule that does not allow new addition of external snapshots

**Note**: Adding new internal snapshot of more than 25 lines is already prevented by in-build eslint rule jest/no-large-snapshots

#### Screenshots

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2024-01-03 10:17 UTC, Eric761 submitted a review, later dismissed

2024-01-03 10:27 UTC, shivanand-harness approved these changes

2024-01-03 10:50 UTC, PratyushGar approved these changes

2024-01-03 17:41 UTC, abhinavrastogi-harness requested changes
why do we need this change?
we can also just make `maxSize: 0`..that should prevent addition of snapshots directly.. and also prevent updates to existing snapshots (which will push for migration to assertions)

2024-01-03 17:41 UTC, abhinavrastogi-harness commented on scripts/eslint-rules/no-external-snapshot.js
> +const MAX_EXTERNAL_SNAPSHOT_COUNT = 3381 // These many times toMatchSnapshot is used as of Jan 3, 2024
hardcoding the max count will only for a week.. when someone removes one snapshot, this script will allow addition of one more snapshot again

2024-01-04 02:18 UTC, chetanvekariya-harness commented
> why do we need this change? we can also just make `maxSize: 0`..that should prevent addition of snapshots directly.. and also prevent updates to existing snapshots (which will push for migration to assertions)

That property (maxSize) does not work in the inbuilt rule. That is the reason we could not prevent external snapshots through lint rule earlier and had to write pre-commit hook instead.

2024-01-04 02:22 UTC, chetanvekariya-harness commented on scripts/eslint-rules/no-external-snapshot.js
> +const MAX_EXTERNAL_SNAPSHOT_COUNT = 3381 // These many times toMatchSnapshot is used as of Jan 3, 2024
Thanks for pointing this out. In that case, I should write something that checks quality like we discussed once. May be, no of snapshots / no of test cases or something similar.

2024-01-09 05:32 UTC, chetanvekariya-harness commented
Closing this until I have proper solution.

2024-01-09 05:32 UTC, closed without merging