feat: [CDS-88350]:OciHelm-new-aws-connector
harness/harness-core-ui pull request #19801
Opened 2024-01-12 09:46 UTC by litvinovstas

### Summary
1.Fixed issue with creating new aws connector from OciHelm Manifest (ECR type)
Added handling for identify two config types in OciHelm store.

Test cases.
1.Created OciHelm store, provider ECR type, create new aws connector , and saved.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2024-01-12 11:23 UTC, litvinovstas commented
trigger messagecheck

2024-01-15 07:16 UTC, Eric761 approved these changes

2024-01-15 07:25 UTC, shivanand-harness commented
Please add screenshots or working demo of the feature from your local

2024-01-15 07:35 UTC, shivanand-harness requested changes

2024-01-15 07:35 UTC, shivanand-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestListView/ManifestListViewMultiple.tsx
> +  const handleSetEcr = (status: boolean): void => {
`handleSetEcr` is same as `setIsEcr`

can we remove `handleSetEcr` and use `setIsEcr` directly

2024-01-15 07:35 UTC, shivanand-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/HelmWithOCI/HelmWithOCI.tsx
> +                  connectorRef: defaultTo(get(modifiedPrevStepData, 'identifier'), formData?.connectorRef),
which is on high priority? `get(modifiedPrevStepData, 'identifier')` or `formData?.connectorRef`

because in prev code `formData?.connectorRef` is on high priority and now we changed to `get(modifiedPrevStepData, 'identifier')`

2024-01-15 07:35 UTC, shivanand-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/HelmWithOCI/HelmWithOCI.tsx
> +                  connectorRef: defaultTo(get(modifiedPrevStepData, 'identifier'), formData?.connectorRef),
Please add test cases for this change

2024-01-15 07:35 UTC, shivanand-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/HelmWithOCI/HelmWithOCI.tsx
> +                    setIsEcr(true)
why always set to true if user clicks on back button?

2024-01-15 07:35 UTC, shivanand-harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/ManifestStore.tsx
> +                            const isEcr = configType === OciHelmTypes.Ecr
please confirm the position of this check? should it be after line 234?

2024-01-15 07:52 UTC, litvinovstas commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/HelmWithOCI/HelmWithOCI.tsx
> +                  connectorRef: defaultTo(get(modifiedPrevStepData, 'identifier'), formData?.connectorRef),
identifier has more priority, when created new connector via manifest wizard.

2024-01-15 08:09 UTC, shivanand-harness approved these changes

2024-01-15 08:11 UTC, Eric761 approved these changes

2024-01-15 08:17 UTC, merged