feat: [CI-3426]: STO Step UI
harness/harness-core-ui pull request #6661
Opened 2021-12-30 20:31 UTC by chris-harness

##### Summary:

Adds a new Pipeline Step, patterned after the PluginStep, with some form field changes and defaulting.

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-01-19 07:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6661) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6661) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=6661) it.</sub>

2022-02-03 20:39 UTC, r0610205 commented
retrigger titlecheck

2022-02-03 20:49 UTC, r0610205 commented
retrigger titlecheck

2022-02-03 20:51 UTC, r0610205 commented
retrigger titlecheck

2022-02-18 03:03 UTC, chris-harness commented
retrigger jest

2022-02-18 03:03 UTC, chris-harness commented
retrigger coverage

2022-02-23 02:28 UTC, williamwissemann commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.stories.tsx
> +      identifier: 'ZeroNorth',
Should this be hardcoded to ZeroNorth?

2022-02-24 00:23 UTC, r0610205 submitted a review, later dismissed

2022-02-24 16:09 UTC, chris-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.stories.tsx
> +      identifier: 'ZeroNorth',
Fixed

2022-02-24 23:42 UTC, chris-harness commented
trigger cypress

2022-02-24 23:42 UTC, chris-harness commented
retrigger coverage

2022-02-24 23:42 UTC, chris-harness commented
retrigger jest

2022-02-25 15:53 UTC, chris-harness commented
retrigger jest

2022-02-25 18:06 UTC, tan-nhu submitted a review, later dismissed

2022-02-25 18:06 UTC, tan-nhu commented on scripts/strings/yamlStringsCheck.mjs
> +    console.log(ref)
Remove console.log

2022-02-25 18:06 UTC, tan-nhu commented on src/modules/70-pipeline/components/PipelineStudio/StepPalette/StepPalette.tsx
> +                  name: 'Security Scan',
Should use `useString` to get the text

2022-02-25 19:20 UTC, chris-harness commented on src/modules/70-pipeline/components/PipelineStudio/StepPalette/StepPalette.tsx
> +                  name: 'Security Scan',
This is just a temporary work-around for local dev, and will be removed soon

2022-02-25 19:20 UTC, chris-harness commented on scripts/strings/yamlStringsCheck.mjs
> +    console.log(ref)
Done

2022-02-25 19:24 UTC, tan-nhu submitted a review, later dismissed

2022-02-25 19:47 UTC, atmollo-harness submitted a review, later dismissed

2022-02-25 20:16 UTC, anjanBalgovind submitted a review, later dismissed

2022-02-25 20:35 UTC, vardanbansal-harness submitted a review, later dismissed

2022-02-28 04:30 UTC, reetika04 commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.stories.tsx
> +    <div style={{ display: 'grid', gridTemplateColumns: '480px 1fr', columnGap: '20px' }}>
Please

2022-03-01 06:43 UTC, abhinavrastogi-harness requested changes

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on package.json
> +    "generate-eslint": "node scripts/generate-eslint-config-for-imports.mjs",
is this coming from a bad rebase? i think this was already added in master in a different PR?

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on scripts/strings/yamlStringsCheck.mjs
> +      .map(mod => `${mod}.`)
what does this do?

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/10-common/.eslintrc.yml
> +        - modules/85-sto-steps/*
i'd prefer to see all product modules at layer 75.
CV is incorrectly placed at 85 today

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/components/PipelineStudio/StepPalette/StepPalette.tsx
> +        if (localStorage.STO_PIPELINE_SECURITY_ENABLED) {
can we use a feature flag instead of a localstorage flag?
considering that our codebase is public now, customers (or other agents) can enable such incomplete features via LS easily.

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/components/PipelineStudio/StepPalette/StepPalette.tsx
> +          if (stepCat.name === 'Continuous Integration') {
avoid string comparisons for such usecases. enums should be preferered.

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/components/PipelineStudio/StepPalette/StepPalette.tsx
> +          if (stepCat.name === 'Continuous Integration') {
also, switch case is more readable for such cases

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/components/PipelineStudio/StepUtil.ts
> +// eslint-disable-next-line no-restricted-imports
disabling restricted imports check is a bad practice. it will cause issues in the future when we want to split the modules as microfrontends.
it also causes issues with the current bundling as the dependency tree is not acyclic anymore.

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionTabs/ExecutionTabs.tsx
> +          to={routes.toExecutionSecurityView(params) + location.search}
why are we adding search param to the route?

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.tsx
> +  protected stepName = 'Configure Security Scan Step'
string framework should be used

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.tsx
> +  protected stepIconColor = '#4F5162'
can we use a harness standard color?

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.tsx
> +      connectorRef: 'account.harnessImage',
why is a connector reference hardcoded? will all accounts have this connector by default?

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.tsx
> +    if (stepViewType === StepViewType.InputSet || stepViewType === StepViewType.DeploymentForm) {
can we use a switch-case instead of if-else? it's far more readable and sonar friendly.

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStepBase.tsx
> +import get from 'lodash/get'
use `lodash-es` instead

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStepBase.tsx
> +import get from 'lodash/get'
our eslint rules should have caught this ideally. 🤔

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/__test__/ZeroNorthStep.test.tsx
> +      expect(container).toMatchSnapshot()
can we use assertions instead of snapshots? they are more reliable.

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/__test__/ZeroNorthStep.test.tsx
> +      expect(container).toMatchSnapshot()
same

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/__test__/ZeroNorthStep.test.tsx
> +      expect(container).toMatchSnapshot()
same

2022-03-01 06:43 UTC, abhinavrastogi-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/__test__/ZeroNorthStep.test.tsx
> +          customStepProps={{
it's usually a good practice to keep mock JSON objects in a separate json file in the `__test__` folder. it makes maintenance easier on the test file itself.

2022-03-01 13:44 UTC, chris-harness commented on scripts/strings/yamlStringsCheck.mjs
> +      .map(mod => `${mod}.`)
The script was erroneously complaining about string keys that started with `sto`, like `store`, so this explicitly puts a dot after the module name to avoid that bug.

2022-03-01 13:46 UTC, chris-harness commented on package.json
> +    "generate-eslint": "node scripts/generate-eslint-config-for-imports.mjs",
No, there still is no yarn script for this yet in `master`.

2022-03-01 13:47 UTC, chris-harness commented on src/modules/10-common/.eslintrc.yml
> +        - modules/85-sto-steps/*
We need to import some things from `75-ci`, so it needs to be a higher number

2022-03-01 13:49 UTC, chris-harness commented on src/modules/70-pipeline/components/PipelineStudio/StepPalette/StepPalette.tsx
> +        if (localStorage.STO_PIPELINE_SECURITY_ENABLED) {
This can probably be removed at this point, as we've gotten the `harness-core` functionality in place to make this obsolete

2022-03-01 13:49 UTC, chris-harness commented on src/modules/70-pipeline/components/PipelineStudio/StepPalette/StepPalette.tsx
> +          if (stepCat.name === 'Continuous Integration') {
removing this code block

2022-03-01 13:50 UTC, chris-harness commented on src/modules/70-pipeline/components/PipelineStudio/StepUtil.ts
> +// eslint-disable-next-line no-restricted-imports
This is unavoidable from what I can tell, for the same reason that other modules do this here

2022-03-01 13:52 UTC, chris-harness commented on src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionTabs/ExecutionTabs.tsx
> +          to={routes.toExecutionSecurityView(params) + location.search}
This code block was an existing code block that was simply moved to reorder the tabs. @tan-nhu was the original author.

It seems like all of the execution tabs follow this same pattern.

2022-03-01 13:54 UTC, chris-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.tsx
> +      connectorRef: 'account.harnessImage',
Yes, this is a default connector that everyone has. Eventually this will be unnecessary, but that'll require more extensive `harness-core` work.

2022-03-01 13:58 UTC, chris-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.tsx
> +  protected stepName = 'Configure Security Scan Step'
This is code copied from elsewhere, and only minimally modified. I don't think we can use hooks in this context without rewriting the entire component.

Eventually this component will be deprecated and removed, once we have a clear path forward in our product planning, and the time to implement it.

2022-03-01 14:02 UTC, chris-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.tsx
> +  protected stepIconColor = '#4F5162'
Done

2022-03-01 14:06 UTC, chris-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/__test__/ZeroNorthStep.test.tsx
> +      expect(container).toMatchSnapshot()
Again copied from PluginStep. And, I thought there was recent communication that we should use snapshots as our main testing approach, or did I get that backwards?

2022-03-01 14:13 UTC, chris-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.tsx
> +    if (stepViewType === StepViewType.InputSet || stepViewType === StepViewType.DeploymentForm) {
Done

2022-03-01 14:15 UTC, chris-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStep.tsx
> +  protected stepName = 'Configure Security Scan Step'
Looking again at the code, the base class `PipelineStep` specifies this as a simple string, so we'd need to mess with the whole hierarchy to internationalize it.

2022-03-01 14:23 UTC, chris-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/ZeroNorthStepBase.tsx
> +import get from 'lodash/get'
Again copied from PluginStep. Easy fix though.

2022-03-01 14:30 UTC, chris-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/__test__/ZeroNorthStep.test.tsx
> +          customStepProps={{
ditto

2022-03-01 14:30 UTC, chris-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/__test__/ZeroNorthStep.test.tsx
> +      expect(container).toMatchSnapshot()
ditto

2022-03-01 14:30 UTC, chris-harness commented on src/modules/85-sto-steps/components/PipelineSteps/ZeroNorthStep/__test__/ZeroNorthStep.test.tsx
> +      expect(container).toMatchSnapshot()
ditto

2022-03-01 14:51 UTC, chris-harness commented
retrigger typecheck

2022-03-01 15:26 UTC, abhinavrastogi-harness approved these changes

2022-03-01 16:03 UTC, chris-harness commented
retrigger jest

2022-03-01 16:51 UTC, chris-harness commented
Cypress failure is a known issue unrelated to this PR: https://harness.slack.com/archives/C5WTKR3HU/p1646151301520759

Coverage is as good as I can get it, and matches the same testing coverage of the `PluginStep` it's based on.

2022-03-01 16:55 UTC, anjanBalgovind approved these changes

2022-03-01 17:16 UTC, vardanbansal-harness approved these changes

2022-03-01 17:17 UTC, tan-nhu approved these changes

2022-03-01 17:20 UTC, merged