feat: [CCM-5385]: Anomalies detection page UI designs
harness/harness-core-ui pull request #6897
Opened 2022-01-18 10:24 UTC by jyotiarora-harness

##### Summary:

Anomalies detection page UI design under CCM

**Note:** These changes are just the initial layout of the page and also added this nav behind the flag

##### Jira Links:

Feature: https://harness.atlassian.net/browse/CCM-5383
Task: https://harness.atlassian.net/browse/CCM-5385

##### Screenshots:

<img width="1722" alt="Screenshot 2022-01-18 at 3 52 38 PM" src="https://user-images.githubusercontent.com/97077953/149918922-41717a66-0969-4e1d-b507-df2352c2ee57.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-01-19 06:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6897) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6897) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=6897) it.</sub>

2022-01-20 05:06 UTC, jyotiarora-harness commented
retrigger jest

2022-02-03 10:02 UTC, jyotiarora-harness commented
retrigger jest

2022-02-03 11:06 UTC, jyotiarora-harness commented
retrigger coverage

2022-02-08 06:00 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        items={[
Will be replaced with the API data in the upcoming branches

2022-02-08 06:06 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +            label: 'All Cloud Providers',
Will be replaced with the API data in the upcoming branches, please ignore this change

2022-02-08 06:06 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +            102
Will be replaced with the API data in the upcoming branches, please ignore this change

2022-02-08 06:06 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +            $17586.99
Will be replaced with the API data in the upcoming branches, please ignore this change

2022-02-08 06:07 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +          filter: {
Will be replaced with the real time filters data in the upcoming branches, please ignore this change

2022-02-08 07:21 UTC, jyotiarora-harness commented on src/modules/85-cv/strings/strings.en.yaml
> -    status: STATUS
Removed this string as this was not used, please approve this change @harness/ui-cv

2022-02-08 07:22 UTC, jyotiarora-harness commented
retrigger jest

2022-02-08 09:23 UTC, jenil-harness submitted a review, later dismissed

2022-02-08 10:09 UTC, harshilbits submitted a review, later dismissed

2022-02-08 16:46 UTC, anjanBalgovind approved these changes

2022-02-09 05:42 UTC, jenil-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.module.scss
> +  margin-right: 16px;
use css var

2022-02-09 05:44 UTC, jenil-harness approved these changes

2022-02-09 05:52 UTC, anjanBalgovind submitted a review, later dismissed

2022-02-09 05:53 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.module.scss
> +  margin-right: 16px;
Will do in this change upcoming PR

2022-02-09 06:17 UTC, abhinavrastogi-harness requested changes
it seems your routing is not working correctly because the main nav item is not getting highlighted. please check

2022-02-09 06:29 UTC, jenil-harness commented
@abhinavrastogi-harness Changes for the side nav highlight went as a separate PR (It was a generic issue with all the ce routes). Those changes are in master branch.
@jyotiarora-harness Snapshot seems to be before rebasing with master branch, can you replace it with the updated one.

2022-02-09 06:36 UTC, abhinavrastogi-harness requested changes

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/components/CESideNav/CESideNav.tsx
> +  const showAnomalies = localStorage.getItem('showAnomalies')
why are we using local storage to toggle features? we should use feature flags instead

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.module.scss
> +  margin-right: 16px;
why not now?
also, please let the original commenters resolve converstations.

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      <TextInput
use `ExpandingSearchInput` component instead of building a custom search input

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        onChange={(e: any) => {
avoid using `any`

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      <Button
no click handlers?

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        <Container padding="medium" background={Color.GREY_100} border={{ color: Color.GREY_100, radius: 4 }}>
cant we use the existing `Card` components intead of making custom containers with custom css?

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +          {getString('ce.anomalyDetection.summary.perspectiveWise').toUpperCase()}
we have a general guidelines to avoid uppercase text anywhere in the UI. please confirm with UX team.

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +  const { accountId } = useParams<AnomalyParams>()
use existing `AccountPathProps` instead of custom `AnomalyParams` interface

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      const errMessage = error.data.message
use `getErrorInfoFromErrorObject` util

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      response && showSuccess('Thanks for your feedback!')
dont hardcode strings. use i18n framework

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +          onClick={(e: any) => {
we arent actually doing anything when user clicks on this menu item?

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +          onClick={(e: any) => {
also, what about RBAC integration?

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +const AnomaliesListGridView: React.FC<ListProps> = ({ listData }) => {
ideally we should have one component per file. can we move these out to separate files?

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        <Text color={Color.BLACK} font={{ weight: 'semi-bold', size: 'normal' }}>
use FontVariation instead of custom color and size

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        {trend ? <Text font={{ size: 'xsmall' }} color={Color.RED_600}>{`+${trend}%`}</Text> : null}
move strings to i18n files. even `+` and `%`

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +          <Link to={''}>{resourceName || 'squidward/spongebob/1233445...'}</Link>
what is this string? why is this being committed to master branch?

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        <Text font={{ size: 'normal' }} color={Color.ORANGE_700}>
use FontVariation where possible

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      columns={[
columns and data should be wrapped in `useMemo` according to `react-table` docs

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      sortable
avoid client-side sorting. either add support for server sorting or remove it.

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        // console.log('AnomaliesOverviewPage: Error in fetching the anomalies list', error)
what about actual error handling?

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/pages/anomalies-overview/__test__/AnomaliesOverviewPage.test.tsx
> +    expect(container).toMatchSnapshot()
avoid snapshots for entire pages. use assertions instead.
snapshots should only be used for leaf node components

2022-02-09 06:36 UTC, abhinavrastogi-harness commented on src/modules/75-ce/strings/strings.en.yaml
> +    costImpacted: TOTAL COST IMPACT
avoid uppercase text. please confirm with product/UX teams.

2022-02-09 12:13 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.module.scss
> +  margin-right: 16px;
Done the changes

2022-02-09 12:14 UTC, jyotiarora-harness commented on src/modules/75-ce/components/CESideNav/CESideNav.tsx
> +  const showAnomalies = localStorage.getItem('showAnomalies')
Replaced with feature flag

2022-02-09 12:14 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      <TextInput
Changed this with ExpandingSearchInput component

2022-02-09 12:15 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        onChange={(e: any) => {
Replaced this code with `ExpandingSearchInput` component, so no need for this change

2022-02-09 12:15 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      <Button
This is already handled in upcoming PR

2022-02-09 12:16 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        <Container padding="medium" background={Color.GREY_100} border={{ color: Color.GREY_100, radius: 4 }}>
Replaced this with existing card component

2022-02-09 12:18 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +          onClick={(e: any) => {
onClick functionality is not done yet as BE is not ready for this
RBAC integration is not there in whole CCM, it's planned as a whole different ticket

2022-02-09 12:18 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +const AnomaliesListGridView: React.FC<ListProps> = ({ listData }) => {
Done this segregation in upcoming PR already

2022-02-09 12:19 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      columns={[
Handled this change in upcoming PR

2022-02-09 12:21 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +  const { accountId } = useParams<AnomalyParams>()
Done these changes

2022-02-09 12:22 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      const errMessage = error.data.message
Handled with common util function

2022-02-09 12:22 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      response && showSuccess('Thanks for your feedback!')
Removed

2022-02-09 12:23 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        <Text color={Color.BLACK} font={{ weight: 'semi-bold', size: 'normal' }}>
Replaced with font variation

2022-02-09 12:23 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        {trend ? <Text font={{ size: 'xsmall' }} color={Color.RED_600}>{`+${trend}%`}</Text> : null}
This change already handled in upcoming PR
https://github.com/harness/harness-core-ui/pull/7226/files

2022-02-09 12:24 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +          <Link to={''}>{resourceName || 'squidward/spongebob/1233445...'}</Link>
Removed

2022-02-09 12:24 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +        <Text font={{ size: 'normal' }} color={Color.ORANGE_700}>
Done this handling with FontVariation

2022-02-09 12:25 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +      sortable
Removed this code for time being as this needs to be handled on BE side

2022-02-09 13:56 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/AnomaliesOverviewPage.tsx
> +          {getString('ce.anomalyDetection.summary.perspectiveWise').toUpperCase()}
Discussed with UX team and changed the same to normal case

2022-02-09 13:56 UTC, jyotiarora-harness commented on src/modules/75-ce/strings/strings.en.yaml
> +    costImpacted: TOTAL COST IMPACT
Discussed with UX team and changed this to normal casing

2022-02-09 13:57 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/anomalies-overview/__test__/AnomaliesOverviewPage.test.tsx
> +    expect(container).toMatchSnapshot()
Doing this change in upcoming PR (In progress)

2022-02-09 14:22 UTC, jyotiarora-harness commented
retrigger jest

2022-02-09 16:04 UTC, abhinavrastogi-harness approved these changes

2022-02-09 16:48 UTC, anjanBalgovind approved these changes

2022-02-09 16:51 UTC, merged