feat: [PL-22010]: enable user group copy for scim users
harness/harness-core-ui pull request #6901
Opened 2022-01-18 14:26 UTC by avinashmadhwani02

<img width="793" alt="Screenshot 2022-01-18 at 7 45 31 PM" src="https://user-images.githubusercontent.com/62028553/149955974-67f3da21-a6d1-46fd-abbc-5abca9f837a1.png">

2022-01-19 04:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6901) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6901) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=6901) it.</sub>

2022-01-19 12:58 UTC, abhinavrastogi-harness requested changes
I think the UX needs to be reviewed by design/product. It looks incomplete and non-standard right now.

2022-01-19 12:58 UTC, abhinavrastogi-harness commented on src/modules/18-audit-trail/components/FilterDrawer/AuditTrailFilterForm.tsx
> +  const organizations = data?.data?.content ? getOrgDropdownList(data?.data?.content) : []
null check for `data?.data?.content` can also be moved to the function itself

2022-01-19 12:58 UTC, abhinavrastogi-harness commented on src/modules/18-audit-trail/components/FilterDrawer/AuditTrailFilterForm.tsx
> +  const projects = projectData?.data?.content ? getProjectDropdownList(projectData?.data?.content) : []
same

2022-01-19 12:58 UTC, abhinavrastogi-harness commented on src/modules/20-rbac/pages/UserGroups/CopyGroupMenuItem/__tests__/__snapshots__/CopyGroupForm.test.tsx.snap
> +  <CopyGroupForm
what kind of a snapshot is this? 😅 
i dont think this is useful. please render the complete component, or even better, use assertions instead of snapshots.

2022-01-19 14:19 UTC, avinashmadhwani02 commented on src/modules/18-audit-trail/components/FilterDrawer/AuditTrailFilterForm.tsx
> +  const organizations = data?.data?.content ? getOrgDropdownList(data?.data?.content) : []
it expects a list, there is no point making its parameter optional.

we can probably do this - `getOrgDropdownList(data?.data?.content || []) `

2022-01-21 12:51 UTC, abhinavrastogi-harness approved these changes

2022-01-21 13:06 UTC, sunnykesh-harness approved these changes

2022-01-21 13:06 UTC, merged