feat: [FFM-1222]: Edit criteria modal
harness/harness-core-ui pull request #6916
Opened 2022-01-19 10:11 UTC by knagurski

This PR adds the _Edit Criteria_ modal which can be triggered from the _Criteria_ section of the new _Target Group_ detail page.

|Before|After|
|------|------|
|![Before]()|![After]()|

Refs [FFM-1222](https://harness.atlassian.net/browse/FFM-1222)

### Additions
- added `EditTargetGroupCriteriaDialog` component, styling and tests
- added `RuleRow` component, styling and tests
- added `section` styling
- added `SpecifyIndividualTargets` component, styling and tests
- added `TargetBasedOnConditions` component, styling and tests
- added `TargetSelect` component, styling and tests
- added `getInstructions` file with `getTargetInstructions` and `getRulesInstructions` functions and associated tests
- added `useEditTargetGroupCriteriaDialog` hook and tests
- added new language strings
- added `targetToSelectOption` utility and tests

### Changes
- changed `TargetGroupCriteria` to include edit button to invoke modal

2022-01-19 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6916) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6916) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=6916) it.</sub>

2022-01-19 10:33 UTC, crystal-fong commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/RuleRow.tsx
> +          itemFromNewTag={tag => tag}
what is this line doing?

2022-01-19 10:37 UTC, crystal-fong commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/TargetSelect.tsx
> +      style={{ marginBottom: 0 }}
why inline styling here?

2022-01-19 10:48 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/RuleRow.tsx
> +          itemFromNewTag={tag => tag}
Good question. It gives the opportunity to transform what the user entered into a new item. In our case all we want is a string, so we can take it verbatim, but in others, maybe we'd need to generate something else. Looks silly here, but it's a required prop unfortunately.

2022-01-19 10:53 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/TargetSelect.tsx
> +      style={{ marginBottom: 0 }}
Laziness and it seemed like overkill for a single thing like this. Open to pulling it into its own file if you want (I'd probably suggest the same thing).

2022-01-19 10:56 UTC, crystal-fong commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/TargetSelect.tsx
> +      style={{ marginBottom: 0 }}
you're giving the kids a bad example 😞

2022-01-20 21:23 UTC, tan-nhu submitted a review, later dismissed

2022-01-24 11:04 UTC, chrisblakely01 requested changes
Looks good just a few things/Questions

2022-01-24 11:04 UTC, chrisblakely01 commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/__tests__/TargetSelect.test.tsx
> +    for (const target of mockTargets) {
probably no need to loop this especially when theres only 3 things. Would read better if the 3 `expects` were explicit. But no real need to change this now

2022-01-24 11:15 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/EditTargetGroupCriteriaDialog.tsx
> +      environment: targetGroup.environment as string,
Yeah... although `environment` in practice is always present, it's officially an optional field and `queryParams` requires it.

2022-01-24 11:16 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/TargetBasedOnConditions.tsx
> +                  style={{ padding: 0 }}
The link variation includes padding at the start and end of the button, which is fine mid-sentence to make sure words don't but up against it, but at the start of a line, it pushes the alignment out.

2022-01-24 11:23 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/TargetBasedOnConditions.tsx
> +      {targetAttributes && (
So when the fetch call hasn't completed successfully (i.e. it's loading or there's an error), `targetAttributes` is falsy, but when it completes, it will always be an array, so truthy, regardless of it having contents or not. `loading`, `error` and `targetAttributes` are in fact mutually exclusive.

But in saying that, I did have to read over the code again to confirm as it's not actually obvious in this chunk.

2022-01-24 11:25 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/TargetSelect.tsx
> +    debounce: 250
Fair enough.. what's 50ms between friends?

2022-01-24 11:37 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/TargetGroupCriteria.tsx
> +      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
Dang! How did I miss this? I typically dev like this and then extract to a SCSS file. My bad. Will fix 👍🏻

2022-01-24 11:39 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/EditTargetGroupCriteriaDialog.module.scss
> +.dialog {
Almost all dialogs have a set width and height, but most do so in a style prop. Just pulled it out.

2022-01-24 11:43 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/__tests__/TargetSelect.test.tsx
> +    for (const target of mockTargets) {
You're probably right. Always feels icky using numerical array indexes. My reasoning was that `mockTargets` can then grow to any size and we'll not need to change the assertions.

2022-01-24 14:42 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/__tests__/TargetSelect.test.tsx
> +    for (const target of mockTargets) {
Changed

2022-01-24 14:42 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/TargetGroupCriteria.tsx
> +      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
Fixed

2022-01-24 14:43 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/TargetBasedOnConditions.tsx
> +                  style={{ padding: 0 }}
Removed extra styling

2022-01-24 14:47 UTC, crystal-fong commented on src/modules/75-cf/pages/target-group-detail/components/EditTargetGroupCriteria/TargetSelect.tsx
> +      style={{ marginBottom: 0 }}
😆 👍

2022-01-24 16:13 UTC, chrisblakely01 approved these changes
Awesome stuff, big improvements to the codebase all round with this one 👍

2022-01-24 16:21 UTC, tan-nhu approved these changes

2022-01-24 16:21 UTC, merged