feat: [COMP-3475]: Add STO module into Core UI
harness/harness-core-ui pull request #6931
Opened 2022-01-19 23:39 UTC by tan-nhu

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-01-19 23:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6931) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6931) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=6931) it.</sub>

2022-01-20 01:35 UTC, anjanBalgovind approved these changes

2022-01-20 14:34 UTC, chris-harness requested changes
STO needs to be further down on the modules hierarchy, as it will be defining its own CI and CD steps. See my PR: https://github.com/harness/harness-core-ui/pull/6661

2022-01-20 16:51 UTC, chris-harness approved these changes
Discussed my previous question with Tan. We'll be using two separate modules.

2022-01-20 16:52 UTC, merged