feat: [GTM-613]: add new feature banner
harness/harness-core-ui pull request #6949
Opened 2022-01-20 22:01 UTC by nanaxuHarness

##### Summary:

this is to add feature banner so that each module page can show different messages accordingly

##### Jira Links:

https://harness.atlassian.net/browse/PLG-613

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-01-20 23:05 UTC, nanaxuHarness commented
retrigger jest

2022-01-22 04:49 UTC, vkbansal requested changes

2022-01-22 04:49 UTC, vkbansal commented on src/framework/featureStore/FeaturesFactory.ts
> +import type { BannerType } from '@common/layouts/FeatureBanner'
This is a circular dependency. Please fix it.

2022-01-22 04:49 UTC, vkbansal commented on src/modules/10-common/layouts/FeatureBanner.tsx
> +export enum BannerType {
Move this to seperate file to avoid circular dependency

2022-01-24 15:17 UTC, nanaxuHarness commented on src/modules/10-common/layouts/FeatureBanner.tsx
> +export enum BannerType {
moved to `Constants.ts`

2022-01-24 15:24 UTC, vkbansal approved these changes

2022-01-24 15:31 UTC, kapilkumawat86 approved these changes

2022-01-24 15:43 UTC, merged