feat: [FFM-2087]: Added developer limit banner and plan enforcement tooltip to access control page
harness/harness-core-ui pull request #6967
Opened 2022-01-21 14:40 UTC by chrisblakely01

##### Summary:

- Adds the plan enforcement developer limit banner to the access control pages
- Adds the plan enforcement tooltip to the "Feature Flag Management" option in the "New User" > "Roles" dropdown 

##### Changes:

- Added `DeveloperLimitBanner` and tests to `rbac` module
- Move `user role` dropdown from `RoleAssignmentForm` to its own component `NewUserRoleDropdown` and added tests (This made it easier to isolate/write cleaner tests for my change"

##### Jira Links:

[FFM-2087](https://harness.atlassian.net/jira/software/c/projects/FFM/boards/98?modal=detail&selectedIssue=FFM-2087)

#####  Figma Links:

https://www.figma.com/file/KBWLXtXUnh6leVq0l7OzNG/Product-Led-Growth?node-id=570%3A68763

##### Screenshots:

If `FEATURE_ENFORCEMENT_ENABLED` is disabled, the functionality remains the same:

<img width="228" alt="Screenshot 2022-01-19 at 10 15 57" src="https://user-images.githubusercontent.com/10871707/150542292-55b308bb-ebf5-486f-80b7-a0f3548e2c75.png">

IF `FEATURE_ENFORCEMENT_ENABLED` is enabled, and the account has reached its FF free plan limits, the "Feature Flag Management" option is disabled, and a tooltip is shown:

<img width="680" alt="Screenshot 2022-01-19 at 10 08 31" src="https://user-images.githubusercontent.com/10871707/150542485-bea026b4-f9b2-4c9c-9606-693125c89d85.png">

We also show the developer limit banner in this case:

<img width="1073" alt="Screenshot 2022-01-24 at 11 18 49" src="https://user-images.githubusercontent.com/10871707/150773745-d9304423-e31b-4980-a707-300b48fea760.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-01-21 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6967) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=6967) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=6967) it.</sub>

2022-01-24 11:13 UTC, chrisblakely01 commented on src/modules/20-rbac/components/DeveloperLimitBanner/__tests__/DeveloperLimitBanner.test.tsx
> +// eslint-disable-next-line no-restricted-imports
This isn't ideal but this is the platform hook I need to use. Moving this component to `common` results in the same thing linting error - Suggestions welcome

2022-01-24 11:14 UTC, chrisblakely01 commented on src/modules/20-rbac/components/NewUserRoleDropdown/NewUserRoleDropdown.module.scss
> +.selectPopover {
FYI This was moved from the existing stylesheet

2022-01-24 11:15 UTC, chrisblakely01 commented on src/modules/20-rbac/components/NewUserRoleDropdown/NewUserRoleDropdown.tsx
> +        if (isFeatureEnforcementEnabled && item.value === '_feature_flag_manage_role') {
This new functionality should only apply to `_feature_flag_manage_role` - is this a safe check? is `_feature_flag_manage_role` consistent across the environments?

2022-01-24 13:15 UTC, reetika04 commented on src/modules/20-rbac/components/DeveloperLimitBanner/DeveloperLimitBanner.tsx
> +import { useGetUsageAndLimit } from '@auth-settings/hooks/useGetUsageAndLimit'
Please move useGetUsageAndLimit to common instead.

2022-01-24 13:16 UTC, reetika04 commented on src/modules/20-rbac/components/DeveloperLimitBanner/__tests__/DeveloperLimitBanner.test.tsx
> +      path="/account/:accountId/cf/orgs/:orgIdentifier/projects/:projectIdentifier/feature-flags"
Please use routes

2022-01-24 13:16 UTC, reetika04 commented on src/modules/20-rbac/components/NewUserRoleDropdown/NewUserRoleDropdown.tsx
> +          return <Menu.Item key={item.value as string} text={item.value} onClick={handleClick} />
```suggestion
          return <Menu.Item key={item.value as string} text={item.label} onClick={handleClick} />
```

2022-01-24 13:17 UTC, reetika04 commented on src/modules/20-rbac/components/NewUserRoleDropdown/NewUserRoleDropdown.tsx
> +              text={item.value}
```suggestion
              text={item.label}
```

2022-01-24 13:19 UTC, reetika04 commented on src/modules/20-rbac/components/NewUserRoleDropdown/NewUserRoleDropdown.tsx
> +        if (isFeatureEnforcementEnabled && item.value === '_feature_flag_manage_role') {
This is not a safe check, Any managed role such as _feature_flag_manage_role could be replicated as a custom role. Account/Project Admin is also super set of  FF Manage Role.

2022-01-24 13:22 UTC, reetika04 requested changes

2022-01-24 13:22 UTC, reetika04 commented on src/modules/20-rbac/components/DeveloperLimitBanner/DeveloperLimitBanner.tsx
> +  const isPaidTeamOrEnterpriseSubscription =
Can we check why this is specific to FF?

2022-01-25 12:58 UTC, chrisblakely01 commented on src/modules/20-rbac/components/DeveloperLimitBanner/DeveloperLimitBanner.tsx
> +import { useGetUsageAndLimit } from '@auth-settings/hooks/useGetUsageAndLimit'
moved

2022-01-25 12:58 UTC, chrisblakely01 commented on src/modules/20-rbac/components/DeveloperLimitBanner/DeveloperLimitBanner.tsx
> +  const isPaidTeamOrEnterpriseSubscription =
See answers in comments here: https://harness.atlassian.net/browse/FFM-2087

2022-01-25 12:58 UTC, chrisblakely01 commented on src/modules/20-rbac/components/DeveloperLimitBanner/__tests__/DeveloperLimitBanner.test.tsx
> +// eslint-disable-next-line no-restricted-imports
fixed as per comments above

2022-01-25 12:58 UTC, chrisblakely01 commented on src/modules/20-rbac/components/DeveloperLimitBanner/__tests__/DeveloperLimitBanner.test.tsx
> +      path="/account/:accountId/cf/orgs/:orgIdentifier/projects/:projectIdentifier/feature-flags"
fixed

2022-01-25 12:59 UTC, chrisblakely01 commented on src/modules/20-rbac/components/NewUserRoleDropdown/NewUserRoleDropdown.tsx
> +        if (isFeatureEnforcementEnabled && item.value === '_feature_flag_manage_role') {
See answers in comments here: https://harness.atlassian.net/browse/FFM-2087

2022-01-25 12:59 UTC, chrisblakely01 commented on src/modules/20-rbac/components/NewUserRoleDropdown/NewUserRoleDropdown.tsx
> +              text={item.value}
fixed

2022-01-25 12:59 UTC, chrisblakely01 commented on src/modules/20-rbac/components/NewUserRoleDropdown/NewUserRoleDropdown.tsx
> +          return <Menu.Item key={item.value as string} text={item.value} onClick={handleClick} />
fixed

2022-01-25 13:30 UTC, reetika04 approved these changes
There are a few other open questions on this PR listed here https://harness.atlassian.net/browse/FFM-2087

2022-01-27 08:45 UTC, willd0yle approved these changes

2022-01-27 08:48 UTC, merged