feat: [PL-20882]: Full Sync UI page
harness/harness-core-ui pull request #6998
Opened 2022-01-24 16:29 UTC by sunnykesh-harness

##### Summary:
Changes are to list the entities created before enabling gitSync with the option of 

- Filter and search with debounce
- Trigering reSync
- Pagination

It is deployed in [PR env](https://pr.harness.io/full-sync-pms/ng/#/account/kmpySmUISimoRrJL6NL73w/cd/orgs/default/projects/newproject2/setup/git-sync/config) and use cases tested are [listed here](https://docs.google.com/spreadsheets/d/1ZtvPS-HHJGSftwziMaflSkPiBM1MOwuHEyuBqW2pf-s/edit#gid=2069188771)

##### Jira Links:
https://harness.atlassian.net/browse/PL-20882

##### Screenshots:
<img width="1786" alt="Screenshot 2022-01-24 at 9 51 41 PM" src="https://user-images.githubusercontent.com/63278928/150822106-f5c82468-dd65-43bb-a1bf-1399a1e465dc.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-01-24 16:46 UTC, sunnykesh-harness commented
retrigger titlecheck

2022-01-24 16:55 UTC, avinashmadhwani02 commented on src/modules/40-gitsync/pages/GitSyncPage.tsx
> +                        label: 'Config',
Add Config in string constants

2022-01-24 16:59 UTC, avinashmadhwani02 commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +      padding={{ top: 'small', right: 'small', bottom: 'small', left: 'small' }}
padding='small'?

2022-01-24 17:00 UTC, avinashmadhwani02 commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +      <Text font={{ size: 'normal' }} color={highlightedColor}>
We can use fontVariation here

2022-01-24 17:03 UTC, sunnykesh-harness commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +      <Text font={{ size: 'normal' }} color={highlightedColor}>
Has to add different colour explicitly so inline styling will be not avoided. Variation will add its own colour and weight, but we need just size.

2022-01-24 17:05 UTC, avinashmadhwani02 commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +        flex={{ alignItems: 'center' }}
Do we need alignItems center? there are no items in Icon

2022-01-24 17:05 UTC, avinashmadhwani02 commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +        <Text lineClamp={1} color={Color.GREY_900} font={{ weight: 'semi-bold' }}>
fontVariation?

2022-01-24 17:08 UTC, sunnykesh-harness commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +        flex={{ alignItems: 'center' }}
It has internally.

2022-01-24 17:09 UTC, avinashmadhwani02 commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +        ) : fullSyncEntities?.totalItems ? (
Please avoid using nested conditional operator

2022-01-24 17:11 UTC, sunnykesh-harness commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +        <Text lineClamp={1} color={Color.GREY_900} font={{ weight: 'semi-bold' }}>
no variation matches this styling. Variation is mostly a combination of <size, weight, colour>, That will fit most of places but few places are different.

2022-01-24 17:13 UTC, sunnykesh-harness commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +        ) : fullSyncEntities?.totalItems ? (
IMO, it is not so complex, handling 3 use case  --> showing  loading , ( data ? showing data : NoData)

2022-01-24 17:15 UTC, avinashmadhwani02 commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +      <Text font={{ size: 'normal' }} color={highlightedColor}>
FontVariation shouldn't add colour, it should only change weight and size. If color is getting added, we should solve this problem

2022-01-24 17:31 UTC, sunnykesh-harness commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +        <Text lineClamp={1} color={Color.GREY_900} font={{ weight: 'semi-bold' }}>
Will discuss with UX, about introducing new variation for this use case.

2022-01-24 17:33 UTC, sunnykesh-harness commented
trigger cypress

2022-01-24 17:33 UTC, knagurski reviewed
Some comments and suggestions

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +        <Text lineClamp={1}> {`${getString('common.ID')}: ${data.identifier}`} </Text>
Does this need the spaces?

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +      <Text font={{ size: 'normal' }} color={highlightedColor}>
Is there a `FontVariation` that might be more suitable than specifying the size and color?

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +      padding={{ top: 'small', right: 'small', bottom: 'small', left: 'small' }}
I think you can just pass `small` instead of specifying each side
```suggestion
      padding="small"
```

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +  switch (prop.status) {
Might as well use the `status` variable from a few lines above
```suggestion
  const status = prop.status
  let data: StatusData

  switch (status) {
```

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.module.scss
> +  [data-testid='entityTypeFilter'] {
Probably shouldn't use the testid as a selector.

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +  const fetchFullSyncFiles = () => {
Do we know the return type of this?

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +  const { mutate: getFullSyncFiles, loading } = useListFullSyncFiles({
Why is this a mutation? Seems like it should just be a normal fetch

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +      searchTerm
Would `debounce: 500` work here and allow you to pull out the manual debouncing stuff below?

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +  }, [fullSyncEntities])
Do you need to also add `page` to the deps array?

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +        <Layout.Horizontal flex={{ justifyContent: 'space-between' }} width={'100%'}>
No need for parens
```suggestion
        <Layout.Horizontal flex={{ justifyContent: 'space-between' }} width="100%">
```

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +            ></Button>
Self closing tag
```suggestion
            />
```

2022-01-24 17:33 UTC, knagurski commented on src/modules/40-gitsync/pages/config/__tests__/GitSyncConfigTab.test.tsx
> +    expect(container).toMatchSnapshot()
Would it be possible to add some more assertions instead of a snapshot. Snapshots tend to be brittle and don't really prove the code is working.

2022-01-24 17:35 UTC, sunnykesh-harness commented on src/modules/40-gitsync/pages/config/__tests__/GitSyncConfigTab.test.tsx
> +    expect(container).toMatchSnapshot()
It is  primarily a listing page. I am waiting for one of the entity name, when it is available then just matching the page.

2022-01-24 17:41 UTC, sunnykesh-harness commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.module.scss
> +  [data-testid='entityTypeFilter'] {
Intentionally did that as jest test written with this will break if this changes and then we change at both place,. But, not sure about other DOM elements.

2022-01-24 17:59 UTC, sunnykesh-harness commented on src/modules/40-gitsync/pages/config/__tests__/GitSyncConfigTab.test.tsx
> +    .mockImplementation(() => ({ mutate: fetchFullSyncEntities, loading: false, data: mockFullSyncFiles.data })),
Simplified other mocks to `mockReturnValue` , for this if I change syntax it is throwing error that can not access `fetchFullSyncEntities`

2022-01-24 18:33 UTC, yc147 submitted a review, later dismissed

2022-01-24 18:34 UTC, sunnykesh-harness commented
dockerize

2022-01-25 05:21 UTC, avinashmadhwani02 approved these changes

2022-01-25 07:21 UTC, abhinavrastogi-harness requested changes

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +  icontProp: IconProps
spelling of `icontProp`?

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/pages/config/GitFullSyncEntityList.tsx
> +const RenderEntityStatus = (prop: Record<'status', GitFullSyncEntityInfoDTO['syncStatus']>): JSX.Element => {
use `React.FC` instead of custom return type of `JSX.ELement`

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.module.scss
> +  [data-testid='entityTypeFilter'] {
+1. Avoid targetting data attributes in CSS. It can be flaky.
I didn't understand what's the issue with adding a new class?

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.module.scss
> +  border-radius: var(--spacing-2);
spacing for radius?

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +    debounceWait
why would this ever be zero?

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +    debounceWait
if you want to avoid debounce on the first call, you can either call `returnvalue.flush()` or set the option to trigger it on the leading edge.

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +    const triggerFullSync = await triggerFullSyncPromise({
should be wrapper in try-catch to handle 500s or network failures

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +    setFullSyncEntities((await debouncedGetFullSyncFiles()).data)
should be wrapper in try-catch to handle 500s or network failures

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.tsx
> +      <Page.Body>
why not use the `loading` and `noData` props from PageBody itself? no need to handle that logic on your own

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/pages/config/__tests__/GitSyncConfigTab.test.tsx
> +    expect(container).toMatchSnapshot()
you can add an assertion for count of rows on the page to match your mock data

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/pages/config/__tests__/GitSyncConfigTab.test.tsx
> +        path="/account/:accountId/cd/orgs/:orgIdentifier/projects/:projectIdentifier/admin/git-sync/config"
you can use the RouteDefintion here also instead of hardcoding the path. makes the test less brittle in case the route changes in the future

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/strings/strings.en.yaml
> +syncFailed: Sync Failed
why is Failed capitalised?

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/strings/strings.en.yaml
> +syncStatus: Sync Status
Why is Status capitalised?

2022-01-25 07:21 UTC, abhinavrastogi-harness commented on src/modules/40-gitsync/strings/strings.en.yaml
> +resyncButtonText: Resync Failed Entities
why is Failed and Entities capitalised?

2022-01-25 07:45 UTC, sunnykesh-harness commented on src/modules/40-gitsync/strings/strings.en.yaml
> +syncStatus: Sync Status
It is in mock https://www.figma.com/file/4cqisYyQGDjzz51LyDp0Wj/Config-as-Code?node-id=3374%3A24418

2022-01-25 07:45 UTC, sunnykesh-harness commented on src/modules/40-gitsync/strings/strings.en.yaml
> +syncFailed: Sync Failed
It is in mock https://www.figma.com/file/4cqisYyQGDjzz51LyDp0Wj/Config-as-Code?node-id=3374%3A24418

2022-01-28 11:43 UTC, sunnykesh-harness commented on src/modules/40-gitsync/pages/config/GitSyncConfigTab.module.scss
> +  [data-testid='entityTypeFilter'] {
corrected.

2022-01-28 11:43 UTC, sunnykesh-harness commented on src/modules/40-gitsync/pages/config/__tests__/GitSyncConfigTab.test.tsx
> +    expect(container).toMatchSnapshot()
done

2022-01-28 11:45 UTC, sunnykesh-harness commented on src/modules/40-gitsync/strings/strings.en.yaml
> +resyncButtonText: Resync Failed Entities
It is for button text, same in mock https://www.figma.com/file/4cqisYyQGDjzz51LyDp0Wj/Config-as-Code?node-id=3374%3A24418

2022-01-28 12:59 UTC, abhinavrastogi-harness approved these changes

2022-01-28 16:06 UTC, sunnykesh-harness commented
dockerize

2022-01-29 04:43 UTC, abhinavrastogi-harness approved these changes

2022-01-29 07:09 UTC, avinashmadhwani02 approved these changes

2022-01-29 07:10 UTC, merged