fix: [PIE-2402]: skipped stage unselection
harness/harness-core-ui pull request #7017
Opened 2022-01-25 08:50 UTC by AshwinBhatkal-Harness

##### Summary:

We should not auto select a stage that is skipped

##### Jira Links:

https://harness.atlassian.net/browse/PIE-2402

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-01-25 11:02 UTC, vkbansal approved these changes

2022-01-27 04:25 UTC, kapilkumawat86 approved these changes

2022-01-27 04:37 UTC, vkbansal requested changes

2022-01-27 04:37 UTC, vkbansal commented on src/modules/70-pipeline/utils/executionUtils.ts
> +      if (stage.status === 'Skipped') {
please use `isExecutionSkipped` helper from [here](https://github.com/harness/harness-core-ui/blob/85e84789084c51a779dda606ae622c058db227d0/src/modules/70-pipeline/utils/statusHelpers.ts#L135)

2022-01-27 04:50 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/utils/executionUtils.ts
> +      if (stage.status === 'Skipped') {
Made the change

2022-01-27 04:50 UTC, AshwinBhatkal-Harness commented
retrigger typecheck

2022-01-27 05:11 UTC, AshwinBhatkal-Harness commented
retrigger typecheck

2022-01-27 06:02 UTC, closed without merging

2022-01-27 06:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7017) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7017) before we can accept your contribution.<br/>**13** out of **18** committers have signed the CLA.<br/><br/>:white_check_mark: bhavya-sinha<br/>:white_check_mark: AshwinBhatkal-Harness<br/>:white_check_mark: vardanbansal-harness<br/>:white_check_mark: azharness<br/>:white_check_mark: vkbansal<br/>:white_check_mark: sean-harness<br/>:white_check_mark: rajarshee-harness<br/>:white_check_mark: yc147<br/>:white_check_mark: kapilkumawat86<br/>:white_check_mark: mtran7<br/>:white_check_mark: chetanvekariya-harness<br/>:white_check_mark: crystal-fong<br/>:white_check_mark: deepesh-ui<br/>:x: jenil-harness<br/>:x: chiragp1212<br/>:x: chrisblakely01<br/>:x: dhruvUpadhyay07<br/>:x: anjanBalgovind<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=7017) it.</sub>