Fix: [FFM-2080]: Learn More link redirects to Harness docs
harness/harness-core-ui pull request #7044
Opened 2022-01-26 15:42 UTC by crystal-fong

##### Summary:

The `Learn More` link in the tooltip didn't open.
Normal function is https://ngdocs.harness.io/article/dbk9uoaid3-add-targets should open when user click on `Learn More`
##### Jira Links:

https://harness.atlassian.net/browse/FFM-2080
##### Screenshots:
![image](https://user-images.githubusercontent.com/95680496/151195550-efacd160-945b-48f1-afdb-0c5a46ea7a29.png)

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-01-26 15:49 UTC, crystal-fong commented
retrigger titlecheck

2022-01-26 15:55 UTC, crystal-fong commented
retrigger titlecheck

2022-01-26 15:57 UTC, crystal-fong commented
trigger cypress

2022-01-26 16:09 UTC, crystal-fong commented
trigger cypress

2022-01-26 23:08 UTC, knagurski commented on src/modules/10-common/components/StringWithTooltip/StringWithTooltip.tsx
> +  onClick?: (e: React.MouseEvent<HTMLElement, MouseEvent>) => void
Since `StringWithTooltip` is just a `<span>`, we don't want to specifically offer `onClick` as an option, we want to allow the consumer to pass any prop which can be set on a `<span>`. I *THINK* what you need to do is just have the interface extent the right thing. Maybe like this...

```ts
export interface StringWithTooltipProps extends React.HTMLAttributes<HTMLSpanElement> {
  stringId: StringKeys
  tooltipId: string
}
```

2022-01-26 23:11 UTC, knagurski commented on src/modules/75-cf/components/SectionToggle/SectionToggle.tsx
> +          onClick={(e: React.MouseEvent<HTMLElement, MouseEvent>): void => e.stopPropagation()}
I think if you make the change in the interface you can simplify this...
```suggestion
          onClick={e => e.stopPropagation()}
```

2022-01-26 23:13 UTC, knagurski commented on src/modules/75-cf/components/SectionToggle/__test__/SectionToggle.test.tsx
> +      expect(document.getElementsByClassName('Tooltip--tooltipContentWrapper')).toBeInTheDocument()
If you need to query by class name, try `document.querySelector`
```suggestion
      expect(document.querySelector('.Tooltip--tooltipContentWrapper')).toBeInTheDocument()
```

2022-01-26 23:14 UTC, knagurski commented on src/modules/75-cf/components/SectionToggle/__test__/SectionToggle.test.tsx
> +      expect(screen.getByRole('link')).toHaveAttribute('href')
Nice use of `getByRole`!

2022-01-26 23:23 UTC, knagurski commented on src/modules/75-cf/components/SectionToggle/__test__/SectionToggle.test.tsx
> +      expect(document.getElementsByClassName('Tooltip--tooltipContentWrapper')).toBeInTheDocument()
I _THINK_ this will actually evaluate as true even without hovering. You need to wrap the component in the `TooltipContextProvider` and give it a dictionary of tooltip ids vs content. Check out `StringWithTooltip`'s test for an example.

2022-01-26 23:27 UTC, knagurski commented on src/modules/75-cf/components/SectionToggle/__test__/SectionToggle.test.tsx
> +      expect(document.getElementsByClassName('Tooltip--tooltipContentWrapper')).toBeInTheDocument()
I think to prove this actually works, you'll need the above tooltip dictionary with a link in it and override `NavLink` to have an `onClick` mock. The test would be to render the thing, hover, wait for the new link to show, click it and then assert that the `onClick` mock did not get called.

2022-01-26 23:29 UTC, knagurski commented on src/modules/75-cf/components/SectionToggle/__test__/SectionToggle.test.tsx
> +  test.only('it should render a tooltip with a link when hovering over Target Segments button', () => {
As above, I'm pretty sure this won't actually exercise the component

2022-01-26 23:29 UTC, knagurski commented on src/modules/75-cf/components/SectionToggle/__test__/SectionToggle.test.tsx
> +  test.only('it should render a tooltip with a link when hovering over Target Segments button', () => {
Looks like you left an `only` in there
```suggestion
  test('it should render a tooltip with a link when hovering over Target Segments button', () => {
```

2022-01-26 23:31 UTC, knagurski requested changes
Really good first swipe at it! There's some nuance in testing the tooltips to watch out for and I think you can make the `StringWithTooltipProps` interface a bit more useful with a tweak.

2022-01-28 14:33 UTC, knagurski submitted a review, later dismissed
Looks the part!

2022-01-31 11:20 UTC, chrisblakely01 approved these changes

2022-01-31 14:17 UTC, willd0yle approved these changes

2022-01-31 14:19 UTC, merged