feat: [CCM-5384]: Anomaly detection tooltip ingress point
harness/harness-core-ui pull request #7153
Opened 2022-02-02 12:31 UTC by jyotiarora-harness

##### Summary:

Ingress point of anomaly detection page, show tooltip on perspective page(charts)

##### Jira Links:
Feature: https://harness.atlassian.net/browse/CCM-5383
Task: https://harness.atlassian.net/browse/CCM-5384

##### Screenshots:

<img width="1394" alt="Screenshot 2022-02-02 at 6 00 53 PM" src="https://user-images.githubusercontent.com/97077953/152154042-07170042-8f5a-47c0-8230-e7936020ce91.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-15 06:24 UTC, jyotiarora-harness commented
retrigger typecheck

2022-02-15 06:38 UTC, jyotiarora-harness commented
retrigger jest

2022-02-15 07:20 UTC, jyotiarora-harness commented
retrigger coverage

2022-02-15 11:08 UTC, jyotiarora-harness commented
retrigger jest

2022-02-15 12:20 UTC, rishik30 requested changes

2022-02-15 12:20 UTC, rishik30 commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.tsx
> +              ${item.differenceFromExpectedCost && formatCost(item.differenceFromExpectedCost)}
We should use conditional expression here or some default value to not render `undefined` in case.

2022-02-15 12:20 UTC, rishik30 commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.tsx
> +      anomaliesCountData &&
use optional chaining here like this `anomaliesCountData?.map(cb)`

2022-02-15 12:20 UTC, rishik30 commented on src/modules/75-ce/pages/perspective-details/PerspectiveDetailsPage.tsx
> +        // console.log('response', response)
remove commented code

2022-02-15 12:20 UTC, rishik30 commented on src/modules/75-ce/pages/perspective-details/PerspectiveDetailsPage.tsx
> +        // console.log('error', error)
remove this commented code

2022-02-15 12:21 UTC, rishik30 commented
@jyotiarora-harness please address sonar issues too.

2022-02-16 04:23 UTC, jyotiarora-harness commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.tsx
> +              ${item.differenceFromExpectedCost && formatCost(item.differenceFromExpectedCost)}
Done the null handling here

2022-02-16 04:23 UTC, jyotiarora-harness commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.tsx
> +      anomaliesCountData &&
Updated

2022-02-16 04:23 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/perspective-details/PerspectiveDetailsPage.tsx
> +        // console.log('response', response)
Removed

2022-02-16 04:23 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/perspective-details/PerspectiveDetailsPage.tsx
> +        // console.log('error', error)
Handled with error toaster

2022-02-16 04:51 UTC, rishik30 submitted a review, later dismissed

2022-02-16 05:23 UTC, jenil-harness commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.module.scss
> +  border-bottom: var(--spacing-xxlarge) solid #cf2318;
use css vars.

2022-02-16 05:35 UTC, jenil-harness commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.module.scss
> +  padding: var(--spacing-medium) 12px;
Possible to use standard spacing defined?

2022-02-16 05:35 UTC, jenil-harness commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.module.scss
> +  font-weight: normal;
By default font-weight will be normal right?

2022-02-16 05:35 UTC, jenil-harness commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.tsx
> +    <article key={idx} onClick={redirection}>
on click is on the entire chart? Better to keep it on the element.

2022-02-16 06:38 UTC, jyotiarora-harness commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.module.scss
> +  border-bottom: var(--spacing-xxlarge) solid #cf2318;
Updated

2022-02-16 06:39 UTC, jyotiarora-harness commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.module.scss
> +  padding: var(--spacing-medium) 12px;
Changed it to standard one

2022-02-16 06:39 UTC, jyotiarora-harness commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.module.scss
> +  font-weight: normal;
Yes, removed the same

2022-02-16 06:39 UTC, jyotiarora-harness commented on src/modules/75-ce/components/CloudCostInsightChart/Chart.tsx
> +    <article key={idx} onClick={redirection}>
Yes I tried onClick on element only but that's not working
It seems like html onclick event is not getting triggered in react synthetic events environment
That's why written on chart level

2022-02-16 07:14 UTC, jyotiarora-harness commented
retrigger coverage

2022-02-16 09:08 UTC, jyotiarora-harness commented
retrigger coverage

2022-02-16 11:47 UTC, jyotiarora-harness commented
retrigger coverage

2022-02-17 05:36 UTC, jenil-harness approved these changes

2022-02-17 05:46 UTC, rishik30 approved these changes

2022-02-18 07:46 UTC, kapilkumawat86 approved these changes

2022-02-18 07:46 UTC, merged