chore: [PL-20548]: update ui-core version for Fix for Placeholder in tag component
harness/harness-core-ui pull request #7167
Opened 2022-02-03 08:44 UTC by mayankVermaHarness

##### Summary:

Corresponding UI-Core PR: https://github.com/harness/uicore/pull/579

##### Jira Links:

https://harness.atlassian.net/browse/PL-20548

##### Screenshots:

**Before:**
![image](https://user-images.githubusercontent.com/96057095/152298672-2b791b81-5e3b-4b73-9d24-6b74fc13d8f6.png)

**After:**
![image](https://user-images.githubusercontent.com/96057095/152298378-70cb520e-7d98-47ee-8142-f9fc46fddd5e.png)

**Before:**
![image](https://user-images.githubusercontent.com/96057095/152298534-d4fdc89f-b85a-4544-b980-d0608d8320db.png)

**After:**
![image](https://user-images.githubusercontent.com/96057095/152298484-fe295402-a6cc-49c4-b5b5-0f1f290cd3fa.png)

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-03 08:48 UTC, avinashmadhwani02 approved these changes

2022-02-03 08:51 UTC, avinashmadhwani02 commented on package.json
> +    "@harness/uicore": "^2.3.0",
let's use exact version, remove ^

2022-02-03 08:56 UTC, reetika04 approved these changes

2022-02-03 09:09 UTC, abhinavrastogi-harness commented on package.json
> +    "@harness/uicore": "^2.3.0",
please dont change this. it can have dangerous side effects with microfrontends.

2022-02-03 09:09 UTC, abhinavrastogi-harness requested changes
@mayankVermaHarness i think you manually changed in package.json?
use `yarn upgrade` instead so that yarn.lock also updates.
otherwise uicore will not actually get updated.

2022-02-03 12:13 UTC, mayankVermaHarness commented
retrigger jest

2022-02-04 07:47 UTC, mayankVermaHarness commented
retrigger jest

2022-02-04 07:50 UTC, closed without merging