feat: [PL-22001]: Added Account Setting section to allow disable of Harness SM
harness/harness-core-ui pull request #7171
Opened 2022-02-03 14:02 UTC by meenakshi-harness

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-03 16:44 UTC, avinashmadhwani02 requested changes

2022-02-03 16:44 UTC, avinashmadhwani02 commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +      <Text color={Color.BLACK} font={{ weight: 'semi-bold', size: 'medium' }} margin={{ bottom: 'xlarge' }}>
fontVariation?

2022-02-03 16:44 UTC, avinashmadhwani02 commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +      component: <ConnectorSetting disableBuiltInSM={disableBuiltInSM} setDisableBuiltInSM={setDisableBuiltInSM} />
Avoid passing `setDisableBuiltInSM` method to this component, instead add onChange method

2022-02-03 16:44 UTC, avinashmadhwani02 commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +  useEffect(() => {
Do we need useEffect? `data` is already in state. Can we use that directly?

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/AccountOverview.tsx
> +        <AccountSetting />
nit: the component should be called `AccountSettings` :)

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/__test__/AccountSetting.test.tsx
> +    expect(container).toMatchSnapshot()
is snapshot required?

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/__test__/AccountSetting.test.tsx
> +    expect(container).toMatchSnapshot()
can we add an assertion on the dom instead of snapshot?

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.module.scss
> +        margin-top: 3px !important;
why a non-standard margin specifically on a control element? cant add a standard margin on the container instead?

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +      component: <ConnectorSetting disableBuiltInSM={disableBuiltInSM} setDisableBuiltInSM={setDisableBuiltInSM} />
+1

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +        connectorSetting && connectorSetting.length
nit: `connectorSettings` please :)

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +        connectorSetting && connectorSetting.length
also explicit `> 0` check on length is better for readability

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +          ? !!(connectorSetting[0].config as ConnectorSettings)?.builtInSMDisabled
why are we hardcoding `[0]` here?

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +        <PageError message={(error.data as Error)?.message || error.message} onClick={() => refetchAccountSettings()} />
use the existing `getError...` util. I dont remember the name exactly

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/connector/ConnectorSetting.tsx
> +const ConnectorSetting: React.FC<ConnectorSettingProps> = props => {
nit: `ConnectorSettings` please

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/connector/ConnectorSetting.tsx
> +  const { data: secretManagersApiResponse, loading: loadingSecretsManagers } = useGetConnectorList({
why do we need to fetch all secret managers for changing a setting?

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/connector/ConnectorSetting.tsx
> +      (secretManagersApiResponse?.data?.content?.length ? secretManagersApiResponse.data.content.length < 2 : true)
explicit `length > 0` check would be better

2022-02-04 04:39 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/connector/ConnectorSetting.tsx
> +        showError(e.data?.message || e.message)
use existing util to extract the error

2022-02-04 08:17 UTC, meenakshi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +      component: <ConnectorSetting disableBuiltInSM={disableBuiltInSM} setDisableBuiltInSM={setDisableBuiltInSM} />
done

2022-02-04 08:19 UTC, meenakshi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/connector/ConnectorSetting.tsx
> +          <div>
yes, label element renders the child inline.

2022-02-04 08:21 UTC, meenakshi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/connector/ConnectorSetting.tsx
> +          props.setDisableBuiltInSM(event.currentTarget.checked)
Was doing that earlier but I need to update the default value as well... since it can change from child. Hence instead on maintaining 2 states.. moved the state to parent.
Added onChange instead.

2022-02-04 08:22 UTC, meenakshi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/__test__/AccountSetting.test.tsx
> +    expect(container).toMatchSnapshot()
removed

2022-02-04 08:25 UTC, meenakshi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.module.scss
> +        margin-top: 3px !important;
I am using Checkbox component with labelElement. But when it renders label element, the checkbox input is misaligned to the labelElement.. hence added this margin. Is there other better way of fixing this?

2022-02-04 08:28 UTC, meenakshi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +  useEffect(() => {
added useEffect to avoid re-renders. let me know if it is still doable some other way?

2022-02-04 08:30 UTC, meenakshi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +          ? !!(connectorSetting[0].config as ConnectorSettings)?.builtInSMDisabled
This will always have one element. Added the check connectorSetting.length === 1 for safe side.

2022-02-04 08:38 UTC, meenakshi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/connector/ConnectorSetting.tsx
> +  const { data: secretManagersApiResponse, loading: loadingSecretsManagers } = useGetConnectorList({
We will not allow user to modify setting related to built-in SM if they don't have replacement for that secret manager configured at account level.

2022-02-04 08:42 UTC, meenakshi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/connector/ConnectorSetting.tsx
> +      (secretManagersApiResponse?.data?.content?.length ? secretManagersApiResponse.data.content.length < 2 : true)
You mean one more check of > 0?
```secretManagersApiResponse?.data?.content?.length  && secretManagersApiResponse?.data?.content?.length > 0? secretManagersApiResponse.data.content.length < 2 : true```

2022-02-04 08:59 UTC, meenakshi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/AccountSetting.tsx
> +        connectorSetting && connectorSetting.length
added connectorSetting.length===1

2022-02-06 18:07 UTC, meenakshi-harness commented
dockerize

2022-02-07 05:07 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/connector/ConnectorSetting.tsx
> +  const { data: secretManagersApiResponse, loading: loadingSecretsManagers } = useGetConnectorList({
if you just need the count of secret managers, you can request only one SM, and you'll get the count in the metadata.. It'll make teh API much faster.

2022-02-07 05:08 UTC, abhinavrastogi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/connector/ConnectorSetting.tsx
> +      (secretManagersApiResponse?.data?.content?.length ? secretManagersApiResponse.data.content.length < 2 : true)
just `secretManagersApiResponse?.data?.content?.length > 0` is sufficient. you dont need a null check.
`undefined > 0` returns false

2022-02-07 05:10 UTC, abhinavrastogi-harness approved these changes

2022-02-07 05:13 UTC, avinashmadhwani02 submitted a review, later dismissed

2022-02-09 16:02 UTC, meenakshi-harness commented on src/modules/33-auth-settings/pages/AccountOverview/views/Settings/connector/ConnectorSetting.tsx
> +      (secretManagersApiResponse?.data?.content?.length ? secretManagersApiResponse.data.content.length < 2 : true)
typescript is gives error in this comparison undefined > 0

2022-02-10 16:44 UTC, meenakshi-harness commented
dockerize

2022-02-10 21:46 UTC, meenakshi-harness commented
retrigger coverage

2022-02-10 23:09 UTC, meenakshi-harness commented
retrigger coverage

2022-02-11 10:51 UTC, meenakshi-harness commented
retrigger typecheck

2022-02-11 10:51 UTC, meenakshi-harness commented
retrigger titlecheck

2022-02-13 10:51 UTC, abhinavrastogi-harness commented
force-merging on request for monday branch cut. avinash had already approved earlier.

2022-02-13 10:51 UTC, merged