fix: [PIE-2561]: zoom to fit pipeline persistence over stage executions
harness/harness-core-ui pull request #7185
Opened 2022-02-04 11:53 UTC by AshwinBhatkal-Harness

##### Summary:

zoom to fit pipeline persistence over stage executions

##### Jira Links:

https://harness.atlassian.net/browse/PIE-2561

##### Screenshots:

Before:

https://user-images.githubusercontent.com/96711906/152524540-df043acd-c29f-4494-82b0-b76658faa7f7.mov

After:

https://user-images.githubusercontent.com/96711906/152523930-746c4ead-6f17-4229-8331-bd8ee6c40b19.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-04 12:48 UTC, chetanvekariya-harness approved these changes

2022-02-04 14:07 UTC, kapilkumawat86 approved these changes

2022-02-04 14:09 UTC, kapilkumawat86 requested changes

2022-02-04 14:09 UTC, kapilkumawat86 commented on src/modules/70-pipeline/components/ExecutionStageDiagram/ExecutionStageDiagram.tsx
> +    moveStageToFocus(engine, selectedIdentifier, true, mode === Modes.STEP)
I am confused, are stop doing reset only for stage

2022-02-04 16:54 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/ExecutionStageDiagram/ExecutionStageDiagram.tsx
> +    moveStageToFocus(engine, selectedIdentifier, true, mode === Modes.STEP)
We will reset zoom only for step and not for stage. Stage is for the stage execution and step is for the step execution. Stage is where the issue was reported

2022-02-11 06:05 UTC, kapilkumawat86 approved these changes

2022-02-11 06:52 UTC, YounixIO approved these changes

2022-02-11 06:52 UTC, devinder-harness approved these changes

2022-02-11 06:53 UTC, merged