feat: [CDB-61]: dashboards should be enterprise plans only
harness/harness-core-ui pull request #7217
Opened 2022-02-07 17:12 UTC by sean-harness

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-08 11:12 UTC, knagurski commented on src/framework/featureStore/FeatureIdentifier.ts
> +  CUSTOM_DASHBOARDS = 'CUSTOM_DASHBOARDS',
It doesn't look like this flag is used anywhere

2022-02-08 11:17 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsCommonHeaderPage.tsx
> +          {' '}
Do you need this space?

2022-02-08 11:18 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsCommonHeaderPage.tsx
> +        <Text color={Color.PRIMARY_6} style={{ cursor: 'pointer' }} onClick={() => setDrawerOpen(true)}>
A `div` should never be used to trigger an action. Use a `Button` component instead.

2022-02-08 11:22 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsContext.tsx
> +  breadcrumbs: { url: string; label: string }[]
You can use the `Breadcrumb` type here from `@harness/uicore`

2022-02-08 11:23 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsCommonHeaderPage.tsx
> +  const title = breadcrumbs ? breadcrumbs[breadcrumbs.length - 1].label : ''
Looking at the interface of the context hook, breadcrumbs will always be an array. Do you mean to check if that array has items?
```suggestion
  const title = breadcrumbs.length ? breadcrumbs[breadcrumbs.length - 1].label : ''
```

2022-02-08 11:24 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsContext.tsx
> +const DashboardsContext = React.createContext<DashboardsContextProps>({} as DashboardsContextProps)
Really annoying that React makes you create context values that are never used. I suppose an empty object is as good a solution as any 👍🏻

2022-02-08 11:26 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsContext.tsx
> +  const standardBreadcrumbs = [
Super minor, but might be worth typing this array
```suggestion
  const standardBreadcrumbs: Breadcrumb[] = [
```

2022-02-08 11:26 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsContext.tsx
> +  const [breadcrumbs, setBreadcrumbs] = useState(standardBreadcrumbs)
You can type this as well.
```suggestion
  const [breadcrumbs, setBreadcrumbs] = useState<Breadcrumb[]>(standardBreadcrumbs)
```

2022-02-08 11:27 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsContext.tsx
> +  const includeBreadcrumbs = (breadcrumbsToAdd: { url: string; label: string }[]): void => {
And use the `Breadcrumb type here too
```suggestion
  const includeBreadcrumbs = (breadcrumbsToAdd: Breadcrumb[]): void => {
```

2022-02-08 11:29 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsPage.tsx
> +}
`FC` already defines `children`, so you can drop this interface

2022-02-08 11:31 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsPage.tsx
> +const isEnterpriseLicense = (licenseInformation: { [key: string]: ModuleLicenseDTO } | Record<string, undefined>) => {
You can simplify the typing here.
```suggestion
const isEnterpriseLicense = (licenseInformation: Record<string, ModuleLicenseDTO | undefined>) => {
```

2022-02-08 11:32 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsPage.tsx
> +const isEnterpriseLicense = (licenseInformation: { [key: string]: ModuleLicenseDTO } | Record<string, undefined>) => {
You should provide the return type here
```suggestion
const isEnterpriseLicense = (licenseInformation: { [key: string]: ModuleLicenseDTO } | Record<string, undefined>): boolean => {
```

2022-02-08 11:33 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsPage.tsx
> +  return Object.values(licenseInformation).some(license => license && license.edition === Editions.ENTERPRISE)
Can you just use optional chaining?
```suggestion
  return Object.values(licenseInformation).some(license => license?.edition === Editions.ENTERPRISE)
```

2022-02-08 11:34 UTC, knagurski commented on src/modules/45-dashboards/pages/DashboardsPage.tsx
> +const DashboardsPage: React.FC<DashboardsPageProps> = ({ children }) => {
As above, you can drop the interface as `FC` has you covered
```suggestion
const DashboardsPage: React.FC = ({ children }) => {
```

2022-02-08 11:38 UTC, knagurski commented on src/modules/45-dashboards/pages/dashboardView/DashboardView.tsx
> +  }, [folderDetail, dashboarDetail])
I know not part of this PR, but there's a typo in `dashboardDetail`

2022-02-08 11:39 UTC, knagurski commented on src/modules/45-dashboards/pages/dashboardView/DashboardView.tsx
> +        label: folderDetail?.resource
You don't need the `?` here... the `if` above asserts it exists
```suggestion
        label: folderDetail.resource
```

2022-02-08 11:41 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +const getBreadcrumbLinks = (folderDetail: { resource: string }, accountId: string, folderString: string) => {
You should add the return type
```suggestion
const getBreadcrumbLinks = (folderDetail: { resource: string }, accountId: string, folderString: string): Breadcrumb[] => {
```

2022-02-08 11:42 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +        label: folderDetail?.resource
The `if` above asserts that `resource` exists, so you don't need the optional chaining here
```suggestion
        label: folderDetail.resource
```

2022-02-08 11:43 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +    includeBreadcrumbs(links)
Might as well eliminate the variable.
```suggestion
    includeBreadcrumbs(
      getBreadcrumbLinks(folderDetail, accountId, getString('dashboards.homePage.folders'))
    )
```

2022-02-08 11:44 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +  }, [folderDetail])
```suggestion
  }, [folderDetail, accountId])
```

2022-02-08 11:50 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +        >
Try to avoid inline styles; either use the props of the layout, or a class.
```suggestion
        <Layout.Horizontal border={{ bottom: true }} flex={{ justifyContent: 'space-between }}>
```

2022-02-08 11:51 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +            paddingRight: 0
Are these needed? I don't think `Layout` adds `padding` by default

2022-02-08 11:53 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +            style={{ justifyContent: 'space-between', alignItems: 'center', width: '100%' }}
Again, avoid inline styles.
```suggestion
            flex={{ justifyContent: 'space-between', alignItems: 'center' }}
```

2022-02-08 11:55 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                  <div key={item.value.toString()}>
Is this surrounding `div` required?

2022-02-08 11:56 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                  </div>
Is this surrounding `div` required?
```suggestion
                  <Menu.Item
                    key={item.value.toString()}
                    text={item.label}
                    onClick={handleClick}
                  />
```

2022-02-08 11:58 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                      <Text color={Color.BLACK}>{'Sort By'}</Text>
Can you get `Sort by` from the `getString` function instead

2022-02-08 12:03 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                <Button
Since there is no `text` prop or content, add the `aria-label` prop with a description of what this button does for accessibility
```suggestion
                <Button
                  aria-label={getString('switch to grid view')}
```

2022-02-08 12:03 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                <Button
As above with `aria-label`

2022-02-08 12:04 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +            FILTER BY TAGS
Extract this to the strings

2022-02-08 12:06 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +          <Text font={{ weight: 'semi-bold' }} color={Color.GREY_800}>
Is there a [variation](https://uicore.harness.io/?path=/story/components-text--basic&globals=measureEnabled:false) for this?

2022-02-08 12:10 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +        style={{ width: 'calc(100% - 280px)', height: 'calc(100vh - 226px)', paddingTop: 0, overflow: 'scroll' }}
Try to avoid inline styles. Use layout props or extract to a class.

2022-02-08 12:12 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +        style={{ width: 'calc(100% - 280px)', height: 'calc(100vh - 226px)', paddingTop: 0, overflow: 'scroll' }}
`overflow: 'scroll'` will ALWAYS should scrollbars, regardless of whether they are required or not. `overflow: 'auto'` will selectively show them.

2022-02-08 12:16 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +        <Layout.Horizontal style={{ marginLeft: 'var(--spacing-xxxlarge)', alignItems: 'baseline' }}>
You can use the `margin` and `flex` props or extract to a class
```suggestion
        <Layout.Horizontal margin={{ left: 'xxxlarge' }} flex={{ alignItems: 'baseline' }}>
```

2022-02-08 12:17 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                <section className={css.customTag} key={tag + index}>
Kinda overusing `section`

2022-02-08 12:19 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                  />
Don't use an icon as a button. You can use the icon variation of the `Button` component. ONLY buttons and links should have actions associated with them.

2022-02-08 12:20 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +            </Text>
Never hang an action off a `div`, always use a `Button` or a link

2022-02-08 12:22 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +        {filteredDashboardList && filteredDashboardList.length > 0 && layoutView === LayoutViews.GRID && (
You can simplify with optional chaining
```suggestion
        {!!filteredDashboardList?.length && layoutView === LayoutViews.GRID && (
```

2022-02-08 12:24 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                    >
Never navigate based on a click to a `div` use a `Link` instead

2022-02-08 12:25 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                      <Text color={Color.BLACK_100} font={{ size: 'normal', weight: 'semi-bold' }}>
Use a `variation` instead.

2022-02-08 12:28 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                      </Layout.Horizontal>
Any reason not to move the outer layout inside the condition?
```suggestion
                      
                        {dashboard?.type !== dashboardType.SHARED && (
                          <Layout.Horizontal spacing="medium">
                            <Layout.Horizontal style={{ marginRight: 'var(--spacing-8)' }}>
                              <Icon name="eye-open" size={18} style={{ marginRight: 'var(--spacing-4)' }} />
                              <Text color={Color.BLACK_100} font={{ size: 'normal', weight: 'semi-bold' }}>
                                {dashboard?.view_count}
                              </Text>
                            </Layout.Horizontal>

                            <Layout.Horizontal>
                              <Icon name="star-empty" size={18} style={{ marginRight: 'var(--spacing-4)' }} />
                              <Text color={Color.BLACK_100} font={{ size: 'normal', weight: 'semi-bold' }}>
                                {dashboard?.favorite_count}
                              </Text>
                            </Layout.Horizontal>
                          </Layout.Horizontal>
                        )}
```

2022-02-08 12:30 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                              <Icon name="eye-open" size={18} style={{ marginRight: 'var(--spacing-4)' }} />
Again, instead of using margin on the icon, you can use `spacing` on the surrounding layout

2022-02-08 12:36 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +                            </Layout.Horizontal>
Instead of layouts and icons, you can just use the `icon` prop of the `Text` component
```suggestion
                            <Text
                              color={Color.BLACK_100}
                              font={{ variation: FontVariation.SOMETHING_APPROPRIATE }}
                              icon="eye-open"
                              iconProps={{ size: 18 }}
                            >
                              {dashboard?.view_count}
                            </Text>
                            
                            <Text
                              color={Color.BLACK_100}
                              font={{ variation: FontVariation.SOMETHING_APPROPRIATE }}
                              icon="star-empty"
                              iconProps={{ size: 18 }}
                            >
                              {dashboard?.favourite_count}
                            </Text>
```

2022-02-08 12:41 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +      }}
By passing `retryOnError` you tell the body to render a `Retry` button, which in this case will do nothing and probably confuse the user. Better not to pass it if you don't want to trigger refetches.

2022-02-08 12:42 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +          }}
Use props or extract to a class.

2022-02-08 12:43 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +            <section style={{ display: 'flex' }}>
This really isn't a section

2022-02-08 12:44 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +            <section style={{ display: 'flex' }}>
`flex` with a single child element is kinda pointless. Do you need this tag at all?

2022-02-08 12:44 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                  <div key={item.value.toString()}>
Do you need these `div`s?

2022-02-08 12:45 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                      <Text color={Color.BLACK}>{'Sort By'}</Text>
Extract to the strings

2022-02-08 12:46 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                      <Text color={Color.BLACK}>{'Sort By'}</Text>
Instead of using a layout to align these, you can use pass the `inline` prop to the `Text` component to render it as a `span` instead of a `div`

2022-02-08 12:47 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                <Button
Add `aria-label` attribute

2022-02-08 12:47 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                <Button
Add `aria-label` attribute

2022-02-08 12:47 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +        <Layout.Horizontal style={{ padding: 'var(--spacing-6) var(--spacing-9) ' }}>
Avoid inline styles. Extract to a class or use layout props

2022-02-08 12:49 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                  />
Never hang an action off an icon, use a `Button` with the icon variation and the `aria-label` attribute.

2022-02-08 12:50 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +              onClick={() => setFilteredTags([])}
Never hang an action off a `Text` component. Use a `Button`

2022-02-08 12:51 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                      >
Never navigate using a click on a layout. Use a `Link` instead.

2022-02-08 12:53 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                                <img src={dashboardIcon} height={20} />
If this is an icon, it should be in UI Core as an icon and then you can use it using either the `Icon` component or the `icon` prop of the `Text` component

2022-02-08 12:55 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                          >
Avoid inline styles. Use layout props or extract to a class.

2022-02-08 12:57 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                                <Text color={Color.PRIMARY_7} font={{ size: 'medium', weight: 'semi-bold' }}>
There are SOOO many layers here. You can probably achieve the same thing by styling the `Text` directly instead of having a `p` inside of a `div` inside of a `div` inside of a `div` inside of a `div`

2022-02-08 12:59 UTC, knagurski requested changes
There are a lot of accessibility issues regarding click handlers on non-button/link elements. Also there are a lot of inline styles that need to be extracted to classes or converted to layout props. The a11y issues are a blocker

2022-02-09 13:59 UTC, sean-harness commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                      <Text color={Color.BLACK}>{'Sort By'}</Text>
The layout is adding margin through the spacing attribute. If I was to remove the layout I would need to add padding or margin to one of the text components.

2022-02-09 15:36 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                      <Text color={Color.BLACK}>{'Sort By'}</Text>
You can just use a space
```typescript
  text={
    <>
      <Text inline color={Color.BLACK}>Sort by</Text> {sortby.label}
    </>
  }
```

2022-02-09 15:43 UTC, sean-harness commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                      <Text color={Color.BLACK}>{'Sort By'}</Text>
I thought it was prefered to use the uicore components? You recommended using `<Text inline...>` earlier. Which is the recommended approach?

2022-02-09 15:57 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                      <Text color={Color.BLACK}>{'Sort By'}</Text>
Since all you want to do is change the colour of 2 words within this button, the `<span>` is the easier, more performant and more correct solution.

2022-02-10 12:13 UTC, knagurski requested changes
Really awesome stuff. Just a few wee notes and some click handlers hanging off non-button/link elements.

2022-02-10 12:13 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +        formName={'createFolderForm'}
```suggestion
        formName="createFolderForm"
```

2022-02-10 18:05 UTC, knagurski commented on src/modules/45-dashboards/pages/home/FilterTagsSideBar.tsx
> +  })
Is there not a hook in the dashboard service to get this instead of using `useGet` directly?

2022-02-10 18:22 UTC, knagurski commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +  }, [folderDetail, accountId])
```suggestion
  }, [folderDetail, accountId, folderId])
```

2022-02-10 18:35 UTC, knagurski commented on src/modules/45-dashboards/pages/folders/FoldersPage.tsx
> +                    accountId: accountId
Don't change it, but just just a wee FYI, with ES2017+ you simplify things like this
```suggestion
                    accountId
```

2022-02-10 18:41 UTC, knagurski approved these changes
Nice work and thanks for hanging in there with the comments.

2022-02-11 10:02 UTC, sean-harness commented on src/modules/45-dashboards/pages/home/HomePage.tsx
> +    return folderId.replace('shared', '')
`folderId` will be either an integer or the string 'shared' 
This is a little bit of a hack to reduce the cognitive complexity of the `HomePage` component as the Sonar check was failing everytime I made a change in `HomePage`

2022-02-11 10:06 UTC, sean-harness commented on src/modules/45-dashboards/pages/home/FilterTagsSideBar.tsx
> +  })
I moved this call from `HomePage` to here as a way to reduce the complexity of `HomePage`. Also this just happened to be a fairly isolated chunk which makes sense to be separated out.

2022-02-15 18:59 UTC, merged