fix: [CI-3443]: Fixing regex for map keys
harness/harness-core-ui pull request #7239
Opened 2022-02-08 10:56 UTC by vardanbansal-harness

##### Summary:

Bug fix for https://harness.atlassian.net/browse/CI-3443

![image](https://user-images.githubusercontent.com/48940704/152973485-9f53b350-03bd-4890-b131-88f218d4922b.png)

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-08 14:00 UTC, vardanbansal-harness commented
retrigger jest

2022-02-09 08:14 UTC, bhavya-sinha approved these changes

2022-02-09 08:20 UTC, vkbansal requested changes

2022-02-09 08:20 UTC, vkbansal commented on src/modules/10-common/utils/StringUtils.ts
> +export const keyRegexIdentifier = /^[a-zA-Z_][0-9a-zA-Z_$]+(\.[0-9a-zA-Z_$]+)*$/
Add test cases

2022-02-14 23:46 UTC, vardanbansal-harness commented on src/modules/10-common/utils/StringUtils.ts
> +export const keyRegexIdentifier = /^[a-zA-Z_][0-9a-zA-Z_$]+(\.[0-9a-zA-Z_$]+)*$/
Done.

2022-02-15 00:05 UTC, mtran7 approved these changes

2022-02-15 00:09 UTC, vardanbansal-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/__tests__/StepsValidateUtils.test.ts
> +    validKeyRegex: 'Keys can only contain alphanumerics and _ with an optional dot(.) in the middle',
Great point! I'll create one as soon as this change gets merged.

2022-02-15 02:56 UTC, vkbansal approved these changes

2022-02-15 03:00 UTC, merged