fix: [FFM-1165]: Loader overlay does not cover nav bar
harness/harness-core-ui pull request #7305
Opened 2022-02-11 15:12 UTC by crystal-fong

##### Summary:
Previously the Loading overlay would cover the nav bar. 

##### Jira Links:
https://harness.atlassian.net/browse/FFM-1165

##### Screenshots:
![image](https://user-images.githubusercontent.com/95680496/153616807-afd957a9-1911-43e9-a009-8a2258c947a9.png)

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-11 17:42 UTC, tan-nhu approved these changes

2022-02-14 10:09 UTC, chrisblakely01 requested changes

2022-02-14 10:09 UTC, chrisblakely01 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateVariables/_test_/__snapshots__/TemplateVariables.test.tsx.snap
> +        <div />
I dont think you want this snapshot in here, doesn't look to be part of your stuff

2022-02-14 10:18 UTC, crystal-fong commented on src/modules/72-templates-library/components/TemplateStudio/TemplateVariables/_test_/__snapshots__/TemplateVariables.test.tsx.snap
> +        <div />
the snapshot was failing, even when I checked it locally. So had to update it

2022-02-14 10:24 UTC, chrisblakely01 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateVariables/_test_/__snapshots__/TemplateVariables.test.tsx.snap
> +        <div />
weird, did you run `yarn`? If its still broken we'll call it out as its not our responsibility to fix it (since we don't know what  changed in template studio and if this is the correct snap or not)

2022-02-14 11:22 UTC, crystal-fong commented
trigger cypress

2022-02-14 11:47 UTC, chrisblakely01 submitted a review, later dismissed

2022-02-14 12:06 UTC, knagurski commented
@crystal-fong this issue also effects the Flags listing page

![Flags listing page](https://user-images.githubusercontent.com/7167253/153861358-7e0d068a-0767-4c1d-a6b3-cb353aaeba6e.mp4)

2022-02-15 11:04 UTC, chrisblakely01 approved these changes

2022-02-15 11:18 UTC, knagurski approved these changes
Noice 👍🏻

2022-02-15 11:21 UTC, merged