feat: [CCM-5464]: node recommendation enhancements
harness/harness-core-ui pull request #7325
Opened 2022-02-14 10:08 UTC by rajarshee-harness

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-09 13:13 UTC, rajarshee-harness commented
trigger rebase

2022-03-17 06:47 UTC, rajarshee-harness commented
trigger rebase

2022-03-21 10:03 UTC, jenil-harness requested changes

2022-03-21 10:03 UTC, jenil-harness commented on src/modules/75-ce/components/NodeRecommendation/TuneNodeRecommendationCard.tsx
> +          <Text inline font={{ variation: FontVariation.SMALL }}>{`${getString(
knit: you can define one string and pass variables to it.

2022-03-21 10:32 UTC, rajarshee-harness commented on src/modules/75-ce/components/InstanceFamiliesModalTab/InstanceFamiliesModalTab.module.scss
> +      background-color: rgba(27, 46, 73, 0.02);
We have variables for both the colours but as they have opacity of 0.05 and 0.02 and adding opacity affects the entire component, I am using rgba.

2022-03-21 10:37 UTC, rajarshee-harness commented on src/modules/75-ce/utils/momentUtils.ts
> +  [NodepoolTimeRangeType.LAST_DAY]: [todayInUTC().subtract(1, 'days').startOf('day').format(), todayInUTC().format()],
There were constants for timerange but they didn’t have `LAST_DAY` and I wasn't sure how adding it to them would affect the existing components so defined a new one for nodepool.

2022-03-24 02:32 UTC, rajarshee-harness commented
retrigger typecheck

2022-03-24 02:32 UTC, rajarshee-harness commented
trigger cypress

2022-03-24 03:23 UTC, rajarshee-harness commented
trigger rebase

2022-03-24 05:41 UTC, rajarshee-harness commented
trigger cypress

2022-03-25 04:25 UTC, rajarshee-harness commented
retrigger jest

2022-03-30 09:39 UTC, jenil-harness commented on src/modules/75-ce/pages/node-recommendation-details/NodeRecommendationDetailsPage.tsx
> +            <Text color={Color.GREY_800} font={{ weight: 'semi-bold' }}>
?

2022-03-30 09:45 UTC, rajarshee-harness commented on src/modules/75-ce/pages/node-recommendation-details/NodeRecommendationDetailsPage.tsx
> +            <Text color={Color.GREY_800} font={{ weight: 'semi-bold' }}>
Forgot to edit it while copying the existing component. Will fix this.

2022-03-30 09:45 UTC, rajarshee-harness commented on src/modules/75-ce/components/NodeRecommendation/NodeRecommendation.tsx
> +  const debouncedFetchNewRecomm = useCallback(pDebounce(fetchNewRecommendation, 500), [])
It didn't have a debounce option.

2022-03-31 03:24 UTC, rajarshee-harness commented
trigger rebase

2022-03-31 04:15 UTC, rajarshee-harness commented
trigger cypress

2022-03-31 11:12 UTC, vkbansal approved these changes

2022-03-31 16:47 UTC, abhinavrastogi-harness approved these changes
approving the configs and package.json changes

2022-04-01 05:37 UTC, jenil-harness approved these changes

2022-04-01 05:37 UTC, merged