Hotfix/cdn
harness/harness-core-ui pull request #7342
Opened 2022-02-15 06:59 UTC by mayankVermaHarness

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-17 08:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7342) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7342) before we can accept your contribution.<br/>**24** out of **27** committers have signed the CLA.<br/><br/>:white_check_mark: goyalsonali<br/>:white_check_mark: avinashmadhwani02<br/>:white_check_mark: kapilkumawat86<br/>:white_check_mark: nanaxuHarness<br/>:white_check_mark: bhavya-sinha<br/>:white_check_mark: vardanbansal-harness<br/>:white_check_mark: mtran7<br/>:white_check_mark: deepesh-ui<br/>:white_check_mark: yc147<br/>:white_check_mark: vasuki-kalluri<br/>:white_check_mark: vkbansal<br/>:white_check_mark: crystal-fong<br/>:white_check_mark: knagurski<br/>:white_check_mark: AshwinBhatkal-Harness<br/>:white_check_mark: shashidhargg<br/>:white_check_mark: ishantmehtaharness<br/>:white_check_mark: sean-harness<br/>:white_check_mark: chrisblakely01<br/>:white_check_mark: mayankVermaHarness<br/>:white_check_mark: chris-harness<br/>:white_check_mark: harshilbits<br/>:white_check_mark: jenil-harness<br/>:white_check_mark: sunnykesh-harness<br/>:white_check_mark: praneshg239<br/>:x: samarth-sharma31<br/>:x: swarajcheguri-harness<br/>:x: kylekstewart<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=7342) it.</sub>

2022-03-10 07:26 UTC, mayankVermaHarness commented
retrigger titlecheck

2022-03-10 07:30 UTC, mayankVermaHarness commented
retrigger titlecheck

2022-03-11 07:32 UTC, vkbansal requested changes

2022-03-11 07:32 UTC, vkbansal commented on src/modules/10-common/components/MonacoEditor/MonacoEditor.tsx
> +    const getUrlPrefix = () => {
There is already a function being used by microfrontends: `window.getApiBaseUrl`. it be reused instead of writing a new one?

2022-03-11 07:56 UTC, abhinavrastogi-harness commented on configs/monacoWorkers.webpack.config.js
> +/*
can we rename the file to `webpack.monaco.js`? does that make more or less sense?

2022-03-11 07:56 UTC, abhinavrastogi-harness commented on package.json
>      "watch": "yarn clean && NODE_ENV=development webpack --watch --progress --config configs/webpack.dev.js",
should we add the monaco config here also?

2022-03-11 07:56 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/MonacoEditor/MonacoEditor.tsx
> +      }
in what cases will pathname not end with a `/`?
can we use `path.join()` instead of writing a custom `charAt` check? not sure if we ship `path` package today or not.

2022-03-11 10:08 UTC, mayankVermaHarness commented on configs/monacoWorkers.webpack.config.js
> +/*
yes, since all other webpack files are also named as such `webpack.<context>.js`. Done

2022-03-11 10:12 UTC, mayankVermaHarness commented on src/modules/10-common/components/MonacoEditor/MonacoEditor.tsx
> +      }
I saw a use-case where paths wouldn't always end with a `/`, or even a user could type that in the browser without the trailing slash. Can't rely on user, hence added this as a safety check. 
This is a relatively cheap check and we don't have `path` package in dependencies.

2022-03-11 10:18 UTC, mayankVermaHarness commented on src/modules/10-common/components/MonacoEditor/MonacoEditor.tsx
> +    const getUrlPrefix = () => {
I checked [window.getApiBaseUrl](https://github.com/harness/harness-core-ui/blob/master/src/index.html#L14)—it depends on [API_URL defined in ng-prod-manifests](https://github.com/wings-software/ng-prod-manifests/blob/master/nextgen-ui/values.yaml#L29). The value for `window.apiUrl` is `/gateway`.

As per my understanding, the CDN files need not go through this gateway path—hence we can't use `window.getApiBaseUrl`

2022-03-11 10:20 UTC, mayankVermaHarness commented on package.json
>      "watch": "yarn clean && NODE_ENV=development webpack --watch --progress --config configs/webpack.dev.js",
Yes, adding. Just a general question: what's the `watch` script used for?

2022-03-11 10:27 UTC, abhinavrastogi-harness commented on package.json
>      "watch": "yarn clean && NODE_ENV=development webpack --watch --progress --config configs/webpack.dev.js",
if you are using nginx on local, you can run `yarn watch` to only build ngui, without webpack-dev-server

2022-03-11 10:27 UTC, vkbansal commented on src/modules/10-common/components/MonacoEditor/MonacoEditor.tsx
> +    const getUrlPrefix = () => {
ok

2022-03-11 10:27 UTC, abhinavrastogi-harness commented on src/modules/10-common/components/MonacoEditor/MonacoEditor.tsx
> +      }
sure

2022-03-11 10:27 UTC, abhinavrastogi-harness approved these changes

2022-03-11 10:29 UTC, vkbansal approved these changes

2022-03-11 10:50 UTC, merged