fix: [PL-22728]: Moving HARNESS_ENABLE_NG_AUTH_UI to dev only config
harness/harness-core-ui pull request #7363
Opened 2022-02-16 08:07 UTC by avinashmadhwani02

2022-02-16 11:29 UTC, abhinavrastogi-harness submitted a review, later dismissed

2022-02-16 13:54 UTC, mayankVermaHarness commented on src/index.html
>      <% if (HARNESS_ENABLE_NG_AUTH_UI) { %>
how does `HARNESS_ENABLE_NG_AUTH_UI` have its value hydrated?
IIRC, there should be reference of the same variable in `HTMLWebpackPlugin` in webpack file

2022-02-16 13:56 UTC, avinashmadhwani02 commented on src/index.html
>      <% if (HARNESS_ENABLE_NG_AUTH_UI) { %>
There's a variable in Define Plugin, right? the same way we are using __DEV__

2022-02-17 05:49 UTC, abhinavrastogi-harness requested changes

2022-02-17 05:49 UTC, abhinavrastogi-harness commented on configs/webpack.prod.js
> +      HARNESS_ENABLE_NG_AUTH_UI: false
will this force-disable the flag, even if the env variable is true in SaaS?

2022-02-21 05:40 UTC, avinashmadhwani02 commented on configs/webpack.prod.js
> +      HARNESS_ENABLE_NG_AUTH_UI: false
No this will not, HARNESS_ENABLE_NG_AUTH_UI will be replaced in index.html once the build is generated

2022-02-23 06:33 UTC, abhinavrastogi-harness approved these changes

2022-02-23 06:34 UTC, mayankVermaHarness approved these changes

2022-02-23 08:52 UTC, merged