fix: [PIE-25770]: resizable and draggable support added
harness/harness-core-ui pull request #7404
Opened 2022-02-19 14:06 UTC by samarth-sharma31

##### Summary:

Adds support for resizable and draggable components

##### Jira Links:

https://harness.atlassian.net/browse/CDS-25770

##### Screenshots:

https://user-images.githubusercontent.com/96409598/154804145-c40df51c-590d-4fc3-a8a8-5d1c76da8ef6.mov

https://user-images.githubusercontent.com/96409598/154804148-6aea4227-e6ee-4fe8-b2b4-0da295750deb.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-19 14:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7404) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7404) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=7404) it.</sub>

2022-02-21 05:50 UTC, ishantmehtaharness commented on src/modules/10-common/components/DraggableAndResizableWrapper/DraggableAndResizableWrapper.tsx
> +        topLeft: false
Is it better to make these defaults and take as a prop as well?

2022-02-21 05:50 UTC, kapilkumawat86 requested changes
Use existing packages

2022-02-21 05:52 UTC, ishantmehtaharness approved these changes
Looks Good

2022-02-21 05:54 UTC, ishantmehtaharness commented on package.json
> +    "react-rnd": "^10.3.5",
Not sure if this was discussed with team,
but as a good practice we should discuss this internally with team, before adding any new package to our existing codebase.

2022-02-21 05:57 UTC, samarth-sharma31 commented on package.json
> +    "react-rnd": "^10.3.5",
yes sure, i'll sync with @chiragp1212 on this, @kapilkumawat86 had mentioned that he has used a similar library for this use case

2022-08-01 19:00 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 24 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 24 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/7404)

2022-08-07 19:03 UTC, closed without merging