feat: [PL-22534]: Adding support for adding bitBucket SCM
harness/harness-core-ui pull request #7433
Opened 2022-02-21 16:20 UTC by sunnykesh-harness

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-22 17:48 UTC, avinashmadhwani02 requested changes

2022-02-22 17:48 UTC, avinashmadhwani02 commented on src/modules/10-common/components/ConditionalRenderer/ConditionalRenderer.tsx
> +  return display && children ? <>{children}</> : null
display || children ?

2022-02-22 17:48 UTC, avinashmadhwani02 commented on src/modules/35-user-profile/modals/SourceCodeManager/views/SourceCodeManagerForm.tsx
> +                    <ConditionalRenderer display={allowSCMChange(isEditMode, selected?.value)}>
Children of this component will be evaluated even if the condition is false, we should avoid this practice - it can lead to performance issues. Use the ternary operator instead. 

try adding console.log as it's children, it will be evaluated.

2022-02-22 17:48 UTC, avinashmadhwani02 commented on src/modules/10-common/components/ConditionalRenderer/ConditionalRenderer.tsx
> +const ConditionalRenderer: React.FC<ConditionalRendererProps> = props => {
Why do we need this component?

2022-02-22 17:48 UTC, avinashmadhwani02 commented on src/modules/35-user-profile/modals/SourceCodeManager/views/SourceCodeManagerForm.tsx
> +    // {
Don't we need this now?

2022-02-22 17:48 UTC, avinashmadhwani02 commented on src/modules/35-user-profile/modals/SourceCodeManager/views/SourceCodeManagerForm.tsx
> +    const saved = await saveSourceCodeManager(dataToSubmit)
do we need try catch here?

we should show `howError(getString('userProfile.scmCreateFail'))` error when this API fails

2022-02-22 17:48 UTC, avinashmadhwani02 commented on src/modules/35-user-profile/utils/utils.ts
> +      return Promise.resolve(undefined)
why do we need undefined if the default value of state is {}

2022-02-22 17:57 UTC, avinashmadhwani02 commented on src/modules/35-user-profile/modals/SourceCodeManager/views/SourceCodeManagerForm.tsx
> +                    <ConditionalRenderer display={allowSCMChange(isEditMode, selected?.value)}>
Sandbox example - 

<img width="1136" alt="Screenshot 2022-02-22 at 11 22 27 PM" src="https://user-images.githubusercontent.com/62028553/155191273-945862a3-5509-43f1-b21a-3ac2dc079bbe.png">

2022-02-22 17:57 UTC, sunnykesh-harness commented on src/modules/35-user-profile/modals/SourceCodeManager/views/SourceCodeManagerForm.tsx
> +    // {
no.

2022-02-22 18:10 UTC, sunnykesh-harness commented on src/modules/35-user-profile/utils/utils.ts
> +      return Promise.resolve(undefined)
We do not want to resolve this function to {}. Right now resolve type is Promise<SCMData | undefined> which is better than typecasting {} to SCMData.
Before setting the state we are checking, we get any resolved value or not. This way we will have even 1 less state change and re-render too.

2022-02-22 19:08 UTC, meenakshi-harness commented on src/modules/35-user-profile/modals/SourceCodeManager/views/SourceCodeManagerForm.tsx
> +    // }
Should we remove this unused code?

2022-02-22 19:10 UTC, meenakshi-harness commented on src/modules/35-user-profile/modals/SourceCodeManager/views/SourceCodeManagerForm.tsx
> +  const { mutate: saveSourceCodeManager } = useSaveSourceCodeManagers({})
This api does not take accountId as query param?

2022-02-22 19:15 UTC, meenakshi-harness commented on src/modules/35-user-profile/modals/SourceCodeManager/views/__tests__/SourceCodeManagerForm.test.tsx
> +    expect(container).toMatchSnapshot()
can we avoid snapshots here and assert on the dom elements?

2022-02-22 19:16 UTC, meenakshi-harness commented on src/modules/35-user-profile/utils/utils.ts
> +    // No SCM use these auth types right now
We can remove this code if this is not used instead of commenting.

2022-02-22 19:20 UTC, meenakshi-harness commented on src/modules/35-user-profile/utils/utils.ts
> +export const getDefaultSelected = (type?: SourceCodeTypes): AuthTypes | undefined => {
type should not be an optional param for this util?

2022-02-22 19:37 UTC, sunnykesh-harness commented on src/modules/35-user-profile/modals/SourceCodeManager/views/SourceCodeManagerForm.tsx
> +    // }
No, will be used as we add support for new providers. If we keep uncommented, we will have to write tests for unused code.

2022-02-22 19:40 UTC, sunnykesh-harness commented on src/modules/35-user-profile/utils/utils.ts
> +    // No SCM use these auth types right now
These SCM and authTypes will be used in future so keeping it.

2022-02-22 19:45 UTC, meenakshi-harness commented on src/modules/35-user-profile/utils/utils.ts
> +    // No SCM use these auth types right now
I would say to remove them and add them back when authTypes are supported.

2022-02-22 19:47 UTC, meenakshi-harness commented on src/modules/35-user-profile/modals/SourceCodeManager/views/SourceCodeManagerForm.tsx
> +    // }
I would say to remove them and add them back when authTypes are supported (from git history). So as to avoid committing  commented code to prod.

2022-02-22 19:48 UTC, sunnykesh-harness commented on src/modules/35-user-profile/utils/utils.ts
> +export const getDefaultSelected = (type?: SourceCodeTypes): AuthTypes | undefined => {
Can be but trying to avoid putting extra condition in parent for checking type is there or not. In `CardSelect` while user do a change, no card is selected.

2022-02-23 06:33 UTC, sunnykesh-harness commented on src/modules/35-user-profile/modals/SourceCodeManager/views/__tests__/SourceCodeManagerForm.test.tsx
> +    expect(container).toMatchSnapshot()
Added some explicit DoM asserts too. But will keep snapshots too as it assets all.

2022-02-23 07:33 UTC, sunnykesh-harness commented
retrigger jest

2022-02-23 07:53 UTC, meenakshi-harness approved these changes

2022-02-23 07:56 UTC, avinashmadhwani02 approved these changes

2022-02-23 07:59 UTC, sunnykesh-harness commented
retrigger jest

2022-02-23 08:34 UTC, sunnykesh-harness commented
retrigger coverage

2022-02-23 09:04 UTC, merged