WIP: feat: [FFM-2228]: plan enforcement improvement
harness/harness-core-ui pull request #7451
Opened 2022-02-22 09:57 UTC by crystal-fong

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-22 10:08 UTC, chrisblakely01 commented on src/modules/75-cf/RouteDestinations.tsx
> +  renderMessage: (props, getString, additionalLicenseProps = {}) => {
Think we can move this logic to a custom hook - so we can test it

2022-02-22 10:11 UTC, chrisblakely01 commented on src/modules/75-cf/RouteDestinations.tsx
> +    const monthlyActiveUsers = featuresMap.get(FeatureIdentifier.MAUS)
can you merge line `78/79`?

```suggestion
    const monthlyActiveUsers = props.features.get(FeatureIdentifier.MAUS)
```

Also this number could be `undefined` (for whatever reason) so might want to check for that. I think we cater for 0 below so thats good

2022-02-28 11:59 UTC, crystal-fong commented
retrigger titlecheck

2022-02-28 12:00 UTC, crystal-fong commented
trigger jest

2022-02-28 12:36 UTC, crystal-fong commented on src/modules/75-cf/RouteDestinations.tsx
> +    const monthlyActiveUsers = featuresMap.get(FeatureIdentifier.MAUS)
done

2022-02-28 12:36 UTC, crystal-fong commented on src/modules/75-cf/RouteDestinations.tsx
> +  renderMessage: (props, getString, additionalLicenseProps = {}) => {
moved to a func in a utils file

2022-02-28 16:29 UTC, crystal-fong commented
trigger cypress

2022-03-01 08:56 UTC, crystal-fong commented
trigger cypress

2022-03-01 10:46 UTC, crystal-fong commented
retrigger jest

2022-03-01 10:46 UTC, crystal-fong commented
trigger cypress

2022-03-02 09:34 UTC, chrisblakely01 requested changes
Nice work, just a few more test cases to add and 1/2 minor comments and I think we're good to go

2022-03-02 09:34 UTC, chrisblakely01 commented on src/modules/75-cf/utils/__tests__/UsageLimitUtils.test.ts
> +        'You have used 0.96% of Monthly Active Users (MAU) included in the free plan. After 25K MAUs, flag management will be restricted.'
This message is a bit misleading, as we're not expecting this

```suggestion
        'You have used 99% of Monthly Active Users (MAU) included in the free plan. After 25K MAUs, flag management will be restricted.'
```

2022-03-02 09:34 UTC, chrisblakely01 commented on src/modules/75-cf/utils/__tests__/UsageLimitUtils.test.ts
> +    test('it should return correct message when usage is above 99%', () => {
```suggestion
    test('it should return correct message when usage is 99%', () => {
```

2022-03-02 09:34 UTC, chrisblakely01 commented on src/modules/75-cf/utils/__tests__/UsageLimitUtils.test.ts
> +    test('it should return correct message when usage is above 99%', () => {
```suggestion
    test('it should return correct message when usage is 99%', () => {
```

2022-03-02 09:34 UTC, chrisblakely01 commented on src/modules/75-cf/utils/__tests__/UsageLimitUtils.test.ts
> +describe('Usage Limit Utils', () => {
Nice set of tests, we just need some for when `count = 0` for FREE/team/enterprise and I think we're good

2022-03-02 10:38 UTC, chrisblakely01 approved these changes
HURRAYYYYY

2022-03-02 10:49 UTC, chrisblakely01 commented
trigger cypress

2022-03-02 10:55 UTC, willd0yle approved these changes

2022-03-02 11:07 UTC, knagurski commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  let bannerType!: BannerType
Why the `!` here?

2022-03-02 11:11 UTC, crystal-fong commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  let bannerType!: BannerType
stuck it in there because it made some ts warning go away but it seems to be okay without it so I'll remove it

2022-03-02 11:13 UTC, knagurski commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  const clientMauPlanLimit = Number(limit)
Since `count` and `limit` are optional, passing them through `Number` could result in `NaN` and throw off the rest of the function

2022-03-02 11:18 UTC, chrisblakely01 commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  const clientMauPlanLimit = Number(limit)
it wont throw off the rest of the function as its caught by `clientMauPlanLimit > 0`. `NaN > 0` will return `false`

2022-03-02 11:19 UTC, chrisblakely01 commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  const clientMauPlanLimit = Number(limit)
`count` & `limit` need to be converted to a number as (I think) the types are `any`. Can you suggest a better way to do this?

2022-03-02 11:25 UTC, crystal-fong commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  let bannerType!: BannerType
without it creates
<img width="587" alt="Screenshot 2022-03-02 at 11 17 47" src="https://user-images.githubusercontent.com/95680496/156352857-c3e1d7c1-b5c3-4b0c-a87c-0dfc525d1160.png">

2022-03-02 11:26 UTC, knagurski commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  const clientMauPlanLimit = Number(limit)
The values are used in a couple of calculations before that as well. Instead of letting it do those, you could return early, or detect early in the caller and just not call this function at all (thereby letting you set them as required).
```suggestion
  const clientMauUsageCount = Number(count)
  const clientMauPlanLimit = Number(limit)
  
  if (isNaN(clientMauUsageCount) || isNaN(clientMauPlanLimit)) {
    // return early
  }
```

If if's coz they are typed as `any`, but always are genuinely numbers, then a type assertion is a better option.

2022-03-02 12:16 UTC, knagurski commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  let bannerType!: BannerType
The `!` essentially tells Typescript that you you've got this and don't worry. In other words, it opts out of the type checking here and opens the gate for type errors to sneak in. A better option in this file would be to change the `BannerText` interface to allow these to be optional and just return `{}` if none of the conditions match. In the caller file you need to figure out that those 2 are `undefined` and do what `featureFactory.registerFeaturesByModule` expects in that case.

2022-03-02 12:19 UTC, knagurski commented on src/modules/75-cf/utils/__tests__/UsageLimitUtils.test.ts
> +describe('Usage Limit Utils', () => {
Also with the current ability to omit `count` and `limit` in `getBannerText`, you could do with a test for each individually being `undefined` and for both being `undefined`

2022-03-02 12:25 UTC, chrisblakely01 commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  let bannerType!: BannerType
But you couldn't test that little bit of logic in `featureFactory.registerFeaturesByModule`. Thats why the goal is to encapsulate everything in this function. That being said can you not change BannerText to allow `undefined` for message, bannerType and update the default return at `line 76` to:

```
  return {
    message: undefined
    bannerType: undefined
  }
```

2022-03-02 12:27 UTC, chrisblakely01 commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  let bannerType!: BannerType
Or

```suggestion
  let message?: string
  let bannerType?: BannerType
```

2022-03-02 16:18 UTC, crystal-fong commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  let bannerType!: BannerType
bannerType in `featureFactory.registerFeaturesByModule` can't be undefined, but in other `RouteDestinations` it seems like banners won't render if the string is empty so could just return `bannerType: BannerType.INFO`

2022-03-03 09:08 UTC, crystal-fong commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  let bannerType!: BannerType
removed

2022-03-03 11:48 UTC, knagurski commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  message: string | undefined
You can just mark this as optional. Does the same thing
```suggestion
  message?: string
```

2022-03-03 11:52 UTC, crystal-fong commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  message: string | undefined
done

2022-03-03 11:53 UTC, knagurski commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  }
**TOTALLY OPTIONAL AND MAKES NO DIFFERENCE TO THE FUNCTIONALITY**, but you can swap the logic and simplify a wee bit.

```typescript
if (!isNaN(clientMauPlanLimit) && isNaN(clientMauUsageCount)) {
  // all the other stuff in the function
}

return {
  bannerType: BannerType.INFO
}
```

Note you don't need the `message: undefined` as without it `message` will be literally _undefined_

2022-03-03 11:54 UTC, knagurski commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  }
^ **THIS IS TOTALLY OPTIONAL AND JUST MY OPINION**

2022-03-03 11:57 UTC, knagurski commented on src/modules/75-cf/utils/__tests__/UsageLimitUtils.test.ts
> +      const { message, bannerType } = getBannerText(getString, additionalLicenseProps, count, limit)
Instead of passing `undefined` for these two, you can just not pass them
```suggestion
      const { message, bannerType } = getBannerText(getString, additionalLicenseProps)
```

2022-03-03 12:10 UTC, knagurski commented on src/modules/75-cf/utils/__tests__/UsageLimitUtils.test.ts
> +      const { message, bannerType } = getBannerText(getString, additionalLicenseProps, count, limit)
Here as well, no need to pass `undefined`, just don't define it.
```suggestion
      const { message, bannerType } = getBannerText(getString, additionalLicenseProps, count)
```

2022-03-03 12:36 UTC, crystal-fong commented on src/modules/75-cf/utils/__tests__/UsageLimitUtils.test.ts
> +      const { message, bannerType } = getBannerText(getString, additionalLicenseProps, count, limit)
doneee

2022-03-03 12:37 UTC, crystal-fong commented on src/modules/75-cf/utils/__tests__/UsageLimitUtils.test.ts
> +      const { message, bannerType } = getBannerText(getString, additionalLicenseProps, count, limit)
doneeee

2022-03-03 12:37 UTC, crystal-fong commented on src/modules/75-cf/utils/UsageLimitUtils.ts
> +  }
shimmied em in

2022-03-03 14:03 UTC, chrisblakely01 approved these changes

2022-03-03 15:13 UTC, merged