fix: [CDS-25448]: Showed correct error message on fetching projects
harness/harness-core-ui pull request #7473
Opened 2022-02-23 07:56 UTC by goyalsonali

Summary:

Problem: UI fails at fetching projects in Jira and showed "Failed to fetch:400" message
Solution: Showed the exact message that is coming from BE in jira approval, create and update

 Jira Links:

https://harness.atlassian.net/browse/CDS-25448

Screenshots:

Earlier:
<img width="1292" alt="Screenshot 2022-02-23 at 1 11 24 PM" src="https://user-images.githubusercontent.com/98508399/155279895-2dfe56c6-19c5-4eab-b28a-ad753a0c7d07.png">
<img width="1365" alt="Screenshot 2022-02-23 at 1 11 54 PM" src="https://user-images.githubusercontent.com/98508399/155280009-cfdca9d7-7b94-4267-a42f-4b7bdfbb4a89.png">

Now:
<img width="1258" alt="Screenshot 2022-02-23 at 1 07 25 PM" src="https://user-images.githubusercontent.com/98508399/155279940-873ccbf3-66c5-47db-a315-842080634128.png">
<img width="1364" alt="Screenshot 2022-02-23 at 1 09 49 PM" src="https://user-images.githubusercontent.com/98508399/155279977-d3d9d02b-d306-4853-b6a1-8d18b88646c8.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-02-23 08:34 UTC, goyalsonali commented
trigger cypress

2022-02-23 08:46 UTC, chetanvekariya-harness requested changes

2022-02-23 08:46 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraCreate.module.scss
> +.projectsFetchErrors {
Add some bottom margin here as from screenshots it looks like there is not enough space between error and the next field

2022-02-23 08:46 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraApproval/JiraApproval.module.scss
> +.projectsFetchErrors {
Add some bottom margin here as from screenshots it looks like there is not enough space between error and the next field

2022-02-23 08:49 UTC, goyalsonali commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraApproval/JiraApproval.module.scss
> +.projectsFetchErrors {
Okay. I will do it

2022-02-23 08:49 UTC, goyalsonali commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraCreate.module.scss
> +.projectsFetchErrors {
Okay. I will do it.

2022-02-23 08:55 UTC, chiragp1212 commented
@goyalsonali can we add a tooltip and line clamp on this error? If possible, we should have the error in one line and if it overflows, use the tooltip to show the entire thing. The current screenshot looks too crowded and the BE errors can be even longer than this

2022-02-23 08:58 UTC, goyalsonali commented
> 

Sure, I will look into it.

2022-02-23 17:15 UTC, vkbansal commented
retrigger typecheck

2022-02-23 17:22 UTC, goyalsonali commented
retrigger typecheck

2022-02-24 05:47 UTC, goyalsonali commented
trigger rebase

2022-02-24 06:26 UTC, goyalsonali commented
retrigger typecheck

2022-02-24 06:35 UTC, goyalsonali commented
trigger rebase

2022-02-24 08:36 UTC, goyalsonali commented
retrigger jest

2022-02-24 10:08 UTC, chetanvekariya-harness approved these changes

2022-02-24 10:14 UTC, chiragp1212 approved these changes

2022-02-24 10:52 UTC, vkbansal approved these changes

2022-02-24 10:52 UTC, merged