fix: [CDS-34551]: exporting deployservicestep for gitops
harness/harness-core-ui pull request #7651
Opened 2022-03-03 22:30 UTC by cjlee01

##### Summary:

exporting deployservicestep for gitops to be used in the new app flow

##### Jira Links:

https://harness.atlassian.net/browse/CDS-34551

##### Screenshots:

![image](https://user-images.githubusercontent.com/92757601/156663659-ae897897-6f9c-4dad-b0ad-36434372841f.png)

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-03 22:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7651) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7651) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=7651) it.</sub>

2022-03-03 22:39 UTC, cjlee01 commented
retrigger titlecheck

2022-03-03 22:44 UTC, sahithikolichala submitted a review, later dismissed

2022-03-03 23:08 UTC, cjlee01 commented
retrigger jest

2022-03-04 06:16 UTC, vkbansal commented on src/microfrontends/ChildAppMounter.tsx
> +          customComponents={{ DeployServiceWidget, DeployEnvironmentWidget }}
Please add it here https://github.com/harness/harness-core-ui/blob/a7d2c91d25038f66adc06a4ba7b920d28027ee64/src/modules/75-cd/RouteDestinations.tsx#L416

2022-03-09 07:35 UTC, chiragp1212 approved these changes

2022-03-09 07:44 UTC, abhinavrastogi-harness requested changes

2022-03-09 07:44 UTC, abhinavrastogi-harness commented on src/microfrontends/index.ts
> +export type CustomComponents = Record<string, React.ComponentType<any>>
why are we wrapping the components in "CustomComponents" with forced `any`, which disables typechecking?
why cant we pass the required components directly?

2022-03-09 07:51 UTC, vkbansal commented on src/microfrontends/index.ts
> +export type CustomComponents = Record<string, React.ComponentType<any>>
These custom components can be chosen by the MFE as per their requirements and not required by everyone. `any` is required to make it generic record.

2022-03-09 08:23 UTC, vkbansal commented on src/microfrontends/index.ts
> +export type CustomComponents = Record<string, React.ComponentType<any>>
Example: https://github.com/wings-software/gitops/pull/615

2022-03-10 09:10 UTC, abhinavrastogi-harness approved these changes

2022-03-10 09:10 UTC, abhinavrastogi-harness commented on src/microfrontends/ChildAppMounter.tsx
> +const ChildAppMounterWithRouter = withRouter(ChildAppMounter as any)
why do we need `any` here? it was working without it earlier

2022-03-10 09:44 UTC, vkbansal commented on src/microfrontends/ChildAppMounter.tsx
> +const ChildAppMounterWithRouter = withRouter(ChildAppMounter as any)
After the refactor it's not and I'm unable to figure this out.

2022-03-10 09:44 UTC, vkbansal approved these changes

2022-03-10 09:45 UTC, merged