fix: [CCM-6871]: remove resource type filter on the overview screen recommendation API call
harness/harness-core-ui pull request #7718
Opened 2022-03-08 07:08 UTC by rajarshee-harness

##### Summary:

##### Jira Links:

https://harness.atlassian.net/browse/CCM-6871

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-08 11:52 UTC, rajarshee-harness commented
retrigger standards

2022-03-08 12:19 UTC, rishik30 requested changes

2022-03-08 12:19 UTC, rishik30 commented on src/modules/75-ce/components/OverviewPage/OverviewTopRecommendations.tsx
> +      WORKLOAD: getString('ce.overview.workload'),
let's use `ResourceType` here to be consistent across

2022-03-08 13:20 UTC, rajarshee-harness commented
trigger cypress

2022-03-09 04:57 UTC, jenil-harness approved these changes

2022-03-10 10:39 UTC, rishik30 approved these changes

2022-03-10 11:11 UTC, merged