fix: [CDS-34697]: max height added for text area
harness/harness-core-ui pull request #7729
Opened 2022-03-08 12:08 UTC by samarth-sharma31

##### Summary:

Max height to be added to text area input

##### Jira Links:

https://harness.atlassian.net/browse/CDS-34697

##### Screenshots:

https://user-images.githubusercontent.com/96409598/157234805-26d504b3-a129-48eb-8093-e1ce43cfb588.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-08 12:11 UTC, samarth-sharma31 commented
retrigger titlecheck

2022-03-08 12:12 UTC, samarth-sharma31 commented
retrigger titlecheck

2022-03-08 12:29 UTC, samarth-sharma31 commented
retrigger titlecheck

2022-03-08 14:01 UTC, ishantmehtaharness commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.module.scss
> +    }
Can it be done using className?

2022-03-08 19:29 UTC, samarth-sharma31 commented on src/framework/Templates/TemplateConfigModal/TemplateConfigModal.module.scss
> +    }
Yes, have changed the implementation now. Please review. Thanks!

2022-03-09 06:36 UTC, ishantmehtaharness submitted a review, later dismissed
Looks good now

2022-03-09 06:53 UTC, samarth-sharma31 commented
retrigger jest

2022-03-09 06:53 UTC, samarth-sharma31 commented
retrigger typecheck

2022-03-09 06:54 UTC, samarth-sharma31 commented
trigger cypress

2022-03-09 08:25 UTC, AshwinBhatkal-Harness approved these changes

2022-03-09 08:50 UTC, samarth-sharma31 commented
trigger cypress

2022-03-09 09:22 UTC, yc147 requested changes
Revert changes in src/framework/Templates/TemplateConfigModal/TemplateConfigModal.module.scss. It is not required.

2022-03-09 09:26 UTC, chiragp1212 approved these changes

2022-03-09 09:34 UTC, yc147 approved these changes

2022-03-09 22:04 UTC, samarth-sharma31 commented
trigger rebase

2022-03-10 06:57 UTC, kapilkumawat86 approved these changes

2022-03-10 06:58 UTC, yc147 approved these changes

2022-03-10 06:58 UTC, AshwinBhatkal-Harness approved these changes

2022-03-10 07:00 UTC, merged