fix: [PIE-2999]: land user to yaml view with empty pipeline for empty…
harness/harness-core-ui pull request #7741
Opened 2022-03-09 07:29 UTC by goyalsonali

Summary:

After loading of invalid pipeline, it takes to yaml view directly.

Jira Links:

https://harness.atlassian.net/browse/PIE-2999

Screenshots:

https://user-images.githubusercontent.com/98508399/157393331-05dbd29a-cb02-4d82-9683-7f0b890ba2ef.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-09 07:32 UTC, goyalsonali commented
retrigger titlecheck

2022-03-09 09:57 UTC, goyalsonali commented
trigger cypress

2022-03-09 10:00 UTC, chiragp1212 commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
> +          ...parse(obj.data.yamlPipeline),
this feels incorrect. why would we parse anything that is null?

2022-03-09 12:20 UTC, vkbansal commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
> +      if (yamlPipelineDetails === null) {
if `yamlPipelineDetails` is null then why spread it?

2022-03-09 12:25 UTC, goyalsonali commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
> +      if (yamlPipelineDetails === null) {
I will remove it. There is no need of this.

2022-03-09 13:36 UTC, goyalsonali commented
trigger cypress

2022-03-09 14:11 UTC, goyalsonali commented
trigger cypress

2022-03-09 14:15 UTC, goyalsonali commented
trigger cypress

2022-03-09 15:14 UTC, chetanvekariya-harness requested changes

2022-03-09 15:14 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
> +          yamlPipelineDetails,
Remove this field completely is what @vkbansal meant. **yamlPipelineDetails**  is unknown field, I am not sure why typecheck is not breaking for you or we might not have proper return type given here.

2022-03-09 15:57 UTC, goyalsonali commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
> +          yamlPipelineDetails,
Okay

2022-03-10 03:47 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
> +      } else {
instead of the if else check we can do this:
return {
        ...(yamlPipelineDetails !== null && { ...yamlPipelineDetails.pipeline }),
        gitDetails: obj.data.gitDetails ?? {},
        entityValidityDetails: obj.data.entityValidityDetails ?? {}
      }

2022-03-10 04:31 UTC, goyalsonali commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
> +      } else {
Okay, will update it.
Thank you.

2022-03-10 05:04 UTC, AshwinBhatkal-Harness approved these changes

2022-03-10 05:12 UTC, goyalsonali commented
trigger cypress

2022-03-10 05:12 UTC, vkbansal requested changes

2022-03-10 05:12 UTC, vkbansal commented on src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
> +        ...(yamlPipelineDetails !== null && { ...yamlPipelineDetails.pipeline }),
Please use ternary operator as incase of `true`, it will try to spread `true`, which internally is a `Boolean` object.
```suggestion
        ...(yamlPipelineDetails !== null ? { ...yamlPipelineDetails.pipeline }: {}),
```

2022-03-10 05:25 UTC, vkbansal approved these changes

2022-03-10 06:25 UTC, chetanvekariya-harness approved these changes

2022-03-10 06:27 UTC, merged