feat: [CCM-6959]: GCP UI enhancements
harness/harness-core-ui pull request #7865
Opened 2022-03-16 08:59 UTC by rishik30

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-16 11:35 UTC, rishik30 commented
trigger cypress

2022-03-16 12:55 UTC, rajarshee-harness submitted a review, later dismissed

2022-03-16 13:49 UTC, jenil-harness requested changes

2022-03-16 13:49 UTC, jenil-harness commented on src/modules/75-ce/components/COGatewayConfig/steps/ManageResources/ManageResources.tsx
> +    label: 'GCE VM(s)',
move all the labels to strings.yml

2022-03-16 16:26 UTC, jenil-harness commented on src/modules/75-ce/components/COGatewayConfig/steps/ManageResources/ManageResources.tsx
> +    label: 'GCE VM(s)',
You can pass `getString` function to it. or return string id

2022-03-17 03:27 UTC, jenil-harness submitted a review, later dismissed

2022-03-17 10:23 UTC, rajarshee-harness approved these changes

2022-03-17 12:07 UTC, jyotiarora-harness commented on src/modules/75-ce/components/COGatewayConfig/steps/ResourceFulfilment.tsx
> +    let flag
By default we can keep this flag as false and combine the below cases with OR

2022-03-17 12:09 UTC, rishik30 commented on src/modules/75-ce/components/COGatewayConfig/steps/ResourceFulfilment.tsx
> +    let flag
that was the approach earlier but sonar created an issue for that so boiled down to this.

2022-03-17 12:13 UTC, jyotiarora-harness commented on src/modules/75-ce/components/COGatewayConfig/steps/ResourceFulfilment.tsx
> +    let flag
ok

2022-03-17 12:14 UTC, merged