feat: [PL-23207]: with account id for few API calls
harness/harness-core-ui pull request #7868
Opened 2022-03-16 11:33 UTC by swarajcheguri-harness

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-16 11:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7868) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7868) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=7868) it.</sub>

2022-03-16 13:04 UTC, swarajcheguri-harness commented on src/modules/20-rbac/modals/TokenModal/views/TokenForm.tsx
> +interface SubmitOrCloseBtn {
Made this change to make sonarqube code complexity work

2022-03-16 13:16 UTC, avinashmadhwani02 commented on src/modules/10-common/components/Smtp/views/StepCredentials.tsx
> +              { ...data, uuid, accountId },
We are already passing accountId in pageBody, why do we need it in query params also?

2022-03-17 05:45 UTC, abhinavrastogi-harness commented
@swarajcheguri-harness please see https://harness.slack.com/archives/C02FTLMTQBA/p1647495165445759

instead of adding `accountIdentifier` to each API separately, we can add it at a framework level, and remove `routingId`

2022-03-17 05:45 UTC, abhinavrastogi-harness requested changes
@swarajcheguri-harness please see https://harness.slack.com/archives/C02FTLMTQBA/p1647495165445759

instead of adding accountIdentifier to each API separately, we can add it at a framework level, and remove routingId

2022-03-24 07:10 UTC, abhinavrastogi-harness approved these changes

2022-04-20 10:44 UTC, closed without merging