feat: [CDB-1]: allow moving dashboard between folders
harness/harness-core-ui pull request #7871
Opened 2022-03-16 14:26 UTC by sean-harness

##### Summary:

Add an edit dialog for NG Custom Dashboards home page which allows updating name, folder and tags.

##### Jira Links:

##### Screenshots:

![Screenshot 2022-03-16 at 14 28 26](https://user-images.githubusercontent.com/83951788/158613445-edc6fa67-7573-441f-a8dc-9cf1a802d070.png)
![Screenshot 2022-03-16 at 14 29 20](https://user-images.githubusercontent.com/83951788/158613477-b1906021-439d-445b-a9b0-915472012488.png)

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-17 10:38 UTC, praneshg239 commented
trigger cypress

2022-03-21 10:38 UTC, sean-harness commented
retrigger typecheck

2022-03-22 13:16 UTC, sean-harness commented
retrigger jest

2022-03-23 13:00 UTC, abhinavrastogi-harness requested changes

2022-03-23 13:00 UTC, abhinavrastogi-harness commented on src/modules/45-dashboards/pages/home/CreateDashboardForm.tsx
> +  const { mutate: createDashboard, loading } = useMutate({
why are we not using the restful-react auto-generated service for this endpoint?

2022-03-23 13:00 UTC, abhinavrastogi-harness commented on src/modules/45-dashboards/pages/home/CreateDashboardForm.tsx
> +  const submitForm = async (formData: { name: string; description: string; folderId: string }) => {
no return-type on this function?

2022-03-23 13:00 UTC, abhinavrastogi-harness commented on src/modules/45-dashboards/pages/home/CreateDashboardForm.tsx
> +  const onSuccess = (data: any) => {
why explicit `any`?

2022-03-23 13:00 UTC, abhinavrastogi-harness commented on src/modules/45-dashboards/pages/home/DashboardForm.tsx
> +const DashboardForm = (props: any): JSX.Element => {
why explicit any?
use `React.FC` instead of returning `JSX.Element`

2022-03-23 13:00 UTC, abhinavrastogi-harness commented on src/modules/45-dashboards/pages/home/DashboardForm.tsx
> +    label: 'Organization Shared Folder'
use strings framework

2022-03-23 13:00 UTC, abhinavrastogi-harness commented on src/modules/45-dashboards/pages/home/DashboardForm.tsx
> +  const isMissingFolderId = (folders: any) => !folders.some((item: any) => item.value === props?.formData?.folderId)
why explicit any?

2022-03-23 13:00 UTC, abhinavrastogi-harness commented on src/modules/45-dashboards/pages/home/DashboardForm.tsx
> +            <></>
what is this empty fragment for?

2022-03-23 13:00 UTC, abhinavrastogi-harness commented on src/modules/45-dashboards/pages/home/DashboardForm.tsx
> +                {errorMessage && <Text intent="danger">{errorMessage}</Text>}
we usually use `ModalErrorHandler` or Toaster instead of `Text` to display error messages

2022-03-23 13:00 UTC, abhinavrastogi-harness commented on src/modules/45-dashboards/pages/home/UpdateDashboardForm.tsx
> +const UpdateDashboardForm = (props: any): JSX.Element => {
why any?

2022-03-23 13:00 UTC, abhinavrastogi-harness commented on src/modules/45-dashboards/pages/home/UpdateDashboardForm.tsx
> +  const onSuccess = (data: any) => {
why any?

2022-03-23 13:00 UTC, abhinavrastogi-harness commented on src/modules/45-dashboards/strings/strings.en.yaml
> +  submitFail: 'Edit dashboard failed, Please try again.'
case and grammer looks wrong. can we get this checked?

2022-03-31 14:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7871) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=7871) before we can accept your contribution.<br/>**24** out of **26** committers have signed the CLA.<br/><br/>:white_check_mark: depanshu-dhiman<br/>:white_check_mark: jenil-harness<br/>:white_check_mark: samarth-sharma31<br/>:white_check_mark: avinashmadhwani02<br/>:white_check_mark: Sagar-Rajput7<br/>:white_check_mark: vkbansal<br/>:white_check_mark: PratyushGar<br/>:white_check_mark: reetika04<br/>:white_check_mark: bhavya-sinha<br/>:white_check_mark: nanaxuHarness<br/>:white_check_mark: knagurski<br/>:white_check_mark: vardanbansal-harness<br/>:white_check_mark: crystal-fong<br/>:white_check_mark: rishik30<br/>:white_check_mark: tan-nhu<br/>:white_check_mark: diptiman-adak<br/>:white_check_mark: harshilbits<br/>:white_check_mark: AshwinBhatkal-Harness<br/>:white_check_mark: ishantmehtaharness<br/>:white_check_mark: rajarshee-harness<br/>:white_check_mark: Tamaraius<br/>:white_check_mark: chetanvekariya-harness<br/>:white_check_mark: sean-harness<br/>:white_check_mark: goyalsonali<br/>:x: nataraja2018<br/>:x: swarajcheguri-harness<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=7871) it.</sub>

2022-04-11 10:44 UTC, closed without merging