feat: [CDS-35104]: Added test case for CDS-25549 and removed duplication of code
harness/harness-core-ui pull request #7877
Opened 2022-03-17 08:16 UTC by goyalsonali

Summary:
Jira Links:

https://harness.atlassian.net/browse/CDS-35104

 Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-17 08:17 UTC, goyalsonali commented
retrigger titlecheck

2022-03-17 10:04 UTC, chetanvekariya-harness requested changes

2022-03-17 10:04 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/__tests__/__snapshots__/JiraCreate.test.tsx.snap
> +      Errors
I think your test should render component with some fields properly. It is just rendering Errors here. Please check mocking of data and APIs properly.

2022-03-17 11:04 UTC, goyalsonali commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/__tests__/__snapshots__/JiraCreate.test.tsx.snap
> +      Errors
Okay

2022-03-18 04:05 UTC, chetanvekariya-harness approved these changes

2022-03-18 04:33 UTC, chiragp1212 commented on src/modules/70-pipeline/components/PipelineSteps/Steps/JiraCreate/JiraFieldsRenderer.tsx
> +  const multiType =
Rename to more `meaningful`

2022-03-18 05:23 UTC, chetanvekariya-harness requested changes
We need to change test case, so that it actually automate changes which are done as part of  CDS-25549 ticket.

2022-03-20 11:14 UTC, goyalsonali commented
trigger rebase

2022-03-20 11:16 UTC, goyalsonali commented
trigger rebase

2022-03-20 13:11 UTC, goyalsonali commented
trigger cypress

2022-03-21 06:05 UTC, chiragp1212 approved these changes

2022-03-21 06:23 UTC, chetanvekariya-harness approved these changes

2022-03-21 06:24 UTC, merged