fix: [PIE-3144]: Handle longer policy set name
harness/harness-core-ui pull request #7985
Opened 2022-03-24 14:28 UTC by depanshu-dhiman

##### Summary:

If only single policy added in a set, then try to show it fully without truncating by using the total width of 2 policies.
If more than 2 policies, then cap each policy width at 100px.
Adjust line height because of smaller font size and line clamp issue.
Use proper margin for numeric box.

##### Jira Links:

https://harness.atlassian.net/browse/PIE-3144

##### Screenshots:

<img width="589" alt="Screenshot 2022-03-24 at 7 42 43 PM" src="https://user-images.githubusercontent.com/101629876/159938140-30da9b40-6437-4029-92f3-fc20968ee63b.png">
<img width="604" alt="Screenshot 2022-03-25 at 3 12 09 PM" src="https://user-images.githubusercontent.com/101629876/160096157-8386e847-0aae-4a27-9c98-a16adaeb1a12.png">
<img width="493" alt="Screenshot 2022-03-25 at 3 12 42 PM" src="https://user-images.githubusercontent.com/101629876/160096178-70f12858-5595-46e5-b3b9-6dac4fda133d.png">
<img width="540" alt="Screenshot 2022-03-25 at 3 12 55 PM" src="https://user-images.githubusercontent.com/101629876/160096188-27152092-fac6-434a-a2ec-c333aa343600.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-24 15:24 UTC, devinder-harness requested changes

2022-03-24 15:24 UTC, devinder-harness commented on src/modules/75-cd/components/PipelineSteps/PolicyStep/PolicySets/PolicySetListRenderer/MiniPolicySetRenderer.tsx
> +          className={css.styledPolicy}
`FontVariation` is missing

2022-03-24 15:24 UTC, devinder-harness commented on src/modules/75-cd/components/PipelineSteps/PolicyStep/PolicySets/PolicySetListRenderer/MiniPolicySetRenderer.tsx
> +          style={{ maxWidth: length === 1 ? '240px' : '100px', lineHeight: '1.5em' }}
can we use `classnames`  here?

2022-03-25 09:43 UTC, depanshu-dhiman commented on src/modules/75-cd/components/PipelineSteps/PolicyStep/PolicySets/PolicySetListRenderer/MiniPolicySetRenderer.tsx
> +          style={{ maxWidth: length === 1 ? '240px' : '100px', lineHeight: '1.5em' }}
done

2022-03-25 09:44 UTC, depanshu-dhiman commented on src/modules/75-cd/components/PipelineSteps/PolicyStep/PolicySets/PolicySetListRenderer/MiniPolicySetRenderer.tsx
> +          className={css.styledPolicy}
done, used font size variable in css

2022-03-25 16:29 UTC, AshwinBhatkal-Harness submitted a review, later dismissed

2022-03-25 18:44 UTC, PratyushGar approved these changes

2022-03-28 05:10 UTC, devinder-harness submitted a review, later dismissed

2022-03-28 06:18 UTC, devinder-harness approved these changes

2022-03-28 06:29 UTC, AshwinBhatkal approved these changes

2022-03-28 06:46 UTC, AshwinBhatkal-Harness approved these changes

2022-03-28 07:23 UTC, merged