fix: [CDS-34621]: Infrastructure tab changes for serverless functions
harness/harness-core-ui pull request #8005
Opened 2022-03-25 09:48 UTC by satyam-harness

##### Summary:

##### Jira Links:

https://harness.atlassian.net/jira/software/c/projects/PIE/boards/287?modal=detail&selectedIssue=CDS-34621

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-25 10:00 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/GcpInfrastructureSpec/GcpInfrastructureSpec.tsx
> -
Remove this file from changed.

2022-03-25 10:16 UTC, chetanvekariya-harness requested changes

2022-03-25 10:16 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/PipelineStepsUtil.ts
> +  ServerlessGCPLambda = 'ServerlessGCPLambda',
Change **ServerlessGCPLambda** to **ServerlessGoogleFunctions**
Change **ServerlessAzureLambda** to **ServerlessAzureFunctions**

2022-03-25 10:16 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/ServerlessAwsLambdaSpec.tsx
> +      return Yup.object().test({
This is not needed. This fields is of string type always.

2022-03-25 10:16 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/ServerlessAwsLambdaSpec.tsx
> +      return Yup.object().test({
This is not needed. This fields is of string type always.

2022-03-25 10:16 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/SelectInfrastructureType/SelectInfrastructureType.tsx
> +              label: getString('pipelineSteps.deploymentTypes.gcp'),
disable this option

2022-03-25 10:16 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/SelectInfrastructureType/SelectInfrastructureType.tsx
> +              label: getString('pipelineSteps.deploymentTypes.azure'),
disable this one

2022-03-25 10:16 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
> +  const deploymentType = getDeploymentType(
rename this to **selectedDeploymentType**

2022-03-25 10:16 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
> +    newDeploymentType: string | undefined
revert this change and keep the way it was - `deploymentType `

2022-03-25 10:16 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
>              selectedInfrastructureType={selectedDeploymentType}
rename **selectedDeploymentType** to **selectedInfrastructureType**

2022-03-25 10:16 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
> +            deploymentType={deploymentType}
Once renamed at the top, pass **selectedDeploymentType** here.

2022-03-25 10:16 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/ServerlessAwsLambdaSpec.tsx
> +    if (
remove code from this function for the fields which are not supported in serverless

2022-03-25 10:16 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/ServerlessAwsLambdaSpec.tsx
> +  //   useEffect(() => {
Remove commented code if not needed later.

2022-03-25 10:50 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
> +  const deploymentType = getDeploymentType(
already there is a state of same name

2022-03-25 10:50 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
> +    newDeploymentType: string | undefined
there was an unusual error happening, thats why changed it

2022-03-25 10:55 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
> +  const deploymentType = getDeploymentType(
done

2022-03-25 11:33 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
> +    newDeploymentType: string | undefined
That was happening because you has same variable in parent scope which you changed now. So, should work.

2022-03-28 06:11 UTC, chetanvekariya-harness requested changes

2022-03-28 06:11 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
> +    // const type = stage?.stage?.spec?.infrastructure?.infrastructureDefinition?.type
Remove this if not needed.

2022-03-28 06:11 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/SelectInfrastructureType/SelectInfrastructureType.tsx
>  export default function SelectDeploymentType(props: SelectDeploymentTypeProps): JSX.Element {
While we are here, could you please rename this file ?

2022-03-28 06:11 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/SelectInfrastructureType/SelectInfrastructureType.tsx
> +          groupLabel: '',
We should create these tiles as groups. They should be render in one line without any group.

2022-03-28 06:11 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
> +  SERVERLESS_SUPPORT = true
Why is this changed ?

2022-03-28 06:11 UTC, chetanvekariya-harness commented on src/services/cd-ng/index.tsx
> +export type ServerlessGCPInfrastructure = Infrastructure & {
This looks like manual change. Remove it. Or generate services by running BE locally.

2022-03-29 06:44 UTC, chetanvekariya-harness requested changes

2022-03-29 06:44 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/ServerlessAwsLambdaSpec.tsx
> +  cluster?: { label?: string; value?: string } | string | any
We do not have cluster in Serverless. Remove this and use **ServerlessAwsLambdaInfrastructure** directly.

2022-03-29 06:44 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/ServerlessAwsLambdaSpec.tsx
> +  const getInitialValues = (): ServerlessAwsLambdaInfrastructureUI => {
This functions is useless, not doing anything at all. Please remove it.

2022-03-29 06:44 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/ServerlessAwsLambdaSpec.tsx
> +                    dataTooltipId: 'gcpInfraConnector'
Give other unique dataTooltipId here.

2022-03-29 06:46 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/ServerlessAwsLambdaSpec.tsx
> +  cluster?: { label?: string; value?: string } | string | any
ohh i have removed these things, code is not pushed i guess, give me 2 mins

2022-03-29 07:48 UTC, satyam-harness commented
retrigger titlecheck

2022-03-29 08:14 UTC, satyam-harness commented
retrigger standards

2022-03-29 08:20 UTC, satyam-harness commented
retrigger sonar

2022-03-30 06:25 UTC, satyam-harness commented
retrigger typecheck

2022-03-31 07:32 UTC, closed without merging