Ffm 1784
harness/harness-core-ui pull request #8043
Opened 2022-03-28 13:40 UTC by chrisblakely01

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-29 07:20 UTC, chrisblakely01 commented
trigger cypress

2022-03-29 09:24 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
> +  const variationPercentageRollout = featureFlagData.envProperties?.rules?.find(rule => rule.serve.distribution)
Does this just look for the first rule with a `distribution`?

2022-03-29 09:34 UTC, kylekstewart submitted a review, later dismissed

2022-03-29 09:45 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
> +  const variationPercentageRollout = featureFlagData.envProperties?.rules?.find(rule => rule.serve.distribution)
yep, there's no other obvious way to pick out percentage rollout from the rules that I can see - but open to ideas 👍

2022-03-29 10:04 UTC, willd0yle approved these changes

2022-03-29 10:19 UTC, crystal-fong commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
> +                      ruleId: uuid(),
is variation.identifier not unique enough to use instead of uuid()?

2022-03-29 10:21 UTC, crystal-fong commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/components/flag-enabled-rules-card/FlagEnabledRulesCard.tsx
> +                  data-testid={`remove_percentage_rollout`}
why is this in backticks?

2022-03-29 10:25 UTC, knagurski requested changes
Overall fantastic work, but I think the requirement for this to be a repeating field was missed 😞

2022-03-29 10:25 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/Types.types.ts
> +  targets: TargetMap[] | []
Why the `| []`?

2022-03-29 10:25 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/components/flag-enabled-rules-card/FlagEnabledRulesCard.tsx
> +                  data-testid={`remove_percentage_rollout`}
```suggestion
                  data-testid="remove_percentage_rollout"
```

2022-03-29 10:25 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/components/flag-enabled-rules-card/FlagEnabledRulesCard.tsx
> +                      data-testid={`variation_option_percentage_rollout`}
```suggestion
                      data-testid="variation_option_percentage_rollout"
```

2022-03-29 10:25 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/hooks/PatchFeatureFlagUtils.ts
> +    )[0].targetGroups
Will the `filter` ALWAYS return a result?

2022-03-29 10:25 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/hooks/PatchFeatureFlagUtils.ts
> +          .map(intialTargetGroup => intialTargetGroup.identifier)
SUPER pedantic, so please feel free to ignore, but this would be a great place for destructuring
```suggestion
          .map(({ identifier }) => identifier)
```

2022-03-29 10:25 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/hooks/PatchFeatureFlagUtils.ts
> +    )[0].targetGroups
Again, will the `filter` ALWAYS result in at least one row?

2022-03-29 10:25 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/hooks/PatchFeatureFlagUtils.ts
> +    const intialTargetIds = formVariation.targets.map((target: TargetMap) => target.identifier)
Misspelling
```suggestion
    const initialTargetIds = formVariation.targets.map((target: TargetMap) => target.identifier)
```

2022-03-29 10:25 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/hooks/PatchFeatureFlagUtils.ts
> +    const intialTargetIds = formVariation.targets.map((target: TargetMap) => target.identifier)
Here too
```suggestion
    const initialTargetIds = formVariation.targets.map((target: TargetMap) => target.identifier)
```

2022-03-29 10:25 UTC, knagurski commented on src/modules/75-cf/strings/strings.en.yaml
> +    onRequestVariation: On Request, check for condition and serve variation'
Trailing quote
```suggestion
    onRequestVariation: On Request, check for condition and serve variation
```

2022-03-29 10:46 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
> +                      ruleId: uuid(),
nope, variation.identifier is like "true" "false" etc. We need to generate a UUID clientside for this rule (BE doesn't do it for some reason)

2022-03-29 10:50 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
>    const formVariationMap: FormVariationMap[] = featureFlagData.variations.map(variation => {
yeah I would like to rename it, but maybe towards the end of the epic as theres alot of places its used lol

2022-03-29 10:52 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
> +                          .flatMap(x => x.weight)
good catch, changed to `map`

2022-03-29 10:52 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
> +      validateYupSchema(
having to work in the weight totals validation was extra fun!

2022-03-29 10:55 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
> +        yup.object().shape({
will change, to reduce the amount of stuff in this schema

2022-03-29 10:55 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
> +    initialValues: initialValues,
fixed

2022-03-29 10:57 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
> +                style={{ overflowY: 'auto' }}
fixed

2022-03-29 10:59 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/Types.types.ts
> +  targets: TargetMap[] | []
leftover from a first cut - fixed

2022-03-29 11:00 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/hooks/PatchFeatureFlagUtils.ts
> +    )[0].targetGroups
should do, but I'll change this to use `find` to be safe

2022-03-29 11:02 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/hooks/PatchFeatureFlagUtils.ts
> +          .map(intialTargetGroup => intialTargetGroup.identifier)
fixed

2022-03-29 11:02 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/hooks/PatchFeatureFlagUtils.ts
> +    )[0].targetGroups
should do, but I'll change this to use find to be safe

2022-03-29 11:03 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/hooks/PatchFeatureFlagUtils.ts
> +    const intialTargetIds = formVariation.targets.map((target: TargetMap) => target.identifier)
doh - fixed

2022-03-29 11:04 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/hooks/PatchFeatureFlagUtils.ts
> +    const intialTargetIds = formVariation.targets.map((target: TargetMap) => target.identifier)
fixed

2022-03-29 11:04 UTC, chrisblakely01 commented on src/modules/75-cf/strings/strings.en.yaml
> +    onRequestVariation: On Request, check for condition and serve variation'
fixed

2022-03-29 12:43 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
> +                      ruleId: uuid(),
It doesn't actually need to be totally unique, it only has to be unique within the rules for this specific flag, not all flags. Something as simple as a prefix might be enough. `uuid` is fine too

2022-03-30 11:18 UTC, chrisblakely01 commented
retrigger jest

2022-03-30 11:50 UTC, crystal-fong approved these changes
🔥

2022-03-31 09:55 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/data/expectedFormValues.ts
> +import type { TargetingRulesFormValues } from '../../Types.types'
I'm just thinking... with this (i.e. `expectedFormValues.ts`) just being a `.ts` file, it'll probably get pulled into the coverage metrics. If you change to `expectedFormValues.mocks.ts`, it'll get ignored.

2022-03-31 09:57 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/components/add-targeting-button/AddTargetingButton.tsx
> +          </Text>
Need to swap these for buttons.

2022-03-31 10:28 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/TargetingRulesTab.tsx
> +                    formikProps.setFieldValue(`variationPercentageRollouts`, percentageRollouts)
Thanks for suggestion - I'll likely be revisiting this as part of the rule ordering ticket I've got coming up, so I can look into changing that then 👍

2022-03-31 10:29 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/data/expectedFormValues.ts
> +import type { TargetingRulesFormValues } from '../../Types.types'
Filename is `Types.types.ts` (🙃) and I think `.types.ts`  extentions are excluded from code coverage (its not showing up as low coverage anyway)

2022-03-31 10:29 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/components/add-targeting-button/AddTargetingButton.tsx
> +          </Text>
yep, I've actually done this as part of my other ticket (still in flight)

2022-03-31 10:46 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/data/expectedFormValues.ts
> +import type { TargetingRulesFormValues } from '../../Types.types'
Not this line, this file (GH doesn't allow general file comments).

2022-03-31 10:57 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/components/flag-enabled-rules-card/FlagEnabledRulesCard.tsx
>  import SpecificTargetingItem from '../specific-targeting-item.tsx/SpecificTargetingItem'
Not your code, but does this directory really have a file extension?! 🤯

2022-03-31 11:07 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/data/expectedFormValues.ts
> +import type { TargetingRulesFormValues } from '../../Types.types'
ah I understand. Will change

2022-03-31 11:09 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/components/flag-enabled-rules-card/FlagEnabledRulesCard.tsx
>  import SpecificTargetingItem from '../specific-targeting-item.tsx/SpecificTargetingItem'
lol this is from a previous PR. I named the folder with a `tsx`. Yeno, just to be extra clear its a TSX stuff inside 🤓  - will fix

2022-03-31 11:12 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/data/expectedFormValues.ts
> +import type { TargetingRulesFormValues } from '../../Types.types'
Actually, this is all within the test folder and it isn't being picked up in code metrics. Everything is 95%+ apart from `FlagActivation` which is causing this PR to miss the thresholds

2022-03-31 11:12 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/components/flag-enabled-rules-card/FlagEnabledRulesCard.tsx
> +              segments={segments}
We need to be careful and not allow conflicting rules to be able to be created. A user shouldn't be able to create a percentage rollout for a target group they already have a variation rule for, and vice versa. Also they shouldn't be able to create 2 variation rules that target the same group, or 2 percentage rollout rules that target the same group. The backend will take them, but they can get the user in a weird state.

2022-03-31 11:13 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/components/percentage-rollout-item/PercentageRolloutItem.tsx
> +          onClick={() => removePercentageRollout(index)}
This button is within the form, so you might wanna kill the event.

2022-03-31 11:18 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/components/percentage-rollout-item/PercentageRolloutItem.tsx
> +        data-testid={`percentage_rollout_item_${index}`}
Do we only need this container to get a `testid` in? Might be worth changing `PercentageRollout` to accept extra props to be spread onto the container within the component.

2022-03-31 11:33 UTC, chrisblakely01 commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/components/flag-enabled-rules-card/FlagEnabledRulesCard.tsx
> +              segments={segments}
theres a ticket upcoming to handle this

2022-03-31 11:45 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/TargetingRulesTab.test.tsx
> +      await waitFor(() => expect(targetGroupInputList).toBeInTheDocument())
I see this is just tidied up code, but this will either work on the first pass or always fail. The `document.querySelector` call only happens once and is a snapshot of things when it was called, so if it turns up after the call, it won't be picked up in the `waitFor`.
```suggestion

      await waitFor(() => expect(screen.getByRole('list').toBeInTheDocument())
      
```

2022-03-31 11:49 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/TargetingRulesTab.test.tsx
> +      expect(document.querySelectorAll('li')[4]).toHaveTextContent(/target_group_3/)
Again, I know it's tidied up code, but this is a bit wasteful.
```suggestion
      
      const listItems = screen.getAllByRole('listitem')
      
      expect(listItems[0]).toHaveTextContent(/target_group_5/)
      expect(listItems[1]).toHaveTextContent(/target_group_4/)
      expect(listItems[2]).toHaveTextContent(/target_group_1/)
      expect(listItems[3]).toHaveTextContent(/target_group_2/)
      expect(listItems[4]).toHaveTextContent(/target_group_3/)
```

2022-03-31 11:57 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/TargetingRulesTab.test.tsx
> +      await waitFor(() => expect(percentageRolloutOption).toBeInTheDocument())
This will either succeed or throw an error before the `waitFor` is reached. You might want to try `findBy` here instead of `getBy`
```suggestion

      const percentageRolloutOption = await screen.findByTestId('variation_option_percentage_rollout')

```

2022-03-31 11:59 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/TargetingRulesTab.test.tsx
> +    test('it should render percentage rollout correctly when not present', () => {
This is a pretty weird test description. Rendering correctly in this case is not rendering at all.
```suggestion
    test('it should not render percentage rollout when not present', () => {
```

2022-03-31 12:00 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/TargetingRulesTab.test.tsx
> +      expect(screen.queryByText('cf.featureFlags.percentageRollout')).not.toBeInTheDocument()
Might be worth asserting that it existed before the click as well to prove it did something

2022-03-31 12:02 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/TargetingRulesTab.test.tsx
> +      await waitFor(() => expect(percentageRolloutOption).toBeInTheDocument())
As above...
```suggestion
      const percentageRolloutOption = await screen.findByTestId('variation_option_percentage_rollout')
```

2022-03-31 12:09 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/TargetingRulesTab.test.tsx
> +    test('it should call saveChanges with correct data on save', async () => {
Wow, that's some test, but easy to follow and exercises the form nicely. Great job!

2022-03-31 12:15 UTC, knagurski commented on src/modules/75-cf/pages/feature-flags-detail/targeting-rules-tab/__tests__/data/expectedFormValues.ts
> +import type { TargetingRulesFormValues } from '../../Types.types'
Nice! They must've changed it, or maybe the rule I was hit with was for new files only.

2022-03-31 12:19 UTC, knagurski approved these changes
DAAAAAAMMMMMNNNNN!!! A lot of work went into this. Great job. Just a few suggestions/opinions, plus the a11y button issue and conflicting rules stuff (which you're handling in another ticket). If everything still works when the flag is off, then I think you're good to go!

2022-03-31 15:11 UTC, merged