feat: [PL-23322]: PreferenceFramework to retain scoped preferences in localStorage
harness/harness-core-ui pull request #8061
Opened 2022-03-29 12:05 UTC by mayankVermaHarness

##### Summary:

##### Jira Links:

https://harness.atlassian.net/browse/PL-23322

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-29 12:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=8061) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=8061) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mayankVermaHarness<br/>:x: bot-harness<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=8061) it.</sub>

2022-03-30 15:32 UTC, avinashmadhwani02 requested changes

2022-04-14 09:31 UTC, diptiman-adak commented on src/modules/10-common/utils/testUtils.tsx
> +      <StringsContext.Provider value={{ data: stringsData as any, getString }}>
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232308)
```suggestion
    <StringsContext.Provider value={{ data: stringsData as unknown, getString }}>
```

2022-04-18 08:50 UTC, diptiman-adak commented on src/modules/10-common/utils/testUtils.tsx
> +      <StringsContext.Provider value={{ data: stringsData as any, getString }}>
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232308)
```suggestion
    <StringsContext.Provider value={{ data: stringsData as unknown, getString }}>
```

2022-04-18 08:50 UTC, diptiman-adak commented on src/framework/PreferenceStore/PreferenceStoreContext.tsx
> +  const getPreference = (key: string, options?: PreferenceStoreOptions): any => {
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232308)
```suggestion
  const getPreference = (key: string, options?: PreferenceStoreOptions): unknown => {
```

2022-04-18 08:50 UTC, diptiman-adak commented on src/framework/PreferenceStore/PreferenceStoreContext.tsx
> +export const PreferenceStoreContext = React.createContext<PreferenceStoreProps<any>>({
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232308)
```suggestion
export const PreferenceStoreContext = React.createContext<PreferenceStoreProps<unknown>>({
```

2022-04-18 08:50 UTC, diptiman-adak commented on src/framework/PreferenceStore/__tests__/PreferenceStoreContext.test.tsx
> +  }, [])
Codacy has a fix for the issue: [React Hook useEffect has a missing dependency: 'updatePreferenceStore'. Either include it or remove the dependency array.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232308)
```suggestion
  }, [updatePreferenceStore])
```

2022-04-18 09:13 UTC, mayankVermaHarness commented
retrigger build

2022-04-19 20:07 UTC, mayankVermaHarness commented
trigger rebase

2022-04-20 14:14 UTC, mayankVermaHarness commented
trigger cypress

2022-05-04 06:57 UTC, avinashmadhwani02 commented on src/framework/AppStore/AppStoreContext.tsx
> +  } = usePreferenceStore<SavedProjectDetails>(PreferenceScope.USER, 'savedProject')
`savedProject` can be moved to a constant file

2022-05-08 16:21 UTC, avinashmadhwani02 approved these changes

2022-05-09 05:03 UTC, sunnykesh-harness approved these changes

2022-05-09 06:53 UTC, abhinavrastogi-harness commented
retrigger jest

2022-05-09 09:06 UTC, merged