fix: [CDS-35689]: Testcases for severlessAwsLambda step
harness/harness-core-ui pull request #8080
Opened 2022-03-30 09:07 UTC by satyam-harness

##### Summary:

##### Jira Links:
https://harness.atlassian.net/browse/CDS-35689

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-03-31 16:49 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/__test__/ServerlessAwsLambdaSpec.test.tsx
> +      // TODO: add other fields
Address this TODO in next PR.

2022-03-31 16:49 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/__test__/ServerlessAwsLambdaSpec.test.tsx
> +      await ref.current?.submitForm()
May be, we do not have Submit button under this component. If it is there then click on button and submit form.

2022-03-31 16:52 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/__test__/mock/ConnectorsResponse.mock.ts
> +export const ConnectorsResponse = {
Create just one file for Connector responses under mock folder and keep all connector responses in that file.

2022-03-31 17:00 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
> +    const initialInfraDefValues = getInfrastructureDefaultValue(stage, infrastructureType)
Earlier, **stage?.stage?.spec?.infrastructure?.infrastructureDefinition?.type** was passed to **getInfrastructureDefaultValue** as second argument.
Now, you are passing **deploymentTypeInfraTypeMap[stage?.stage?.spec?.serviceConfig?.serviceDefinition?.type]**
Hope that is expected

2022-03-31 17:04 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/deployInfraHelper.tsx
> +  deploymentType: string | undefined
Change in next PR - This variable name should be **infrastructureType**

2022-03-31 17:05 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
> +  SERVERLESS_SUPPORT = true
**Too dangerous** - Please revert this change. I had a comment for this earlier as well,

2022-03-31 17:07 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployStageSetupShell/__tests__/__snapshots__/DeployStageSetupShell.test.tsx.snap
> +                        <span
This change should not appear if there is no corresponding change in test file.

2022-03-31 17:08 UTC, chetanvekariya-harness commented on src/modules/75-cd/strings/strings.en.yaml
> +    regionError: No region found with given Connector
Is this change intended ? regionError and stageError

2022-03-31 17:10 UTC, chetanvekariya-harness requested changes
Need to revert default value of feature flag. We can address other comments as well along with it.

2022-04-01 05:27 UTC, chetanvekariya-harness commented on src/modules/75-cd/strings/strings.en.yaml
> +    regionError: No region found with given Connector
Fixed.

2022-04-01 05:27 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployStageSetupShell/__tests__/__snapshots__/DeployStageSetupShell.test.tsx.snap
> +                        <span
Fixed.

2022-04-01 05:27 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/SelectDeploymentType.tsx
> +  SERVERLESS_SUPPORT = true
Fixed.

2022-04-01 05:27 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/deployInfraHelper.tsx
> +  deploymentType: string | undefined
Fixed,

2022-04-01 05:27 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAWSLambda/__test__/mock/ConnectorsResponse.mock.ts
> +export const ConnectorsResponse = {
Fixed.

2022-04-01 06:46 UTC, chetanvekariya-harness approved these changes

2022-04-01 08:53 UTC, kapilkumawat86 approved these changes

2022-04-01 09:45 UTC, merged