feat: [CDS-35302]: ssh connector creation wizard
harness/harness-core-ui pull request #8104
Opened 2022-03-31 12:46 UTC by azharness

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-13 19:54 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/components/UploadJSON.tsx
> +              handleFileUpload(file as any)
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
              handleFileUpload(file as unknown)
```

2022-04-13 19:54 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/StepDetails/PdcDetails.tsx
> +          setManualTypedHosts(props.connectorInfo?.spec?.hosts?.map?.((host: any) => host.hostname).join('\n'))
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
          setManualTypedHosts(props.connectorInfo?.spec?.hosts?.map?.((host: unknown) => host.hostname).join('\n'))
```

2022-04-13 19:54 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/components/UploadJSON.tsx
> +        onChange={event => handleFileUpload((event.target as any).files[0])}
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
        onChange={event => handleFileUpload((event.target as unknown).files[0])}
```

2022-04-13 19:54 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/components/UploadJSON.tsx
> +  }, [fileContent])
Codacy has a fix for the issue: [React Hook useEffect has a missing dependency: 'setJsonValue'. Either include it or remove the dependency array. If 'setJsonValue' changes too often, find the parent component that defines it and wrap that definition in useCallback.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
  }, [fileContent, setJsonValue])
```

2022-04-13 19:54 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/StepDetails/PdcDetails.tsx
> +  }, [])
Codacy has a fix for the issue: [React Hook useEffect has a missing dependency: 'prevStepData?.hosts'. Either include it or remove the dependency array.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
  }, [prevStepData?.hosts])
```

2022-04-13 21:11 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/components/UploadJSON.tsx
> +              handleFileUpload(file as any)
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
              handleFileUpload(file as unknown)
```

2022-04-13 21:12 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/StepDetails/TestConnection.tsx
> +  const steps: string[] = useMemo(() => [getString('connectors.pdc.testConnection.step1')], [])
Codacy has a fix for the issue: [React Hook useMemo has a missing dependency: 'getString'. Either include it or remove the dependency array.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
  const steps: string[] = useMemo(() => [getString('connectors.pdc.testConnection.step1')], [getString])
```

2022-04-13 21:12 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/StepDetails/PdcDetails.tsx
> +  }, [])
Codacy has a fix for the issue: [React Hook useEffect has a missing dependency: 'prevStepData?.hosts'. Either include it or remove the dependency array.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
  }, [prevStepData?.hosts])
```

2022-04-13 21:12 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/StepDetails/TestConnection.tsx
> +  }, [])
Codacy has a fix for the issue: [React Hook useEffect has a missing dependency: 'verifyTestConnection'. Either include it or remove the dependency array.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
  }, [verifyTestConnection])
```

2022-04-14 19:27 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/StepDetails/TestConnection.tsx
> +  }, [])
Codacy has a fix for the issue: [React Hook useEffect has a missing dependency: 'verifyTestConnection'. Either include it or remove the dependency array.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
  }, [verifyTestConnection])
```

2022-04-14 19:27 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/components/UploadJSON.tsx
> +              handleFileUpload(file as any)
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
              handleFileUpload(file as unknown)
```

2022-04-14 19:27 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/StepDetails/PdcDetails.tsx
> +  }, [])
Codacy has a fix for the issue: [React Hook useEffect has a missing dependency: 'prevStepData?.hosts'. Either include it or remove the dependency array.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
  }, [prevStepData?.hosts])
```

2022-04-14 19:27 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/StepDetails/PdcDetails.tsx
> +      hosts: typeof hosts === 'string' ? hosts : hosts?.map?.((host: any) => host.hostname).join('\n')
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
      hosts: typeof hosts === 'string' ? hosts : hosts?.map?.((host: unknown) => host.hostname).join('\n')
```

2022-04-14 19:27 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/components/UploadJSON.tsx
> +        onChange={event => handleFileUpload((event.target as any).files[0])}
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
        onChange={event => handleFileUpload((event.target as unknown).files[0])}
```

2022-04-15 13:07 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/components/UploadJSON.tsx
> +        onChange={event => handleFileUpload((event.target as any).files[0])}
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
        onChange={event => handleFileUpload((event.target as unknown).files[0])}
```

2022-04-15 13:07 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/StepDetails/TestConnection.tsx
> +  }, [])
Codacy has a fix for the issue: [React Hook useEffect has a missing dependency: 'verifyTestConnection'. Either include it or remove the dependency array.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
  }, [verifyTestConnection])
```

2022-04-18 15:15 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/StepDetails/PdcDetails.tsx
> +      hosts: typeof hosts === 'string' ? hosts : hosts?.map?.((host: any) => host.hostname).join('\n')
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
      hosts: typeof hosts === 'string' ? hosts : hosts?.map?.((host: unknown) => host.hostname).join('\n')
```

2022-04-18 15:15 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/components/UploadJSON.tsx
> +        onChange={event => handleFileUpload((event.target as any).files[0])}
Codacy has a fix for the issue: [Unexpected any. Specify a different type.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
        onChange={event => handleFileUpload((event.target as unknown).files[0])}
```

2022-04-18 15:15 UTC, diptiman-adak commented on src/modules/35-connectors/components/CreateConnector/PdcConnector/StepDetails/TestConnection.tsx
> +  }, [])
Codacy has a fix for the issue: [React Hook useEffect has a missing dependency: 'verifyTestConnection'. Either include it or remove the dependency array.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232306)
```suggestion
  }, [verifyTestConnection])
```

2022-05-12 13:35 UTC, azharness commented
retrigger jest

2022-05-12 15:44 UTC, azharness commented
retrigger jest

2022-05-16 08:11 UTC, azharness commented
retrigger coverage

2022-05-17 08:47 UTC, azharness commented
retrigger coverage

2022-05-17 08:48 UTC, azharness commented
retrigger jest

2022-05-17 09:46 UTC, azharness commented
retrigger coverage

2022-05-17 13:26 UTC, azharness commented
retrigger jest

2022-05-17 13:29 UTC, azharness commented
retrigger coverage

2022-05-17 13:40 UTC, azharness commented
retrigger coverage

2022-05-17 14:49 UTC, azharness commented
retrigger jest

2022-05-17 16:38 UTC, azharness commented
retrigger coverage

2022-05-18 15:36 UTC, azharness commented
retrigger coverage

2022-05-20 14:57 UTC, azharness commented
retrigger jest

2022-05-20 15:05 UTC, azharness commented
retrigger coverage

2022-05-20 15:47 UTC, azharness commented
retrigger jest

2022-05-23 07:15 UTC, Tamaraius approved these changes

2022-05-23 07:36 UTC, azharness commented
retrigger jest

2022-05-23 07:38 UTC, azharness commented
trigger cypress

2022-05-23 07:38 UTC, azharness commented
retrigger cypress

2022-05-23 13:52 UTC, azharness commented
retrigger jest

2022-05-23 14:40 UTC, Tamaraius approved these changes

2022-05-24 07:01 UTC, azharness commented
trigger rebase

2022-05-24 07:01 UTC, azharness commented
trigger rebase

2022-05-24 07:24 UTC, azharness commented
retrigger jest

2022-05-24 07:41 UTC, azharness commented
retrigger cypress

2022-05-24 08:20 UTC, azharness commented
retrigger jest

2022-05-24 08:52 UTC, Tamaraius submitted a review, later dismissed

2022-05-24 08:57 UTC, kapilkumawat86 requested changes
Fix cypress test case, since its broken after your change only

2022-05-24 09:40 UTC, azharness commented
trigger cypress

2022-05-24 10:05 UTC, azharness commented
retrigger jest

2022-05-24 10:36 UTC, azharness commented
retrigger jest

2022-05-24 11:39 UTC, merged