fix: [PL-21099]: Connector details page tab view based on query params and added …
harness/harness-core-ui pull request #8128
Opened 2022-04-01 11:16 UTC by avinashmadhwani02

…a popup when deleting referenced connector

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-01 13:12 UTC, sunnykesh-harness approved these changes
1. The modal showing referenced by error should be consistent. It is different than when a referenced service deleting fails.
2. As discussed please test for gitSync.

2022-04-01 13:12 UTC, sunnykesh-harness commented on src/modules/35-connectors/strings/strings.en.yaml
> +connectorReferenceText: 'cannot be deleted as it is being referenced by other entities. To see the list of entities referencing to this connector,'
It should be either **can not** or **can't** . Please confirm with doc team.

2022-04-01 13:12 UTC, sunnykesh-harness commented on src/modules/35-connectors/pages/connectors/views/ConnectorsListView.tsx
> +      <Text inline>
Is nested `Text` throwing any console error/warning?

2022-04-01 13:26 UTC, avinashmadhwani02 commented on src/modules/35-connectors/strings/strings.en.yaml
> +connectorReferenceText: 'cannot be deleted as it is being referenced by other entities. To see the list of entities referencing to this connector,'
I think @sunnykesh-harness `cannot` is also fine, it's given by Kapil and we are using the same in the title also.

2022-04-01 13:27 UTC, avinashmadhwani02 commented on src/modules/35-connectors/pages/connectors/views/ConnectorsListView.tsx
> +      <Text inline>
Any reason for error/warning?

2022-04-01 13:32 UTC, abhinavrastogi-harness requested changes

2022-04-01 13:32 UTC, abhinavrastogi-harness commented on src/modules/10-common/RouteDefinitions.ts
> +        path = `resources/connectors/${connectorId}?view=${view}`
query params should NOT be added to the route.
pass them as a second param of `history.push` instead.

2022-04-01 13:32 UTC, abhinavrastogi-harness commented on src/modules/35-connectors/pages/connectors/ConnectorDetailsPage/ConnectorDetailsPage.tsx
> +                          view: item
move this to the second param of `history.push(route.toConnectorDetails(...), {search: '?view=xyz'})`

2022-04-01 13:32 UTC, abhinavrastogi-harness commented on src/modules/35-connectors/pages/connectors/views/ConnectorsListView.tsx
> +      <Text inline>
+1
Text should not be nested

2022-04-01 13:32 UTC, abhinavrastogi-harness commented on src/modules/35-connectors/pages/connectors/views/ConnectorsListView.tsx
> +import defaultTo from 'lodash/defaultTo'
import from `lodash-es`

2022-04-01 13:32 UTC, abhinavrastogi-harness commented on src/modules/35-connectors/pages/connectors/utils/ConnectorHelper.tsx
> +  'refrencedBy' = 'refrencedBy',
spelling mistake

2022-04-01 13:32 UTC, abhinavrastogi-harness commented on src/modules/35-connectors/strings/strings.en.yaml
> +connectorReferenceText: 'cannot be deleted as it is being referenced by other entities. To see the list of entities referencing to this connector,'
`referencing this connector` instead of `referencing to this connector`

2022-04-01 14:29 UTC, abhinavrastogi-harness commented on src/modules/35-connectors/pages/connectors/views/ConnectorsListView.tsx
> +import defaultTo from 'lodash-es/defaultTo'
combine this with above import..
`import { pick, defaultTo } from 'lodash-es'`

2022-04-01 14:30 UTC, abhinavrastogi-harness approved these changes

2022-04-02 06:41 UTC, avinashmadhwani02 commented on src/modules/35-connectors/pages/connectors/ConnectorDetailsPage/ConnectorDetailsPage.tsx
> +  }, [view])
Yes we do

2022-04-02 07:13 UTC, VikasMaddukuriHarness approved these changes

2022-04-02 07:13 UTC, merged