fix: [PIE-3347]: on error GenericErrorHandler screen is shown
harness/harness-core-ui pull request #8132
Opened 2022-04-01 11:40 UTC by PratyushGar

##### Summary:

If pipeline details encounters error, the error is stored as templateError in the reducer and GenericErrorHandler screen with the status code and message.

##### Jira Links:

[https://harness.atlassian.net/browse/PIE-3347](https://harness.atlassian.net/browse/PIE-3347)

##### Screenshots:

![Screenshot 2022-04-01 at 4 59 18 PM](https://user-images.githubusercontent.com/100121280/161256309-f1d0dd36-b8a6-43d6-9128-64de7ee61924.png)

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-01 12:56 UTC, yc147 commented on src/services/pipeline-ng/index.tsx
> +  message?: string
You can edit this file manually. It has to be generated through pipeline service's swagger.json

2022-04-01 12:57 UTC, yc147 requested changes
You can not edit this `services/*/index.tsx` manually. It has to be generated through pipeline service's `swagger.json`

2022-04-04 05:56 UTC, yc147 approved these changes

2022-04-04 06:01 UTC, kapilkumawat86 approved these changes

2022-04-04 06:02 UTC, merged