feat: CCM-5386: Anomaly alert feature
harness/harness-core-ui pull request #8134
Opened 2022-04-01 12:37 UTC by jyotiarora-harness

##### Summary:

Anomalies notification alerts functionality

##### Jira Links:

https://harness.atlassian.net/browse/CCM-5386

##### Screenshots:

<img width="1106" alt="Screenshot 2022-03-23 at 11 00 57 AM" src="https://user-images.githubusercontent.com/97077953/161264610-4f0ed9f0-9483-4f70-9b76-d2ebbd8f752c.png">
<img width="1109" alt="Screenshot 2022-03-23 at 11 01 05 AM" src="https://user-images.githubusercontent.com/97077953/161264633-e48c9821-a128-46d9-91ac-fb02bdc9a6aa.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-01 13:07 UTC, jyotiarora-harness commented
retrigger titlecheck

2022-04-01 13:21 UTC, jyotiarora-harness commented
trigger cypress

2022-04-01 14:03 UTC, jyotiarora-harness commented
trigger cypress

2022-04-04 05:59 UTC, jyotiarora-harness commented
trigger cypress

2022-04-04 06:03 UTC, jyotiarora-harness commented
trigger cypress

2022-04-04 10:32 UTC, jenil-harness requested changes

2022-04-04 10:32 UTC, jenil-harness commented on src/modules/75-ce/components/AnomaliesAlert/AnomaliesAlertDialog.tsx
> +  notificationData: any
Avoid using `any`

2022-04-04 10:32 UTC, jenil-harness commented on src/modules/75-ce/components/AnomaliesAlert/AnomaliesAlertDialog.tsx
> +                  color: 'white'
knit - `Color.White`

2022-04-04 10:32 UTC, jenil-harness commented on src/modules/75-ce/components/AnomaliesAlert/AnomaliesAlertDialog.tsx
> +    const payload = data.alertList.map((item: any) => {
avoid `any`

2022-04-04 10:32 UTC, jenil-harness commented on src/modules/75-ce/components/AnomaliesAlert/PerspectiveSelection.tsx
> +          name={'perspective'}
move to i18n

2022-04-04 10:32 UTC, jenil-harness commented on src/modules/75-ce/components/AnomaliesSearch/AnomaliesSearch.tsx
> +  showModal: any
`any`

2022-04-04 10:32 UTC, jenil-harness commented on src/modules/75-ce/components/AnomaliesSettings/AnomaliesSettings.tsx
> +              font={{ size: 'normal', weight: 'semi-bold' }}
`FontVariation`

2022-04-04 10:32 UTC, jenil-harness commented on src/modules/75-ce/components/AnomaliesSettings/AnomaliesSettings.tsx
> +            font={{ size: 'normal', weight: 'semi-bold' }}
`FontVariation`

2022-04-04 10:32 UTC, jenil-harness commented on src/modules/75-ce/components/AnomaliesSettings/__test__/AnomaliesSettings.test.tsx
> +    const hideDrawer = jest.fn()
Knit - Can move it to top of the file, rather that defining again and again

2022-04-04 10:32 UTC, jenil-harness commented on src/modules/75-ce/constants.ts
> +    label: 'Slack webhook url',
Move labels to i18n

2022-04-04 10:32 UTC, jenil-harness commented on src/modules/75-ce/components/PerspectiveReportsAndBudget/__test__/PerspectiveReportsAndBudget.test.tsx
> +    await waitFor(() => Promise.resolve())
?

2022-04-04 10:32 UTC, jenil-harness commented on src/modules/75-ce/components/PerspectiveReportsAndBudget/PerspectiveReportsAndBudgets.tsx
> +        color="primary7"
`Color`

2022-04-04 15:40 UTC, jyotiarora-harness commented on src/modules/75-ce/components/AnomaliesAlert/AnomaliesAlertDialog.tsx
> +                  color: 'white'
Updated

2022-04-04 15:40 UTC, jyotiarora-harness commented on src/modules/75-ce/components/AnomaliesAlert/AnomaliesAlertDialog.tsx
> +    const payload = data.alertList.map((item: any) => {
Updated according to the data type

2022-04-04 15:42 UTC, jyotiarora-harness commented on src/modules/75-ce/components/AnomaliesSearch/AnomaliesSearch.tsx
> +  showModal: any
Updated according to the data type

2022-04-04 15:42 UTC, jyotiarora-harness commented on src/modules/75-ce/components/AnomaliesSettings/AnomaliesSettings.tsx
> +            font={{ size: 'normal', weight: 'semi-bold' }}
Updated

2022-04-04 15:42 UTC, jyotiarora-harness commented on src/modules/75-ce/components/AnomaliesSettings/__test__/AnomaliesSettings.test.tsx
> +    const hideDrawer = jest.fn()
Moved to the top

2022-04-04 15:43 UTC, jyotiarora-harness commented on src/modules/75-ce/constants.ts
> +    label: 'Slack webhook url',
Done

2022-04-04 15:43 UTC, jyotiarora-harness commented on src/modules/75-ce/components/PerspectiveReportsAndBudget/__test__/PerspectiveReportsAndBudget.test.tsx
> +    await waitFor(() => Promise.resolve())
It's unused, so removed

2022-04-05 07:11 UTC, jenil-harness approved these changes

2022-04-05 07:21 UTC, rajarshee-harness approved these changes

2022-04-05 08:39 UTC, chiragp1212 commented on src/modules/75-ce/components/AnomaliesAlert/AnomaliesAlertDialog.tsx
> +  const items = perspectiveList.map(pName => ({
we can memoize

2022-04-05 08:39 UTC, chiragp1212 commented on src/modules/75-ce/components/AnomaliesAlert/AnomaliesAlertDialog.tsx
> +    notificationData?.channels?.map((item: CCMNotificationChannel) => {
we can memoize

2022-04-05 08:40 UTC, chiragp1212 commented on src/modules/75-ce/components/AnomaliesAlert/AnomaliesAlertDialog.tsx
> +          [channelNameUrlMapping[channel as keyof typeof channelNameUrlMapping]]: emailList
we can extract this out in a variable and use in line 154 and line 159

2022-04-05 08:41 UTC, chiragp1212 commented on src/modules/75-ce/components/AnomaliesAlert/AnomaliesAlertDialog.tsx
> +        response = await updateNotificationAlert({ channels: payload as CCMNotificationChannel[] }, { queryParams })
we aren't we using the hooks for making the API calls

2022-04-05 08:45 UTC, chiragp1212 commented on src/modules/75-ce/components/AnomaliesSettings/AnomaliesSettings.tsx
> +      const response = await deleteNotificationAlert(void 0, {
please use hooks wherever possible

2022-04-05 08:45 UTC, chiragp1212 commented on src/modules/75-ce/components/AnomaliesSettings/AnomaliesSettings.tsx
> +  const actionCell: Renderer<CellProps<CCMNotificationSetting>> = ({ row }) => {
always better to memoize

2022-04-05 08:46 UTC, chiragp1212 commented on src/modules/75-ce/components/AnomaliesSettings/AnomaliesSettings.tsx
> +      <Container className={css.loader} data-testid="loader">
we generally use <PageSpinner /> for loading interactions

2022-04-05 08:46 UTC, chiragp1212 approved these changes

2022-04-05 08:51 UTC, kapilkumawat86 approved these changes

2022-04-05 08:52 UTC, merged