feat: [SRM-9913]: 3rd part API call log and execution log for Mmonito…
harness/harness-core-ui pull request #8142
Opened 2022-04-03 06:50 UTC by vasuki-kalluri

…red Service details page

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-05 05:48 UTC, shashidhargg approved these changes

2022-04-07 19:23 UTC, vasuki-kalluri commented
retrigger coverage

2022-04-08 08:29 UTC, vasuki-kalluri commented
retrigger jest

2022-04-08 08:31 UTC, vasuki-kalluri commented
retrigger coverage

2022-04-08 15:36 UTC, vasuki-kalluri commented
retrigger coverage

2022-04-08 17:16 UTC, shashidhargg requested changes
Please check the comments.

2022-04-08 17:16 UTC, shashidhargg commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/MetricsAndLogs/__tests__/MetricsAndLogs.test.tsx
> +  test('should open the LogContent modal and render MonitoredServiceLog with typ ApiCallLog by clicking the Execution Logs button', async () => {
Please change the test title, here we are clicking the External API Calls link.

2022-04-08 17:16 UTC, shashidhargg commented on src/modules/85-cv/hooks/useLogContentHook/views/LogContentHeader/LogContentHeader.tsx
> +            />
Please have a single Select for both. Just use diff data.
```
{(isVerifyStep || isMonitoredDetailsStep ) ? (
  <Select
    value={{
      label: `${getString('pipeline.verification.healthSourceLabel')}: ${healthSource?.label}`,
      value: healthSource?.value ?? ''
    }}
    items={getHealthSourceOptions(getString, isVerifyStep ? verifyStep?.resource : monitoredService?.resource)}
    onChange={handleHealthSource}
    disabled={loading || monitoredServiceLoading}
  />
```

2022-04-08 17:16 UTC, shashidhargg commented on src/modules/85-cv/hooks/useLogContentHook/views/LogContentHeader/LogContentHeader.tsx
> +      environmentIdentifier: envName!
Please use empty strings as default values for `serviceName` and `envName` at the level of the props and remove the force type.

2022-04-08 17:48 UTC, vasuki-kalluri commented on src/modules/85-cv/hooks/useLogContentHook/__test__/VerifyStepLogContentWithMockActions.test.tsx
> +    .mockImplementation(() => ({ data: executionLogsResponse, loading: false, error: null, refetch: jest.fn() })),
Done

2022-04-08 17:48 UTC, vasuki-kalluri commented on src/modules/85-cv/hooks/useLogContentHook/views/LogContentHeader/LogContentHeader.tsx
> +  } = useGetAllHealthSourcesForServiceAndEnvironment({
Done

2022-04-08 17:50 UTC, vasuki-kalluri commented on src/modules/85-cv/hooks/useLogContentHook/views/MonitoredServiceLogContent.tsx
> +        }
Done

2022-04-08 17:50 UTC, vasuki-kalluri commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/MetricsAndLogs/__tests__/MetricsAndLogs.test.tsx
> +  test('should open the LogContent modal and render MonitoredServiceLog with typ ApiCallLog by clicking the Execution Logs button', async () => {
Done

2022-04-08 17:50 UTC, vasuki-kalluri commented on src/modules/85-cv/hooks/useLogContentHook/views/LogContentHeader/LogContentHeader.tsx
> +            />
Done

2022-04-08 17:50 UTC, vasuki-kalluri commented on src/modules/85-cv/hooks/useLogContentHook/views/LogContentHeader/LogContentHeader.tsx
> +      environmentIdentifier: envName!
Done

2022-04-08 18:14 UTC, vasuki-kalluri commented on src/modules/85-cv/hooks/useLogContentHook/useLogContentHook.tsx
> +  envName = '',
Done

2022-04-08 18:27 UTC, vasuki-kalluri commented
retrigger coverage

2022-04-09 07:46 UTC, shashidhargg approved these changes

2022-04-11 04:22 UTC, diptiman-adak submitted a review, later dismissed

2022-04-11 04:40 UTC, shashidhargg commented on src/modules/85-cv/hooks/useLogContentHook/views/MonitoredServiceLogContent.tsx
> +        }
Why did we remove it again?

2022-04-11 06:23 UTC, shashidhargg approved these changes

2022-04-11 06:49 UTC, diptiman-adak approved these changes
Approving since no other reviewer is available that time.

2022-04-11 07:05 UTC, vasuki-kalluri commented
retrigger cypress

2022-04-11 07:06 UTC, vasuki-kalluri commented
trigger cypress

2022-04-11 14:19 UTC, shashidhargg approved these changes

2022-04-11 15:14 UTC, tan-nhu approved these changes

2022-04-11 15:25 UTC, merged