fix: [CDS-35957]: Infra tab changes
harness/harness-core-ui pull request #8161
Opened 2022-04-04 10:09 UTC by satyam-harness

##### Summary:

##### Jira Links:
https://harness.atlassian.net/browse/CDS-35957

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-05 07:01 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/Serverless/ServerlessStep.module.scss
> +/*
Keep this file name same as component name

2022-04-05 07:06 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAzure/__test__/__snapshots__/ServerlessAzureSpec.test.tsx.snap
> +              data-tooltip-id="awsInfraConnector"
If we need to have different tooltip for different types of connector then these changes are wrong.

2022-04-05 07:09 UTC, chetanvekariya-harness requested changes

2022-04-05 07:09 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessGCP/__test__/__snapshots__/ServerlessGCPSpec.test.tsx.snap
> +              data-tooltip-id="awsInfraConnector"
If we need to have different tooltip for different types of connector then these changes are wrong.

2022-04-05 07:32 UTC, samarth-sharma31 commented on src/modules/75-cd/components/PipelineSteps/Serverless/ServerlessSpecEditable.tsx
> +  const infraVariables = variablesData?.infrastructureDefinition?.spec
variablesData is a mandatory prop from ServerlessSpecEditableProps interface --> Please check if we need to use optional chaning while reading infrastructureDefinition from it

2022-04-05 07:57 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
> +                header: getString('pipelineSteps.awsConnectorLabel')
that will be changed in next pr, type 'azure' is not added in services. (currently we have disabled gcp and azure both).

2022-04-05 08:17 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployInfraSpecifications/DeployInfraSpecifications.tsx
> +                header: getString('pipelineSteps.awsConnectorLabel')
Let's fix this as well as you are already fixing other comments

2022-04-05 10:22 UTC, satyam-harness commented
retrigger titlecheck

2022-04-05 10:29 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineSteps/Serverless/ServerlessSpecEditable.tsx
> +  const infraVariables = variablesData?.infrastructureDefinition?.spec
this was earlier added for testcases

2022-04-05 11:15 UTC, satyam-harness commented
retrigger jest

2022-04-06 04:52 UTC, bhavya-sinha commented on src/modules/70-pipeline/utils/stageHelpers.ts
> +          type: 'Gcp',
Instead of hardcoding, can we have enum/maps for the types

2022-04-06 04:54 UTC, chetanvekariya-harness submitted a review, later dismissed

2022-04-06 04:56 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/ServerlessInfraSpec/ServerlessInfraSpec.module.scss
> +  padding-bottom: 0px !important;
`!important` is used at a lot of places. Hope all are intentional.

2022-04-06 05:21 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/utils/stageHelpers.ts
> +          type: 'Gcp',
Fixed.

2022-04-06 05:37 UTC, chetanvekariya-harness commented
retrigger jest

2022-04-06 05:45 UTC, chetanvekariya-harness commented
retrigger jest

2022-04-06 06:05 UTC, chetanvekariya-harness approved these changes

2022-04-06 06:20 UTC, chetanvekariya-harness commented
retrigger jest

2022-04-06 06:55 UTC, chetanvekariya-harness commented
trigger cypress

2022-04-06 08:16 UTC, chetanvekariya-harness approved these changes

2022-04-06 08:34 UTC, bhavya-sinha approved these changes

2022-04-06 08:35 UTC, merged