fix: [CDS-35689]: Feature/infra testing
harness/harness-core-ui pull request #8217
Opened 2022-04-06 11:02 UTC by satyam-harness

##### Summary:

##### Jira Links:
https://harness.atlassian.net/browse/CDS-35689

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-12 09:48 UTC, satyam-harness commented
retrigger jest

2022-04-12 09:52 UTC, satyam-harness commented
retrigger coverage

2022-04-13 13:13 UTC, chetanvekariya-harness approved these changes

2022-04-13 13:13 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/__tests__/__snapshots__/Artifactory.test.tsx.snap
> +                          value=""
When there is error, value should be same as error text. The reason this has not happened is because you removed **artifactRepoError** from useEffect dependencies.

2022-04-13 13:13 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/__tests__/__snapshots__/Artifactory.test.tsx.snap
> +                          value=""
Same as above comment.

2022-04-13 13:13 UTC, chetanvekariya-harness requested changes
Need to fix issues.

2022-04-13 22:01 UTC, diptiman-adak commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/ServerlessArtifactoryRepository.tsx
> +  }, [artifactRepoLoading])
Codacy has a fix for the issue: [React Hook useEffect has missing dependencies: 'artifactRepoError?.data' and 'getString'. Either include them or remove the dependency array.](https://app.codacy.com/gh/harness/harness-core-ui/pullRequest?prid=9232287)
```suggestion
  }, [artifactRepoError?.data, artifactRepoLoading, getString])
```

2022-04-14 10:13 UTC, satyam-harness commented
retrigger cypress

2022-04-14 11:28 UTC, satyam-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/ServerlessArtifactoryRepository.tsx
> +  }, [artifactRepoLoading])
done

2022-04-14 11:28 UTC, satyam-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/__tests__/Artifactory.test.tsx
> +  test(`ServerlessArtifactoryRepository while fetching repository list`, () => {
done

2022-04-14 11:28 UTC, satyam-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/__tests__/__snapshots__/Artifactory.test.tsx.snap
> +                          data-icon="fixed-input"
done

2022-04-14 11:28 UTC, satyam-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/__tests__/__snapshots__/Artifactory.test.tsx.snap
> +                          value=""
done

2022-04-14 11:29 UTC, satyam-harness commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/Artifactory/__tests__/__snapshots__/Artifactory.test.tsx.snap
> +                          value=""
done

2022-04-14 11:44 UTC, chetanvekariya-harness commented
retrigger jest

2022-04-14 13:31 UTC, chetanvekariya-harness commented
retrigger jest

2022-04-17 06:07 UTC, chetanvekariya-harness approved these changes

2022-04-17 08:30 UTC, merged