fix: [CDS-36010]: nexus and artifactory runtime repositoryURL field
harness/harness-core-ui pull request #8220
Opened 2022-04-06 12:41 UTC by PratyushGar

##### Summary:

RepositoryUrl Runtime field was added in nexus and artifact runtime input and the order of the fields are changed in the way it appears during pipeline configuration.

##### Jira Links:

[https://harness.atlassian.net/browse/CDS-36009](https://harness.atlassian.net/browse/CDS-36009)
[https://harness.atlassian.net/browse/CDS-36010](https://harness.atlassian.net/browse/CDS-36010)

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-06 13:04 UTC, dhruvUpadhyay07 commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/ArtifactoryArtifactSource/ArtifactoryArtifactSource.tsx
> +              name={`${path}.artifacts.${artifactPath}.spec.repositoryUrl`}
were we supposed to move onChange also ?

2022-04-06 13:09 UTC, PratyushGar commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/ArtifactoryArtifactSource/ArtifactoryArtifactSource.tsx
> +              name={`${path}.artifacts.${artifactPath}.spec.repositoryUrl`}
repositoryUrl is not required for tags population

2022-04-06 14:44 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/ArtifactoryArtifactSource/ArtifactoryArtifactSource.tsx
> +              disabled={isFieldDisabled(`artifacts.${artifactPath}.spec.repositoryUrl`)}
We already have `artifactRepositoryUrl`. Why is this `repositoryUrl` needed?

2022-04-06 14:51 UTC, bhavya-sinha requested changes

2022-04-07 05:28 UTC, bhavya-sinha approved these changes

2022-04-07 06:43 UTC, samarth-sharma31 approved these changes

2022-04-07 06:44 UTC, merged