feat: [FFM-2243]: Add percentage rollout support
harness/harness-core-ui pull request #8224
Opened 2022-04-06 15:04 UTC by knagurski

This PR adds Percentage Rollout support to the Target Group detail page, refactors the page to use the same flags listing component and refactors the `PercentageRollout` component to be more flexible.

|Before|After|
|------|------|
|![Before]()|![After]()|

Refs [FFM-2243](https://harness.atlassian.net/browse/FFM-22423)

2022-04-06 15:52 UTC, chrisblakely01 requested changes

2022-04-06 15:52 UTC, chrisblakely01 commented on src/modules/75-cf/pages/target-group-detail/hooks/usePercentageRolloutValidationSchema.tsx
> +                  (variations || []).map(({ weight }) => weight).reduce((total, weight) => total + weight, 0) === 100
We should be testing this logic not ignoring as its pretty important. There probably needs to be a test that exercises the form, triggers the validation and asserts the `invalidTotalError` message appears. Didn't see any test that covers this

2022-04-06 15:54 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/hooks/usePercentageRolloutValidationSchema.tsx
> +                  (variations || []).map(({ weight }) => weight).reduce((total, weight) => total + weight, 0) === 100
It's actually impossible to get into the state where it'll use `[]`, but it's also impossible to convince TS of that without a bunch of casting. If this even does get in here, then the test will still resolve as failed (as it should) since the totals will still not reach 100%.

2022-04-06 15:57 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/hooks/usePercentageRolloutValidationSchema.tsx
> +                  (variations || []).map(({ weight }) => weight).reduce((total, weight) => total + weight, 0) === 100
Triggering of the error is scattered around the place, but has 100% coverage across the various levels that contribute to the error being displayed. Might be worth an all-encompassing test at a higher level though.

2022-04-06 16:04 UTC, chrisblakely01 commented on src/modules/75-cf/pages/target-group-detail/hooks/usePercentageRolloutValidationSchema.tsx
> +                  (variations || []).map(({ weight }) => weight).reduce((total, weight) => total + weight, 0) === 100
ah! Ok I see, I thought this was ignoring the entire line but I see you've got a decent tests around the weights. If you default the variations to `[]` at the point you intialise the form instead of checking it here would that get rid of the extra branches here? 

I guess this is one of those instances where high test coverage isn't worth shooting for

2022-04-06 16:12 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/hooks/usePercentageRolloutValidationSchema.tsx
> +                  (variations || []).map(({ weight }) => weight).reduce((total, weight) => total + weight, 0) === 100
New, more-holistic, test added 👍🏻 Good shout!

2022-04-06 16:31 UTC, chrisblakely01 reviewed
Looks good, just 1/2 Q's

2022-04-06 16:31 UTC, chrisblakely01 commented on src/modules/75-cf/components/PercentageRollout/PercentageRollout.tsx
> +  hideOverError?: boolean
Hurray!

2022-04-06 16:31 UTC, chrisblakely01 commented on src/modules/75-cf/hooks/useFormValues.tsx
> +export default function useFormValues<FormType>(): UseFormValuesPayload<FormType> {
Curious as to why you needed to do this instead of just getting the stuff from Formik/its own context?

2022-04-06 16:31 UTC, chrisblakely01 commented on src/modules/75-cf/pages/target-group-detail/components/FlagSettingsPanel/FlagSettingsForm.tsx
> +}
dont ya just love having to do stuff like this ? 😂

2022-04-06 21:02 UTC, knagurski commented on src/modules/75-cf/hooks/useFormValues.tsx
> +export default function useFormValues<FormType>(): UseFormValuesPayload<FormType> {
The version of formik we have doesn't come with hooks. When we update to the newer version I want to double back and yank this out.

2022-04-06 21:02 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/FlagSettingsPanel/FlagSettingsForm.tsx
> +}
No. No I do not

2022-04-06 21:06 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/FlagSettingsPanel/FlagsListing/FlagsListing.tsx
> +        width: '5%',
I originally had them all as %, but then opted for the variations column as px for consistency between the edit and add views. The other columns looked fine in both, so I left it. Ideally the checkbox, variation and delete should be px and details should take up the rest of the space. I'm planning of pulling this out into a common component that can be used for Targets as well in the next epic. I'll deffo take the time then to pixelise the other columns. Good eye for detail!

2022-04-06 21:07 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/FlagSettingsPanel/FlagsListing/VariationsCell.tsx
> +        setField(`${fieldPrefix}.percentageRollout.variations[${index}]`, undefined)
That is a damn fine point! I could just wipe out the entire `percentageRollout` and call it a day.

2022-04-06 21:31 UTC, knagurski commented on src/modules/75-cf/pages/target-group-detail/components/FlagSettingsPanel/FlagsListing/VariationsCell.tsx
> +        setField(`${fieldPrefix}.percentageRollout.variations[${index}]`, undefined)
Done now. I flip'n love simplifications!

2022-04-06 21:34 UTC, knagurski commented on src/modules/75-cf/components/PercentageRollout/PercentageRollout.tsx
> +  hideOverError?: boolean
I was thinking about going a step further and yanking the current error entirely and teaching pipelines how to do the validation, but I didn't want to open that can of worms!

2022-04-06 21:46 UTC, tan-nhu commented on src/modules/75-cf/constants/index.ts
> +export const PERCENTAGE_ROLLOUT_VALUE = 'Percentage Rollout'
Why this string is not in i18n/useString?

2022-04-07 08:16 UTC, crystal-fong commented on src/modules/75-cf/components/PercentageRollout/PercentageRollout.module.scss
> -  --variationColor: hotpink;
damn why did you take that out :(

2022-04-07 09:20 UTC, knagurski commented on src/modules/75-cf/constants/index.ts
> +export const PERCENTAGE_ROLLOUT_VALUE = 'Percentage Rollout'
This is actually the value from the server, not what is displayed.

2022-04-07 09:21 UTC, knagurski commented on src/modules/75-cf/components/PercentageRollout/PercentageRollout.module.scss
> -  --variationColor: hotpink;
No named colours allowed :-( It was just a default value which wasn't actually used.

2022-04-07 09:25 UTC, chrisblakely01 approved these changes
Good stuff 👍  And thanks for tidying the Percentage Rollout component, saves me the work! 💯

2022-04-07 10:00 UTC, crystal-fong approved these changes

2022-04-07 10:30 UTC, merged