Ccm 7145 connectors error handling
harness/harness-core-ui pull request #8271
Opened 2022-04-11 08:12 UTC by jyotiarora-harness

##### Summary:

Connectors error handling for verification step (AWS, Azure, GCP and )

##### Jira Links:

https://harness.atlassian.net/browse/CCM-7145

##### Screenshots:

<img width="1199" alt="Screenshot 2022-04-11 at 1 41 38 PM" src="https://user-images.githubusercontent.com/97077953/162693365-4e10e9d4-a599-4df7-9676-cec444178e8b.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-12 17:30 UTC, jenil-harness commented on src/modules/35-connectors/common/VerifyOutOfClusterDelegate/VerifyOutOfClusterDelegate.tsx
> +          break
Will it be possible to merge them into one event?

2022-04-12 17:32 UTC, jenil-harness commented on src/modules/10-common/components/ErrorHandler/ErrorHandler.tsx
> +              {isCeConnector ? (
What is changing here?
I thought the response is standard with all connectors.

2022-04-12 17:34 UTC, jenil-harness commented on src/modules/10-common/components/ErrorHandler/ErrorHandler.tsx
> +const Suggestions: React.FC<{
Let's move it to a new file.

2022-04-13 06:42 UTC, jyotiarora-harness commented on src/modules/35-connectors/common/VerifyOutOfClusterDelegate/VerifyOutOfClusterDelegate.tsx
> +          break
Right now we are tracking with different names in our funnel, so to change this we need to align product's team
Will start the discussion with them for this and will fix it in follow up PR's

2022-04-13 06:43 UTC, jyotiarora-harness commented on src/modules/10-common/components/ErrorHandler/ErrorHandler.tsx
> +              {isCeConnector ? (
For CE connectors we have to show the documentation links embedded from the UI side, so added this functionality as a separate component

2022-04-13 06:44 UTC, jyotiarora-harness commented on src/modules/10-common/components/ErrorHandler/ErrorHandler.tsx
> +const Suggestions: React.FC<{
Moved to a new file

2022-04-13 06:58 UTC, jyotiarora-harness commented
retrigger jest

2022-04-13 07:39 UTC, jyotiarora-harness commented
trigger cypress

2022-04-13 09:41 UTC, jenil-harness submitted a review, later dismissed

2022-04-13 09:41 UTC, avinashmadhwani02 commented on src/modules/10-common/components/ErrorHandler/ErrorHandler.tsx
> +    isCeConnector = false
ErrorHandler should not understand Connector, we should not put module-specific login in common components.

2022-04-13 10:26 UTC, avinashmadhwani02 submitted a review, later dismissed

2022-04-13 10:29 UTC, avinashmadhwani02 requested changes

2022-04-13 10:29 UTC, avinashmadhwani02 commented on src/modules/10-common/components/ErrorHandler/ErrorSuggestionsCe.tsx
> +// eslint-disable-next-line no-restricted-imports
We should not use anything from higher modules like connectors in this case

2022-04-13 10:31 UTC, meenakshi-harness commented on src/modules/10-common/components/ErrorHandler/ErrorHandler.tsx
> +  isCeConnector?: boolean
We should not be adding connector specific props to common component.

2022-04-13 10:33 UTC, meenakshi-harness commented on src/modules/35-connectors/common/VerifyOutOfClusterDelegate/VerifyOutOfClusterDelegate.tsx
> +          break
Can we move this logic to some util outside this component and call that util here.

2022-04-13 10:35 UTC, meenakshi-harness commented on src/modules/35-connectors/common/VerifyOutOfClusterDelegate/VerifyOutOfClusterDelegate.tsx
> +            </Layout.Horizontal>
Why are we hiding this logic for CE connector. Edit credential button and View link is consistent across all connectors.

2022-04-13 10:36 UTC, avinashmadhwani02 commented on src/modules/10-common/components/ErrorHandler/ErrorSuggestionsCe.tsx
> +    const docIndex = msg.lastIndexOf('document')
Is the 'document' string coming from backend? we should not add string checks like this

2022-04-13 10:37 UTC, avinashmadhwani02 commented on src/modules/10-common/components/ErrorHandler/ErrorSuggestionsCe.tsx
> +              {!secondStr ? (
if the document is not present, do we have to render this?

2022-04-13 10:38 UTC, avinashmadhwani02 commented on src/modules/10-common/components/ErrorHandler/ErrorSuggestionsCe.tsx
> +      <Icon name={props.icon} margin={{ right: 'small' }} />
We already have this code in ErrorList component. Can we check if  we can use that component instead

2022-04-13 10:38 UTC, avinashmadhwani02 commented on src/modules/10-common/components/ErrorHandler/ErrorHandler.tsx
> +                <Suggestions
This looks like a variant of ErrorList component, do we need a separate component?

2022-04-13 11:36 UTC, jyotiarora-harness commented on src/modules/35-connectors/common/VerifyOutOfClusterDelegate/VerifyOutOfClusterDelegate.tsx
> +            </Layout.Horizontal>
For CE connectors this is the requirement to hide the Edit credential button and view permission link

2022-04-13 11:36 UTC, jyotiarora-harness commented on src/modules/35-connectors/common/VerifyOutOfClusterDelegate/VerifyOutOfClusterDelegate.tsx
> +          break
Yes, we can do that

2022-04-13 11:38 UTC, jyotiarora-harness commented on src/modules/10-common/components/ErrorHandler/ErrorSuggestionsCe.tsx
> +              {!secondStr ? (
Yes, this is the requirement, if the doc link is not present, provide the support links

2022-04-13 13:09 UTC, meenakshi-harness commented on src/modules/35-connectors/common/VerifyOutOfClusterDelegate/VerifyOutOfClusterDelegate.tsx
> +            </Layout.Horizontal>
Even if want to hide something in this component we should have a generic prop for that, like `enableEditCredential` or `showViewPermission` so that these could be extended to more use-cases apart from binding it to certain type of connectors.

2022-04-13 15:25 UTC, jyotiarora-harness commented on src/modules/10-common/components/ErrorHandler/ErrorSuggestionsCe.tsx
> +    const docIndex = msg.lastIndexOf('document')
Yes document string will be part of the error message coming from backend

2022-04-14 04:27 UTC, jyotiarora-harness commented
retrigger jest

2022-04-14 04:45 UTC, avinashmadhwani02 commented on src/modules/10-common/components/ErrorHandler/ErrorSuggestionsCe.tsx
> +    const docIndex = msg.lastIndexOf('document')
What if the `document` string is coming as part of message itself?

2022-04-14 04:47 UTC, avinashmadhwani02 commented on src/modules/10-common/strings/strings.en.yaml
> +  contactLabel: 'Contact '
Why are we adding ' ' (empty space) here? It should be added where you are rendering it.

2022-04-14 04:49 UTC, avinashmadhwani02 commented on src/modules/35-connectors/common/ErrorSuggestions/ErrorSuggestionsCe.tsx
> +import { Color, Container, FontVariation, Icon, Layout, Text, IconName } from '@harness/uicore'
Color and FontVariation should be imported from `harness/design-system`... are you not getting any lint error?

2022-04-14 05:11 UTC, avinashmadhwani02 commented on src/modules/35-connectors/common/VerifyOutOfClusterDelegate/VerifyOutOfClusterDelegate.tsx
> +            <ErrorHandler
Can we directly render <Suggestions /> in case of isCeConnector?  
For eg. 

`isCeConnector ? <Suggestions /> : <ErrorHandler />`

Reason - we are not using anything from ErrorHandler

2022-04-14 05:12 UTC, avinashmadhwani02 commented on src/modules/35-connectors/utils/connectorEvents.ts
> +  [Connectors.CE_KUBERNETES]: [CE_K8S_CONNECTOR_CREATION_EVENTS.LOAD_CONNECTION_TEST],
why value needs to be an array?

2022-04-14 05:14 UTC, jyotiarora-harness commented on src/modules/35-connectors/common/VerifyOutOfClusterDelegate/VerifyOutOfClusterDelegate.tsx
> +            <ErrorHandler
Suggestions (it's just covering the hints) is a part of Error handler component

2022-04-14 05:31 UTC, avinashmadhwani02 approved these changes

2022-04-14 05:40 UTC, jyotiarora-harness commented on src/modules/35-connectors/utils/connectorEvents.ts
> +  [Connectors.CE_KUBERNETES]: [CE_K8S_CONNECTOR_CREATION_EVENTS.LOAD_CONNECTION_TEST],
Changed it to normal string value

2022-04-14 06:32 UTC, avinashmadhwani02 approved these changes

2022-04-14 07:19 UTC, jenil-harness approved these changes

2022-04-14 07:20 UTC, merged