feat: [PIE-3300]: Cypress tests for Service/Environment edit flow
harness/harness-core-ui pull request #8306
Opened 2022-04-12 13:43 UTC by Sagar-Rajput7

##### Summary:

Added cypress test cases for service/environment edit flow

##### Jira Links:

https://harness.atlassian.net/browse/PIE-3300

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-12 13:44 UTC, Sagar-Rajput7 commented
retrigger titlecheck

2022-04-12 15:34 UTC, PratyushGar requested changes

2022-04-12 15:34 UTC, PratyushGar commented on cypress/fixtures/ng/api/servicesV2/servicesUpdate.json
> +      "projectIdentifier": "Chirag",
Please ensure same projectIdentifier in all mocks.

2022-04-12 15:34 UTC, PratyushGar commented on cypress/fixtures/ng/api/servicesV2/servicesUpdate.json
> +    },
same here.

2022-04-12 15:34 UTC, PratyushGar commented on cypress/integration/70-pipeline/Environments.spec.ts
> +    '/ng/api/environmentsV2?routingId=accountId&accountIdentifier=accountId&orgIdentifier=default&projectIdentifier=project1&page=0&size=10'
apiRoutes and call declarations can be moved to 70-pipeline/constants.

2022-04-13 04:11 UTC, AshwinBhatkal-Harness approved these changes

2022-04-13 04:14 UTC, Sagar-Rajput7 commented
retrigger typecheck

2022-04-13 04:45 UTC, PratyushGar approved these changes

2022-04-13 04:46 UTC, Sagar-Rajput7 commented on cypress/integration/70-pipeline/Environments.spec.ts
> +    '/ng/api/environmentsV2?routingId=accountId&accountIdentifier=accountId&orgIdentifier=default&projectIdentifier=project1&page=0&size=10'
Resolved

2022-04-13 04:46 UTC, Sagar-Rajput7 commented on cypress/fixtures/ng/api/servicesV2/servicesUpdate.json
> +    },
Resolved

2022-04-13 04:46 UTC, Sagar-Rajput7 commented on cypress/fixtures/ng/api/servicesV2/servicesUpdate.json
> +      "projectIdentifier": "Chirag",
Resolved

2022-04-13 04:46 UTC, Sagar-Rajput7 commented on cypress/integration/70-pipeline/Services.spec.ts
> +    '/ng/api/servicesV2?routingId=accountId&accountIdentifier=accountId&orgIdentifier=default&projectIdentifier=project1&size=10&page=0'
Resolved

2022-04-13 04:46 UTC, merged