feat: CCM-7143: AWS connector ui changes
harness/harness-core-ui pull request #8362
Opened 2022-04-14 12:35 UTC by jyotiarora-harness

##### Summary:

CE AWS connector UI improvements 

##### Jira Links:

https://harness.atlassian.net/browse/CCM-7143

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-18 04:50 UTC, jyotiarora-harness commented
trigger cypress

2022-04-18 09:38 UTC, jyotiarora-harness commented
trigger cypress

2022-04-21 05:16 UTC, jyotiarora-harness commented
trigger cypress

2022-04-26 06:40 UTC, jyotiarora-harness commented
retrigger jest

2022-04-26 06:41 UTC, jyotiarora-harness commented
trigger cypress

2022-04-26 09:21 UTC, jyotiarora-harness commented
trigger cypress

2022-04-26 09:57 UTC, rishik30 requested changes

2022-04-26 09:57 UTC, rishik30 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CostUsageReport.tsx
> +                    window.open('https://console.aws.amazon.com/billing/home?#/reports')
open the link in a separate tab, for that provide the target `_blank`

2022-04-27 06:44 UTC, jyotiarora-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CostUsageReport.tsx
> +                    window.open('https://console.aws.amazon.com/billing/home?#/reports')
Updated

2022-04-27 08:09 UTC, jyotiarora-harness commented
trigger cypress

2022-04-27 09:24 UTC, rishik30 submitted a review, later dismissed

2022-04-27 14:23 UTC, avinashmadhwani02 commented on src/modules/35-connectors/common/ConnectorCreationInstructionList/ConnectorCreationInstructionList.tsx
> +const ConnectorInstructionList: React.FC<InstuctionListProps> = props => {
We can create this as a Generic component, it can be used anywhere else apart from connectors.... Also this component should not understand button. 

It can be a simple ordered list component. Let's discuss if you have any questions.

2022-04-27 14:23 UTC, avinashmadhwani02 commented on src/modules/35-connectors/common/ConnectorCreationInstructionList/ConnectorCreationInstructionList.module.scss
> +  line-height: 0;
Where are we using this?

2022-04-27 14:23 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +    font-size: 13px !important;
fontSize from variation

2022-04-27 14:23 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +    margin-bottom: 34px !important;
SAA

2022-04-27 14:23 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +    background: var(--primary-1) !important;
we have defined similar classed in [ConnectorCreationInstructionList.module.scss], please avoid code duplication

2022-04-27 14:23 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CostUsageReport.tsx
> +                      'https://newdocs.helpdocs.io/article/80vbt5jv0q-set-up-cost-visibility-for-aws#review_aws_access_permissions'
Should we keep these links in a constant file?

2022-04-27 14:23 UTC, avinashmadhwani02 commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CostUsageReportExisting.tsx
> +            onChange={/* istanbul ignore next */ text => onChange(text.trim())}
why are we ignoring coverage?

2022-04-27 15:07 UTC, jyotiarora-harness commented on src/modules/35-connectors/common/ConnectorCreationInstructionList/ConnectorCreationInstructionList.module.scss
> +  margin-bottom: 34px !important;
34px is not defined in our spacing guidelines, that's why used it like this

2022-04-27 15:18 UTC, jyotiarora-harness commented on src/modules/35-connectors/common/ConnectorCreationInstructionList/ConnectorCreationInstructionList.tsx
> +const ConnectorInstructionList: React.FC<InstuctionListProps> = props => {
By adding button and hybrid feasibility is the requirement of this list in the connectors to add the instructions, that's why created this component in that manner only.

It's not a simple ordered list component

2022-04-27 15:19 UTC, jyotiarora-harness commented on src/modules/35-connectors/common/ConnectorCreationInstructionList/ConnectorCreationInstructionList.module.scss
> +  line-height: 0;
Passed the classname from the list object defined in the parent component

2022-04-27 15:37 UTC, jyotiarora-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/steps/CostUsageReportExisting.tsx
> +  const [curReports, setCurReports] = useState(props.existingCurReports)
it specifies cost usage reports -- CUR

2022-04-27 15:50 UTC, jyotiarora-harness commented on src/modules/35-connectors/common/ConnectorCreationInstructionList/ConnectorCreationInstructionList.module.scss
> +  font-size: 13px;
Updated with variation

2022-04-27 15:50 UTC, jyotiarora-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +    font-size: 13px !important;
Updated

2022-04-27 15:51 UTC, jyotiarora-harness commented on src/modules/35-connectors/components/CreateConnector/CENGAwsConnector/CreateCeAwsConnector.module.scss
> +    background: var(--primary-1) !important;
Removed duplicate css code

2022-04-28 04:55 UTC, jyotiarora-harness commented
trigger cypress

2022-04-28 08:38 UTC, avinashmadhwani02 approved these changes
@jyotiarora-harness as discussed, please take up the changes in the follow up PR

2022-04-28 08:38 UTC, avinashmadhwani02 commented on src/modules/35-connectors/common/ConnectorCreationInstructionList/ConnectorCreationInstructionList.tsx
> +  instructionsList: Record<string, any>[]
Avoid using any

2022-04-28 08:38 UTC, avinashmadhwani02 commented on src/modules/35-connectors/common/ConnectorCreationInstructionList/ConnectorCreationInstructionList.tsx
> +            /* istanbul ignore next */ () => {
Why are we ignoring coverage?

2022-04-28 08:38 UTC, avinashmadhwani02 commented on src/modules/35-connectors/common/ConnectorCreationInstructionList/ConnectorCreationInstructionList.tsx
> +const ConnectorInstructionList: React.FC<InstuctionListProps> = props => {
I agree but let's say if I want to use a smilar list somewhere else in connectors with slight differences, I will not be able to do that. 

Let's discuss, I have one approach in mind

2022-04-28 08:38 UTC, avinashmadhwani02 commented on src/modules/35-connectors/common/ConnectorCreationInstructionList/ConnectorCreationInstructionList.tsx
> +      <Layout.Vertical>
Do we need Layout.vErtical?

2022-04-28 10:14 UTC, rishik30 approved these changes

2022-04-28 10:14 UTC, merged