feat: [CDS-36176]: delegate selector support
harness/harness-core-ui pull request #8375
Opened 2022-04-17 16:33 UTC by dhruvUpadhyay07

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-19 05:12 UTC, dhruvUpadhyay07 commented
retrigger jest

2022-04-19 06:05 UTC, dhruvUpadhyay07 commented
trigger cypress

2022-04-19 10:43 UTC, dhruvUpadhyay07 commented
trigger rebase

2022-04-20 03:18 UTC, dhruvUpadhyay07 commented
trigger cypress

2022-04-20 03:36 UTC, kapilkumawat86 requested changes

2022-04-20 03:36 UTC, kapilkumawat86 commented on src/modules/70-pipeline/components/PipelineInputSetForm/PipelineInputSetForm.module.scss
> +:global {
Never do this, put it under local selector

2022-04-20 06:32 UTC, closed without merging