fix: [CDS-36437]: added the on401 prop in childAppmounter
harness/harness-core-ui pull request #8392
Opened 2022-04-18 17:08 UTC by cjlee01

##### Summary:

Added the on401 prop to childAppMounter so it can be used in child apps

##### Jira Links:

https://harness.atlassian.net/browse/CDS-36437

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-18 17:10 UTC, cjlee01 commented
retrigger titlecheck

2022-04-18 17:16 UTC, tan-nhu approved these changes

2022-04-18 17:25 UTC, cjlee01 commented
retrigger titlecheck

2022-04-18 17:32 UTC, tan-nhu approved these changes

2022-04-18 18:01 UTC, tan-nhu submitted a review, later dismissed

2022-04-19 03:55 UTC, abhinavrastogi-harness requested changes

2022-04-19 03:55 UTC, abhinavrastogi-harness commented on src/microfrontends/ChildAppMounter.tsx
> +    const redirectOn401: () => void = () => {
can we create a util in 10-common to trigger a logout instead of defining a new function here?
we can reuse the logic from https://github.com/harness/harness-core-ui/blob/develop/src/framework/app/App.tsx#L144

we also need to call `AppStorage.clear()`

2022-04-19 03:55 UTC, abhinavrastogi-harness commented on src/microfrontends/ChildAppMounter.tsx
> +          on401={redirectOn401}
this param should be added in the `ChildAppProps` interface

2022-04-19 19:29 UTC, cjlee01 commented on src/microfrontends/ChildAppMounter.tsx
> +    const redirectOn401: () => void = () => {
added the util triggerLogout

2022-04-19 19:29 UTC, cjlee01 commented on src/microfrontends/ChildAppMounter.tsx
> +          on401={redirectOn401}
added the prop in interface

2022-04-19 19:34 UTC, tan-nhu requested changes

2022-04-19 19:34 UTC, tan-nhu commented on src/microfrontends/ChildAppMounter.tsx
> +import { triggerLogout } from '@common/utils/triggerLogoutUtils'
We can name it better, like `makeGlobal404Handler`

2022-04-19 19:34 UTC, tan-nhu commented on src/microfrontends/ChildAppMounter.tsx
> +          on401={triggerLogout}
You must call it and pass accountId, along with history

```
on401={triggerLogout(accountId, history)}
```

2022-04-19 19:34 UTC, tan-nhu commented on src/modules/10-common/utils/triggerLogoutUtils.tsx
> +  const username = SessionToken.username()
Must return a proper Restful React response handler:

```
return response => {
   const username ...
}
```

2022-04-19 19:37 UTC, cjlee01 commented on src/microfrontends/ChildAppMounter.tsx
> +import { triggerLogout } from '@common/utils/triggerLogoutUtils'
changed name

2022-04-19 19:58 UTC, tan-nhu commented on src/modules/10-common/utils/triggerLogoutUtils.tsx
> +  const username = SessionToken.username()
The return of this function should be `(response: Response) => void`. You can do:

```
type GlobalResponseHandler = (response: Response) => void
```

Then 

```
const triggerLogout/makeGlobalResponseHandler: (accountId: string, history: History) => GlobalResponseHandler = (accountId, history) => {
   return response => {
     const username = ....
   }
}
```

2022-04-19 22:53 UTC, tan-nhu reviewed
You also need to update App.tsx and ChildAppMounter.tsx?

2022-04-19 22:53 UTC, tan-nhu commented on src/modules/10-common/utils/triggerLogoutUtils.tsx
> +/*
Remove this file?

2022-04-19 23:04 UTC, cjlee01 commented on src/modules/10-common/utils/triggerLogoutUtils.tsx
> +/*
removed

2022-04-20 01:19 UTC, tan-nhu submitted a review, later dismissed

2022-04-20 05:44 UTC, abhinavrastogi-harness requested changes

2022-04-20 05:44 UTC, abhinavrastogi-harness commented on src/modules/10-common/utils/makeGlobal401Handler.tsx
> +    // const triggerLogout/makeGlobalResponseHandler: (accountId: string, history: History) => GlobalResponseHandler = (accountId, history) => { return response => { const username = .... } }
can we remove commented code?

2022-04-20 05:44 UTC, abhinavrastogi-harness commented on src/modules/10-common/utils/makeGlobal401Handler.tsx
> +    // if user lands on /, they'll first get redirected to a path with accountId
what are these comments about? don't seem relevant to this code, and they were not part of this function earlier

2022-04-20 05:44 UTC, abhinavrastogi-harness commented on src/microfrontends/ChildAppMounter.tsx
> +          on401={makeGlobal401Handler(params?.accountId as string, history)}
why is `params` nullable? and why are we typecasting it as string forcibly? 
undefined should not be cast as a string just to fool the type system.
401 tracking doesn't work without an account id.

2022-04-20 05:44 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +      globalResponseHandler()
no need for this indirection now that the logic is moved to another utli function.
you can call `makeGlobal401Handler(accountId, history)` directly here

2022-04-20 05:44 UTC, abhinavrastogi-harness commented on src/framework/app/App.tsx
> +    makeGlobal401Handler(accountId, history)
this seems incomplete.. 
`makeGlobal401Handler` just returns a function.. where we are actually calling that returned function?
have you tested this?

2022-04-20 05:44 UTC, abhinavrastogi-harness commented on src/modules/10-common/utils/makeGlobal401Handler.tsx
> +  return response => {
why do we need this HoC pattern here? why cant this be a simple util function which takes accountId, history and response as params?
cc @tan-nhu

2022-04-20 06:26 UTC, cjlee01 commented on src/modules/10-common/utils/makeGlobal401Handler.tsx
> +    // const triggerLogout/makeGlobalResponseHandler: (accountId: string, history: History) => GlobalResponseHandler = (accountId, history) => { return response => { const username = .... } }
removed the code

2022-04-20 06:26 UTC, cjlee01 commented on src/modules/10-common/utils/makeGlobal401Handler.tsx
> +    // if user lands on /, they'll first get redirected to a path with accountId
removed it

2022-04-20 06:27 UTC, cjlee01 commented on src/framework/app/App.tsx
> +    makeGlobal401Handler(accountId, history)
yeah I realized that I was missing stuff when I checked back

2022-04-21 21:27 UTC, tan-nhu commented on src/modules/10-common/utils/makeGlobal401Handler.tsx
> +  return response => {
The util needs a hook and also accountId.

2022-04-22 04:14 UTC, abhinavrastogi-harness approved these changes

2022-04-22 04:26 UTC, vkbansal approved these changes

2022-04-22 07:41 UTC, ishantmehtaharness submitted a review, later dismissed
Looks Good

2022-04-22 17:19 UTC, tan-nhu submitted a review, later dismissed

2022-04-22 18:33 UTC, tan-nhu approved these changes

2022-04-25 04:51 UTC, abhinavrastogi-harness approved these changes

2022-04-25 08:28 UTC, vkbansal approved these changes

2022-04-25 08:28 UTC, merged