feat: [SRM-10035]: Changes Table changes for SLO Details
harness/harness-core-ui pull request #8406
Opened 2022-04-19 14:41 UTC by shashidhargg

##### Summary:

Changes Table support in SLO Details

##### Jira Links:

https://harness.atlassian.net/browse/SRM-10035

##### Screenshots:

<img width="1493" alt="Screenshot 2022-04-19 at 8 14 23 PM" src="https://user-images.githubusercontent.com/80388547/164030944-6daf4a8d-4364-482b-9e24-b201693e3cf5.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-20 09:49 UTC, deepesh-ui commented
the space between ticker arrow and percentage is  more than expected 
![image](https://user-images.githubusercontent.com/81554936/164201294-d6ba2b7e-e0f0-4d2a-8a5c-0fcc4578a65b.png)

2022-04-20 10:07 UTC, shashidhargg commented
@deepesh-ui it's an existing component. You can see it in the Monitored Service details. I am just using it here.

2022-04-20 10:20 UTC, praneshg239 commented on src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesAndServiceDependency/components/ChangesTable/ChangesTable.tsx
> +  const Wrapper: React.FC = ({ children }) => {
Can we extract this to separate component?

2022-04-20 10:24 UTC, praneshg239 approved these changes

2022-04-20 10:25 UTC, praneshg239 requested changes
Please check the comment

2022-04-21 08:56 UTC, deepesh-ui submitted a review, later dismissed

2022-04-21 10:17 UTC, praneshg239 approved these changes

2022-04-21 10:38 UTC, deepesh-ui approved these changes

2022-04-21 10:38 UTC, merged