feat: [SRM-9968]: adding support for inline creation of monitored service
harness/harness-core-ui pull request #8420
Opened 2022-04-20 08:21 UTC by harshilbits

…vice for SLO

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-20 12:53 UTC, harshilbits commented
retrigger jest

2022-04-21 09:38 UTC, praneshg239 requested changes

2022-04-21 09:38 UTC, praneshg239 commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/SLOName.tsx
> +          onSubmit={() => hideModal()}
`onSubmit={() => hideModal()}` can be given as `onSubmit={hideModal}`. So that it won't get new function instance for every re-render

2022-04-21 09:38 UTC, praneshg239 commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/SLOName.tsx
> +            onClick={() => showModal()}
Same here

2022-04-21 09:52 UTC, chiragp1212 commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/CVCreateSLO.module.scss
> +  border-radius: 4px;
do we need to override dialog css now that we have standard design pattern?

2022-04-21 09:53 UTC, chiragp1212 commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/components/CreateMonitoredServiceFromSLO/CreateMonitoredServiceFromSLO.module.scss
> +      display: none !important;
this feels like a risky workaround

2022-04-21 09:53 UTC, chiragp1212 approved these changes

2022-04-21 09:54 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/SLOName.tsx
> +          }}
Can we make value of initialValues as constant ?
You already have it at  `CreateMonitoredServiceFromSLO.mock.ts`

2022-04-21 09:54 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/components/CreateMonitoredServiceFromSLO/CreateMonitoredServiceFromSLO.tsx
> +  const { serviceRef, environmentRef } = monitoredServiceFormikProps?.values || {}
SLOFormikProps. has no other use  apart from using it's setFieldValue function , we can pass only setFieldValue as prop to this component

2022-04-21 09:54 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/SLOName.tsx
> +                  SLOFormikProps={formikProps}
add only formikProps.setFieldValue as prop

2022-04-21 09:54 UTC, deepesh-ui commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/components/CreateMonitoredServiceFromSLO/CreateMonitoredServiceFromSLO.tsx
> +      fetchingMonitoredServices()
should we await for fetchingMonitoredServices and then show success ?

2022-04-21 10:35 UTC, harshilbits commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/SLOName.tsx
> +          onSubmit={() => hideModal()}
done.

2022-04-21 10:35 UTC, harshilbits commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/SLOName.tsx
> +            onClick={() => showModal()}
done.

2022-04-21 10:56 UTC, harshilbits commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/SLOName.tsx
> +                  SLOFormikProps={formikProps}
monitoredServiceFormikProps is used extensively in the child component.

2022-04-21 10:58 UTC, harshilbits commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/SLOName.tsx
> +          }}
done.

2022-04-21 11:22 UTC, harshilbits commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/components/CreateMonitoredServiceFromSLO/CreateMonitoredServiceFromSLO.tsx
> +  const { serviceRef, environmentRef } = monitoredServiceFormikProps?.values || {}
done.

2022-04-21 11:42 UTC, deepesh-ui submitted a review, later dismissed

2022-04-21 11:48 UTC, harshilbits commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/components/CreateSLOForm/components/SLOName/components/CreateMonitoredServiceFromSLO/CreateMonitoredServiceFromSLO.module.scss
> +      display: none !important;
removed

2022-04-21 11:48 UTC, harshilbits commented on src/modules/85-cv/pages/slos/components/CVCreateSLO/CVCreateSLO.module.scss
> +  border-radius: 4px;
removed

2022-04-21 11:49 UTC, deepesh-ui approved these changes

2022-04-21 11:50 UTC, chiragp1212 approved these changes

2022-04-21 12:10 UTC, merged