feat: [FFM-1777]: UI Left Bar enhancements
harness/harness-core-ui pull request #8440
Opened 2022-04-20 16:14 UTC by Kira-Jennings

- Removed Variations & Prerequisites card backgrounds
- Standardise ID element (Removed “ID: “ text in label)
- archive option already removed
- Standardise breadcrumbs in left bar
- Add value column to variations
- Updated left bar bg
- Tidied up display of saved prerequisites
- Flag Description text position & font style

##### Jira Links:
[FFM-1777: UI Left Bar Enhancements](https://harness.atlassian.net/browse/FFM-1777)

##### Screenshots:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/5584348/164275517-8e7dc8d3-213a-441d-837d-2ff578ea72c7.png">
Multivariate:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/5584348/164275624-bc6fb3ca-039b-460e-abd2-24ddfc1f0aa2.png">

2022-04-20 17:11 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/FlagActivationDetails.module.scss
> +  line-height: '24px' !important;
Instead of using specific weights, sizes and heights, use the `font` prop of `Heading` and `Text` to set a variation. You can find variations [here](https://uicore.harness.io/?path=/story/components-text--basic).

2022-04-21 06:40 UTC, chrisblakely01 reviewed
looks good, just 1 thing around font variations

2022-04-21 06:40 UTC, chrisblakely01 commented on src/modules/75-cf/components/FlagActivation/FlagActivationDetails.tsx
> +            style={{ fontSize: '13px', lineHeight: '20px', fontWeight: 400 }}
probs want to use font variations in here too - can check with @Kseniia-Dudina if you're not sure what font thing to use

2022-04-21 06:40 UTC, chrisblakely01 commented on src/modules/75-cf/components/FlagActivation/FlagActivationDetails.module.scss
> +  // padding: 3px 6px !important;
can remove this if unneeded

2022-04-21 08:35 UTC, knagurski requested changes
Awesome work! Just a few things to do with font variations, styling and `Text`/`Heading`.

2022-04-21 08:35 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/FlagActivationDetails.module.scss
> +  padding: var(--spacing-small) 0 !important;
You should be able to do all of these with the associated props on the `Layout`

2022-04-21 08:35 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/FlagPrerequisites.tsx
> +                {!isFlagTypeBoolean ? flagVariation : getString(`cf.featureFlags.${flagVariation}` as StringKeys)}
String concatenation like this prevents the string tools from working. Can we pull this out into a mapping function or (since it's just true/false), use a ternary to put the strings in whole?
```suggestion
                {!isFlagTypeBoolean ? flagVariation : getString(flagVariation === 'true' ? 'cf.featureFlags.true' : 'cf.featureFlags.false')}
```

2022-04-21 08:35 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/FlagPrerequisites.tsx
> +          text={getString('cf.shared.prerequisites')}
Might be worth asking @Kseniia-Dudina if this button needs to use the _"+ New Prerequisite"_ style as it is a creation button

2022-04-21 08:35 UTC, knagurski commented on src/modules/75-cf/components/IdentifierText/IdentifierText.tsx
> -      </Text>
This needs to be here. The mockups for this page are out of date and this is needed both here and in all the other places it's used.

2022-04-21 08:35 UTC, knagurski commented on src/modules/75-cf/strings/strings.en.yaml
> +  modifiedDate: 'Modified {{date}}'
Might be worth checking with @Kseniia-Dudina to see if these `:` are needed. I have a feeling it's just an old mockup.

2022-04-21 08:38 UTC, Kira-Jennings commented on src/modules/75-cf/components/IdentifierText/IdentifierText.tsx
> -      </Text>
What did the ticket mean for 'standardise ID element'?

2022-04-21 11:12 UTC, knagurski commented on src/modules/75-cf/components/IdentifierText/IdentifierText.tsx
> -      </Text>
I think the ticket description was out of date. This page was out of sync with the rest, but I see from the current version on QA that it is already standardised.

2022-04-21 11:38 UTC, Kira-Jennings commented on src/modules/75-cf/components/FlagActivation/FlagActivationDetails.tsx
> +    <Layout.Vertical margin={{ bottom: 'xlarge' }} id="flagVariationsContainer">
No, force of habit

2022-04-21 14:53 UTC, Kira-Jennings commented on src/modules/75-cf/components/FlagActivation/FlagActivationDetails.module.scss
> +  margin-bottom: var(--spacing-xsmall) !important;
To prevent repetition I chose to put this in a class since I've used it in 3 places

2022-04-21 14:59 UTC, Kira-Jennings commented on src/modules/75-cf/components/FlagActivation/FlagActivationDetails.tsx
> +            style={{ fontSize: '13px', lineHeight: '20px', fontWeight: 400 }}
I just updated the colour here, but I will update the rest to use variations instead of inline style

2022-04-25 09:11 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/FlagActivationDetails.module.scss
> +  font-size: 10px !important;
Looks like `FontVariation.TINY` would do this

2022-04-25 10:48 UTC, knagurski reviewed
Great work and SOOOOO dang close!

2022-04-26 11:22 UTC, Kira-Jennings commented on src/modules/75-cf/components/VariationWithIcon/VariationWithIcon.tsx
> +  textClassName?: string
Nope, removed

2022-04-26 11:28 UTC, Kira-Jennings commented on src/modules/75-cf/components/FlagActivation/FlagActivationDetails.module.scss
> +  font-size: 10px !important;
All except border-radius need it unfortunately. This is that element I found the defects on & required a classname to get around

2022-04-26 11:29 UTC, Kira-Jennings commented on src/modules/75-cf/components/VariationWithIcon/VariationWithIcon.tsx
> +      <Text inline color={Color.GREY_800} font={{ variation: FontVariation.BODY }} style={{ ...textStyle }}>
Updated this

2022-04-26 11:31 UTC, Kira-Jennings commented on src/modules/75-cf/components/FlagActivation/FlagPrerequisites.tsx
> +      {Boolean(featureFlag.prerequisites?.length) &&
I had trouble trying to nest the map from the second check inside the first check 🤔

2022-04-26 12:00 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/FlagActivationDetails.tsx
> +          <Text inline margin={{ bottom: 'small' }} color={Color.GREY_800} font={{ variation: FontVariation.SMALL }}>
Any reason to use `inline` here? It'll swap it from a `<p>` to a `<span>`. It looks like you still want a block-level element.

2022-04-26 12:15 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/FlagPrerequisites.tsx
> +          {featureFlag.prerequisites?.map((elem, i) => {
**No need to change**, but if you don't use `Boolean`, you might find that typescript understands that `prerequisites` exists.
```typescript
{!!featureFlag.prerequisites?.length && (
  <>
    { /* ... */ }
    {featureFlag.prerequisites.map((prereq, index) => {
      // ...
    }
  </>
)}
```

[Here's a wee snippet to illustrate](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBDIKMjJBhLABijBGAG9FCUSgQnE4AI7sITyfQAfny-XYiGk3wA2gBdRQAX2CCE4ghoqyF9IYIwAvMzWfMOZBubyFAVQOKAIy8ABMvAAzNK5YoEaAABSrALs5EGuRG-kBdycZixACUoG1rNd7q5PK9+gCyXgZAAojTME68KANQA+NGK+DuX3wZipwOB2XBFQ4ZoeMheRDx5zA9g0L5uMzMdjqyD8WDQdSJBjAvQiLwAIgTqwYiAW+mHSWxw-ADlQAHJhAA5SASYdBFQAeS+ZHegk7WkgR1QjgUrmkaactZ0wyw+hQCEQ0OEl2bEnj0REBg42IWJhWA4HgghKIA).

2022-04-26 13:04 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/FlagActivationDetails.tsx
> +          textStyle={{ fontSize: '13px' }}
Looks like this is a non-standard font size. Is there a token we can use? I know @Kseniia-Dudina is usually dead-against non-even font sizes. Might be a case of the mockup being incorrect. Worth asking

2022-04-26 16:12 UTC, Kira-Jennings commented on src/modules/75-cf/components/FlagActivation/FlagPrerequisites.tsx
> +          {featureFlag.prerequisites?.map((elem, i) => {
Updated this to remove Boolean

2022-04-28 08:18 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/FlagPrerequisites.tsx
> +      {featureFlag.prerequisites?.length && (
Little gotcha here. If `featureFlag.prerequisites.length` is `0`, it'll actually output that on screen. Use a `!!` to make sure it's a boolean at this stage
```suggestion
      {!!featureFlag.prerequisites?.length && (
```

2022-04-28 08:21 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/__tests__/FlagPrerequisiteItem.test.tsx
> +    expect(container).toMatchSnapshot()
Can we drop this snapshot test? Personally I think they're more trouble than they're worth.

2022-04-28 08:27 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/__tests__/FlagPrerequisiteItem.test.tsx
> +    await waitFor(() => expect(document.querySelector('#deletePrerequisite')).toBeInTheDocument())
Instead of using an id, try to use things that the user can actually see. In this case you should be able to get the `edit` and `delete` by the text. Even better is if you use `getByRole` to select them. I can't remember off hand what the markup is, but if they are buttons, you can use `screen.getByRole('button', { name: 'edit' })`, if they're links, swap the `'button'` for `'link'`. You can also pass a regex as the name if required.

2022-04-28 08:27 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/__tests__/FlagPrerequisiteItem.test.tsx
> +    await waitFor(() => expect(document.querySelector('#deletePrerequisite')).toBeInTheDocument())
You can also put these both in the same `waitFor` block.

2022-04-28 08:34 UTC, knagurski commented on src/modules/75-cf/components/VariationWithIcon/VariationWithIcon.tsx
> +        style={{ marginBottom: 0, ...textStyle }} // will override fontSize if set
Looks like it's setting `xsmall` `margin` with the `margin` prop and then unsetting it with an inline style.

2022-04-28 08:45 UTC, Kira-Jennings commented on src/modules/75-cf/components/VariationWithIcon/VariationWithIcon.tsx
> +        style={{ marginBottom: 0, ...textStyle }} // will override fontSize if set
This shouldn't be here, I think it's an incorrect merge. However, this is how the component existed before I fixed it so I've only improved it

2022-04-28 08:46 UTC, Kira-Jennings commented on src/modules/75-cf/components/FlagActivation/__tests__/FlagPrerequisiteItem.test.tsx
> +    await waitFor(() => expect(document.querySelector('#deletePrerequisite')).toBeInTheDocument())
Like the statements above, yes

2022-04-28 08:47 UTC, Kira-Jennings commented on src/modules/75-cf/components/FlagActivation/__tests__/FlagPrerequisiteItem.test.tsx
> +    await waitFor(() => expect(document.querySelector('#deletePrerequisite')).toBeInTheDocument())
This doesn't work due to the location the Popover is inserted into the DOM, which is nowhere near the HTML that calls it. This is the _only_ way to get it to recognise these buttons

2022-04-28 10:42 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/__tests__/FlagPrerequisiteItem.test.tsx
> +    await waitFor(() => expect(document.querySelector('#deletePrerequisite')).toBeInTheDocument())
When a component is rendered in a test it is wrapped in a container (a `div` by default), which acts as the root of the document. When something creates a new render root (like a popover portal), it does so as a child of that container and a sibling of the component. The `screen` object acts at the container level, not at the component level, so can pick up everything, including the popover. You can have a look at the render output by destructuring the `debug` method out of the return of the `render` call; just call that method whenever you want to see what the document looks like.
```typescript
const { debug } = render(/* ... */)

// ...

debug()
```

Anyway, I had a look-e-see and it looks like you'll hit 2 issues with getting a handle on this with `getByRole`. The first is that the button is rendered as an `<a>` without a `href`, which browsers (and jsdom) treat as having no `role`. We can fix this by adding `role: 'link'` to the `RbacMenuOptionsButton` items.
```typescript
[
  {
    role: 'link',
    icon: 'edit',
    text: getString('edit'),
    onClick: () => handlePrerequisiteInteraction('edit', prerequisite),
    disabled: flagArchived,
    permission: permission
  },
  {
    role: 'link',
    icon: 'cross',
    text: getString('delete'),
    onClick: () => handlePrerequisiteInteraction('delete', prerequisite),
    disabled: flagArchived,
    permission: permission
  }
]
```

The next issue is that jsdom picks up the `desc` tag of the SVG. That means that there are then 2 nodes in the DOM that have the accessible text content of `edit`. That means `getByText` will fail as it will find both. Luckily if we add the `role` to the items, we can then use `getByRole` and use a regex to target.
```suggestion
    await waitFor(() => {
      expect(screen.getByRole('link', { name: /edit/ })).toBeInTheDocument()
      expect(screen.getByRole('link', { name: /delete/ })).toBeInTheDocument()
    })
```

2022-04-28 12:43 UTC, Kira-Jennings commented on src/modules/75-cf/components/FlagActivation/__tests__/FlagPrerequisiteItem.test.tsx
> +    await waitFor(() => expect(document.querySelector('#deletePrerequisite')).toBeInTheDocument())
Nice

2022-04-28 12:45 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/__tests__/FlagPrerequisiteItem.test.tsx
> +    await waitFor(() => expect(document.querySelector('#deletePrerequisite')).toBeInTheDocument())
lol, sorry for the long ramble, it was more for gathering my own thoughts on the approach rather than anything to do with this PR 🤪

2022-04-28 14:58 UTC, knagurski commented on src/modules/75-cf/components/FlagActivation/FlagPrerequisiteItem.tsx
> +  handlePrerequisiteInteraction: (action: 'edit' | 'delete', prereq: Prerequisite) => void
Nice use of narrowing! I actually prefer this over enums personally 👍🏻

2022-04-28 15:05 UTC, knagurski approved these changes
Great job sticking with this!

2022-04-28 15:11 UTC, chrisblakely01 submitted a review, later dismissed

2022-05-09 09:18 UTC, chrisblakely01 approved these changes

2022-05-09 09:19 UTC, merged