feat: [SRM-10085]: Added time range filter support
harness/harness-core-ui pull request #8477
Opened 2022-04-23 10:42 UTC by shashidhargg

##### Summary:

Time filter support for the SLO Details page.

##### Jira Links:

https://harness.atlassian.net/browse/SRM-10085

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-25 13:18 UTC, shashidhargg commented
trigger cypress

2022-04-25 19:08 UTC, vasuki-kalluri approved these changes

2022-04-25 19:26 UTC, tan-nhu requested changes

2022-04-25 19:26 UTC, tan-nhu commented on src/modules/85-cv/pages/slos/CVSLODetailsPage/DetailsPanel/DetailsPanel.module.scss
> +  border: 1px solid rgba(11, 11, 13, 0.1) !important;
Use CSS var name - https://uicore.harness.io/?path=/story/foundation-colors--page&globals=measureEnabled:false

2022-04-25 20:00 UTC, tan-nhu approved these changes

2022-04-25 22:41 UTC, vasuki-kalluri approved these changes

2022-04-26 04:26 UTC, shashidhargg commented
retrigger coverage

2022-04-26 04:26 UTC, shashidhargg commented
trigger cypress

2022-04-26 05:02 UTC, merged