fix: [PIE-3564]: written test cases to improve coverage
harness/harness-core-ui pull request #8519
Opened 2022-04-26 06:16 UTC by satyam-harness

##### Summary:

##### Jira Links:
https://harness.atlassian.net/browse/PIE-3564

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-26 08:59 UTC, ishantmehtaharness commented on src/modules/70-pipeline/components/GitPopover/__test__/GitPopover.test.tsx
> +    await waitFor(() => expect(getByText('PIPELINE.GITDETAILS')).toBeDefined())
Do you want to assert something after waiting for this?

2022-04-26 09:00 UTC, ishantmehtaharness commented on src/modules/70-pipeline/components/GitPopover/__test__/GitPopoverInfo.test.tsx
> +    expect(container).toMatchInlineSnapshot(`
Can you move this to `toMatchSnapshot` rather than `toMatchInlineSnapshot`

2022-04-26 09:01 UTC, ishantmehtaharness commented on src/modules/70-pipeline/components/LogsContent/__tests__/LogsContent.test.tsx
> +    test('SingleSectionLogs', async () => {
we dont need async here, since there is no await

2022-04-26 09:02 UTC, satyam-harness commented on src/modules/70-pipeline/components/LogsContent/LogsState/utils.ts
> +          status: 'FAILED' as UnitLoadingStatus,
yes, because status has a type of UnitLoadingStatus, it was throwing error if not added

2022-04-26 09:05 UTC, ishantmehtaharness commented on src/modules/70-pipeline/pages/execution/ExecutionPipelineView/ExecutionLogView/__tests__/__snapshots__/Summary.test.tsx.snap
> +    summaryElement
This should be `summaryElement ` or the value of summaryElement = `<div />`

2022-04-26 09:06 UTC, satyam-harness commented on src/modules/70-pipeline/components/LogsContent/__tests__/LogsContent.test.tsx
> +    test('SingleSectionLogs', async () => {
ohh yes, forgot to remove that

2022-04-26 09:07 UTC, satyam-harness commented on src/modules/70-pipeline/pages/execution/ExecutionPipelineView/ExecutionLogView/__tests__/__snapshots__/Summary.test.tsx.snap
> +    summaryElement
yeah actually this file is currently not in use anywhere, so dummy summaryElement was written there, and we needed to pass a ReactElement as summaryElement so used <div />

2022-04-26 09:09 UTC, ishantmehtaharness commented on src/modules/75-cd/components/PipelineStudio/__test__/CDPipelineStagesUtils.test.tsx
> +    expect(argsMock.getNewStageFromType).toBeCalled()
We can improvise on this by using `toBeCalledWith`

2022-04-26 09:10 UTC, ishantmehtaharness reviewed
Added comments

2022-04-26 09:10 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/GitPopover/__test__/GitPopover.test.tsx
> +    await waitFor(() => expect(getByText('PIPELINE.GITDETAILS')).toBeDefined())
Could you please also add assertion for repo, branch etc., if not already added in other test cases.
Also, do not send repo, branch etc through props and check through assertion that those detail is not appearing in popover.

2022-04-26 09:11 UTC, satyam-harness commented on src/modules/70-pipeline/components/GitPopover/__test__/GitPopover.test.tsx
> +    await waitFor(() => expect(getByText('PIPELINE.GITDETAILS')).toBeDefined())
upon mouseOver, async operation will happen so actually we are waiting for  PIPELINE.GITDETAILS to appear then assert it inplace

2022-04-26 09:14 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/GitPopover/__test__/GitPopoverInfo.test.tsx
> +    expect(container).toMatchInlineSnapshot(`
Agreed with Ishant. Also, these are all just empty DOM elements, there is no content inside any of **<p>** tags. Could you please required props properly, so that content appears properly in snapshot.

2022-04-26 09:18 UTC, satyam-harness commented on src/modules/70-pipeline/components/GitPopover/__test__/GitPopover.test.tsx
> +    await waitFor(() => expect(getByText('PIPELINE.GITDETAILS')).toBeDefined())
one test is written for the case when repoIdentifier is not passed

2022-04-26 09:19 UTC, satyam-harness commented on src/modules/70-pipeline/components/GitPopover/__test__/GitPopoverInfo.test.tsx
> +    expect(container).toMatchInlineSnapshot(`
done, thanks

2022-04-26 09:22 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineStudio/__test__/CDPipelineStagesUtils.test.tsx
> +    expect(argsMock.getNewStageFromType).toBeCalled()
done

2022-04-26 09:32 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/GitPopover/GitPopoverInfo.tsx
> -  return content && content.length ? (
I think, the exiting implementation was better. This change could introduce bugs, if content string is empty. Also, it is extra work for every consumer to filter content which is empty. So, it would have been better if this change was not done.

2022-04-26 09:34 UTC, satyam-harness commented
retrigger jest

2022-04-26 09:41 UTC, ishantmehtaharness commented on src/modules/70-pipeline/components/GitPopover/GitPopoverInfo.tsx
> -  return content && content.length ? (
Actually its used only at one place
but agreed with @chetanvekariya-harness , this safe check provides extra stability

2022-04-26 09:41 UTC, ishantmehtaharness commented on src/modules/70-pipeline/components/GitPopover/GitPopoverInfo.tsx
> -  return content && content.length ? (
@satyam-harness Can you add it back

2022-04-26 09:52 UTC, satyam-harness commented
retrigger jest

2022-04-26 11:44 UTC, chetanvekariya-harness approved these changes

2022-04-26 12:20 UTC, ishantmehtaharness approved these changes
looks good now. thanks

2022-04-26 12:29 UTC, kapilkumawat86 submitted a review, later dismissed

2022-04-27 04:44 UTC, vkbansal requested changes

2022-04-27 04:44 UTC, vkbansal commented on src/modules/70-pipeline/components/LogsContent/LogsState/utils.ts
> +    logKeys: [
This is not test data. This actual production data. Please revert this change.

2022-04-27 05:10 UTC, chetanvekariya-harness requested changes
Please go through each and every line of the change, make sure the change is intentional

2022-04-27 05:10 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/CommonPipelineStages/ApprovalStage/__tests__/ApprovalStageTestsHelper.tsx
> +export const stepsMock = {
Looks like this is not used anywhere. Remove this as well.

2022-04-27 05:17 UTC, satyam-harness commented on src/modules/70-pipeline/components/CommonPipelineStages/ApprovalStage/__tests__/ApprovalStageTestsHelper.tsx
> +export const stepsMock = {
removed this is latest push

2022-04-27 05:17 UTC, satyam-harness commented on src/modules/70-pipeline/components/LogsContent/LogsState/utils.ts
> +    logKeys: [
reverted, thanks. Added test data separately

2022-04-27 06:16 UTC, chetanvekariya-harness requested changes

2022-04-27 06:16 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/LogsContent/LogsState/utils.ts
> +export const testReducerState: State = {
mock data should not be with actual code file. Create other util or helper file inside **__test__** folder.

2022-04-27 09:34 UTC, chetanvekariya-harness approved these changes

2022-04-28 04:58 UTC, merged