feat: [STO-4451]: STO Pipelines and Deployments pages
harness/harness-core-ui pull request #8563
Opened 2022-04-27 21:53 UTC by chris-harness

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-16 17:16 UTC, chris-harness commented
retrigger jest

2022-05-16 17:25 UTC, chris-harness commented
retrigger jest

2022-05-16 17:57 UTC, chris-harness commented
Jest failure is intermittent, and passes on my local

2022-05-16 17:58 UTC, chris-harness commented
retrigger jest

2022-05-16 17:58 UTC, chris-harness commented
retrigger coverage

2022-05-16 19:01 UTC, nanaxuHarness commented on src/modules/70-pipeline/pages/pipeline-deployment-list/PipelineDeploymentList.tsx
> +    case 'ci':
can we use Module enum here

2022-05-16 19:08 UTC, nanaxuHarness commented on src/modules/85-sto-steps/components/STOExecutionCardSummary/STOExecutionCardSummary.tsx
> +      {issueCounts?.critical ? <SeverityPill severity={SeverityCode.Critical} value={issueCounts.critical} /> : <></>}
can we do `issueCounts?.critical && <SeverityPill severity={SeverityCode.Critical} value={issueCounts.critical} />` here

2022-05-16 19:08 UTC, nanaxuHarness commented on src/modules/85-sto-steps/components/STOExecutionCardSummary/__tests__/STOExecutionCardSummary.test.tsx
> +jest.mock('@blueprintjs/core', () => {
why do we need to mock this?

2022-05-16 19:10 UTC, nanaxuHarness commented on src/modules/85-sto-steps/components/STOSideNav/STOSideNav.tsx
> +    module: 'sto'
can we use Module enum here

2022-05-16 19:11 UTC, nanaxuHarness commented on src/modules/85-sto-steps/strings/strings.en.yaml
> +noScansRunPipelineText: No Security Test pipelines have run, yet. Click the button below to run a pipeline.
do we need the `,` here?

2022-05-16 20:04 UTC, chris-harness commented on src/modules/70-pipeline/pages/pipeline-deployment-list/PipelineDeploymentList.tsx
> +    case 'ci':
Refactored to use the `Module` type for this prop

2022-05-16 20:04 UTC, chris-harness commented on src/modules/85-sto-steps/components/STOExecutionCardSummary/STOExecutionCardSummary.tsx
> +      {issueCounts?.critical ? <SeverityPill severity={SeverityCode.Critical} value={issueCounts.critical} /> : <></>}
Yes! fixed

2022-05-16 20:04 UTC, tan-nhu commented on src/modules/70-pipeline/pages/pipelines/PipelinesPage.tsx
> +    module: module,
Value and key is the same. We can ignore value

2022-05-16 20:05 UTC, chris-harness commented on src/modules/70-pipeline/pages/pipeline-deployment-list/images/security-tests-illustration.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="120" height="75" fill="none" viewBox="0 0 120 75">
Not sure it's necessary. It renders the expected, consistent size due to existing CSS.

2022-05-16 20:06 UTC, chris-harness commented on src/modules/70-pipeline/pages/pipelines/PipelinesPage.tsx
> +    module: module,
Yeah, noticed this as well. Fixed

2022-05-16 20:13 UTC, chris-harness commented on src/modules/85-sto-steps/components/STOExecutionCardSummary/__tests__/STOExecutionCardSummary.test.tsx
> +jest.mock('@blueprintjs/core', () => {
It's done to inject a test ID

2022-05-16 20:15 UTC, chris-harness commented on src/modules/85-sto-steps/components/STOSideNav/STOSideNav.tsx
> +    module: 'sto'
The `Module` type ensures it is valid. Not aware of any enum for this.

2022-05-16 20:15 UTC, chris-harness commented on src/modules/85-sto-steps/strings/strings.en.yaml
> +noScansRunPipelineText: No Security Test pipelines have run, yet. Click the button below to run a pipeline.
removed

2022-05-16 20:52 UTC, chris-harness commented
retrigger coverage

2022-05-16 20:52 UTC, chris-harness commented
retrigger jest

2022-05-16 22:01 UTC, chris-harness commented
retrigger coverage

2022-05-16 22:02 UTC, chris-harness commented
retrigger jest

2022-05-16 22:03 UTC, chris-harness commented
retrigger eslint

2022-05-17 04:25 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/pages/deployments-list/__tests__/DeploymentsList.test.tsx
> +    useParams.mockImplementation(() => {
this should be passed as part of the test wrapper. The test wrapper has a prop for pathParams

2022-05-17 04:29 UTC, AshwinBhatkal-Harness commented on src/modules/10-common/utils/routeUtils.ts
> +export const moduleFromPathParam = (module: Module): ModuleName | null => {
What do we need this for?
We already have moduleToModuleNameMapping, can we use that instead?

2022-05-17 04:31 UTC, vkbansal requested changes

2022-05-17 04:31 UTC, vkbansal commented on src/modules/70-pipeline/pages/pipeline-deployment-list/PipelineDeploymentList.tsx
> +  const module: Module = moduleFromPathParam(modulePathParam) || 'cd'
This is not the right way of doing this. We already have a `useModuleInfo` hook for this kind of use case. Please use that.

2022-05-17 04:31 UTC, vkbansal commented on src/modules/10-common/utils/routeUtils.ts
> +export const moduleFromPathParam = (module: Module): ModuleName | null => {
Use `useModuleInfo` hook instead. This is not reliable.

2022-05-17 15:25 UTC, chris-harness commented on src/modules/70-pipeline/pages/pipeline-deployment-list/PipelineDeploymentList.tsx
> +  const module: Module = moduleFromPathParam(modulePathParam) || 'cd'
Done

2022-05-17 15:25 UTC, chris-harness commented on src/modules/10-common/utils/routeUtils.ts
> +export const moduleFromPathParam = (module: Module): ModuleName | null => {
Done

2022-05-17 17:33 UTC, chris-harness commented
retrigger jest

2022-05-17 18:07 UTC, chris-harness commented on src/modules/70-pipeline/pages/deployments-list/__tests__/DeploymentsList.test.tsx
> +    useParams.mockImplementation(() => {
fixed tests to do it the right way

2022-05-17 18:21 UTC, nanaxuHarness submitted a review, later dismissed

2022-05-17 19:21 UTC, tan-nhu approved these changes

2022-05-17 19:32 UTC, tan-nhu approved these changes

2022-05-17 20:56 UTC, vasuki-kalluri approved these changes

2022-05-18 03:58 UTC, vkbansal approved these changes

2022-05-18 04:07 UTC, AshwinBhatkal-Harness approved these changes

2022-05-18 14:27 UTC, merged