fix: [PL-24273]: Prevent identifier change during connector edit via YAML
harness/harness-core-ui pull request #8566
Opened 2022-04-28 05:51 UTC by tiwaritejas

##### Summary:

Resolved by passing connector id in the getYamlSchema API. The immutability is handled by the YAML framework.

##### Jira Links:

https://harness.atlassian.net/browse/PL-24273

##### Screenshots:

<img width="1680" alt="Screenshot 2022-04-28 at 11 17 07 AM" src="https://user-images.githubusercontent.com/97941439/165685294-96fa24d1-20bb-42d6-a4a5-2c17e243dbeb.png">
<img width="1680" alt="Screenshot 2022-04-28 at 11 17 10 AM" src="https://user-images.githubusercontent.com/97941439/165685312-afcc6baa-26b9-4269-b5e2-ba596b982f8a.png">
<img width="1680" alt="Screenshot 2022-04-28 at 11 17 16 AM" src="https://user-images.githubusercontent.com/97941439/165685318-a0b9556c-d8de-4419-b191-4203db969fc2.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-04-28 06:00 UTC, tiwaritejas commented
retrigger titlecheck

2022-04-28 06:24 UTC, tiwaritejas commented
retrigger titlecheck

2022-04-28 06:49 UTC, tiwaritejas commented
retrigger titlecheck

2022-04-28 07:06 UTC, tiwaritejas commented
retrigger titlecheck

2022-05-04 04:26 UTC, tiwaritejas commented
trigger cypress

2022-05-04 05:02 UTC, upadhyay-an approved these changes

2022-05-04 05:04 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/__tests__/ConnectorView.test.tsx
> +    await act(async () => {
not need of async await in act

2022-05-04 05:06 UTC, meenakshi-harness requested changes

2022-05-04 05:06 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/__tests__/ConnectorView.test.tsx
> +    await act(async () => {
no need of async await in act

2022-05-04 05:06 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/__tests__/ConnectorView.test.tsx
> +      expect(switchToYAML).toBeTruthy()
you can wait for till here then put fireEvent.click in act and then again wait For some text

2022-05-04 05:06 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/__tests__/ConnectorView.test.tsx
> +      fireEvent.click(editDetailsBtn!)
same

2022-05-04 05:06 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/__tests__/ConnectorView.test.tsx
> +    expect(container).toMatchSnapshot()
After save we expect some call to be made for saving connector. We can assert that instead of asserting snapshot.

2022-05-04 05:48 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/__tests__/ConnectorView.test.tsx
> +    fireEvent.click(switchToYAML!)
put this inside act

2022-05-04 05:48 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/__tests__/ConnectorView.test.tsx
> +    fireEvent.click(editDetailsBtn!)
same. Any state changing action should be inside act

2022-05-04 05:49 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/__tests__/ConnectorView.test.tsx
> +    waitFor(() => {
await on this

2022-05-04 05:50 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/__tests__/ConnectorView.test.tsx
> +    waitFor(() => expect(getByText('spec')))
await on this

2022-05-04 08:54 UTC, meenakshi-harness approved these changes

2022-05-04 08:57 UTC, upadhyay-an approved these changes

2022-05-04 08:57 UTC, merged