feat:[CDB-179]: Custom Dashboards - Ability to open a Folder in a new tab
harness/harness-core-ui pull request #8642
Opened 2022-05-03 11:36 UTC by Harness-JKhattak

##### Summary:

- Split FolderCard logic into separate component
- Added Unit tests to test this new component
- Added ability to open a Folder within a new tab through the browser specific right click context menu or CMD+click by wrapping the component in a React-Router Link.
- Created new "interfaces" folder within module folder for module specific interfaces

##### Jira Links:

[CDB-179](https://harness.atlassian.net/browse/CDB-179)

##### Screenshots:

![Screenshot 2022-05-03 at 12 33 38](https://user-images.githubusercontent.com/103499516/166445668-84625598-8c6f-4279-867b-70100c5809cf.png)

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-03 11:39 UTC, Harness-JKhattak commented
retrigger titlecheck

2022-05-04 09:13 UTC, Harness-JKhattak commented
retrigger jest

2022-05-05 10:35 UTC, sean-harness approved these changes

2022-05-05 11:11 UTC, meenakshi-harness commented on src/modules/45-dashboards/components/FolderCard/FolderCard.tsx
> +    folderId: folder?.id ? folder?.id : 'shared',
null check  in folder?.id not needed the second time

2022-05-05 11:11 UTC, meenakshi-harness commented on src/modules/45-dashboards/components/FolderCard/FolderCard.tsx
> +    folderId: folder?.id ? folder?.id : 'shared',
or better use. -->  folder?.id  ?? 'shared'

2022-05-05 11:12 UTC, meenakshi-harness commented on src/modules/45-dashboards/components/FolderCard/FolderCard.tsx
> +                    text="Delete"
use getString

2022-05-05 11:15 UTC, meenakshi-harness requested changes

2022-05-05 11:15 UTC, meenakshi-harness commented on src/modules/45-dashboards/components/FolderCard/FolderCard.tsx
> +            <Text color={Color.BLACK_100} font={{ size: 'medium', weight: 'semi-bold' }}>
Use FontVariation

2022-05-05 11:15 UTC, meenakshi-harness commented on src/modules/45-dashboards/components/FolderCard/FolderCard.tsx
> +            </Text>
Render whole Text  element only if folder?.name is defined

2022-05-05 11:15 UTC, meenakshi-harness commented on src/modules/45-dashboards/components/FolderCard/FolderCard.tsx
> +              font={{ size: 'medium', weight: 'semi-bold' }}
FontVariation

2022-05-05 11:15 UTC, meenakshi-harness commented on src/modules/45-dashboards/components/FolderCard/__tests__/FolderCard.test.tsx
> +  await act(async () => {
no need of await in act. wait for some element post act

2022-05-05 11:15 UTC, meenakshi-harness commented on src/modules/45-dashboards/components/FolderCard/__tests__/FolderCard.test.tsx
> +  })
any assertion post clicking?

2022-05-05 11:15 UTC, meenakshi-harness commented on src/modules/45-dashboards/components/FolderCard/__tests__/FolderCard.test.tsx
> +    fireEvent.click(button)
move this inside act

2022-05-05 11:16 UTC, meenakshi-harness commented on src/modules/45-dashboards/components/FolderCard/__tests__/FolderCard.test.tsx
> +    expect(screen.getByText(testFolder.name)).toBeInTheDocument()
await wait for this.. else this might be flaky

2022-05-05 11:17 UTC, meenakshi-harness commented on src/modules/45-dashboards/components/FolderCard/__tests__/FolderCard.test.tsx
> +    fireEvent.click(screen.getByText('Delete'))
move inside act (any state changing action)

2022-05-05 12:16 UTC, Harness-JKhattak commented on src/modules/45-dashboards/components/FolderCard/__tests__/FolderCard.test.tsx
> +    fireEvent.click(button)
That's in a function that specifically is for re-use within tests to open that context menu

2022-05-05 12:17 UTC, Harness-JKhattak commented on src/modules/45-dashboards/components/FolderCard/__tests__/FolderCard.test.tsx
> +  })
That's within a function that's used within a few separate tests just to open the context menu

2022-05-05 12:20 UTC, Harness-JKhattak commented on src/modules/45-dashboards/components/FolderCard/FolderCard.tsx
> +            </Text>
Removed optional chain as it's not needed

2022-05-05 13:06 UTC, meenakshi-harness approved these changes

2022-05-05 14:08 UTC, DFieldFL approved these changes

2022-05-05 14:09 UTC, sean-harness approved these changes

2022-05-05 14:50 UTC, kapilkumawat86 approved these changes

2022-05-05 14:51 UTC, merged