fix: [PL-25027]: release branch cut script changes
harness/harness-core-ui pull request #8727
Opened 2022-05-06 18:10 UTC by mayankVermaHarness

##### Summary:

After branching strategy change, the release branch cut process was broken and needed to be fixed.
There are 2 parts to it:

1. Script changes: part of this PR.

2. Pipeline changes: `stage.harness.io` pipeline needs to be updated with the code below: https://stage.harness.io/ng/#/account/wFHXHD0RRQWoO8tIZT5YVw/ci/orgs/Harness/projects/RELEASEBUILDS/pipelines/nextGenUI_cutBranch/pipeline-studio/

```
function print_err(){
    local_cmd_status=$1
    local_cmd_name=$2
    if [ "$local_cmd_status" != 0 ]; then
        echo "ERROR: Line $LINENO: $2 Command Failed... Exiting..."
        exit 1
    fi
}

# Set up Github Package Registry token
echo @harness:registry=https://npm.pkg.github.com > .npmrc
echo "//npm.pkg.github.com/:_authToken="<+pipeline.variables.GITHUB_BOT_TOKEN> >> .npmrc
echo always-auth=true >> .npmrc

# configure git
git config --global user.email "bot@harness.io"
git config --global user.name "bot-harness"
#git remote set-url origin 'https://bot-harness:${BOT_PASSWORD}@github.com/wings-software/nextgenui.git'
git remote set-url origin https://<+pipeline.variables.GITHUB_BOT_TOKEN>:x-oauth-basic@github.com/harness/harness-core-ui.git

# To get all the git history which helps in updating jira tickets
git fetch --unshallow
git fetch --all

sh scripts/ci/release-branch-cut.sh
print_err "$?" "\"RELEASE_BRANCH_CUT\""

```

##### Jira Links:

https://harness.atlassian.net/browse/PL-24951

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-07 04:51 UTC, diptiman-adak requested changes

2022-05-07 04:51 UTC, diptiman-adak commented on scripts/ci/release-branch-cut.sh
> +git checkout -b $NEW_BRANCH
This branch cut should happen from master always. Not from develop

2022-05-08 08:05 UTC, mayankVermaHarness commented on scripts/ci/release-branch-cut.sh
> +git checkout -b $NEW_BRANCH
You are right. I have done the requested changes

2022-05-08 12:05 UTC, diptiman-adak approved these changes

2022-05-08 12:07 UTC, merged