fix: [CDS-36473]: fixed time filter reset issue for (home, services, overview) dashboards.
harness/harness-core-ui pull request #8729
Opened 2022-05-07 20:24 UTC by Sagar-Rajput7

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-07 20:31 UTC, Sagar-Rajput7 commented
retrigger titlecheck

2022-05-10 06:27 UTC, abhinavrastogi-harness requested changes

2022-05-10 06:27 UTC, abhinavrastogi-harness commented on src/modules/10-common/hooks/useSessionStorage.ts
> +export const useSessionStorage = <T>(
we already have existing hooks for session storage.
In fact, we should consider using the Preference Framework, instead of directly writing to session storage.

2022-05-10 09:14 UTC, Sagar-Rajput7 commented on src/modules/10-common/hooks/useSessionStorage.ts
> +export const useSessionStorage = <T>(
yes, we can use `useLocalStorage` hook (with window.sessionStorage as props) thanks for suggesting this.

And regarding using Preference Framework - our use case here in this ticket is to clear sessionStorage after logout but with `usePreferenceStore` we work more around storing after logout, so we can't use that here I guess.

2022-05-11 09:12 UTC, Sagar-Rajput7 commented
dockerize

2022-05-23 12:54 UTC, Sagar-Rajput7 commented on src/modules/10-common/hooks/useSessionStorage.ts
> +export const useSessionStorage = <T>(
Following this Ticket in this branch - https://github.com/harness/harness-core-ui/pull/9003

**Closing this one**

- used existing useLocalStorageHook 
- existing secureStorage helped with clearing storage after logout

2022-05-23 12:54 UTC, closed without merging