feat: [CCM-7489]: Perspective Builder Enhancements
harness/harness-core-ui pull request #8734
Opened 2022-05-09 06:17 UTC by rajarshee-harness

##### Summary:

##### Jira Links:

https://harness.atlassian.net/browse/CCM-7489

##### Screenshots:

<img width="1678" alt="Screenshot 2022-05-09 at 11 47 15 AM" src="https://user-images.githubusercontent.com/97532027/167351301-4bf9cddd-73fa-4610-a060-f034eae4be1c.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-11 11:42 UTC, rajarshee-harness commented
retrigger jest

2022-05-11 11:48 UTC, rishik30 requested changes

2022-05-11 11:48 UTC, rishik30 commented on src/modules/75-ce/components/MultiValueSelectorComponent/PerspectiveBuilderMultiValueSelector.tsx
> +    const allowToFetchMore = shouldFetchMore
what's the need of duplicate variable when we already have the boolean value in props?

2022-05-11 11:48 UTC, rishik30 commented on src/modules/75-ce/components/MultiValueSelectorComponent/PerspectiveBuilderMultiValueSelector.tsx
> +            const re = new RegExp(splitAt, 'g')
try to have some descriptive names for the variables.

2022-05-11 11:48 UTC, rishik30 commented on src/modules/75-ce/components/MultiValueSelectorComponent/PerspectiveBuilderMultiValueSelector.tsx
> +      {searchText && searchText?.length > 0 && !filteredValues.includes(searchText) ? (
we can store the value of this check in a variable and use that as it's being used in couple of places.

2022-05-11 11:48 UTC, rishik30 commented on src/modules/75-ce/components/MultiValueSelectorComponent/PerspectiveBuilderMultiValueSelector.tsx
> +                    key={i}
have some unique key, no index in the key

2022-05-11 11:48 UTC, rishik30 commented on src/modules/75-ce/components/PerspectiveBuilderFilters/views/OperandSelector.tsx
> +          {provider?.id && service?.id ? `${provider.name || provider.id} > ${service.name}` : 'Choose Operand'}
put it in strings

2022-05-11 12:45 UTC, rajarshee-harness commented
retrigger jest

2022-05-11 12:58 UTC, rajarshee-harness commented
retrigger jest

2022-05-12 07:10 UTC, jyotiarora-harness commented on src/modules/75-ce/pages/business-mapping/BusinessMapping.tsx
> +  const NewCostVategoryDrawer = (
Correct the spelling `NewCostVategoryDrawer`, it should be `NewCostCategoryDrawer`

2022-05-12 07:16 UTC, jyotiarora-harness commented on src/modules/75-ce/components/MultiValueSelectorComponent/PerspectiveBuilderMultiValueSelector.tsx
> +                  <Icon name="spinner" size={20} color="blue500" />
Don't use the color codes like this, use it like this `Color.BLUE_500`

2022-05-12 07:45 UTC, rajarshee-harness commented
retrigger jest

2022-05-12 07:54 UTC, rishik30 approved these changes

2022-05-12 08:00 UTC, jyotiarora-harness approved these changes

2022-05-12 08:10 UTC, merged