feat: [GTM-1010]: add extra CCM telemetry events
harness/harness-core-ui pull request #8758
Opened 2022-05-09 18:35 UTC by nanaxuHarness

##### Summary:

this is to add more CCM telemetry events for better data quality
1) add all CCM page events
2) add more sign up flow track events

##### Jira Links:

https://harness.atlassian.net/browse/PLG-1010

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-17 14:50 UTC, nanaxuHarness commented
retrigger jest

2022-05-17 17:23 UTC, rishik30 submitted a review, later dismissed

2022-05-31 17:35 UTC, nanaxuHarness commented on src/modules/10-common/constants/TrackingConstants.ts
>    StartCreateConnector = 'Start Create Connector',
Create Connector Started

2022-05-31 17:35 UTC, nanaxuHarness commented on src/modules/10-common/pages/pageContext/PageName.ts
> +  CETrialHomePage = 'CETrialHomePage',
CCM Trial Home

2022-05-31 17:38 UTC, nanaxuHarness commented on src/modules/10-common/constants/TrackingConstants.ts
> +  CEGcpConnectorBillingExportLoad = 'CE Gcp Connector Billing Export Loaded',
CE => CCM

2022-05-31 17:46 UTC, nanaxuHarness commented on src/modules/10-common/constants/TrackingConstants.ts
> +  CEK8 = 'CEK8sCluster',
keep CE here

2022-06-02 18:09 UTC, abhinavrastogi-harness commented on src/modules/10-common/constants/TrackingConstants.ts
> +export enum ConnectorTypes {
we already have a connector types enum. why do we need to create a duplicate?
https://github.com/harness/harness-core-ui/blob/develop/src/modules/35-connectors/constants.ts#L64

2022-06-02 18:09 UTC, abhinavrastogi-harness commented on src/modules/35-connectors/components/CreateConnector/AWSCodeCommitConnector/AWSCCAuthStep.tsx
> +  React.useEffect(() => {
this useEffect is repeated in a lot of places.
can we create a custom hook version of trackEvent, which includes the useEffect? Something like:

```
import { useTrackEvent } from '@common/hooks/useTelemetry`

useTrackEvent({ ... })
```

2022-06-02 18:09 UTC, abhinavrastogi-harness commented on src/modules/35-connectors/components/CreateConnector/CEK8sConnector/SecretCreationStep.tsx
> +    trackEvent(ConnectorActions.SecretCreationStepSubmit, {
i hope `trackEvent` can never throw an exception... even if the n/w call fails or returns 400/404/500.
It'll block the actual user action.

2022-06-02 18:09 UTC, abhinavrastogi-harness commented on src/modules/75-ce/modals/CETrialModal/useCETrialModal.tsx
> +                trackEvent(CCMActions.CCMStartPlanContinue, {
trackEvent should be called in the `onContinue` function.. user can click multiple times on a button. I'm expecting that onContinue will handle that internally.

2022-06-03 20:18 UTC, nanaxuHarness commented on src/modules/75-ce/modals/CETrialModal/useCETrialModal.tsx
> +                trackEvent(CCMActions.CCMStartPlanContinue, {
the `onContinue` is also called whenever the dialog is closed, we only want to track it when user clicks on the button.
```
      <Dialog
        isOpen={true}
        enforceFocus={false}
        canOutsideClickClose={false}
        canEscapeKeyClose={false}
        onClose={onContinue}
        className={cx(css.dialog, css.ceTrial)}
      >
```

2022-06-03 21:01 UTC, nanaxuHarness commented on src/modules/35-connectors/components/CreateConnector/CEK8sConnector/SecretCreationStep.tsx
> +    trackEvent(ConnectorActions.SecretCreationStepSubmit, {
this is a very fair concern, I couldn't find very details of this from the website, but they do have this about retries: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/ajs-classic/#retries

2022-06-03 22:10 UTC, nanaxuHarness commented on src/modules/10-common/constants/TrackingConstants.ts
> +export enum ConnectorTypes {
still these 3 no mappings yet, so save them here.

2022-06-03 22:39 UTC, nanaxuHarness commented on src/modules/35-connectors/components/CreateConnector/AWSCodeCommitConnector/AWSCCAuthStep.tsx
> +  React.useEffect(() => {
updated

2022-06-06 16:39 UTC, abhinavrastogi-harness submitted a review, later dismissed

2022-06-07 05:21 UTC, rishik30 requested changes

2022-06-07 05:21 UTC, rishik30 commented on src/modules/75-ce/RouteDestinations.tsx
> +          pageName={PAGE_NAME.CECODashboardPage}
this is a different page route. It's not a dashboard but the start of creating AS rules. We should have a different name for this page.

2022-06-07 05:31 UTC, nanaxuHarness commented on src/modules/75-ce/RouteDestinations.tsx
> +          pageName={PAGE_NAME.CECODashboardPage}
good catch!

2022-06-07 05:42 UTC, rishik30 approved these changes

2022-06-07 05:43 UTC, reetika04 approved these changes

2022-06-07 05:47 UTC, merged