feat: [PL-24308]: Git simplification changes
harness/harness-core-ui pull request #8764
Opened 2022-05-10 04:36 UTC by sunnykesh-harness

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-19 07:50 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/pages/pipeline-details/PipelineDetails.tsx
> +    if (repoIdentifier && !storeType) {
I don't understand this change.

2022-05-25 08:27 UTC, avinashmadhwani02 commented
dockerize

2022-05-25 08:45 UTC, chetanvekariya-harness commented
dockerize

2022-05-25 11:06 UTC, chetanvekariya-harness commented
dockerize

2022-05-26 08:30 UTC, chetanvekariya-harness commented
dockerize

2022-05-27 03:40 UTC, kapilkumawat86 commented on src/modules/10-common/components/ErrorHandler/ErrorHandler.module.scss
> +.v2.container {
remove this, unused styles

2022-05-27 03:41 UTC, kapilkumawat86 commented on src/modules/10-common/components/GitRemoteDetails/GitRemoteDetails.module.scss
> +      padding-left: 8px !important;
use variables

2022-05-27 04:13 UTC, kapilkumawat86 requested changes
Remove three empty files

2022-05-27 04:13 UTC, kapilkumawat86 commented on src/modules/70-pipeline/components/PipelineStudio/CreateModal/PipelineCreate.tsx
> +      info: 'Pipeline content is stored in Harness',
Hardcoded strings and use Enums

2022-05-27 04:13 UTC, kapilkumawat86 commented on src/modules/70-pipeline/components/PipelineStudio/CreateModal/PipelineCreate.tsx
> +          name: NameSchema({ requiredErrorMsg: getString('createPipeline.pipelineNameRequired') }),
move this validation as separate function

2022-05-27 10:28 UTC, chetanvekariya-harness commented
dockerize

2022-05-27 15:51 UTC, kapilkumawat86 approved these changes

2022-05-27 15:51 UTC, vkbansal approved these changes

2022-05-28 06:58 UTC, sunnykesh-harness commented
dockerize

2022-05-28 07:23 UTC, kapilkumawat86 submitted a review, later dismissed

2022-05-28 08:58 UTC, vardanbansal-harness commented on src/modules/72-triggers/pages/triggers/TriggersDetailPage.tsx
> +    () => isGitSyncEnabled || isGitSimplificationEnabled,
I will update this check to `isGitSyncEnabled && isGitSimplificationEnabled` so that it excludes inline pipelines for the changes.

2022-05-28 09:06 UTC, vardanbansal-harness approved these changes
Reviewed CI specific changes

2022-05-28 11:31 UTC, sunnykesh-harness commented
trigger cypress

2022-05-28 11:36 UTC, kapilkumawat86 approved these changes

2022-05-28 11:36 UTC, merged