fix: [CCM-7606]: doc link fixes on connector error screen
harness/harness-core-ui pull request #8807
Opened 2022-05-11 08:17 UTC by jyotiarora-harness

##### Summary:

Documentation link fixes on connector test connection screen

##### Jira Links:

https://harness.atlassian.net/browse/CCM-7606

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-16 05:41 UTC, jyotiarora-harness commented
retrigger titlecheck

2022-05-19 07:25 UTC, meenakshi-harness requested changes

2022-05-19 07:25 UTC, meenakshi-harness commented on src/modules/35-connectors/pages/connectors/views/connectivityStatus/ConnectivityStatus.tsx
> +  const isCeConnector = ceConnectors.includes(data.connector?.type as string)
I see this same logic is used before at some other place. Can we move it to a util and then use at both places. 
Also if possible can we rename it to something generic and not  `ceConnector` since in future other connectors can also support this.

2022-05-19 09:56 UTC, jyotiarora-harness commented
retrigger jest

2022-05-19 12:06 UTC, meenakshi-harness approved these changes

2022-05-19 12:14 UTC, rajarshee-harness approved these changes

2022-05-19 12:21 UTC, merged