feat: update account resources and routing to agents list
harness/harness-core-ui pull request #8879
Opened 2022-05-17 01:32 UTC by bao-harness

##### Summary:

- Updates card styles according to [mocks](https://www.figma.com/file/a96xcWOd4CmBMEOsqKbrgG/gitOps?node-id=9885%3A356491)
- Added routing to Agents entity card to render GitOps microservice within the scope of Account Resources tab.
- Added temporary `false` condition while the section is being developed

##### Jira Links:

https://harness.atlassian.net/browse/CDS-37039
https://harness.atlassian.net/browse/CDS-37040
https://harness.atlassian.net/browse/CDS-37043

##### Screenshots:

![image](https://user-images.githubusercontent.com/97480594/168701960-267cb823-913e-468b-88af-331fee6956fc.png)

https://user-images.githubusercontent.com/97480594/168702080-6b381913-1891-4681-a655-dde7edf246a5.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-18 01:00 UTC, sahithikolichala approved these changes

2022-05-18 17:58 UTC, sahithikolichala submitted a review, later dismissed

2022-05-18 18:00 UTC, tan-nhu submitted a review, later dismissed

2022-05-18 18:37 UTC, mtran7 approved these changes

2022-05-19 04:22 UTC, abhinavrastogi-harness requested changes
According to the video attached, the main nav highlight is not working correctly when you are on the account-scope gitops agents list page.

2022-05-19 06:59 UTC, bao-harness commented
> According to the video attached, the main nav highlight is not working correctly when you are on the account-scope gitops agents list page.

The changes for those nav are going to be in the GitOps microfrontend side!

2022-05-19 11:03 UTC, abhinavrastogi-harness commented on src/modules/75-cd/RouteDestinations.tsx
> +      sidebarProps={AccountSideNavProps}
why do we need AccountSideNavProps in CD side nav? CD only shows Project scope links

2022-05-19 16:42 UTC, bao-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +/* eslint-disable strings-restrict-modules */
This eslint was for linting issues I was getting for trying to use `cd.gitOps` in `<String />`
![image](https://user-images.githubusercontent.com/97480594/169353543-aa071099-a604-454f-9b63-b57b1831079d.png)

2022-05-19 17:08 UTC, bao-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +      icon: 'connectors-blue',
Do you have a suggestion for setting `currentColor`. I attempted that, but there doesn't seem to be a clean way to do it and have the colors be as intended. Each icon has various different implementations of the icon, including uses of `<path>`, `<fill>`, `<mask>`, and in some cases, there could be two `<paths>` that exist inside of the `<svg>` with different `stroke` or `fill` attributes.

Using the blue version of these icons instead seems to be the less hacky way of implementing this unless you had a method in mind that I'm not thinking about. The blue versions are also implemented based on the [designs](https://www.figma.com/file/a96xcWOd4CmBMEOsqKbrgG/gitOps?node-id=9885%3A356491)

2022-05-19 18:51 UTC, bao-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +              [`${css.selected}`]: showGitOpsEntities && option.icon.includes('gitops')
Would it be possible to address this if there are plans to add additional clickable cards in the future?

I would imagine this would be implemented within the Card component itself.

2022-05-19 20:39 UTC, bao-harness commented on src/modules/75-cd/RouteDestinations.tsx
> +      sidebarProps={AccountSideNavProps}
Based on the mocks, it seemed like we wanted to keep the `AccountSideNavProps` https://www.figma.com/file/a96xcWOd4CmBMEOsqKbrgG/gitOps?node-id=9885%3A351816

I could attempt to export/import `<GitOpsPage />` into an account level page somewhere if that makes more sense.

2022-05-19 20:39 UTC, bao-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +        setShowGitOpsEntities(prev => !prev)
Done

2022-05-19 20:40 UTC, bao-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +  const showGitOpsCard = useMemo(() => history?.location?.pathname.includes('resources') && false, [history])
Is there a hook to use for nested routes? Otherwise I did update the dependency array to have `history?.location?.pathname`

2022-05-20 05:38 UTC, bao-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +  const showGitOpsCard = useMemo(() => history?.location?.pathname.includes('resources') && false, [history])
Synced with Abhinav offline, and this would be a larger task to do correct path matching, which would be beyond the scope of this ticket/PR.

2022-05-20 05:42 UTC, bao-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +      icon: 'connectors-blue',
Synced with Abhinav offline, and will need to confirm with designers on decision for icons. If it's intended to be replaced app wide, replace the existing icons instead of creating new ones in the `uicore` repo.

If not, update existing `uicore` icons to use `currentColor` instead of hardcoding colors

2022-05-20 05:43 UTC, bao-harness commented on src/modules/75-cd/RouteDestinations.tsx
> +      sidebarProps={AccountSideNavProps}
Synced with Abhinav offline, despite having "common/account" scoped components inside of the cd module being bad practice, we're okay to continue with this implementation given current business need.

2022-05-20 05:49 UTC, vkbansal requested changes

2022-05-20 05:49 UTC, vkbansal commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +/* eslint-disable strings-restrict-modules */
Please fix this. This is a valid issue.

2022-05-20 05:49 UTC, vkbansal commented on src/modules/75-cd/RouteDestinations.tsx
> +      sidebarProps={AccountSideNavProps}
Let's create a new module for gitops and move this there

2022-05-20 05:53 UTC, bao-harness commented on src/modules/10-common/components/ResourceCardList/ResourceCardList.tsx
> +/* eslint-disable strings-restrict-modules */
Yes I synced with Abhinav and he told me the issue. I will address

2022-05-20 06:00 UTC, abhinavrastogi-harness commented on src/modules/75-cd/RouteDestinations.tsx
> +      sidebarProps={AccountSideNavProps}
+1 for a separate module

2022-05-20 06:01 UTC, abhinavrastogi-harness commented
> > According to the video attached, the main nav highlight is not working correctly when you are on the account-scope gitops agents list page.
> 
> The changes for those nav are going to be in the GitOps microfrontend side!

Discussed this offline. The routes changes need to be done in NGUI only, and is a blocker

2022-05-26 04:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core-ui?pullRequest=8879) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core-ui?pullRequest=8879) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: bao-harness<br/>:x: sahithikolichala<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core-ui?pullRequest=8879) it.</sub>

2022-05-26 04:13 UTC, sahithikolichala commented
ResourceCardList is reverted back to original 
<img width="1139" alt="Screen Shot 2022-05-25 at 9 10 36 PM" src="https://user-images.githubusercontent.com/57372986/170414537-4a0a8c74-ea22-4996-81ed-a58705c29a4a.png">
cc: @abhinavrastogi-harness  @bao-harness  @vkbansal

2022-05-26 14:04 UTC, vkbansal submitted a review, later dismissed

2022-05-28 07:10 UTC, vkbansal submitted a review, later dismissed

2022-05-30 09:24 UTC, bao-harness commented
retrigger coverage

2022-05-30 18:27 UTC, bao-harness commented
retrigger standards

2022-05-30 18:27 UTC, bao-harness commented
retrigger typecheck

2022-05-30 18:54 UTC, bao-harness commented
retrigger standards

2022-05-30 18:54 UTC, bao-harness commented
retrigger typecheck

2022-05-31 04:13 UTC, sahithikolichala commented
retrigger typecheck

2022-05-31 06:11 UTC, upadhyay-an commented on package.json
> +    "@harness/icons": "^1.9.0",
Please revert this change.

2022-05-31 06:11 UTC, vkbansal approved these changes

2022-05-31 06:15 UTC, sahithikolichala approved these changes

2022-05-31 07:07 UTC, kapilkumawat86 approved these changes

2022-05-31 07:08 UTC, kapilkumawat86 commented on package.json
> +    "@harness/icons": "^1.9.0",
agree @sahithikolichala @bao-harness

2022-05-31 07:16 UTC, bao-harness commented on package.json
> +    "@harness/icons": "^1.9.0",
Is there a reason why we need to pin it to `1.13.0`? Even with `^1.9.0`, the current version of @harness/icons is `1.13.0`. Further upgrades to @harness/icons won't carry unless the version isn't pinned? @upadhyay-an

2022-05-31 07:27 UTC, vasuki-kalluri approved these changes

2022-05-31 16:06 UTC, vkbansal approved these changes

2022-05-31 19:01 UTC, sahithikolichala approved these changes

2022-06-01 04:10 UTC, merged

2022-06-01 05:51 UTC, vardanbansal-harness commented
@rajatharanganath this changed got merged without `ui-ci` team approval.