feat: [PL-25230]: Hiding dashboard if there is no CD license
harness/harness-core-ui pull request #8892
Opened 2022-05-17 13:10 UTC by avinashmadhwani02

2022-05-17 13:19 UTC, kapilkumawat86 submitted a review, later dismissed

2022-05-18 04:42 UTC, abhinavrastogi-harness requested changes

2022-05-18 04:42 UTC, abhinavrastogi-harness commented on src/modules/45-projects-orgs/pages/LandingDashboardPage/LandingDashboardWelcomeView.tsx
> +  const hideBackButton = getLandingDashboardDefaultView(CD_LICENSE_STATE)
`hideBackButton` is a boolean.. why are we assigning the type `View` to it?

2022-05-18 04:42 UTC, abhinavrastogi-harness commented on src/modules/45-projects-orgs/utils/utils.ts
> +export const getLandingDashboardDefaultView = (cdLicenseState: LICENSE_STATE_VALUES) => {
this API is not extensible.. in a few weeks we will have other modules also which we will need to evaluate.

can we instead create a new hook, which itself includes `useLicenseStore` instead of the page using it and passing the license to this util.

2022-05-18 12:53 UTC, mayankVermaHarness approved these changes

2022-05-18 13:03 UTC, abhinavrastogi-harness approved these changes

2022-05-18 13:04 UTC, merged