feat: [FFM-3327]: Standardising button variations in the environments pages
harness/harness-core-ui pull request #8963
Opened 2022-05-19 11:51 UTC by laura-mannus

##### Summary:

**Environments listing page**

“+ New Environment” - change to use primary variation

**Environment detail page**

_Empty state_

“Create SDK Key” - change to use primary variation

_Non-empty state_

“Create SDK Key” - change to use primary variation

- Using relative css path
- Removed css classes that were not needed in layout containers
- Dropping unnecessary Container

##### Jira Links:

https://harness.atlassian.net/browse/FFM-3327

##### Screenshots:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/103498167/169286757-c3c229af-4dc5-4936-a3ad-04eb5fc8e6d5.png">

<img width="355" alt="image" src="https://user-images.githubusercontent.com/103498167/169286853-65d9d148-39bf-4247-84df-2916258ceddc.png">

<img width="799" alt="image" src="https://user-images.githubusercontent.com/103498167/169286936-f4121e0f-fe4d-4c38-be7f-a38901da3c94.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-19 12:03 UTC, laura-mannus commented
retrigger jest

2022-05-19 13:27 UTC, laura-mannus commented
retrigger jest

2022-05-19 13:50 UTC, laura-mannus commented
retrigger jest

2022-05-19 14:04 UTC, laura-mannus commented
retrigger jest

2022-05-20 10:11 UTC, chrisblakely01 requested changes
We probs want to rollback the `75-cd` changes as its not our module/out of scope for this ticket

2022-05-20 10:18 UTC, crystal-fong commented on src/modules/75-cf/components/AddKeyDialog/AddKeyDialog.tsx
>      <RbacButton
this won't let me comment on the exact line that needs changed but line 165

`text={getString('cf.environments.apiKeys.addKeyTitle')}`

2022-05-20 10:22 UTC, crystal-fong commented on src/modules/75-cd/components/Environments/EnvironmentList/EnvironmentsList.tsx
> +import { Pagination, Layout, Text, Container, Heading, TableV2, ButtonVariation } from '@wings-software/uicore'
if you're pushing changes anyway :) 

```suggestion
import { Pagination, Layout, Text, Container, Heading, TableV2, ButtonVariation } from '@harness/uicore'
```

2022-05-20 10:25 UTC, laura-mannus commented on src/modules/75-cd/components/Environments/EnvironmentList/EnvironmentsList.tsx
> +import { Pagination, Layout, Text, Container, Heading, TableV2, ButtonVariation } from '@wings-software/uicore'
Unfortunately can't fix this as its not our module, have removed the change altogether

2022-05-20 10:34 UTC, laura-mannus commented on src/modules/75-cf/components/AddKeyDialog/AddKeyDialog.tsx
>      <RbacButton
Thank you! Have changed key title to '+ New SDK Key' 
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/103498167/169509374-e1e34f6f-ee39-49b9-a4e1-a55e3601e56d.png">

2022-05-20 10:43 UTC, knagurski commented on src/modules/75-cf/pages/environments/EnvironmentsPage.tsx
> +          <Text style={{ font: FontVariation.SMALL, color: Color.GREY_600 }}>{environment.description}</Text>
Don't know how I didn't spot this before, but for this (and the one above), we need to use the `font` prop, not the `style` prop for variations and colour
```suggestion
          <Text font={{ variation: FontVariation.SMALL, color: Color.GREY_600 }}>{environment.description}</Text>
```

2022-05-20 10:48 UTC, laura-mannus commented on src/modules/75-cf/pages/environments/EnvironmentsPage.tsx
> +          <Text style={{ font: FontVariation.SMALL, color: Color.GREY_600 }}>{environment.description}</Text>
Don't think color is a prop of font?

2022-05-20 11:03 UTC, crystal-fong commented on src/modules/75-cf/pages/environments/EnvironmentsPage.tsx
> +          <Text style={{ font: FontVariation.SMALL, color: Color.GREY_600 }}>{environment.description}</Text>
```suggestion
          <Text color={Color.GREY_600} font={{ font: FontVariation.SMALL }}>{environment.description}</Text>
```

2022-05-20 11:15 UTC, laura-mannus commented on src/modules/75-cf/pages/environments/EnvironmentsPage.tsx
> +          <Text style={{ font: FontVariation.SMALL, color: Color.GREY_600 }}>{environment.description}</Text>
Lovely thank you have changed

2022-05-20 13:36 UTC, knagurski approved these changes
Noice

2022-05-20 13:41 UTC, merged