feat: [SRM-10245]: Fixes for appD template
harness/harness-core-ui pull request #9061
Opened 2022-05-25 14:54 UTC by deepesh-ui

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-26 16:49 UTC, deepesh-ui commented
retrigger jest

2022-05-26 16:50 UTC, deepesh-ui commented
trigger cypress

2022-05-27 01:22 UTC, deepesh-ui commented
retrigger jest

2022-05-27 05:26 UTC, praneshg239 commented on src/modules/85-cv/pages/health-source/connectors/AppDynamics/AppDHealthSource.utils.ts
> +    : tierOptions.find((item: SelectOption) => {
above function `setAppDynamicsApplication` doing the same operation as `setAppDynamicsTier`. Is it possible to extract the common logic to a separate function?

2022-05-27 08:21 UTC, praneshg239 commented on src/modules/85-cv/pages/health-source/connectors/AppDynamics/Components/AppDynamicsTier/AppDynamicsTier.tsx
> +        onChange: async (item, _type, multiType) => {
why `async` is used here?

2022-05-27 08:35 UTC, praneshg239 approved these changes

2022-05-30 02:59 UTC, deepesh-ui commented
trigger cypress

2022-05-30 04:24 UTC, AshwinBhatkal-Harness commented on src/modules/72-templates-library/components/TemplateStudio/MonitoredServiceTemplateCanvas/MonitoredServiceTemplateCanvas.tsx
> +import { MonitoredServiceProvider } from '@cv/pages/monitored-service/MonitoredServiceContext'
This should be moved into templates or some other higher module level. If it doesn't fit, then we may have to refactor that component accordingly. Disabling es-lint defeats the purpose of module layering.

2022-05-30 05:53 UTC, vkbansal requested changes

2022-05-30 05:53 UTC, vkbansal commented on src/modules/72-templates-library/components/TemplateStudio/MonitoredServiceTemplateCanvas/MonitoredServiceTemplateCanvas.tsx
> +import { MonitoredServiceProvider } from '@cv/pages/monitored-service/MonitoredServiceContext'
Don't disable eslint errors. They are enforced for a reason.

2022-05-30 05:55 UTC, praneshg239 commented on src/modules/85-cv/pages/health-source/connectors/AppDynamics/AppDHealthSource.tsx
> +      getMultiTypeFromValue(connectorIdentifier) !== MultiTypeInputType.RUNTIME &&
please store `getMultiTypeFromValue(connectorIdentifier)` in a variable and use that for comparison.

2022-05-30 10:34 UTC, deepesh-ui commented on src/modules/72-templates-library/components/TemplateStudio/MonitoredServiceTemplateCanvas/MonitoredServiceTemplateCanvas.tsx
> +import { MonitoredServiceProvider } from '@cv/pages/monitored-service/MonitoredServiceContext'
resolved

2022-05-30 10:34 UTC, deepesh-ui commented on src/modules/85-cv/pages/health-source/connectors/AppDynamics/AppDHealthSource.tsx
> +      getMultiTypeFromValue(connectorIdentifier) !== MultiTypeInputType.RUNTIME &&
resolved

2022-05-30 14:59 UTC, vkbansal approved these changes

2022-05-30 15:01 UTC, AshwinBhatkal-Harness approved these changes

2022-05-31 04:06 UTC, praneshg239 approved these changes

2022-05-31 04:07 UTC, merged