Ccm 7654 perspective folders
harness/harness-core-ui pull request #9105
Opened 2022-05-27 09:11 UTC by jyotiarora-harness

##### Summary:

Perspective folder feature

##### Jira Links:

https://harness.atlassian.net/browse/CCM-7654

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-02 06:42 UTC, rishik30 requested changes

2022-06-02 06:42 UTC, rishik30 commented on src/modules/75-ce/components/PerspectiveFolders/MoveFolderModal.tsx
> +  const queryParams = Object.fromEntries(new URLSearchParams(location.search))
use already implemented hook `useQueryParams` to be consistent across

2022-06-02 06:42 UTC, rishik30 commented on src/modules/75-ce/components/PerspectiveFolders/MoveFolderModal.tsx
> +        response && showSuccess(getString('ce.perspectives.folders.folderMoved'))
no need to check response as the code will move here only after successful response

2022-06-02 06:42 UTC, rishik30 commented on src/modules/75-ce/components/PerspectiveFolders/MoveFolderModal.tsx
> +      folderOptions.push({
why perform a push operation when we can simply set the values of options after `foldersList` is fetched?

2022-06-02 06:42 UTC, rishik30 commented on src/modules/75-ce/components/PerspectiveFolders/MoveFolderModal.tsx
> +                    {currentFolder?.name || /* istanbul ignore next */ ''}
avoid `istanbul ignore` and use `_.defaultTo` for these default values.

2022-06-02 06:42 UTC, rishik30 commented on src/modules/75-ce/components/PerspectiveFolders/PerspectiveFoldersSideNav.module.scss
> +  height: 324px;
Can't we calculate the height something like `height: calc(100vh - {dist from top in px})` instead of having a static height?

2022-06-02 06:42 UTC, rishik30 commented on src/modules/75-ce/components/PerspectiveFolders/PerspectiveFoldersSideNav.tsx
> +        onClick={() => props.setSelectedFolder({ folderId: folderId })}
we can simply use `props.setSelectedFolder({ folderId })`

2022-06-02 06:42 UTC, rishik30 commented on src/modules/75-ce/components/PerspectiveFolders/PerspectiveFoldersSideNav.tsx
> +  const SideNavItem: React.FC<SidebarLinkProps> = ({
What's the need of creating a component inside a component? We should extract the component outside.

2022-06-02 06:42 UTC, rishik30 commented on src/modules/75-ce/components/PerspectiveFolders/PerspectiveFoldersSideNav.tsx
> +      defaultFolders.push(item)
we can simply assign the array instead of pushing every item extensively.

2022-06-02 06:42 UTC, rishik30 commented on src/modules/75-ce/pages/perspective-list/PerspectiveListPage.tsx
> +      if (deletedFolder) {
no need for this check

2022-06-02 06:42 UTC, rishik30 commented on src/modules/75-ce/utils/perspectiveUtils.ts
> +  let filteredList = perspectiveList
no need to assign the list to a new variable. Simply return the filtered list if searchVal is present otherwise return the original list
```js
if (searchVal) {
  return perspectiveList.filter((item: any) => item?.name?.toLowerCase().includes(searchVal.toLowerCase()))
  }

  return perspectiveList
```

2022-06-03 06:14 UTC, rishik30 submitted a review, later dismissed

2022-06-03 06:14 UTC, rishik30 commented on src/modules/75-ce/components/PerspectiveFolders/MoveFolderModal.tsx
> +    folderId ? /* istanbul ignore next */ item.uuid === JSON.parse(folderId) : item.viewType === folderViewType.DEFAULT
better not to parse on every element but save the parsed value and use it inside callbacks

2022-06-03 06:16 UTC, jyotiarora-harness commented on src/modules/75-ce/components/PerspectiveFolders/MoveFolderModal.tsx
> +    folderId ? /* istanbul ignore next */ item.uuid === JSON.parse(folderId) : item.viewType === folderViewType.DEFAULT
Sure, taking up in follow up PR

2022-06-03 08:51 UTC, jyotiarora-harness commented
retrigger jest

2022-06-03 08:59 UTC, jyotiarora-harness commented
retrigger coverage

2022-06-03 09:09 UTC, rishik30 approved these changes

2022-06-03 09:11 UTC, rajarshee-harness approved these changes

2022-06-03 09:33 UTC, kapilkumawat86 approved these changes

2022-06-03 09:35 UTC, merged