feat: [CDS-36889]: Added override yaml values in K8sApply step
harness/harness-core-ui pull request #9120
Opened 2022-05-28 12:52 UTC by goyalsonali

##### Summary:

##### Jira Links:

https://harness.atlassian.net/browse/CDS-36889

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-05-31 07:28 UTC, goyalsonali commented
trigger cypress

2022-05-31 07:31 UTC, goyalsonali commented
retrigger jest

2022-05-31 07:47 UTC, goyalsonali commented
retrigger jest

2022-05-31 09:06 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sInterface.ts
> +export type K8ManifestTypes = 'Values' | 'OpenshiftParam' | 'KustomizePatches'
Can you rename it to K8sApplyManifest types

2022-05-31 09:07 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.module.scss
> +  line-height: 16px !important;
Why is all the styles `!important`. Is this intentional. Please check

2022-05-31 09:07 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +    return false
Is `allowOnlyOne` needed. I believe it was added for serverless

2022-05-31 09:11 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +      listOfManifests.push(manifestObj)
Are we not updating formik onSubmit?

2022-05-31 09:11 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +  const handleStoreChange = (store?: K8ManifestStores): void => {
useCallback?

2022-05-31 09:14 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +      case [ManifestDataType.Values].includes(selectedManifest as K8ManifestTypes) &&
This can be directly checked, as only 1 parameter is there

2022-05-31 09:15 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +    expressions,
Both expressions and its length??

2022-05-31 09:16 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +    <Layout.Vertical style={{ width: '100%' }}>
inline style?

2022-05-31 09:17 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesRuntimeFields.tsx
> +          {'Manifest ID'}: {overrideValue?.manifest?.identifier}
Move this to strings file

2022-05-31 09:19 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8shelper.ts
> +  Values: [...manifestStoreTypes],
No need of spread here.

2022-05-31 09:20 UTC, goyalsonali commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sInterface.ts
> +export type K8ManifestTypes = 'Values' | 'OpenshiftParam' | 'KustomizePatches'
Yes, I will do it

2022-05-31 09:21 UTC, goyalsonali commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +    return false
yes, but i kept it if we require it in future for some case. 
I can remove it too.

2022-05-31 09:22 UTC, bhavya-sinha requested changes

2022-05-31 09:22 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesRuntimeFields.tsx
> +          type={[overrideValue?.manifest?.spec?.type]}
Why is type an array?

2022-05-31 09:28 UTC, goyalsonali commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesRuntimeFields.tsx
> +          type={[overrideValue?.manifest?.spec?.type]}
I did this mistakenly.Will remove it.

2022-05-31 09:42 UTC, goyalsonali commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +      manifestIdsList: listOfManifests.map((item: ManifestConfigWrapper) => item.manifest?.identifier as string),
We need it here too.

2022-05-31 10:02 UTC, goyalsonali commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +      listOfManifests.push(manifestObj)
No, we are updating formik while applying changes to step. Here, we just render it in step view.

2022-05-31 21:23 UTC, goyalsonali commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +      listOfManifests.push(manifestObj)
I have updated the code and reduced one file. 
So updated the formik here only now.

2022-06-01 11:17 UTC, goyalsonali commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +  const handleStoreChange = (store?: K8ManifestStores): void => {
It is working fine. should we still use it?

2022-06-02 04:34 UTC, goyalsonali commented
retrigger jest

2022-06-02 08:44 UTC, goyalsonali commented
retrigger jest

2022-06-02 10:55 UTC, goyalsonali commented
fix prettier

2022-06-02 11:37 UTC, goyalsonali commented
trigger cypress

2022-06-03 04:46 UTC, goyalsonali commented
trigger cypress

2022-06-03 07:27 UTC, chetanvekariya-harness submitted a review, later dismissed

2022-06-03 07:27 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/K8sApply/__tests__/K8sOverrideValuesManifest.test.tsx
> +    const addFileButton = await getByText(container, 'pipelineSteps.serviceTab.manifestList.addManifest')
NIT - let's call it addManifestButton

2022-06-03 07:27 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/K8sApply/__tests__/K8sOverrideValuesManifest.test.tsx
> +  test('delete manifest list works correctly', async () => {
NIT - This test case can be part of test file of K8sOverrideValuesListView component

2022-06-03 10:14 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestInterface.ts
> +  | 'Inline'
Dont add Inline here

2022-06-03 10:16 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizard/ManifestWizard.tsx
> +  types: ManifestTypes[]
pass a new prop from manifestList and K8sapply to handle connectorstep

2022-06-03 10:19 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/InlineManifest/_tests_/Inline.test.tsx
> +    await act(async () => {
i think fireevent is already wrapped in act.

2022-06-03 10:20 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/ManifestStore.tsx
> +      selectedStore !== ManifestStoreMap.InheritFromManifest
use the hasConnectorStep prop here

2022-06-03 10:20 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/ManifestStore.tsx
> +                      handleOptionSelection(formik?.values, storeSelected as ManifestStoreExcludingInheritInline)
Check this

2022-06-03 10:20 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/ManifestStore.tsx
> +                selectedStore !== ManifestStoreMap.InheritFromManifest ? (
same

2022-06-03 10:20 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/Manifesthelper.ts
> +  Inline: 'Inline'
Remove this

2022-06-03 10:20 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/Manifesthelper.ts
> +  Exclude<ManifestStores, 'Inline' | 'InheritFromManifest'>,
this too

2022-06-03 10:21 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/Manifesthelper.ts
> +  Inline: 'inline'
this

2022-06-03 10:27 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +      <DragDropContext onDragEnd={onDragEnd}>
Use DragnDropPaths common component

2022-06-03 10:34 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/K8sApply/K8sOverrideValuesListView.tsx
> +      <DragDropContext onDragEnd={onDragEnd}>
Use DragnDropPaths common component

2022-06-05 19:14 UTC, goyalsonali commented
trigger rebase

2022-06-09 05:27 UTC, goyalsonali commented
trigger rebase

2022-06-09 07:12 UTC, bhavya-sinha approved these changes

2022-06-09 08:47 UTC, merged