feat: [CDS-36921]: pipeline with env ref
harness/harness-core-ui pull request #9170
Opened 2022-06-01 05:54 UTC by AshwinBhatkal-Harness

##### Summary:

1. Pipeline creation & update with env ref
2. Allow simultaneous deployments on Infra
3. Update of env and env group modal for creation from pipeline page

##### Jira Links:

https://harness.atlassian.net/browse/CDS-36921
https://harness.atlassian.net/browse/CDS-36922

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-08 10:44 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/PipelineStudio/StepUtil.ts
> +    // TODO: errors
Please remember to remove this later

2022-06-08 10:45 UTC, bhavya-sinha commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureModal.tsx
> +                }
Commented code?

2022-06-08 10:45 UTC, bhavya-sinha commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureModal.tsx
> +                }
Commented code?

2022-06-08 10:46 UTC, bhavya-sinha commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureModal.tsx
> +          serviceDefinition.type = deploymentType
Why are we updating serviceDefinition? This is not there in new specs

2022-06-08 10:46 UTC, bhavya-sinha commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureModal.tsx
> +          serviceDefinition.type = deploymentType
Why are we updating serviceDefinition? This is not there in new specs

2022-06-08 10:47 UTC, bhavya-sinha commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureModal.tsx
> +                    handleDeploymentTypeChange={handleDeploymentTypeChange}
I have made changes to add a new prop type here. https://github.com/harness/harness-core-ui/pull/9314

If my code gets merged first. Remember to update this

2022-06-08 10:47 UTC, bhavya-sinha commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureModal.tsx
> +                    handleDeploymentTypeChange={handleDeploymentTypeChange}
I have made changes to add a new prop type here. https://github.com/harness/harness-core-ui/pull/9314

If my code gets merged first. Remember to update this

2022-06-08 10:52 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/AddEditEnvironmentModal.tsx
> +    queryParams: {
Make sure this is updated schema. In service we have new schema.

2022-06-08 10:52 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/AddEditEnvironmentModal.tsx
> +    queryParams: {
Make sure this is updated schema. In service we have new schema.

2022-06-08 10:54 UTC, bhavya-sinha requested changes

2022-06-08 10:54 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructureInputStep.tsx
> +    refetch()
If we are refetching the api on mount, we neednot pass lazy: true.

2022-06-08 10:56 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructureInputStep.tsx
> +              disabled={inputSetData?.readonly || (isEditEnvironment(initialValues) ? !canEdit : !canCreate)}
We dont need usePermission Hook. Rbacbutton can be directly used here, which accepts permission props

2022-06-08 10:56 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructureInputStep.tsx
> +  const [canCreate] = usePermission({
This is not needed

2022-06-08 11:04 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructureWidget.tsx
> +                              //       formik,
Commented code?

2022-06-08 11:05 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineStudio/DeployEnvSpecifications/DeployEnvSpecifications.tsx
> +          onChange={itemSelect}
Commented?

2022-06-08 12:58 UTC, vkbansal approved these changes

2022-06-08 13:00 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructureWidget.tsx
> +                              //       formik,
This is the environment group changes which is causing issues. Will put them back later

2022-06-08 13:00 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructureWidget.tsx
> +    resource: {
I'll update it in the next PR

2022-06-08 13:00 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructureInputStep.tsx
> +    resource: {
I'll update it in the next PR

2022-06-08 13:01 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/PipelineStudio/StepUtil.ts
> +    // TODO: errors
Yes

2022-06-08 13:16 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructureInputStep.tsx
> +  const [canCreate] = usePermission({
I'll update it in the next PR

2022-06-08 13:17 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructureInputStep.tsx
> +    refetch()
I'll update it in the next PR

2022-06-08 13:18 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureModal.tsx
> +          serviceDefinition.type = deploymentType
This is to load the deploymentType while creating infrastructure

2022-06-08 13:18 UTC, AshwinBhatkal-Harness commented on src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureModal.tsx
> +                }
Will remove

2022-06-09 05:29 UTC, bhavya-sinha approved these changes

2022-06-09 05:37 UTC, vkbansal approved these changes

2022-06-09 05:37 UTC, merged