feat: [SRM-10423]: Added InputSet route for MS
harness/harness-core-ui pull request #9280
Opened 2022-06-07 05:24 UTC by deepesh-ui

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-09 04:16 UTC, deepesh-ui commented
trigger cypress

2022-06-10 08:41 UTC, avinashmadhwani02 commented on src/modules/10-common/RouteDefinitions.ts
> +      return `/${module}/orgs/${orgIdentifier}/projects/${projectIdentifier}/monitoringservicesinputset`
Shouldn't the module be always 'cv', as the name says `toCVMonitoringServicesInputSets`

2022-06-10 08:43 UTC, avinashmadhwani02 approved these changes
Verified platform related changes

2022-06-10 08:44 UTC, deepesh-ui commented on src/modules/10-common/RouteDefinitions.ts
> +      return `/${module}/orgs/${orgIdentifier}/projects/${projectIdentifier}/monitoringservicesinputset`
correct. we have followed the same convention for for all cv based routes.

2022-06-10 11:54 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateInputs/TemplateInputs.tsx
> +                            ?.renderTemplateInputsForm({ ...templateData })}
use `template` from props instead of creating new object.

2022-06-10 11:55 UTC, yc147 commented on src/modules/85-cv/components/MonitoredServiceInputSets/index.tsx
> +import React from 'react'
Instead of creating a new factory.. use existing one.

2022-06-10 11:55 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateInputs/TemplateInputs.tsx
> +  const templateData = {
We don't need this.

2022-06-10 11:56 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateInputs/index.ts
> +export interface TemplateInputsDataInterface {
Not needed

2022-06-10 11:58 UTC, yc147 commented on src/modules/72-templates-library/pages/TemplatesPage/TemplatesPage.tsx
> +  React.useEffect(() => {
Use `type` query param to filter by template type

2022-06-10 15:08 UTC, yc147 submitted a review, later dismissed

2022-06-10 15:54 UTC, vasuki-kalluri submitted a review, later dismissed

2022-06-11 04:38 UTC, yc147 requested changes

2022-06-11 04:38 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioHeader/__tests__/TemplateStudioHeader.test.tsx
> +  // eslint-disable-next-line jest/no-disabled-tests
Don't skip the test.. fix it.

2022-06-11 04:38 UTC, yc147 commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/__tests__/TemplateStudioSubHeaderLeftView.test.tsx
> +  test.skip('should match snapshot', async () => {
Don't skip the test.. fix it.

2022-06-14 06:18 UTC, harshilbits commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioSubHeader/views/TemplateStudioSubHeaderLeftView/__tests__/TemplateStudioSubHeaderLeftView.test.tsx
> +  test.skip('should match snapshot', async () => {
Done.

2022-06-14 06:18 UTC, harshilbits commented on src/modules/72-templates-library/components/TemplateStudio/TemplateStudioHeader/__tests__/TemplateStudioHeader.test.tsx
> +  // eslint-disable-next-line jest/no-disabled-tests
Done.

2022-06-14 06:19 UTC, harshilbits commented
retrigger jest

2022-06-14 06:31 UTC, merged