feat: [CCM-7889]: Azure Filter Support in Anomalies Filter Panel
harness/harness-core-ui pull request #9318
Opened 2022-06-08 11:56 UTC by rajarshee-harness

##### Summary:

##### Jira Links:

https://harness.atlassian.net/browse/CCM-7889

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-08 13:06 UTC, rajarshee-harness commented
retrigger titlecheck

2022-06-09 09:37 UTC, rishik30 requested changes

2022-06-09 09:37 UTC, rishik30 commented on src/modules/75-ce/components/AnomaliesFilter/FilterDrawer/utils.ts
> +  if (azureResourceGroups) {
create a utility here that takes in formData and based on the keys generates filterProperties.
```js
const getPropertiesFromFormData = (formData) => {
  const filterProperties = {}
  Object.entries(formData).forEach(([key, value]) => {
    filterProperties[key] = getValueFromOption(value)
  })
  return filterProperties
}
```

2022-06-10 04:14 UTC, rajarshee-harness commented on src/modules/75-ce/components/AnomaliesFilter/FilterDrawer/utils.ts
> +  if (azureResourceGroups) {
Done

2022-06-10 05:19 UTC, rajarshee-harness commented
trigger cypress

2022-06-10 12:59 UTC, rishik30 approved these changes

2022-06-16 07:23 UTC, kapilkumawat86 approved these changes

2022-06-16 07:24 UTC, merged