Cds 37727 ms azure ssh infra
harness/harness-core-ui pull request #9329
Opened 2022-06-08 20:08 UTC by azharness

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-14 20:14 UTC, azharness commented
retrigger coverage

2022-06-23 17:43 UTC, azharness commented
trigger rebase

2022-06-27 11:01 UTC, bhavya-sinha requested changes

2022-06-27 11:01 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/SshWinRmAzureInfrastructureSpec/SshWinRmAzureInfrastructureSpec.tsx
> +  lastFetched: number
Please move this to separate file for better clarity.

2022-06-29 21:14 UTC, azharness commented on src/modules/75-cd/components/PipelineSteps/PipelineStepsUtil.ts
> +      return Yup.object().shape({})
That one will be developed in near future, have just added it ot differentiated from ssh

2022-06-29 21:16 UTC, azharness commented on src/modules/75-cd/components/PipelineSteps/SshWinRmAzureInfrastructureSpec/SshWinRmAzureInfrastructureSpec.tsx
> +        }
Yes, they are dependant on each other. Promise.all in this case won't make any difference, since all fetch functions are async.

2022-06-29 21:25 UTC, azharness commented on src/modules/75-cd/components/PipelineSteps/SshWinRmAzureInfrastructureSpec/SshWinRmAzureInfrastructureSpec.tsx
> +  lastFetched: number
Moved

2022-06-30 09:50 UTC, azharness commented
retrigger jest

2022-06-30 09:51 UTC, azharness commented
retrigger coverage

2022-06-30 14:59 UTC, bhavya-sinha approved these changes

2022-06-30 15:22 UTC, chetanvekariya-harness submitted a review, later dismissed

2022-06-30 15:22 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/SshWinRmAzureInfrastructureSpec/__tests__/SshWinRmAzureInfrastructureSpec.test.tsx
> +/*const connectorRefPath = 'pipeline.stages.0.stage.spec.infrastructure.infrastructureDefinition.spec.connectorRef'
Please remove commented code if not needed in near future.

2022-07-01 08:54 UTC, vkbansal commented on src/services/cd-ng/index.tsx
> -/*
Revert this

2022-07-01 08:55 UTC, vkbansal commented on src/services/cd-ng/index.tsx
> +export interface ResponseAzureTagsDTO {
Was this added manually?

2022-07-01 08:57 UTC, azharness commented on src/modules/70-pipeline/utils/stageHelpers.ts
> +  winrm = 'WinRm',
First one is Type, second one is Label

2022-07-01 08:58 UTC, azharness commented on src/modules/75-cd/components/PipelineSteps/SshWinRmAzureInfrastructureSpec/__tests__/SshWinRmAzureInfrastructureSpec.test.tsx
> +/*const connectorRefPath = 'pipeline.stages.0.stage.spec.infrastructure.infrastructureDefinition.spec.connectorRef'
Will need it soon, thats why is left there

2022-07-01 09:01 UTC, azharness commented on src/services/cd-ng/index.tsx
> +export interface ResponseAzureTagsDTO {
No, but there was some conflict so clicked to accept all incoming changes :/
Will revert it do develop version of file, it should be okay

2022-07-01 09:22 UTC, vkbansal approved these changes

2022-07-01 12:20 UTC, azharness commented on src/services/cd-ng/index.tsx
> -/*
fixed.

2022-07-01 12:57 UTC, azharness commented
retrigger jest

2022-07-04 07:56 UTC, sunnykesh-harness approved these changes
Reviewed changes on PL codes.

2022-07-04 07:57 UTC, merged