feat: [CI-4534]: add os field for k8s build infra
harness/harness-core-ui pull request #9400
Opened 2022-06-13 13:54 UTC by d1wilko

##### Summary:

Add OS field to k8s build infra tab

Stop users from choosing build&push build steps if windows OS is chosen for k8s infra

##### Jira Links:

https://harness.atlassian.net/browse/CI-4534

##### Screenshots:

![image](https://user-images.githubusercontent.com/20328202/173368626-aa4947ca-7361-493f-875d-55a18afbae76.png)

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-13 14:41 UTC, d1wilko commented
retrigger coverage

2022-06-13 16:38 UTC, mtran7 commented on src/modules/70-pipeline/components/PipelineInputSetForm/StageInputSetForm.tsx
> +                      allowedTypes: [MultiTypeInputType.FIXED]
should this also support expression and runtime input?

2022-06-13 16:43 UTC, mtran7 commented on src/modules/75-ci/components/PipelineStudio/BuildInfraSpecifications/BuildInfraSpecifications.tsx
> +              getString('fieldRequired', { field: 'OS' }) || '',
Use strings.en.yaml reference for oS

2022-06-14 08:46 UTC, d1wilko commented on src/modules/70-pipeline/components/PipelineInputSetForm/StageInputSetForm.tsx
> +                      allowedTypes: [MultiTypeInputType.FIXED]
no, the underlying field supports fixed and runtime, but not expression

this is basically where the runtime input get added, so we shouldn't input another runtime value

2022-06-14 08:53 UTC, d1wilko commented on src/modules/70-pipeline/components/PipelineStudio/StepPalette/StepPalette.tsx
> +  return buildInfraType === 'KubernetesDirect' &&
I will change this - but the reason I keep this as a string was that it is simply fluke that `StepType.KubernetesDirect` matches the build infra type "KubernetesDirect" - technically step types and build infra types have no relation - if that makes sense

2022-06-14 08:56 UTC, d1wilko commented on src/modules/75-ci/components/PipelineStudio/BuildInfraSpecifications/BuildInfraSpecifications.tsx
> +              getString('fieldRequired', { field: 'OS' }) || '',
nice catch - changing

2022-06-15 13:57 UTC, kapilkumawat86 requested changes
don't write this logic in UI 
<img width="653" alt="image" src="https://user-images.githubusercontent.com/57665511/173845510-91172d27-614b-450d-a162-7649e8f41ff3.png">
move to BE

2022-06-15 15:49 UTC, closed without merging

2022-06-15 16:49 UTC, mtran7 commented on src/modules/70-pipeline/components/PipelineInputSetForm/StageInputSetForm.tsx
> +                      allowedTypes: [MultiTypeInputType.FIXED]
oh right! Got it