feat: [STO-4486]: STO Project setup menu
harness/harness-core-ui pull request #9441
Opened 2022-06-14 13:52 UTC by jsentongo

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-14 15:24 UTC, jsentongo commented
retrigger jest

2022-06-15 14:09 UTC, chris-harness requested changes

2022-06-15 14:09 UTC, chris-harness commented on src/modules/10-common/navigation/ProjectSetupMenu/ProjectSetupMenu.tsx
> +        {OPA_PIPELINE_GOVERNANCE && isCIorCDorSTO && canUsePolicyEngine && (
This doesn't look right. Why did `isCV` go away?

2022-06-15 14:09 UTC, chris-harness commented on src/modules/10-common/navigation/ProjectSetupMenu/ProjectSetupMenu.tsx
> +  const { NG_TEMPLATES, OPA_PIPELINE_GOVERNANCE, NG_VARIABLES, NG_GIT_EXPERIENCE } = useFeatureFlags()
This change seems unrelated. Can you make sure this branch isn't mixed up with other changes

2022-06-15 19:41 UTC, atmollo-harness approved these changes

2022-06-15 20:40 UTC, chris-harness approved these changes

2022-06-15 21:34 UTC, abhinavrastogi-harness commented on src/modules/10-common/navigation/ProjectSetupMenu/ProjectSetupMenu.tsx
> +        {NG_TEMPLATES && isCIorCDorSTO && (
Does STO support templates?

2022-06-15 23:26 UTC, abhinavrastogi-harness approved these changes

2022-06-16 15:11 UTC, merged