feat: [CI-4663] viewCompiled yaml for executions in build and deployment [DRAFT]
harness/harness-core-ui pull request #9456
Opened 2022-06-15 06:09 UTC by udayvunnam

##### Summary:

viewCompiled yaml for executions in build and deployment
BE integration
Error handling

TODO:
Unit tests

##### Jira Links:

https://harness.atlassian.net/browse/CI-4663

##### Screenshots:

2022-06-15 06:10 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCard/ExecutionCard.tsx
> +}: Pick<ExecutionCardProps, 'pipelineExecution' | 'variant'>): React.ReactElement {
Pick only required instead of making remaining fields optional

2022-06-15 06:12 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCompiledYaml/ExecutionCompiledYaml.tsx
> +            <PageError message={(error.data as any)?.message || error.message} onClick={refetch as any} />
`refetch as any` instead of `() => refecth`

2022-06-15 07:06 UTC, udayvunnam commented
retrigger titlecheck

2022-06-15 07:10 UTC, chetanvekariya-harness submitted a review, later dismissed

2022-06-15 07:10 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ExecutionCompiledYaml/ExecutionCompiledYaml.tsx
> +            <PageError message={(error.data as Error)?.message || error.message} onClick={refetch as any} />
If your error contains `responseMessages` then you should show ErrorHandler (Displays hints, explanation etc.) component instead of PageError

2022-06-15 12:44 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCompiledYaml/ExecutionCompiledYaml.tsx
> +            <PageError message={(error.data as Error)?.message || error.message} onClick={refetch as any} />
Thanks for the hint Chetan. 

I don't see responseMessages for this API response structure. Is responseMessages typical pattern for all API errors now from BE?

2022-06-16 04:38 UTC, chetanvekariya-harness approved these changes

2022-06-16 04:38 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/components/ExecutionCompiledYaml/ExecutionCompiledYaml.tsx
> +            <PageError message={(error.data as Error)?.message || error.message} onClick={refetch as any} />
Yes, generally it is followed, at least, I see that it is followed properly in new git-sync.

2022-06-16 09:26 UTC, vardanbansal-harness commented
Do we need to clean up the yaml, like remove empty objects, arrays etc. before showing it? @udayvunnam

2022-06-16 09:26 UTC, vardanbansal-harness approved these changes

2022-06-16 09:38 UTC, vardanbansal-harness submitted a review, later dismissed

2022-06-16 12:49 UTC, chetanvekariya-harness submitted a review, later dismissed

2022-06-16 12:49 UTC, vardanbansal-harness submitted a review, later dismissed

2022-06-16 13:26 UTC, knagurski commented on src/modules/70-pipeline/components/ExecutionActions/__tests__/ExecutionActions.test.tsx
> +  useGetExecutionData: jest.fn(() => ({})),
For things like this, I like to use `mockReturnValue`
```suggestion
  useGetExecutionData: jest.fn().mockReturnValue({}),
```

Just an opinion, fine as-is

2022-06-16 13:34 UTC, knagurski commented on src/modules/70-pipeline/components/ExecutionActions/ExecutionActions.tsx
> +    onViewCompiledYaml
Further down the line `onViewCompiledYaml` is called without any type guards, though it is `optional` here. Could making it mandatory or having a default value of `() => undefined` fix that?

2022-06-16 13:38 UTC, knagurski commented on src/modules/70-pipeline/components/ExecutionCompiledYaml/__tests__/ExecutionCompiledYaml.test.tsx
> +    expect(screen.getByText('Loading, please wait...')).toBeInTheDocument()
Love the use of `toBeInTheDocument`!

2022-06-16 13:46 UTC, knagurski commented on src/modules/70-pipeline/components/ExecutionCompiledYaml/__tests__/ExecutionCompiledYaml.test.tsx
> +    )
I find it very useful to extract these repeating `render` calls to a helper function like this.

```typescript
const renderComponent = (props: Partial<ExecutionCompiledYamlProps> = {}): RenderResult =>
  render(
    <TestWrapper path={TEST_PATH} pathParams={pathParams}>
      <ExecutionCompiledYaml
        executionSummary={{ name: 'TestRun success', planExecutionId: 'planExecutionId', runSequence: 10 }}
        onClose={jest.fn()}
        {...props}
      />
    </TestWrapper>
  )
```

You can then just call `renderComponent()` when you want to render using the defaults you set, or pass in overrides with something like this...

```typescript
const onCloseMock = jest.fn()
renderComponent({ onClose: onCloseMock })
```

Fine as-is, just a pattern I find useful.

2022-06-16 13:48 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionActions/ExecutionActions.tsx
> +    onViewCompiledYaml
+1, already made that check in upcoming PR. Will add here as well

2022-06-16 13:49 UTC, knagurski commented on src/modules/70-pipeline/components/ExecutionCompiledYaml/ExecutionCompiledYaml.module.scss
> +  right: 100%;
What are you trying to do with this? If you want to do be at the right, `right: 0` should do the trick.

2022-06-16 13:53 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCompiledYaml/__tests__/ExecutionCompiledYaml.test.tsx
> +    )
+ yes, if I am asserting onClose

2022-06-16 14:12 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCompiledYaml/ExecutionCompiledYaml.module.scss
> +  right: 100%;
have reused this styling that's used at 10+ places, good to be extracted to a shared component.

right: 100%; would move component out of relative parent, whereas left:0 starts from inside the parent

2022-06-16 14:21 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCompiledYaml/ExecutionCompiledYaml.module.scss
> +  right: 100%;
the negative left has to take the component width into consideration. I see custom-styled drawer component duplicated several times. We should extract to a share one perhaps

2022-06-16 14:28 UTC, knagurski commented on src/modules/70-pipeline/strings/strings.en.yaml
> +    viewCompiledYaml: View Compiled Yaml
Looks like overall we use `YAML` instead of `Yaml`
```suggestion
    viewCompiledYaml: View Compiled YAML
```

2022-06-16 14:31 UTC, knagurski commented on src/modules/70-pipeline/components/ExecutionCompareYamls/ExecutionCompareContext.tsx
> +export function ExecutionCompareProvider({ children }: { children: ReactNode }): ReactElement {
You can simplify this by using the `FC` type.
```suggestion
export const ExecutionCompareProvider: FC = ({ children }) => {
```

2022-06-16 14:34 UTC, knagurski commented on src/modules/70-pipeline/components/ExecutionCompareYamls/ExecutionCompareContext.tsx
> +      setCompareItems([execution, ...compareItems])
Is there a possibility that `execution` is already in the `compareItems` array? If that's a possibility, you can quickly pass it through a `Set` to de-dupe. If not then 👍🏻

2022-06-16 14:37 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCompareYamls/ExecutionCompareContext.tsx
> +export function ExecutionCompareProvider({ children }: { children: ReactNode }): ReactElement {
I like FC, but I see we have a eslint rule that restricts FC arrow components

2022-06-16 14:54 UTC, kapilkumawat86 requested changes

2022-06-16 14:54 UTC, kapilkumawat86 commented on configs/devServerProxy.config.js
> +const baseUrl = 'https://pr.harness.io/pie-2382-exyaml'
don't checkin this change

2022-06-16 14:56 UTC, udayvunnam commented on configs/devServerProxy.config.js
> +const baseUrl = 'https://pr.harness.io/pie-2382-exyaml'
mistakenly, changing back

2022-06-16 14:57 UTC, udayvunnam commented
Please ignore this PR, I have messed up committing multiple files in progress, raising a new one

2022-06-16 14:57 UTC, closed without merging

2022-06-16 15:45 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCompareYamls/ExecutionCompareContext.tsx
> +export function ExecutionCompareProvider({ children }: { children: ReactNode }): ReactElement {
FC latest removed children type, we have to type it explicitely

2022-06-16 15:46 UTC, udayvunnam commented on src/modules/70-pipeline/components/ExecutionCompareYamls/ExecutionCompareContext.tsx
> +      setCompareItems([execution, ...compareItems])
yes, execution can't be sent if already in state