feat: [PIE-3671]: RepoBranchSelectV2 unit test
harness/harness-core-ui pull request #9495
Opened 2022-06-16 13:08 UTC by depanshu-dhiman

##### Summary:
Test cases for common component RepoBranchSelectV2

##### Jira Links:
https://harness.atlassian.net/browse/PIE-3671

##### Screenshots:

<img width="1090" alt="Screenshot 2022-06-16 at 6 36 50 PM" src="https://user-images.githubusercontent.com/101629876/174076487-db190317-53c4-44a0-bd19-5f111e8e06e1.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-16 14:07 UTC, udayvunnam commented on src/modules/10-common/components/RepoBranchSelectV2/__tests__/RepoBranchSelectV2.test.tsx
> +    const errorDialogHeading = document.querySelector('.bp3-portal .bp3-heading') as HTMLHeadingElement
hard to refactor later

2022-06-20 04:56 UTC, chetanvekariya-harness requested changes

2022-06-20 04:56 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepoBranchSelectV2/__tests__/RepoBranchSelectV2.test.tsx
> +    const errorDialogHeading = document.querySelector('.bp3-portal .bp3-heading') as HTMLHeadingElement
Let's use getByText

2022-06-20 04:56 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepoBranchSelectV2/__tests__/RepoBranchSelectV2.test.tsx
> +jest.mock('@harness/uicore', () => ({
Why is this one ? This should not be needed. We should never mock components which are rendered as part of the target component.

2022-06-20 10:26 UTC, depanshu-dhiman commented on src/modules/10-common/components/RepoBranchSelectV2/__tests__/RepoBranchSelectV2.test.tsx
> +jest.mock('@harness/uicore', () => ({
This is needed because I have to test whether our error experience in modal works or not. In RepoBranchSelectV2 we render a Dialog component and show only if isOpen is true and showErrorInModal is true. To test that, this is required.

2022-06-20 10:35 UTC, depanshu-dhiman commented on src/modules/10-common/components/RepoBranchSelectV2/__tests__/RepoBranchSelectV2.test.tsx
> +    const errorDialogHeading = document.querySelector('.bp3-portal .bp3-heading') as HTMLHeadingElement
done

2022-06-20 12:48 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepoBranchSelectV2/__tests__/RepoBranchSelectV2.test.tsx
> +jest.mock('@harness/uicore', () => ({
Okay, then you don't need to mock it. It will work without mocking. If it does not work then there is mistake in the code.

2022-06-20 12:50 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepoBranchSelectV2/__tests__/RepoBranchSelectV2.test.tsx
> +jest.mock('@harness/uicore', () => ({
Check this PR - https://github.com/harness/harness-core-ui/pull/9497/files
In that PR, I am removing some hooks which were mocked and things are still working. Mocking components which gets rendered as a part of your components give impressions that everything is working fine while things could be breaking.

2022-06-22 09:51 UTC, chetanvekariya-harness approved these changes

2022-06-22 10:13 UTC, sunnykesh-harness approved these changes

2022-06-22 10:28 UTC, depanshu-dhiman commented
trigger cypress

2022-06-22 11:14 UTC, merged