feat: [CDS-38231]: added releaserepo wizard
harness/harness-core-ui pull request #9509
Opened 2022-06-17 00:02 UTC by sahithikolichala

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-17 06:12 UTC, tan-nhu submitted a review, later dismissed

2022-06-17 06:12 UTC, tan-nhu commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/ReleaseRepoWizard.tsx
> +        name="Release Repo Store"
Use useStrings()

2022-06-17 12:08 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/RepoStore.tsx
> +  // manifestStoreTypes: Array<ManifestStores>
Commented code?

2022-06-17 12:08 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/RepoStore.tsx
> +            is: !ManifestStoreMap.InheritFromManifest,
This is not needed

2022-06-17 12:09 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/RepoStore.tsx
> +                          MultiTypeInputType.FIXED,
This should be read from pipeline context

2022-06-17 12:12 UTC, bhavya-sinha commented
We also need list view as for repo release. Please add that

2022-06-17 12:15 UTC, bhavya-sinha requested changes

2022-06-17 12:15 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/RepoDetails.tsx
> +  branch: string | undefined
This can be made optional

2022-06-17 12:15 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/RepoDetails.tsx
> +  commitId: string | undefined
same

2022-06-17 12:15 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/RepoStore.tsx
> +                        disabled={isReadonly || !canCreate}
Use Rbac button

2022-06-17 12:15 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/ReleaseRepoWizard.tsx
> +export default ReleaseRepoWizard
Please add list view as well

2022-06-17 14:08 UTC, sahithikolichala commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/RepoStore.tsx
> +                        disabled={isReadonly || !canCreate}
it is the same in manifeststore https://github.com/harness/harness-core-ui/blob/develop/src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/ManifestStore.tsx#L253

2022-06-17 14:09 UTC, sahithikolichala commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/ReleaseRepoWizard.tsx
> +export default ReleaseRepoWizard
as discussed will add later

2022-06-17 16:35 UTC, cjlee01 approved these changes

2022-06-17 19:05 UTC, sahithikolichala commented
retrigger sonar

2022-06-18 00:49 UTC, tan-nhu approved these changes

2022-06-18 11:33 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/__tests__/ReleaseRepoWizard.test.tsx
> +    // fireEvent.click(gcrHostname)
Remove commented code

2022-06-18 11:33 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/__tests__/ReleaseRepoWizard.test.tsx
> +    //   connectorId: 'connectorId'
Remove commented code

2022-06-18 11:33 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/__tests__/ReleaseRepoWizard.test.tsx
> +    //   connectorId: 'connectorId'
here too

2022-06-18 11:33 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ReleaseRepoWizard/__tests__/ReleaseRepoWizard.test.tsx
> +
here

2022-06-18 15:37 UTC, bhavya-sinha approved these changes

2022-06-19 01:33 UTC, merged