feat: [PIE-3671]: Test case for common component RepositorySelect
harness/harness-core-ui pull request #9538
Opened 2022-06-20 10:50 UTC by depanshu-dhiman

##### Summary:
Test cases for common component RepositorySelect

##### Jira Links:
https://harness.atlassian.net/browse/PIE-3671

##### Screenshots:
<img width="1084" alt="Screenshot 2022-06-20 at 4 17 43 PM" src="https://user-images.githubusercontent.com/101629876/174585832-c6b763bb-204f-402d-ad29-3274fddfd8b6.png">

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-20 13:03 UTC, chetanvekariya-harness requested changes

2022-06-20 13:03 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepositorySelect/__tests__/RepositorySelect.test.tsx
> +      <TestWrapper path={testPath} pathParams={pathParams}>
Same as above.

2022-06-20 13:03 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepositorySelect/__tests__/RepositorySelect.test.tsx
> +      <TestWrapper path={testPath} pathParams={pathParams}>
Same as above.

2022-06-20 13:03 UTC, chetanvekariya-harness commented on src/modules/10-common/components/RepositorySelect/__tests__/RepositorySelect.test.tsx
> +    ;(useGetListOfReposByRefConnector as jest.Mock).mockImplementation(() => {
Write this in separate test case

2022-06-22 09:17 UTC, depanshu-dhiman commented on src/modules/10-common/components/RepositorySelect/__tests__/RepositorySelect.test.tsx
> +      <TestWrapper path={testPath} pathParams={pathParams}>
I have tried to remove it. But the component relies on `useParams` and we can either mock `useParams` or use `TestWrapper`. 
I was able to remove `Formik`. But `TestWrapper` seems mandatory

2022-06-22 09:19 UTC, depanshu-dhiman commented on src/modules/10-common/components/RepositorySelect/__tests__/RepositorySelect.test.tsx
> +    ;(useGetListOfReposByRefConnector as jest.Mock).mockImplementation(() => {
done

2022-06-22 09:23 UTC, chetanvekariya-harness approved these changes

2022-06-22 10:12 UTC, sunnykesh-harness approved these changes

2022-06-22 10:28 UTC, merged