fix: [CDS-38231]: integrated repowizard with checkbox
harness/harness-core-ui pull request #9552
Opened 2022-06-20 17:25 UTC by sahithikolichala

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-20 19:52 UTC, bhavya-sinha requested changes

2022-06-20 19:52 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestSelection.tsx
> +      {!(pipeline as any).gitOpsEnabled ? (
Use proper type

2022-06-20 19:52 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/DeployServiceDefinition/DeployServiceDefinition.tsx
> +            //GitOps checkbox is disabled temporarily until Release repo manifest is added
You can remove this now

2022-06-21 03:17 UTC, bhavya-sinha approved these changes

2022-06-21 04:59 UTC, bhavya-sinha commented
retrigger jest

2022-06-21 05:45 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestSelection.tsx
> +      /* istanbul ignore next */
Do we need both?

2022-06-21 05:46 UTC, AshwinBhatkal-Harness approved these changes

2022-06-21 05:47 UTC, AshwinBhatkal-Harness commented on src/modules/70-pipeline/components/ManifestSelection/ManifestSelection.tsx
> +      /* istanbul ignore next */
You can remove this in your PR. LGTM

2022-06-21 05:52 UTC, merged