feat: [SRM-10747]: As a Harness CI/NG customer, I want to be able tur…
harness/harness-core-ui pull request #9590
Opened 2022-06-21 20:05 UTC by angelo-m-rodriguez

…n on Error Tracking in the Run Tests step in the Build Stage

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-22 03:00 UTC, DFieldFL requested changes

2022-06-22 20:35 UTC, DFieldFL submitted a review, later dismissed

2022-06-22 20:51 UTC, mtran7 commented on src/modules/75-ci/components/PipelineSteps/RunTestsStep/RunTestsStepBase.tsx
> +            {ERROR_TRACKING_ENABLED && (formik.values?.spec?.language as any)?.value === Language.Java && (
can use `selectedLanguageValue`

2022-06-22 20:55 UTC, mtran7 commented on src/modules/75-ci/components/PipelineSteps/RunTestsStep/RunTestsStepBase.tsx
> +                  selectedValue={isErrorTrackingCurrentlyOn ? 'yes' : 'no'}
can you create an enum for yes/no. 

Ex. isErrorTrackingCurrentlyOn ? ErrorTrackingOn.YES : ErrorTrackingOn.No

2022-06-22 21:03 UTC, mtran7 commented on src/modules/75-ci/components/PipelineSteps/RunTestsStep/RunTestsStepBase.tsx
> +                <Text font={{ size: 'small' }}>{getString('ci.runTestsErrorTrackingSetupText')}</Text>
Add a ui anchor here so Docs can provide a tooltip on what "Error Tracking" is.

https://harness.atlassian.net/wiki/spaces/CDNG/pages/1626144816/NG+Tooltip+Framework+-+self+help+guide+for+docs

2022-06-23 01:14 UTC, DFieldFL submitted a review, later dismissed

2022-06-23 12:30 UTC, angelo-m-rodriguez commented on src/modules/75-ci/components/PipelineSteps/RunTestsStep/RunTestsStepBase.tsx
> +            {ERROR_TRACKING_ENABLED && (formik.values?.spec?.language as any)?.value === Language.Java && (
Made use of selectedLanguageValue

2022-06-23 12:33 UTC, angelo-m-rodriguez commented on src/modules/75-ci/components/PipelineSteps/RunTestsStep/RunTestsStepBase.tsx
> +        const isErrorTrackingCurrentlyOn =
Move from onChange into method called getUpdatedPreCommand and referenced method inside onChange

2022-06-23 12:34 UTC, angelo-m-rodriguez commented on src/modules/75-ci/components/PipelineSteps/RunTestsStep/RunTestsStepBase.tsx
> +                <Text font={{ size: 'small' }}>{getString('ci.runTestsErrorTrackingSetupText')}</Text>
Added dataTooltipId to tooltipProps

2022-06-23 12:37 UTC, angelo-m-rodriguez commented on src/modules/75-ci/components/PipelineSteps/RunTestsStep/RunTestsStepBase.tsx
> +                    const turnErrorTrackingOn = e.currentTarget.value === 'yes'
Replaced reference to hardcoded strings with reference to newly created ErrorTrackingStatus enum

2022-06-23 13:08 UTC, DFieldFL approved these changes
🥇

2022-06-23 17:14 UTC, angelo-m-rodriguez commented
retrigger titlecheck

2022-06-23 17:42 UTC, DFieldFL approved these changes

2022-06-23 17:50 UTC, DFieldFL commented
trigger cypress

2022-06-23 18:21 UTC, DFieldFL commented
trigger cypress

2022-06-23 19:02 UTC, DFieldFL commented
trigger cypress

2022-06-23 20:00 UTC, DFieldFL commented
retrigger jest

2022-06-23 20:27 UTC, merged