fix: [CDS-37814]: fixed the exec strategy for gitops
harness/harness-core-ui pull request #9650
Opened 2022-06-24 18:53 UTC by sahithikolichala

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-25 03:33 UTC, bhavya-sinha requested changes

2022-06-25 03:33 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineStudio/DeployStageSetupShell/DeployStageSetupShell.tsx
> +const getStrategyType = (selectedStage: any, selectedDeploymentType: any): any => {
We have proper types for These. Please use them

2022-06-25 03:33 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineStudio/DeployStageSetupShell/DeployStageSetupShell.tsx
> +  const selectedDeploymentType = isNewServiceEnvEntity(NG_SVC_ENV_REDESIGN, selectedStage as any)
Use proper type for selectedStage

2022-06-25 03:33 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineStudio/DeployStageSetupShell/DeployStageSetupShell.tsx
> +    ? (selectedStage?.stage?.spec as any)?.deploymentType
Here also

2022-06-25 03:33 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineStudio/DeployStageSetupShell/DeployStageSetupShell.tsx
> +      strategyType: getStrategyType(selectedStage, selectedDeploymentType)
Here. We have exposed a new type `DeployStageConfig` in `src/modules/70-pipeline/utils/DeployStageInterface.ts` You can use that

2022-06-25 04:50 UTC, chetanvekariya-harness submitted a review, later dismissed
Changes seem fine regarding execution strategies panel not to be opened when git ops is enabled.

2022-06-25 04:56 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployStageSetupShell/DeployStageSetupShell.tsx
> +      serviceDefinitionType: selectedDeploymentType || (selectedStage?.stage?.spec as any)?.deploymentType,
If selectedDeploymentType could be null / undefined then value of `selectedStage?.stage?.spec as any)?.deploymentType` must also be undefined.
So, I wanted to ask if this `||` condition is required ?

2022-06-25 04:58 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineStudio/DeployStageSetupShell/DeployStageSetupShell.tsx
>            // Show executiomn strategies when openExecutionStrategy is true and deployment type is not serverless
This comment becomes outdated now
`// Show executiomn strategies when openExecutionStrategy is true and deployment type is not serverless`

You may update comment as you have added one more check now. Will be great if we can take this condition into some function where we can keep adding more conditions as required.

2022-06-27 03:42 UTC, bhavya-sinha approved these changes

2022-06-27 14:23 UTC, vkbansal approved these changes

2022-06-27 14:24 UTC, merged