feat: [CDS-37906]: replaced localtime with UTC time on CDOveriew cards footer (onhover tooltip)
harness/harness-core-ui pull request #9659
Opened 2022-06-26 14:09 UTC by Sagar-Rajput7

##### Summary:

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-27 01:16 UTC, Sagar-Rajput7 commented
retrigger titlecheck

2022-07-14 04:30 UTC, satyam-harness approved these changes

2022-07-14 04:31 UTC, vkbansal approved these changes

2022-07-14 04:37 UTC, udayvunnam requested changes
Providing two dates here is confusing for all other places whether its a UTC or LOCAL. Isn't fix to be made on deployment dashboard where we show LOCAL time?

2022-07-14 04:48 UTC, udayvunnam approved these changes

2022-07-14 04:53 UTC, merged