fix: [PIE-4270]: serverless testcases fixed
harness/harness-core-ui pull request #9684
Opened 2022-06-27 13:06 UTC by satyam-harness

##### Summary:

##### Jira Links:
https://harness.atlassian.net/browse/PIE-4270

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-27 13:33 UTC, Sagar-Rajput7 submitted a review, later dismissed

2022-06-28 04:44 UTC, chetanvekariya-harness reviewed
I think snapshot should have changed for this change. Earlier component was not rendering and now it is getting rendered then snapshot should change.

2022-06-28 04:46 UTC, chetanvekariya-harness requested changes

2022-06-28 04:46 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAwsLambdaServiceSpec/__tests__/ServerlessAwsLambdaServiceSpec.test.tsx
> +  useGetBuildDetailsForArtifactoryArtifactWithYaml: jest.fn().mockReturnValue({
This is response type of this call - `ArtifactoryResponseDTO`. Please check data type and mock response properly.

2022-06-28 06:39 UTC, satyam-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAwsLambdaServiceSpec/__tests__/ServerlessAwsLambdaServiceSpec.test.tsx
> +  useGetBuildDetailsForArtifactoryArtifactWithYaml: jest.fn().mockReturnValue({
addressed

2022-06-28 06:49 UTC, satyam-harness commented
retrigger build

2022-06-28 06:53 UTC, satyam-harness commented
retrigger build

2022-06-28 07:39 UTC, satyam-harness commented
retrigger build

2022-06-28 08:31 UTC, chetanvekariya-harness requested changes

2022-06-28 08:31 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAwsLambdaServiceSpec/__tests__/__snapshots__/ServerlessAwsLambdaServiceSpec.test.tsx.snap
> +      Errors
Could you please check why this is appearing ?

2022-06-28 08:31 UTC, chetanvekariya-harness commented on src/modules/75-cd/components/PipelineSteps/ServerlessAwsLambdaServiceSpec/__tests__/__snapshots__/ServerlessAwsLambdaServiceSpec.test.tsx.snap
> +                      value=""
After this, field for artifactPathFilter should appear as well.

2022-07-11 05:01 UTC, closed without merging