fix: [CI-4859]: Misc. fixes for CIE Hosted Builds
harness/harness-core-ui pull request #9691
Opened 2022-06-28 04:39 UTC by vardanbansal-harness

##### Summary:

1. Handling test connection failure.

<img width="865" alt="image" src="https://user-images.githubusercontent.com/48940704/176094009-42f41768-d3cc-4c64-907a-a55cf733a2f4.png">

2. Adding doc links for Access Token permissions required.

<img width="865" alt="image" src="https://user-images.githubusercontent.com/48940704/176094160-b6531ed4-e393-4967-881a-5c34eb756087.png">

3. Force failing OAuth if not completed within 5 mins. from initiation.

##### Jira Links:

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

2022-06-28 12:44 UTC, d1wilko requested changes
just 1 suggestion :)

2022-06-28 17:47 UTC, vardanbansal-harness commented on src/modules/75-ci/pages/get-started-with-ci/InfraProvisioningWizard/SelectGitProvider.tsx
> +  }, [])
Done.

2022-06-29 06:22 UTC, avinashmadhwani02 approved these changes

2022-06-29 08:41 UTC, d1wilko approved these changes

2022-06-29 09:18 UTC, merged