feat: pipeline list ui changes with refactoring
harness/harness-core-ui pull request #9824
Opened 2022-07-05 14:10 UTC by udayvunnam

### Summary

- pipeline list UI new design
- added a temporary route that allows pushing code and comparing with the old design (this will be changed once BE changes are integrated)
- Use mock data for a few columns
- Refactoring hopefully without regressions :)

TODO:
- Backend integration once API is ready
- remove the grid layout
- Tests will be reused from the current pipeline view and change wherever necessary

#### Screenshots

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/20707504/177347392-c52f5e06-11cf-4ce5-ac95-a084de2a2439.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-05 14:13 UTC, udayvunnam commented
retrigger titlecheck

2022-07-05 14:16 UTC, udayvunnam commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx
> +  const { mutate: deletePipeline, loading: isDeletingPipeline } = useSoftDeletePipeline({
used loading from hook instead of additional state, this was redundant earlier at several places

2022-07-06 05:53 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/pages/pipeline-list/ClonePipeline/ClonePipeline.tsx
> +
Is it possible to show spinner before we start cloning pipeline ?
These loader issues later come up as bugs / enhancement. Better to do it now itself.

2022-07-06 05:53 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx
> +      getDefaultFromOtherRepo: filter.getDefaultFromOtherRepo || undefined,
This should not go into URL. Was it already there ? 
I see it was there and the change was made by Satyam. It was wrong change. 
Let's fix it now.

2022-07-06 05:53 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListUtils.ts
> +    branch: pipeline?.gitDetails?.branch,
From this line to till end, all are query params, Hope that all of these are not considered path params.

2022-07-06 05:53 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx
> +          {createPipeline}
Can we keep name as **createPipelineButton** ? Or use component directly here.

2022-07-06 05:58 UTC, satyam-harness commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx
> +      getDefaultFromOtherRepo: filter.getDefaultFromOtherRepo || undefined,
which change? @chetanvekariya-harness

2022-07-06 06:03 UTC, udayvunnam commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx
> +      getDefaultFromOtherRepo: filter.getDefaultFromOtherRepo || undefined,
Why shouldn't this go to the URL, is there a criteria?

2022-07-06 06:04 UTC, udayvunnam commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx
> +          {createPipeline}
component reused at two places, will make it `createPipelineButton`

2022-07-06 06:08 UTC, vkbansal requested changes

2022-07-06 06:08 UTC, vkbansal commented on src/modules/70-pipeline/pages/pipeline-list/ClonePipeline/ClonePipeline.tsx
> +import React from 'react'
Why can't we reuse the existing form? Why copy it?

2022-07-06 06:13 UTC, udayvunnam commented on src/modules/70-pipeline/pages/pipeline-list/ClonePipeline/ClonePipeline.tsx
> +import React from 'react'
Component name changed and kept it isolated within pipeline-list, I will revert to use from the existing one.

2022-07-06 06:19 UTC, udayvunnam commented on src/modules/70-pipeline/pages/pipeline-list/PipelineListUtils.ts
> +    branch: pipeline?.gitDetails?.branch,
They are parsed as queryparams, This was existing code extracted to a function. If these queryparams are not used in the pipelineStudio, pipeline details pages we can remove the below items.
```
    repoIdentifier: pipeline?.gitDetails?.repoIdentifier,
    repoName: pipeline?.gitDetails?.repoName,
    connectorRef: pipeline?.connectorRef,
    storeType: pipeline?.storeType as StoreType
```

cc: @vkbansal

2022-07-06 07:28 UTC, udayvunnam commented on src/modules/70-pipeline/pages/pipeline-list/ClonePipeline/ClonePipeline.tsx
> +
This was existing behavior though, we can change this

2022-07-06 10:34 UTC, chetanvekariya-harness commented on src/modules/70-pipeline/pages/pipeline-list/ClonePipeline/ClonePipeline.tsx
> +
Yup, good to improve it as we have got chance to revisit the code.

2022-07-06 11:02 UTC, merged