Azure web app common
harness/harness-core-ui pull request #9909
Opened 2022-07-08 07:29 UTC by Tamaraius

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-09 06:51 UTC, YounixIO commented
retrigger titlecheck

2022-07-13 11:25 UTC, bhavya-sinha requested changes

2022-07-13 11:25 UTC, bhavya-sinha commented on src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
> +  setConnector?: any
Why is this any?

2022-07-13 11:25 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactHelper.ts
> +      deploymentType === ServiceDeploymentType.AzureWebApp)
No need to add additional function. Just add `deploymentType === ServiceDeploymentType.AzureWebApp` in `isAdditionAllowed`

2022-07-13 11:25 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactHelper.ts
> +export const isSidecarAllowed = (deploymentType: ServiceDefinition['type'], isReadOnly: boolean): boolean => {
Remove this func

2022-07-13 11:25 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactListView/ArtifactListView.tsx
> +        {isAdditionAllowed && isSidecarAllowed && (
Update this condition

2022-07-13 11:25 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactsSelection.tsx
> +      isAllowedACRArtifactDeploymentTypes(deploymentType)
Please use the old function, as this is not just ACR specific

2022-07-13 11:25 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ArtifactsSelection/ArtifactHelper.ts
> +export const isAllowedACRArtifactDeploymentTypes = (deploymentType: ServiceDefinition['type']): boolean => {
This function is not needed

2022-07-13 11:25 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestInterface.ts
> +  ConnectorConfigDTO,
Why is this added back?

2022-07-13 11:25 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestInterface.ts
> +  ConnectorConfigDTO,
Revert this file changes

2022-07-13 11:30 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecEditable.tsx
> +    if (getValue(connectorValue)?.length) {
Can be written like return `!getValue(connectorValue)?.length`

2022-07-13 11:30 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecEditable.tsx
> +      return false
same as above

2022-07-13 11:31 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecEditable.tsx
> +      tab: DeployTabs.INFRASTRUCTURE,
Why is this `subscribeForm` needed?

2022-07-13 11:31 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecEditable.tsx
> +            connectorRef: undefined,
Extract this to separate function. It's not readable

2022-07-13 11:32 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecEditable.tsx
> +                    if (type !== MultiTypeInputType.FIXED) {
Extract this out

2022-07-13 11:32 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecEditable.tsx
> +                      getMultiTypeFromValue(formik.values?.resourceGroup) !== MultiTypeInputType.RUNTIME &&
Extract this

2022-07-13 11:54 UTC, YounixIO commented on src/modules/70-pipeline/components/ManifestSelection/ManifestInterface.ts
> +  ConnectorConfigDTO,
This is the current change on develop branch.

2022-07-13 11:55 UTC, YounixIO commented on src/modules/70-pipeline/components/ManifestSelection/ManifestInterface.ts
> +  ConnectorConfigDTO,
https://github.com/harness/harness-core-ui/blob/develop/src/modules/70-pipeline/components/ManifestSelection/ManifestInterface.ts

2022-07-13 11:57 UTC, YounixIO commented on src/modules/70-pipeline/components/ManifestSelection/ManifestInterface.ts
> +  ConnectorConfigDTO,
<img width="1438" alt="Screenshot 2022-07-13 at 5 26 34 PM" src="https://user-images.githubusercontent.com/71430923/178728216-7d9176bd-d80f-40c9-9379-adf441a08085.png">

2022-07-13 12:13 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecInputForm.tsx
> +                initialValues.connectorRef !== '<+input>' &&
This is not readable. Please move this to function

2022-07-13 12:19 UTC, bhavya-sinha commented on src/modules/70-pipeline/utils/stageHelpers.ts
> +    return StepType.AzureWebAppServiceSpec
Why is this done?

2022-07-13 12:26 UTC, YounixIO commented on src/modules/70-pipeline/utils/stageHelpers.ts
> +    return StepType.AzureWebAppServiceSpec
We wanted to have all the AzureWebApp service related changes into a separate service file as Kuberentes service file was getting bloated with if else block. Hence the change.

2022-07-13 12:52 UTC, bhavya-sinha commented on src/modules/75-cd/components/PipelineSteps/AzureWebAppServiceSpec/AzureWebAppServiceSpec.tsx
> +          {...(customStepProps as AzureWebAppServiceSpecFormProps)}
` <KubernetesServiceSpecInputSetMode` Use this

2022-07-13 13:17 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ManifestSelection/ManifestInterface.ts
> +  ConnectorConfigDTO,
Looks like the branch is not rebased with develop, else the diff should not be there

2022-07-13 13:40 UTC, bhavya-sinha submitted a review, later dismissed

2022-07-14 10:23 UTC, kapilkumawat86 approved these changes

2022-07-14 12:56 UTC, kapilkumawat86 approved these changes

2022-07-14 13:13 UTC, YounixIO approved these changes

2022-07-14 13:18 UTC, merged