feat: [CDS-38861]: added additional metadata
harness/harness-core-ui pull request #9977
Opened 2022-07-12 13:03 UTC by Sagar-Rajput7

### Summary

#### Screenshots
https://user-images.githubusercontent.com/98325173/178496351-d69a16e1-9605-4c22-a37b-1e4504aceacb.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-12 19:25 UTC, Sagar-Rajput7 commented
retrigger coverage

2022-07-13 03:35 UTC, shamala-harness approved these changes

2022-07-13 06:37 UTC, depanshu-dhiman commented on src/modules/70-pipeline/components/ExecutionCard/ExecutionCard.tsx
> +        window.open(`${baseUrl}#${route}`)
No need to get the baseUrl. Simply use 
`window.open(`#${route}`)`

And if baseUrl is required, try `window.location.origin`

2022-07-13 06:46 UTC, depanshu-dhiman commented on src/modules/70-pipeline/components/ServiceExecutionsCard/ServiceExecutionsCard.tsx
> +            <tr key={`${service.serviceName}-${i}`}>
Avoid indexes in keys. This will degrade the performance if the `services` array is modified.
Just use the `serviceName` or combine it with `serviceTag`

2022-07-13 06:55 UTC, depanshu-dhiman commented on src/modules/70-pipeline/components/ServiceExecutionsCard/ServiceExecutionsCard.tsx
> +                dangerouslySetInnerHTML={{
Why are we using `dangerouslySetInnerHTML`? Let me know the reason please.

2022-07-13 06:58 UTC, depanshu-dhiman commented on src/modules/75-cd/pages/dashboard/DeploymentCards/WorkloadCard.tsx
> +    window.open(`${baseUrl}#${route}`)
Same as above. No need for baseUrl

2022-07-13 06:59 UTC, depanshu-dhiman requested changes
Please address the comments

2022-07-13 10:08 UTC, bhavya-sinha commented on src/modules/70-pipeline/components/ServiceExecutionsCard/ServiceExecutionsCard.tsx
> +          services.map((service, i) => (
You can use optional chaining here instead of `services &&`

2022-07-13 10:12 UTC, bhavya-sinha commented on src/services/cd-ng/index.tsx
> +>
Are these services generated or manually added?

2022-07-13 18:02 UTC, Sagar-Rajput7 commented on src/services/cd-ng/index.tsx
> +>
generated

2022-07-13 18:04 UTC, Sagar-Rajput7 commented on src/modules/70-pipeline/components/ServiceExecutionsCard/ServiceExecutionsCard.tsx
> +            <tr key={`${service.serviceName}-${i}`}>
Here the data is coming updating from BE only and also we dont have any other unique combination here as serviceTag and Image can be empty and serviceName can be duplicate

2022-07-14 05:52 UTC, depanshu-dhiman approved these changes

2022-07-14 05:52 UTC, bhavya-sinha approved these changes

2022-07-14 05:59 UTC, kapilkumawat86 approved these changes

2022-07-14 06:01 UTC, merged