feat: [CDS-39773]: updated icons for pipelines, services and infrastructures
harness/harness-core-ui pull request #9987
Opened 2022-07-13 08:25 UTC by Sagar-Rajput7

### Summary

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-13 08:27 UTC, Sagar-Rajput7 commented
retrigger titlecheck

2022-07-13 09:47 UTC, bhavya-sinha submitted a review, later dismissed

2022-07-13 09:47 UTC, depanshu-dhiman approved these changes

2022-07-13 10:06 UTC, praneshg239 approved these changes

2022-07-13 10:13 UTC, avinashmadhwani02 submitted a review, later dismissed

2022-07-14 04:49 UTC, vkbansal approved these changes

2022-07-14 08:59 UTC, praneshg239 submitted a review, later dismissed

2022-07-14 11:19 UTC, praneshg239 approved these changes

2022-07-14 11:45 UTC, depanshu-dhiman commented on src/modules/45-projects-orgs/components/OverviewGlanceCards/OverviewGlanceCards.tsx
> +          style={{
Use classnames here. Try `!important` if style is not working from classname

2022-07-14 11:46 UTC, depanshu-dhiman commented on src/modules/45-projects-orgs/components/OverviewGlanceCards/OverviewGlanceCards.tsx
> +    <GlanceCard {...data} styling={false} title={getString(data.title)} />
No need to pass false as it will default to false

2022-07-14 11:48 UTC, depanshu-dhiman requested changes
Minor comments

2022-07-14 11:49 UTC, depanshu-dhiman submitted a review, later dismissed

2022-07-14 11:51 UTC, Sagar-Rajput7 commented on src/modules/45-projects-orgs/components/OverviewGlanceCards/OverviewGlanceCards.tsx
> +          style={{
will fix this is another pr that i am raising by EOD

2022-07-14 11:51 UTC, Sagar-Rajput7 commented on src/modules/45-projects-orgs/components/OverviewGlanceCards/OverviewGlanceCards.tsx
> +    <GlanceCard {...data} styling={false} title={getString(data.title)} />
will fix this is another pr that i am raising by EOD

2022-07-14 15:07 UTC, merged