fix: [CDS-39785]: cypress tests added for template references
harness/harness-core-ui pull request #9990
Opened 2022-07-13 09:57 UTC by samarth-sharma31

### Summary

#### Screenshots

<img width="1391" alt="Screenshot 2022-07-13 at 3 09 29 PM" src="https://user-images.githubusercontent.com/96409598/178706730-27d27696-ff12-4bf0-ab2f-794e22135fe1.png">

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

2022-07-13 10:07 UTC, samarth-sharma31 commented
retrigger titlecheck

2022-07-13 10:50 UTC, diptiman-adak commented
retrigger sonar

2022-07-13 10:59 UTC, diptiman-adak commented
retrigger sonar

2022-07-13 11:19 UTC, depanshu-dhiman commented on cypress/integration/72-templates-library/TemplateReferenceBy.spec.ts
> +    const templatesListCall =
Move to constants

2022-07-13 11:21 UTC, depanshu-dhiman commented on cypress/integration/72-templates-library/TemplateReferenceBy.spec.ts
> +        cy.intercept('POST', '/template/api/templates/list?routingId=accountId&accountIdentifier=px7xd_BFRCi-pfWPYXVjvw&orgIdentifier=default&projectIdentifier=Kapil&templateListType=All&module=cd',
Extract url in variable

2022-07-13 11:22 UTC, depanshu-dhiman requested changes
Minor comments

2022-07-13 20:28 UTC, samarth-sharma31 commented on cypress/integration/72-templates-library/TemplateReferenceBy.spec.ts
> +    const templatesListCall =
done

2022-07-13 20:28 UTC, samarth-sharma31 commented on cypress/integration/72-templates-library/TemplateReferenceBy.spec.ts
> +    const templateReferencesCall =
done

2022-07-13 20:28 UTC, samarth-sharma31 commented on cypress/integration/72-templates-library/TemplateReferenceBy.spec.ts
> +        cy.intercept('POST', '/template/api/templates/list?routingId=accountId&accountIdentifier=px7xd_BFRCi-pfWPYXVjvw&orgIdentifier=default&projectIdentifier=Kapil&templateListType=All&module=cd',
yes, done

2022-07-14 09:05 UTC, depanshu-dhiman approved these changes

2022-07-14 09:35 UTC, samarth-sharma31 commented
retrigger jest

2022-07-14 10:54 UTC, merged